// Locale-independent static page paths for this site (excludes brand hub pages
// and per-item model pages, which are generated dynamically from lib/data.ts).
// Single source of truth shared by app/sitemap.ts and the /guides, /compare,
// /trends hub pages, so the sitemap and the hub listings can never drift apart.
export interface StaticPage {
  path: string
  changeFrequency: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never'
  priority: number
}

export const STATIC_PAGES: StaticPage[] = [
  { path: '', changeFrequency: 'weekly', priority: 1.0 },
  { path: '/handbags', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/watches', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/clothing', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/brands', changeFrequency: 'weekly', priority: 0.8 },
  { path: '/shoes', changeFrequency: 'weekly', priority: 0.8 },
  { path: '/under-15000', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/under-30000', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/under-60000', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/guides/first-luxury-bag', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/value-guide', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/market-overview', changeFrequency: 'weekly', priority: 0.9 },
  { path: '/jewelry', changeFrequency: 'weekly', priority: 0.8 },
  { path: '/belts', changeFrequency: 'weekly', priority: 0.8 },
  { path: '/scarves', changeFrequency: 'weekly', priority: 0.8 },
  { path: '/small-leather-goods', changeFrequency: 'weekly', priority: 0.8 },
  { path: '/compare/lv-vs-gucci', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/chanel-vs-lv', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/rolex-vs-omega', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/luxury-gift-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/best-bags-for-travel', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/best-bags-for-work', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/trends/quiet-luxury-2025', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/brands/dior', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/brands/bottega-veneta', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/brands/prada', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/dior-vs-chanel', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/prada-vs-gucci', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/bottega-vs-loewe', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/brands/celine', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/brands/hermes', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/brands/gucci', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/brands/louis-vuitton', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/guides/luxury-bags-as-investments', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/where-to-sell-luxury-bags', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/how-to-spot-fake-luxury-bags', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/hermes-vs-bottega', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/chanel-vs-hermes', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/brands/chanel', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/brands/saint-laurent', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/brands/cartier', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/brands/rolex', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/brands/omega', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/brands/patek-philippe', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/cartier-vs-van-cleef', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/rolex-vs-audemars-piguet', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/saint-laurent-vs-celine', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/how-to-care-for-luxury-bags', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/brands/audemars-piguet', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/chanel-vs-dior', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/rolex-vs-patek-philippe', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/brands/fendi', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/brands/loewe', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/hermes-vs-louis-vuitton', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/pre-owned-watches-buying-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/trends/thai-luxury-market-2025', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/bangkok-luxury-shopping-guide', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/guides/rolex-reference-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/chanel-size-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/fendi-vs-loewe', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/trends/best-bags-to-gift-2025', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/chanel-price-history', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/compare/cartier-vs-bulgari', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/brands/balenciaga', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/brands/valentino', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/omega-vs-tag-heuer', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/saint-laurent-vs-dior', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/authentication-basics', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/brands/miu-miu', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/trends/luxury-above-retail', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/trends/watch-buying-guide-thailand', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/compare/chanel-vs-bottega-veneta', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/pre-owned-vs-new-luxury', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/compare/prada-vs-miu-miu', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/hermes-birkin-vs-kelly', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/compare/ap-vs-patek-philippe', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/lv-neverfull-size-guide', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/trends/resale-value-drops-to-avoid', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/dior-vs-celine', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/brands/bulgari', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/chanel-classic-vs-boy', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/brands/van-cleef', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/gucci-dionysus-vs-marmont', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/lv-vs-celine', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/trends/quiet-luxury-watch-brands-2025', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/how-to-authenticate-bottega-veneta', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/brands/goyard', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/how-to-authenticate-chanel', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/guides/how-to-authenticate-louis-vuitton', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/guides/how-to-authenticate-hermes', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/guides/how-to-authenticate-rolex', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/compare/hermes-vs-goyard', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/lv-vs-goyard', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/cartier-vs-tiffany', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/balenciaga-vs-valentino', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/lv-monogram-vs-damier', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/most-iconic-bags-to-buy-used', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/guides/lv-speedy-size-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/hermes-bag-size-guide', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/guides/luxury-condition-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/saint-laurent-vs-gucci', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/how-to-authenticate-gucci', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/guides/how-to-authenticate-dior', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/guides/how-to-authenticate-cartier', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/guides/patek-philippe-nautilus-guide', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/guides/luxury-jewelry-buying-guide', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/brands/givenchy', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/trends/most-valuable-pre-owned-bags-2025', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/trends/y2k-luxury-bags-2025', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/omega-seamaster-buying-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/chanel-vs-gucci', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/compare/chanel-vs-saint-laurent', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/brands/tag-heuer', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/dior-vs-louis-vuitton', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/cartier-love-bracelet-guide', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/trends/chanel-price-increase-2025', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/guides/how-to-buy-pre-owned-luxury-online', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/compare/fendi-vs-dior', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/rolex-submariner-buying-guide', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/trends/hermes-birkin-waitlist-2025', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/guides/how-to-authenticate-prada', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/gucci-vs-bottega-veneta', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/hermes-vs-dior', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/guides/how-to-authenticate-celine', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/lv-vs-prada', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/chanel-mini-vs-small-flap', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/compare/chanel-vs-celine', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/how-to-authenticate-saint-laurent', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/trends/luxury-resale-platforms-2025', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/compare/dior-vs-gucci', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/trends/louis-vuitton-price-increase-2025', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/compare/prada-vs-bottega-veneta', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/how-to-authenticate-balenciaga', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/best-luxury-bags-under-3000', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/compare/rolex-vs-cartier', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/how-to-authenticate-van-cleef', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/trends/dior-saddle-bag-comeback-2025', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/compare/kelly-vs-birkin', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/tiffany-vs-van-cleef', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/loewe-vs-celine', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/chanel-classic-flap-vs-2-55', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/compare/omega-vs-iwc', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/trends/hermes-birkin-price-increase-2025', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/guides/lv-neverfull-vs-onthego', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/dior-vs-valentino', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/best-pre-owned-watches-under-5000', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/trends/phoebe-philo-effect-2025', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/trends/best-luxury-bags-to-invest-2026', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/guides/best-pre-owned-watches-for-beginners', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/guides/how-to-authenticate-bulgari', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/fendi-vs-valentino', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/rolex-vs-tudor', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/how-to-authenticate-omega', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/trends/miu-miu-rise-2025', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/compare/jacquemus-vs-loewe', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/how-to-authenticate-tag-heuer', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/trends/cartier-tank-vs-santos-2025', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/trends/gen-z-luxury-trends-2025', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/compare/omega-seamaster-vs-constellation', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/lv-pochette-vs-felicie', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/compare/bottega-veneta-vs-celine', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/chanel-19-vs-classic-flap', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/guides/how-to-authenticate-fendi', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/lv-speedy-vs-neverfull', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/compare/saint-laurent-vs-valentino', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/lv-alma-vs-speedy', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/compare/hermes-constance-vs-kelly', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/guides/how-to-authenticate-valentino', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/trends/rolex-daytona-investment-2025', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/guides/how-to-authenticate-loewe', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/guides/how-to-authenticate-miu-miu', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/compare/fendi-vs-gucci', changeFrequency: 'monthly', priority: 0.8 },
  { path: '/trends/patek-philippe-nautilus-investment-2025', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/compare/ap-royal-oak-vs-nautilus', changeFrequency: 'monthly', priority: 0.9 },
  { path: '/${brand.slug}', changeFrequency: 'weekly', priority: 0.7 },
]

function section(prefix: string): StaticPage[] {
  return STATIC_PAGES.filter(p => p.path.startsWith(prefix))
}

export function getGuidePages(): StaticPage[] {
  return section('/guides/')
}

export function getComparePages(): StaticPage[] {
  return section('/compare/')
}

export function getTrendPages(): StaticPage[] {
  return section('/trends/')
}

// Turn "how-to-authenticate-chanel" into "How To Authenticate Chanel", with a
// small dictionary of brand/model abbreviations that should stay uppercase
// instead of being title-cased letter by letter.
const ACRONYMS: Record<string, string> = {
  lv: 'LV',
  ap: 'AP',
  tag: 'TAG',
  gg: 'GG',
  th: 'TH',
  '2': '2',
}

export function humanizeSlug(path: string): string {
  const lastSegment = path.split('/').filter(Boolean).pop() ?? path
  return lastSegment
    .split('-')
    .map(word => ACRONYMS[word] ?? (word.charAt(0).toUpperCase() + word.slice(1)))
    .join(' ')
}
