# -*- coding: utf-8 -*-
"""
apply_hospital_redirects.py — reconcile web/lib/hospital-redirects.ts with the
hospitals that now exist.

Run after import_scraped_hospitals.py --apply and export_to_json.py.

Three things have to stay true at once, and doing them by hand is how a
restored hospital ends up invisible:

  1. A slug that is now a real page must NOT appear in MOVED_TO_GUIDE. The
     redirect runs in middleware, before routing, so it wins over the page and
     the restoration is silently undone.
  2. A searched-for slug whose hospital landed under a different name belongs
     in RENAMED_HOSPITALS, pointing at the real slug.
  3. Everything still missing stays in MOVED_TO_GUIDE untouched.

The file is rewritten from the current database plus redirects.generated.json,
so it is always consistent with what is actually deployable.
"""

from __future__ import annotations

import json
import pathlib
import sys

import pymysql
from pymysql.cursors import DictCursor

from config import DB_CONFIG

HERE = pathlib.Path(__file__).parent
TS = HERE / "web" / "lib" / "hospital-redirects.ts"
GENERATED = HERE / "redirects.generated.json"

HEADER = '''/**
 * Hospital URLs Google still has indexed that no longer resolve.
 *
 * Search Console's 2026-08-25 export lists 211 distinct /:locale/hospital/:slug
 * URLs, and only 62 of them were still a page: the 2026-08 catalogue rebuild
 * dropped every hospital without a priced package, and each dropped slug became
 * a hard 404 carrying real traffic — 74 clicks and 4,894 impressions a quarter,
 * about a third of the site's clicks.
 *
 * The two maps below are different problems and are deliberately not merged.
 *
 * RENAMED_HOSPITALS is a true 1:1: the same business, a different slug. Most
 * are the HDmall catalogue, which `hdmall_insert.py` re-created with an "hdm-"
 * prefix so the indexed slug lost its page while the hospital stayed on the
 * site. The rest come from re-scraping, where the name we searched for turned
 * out to differ from the hospital's real name — several of those searched
 * names were invented by the old city guides, and Google Maps answered with
 * the real hospital nearby. These 308 to identical content.
 *
 * MOVED_TO_GUIDE is a fallback, not an equivalence: the hospital is genuinely
 * not on the site, so the request goes to the city guide covering it, which
 * answers "health check-up in <city>" — the query behind these URLs. Bangkok
 * hospitals and slugs with no city go to the hospital index instead, since
 * that is browsable.
 *
 * Generated by apply_hospital_redirects.py. Do not hand-edit: restoring a
 * hospital has to remove its line from MOVED_TO_GUIDE, or the redirect runs in
 * middleware before routing and silently hides the page that was just added.
 */

/** Old slug -> current slug of the same hospital. */
export const RENAMED_HOSPITALS: Record<string, string> = {
'''


def main() -> int:
    if not TS.exists():
        sys.exit(f"missing {TS}")
    src = TS.read_text(encoding="utf-8")

    def parse(block: str) -> dict[str, str]:
        # Anchor on the declaration, not the bare name. Both map names also
        # appear in the file's header comment, and searching for the name alone
        # matched there first: MOVED_TO_GUIDE then parsed the RENAMED_HOSPITALS
        # body, decided all 67 of those slugs were live pages, and emptied the
        # guide fallbacks — putting every hospital that was *not* restored back
        # on a 404.
        start = src.index(f"export const {block}")
        body = src[src.index("{", start) + 1 : src.index("};", start)]
        return dict(
            (k, v)
            for k, v in (
                (m.split('":')[0].strip(' "'), m.split('":')[1].strip(' ",'))
                for m in body.strip().splitlines()
                if '":' in m
            )
        )

    renamed = parse("RENAMED_HOSPITALS")
    moved = parse("MOVED_TO_GUIDE")
    print(f"current: {len(renamed)} renamed, {len(moved)} moved-to-guide")

    if GENERATED.exists():
        new = json.loads(GENERATED.read_text(encoding="utf-8"))
        print(f"folding in {len(new)} slug changes from the import")
        renamed.update(new)

    cfg = dict(DB_CONFIG)
    cfg.setdefault("database", "bkkcheckup")
    cfg["cursorclass"] = DictCursor
    conn = pymysql.connect(**cfg)
    cur = conn.cursor()
    cur.execute("SELECT slug FROM hospitals")
    live = {r["slug"] for r in cur.fetchall()}

    # A slug that is a page again must not be redirected away from.
    freed = sorted(s for s in moved if s in live)
    for s in freed:
        del moved[s]
    if freed:
        print(f"freed {len(freed)} slugs that are live pages again:")
        for s in freed[:20]:
            print(f"   {s}")

    # A slug that redirects to itself is an infinite loop, and the page is gone
    # for as long as it is there. Cheap to check, catastrophic to miss.
    loops = sorted(k for k, v in renamed.items() if k == v)
    for k in loops:
        del renamed[k]
    if loops:
        print(f"dropped {len(loops)} self-redirects (would have been infinite loops):")
        for k in loops[:10]:
            print(f"   {k}")

    # A rename whose target does not exist would 308 into a 404.
    broken = sorted(k for k, v in renamed.items() if v not in live)
    for k in broken:
        del renamed[k]
    if broken:
        print(f"dropped {len(broken)} renames whose target is not a page: {broken[:8]}")

    # A slug cannot be in both maps; the rename is the better answer.
    for k in list(moved):
        if k in renamed:
            del moved[k]

    out = [HEADER]
    for k in sorted(renamed):
        out.append(f"  {json.dumps(k)}: {json.dumps(renamed[k])},\n")
    out.append("};\n\n")
    out.append("/** Deleted hospital -> the live path (locale-relative) that best covers it. */\n")
    out.append("export const MOVED_TO_GUIDE: Record<string, string> = {\n")
    for k in sorted(moved):
        out.append(f"  {json.dumps(k)}: {json.dumps(moved[k])},\n")
    out.append("};\n")
    TS.write_text("".join(out), encoding="utf-8")
    print(f"\nwrote {TS}: {len(renamed)} renamed, {len(moved)} moved-to-guide")
    return 0


if __name__ == "__main__":
    sys.exit(main())
