const TOPICS = [
  {
    title: "Bangkok's Most-Photographed Locations — Instagram vs. Reality & How to Get the Shot",
    emoji: "📸",
    summary: "Bangkok's Instagram landscape has specific locations that dominate the visual representation of the city — understanding both how to photograph them and the gap between Instagram presentation and reality improves both the creative and experiential visit: (1) Wat Arun at golden hour: Bangkok's most photographed temple (Wat Arun, Temple of Dawn, across the Chao Phraya from Tha Tien Pier) is maximally photogenic at golden hour (approximately 45 minutes before sunset); the river silhouette, prang (tower) reflections, and warm light combine for the classic Bangkok image; the reality check: photographers crowd the opposite bank at Tha Tien pier/restaurant during golden hour; the shot requires arriving 30+ minutes before sunset to secure a position; (2) The floating market boat angle: Thai floating markets (Damnoen Saduak, Amphawa) are heavily photographed with the iconic wooden boat/straw hat/colorful produce visual; this shot requires either hiring a photographer's boat for ฿500–1,000/hour for free positioning, or finding the specific angles near the wooden bridges during peak market hours (8–11am); (3) Bangkok's neon night district: Khao San Road, Nana Plaza, and Patpong's neon-heavy street lighting creates Bangkok's most recognizable night photography material; the mixed lighting (tungsten, fluorescent, LED, neon) creates complex white balance; shooting in raw format (camera) or manual settings (smartphone Pro mode) preserves the mixed-light character rather than auto-correcting it; (4) Temple interior gold: the interiors of Bangkok's major temples (Wat Pho's reclining Buddha, Wat Phra Kaew's golden walls) create challenging high-contrast photography conditions; flash photography is prohibited in most Bangkok temple interiors; night mode/manual ISO settings are necessary for quality shots; bringing a compact tripod (within temple rules) helps during lower-light interior photography; (5) Street food bokeh: Bangkok's street food environment (colorful woks, steaming pots, vendor faces) is a rich photography environment; approaching vendors before ordering (smiling, pantomiming camera use) typically gets permission for close-up shots; food photography from above (flat lay angle) works for plated market dishes; street food portrait photography requires establishing rapport before shooting.",
    action: "Golden hour timing: Bangkok sunset is approximately 6:15–6:45pm year-round (slight variation, near equator); Wat Arun sunset photography position: Tha Tien waterfront and Sala Rattanakosin restaurant (book a table for best angle); drone photography Bangkok: requires CAAT (Civil Aviation Authority of Thailand) permit, prohibited over most Bangkok areas without permit; recommended photography hardware: 24–70mm equivalent lens for versatile Bangkok shooting; waterproof camera bag for monsoon season protection.",
  },
  {
    title: "Bangkok Food Reels & Content Creation — TikTok Bangkok, Food Bloggers & Viral Dishes",
    emoji: "🎥",
    summary: "Bangkok is one of the world's premier food content creation environments, with a distinctive ecosystem of viral food moments and creator culture: (1) Bangkok's food TikTok geography: Bangkok has specific food content that consistently generates viral TikTok/Reels material — the egg-shaped omelet closing technique (kai jeow floating-close at street stalls), the precision papaya salad pounding (som tam preparation ASMR), pad thai flame-wok cooking, and the mango sticky rice assembly process; these dishes/techniques generate high view counts because of their visual interest even without audio; (2) Viral Bangkok food locations: Or Tor Kor Market (Chatuchak, premium produce and prepared food market) provides organized, photogenic food stalls; JJ Mall food section (Chatuchak weekend market, Saturday–Sunday) has high density of photogenic street food; Yaowarat (Chinatown) at night has red lanterns, vendor density, and multi-level composition; (3) Bangkok food blogger ecosystem: Bangkok's Thai food blogger market is enormous — Wongnai (Thailand's Yelp equivalent) has millions of Thai-language food reviews; Bangkok's food content industry ranges from large Thai YouTube channels (Foodwork, multiple food review channels with millions of subscribers) to micro-influencers; international food content (Mark Wiens' YouTube channel Migrationology has Bangkok as a primary location and has influenced international Bangkok food tourism significantly); (4) Content creation infrastructure: Bangkok's photogenic food environment means restaurant and market vendors are generally comfortable with content creation (filming, photography); asking permission remains courteous even when vendors seem accustomed to cameras; some restaurants charge 'photoshoot fees' at particularly Instagrammable establishments; (5) Morning vs. night content opportunities: Bangkok's morning (5–9am) provides market photography with soft light and genuine working atmosphere at Pak Klong Talad (24-hour flower market, peak 2–6am before delivery trucks leave), Bang Kachao community (bicycle food circuit), and early temple merit-making; Bangkok's night (6pm–midnight) provides neon, fire cooking light, and Chinatown lantern visual environments.",
    action: "Filming permits for commercial content: Bangkok commercial film/photography in public spaces requires permits through Bangkok Metropolitan Administration for productions with crew and equipment; tourist content creation (smartphone, solo, without commercial setup) is unrestricted; equipment rental for Bangkok: camera equipment rental available at Fotofile and other Bangkok camera shops in the Fortune IT/Pantip area; content creation cafés: Bangkok has 'café-galleries' specifically designed with photogenic backgrounds for content creation — searchable via 'Bangkok content creation café' Instagram.",
  },
  {
    title: "Bangkok Architecture Photography — Heritage Buildings, Modernism & Contrast Shots",
    emoji: "🏛️",
    summary: "Bangkok offers exceptional architectural photography from multiple eras, styles, and the dramatic visual contrasts between them: (1) Bangkok's architectural photography zones: (a) Rattanakosin Island (old city) — concentrated traditional Thai temple architecture; royal palaces; 19th-century Siamese-European hybrid buildings; the Grand Palace grounds contain multiple architectural photography subjects within walking distance; (b) Old Bangrak/Charoen Krung — Portuguese-era colonial buildings, early 20th century shophouses, art deco bank buildings, Assumption Cathedral; the area provides a European-tropical architectural texture rare in Bangkok; (c) Silom/Sathorn CBD — Bangkok's skyline with glass towers juxtaposed against older Thai temples and shophouses; the contrast between Sathorn's modern glass corporate architecture and Wat Yannawa (a Chinese junk-shaped temple, 1830s) a few blocks away is maximally photogenic; (d) Chinatown (Yaowarat) — preserved shophouse architecture from early 20th century; Chinese merchant building facades; ornate signage; (2) Thai shophouse architecture: Bangkok's traditional shop-house architecture (terrace buildings with commercial ground floor and residential upper floors, typically 3–4 stories, 4–5 meter frontage) is one of the city's most photographed visual textures; the combination of surviving pre-1950 shophouses with aging signage, Chinese-Thai typography, and organic neighborhood activity creates the 'Bangkok atmosphere' for many photographers; these are concentrated in Chinatown, Banglamphu, Samphanthawong, and Talat Noi areas; (3) Modernist Bangkok: Bangkok's 1970s–1990s modernist architecture (sometimes called 'tropical modernism' or colloquially 'Stalinist Thai modernism' for the more brutalist examples) creates its own photographic interest; the State Railway of Thailand Headquarters (Rong Si Road, 1930s), Hua Lamphong Station (Italian neoclassical, 1916), and various government buildings from different eras layer Bangkok's built environment; (4) Contrast shot Bangkok: Bangkok's most iconic visual contrasts — high-rise glass condominiums directly adjacent to traditional shophouse neighborhoods (visible from Surasak BTS); gold temple spires reflected in modern glass towers (various CBD-adjacent temples); rooftop infinity pool overlooking traditional temple roofline (several Silom/Bangrak hotels); (5) Time of day for architecture: Bangkok's flat low-horizon topography means harsh midday light is unflattering for architecture photography; morning (7–10am) and late afternoon (3–6pm) provide directional light that emphasizes architectural texture and avoids overexposure; golden hour creates warm tones on Bangkok's abundant gold temple decoration.",
    action: "Bangkok architectural photography routes: (1) Rattanakosin early morning loop — start at Wat Suthat (7am, few tourists), walk to Giant Swing, Sanam Luang, Grand Palace exterior walls, Tha Chang Pier for river reflections, complete by 10am before crowds; (2) Charoen Krung heritage walk — BACC → Talat Noi → Holy Rosary Church → Haroon Mosque → Assumption Cathedral covering 200 years of non-Thai religious architecture; (3) Sathorn contrast shot: stand at Saint Louis Hospital (Sathorn) and frame the neighborhood's traditional architecture against the glass towers; equipment note: a wide-angle lens (16–24mm full-frame equivalent) is most useful for Bangkok's compressed urban photography conditions.",
  },
];

export function BangkokInstagram() {
  return (
    <div className="rounded-2xl border border-pink-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-pink-700 mb-3">
        📸 Bangkok visual content — Instagram photography, food TikTok & architecture shots
      </h2>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-pink-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-pink-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
