const SPOTS = [
  {
    name: "Chao Phraya Express Boat — Bangkok's Original Mass Transit",
    emoji: "⛵",
    area: "Chao Phraya Express Boat routes: main river route runs from Nonthaburi (north) to Wat Rajsingkorn (south), approximately 40 piers; key tourist piers: Nonthaburi Pier (N30), Phra Arthit/Banglamphu Pier (N13) for Khao San Road, Phra Chan Pier (N10) for Grand Palace and Wat Pho, Rajinee Pier (N12) for Khao San Road south entrance, Yodpiman River Walk Pier, Harbour Department Pier, Central Pier/Saphan Taksin (S6) for BTS connection and Icon Siam; tourist boat (orange flag): central tourist piers only; regular boat (green flag, blue flag, no flag): all piers; operating hours: approximately 6am–7pm; boat types: tourist express (orange flag), local express (yellow flag, green flag), local ordinary (no flag)",
    price: "Local express boat (per section): ฿10–30; Tourist orange flag boat (one-way): ฿50 flat; Tourist orange flag all-day pass: ฿200; Regular boat (full river north-south): approximately ฿30–40 with transfers; Chao Phraya Tourist Boat (hop-on hop-off package): ฿200/day; Khlong Saen Saep canal boat: ฿10–18 per section; Icon Siam river shuttle from Saphan Taksin: free for Icon Siam visitors (scheduled service)",
    why: "The Chao Phraya Express Boat is one of Bangkok's most practical and scenic transportation options for the Grand Palace-Khao San Road-Chinatown corridor: (1) Avoiding traffic: the Chao Phraya River boats are completely immune to Bangkok's notorious road traffic; during peak hours (7–9am, 4–7pm) when Sukhumvit and Silom road traffic can reduce Grab journey speeds to 3–5 km/h, boats maintain their timetable speed along the river regardless; (2) Grand Palace connection: the most practical way to reach the Grand Palace complex from BTS Saphan Taksin (Silom) is the Chao Phraya Express Boat (10–15 minutes to Tha Chang Pier N9); this is faster and cheaper than Grab during tourist hours; (3) Canal boat (Khlong Saen Saep): the east-west canal boat service (Khlong Saen Saep) crosses Bangkok from Pratunam through Asok and to the eastern suburbs; this service connects areas not on the BTS/MRT and runs parallel to Sukhumvit at a distance; transfers at Pratunam Bridge allow combining canal boat with Chao Phraya boat for cross-city travel; (4) Night cruise and dinner boats: the Chao Phraya is the venue for Bangkok's dinner cruise tourism industry; multiple operators run dinner cruises (Chao Phraya Princess, Manohra, The Grand Palace floating restaurant); these cruises (typically 2 hours, ฿800–2,000 per person with dinner) provide the most dramatic angle on Wat Arun and the Rama VIII Bridge; (5) Row boat canals (Khlong tours): smaller canal boats (accessed from various Thonburi piers) navigate Bangkok's surviving canal network past traditional wooden houses, temple gardens, and orchid farms; these tour boats (negotiated privately with longtail boat operators at Tha Tien Pier, Khlong Bangkok Noi, etc.) provide access to Thonburi's disappearing old Bangkok character.",
    tip: "Chao Phraya boat navigation guidance: (1) Flag color confusion: different colored flags indicate different service levels; the orange flag 'Tourist Boat' has fewer stops (only major tourist piers) and costs ฿50 flat; the local yellow flag and no-flag boats stop at all piers and cost ฿10–30 per section but require knowing which pier to exit; tourists staying on major tourist piers (Saphan Taksin, Tha Chang, Phra Arthit) can use either service; (2) Boarding and payment: boarding happens at the pier; some piers have ticketing booths, others have collectors on the boat (paying on board is normal, exact change appreciated); tourist orange flag boats require ticket purchase at pier; (3) Khlong Saen Saep boarding: the Khlong Saen Saep canal boat boarding piers (concrete floating platforms) require confidence in stepping quickly onto moving boats; the boats stop briefly at each pier; watching locals board and then mimicking technique prevents being left at the pier or falling; (4) Life jackets are not standard: the standard Chao Phraya express boats and Khlong Saen Saep boats do not provide life jackets as standard; in the unlikely event of a fall into the canal/river, canal water in Bangkok is not clean; (5) Evening light for Wat Arun photography: the Chao Phraya boat at sunset passing Wat Arun (Temple of Dawn, which is paradoxically most photographed at sunset) provides dramatic photography opportunities from the river perspective impossible to achieve from the temple grounds.",
  },
  {
    name: "Bangkok Longtail Boat Taxis & Canal Network",
    emoji: "🚤",
    area: "Bangkok canal (khlong) network: historically extensive, many filled in for roads; surviving major canals: Khlong Saen Saep (main east-west canal), Khlong Bangkok Noi (Thonburi, connects to Chao Phraya), Khlong Om (north Bangkok, less tourist-visited); longtail boat (reua hang yao) hubs: Tha Tien Pier (near Wat Pho) for hired Thonburi canal tours; Pinklao Pier for northern canal access; negotiated longtail tours: ฿1,500–2,500 per hour for private charter (negotiate before departure); important canals for private tours: Khlong Bangkok Noi, Khlong Bangkok Yai (Thonburi side temple canals)",
    price: "Longtail boat private charter (1 hour, Thonburi canals): ฿1,500–2,500; Floating market longtail tour (Damnoen Saduak or Amphawa from Bangkok): included in tour package ฿1,500–3,000; Canal community tour (Bang Kachao by longtail): ฿600–1,000 per person in group; Khlong Saen Saep all-section ticket (east-to-west): approximately ฿36 accumulated; Long tail boat personal taxi (faster river crossing): ฿5–10",
    why: "Bangkok's longtail boat network provides access to the city's surviving canal culture and is the fastest way to experience old Bangkok: (1) Longtail boat mechanics: the Thai longtail boat (reua hang yao) is a distinctive wooden boat design with an automotive engine (often repurposed car or truck engine) mounted at the stern on a long rotating shaft extending several meters behind the boat; the propeller is at the end of this shaft; the design allows the boat to navigate shallow canals, move at high speed, and be highly maneuverable; the engine noise is considerable — ear protection is available at some tour operators; (2) Thonburi canal culture: the canal networks of Thonburi (Bangkok's western bank, the original capital of Siam) retain wooden stilt houses, orchid gardens, temple compounds accessible only by water, and a lifestyle predating modern Bangkok infrastructure; a 1–2 hour longtail boat tour of Thonburi's canals passes communities where refrigerators and cars are delivered by boat, children travel by water to school, and the canal is the primary road; (3) Floating market canals: Bangkok's day-trip floating markets (Damnoen Saduak, approximately 80km southwest; Amphawa, approximately 70km southwest) involve longtail boat access within the markets; the Amphawa floating market's canal restaurant strip (restaurants accessed by small boat from the canal bank) is a distinctive Thai food experience; (4) Speed vs. scenery tradeoff: the express Khlong Saen Saep canal boats travel fast and provide scenery of canal-side Bangkok communities; longtail charter tours travel at reduced speed to allow photography and closer observation; choosing between transport function and tourism function is the key decision; (5) Bang Kachao by boat: the Bang Krachao green lung island (accessible by ferry from Klong Toey) can alternatively be accessed by longtail boat from Tha Klong Toey pier; the longtail boat approach through the river then canal route provides a different perspective on the island than the ferry approach.",
    tip: "Longtail boat canal tour guidance: (1) Negotiate price clearly before departure: confirm the exact tour duration (minutes/hours), route covered (specific canals), and whether the price is per person or per boat before the engine starts; once the boat is moving, price renegotiation is difficult; (2) Protect camera equipment: spray from longtail boat propellers and wake from passing vessels can wet camera equipment; having a bag for equipment and keeping it dry during the ride; waterproof phone cases are advisable; (3) Motion sickness on longtail boats: the combination of high speed and wake from other vessels can cause motion sickness for susceptible individuals; taking motion sickness medication before canal tours and sitting in the middle of the boat (most stable position) reduces discomfort; (4) Flower garlands at canal temples: canal-accessible temples in Thonburi often have vendors at the water's edge selling flower garlands (malai) for offering; buying and offering these garlands as the longtail boat pauses at temple piers is part of the traditional canal experience; (5) Environmental context: Bangkok's canals have improved in water quality over the past decade (reduction of untreated sewage discharge) but are not clean waterways; falling into canal water should be treated as a medical hygiene concern requiring immediate washing; this context shouldn't deter canal tourism but informs handling water contact.",
  },
  {
    name: "Bangkok River Ferries — Cross-River Routes & Icon Siam Access",
    emoji: "🛥️",
    area: "Cross-river ferry services: multiple short cross-river ferry routes operated by private operators connect Chao Phraya east bank to Thonburi west bank; major cross-river ferries: Tha Maharaj to Wang Lang/Siriraj Hospital Pier; Tha Tien to Wat Arun Pier (most famous, direct Wat Arun access); Sathorn/Saphan Taksin to Asiatique and Icon Siam shuttle; Phibun Songkhram Pier to Thewet Pier for Dusit area; river taxi shortcut services; Icon Siam shuttle boat: free shuttle from Central Pier (Saphan Taksin) for Icon Siam mall visitors",
    price: "Cross-river ferry: ฿3–6 per crossing; Tha Tien to Wat Arun (most tourist cross-river trip): ฿6 per crossing; Icon Siam free shuttle: free (for mall visitors, scheduled service from Central Pier); Asiatique shuttle boat (evening service from Central Pier): ฿30 round trip; Maharaj to Siriraj: ฿4; Private cross-river charter (small boat): ฿50–200 per crossing negotiated",
    why: "Cross-river Bangkok ferries are the fastest way to access major attractions on the Thonburi (west bank) side of the Chao Phraya: (1) Wat Arun's cross-river access: the Tha Tien pier (adjacent to Wat Pho) to Wat Arun pier ferry (2 minutes, ฿6 each way) is Bangkok's most-used tourist ferry; without this ferry, reaching Wat Arun from the east bank requires a significant detour by road or a much longer boat trip; the ferry runs very frequently during daylight hours; (2) Asiatique Riverfront: the Asiatique night market (open from 5pm, on the west bank near Charoen Krung) is accessible by free shuttle boat from the Sathorn Central Pier; the shuttle makes Asiatique accessible from BTS Saphan Taksin without road travel; (3) Icon Siam free shuttle: Icon Siam's free shuttle boat from Central Pier (Saphan Taksin BTS adjacent) runs every 15–30 minutes; the 15-minute river crossing approach to Icon Siam mall provides dramatic views of Bangkok's riverside skyline; (4) Siriraj Hospital access: the Siriraj Hospital complex (Bangkok's oldest hospital and home to the famous medical museum) is most efficiently reached by cross-river ferry from Maharaj Pier; avoiding road traffic on Pinkklao Bridge saves 30–45 minutes during peak hours; (5) Evening cross-river navigation: cross-river ferries generally cease operation in the early evening (typically 6–8pm depending on service); checking last ferry times is important for planning evening Thonburi visits; Grab and taxi are alternatives after ferry service ends.",
    tip: "Cross-river ferry practical guidance: (1) Very short crossings: most Chao Phraya cross-river ferries are 200–400m crossings taking 2–5 minutes; there is minimal risk of motion sickness; the brevity means they are practical even for passengers who find longer boat trips uncomfortable; (2) Busy crossing piers: the Tha Tien to Wat Arun pier is extremely busy during tourist hours (9am–3pm); multiple boats operate at short intervals; waiting time for the next crossing rarely exceeds 5 minutes; (3) Boat vs. taxi to Wat Arun: during weekend traffic, taking the BTS to Saphan Taksin, Chao Phraya Express Boat north to Tha Tien Pier, then cross-river ferry to Wat Arun pier is typically faster than Grab from Sukhumvit by 25–45 minutes; (4) Nighttime river views: even when destination ferries have finished service, the view of Bangkok's lit riverside from the Chao Phraya is one of the city's best nighttime experiences; the Saphan Phut area near Memorial Bridge and the Saphan Taksin bridge area provide river viewing platforms accessible after boat service ends; (5) River taxi vs. express boat: river taxi (private boat hired from any pier) and express boat are different services; river taxis charge negotiated prices for point-to-point trips; express boats follow fixed routes with fixed fares; for unusual pier-to-pier combinations not on standard express routes, river taxi charter is necessary.",
  },
];

export function BangkokBoatTransport() {
  return (
    <div className="rounded-2xl border border-cyan-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-cyan-700 mb-3">
        ⛵ Bangkok water transport — Chao Phraya express boats, longtail canal tours & river ferries
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-cyan-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-cyan-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-cyan-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
