const SPOTS = [
  {
    name: "Bangkok Fine Dining — Asia's 50 Best Restaurants, Michelin Guide & Top Tables",
    emoji: "🍽️",
    area: "Bangkok Michelin Guide restaurants (selection): Le Normandie (Mandarin Oriental, French fine dining, 1–2 stars); Sorn (contemporary southern Thai, Michelin starred, Silom area); Nahm (COMO Metropolitan, Thai fine dining, David Thompson); Le Du (seasonal Thai-European, Silom, multiple Asia's 50 Best); Savelberg (Dutch fine dining, Marriott Marquis, consistent); Gaggan Anand (new location, progressive Indian); Paste (Thai fine dining, gourmet Thai); Sühring (twin brothers German-European, Sathorn); Blue by Alain Ducasse (ICONSIAM); R-Haan (royal Thai cuisine, Asoke area); Eat Me (Convent Road, international); Bangkok Michelin Guide: published annually, typically featuring 10–20 starred restaurants and 100+ Bib Gourmand (value) selections",
    price: "Bangkok fine dining price range: 1–2 star Michelin tasting menu: ฿2,500–8,000 per person without wine pairing; wine pairing typically adds ฿1,500–4,000; Asia's 50 Best ranked Bangkok restaurants without Michelin stars (Le Du, Savelberg): ฿2,000–5,000 per person; mid-tier fine dining (upscale Thai, modern Thai-French): ฿800–2,000 per person; comparison: equivalent Michelin-level dining in Tokyo, Paris, or New York costs 2–4x Bangkok pricing for similar star quality; advance booking: essential for top 10 Bangkok fine dining restaurants, often requiring 1–4 weeks",
    why: "Bangkok's fine dining scene has earned genuine international recognition as one of Asia's most dynamic and innovative: (1) Bangkok's fine dining rise: Bangkok has transformed from a city with limited fine dining options (pre-2010) to one of Asia's most exciting fine dining markets; multiple Bangkok restaurants appear in Asia's 50 Best Restaurant rankings; the Michelin Guide began covering Bangkok in 2018; the pace of new high-quality restaurant openings (from internationally trained Thai chefs returning home and international chefs establishing Bangkok outposts) accelerated through the 2020s; (2) Thai chef renaissance: the most significant development in Bangkok fine dining is the generation of internationally trained Thai chefs reinterpreting Thai cuisine at fine dining levels; chefs like Ton Supasit (Le Du), Chef Noom (Sorn's southern Thai focus), and others have created cooking that is unmistakably Thai in flavor philosophy while applying contemporary technique and presentation; this represents a different creative vision than 'fusion' — it is a sophisticated deepening of Thai culinary heritage; (3) Bangkok's price advantage for fine dining: Bangkok fine dining provides one of the world's best price-to-quality ratios for serious dining; a 3-course dinner at a ranked Bangkok restaurant costs ฿1,500–3,000 ($40–85) — equivalent quality dining in Tokyo, Paris, or New York would cost $150–300+; the combination of genuinely skilled cooking, exceptional local ingredient quality, and lower operating costs creates the price advantage; (4) Vegetable diversity in Bangkok fine dining: Bangkok's proximity to Southeast Asia's year-round growing seasons creates access to vegetable and herb diversity that European fine dining cannot match; fine dining Thai restaurants exploit this — herbs like galangal, kaffir lime leaf, betel leaf, lesser galangal, wild ginger, and dozens of additional aromatics available fresh year-round create flavoring complexity unavailable to chefs in most other countries; (5) Restaurant reservation challenges: Bangkok's top fine dining restaurants are genuinely difficult to book; Gaggan Anand, Le Normandie, and Sorn require advance booking of 2–8 weeks; using the restaurant's online booking system (many use Michelin Experiences, TheFork, or direct booking via Instagram) is the primary approach.",
    tip: "Bangkok fine dining practical guide: (1) Dress code Bangkok fine dining: Bangkok's Michelin-starred restaurants typically require 'smart casual' or 'smart' dress — shorts and flip-flops are genuinely not accepted at Le Normandie, Sühring, or equivalent tier restaurants; tailored pants, collared shirts for men; dresses or elegant separates for women; verifying specific dress code before booking prevents embarrassment; (2) Wine at Bangkok fine dining: Bangkok's wine import duties make wine lists at fine dining restaurants expensive relative to food; a ฿2,500 food tasting menu may pair with wine costing ฿3,000–6,000 extra; some Bangkok fine dining guests choose non-alcoholic pairing options (sometimes offered, typically ฿800–1,500) to reduce total cost; BYOB is possible at some Bangkok restaurants with corkage fee (฿500–1,500); (3) Bangkok vs. Asia fine dining comparison: Bangkok Michelin starred restaurants provide different strengths vs. Tokyo or Singapore — Bangkok's multi-starred restaurants are fewer in total but the density of excellent mid-tier fine dining (฿800–2,000 range) is exceptional; Bangkok specifically excels at contemporary Thai cooking at high-skill levels; Tokyo's fine dining excels at Japanese precision at all price points; (4) Informal fine dining addresses: some of Bangkok's most interesting food experiences at fine dining quality occur in informal settings — Bib Gourmand restaurants (Michelin recognition for value dining) include street-adjacent and shophouse restaurants that deliver sophisticated cooking without formal service overhead; (5) Pre-dinner drinks at Bangkok hotel bars: Bangkok's major hotel bars (Mandarin Oriental Bamboo Bar, Capella Bangkok's Café Muse, Peninsula's Lobby Bar) provide exceptional pre-fine-dinner cocktail settings; the Mandarin Oriental's Bamboo Bar (1953, Bangkok's oldest jazz bar) is a Bangkok institution appropriate for pre-dinner cocktails before Le Normandie.",
  },
  {
    name: "Bangkok Dinner Cruises — Chao Phraya River & Canal Boat Dining",
    emoji: "⛵",
    area: "Bangkok dinner cruise operators: Manohra Cruises (River City Pier, converted rice barges, most atmospheric); Charoennakorn River Tour (Asiatique area, shuttle connection); Grand Pearl River Cruise (Si Phraya Pier); Loy Nava Dinner Cruise (Si Phraya Pier, authentic rice barge, excellent Thai food reputation); Anantara Riverside Bangkok Resort dinner boat (resort pier, Thonburi side); Buddha's Tale Dinner Cruise (river); Yok Yor Marina (Sam Yan area, fixed riverside restaurant but often grouped with cruise options); canal dinner cruises: Bangkok Canal Tour operators offer private canal dinner experiences through Bangkok's network of historic khlongs",
    price: "Bangkok dinner cruise pricing: budget river cruise with dinner: ฿800–1,200 per person; mid-range dinner cruise (good Thai food, live music, air-conditioned main deck): ฿1,500–2,500 per person; premium dinner cruise (Manohra, Loy Nava): ฿2,500–4,000 per person; private charter (small group, custom): ฿8,000–30,000 per boat depending on size and duration; cruise duration typically 1.5–2.5 hours on river; hotel riverside restaurants with river views (non-cruise): Riva del Fiume (Peninsula Bangkok), Authors' Lounge/river deck (Mandarin Oriental) for fixed riverside dining",
    why: "Bangkok's Chao Phraya River provides a genuinely spectacular setting for evening dining: (1) Chao Phraya at night: Bangkok's river is most visually spectacular at night — temples illuminated on both banks (Wat Arun's prang glowing, Grand Palace complex lit from within, Tha Tien area temples), the Rama VIII Bridge's dramatic cable-stay structure with colored LED lighting, and the contrast between riverside traditional architecture and the Bangkok skyline combine for a distinctive evening visual experience; (2) Dinner cruise quality variation: Bangkok's dinner cruise market has significant quality variation; the most common complaint in reviews is food quality vs. price ratio on budget cruises (buffet Thai food that is mediocre despite expensive pricing per cruise); the premium cruises (Manohra, Loy Nava) have genuine quality reputations for food; the visual experience is similar across cruise price tiers; (3) Cruise timing matters: Bangkok dinner cruises typically depart 7–7:30pm and return by 9:30–10pm; sunset is approximately 6:15–6:45pm; cruises that catch the last of sunset before night temple illumination provide the most dramatic visuals; arriving at the departure pier early enough to be onboard for departure (not just before sailing) allows viewing the sunset approach from the water; (4) Manohra as benchmark: Manohra Cruises (River City Pier, central Bangkok) consistently receives the highest ratings among Bangkok dinner cruises for food quality, ambiance, and the unique converted rice barge aesthetic (wooden hull, rattan furnishing, lantern lighting); the Thai cuisine on Manohra is notably better than most comparable price-point dinner cruises; (5) Canal private dinner alternative: Bangkok's network of historic canals (Khlong Bangkok Noi, Khlong Bangkok Yai, inner Thonburi canals) offers private canal dinner experiences through tour operators; canal dinner boats pass through residential and temple neighborhoods invisible from the main river — a different and less touristic experience than the main Chao Phraya cruise.",
    tip: "Bangkok dinner cruise planning: (1) Seat selection on dinner cruises: Bangkok dinner cruises offer deck seating (outdoor, open air, best river views but hot before sunset and occasional motor smell) vs. air-conditioned cabin seating (comfortable but glass-filtered views); for photography, requesting outdoor deck table is the better visual experience; for comfort throughout the meal, AC cabin is more pleasant; (2) Departure pier logistics: Bangkok dinner cruise departure piers are distributed along the river; most popular piers (River City, Si Phraya, Oriental Pier) are accessible from BTS or MRT + short taxi; arriving 20–30 minutes early is recommended for boarding; Grab to pier drops at the right address avoids navigating to obscure pier locations at night; (3) Photography during cruises: Bangkok dinner cruise photography peaks during: Wat Arun crossing (most photographed temple from river), Rama VIII Bridge pass (dramatic structure), Rattanakosin illuminated buildings area; a compact lens (35–50mm equivalent on smartphone or dedicated camera) works better than wide-angle in the low light river environment; (4) Booking and no-show rates: Bangkok dinner cruises have relatively high no-show rates; booking directly with reputable operators (Manohra's own website) rather than through reseller aggregators provides better service and booking flexibility; cancellation policies vary; (5) Alternative: riverside restaurant pier views: visitors who find dinner cruise pricing high can experience the Chao Phraya at night from fixed riverside restaurants (Peninsula's Riva del Fiume at the top end, Asiatique's riverside food court at the bottom end) without cruise cost; the Tha Tien area restaurants across from Wat Arun provide the classic Wat Arun sunset/night view from a fixed position.",
  },
  {
    name: "Bangkok Brunch Culture — Weekend Brunch Scene, Bottomless & Trendy Café Brunches",
    emoji: "🍳",
    area: "Bangkok brunch venues: Eat Me Restaurant (Convent Road, Silom, Sunday brunch institution); Roast Coffee & Eatery (multiple locations, weekend breakfast/brunch); NARA Thai Cuisine (Central Embassy, weekend Thai brunch); The Commons (Thong Lo, weekend market and food hall, brunch vendors); Issaya Siamese Club (weekend Thai brunch in heritage house); Lenôtre (CentralWorld, French bakery brunch concept); Dean & DeLuca (multiple Bangkok locations, American brunch concept); hotel Sunday brunches (Mandarin Oriental Sunday brunch, Peninsula Sunday brunch, Banyan Tree Vertigo Sunday brunch — all with bottomless drinks options); Brunch BKK Instagram community documents Bangkok's weekend brunch scene comprehensively; Thai restaurant weekend brunch: several Thai fine dining options (Bo.lan, Nahm) offer weekend brunch menus",
    price: "Bangkok weekend brunch pricing: casual brunch café: ฿300–600 per person (food only); hotel Sunday brunch: ฿1,500–3,500 per person (food included) or ฿2,500–6,000 with free-flow alcohol; bottomless brunch (2-hour unlimited alcohol + food): ฿1,200–2,000 at Bangkok bistros and brunch venues; weekend brunch popularity: Bangkok's brunch scene is most active on Sundays (9am–2pm); Sunday hotel brunches (Marriott Marquis, Mandarin Oriental) are among Bangkok's most consistent luxury value propositions combining unlimited food + alcohol at approximately 50% below equivalent international city pricing",
    why: "Bangkok has developed a distinctive weekend brunch culture that serves the city's large international expat community and affluent Thai demographic: (1) Bangkok's brunch timing adaptation: international brunch culture (originating in Western 'breakfast+lunch' casual dining tradition) has been adopted by Bangkok's international communities; the adaptation includes incorporating Thai dishes alongside Western brunch standards, creating Bangkok-specific brunch menus that combine eggs benedict and congee, granola and mango sticky rice, and other hybrid combinations; (2) Hotel brunch as social institution: Bangkok's major hotel Sunday brunches (Marriott Marquis Queen's Park Sunday brunch, Sofitel So Bangkok, Peninsula Bangkok) serve as weekly social gatherings for Bangkok's expat community; the unlimited food and free-flow alcohol format (common at hotel brunches) creates a distinctive casual-sophisticated social atmosphere; (3) The rise of brunch café culture: Bangkok's specialty coffee café movement has extended into weekend brunch formats; the Thong Lo-Ekkamai corridor has the highest concentration of Instagram-optimized brunch cafés targeting Thai millennials and expats; café brunches in this area feature elaborate plating and specialty coffee alongside Western and pan-Asian breakfast dishes; (4) Thai influence on Bangkok brunch: Bangkok's brunch culture incorporates local Thai elements beyond pure imported formats — Thai fresh fruit platters (seasonal tropical fruit), khao tom (Thai rice porridge, morning comfort food equivalent to congee), jok (thick rice porridge), and Thai-style omelets appear on Bangkok brunch menus alongside smoothie bowls and avocado toast; (5) Bangkok's rooftop brunch: several Bangkok rooftop venues offer weekend brunch with panoramic city views; the combination of bottomless drinks, high-rise views, and a 3-hour weekend morning creates a distinctive Bangkok experience that maximizes three Bangkok strengths simultaneously (urban views, hospitality value, food quality).",
    tip: "Bangkok brunch practical guide: (1) Hotel brunch reservation requirement: Bangkok's popular hotel Sunday brunches fill quickly — Marriott Marquis, Mandarin Oriental, and Peninsula Sunday brunches are fully reserved weeks in advance during peak season (November–February); booking 1–2 weeks ahead is minimum; October–December holiday period requires 3–4 weeks advance booking; (2) Free-flow value assessment: Bangkok hotel bottomless alcohol brunch (typically ฿2,500–3,500 with free-flow prosecco/wine/spirits for 3 hours) provides genuine value vs. individual drink purchasing — 4 drinks at ฿300–500 each quickly exceeds the inclusive price; the food component at quality hotel brunches (unlimited live station dishes) adds further value; (3) Sunday brunch timing for best experience: Bangkok's hotel brunches typically run 11am–2:30pm; arriving at opening (11am) accesses live cooking stations at their freshest and avoids the 12:30–1:30pm peak crowd; (4) Brunch café photography peak: Bangkok's trendy brunch cafés (The Commons Thong Lo, Rocket Coffee Sunday, specific Thong Lo venues) are most photogenic 9am–11am (soft morning light, pre-crowd); popular cafés on Sunday afternoons have 30–60 minute wait times; (5) Hangover cure brunch culture: Bangkok's brunch scene partially evolved from the 'hangover cure' weekend eating pattern of the city's nightlife-active international community; khao tom (rice congee, gentle on stomach), fresh coconut water (electrolytes), and tom yum soup (spicy clear soup) are Bangkok's practical hangover recovery foods alongside more elaborate brunch concepts.",
  },
];

export function BangkokDinner() {
  return (
    <div className="rounded-2xl border border-amber-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-amber-700 mb-3">
        🍽️ Bangkok dining experiences — fine dining, Chao Phraya dinner cruises & weekend brunch culture
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-amber-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-amber-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-amber-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
