const SPOTS = [
  {
    name: "Grand Palace & Wat Phra Kaew — Bangkok's Sacred Center",
    emoji: "👑",
    area: "Grand Palace complex: Na Phra Lan Road, Phra Nakhon District; Chao Phraya riverfront; accessible by: boat (Chao Phraya express boat to Tha Chang Pier N9), taxi/tuk tuk, or walk from Democracy Monument (20 minutes); entrance on Na Phra Lan Road west gate; open daily 8:30am–3:30pm (last ticket 3:00pm); closed during significant Royal events (announced via official website); adjacent: Wat Pho (5-minute walk south), Thammasat University, Sanam Luang",
    price: "Grand Palace + Wat Phra Kaew + Vimanmek Mansion + Abhisek Dusit Throne Hall combined ticket: ฿500 (foreigners); Thai nationals: free; Audio guide: ฿200; Combined ticket includes multiple royal sites — same-day admission only; Sarong loan at gate: free with deposit; Street guides: unofficial — avoid; Official tour groups: book through licensed operators ฿800–1,500; Photography inside main buildings: not permitted",
    why: "The Grand Palace is Bangkok's most significant historic site and still an active ceremonial center for the Thai state: (1) Construction history: the Grand Palace (Phra Borom Maha Ratcha Wang) was begun in 1782 when King Rama I moved the capital from Thonburi to Bangkok; the complex expanded continuously through the 19th century as successive Rama kings added throne halls, temples, and residence buildings in a mixture of Siamese and European styles; (2) Emerald Buddha (Phra Kaew Morakot): housed in Wat Phra Kaew at the palace's northern compound, the Emerald Buddha is Thailand's most sacred Buddhist image; carved from a single piece of jade (not emerald — the green jade was mistaken for emerald at discovery); only 66cm tall; the Thai King personally changes the Buddha's seasonal robes three times yearly (rainy season, cool season, hot season) in a ceremony that no commoner may witness; (3) Architectural eclecticism: the Grand Palace complex's buildings represent 200 years of Thai royal architectural aspiration; the Chakri Maha Prasat Throne Hall (1882, built by Rama V/Chulalongkorn) is notably hybrid — the main building is Italian Renaissance-influenced while the roof is traditional Thai tiered-peak; this cultural fusion reflects 19th century Siamese modernization; (4) Current royal use: while the current King (Rama X, Vajiralongkorn) maintains primary residence at Amphorn Garden Residence (Dusit Palace) rather than the Grand Palace, the complex hosts major royal ceremonies (Coronation, Royal Ploughing Ceremony, royal cremations at adjacent Sanam Luang); (5) Vimanmek Mansion: included in the combined ticket; the world's largest golden teak wood mansion (built 1900); 72 rooms displaying royal family artifacts and European imports that reveal the depth of 19th century Thai royal international engagement.",
    tip: "Grand Palace visiting strategy: (1) Arrival time: arriving at 8:30am (opening) avoids the 10am–2pm peak crowds when tour buses deposit large groups simultaneously; the temperature is also cooler; (2) Dress code is non-negotiable: many visitors are turned away at the Grand Palace gate for dress code violations; shorts (any length), bare shoulders, sleeveless shirts, and flip-flops all violate the code; changing rooms and sarong loans are available at the entrance but reduce your time inside; carrying appropriate clothing is the most reliable approach; (3) Official guides vs. touts: touts near the Grand Palace often approach visitors claiming the palace is closed and offering to take them to a 'special viewing location' (a prelude to being taken to gem shops); the Grand Palace opens daily unless a specific Royal ceremony is scheduled — confirmed at palace.th.go.th; (4) Combined ticket value: the ฿500 combined ticket covers multiple royal sites (Grand Palace, Wat Phra Kaew, Vimanmek Mansion, Abhisek Dusit); Vimanmek is a 20-minute tuk tuk journey away; planning both in one day maximizes the combined ticket value; (5) Photography inside Wat Phra Kaew: the Emerald Buddha chapel prohibits flash photography and requires complete quiet; the buildings' interiors feature elaborate mural paintings of the Ramakien (Thai version of the Ramayana epic) across all wall surfaces — photography of the murals is generally permitted.",
  },
  {
    name: "Dusit Palace Complex — Royal Bangkok's 20th Century Heart",
    emoji: "🏛️",
    area: "Dusit Palace Complex: Ratchawithi Road, Dusit District; access: BTS (no direct connection — taxi or Grab recommended), MRT Ratchawithee (short walk), Khlong Saen Saep express boat (Tha Ratchawithi); includes: Ananda Samakhom Throne Hall, Vimanmek Mansion, Amphorn Garden Residence (not open to public — current royal residence), Dusit Zoo (now relocated — former zoo site being developed); National Assembly of Thailand is adjacent to Ananda Samakhom; Royal Elephant Museum at Dusit Palace",
    price: "Vimanmek Mansion + Dusit Palace complex: included in Grand Palace ฿500 ticket OR separate ฿150 ticket; Ananda Samakhom Throne Hall: periodic open days (check ahead); Dusit district walking: free; Official Dusit guide (Thai-English): ฿300–500; Photography permit (specific areas): sometimes required (check at gate); Café on palace grounds: ฿80–250",
    why: "Dusit Palace represents Thailand's turn-of-century royal modernization project and provides a different window into Thai royal history than the Grand Palace: (1) Rama V (Chulalongkorn) and Western modernization: the Dusit Palace complex was built by King Chulalongkorn (Rama V, reigned 1868–1910) as part of his deliberate program to modernize Siam while preserving sovereignty; Chulalongkorn's two European tours (1897, 1907) provided architectural inspiration for the European-style Dusit buildings; the strategy of strategic westernization while maintaining cultural distinctiveness preserved Thai independence during European colonialism; (2) Ananda Samakhom Throne Hall: the Italian Renaissance-influenced parliament building (completed 1915) is Bangkok's most dramatic European-style structure; the dome and murals (depicting significant events in early Chakri dynasty history) represent the Thai state's self-presentation to the modern world; currently used for state ceremonies and occasional public exhibitions; (3) Vimanmek Mansion detail: built in 1900 for Rama V's private use; the 72-room teak complex contains the king's private collection of European photographs, crystal, silverware, and gifts from foreign heads of state; the kitchen, bathing rooms, and private gallery rooms create an intimate portrait of royal daily life in the early 20th century; (4) Royal elephant heritage: the Royal Elephant Museum within the Dusit Palace grounds documents Thailand's tradition of white elephants as symbols of royal power; auspicious white (albino) elephants were historically owned exclusively by the Thai king; (5) Dusit district character: the Dusit area retains a distinct governmental character; the National Assembly (parliament), Government House, and multiple royal institutions are concentrated here; the wide European-style boulevards (Ratchadamnoen Avenue — designed by Rama V modeled on the Champs-Elysees) create a distinctly different urban scale from Sukhumvit.",
    tip: "Visiting Dusit Palace and the royal district: (1) Grand Palace combined ticket efficiency: if planning to visit both the Grand Palace complex and Vimanmek Mansion (Dusit), buying the ฿500 combined ticket at the Grand Palace gate and visiting Vimanmek the same day or following day maximizes value; (2) Ananda Samakhom open days: the Ananda Samakhom Throne Hall is not regularly open to public visits but has periodic opening days for exhibitions; checking the Royal Office website (royaloffice.th) or general Bangkok news before visiting Dusit allows planning around open access days; (3) Ratchadamnoen Avenue context: the wide European-styled boulevard connecting the Grand Palace to Dusit Palace is Bangkok's ceremonial axis; royal processions, national day celebrations, and historically protest movements have used this avenue; walking it from the Democracy Monument toward Dusit provides the most direct sense of Bangkok's ceremonial urban design; (4) Royal collection at Vimanmek: Vimanmek Mansion does not permit photography inside the building; the guided tour (required, approximately 45 minutes) covers the most significant rooms with royal household artifacts; the guide quality (English language) varies — patient listening rather than attempting self-exploration is recommended; (5) Dusit Zoo site: the former Dusit Zoo (adjacent to the palace complex) closed and the animals relocated to Khao Kheow Open Zoo (Chonburi); the zoo site is undergoing redevelopment; the surrounding areas retain significant tree cover and provide pleasant walking.",
  },
  {
    name: "Bangkok's Lesser-Known Royal Palaces & Royal Projects",
    emoji: "🌺",
    area: "Additional royal sites: Bang Pa-in Royal Palace (Ayutthaya province, 60km north, on the Chao Phraya River); Chitralada Royal Villa (Dusit, agricultural royal projects — not generally open to public); Suan Pakkad Palace (Sri Ayudhya Road, museum); Jim Thompson House (adjacent, royal patronage history); Royal Projects: Doi Tung (Chiang Mai), Phuping Palace (Chiang Mai, seasonal opening), Royal Project Foundation stores throughout Bangkok",
    price: "Bang Pa-in Royal Palace: ฿100 (Thai), ฿200 (foreigner); Suan Pakkad Palace Museum: ฿100; Royal Project Foundation shop (Chitralada brand): retail prices (agricultural products ฿50–500); Bang Pa-in tour from Bangkok (day trip with transport): ฿800–2,000; Jim Thompson House: ฿200 (the house itself has private museum access, not royal but associated); Royal Project café (Chitralada brand at various locations): ฿80–250",
    why: "Bangkok's royal landscape extends well beyond the Grand Palace and includes productive agricultural projects and lesser-known historic palaces: (1) Bang Pa-in Royal Palace: located 60km north of Bangkok on the Chao Phraya River (typically combined with Ayutthaya day trip), Bang Pa-in represents 19th and early 20th century royal eclectic architecture at its most elaborate; the complex contains structures in Thai, Chinese, Gothic, and Renaissance styles on a river island; the Chinese-style Phra Thinang Wehart Chamrun throne hall is the most photographed; (2) Chitralada Royal Villa (Chitralada Palace): the current king's primary Bangkok residence (Amphorn Residence section) and late King Bhumibol's agricultural research station; the Chitralada brand (branded milk, honey, bread, and agricultural products from royal farms) is sold at Royal Project shops throughout Bangkok; Chitralada brand products represent the royal family's agricultural development projects; (3) Royal Projects Foundation: the late King Bhumibol's project to replace opium cultivation in northern Thai highland communities with sustainable legal agriculture (the Royal Project Foundation) has transformed northern Thailand's hill tribe economy; highland coffee, tea, vegetables, and fruit branded as Doi Kham (Royal Project products) are available at Royal Project shops in Bangkok malls and at Chitralada brand outlets; (4) Suan Pakkad Palace Museum: a collection of eight traditional Thai houses on the grounds of a royal princess's former residence (Prasobsuk Palace area); the houses display antiques, Buddhist art, and lacquer paintings from the royal collection in a garden setting; less visited than major sites but historically significant and peaceful; (5) Royal warrant brands: Bangkok's retail market has multiple long-established companies with Royal Warrants (Thai Royal Household official endorsement — the Garuda seal indicates royal supplier status); these include specific luxury brands, food companies, and service providers that display the Garuda emblem.",
    action: "Bang Pa-in Royal Palace (ratchapreecha.com) — accessible by train from Bangkok's Bang Sue or Hua Lamphong stations (55 min to Ayutthaya then taxi 20 min); Suan Pakkad Palace (suanpakkad.com) on Sri Ayudhya Road; Royal Project Foundation shops: Chitralada brand at CentralWorld, Siam Paragon, and dedicated outlets; Bang Pa-in day trip from Bangkok organized by River City Bangkok pier (river cruise option available).",
  },
];

export function BangkokRoyalPalace() {
  return (
    <div className="rounded-2xl border border-yellow-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-yellow-700 mb-3">
        👑 Bangkok royal heritage — Grand Palace, Dusit Palace & royal projects guide
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-yellow-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-yellow-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
