const TOPICS = [
  {
    title: "Bangkok Urban Wildlife — Monitor Lizards, Cobras, Bats & Urban Wildlife Encounters",
    emoji: "🦎",
    summary: "Bangkok's tropical urban environment hosts surprising wildlife biodiversity that visitors regularly encounter: (1) Monitor lizards in Bangkok parks: Water monitor lizards (Varanus salvator, 'hia' in Thai — a word considered an insult in Thai, reflecting the monitor's low status) are common in Bangkok's parks, canals, and green areas; Lumpini Park has a well-documented monitor population of approximately 100+ animals; Chatuchak Park and Vachirabenjatas Park (Rot Fai Park) also have resident monitors; the monitors are large (1.5–2.5m adults) but not aggressive toward humans unless cornered or fed; feeding monitors is strongly discouraged (habituates them to human proximity and creates nuisance behavior); (2) Bangkok cobras and snakes: Bangkok has 7–9 snake species capable of entering homes, including the King Cobra, Monocled Cobra, and various pit vipers; Bangkok's snake encounters are most common in: green areas, old buildings with gaps, canal-side neighborhoods, and gardens; the Bangkok Snake Farm (Queen Saovabha Memorial Institute, Rama IV Road, established 1923) is both a working anti-venom production facility and educational museum; evening exhibitions include snake handling demonstrations; anti-venom production from the Snake Farm provides treatment for Bangkok's snake bite cases; (3) Bangkok's urban bats: Wat Saket (Golden Mount) area hosts a large fruit bat colony that departs at dusk (approximately 6–7pm) in a dramatic exodus of thousands of bats; the mass bat flight from the temple trees is an easily observed urban wildlife spectacle; the bats are Lyle's flying fox (Pteropus lylei) and play an important ecological role in pollination and seed dispersal; Thong Lor area also has bat colonies; (4) Bangkok birds: Bangkok has approximately 240+ bird species recorded, including urban-adapted species — Rock Pigeon (introduced), Asian Pied Starling, Common Myna, Spotted Dove; wetland birds around canals and parks: Purple Heron, Grey Heron, Little Egret, Purple Swamphen; Lumpini Park: Oriental Magpie Robin, Common Kingfisher; Bangkok parks are genuinely worth casual birdwatching, particularly at dawn (5–8am); (5) Wildlife-human conflict management: Bangkok residents have developed cultural tolerance for many urban wildlife cohabitants (temple cats and dogs, park monitors); the Buddhist ethic of not killing animals contributes to Bangkok's relatively positive coexistence with urban wildlife; however, human-wildlife conflict does occur: monitor lizards raiding fish farms, cobras in homes, birds fouling buildings; Bangkok's Department of National Parks handles removal of dangerous wildlife (snakes in homes) via a 24-hour wildlife hotline.",
    action: "Lumpini Park monitor lizard viewing: best 7–9am or 5–7pm when monitors are most active; approach quietly from upwind; monitors are most visible at canal edges and in shaded vegetation; do not approach closely or attempt to feed; Bangkok Snake Farm visit: Queen Saovabha Memorial Institute, Rama 4 Road, MRT Sam Yan station; snake shows Monday–Friday 11am and 2:30pm, Saturday–Sunday 11am only; admission approximately ฿200; the snake farm also provides anti-venom treatment; Golden Mount bat flight: arrive at Wat Saket (Golden Mount, walkable from Khao San Road) approximately 30 minutes before sunset for positioning to watch the bat departure; the bat colony size is largest during November–February; reporting dangerous snakes in Bangkok: call the wildlife department emergency line or ask neighbors for local snake handler contacts (established in each Bangkok community).",
  },
  {
    title: "Bangkok's Urban Green Spaces — Parks, Gardens & Breathing Room in the Megacity",
    emoji: "🌳",
    summary: "Bangkok's green space provision is limited relative to its population but specific parks offer genuinely valuable breathing room in the dense urban environment: (1) Lumpini Park — Bangkok's central park: Lumpini Park (57 hectares, at the junction of Silom and Rama IV Roads, served by MRT Si Lom and MRT Lumpini) is Bangkok's most important urban park; the park has ponds (paddle boats available), exercise areas, outdoor gyms, concert spaces, and the resident monitor lizard population; the park's exercise culture is most active from 5–8am (Tai Chi practitioners, aerobics classes, joggers) and 5–8pm (evening walkers and exercise groups); the park closes at 9pm; on weekend evenings, the park becomes a community social space with food vendors, families, and couples; (2) Benchakitti Park and Green Ring project: Benchakitti Park (east of Queen Sirikit National Convention Center, Asok area, serving MRT Queen Sirikit National Convention Centre) is Bangkok's newest major park, expanding toward a 'Green Ring' that will eventually circle Bangkok's inner city with connected green corridors; the Phase 1 park features a large lake (with walking bridge), wetland restoration, and elevated walking paths; Phase 2 expansion connects Benchakitti to Benjakitti Forest; the park represents Bangkok's most significant investment in urban green infrastructure in decades; (3) Chatuchak Park and botanical garden area: Chatuchak Park (adjacent to Chatuchak Weekend Market, MRT Chatuchak Park) has an ecology museum, ornamental plant gardens, bamboo garden, and lake areas; less manicured than Lumpini but with more diverse vegetation; the park hosts morning exercise groups and is used by Bangkok University students and families; Queen Sirikit Botanical Garden (within Chatuchak Park boundaries) provides additional botanical interest; (4) Rot Fai Park (Railway Park, Srinakarin): Rotfai Park (Bangkapi area, Ramkhamhaeng/Srinakarin, eastern Bangkok) is Bangkok's largest public park (300 rai, approximately 50 hectares) — less central than Lumpini, larger, and more oriented toward sport and exercise than tourism; the park has dedicated cycling tracks, open-air markets, concert venues, and is extremely popular with Bangkok's eastern district residents; Retro Markets (weekend vintage markets) at Rotfai Park's areas are Bangkok's most popular vintage/antique market alongside Chatuchak; (5) Bangkok's canal-side greenery: Bangkok's klongs (canals) and canal-side communities provide distributed green corridors throughout the city; the Saen Saep canal cycling/walking path (limited sections, Asok area) demonstrates potential for canal-side green movement infrastructure; the Bang Krachao 'Green Lung' (Phra Pradaeng peninsula across the river from On Nut) is the premier green space accessible from Bangkok but requires ferry crossing.",
    action: "Lumpini Park early morning: arrive by 6am for maximum exercise culture immersion and best park conditions; the morning Lumpini experience includes mass aerobics (large organized groups with speaker music), individual Tai Chi practice, and joggers; water aerobics in the lake is practiced by some community groups; all free to observe; Benchakitti Park extension: accessible from MRT Queen Sirikit NCC or through the main Benchakitti Forest Phase 2 entrance; the new lake walkway is Bangkok's best urban waterfront park experience; Bang Krachao cycling: the 'Green Lung' cycling (ferry from Klong Toei Pier or nearby Bang Nam Phueng Pier, ฿6–8) is the best active green space experience within Bangkok's functional reach — ideally 7–11am on a non-holiday weekday; bicycle rental at the landing pier.",
  },
  {
    title: "Bangkok Insect Eating — Fried Bugs, Edible Insects & Thailand's Entomophagy Culture",
    emoji: "🦟",
    summary: "Thailand has one of the world's most developed edible insect cultures, and Bangkok offers visitors organized access to this authentic culinary tradition: (1) Thailand's edible insect history: insect eating (entomophagy) has been practiced in northeastern Thailand (Isaan) for generations as an important protein source; the practice is rooted in agricultural communities where insects were seasonal harvests alongside rice and vegetables; Bangkok's insect food culture derives primarily from Isaan migrant workers who brought the food traditions with them; (2) Common edible insects in Bangkok: fried grasshoppers (tang-krai, crispy, seasoned with salt and chili); fried silkworm pupae (non-pai, more pungent, acquired texture); bamboo worms (rot duan, crispy, buttery flavor, considered the most palatable for beginners); ant eggs (kai mot daeng, used in salads, mild flavor); giant water bugs (maeng da, used as essence in sauces and consumed whole — the largest and most challenging entry); fried crickets (ji-jaa, most similar to Western palate familiar texture); (3) Where to find insect food in Bangkok: Chatuchak Weekend Market (specific stalls, particularly in the food section) offers multiple insect vendors with full display platters; Khao San Road insect carts (primarily for tourist consumption, the most available tourist-facing insect experience in Bangkok, primarily bamboo worms and crickets); Or Tor Kor Market (higher quality presentation in organic/premium food context); Isaan restaurants and food areas (more authentic context, insects as condiment or side rather than tourist spectacle); (4) Nutritional and ecological context: edible insects are nutritionally significant — grasshoppers have approximately 35–60% protein by weight; crickets have comparable protein to beef per gram at 1/10th the resource cost (land, water, feed); the FAO (UN Food and Agriculture Organization) has identified insect farming as a sustainable protein source for global food security; Thailand's traditional insect farming and harvesting has attracted international interest in this context; (5) Bangkok insect eating for first-timers: the most accessible Bangkok insect experience for hesitant visitors: (a) bamboo worm (rot duan) — the mildest flavor, the crispiest texture, easiest first insect; described as 'like eating a crispy corn puff with slight buttery flavor'; (b) fried cricket (ji-jaa) — small, very crispy, seasoned well, texture closest to other crunchy snack foods; (c) food context: eating insects at a market stall (sit down, observe Thai customers ordering) is more comfortable than random tourist cart purchases; understanding that Thais eat insects by choice, not poverty, as a flavor and cultural preference changes the experience framing.",
    action: "Bangkok insect food access: Khao San Road insect cart: visible at the entrance to Khao San, most active evening hours; tourist price ฿100–200 per cup/bag; Chatuchak Weekend Market insect vendors: in the food section (near sections 26–27), active Saturday–Sunday 9am–6pm; Or Tor Kor Market (premium): specific vendors seasonally offering quality insects in organic food context; most authentic Bangkok insect eating: find an Isaan restaurant (search 'ร้านอาหารอีสาน' — raan ahaan Isaan) and ask the owner about current insect preparation; some Isaan restaurants have insects as seasonal menu items available to order rather than on permanent display; insect cooking classes: some Bangkok cooking class operators include insect preparation in specialty sessions — check cooking class operators like Silom Thai Cooking School for current offerings.",
  },
];

export function BangkokWildlife() {
  return (
    <div className="rounded-2xl border border-green-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-green-700 mb-3">
        🦎 Bangkok natural side — urban wildlife encounters, city parks & Thai insect food culture
      </div>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-green-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-green-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
