const SPOTS = [
  {
    name: "Bangkok Nail Art Studios — K-Beauty Nails to Thai Traditional",
    emoji: "💅",
    area: "Nail art concentration in Bangkok: Thonglor and Ekkamai K-beauty nail studios (Korean-trained, gel-based sophisticated art); Sukhumvit corridor shops (tourist-friendly, wide price range); lower Sukhumvit budget nail shops (฿150–400 basic manicure); Siam Square and EmQuartier high-end nail salons; stand-alone nail art specialists in Ari and Ratchada neighborhoods",
    price: "Basic manicure (regular polish): ฿150–400; Gel manicure: ฿400–800; Nail art (simple patterns, per nail): ฿30–100 additional; 3D nail art (elaborate): ฿50–200 additional per nail; Full nail set (gel extensions): ฿800–2,500; Korean-style nail art set: ฿1,500–4,000; Pedicure (basic): ฿200–500; Pedicure (gel + art): ฿600–1,500",
    why: "Bangkok's nail art industry offers exceptional quality-to-price ratio — the caliber of nail technician training (particularly Korean-influenced nail academies that have proliferated in Bangkok) means detailed gel nail art available in Bangkok for ฿1,500–3,000 would cost ฿6,000–15,000 in Tokyo or ฿8,000–20,000 in London. Key Bangkok nail art landscape elements: (1) Korean nail culture influence: K-beauty's domination of global nail aesthetics has transferred to Bangkok through Korean-trained nail technicians and Korean nail product brands (OPI Korea, Gelish, Kokoist); Thonglor and Ekkamai nail studios frequently use Korean nail product lines and Korean technique; (2) Thai traditional nail art: traditional Thai nail design (inspired by patterns from Thai classical dance costume — geometric, floral, and khim patterns in gold and jewel tones) offers a culturally distinct alternative to Korean or Western nail aesthetics; (3) Nail academy culture: Bangkok has multiple Korean nail technique academies training Thai nail artists; this educational infrastructure continuously raises the technical ceiling of Bangkok nail work; (4) Nail supply market: Bangkok's nail supply wholesale market (in Pratunam area) provides access to professional nail products at wholesale prices — useful for nail technicians visiting Bangkok to stock materials; (5) Festival/holiday nails: Bangkok nail studios produce particularly elaborate work for Thai holidays (Songkran — water festival, Loy Krathong) when demand for decorative nails peaks.",
    tip: "Bangkok nail art strategy: (1) Thonglor/Ekkamai for Korean-style: the highest concentration of Korean-influenced nail studios with trained artists is in the Thonglor BTS-Ekkamai BTS corridor; Instagram-browsing these studios' work before visiting allows selecting based on portfolio match; (2) Booking ahead for art: basic manicures can be walk-in at most Bangkok nail shops; elaborate nail art (3D, hand-painted details, foil applications) requires booking 1–3 days ahead for the specific artist whose portfolio matches your vision; (3) Reference photos: bringing clear reference photos (or showing Instagram screenshots) ensures communication alignment between client vision and artist interpretation; Bangkok nail artists respond well to detailed reference rather than vague descriptions; (4) Duration planning: basic gel manicure takes 45–75 minutes; elaborate nail art can take 2–4 hours; planning personal schedule around the time investment is important; (5) Currency and tipping: Bangkok nail studio payment is cash (many) or card; tipping is appreciated (฿50–100 is typical for satisfied customers); asking at payment whether tips go to the technician directly confirms the tip routing.",
  },
  {
    name: "Bangkok Beauty Shopping — Thai & K-Beauty Products",
    emoji: "🛍️",
    area: "Beauty retail in Bangkok: EVEANDBOY (multiple Bangkok branches — Bangkok's largest beauty multi-brand retailer); Watsons and Boots pharmacies (widespread, accessible); Sephora Thailand (Siam Paragon, EmQuartier, Central World); local Thai beauty brands at pharmacies; Korean skincare at specialty Korean beauty shops in Thonglor and Korean-community malls",
    price: "Korean BB cream (at EVEANDBOY): ฿250–600; Thai-brand sunscreen (Mistine, Snail White): ฿100–350; Japanese skincare (SK-II, Shiseido, at duty-free comparable prices): ฿800–5,000; K-beauty sheet mask (per piece): ฿80–250; Sunscreen (Sun Protection Factor 50, Thai brand): ฿150–400; Thai herbal brand (Pañpuri, Harnn): ฿400–2,500",
    why: "Bangkok is one of Asia's best beauty shopping destinations — the combination of Thai-produced tropical-climate skincare formulations, excellent K-beauty selection, and accessible Japanese/European brands creates a comprehensive beauty product ecosystem: (1) Thai brand excellence: Thai beauty brands have developed formulations specifically for tropical climates (high SPF, humidity-resistant, oil-control focused); Mistine (mass market), Snail White (snail mucin for the Thai market before global trend), and premium brands (Pañpuri — spa-grade herbal) represent genuinely high quality at Thai price points; (2) EVEANDBOY: Bangkok's dominant multi-brand beauty retailer; carries Thai, Korean, Japanese, and Western beauty brands in accessible formats; EVEANDBOY stores in Siam Paragon, Paragon Department Store, Emporium, and CentralWorld cover Bangkok's beauty retail geography; (3) K-beauty selection: Bangkok's Korean community areas (Thonglor Soi 10, some Sukhumvit areas) have Korean beauty specialty shops importing directly from Korea with full Korean beauty brand access; (4) Duty-free and tourism advantage: foreign visitors can access Thailand's VAT refund (7% on purchases over ฿2,000 per day at registered shops) for beauty purchases — VAT refund at Suvarnabhumi airport; (5) Herbal and natural beauty: Thailand's traditional herbal beauty tradition (using jasmine, ylang-ylang, turmeric, tamarind, pandan) is commercialized in premium form by brands like Pañpuri, Harnn, Erb, and Thann.",
    tip: "Bangkok beauty shopping optimization: (1) EVEANDBOY Siam Paragon branch is Bangkok's largest beauty store; the multi-floor layout covers the complete Thai, Korean, and international beauty spectrum with trained staff; (2) Sunscreen Thailand specialization: Thailand's intense UV environment means Thai-produced sunscreens are formulated for high effectiveness in tropical conditions; Korean sunscreen innovation also produces excellent results in Bangkok's climate; buying sunscreen in Bangkok for the rest of your Thailand trip is economically rational (cheaper than import-price sunscreen and optimized for local conditions); (3) VAT refund paperwork: for beauty product VAT refund, request the VAT refund form (Por.Por.10) at the store cash register at time of purchase; present accumulated forms at airport VAT refund office before departure; (4) Thai brand authenticity: counterfeit Thai beauty products (particularly Snail White and Mistine) exist at markets; purchasing at authorized retailers (Watson's, Boots, EVEANDBOY, department stores) rather than market stalls ensures authenticity; (5) Japanese beauty at Bangkok duty-free: Suvarnabhumi airport duty-free has extensive Japanese beauty brand selection at prices competitive with Japan duty-free; stock up on specific Japanese brands at Suvarnabhumi departure if Japanese pharmacy prices are a reference point.",
  },
  {
    name: "Bangkok Barbershops — Japanese & Classic Thai Culture",
    emoji: "💈",
    area: "Barbershop culture in Bangkok: old-school Thai barbers in residential Bangkok neighborhoods (฿70–150 haircut); Japanese barbershop culture in Thonglor and Ekkamai (Sukhumvit area Japanese community); premium barbershops (Slick Barbershop, The Cutt House, various Thonglor shops); street-side old Thai barbers in Chinatown and Banglamphu",
    price: "Old Thai barber haircut: ฿70–150; Standard Bangkok barbershop haircut: ฿200–400; Premium barbershop (Japanese style, fade + styling): ฿600–1,200; Beard trim (at barbershop): ฿200–400; Hot towel shave: ฿300–600; Full grooming package (hair + beard + facial): ฿800–2,000",
    why: "Bangkok's barbershop culture operates across a remarkable price-quality spectrum: (1) Traditional Thai barbers: old-school Thai barbershops in residential Bangkok neighborhoods offer haircuts for ฿70–150 using traditional Thai technique (specific scissor and clipper patterns that define classic Thai cuts); these are typically older barbers in family shops or street-side stalls near temples and markets; (2) Japanese barbershop culture: Bangkok's substantial Japanese expatriate community has created Japanese-standard barbershops in Thonglor and Ekkamai; Japanese barbershops emphasize precision fading, attention to detail in neckline and sideburn finishing, and the full service ritual (shampoo, styling consultation, cleanup); (3) Premium Bangkok barbershops: inspired by global premium barbershop culture (including Japanese barbershop techniques imported via Korea), Bangkok has multiple premium barbershops with trained staff, quality products, and experience-focused service; (4) Thai massage barbers: some traditional Thai barbers offer traditional Thai head massage with haircut (an inclusion not common in Japanese or Western barbershops); (5) Hot towel shave: the traditional straight razor hot towel shave — experiencing natural decline in Western markets — is readily available at Bangkok's premium barbershops and some traditional Thai barbers at accessible prices.",
    tip: "Bangkok barbershop navigation: (1) Old Thai barber etiquette: traditional Thai barbershops communicate through pointing and basic instruction ('short here', 'keep length here' with gesture); understanding basic Thai numbers for hair length (centimeters) helps specify outcomes; showing a reference photo remains the most reliable communication tool; (2) Japanese barbershop Japanese language: Bangkok's Japanese-community barbershops sometimes have Japanese-speaking staff; knowing that the target customer base is the Thai-Japanese community means English service availability varies; (3) Thonglor barbershop cluster: the Thonglor BTS station area (particularly Thonglor Soi 10 and adjacent streets) has the highest concentration of quality barbershops with trained staff; (4) Barbershop Instagram: Bangkok's quality barbershops maintain active Instagram portfolios; reviewing portfolio work before choosing provides a better style match than walk-in guesswork; (5) Weekend booking: Bangkok's better barbershops are busy on weekend mornings (peak time for working professionals); weekday morning appointments provide less wait time; some accept walk-ins at quieter times.",
  },
];

export function BangkokNailArt() {
  return (
    <div className="rounded-2xl border border-pink-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-pink-700 mb-3">
        💅 Bangkok beauty culture — nail art studios, K-beauty shopping & Japanese barbershops
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-pink-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-pink-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
