const SPOTS = [
  {
    name: "Silom — Bangkok's Financial District, LGBT Heart & After-Dark Transformation",
    emoji: "🏦",
    area: "Silom district, central Bangkok: BTS Sala Daeng (intersection with Silom Road and Rama IV Road); BTS Chong Nonsi (southern Silom); MRT Si Lom station (near Sala Daeng BTS, interchange point); Silom Road (main commercial artery, 2km stretch of financial institutions, office towers, restaurants, and nightlife); Patpong Night Market (Soi Patpong 1 and 2, between Silom Road and Suriwong Road, tourist market + nightlife); Soi 4 Silom (Bangkok's LGBT nightlife strip, Telephone Bar, DJ Station, G Bar, The Stranger, Balcony); Thaniya Road (Japanese entertainment area, parallel to Silom); Dusit Thani area (historic Dusit Thani hotel, Lumpini Park adjacent); Pan Road (restaurant corridor south of Silom)",
    price: "Silom district costs: business lunch (financial district restaurants): ฿150–350; dinner at Silom restaurants (mid-range): ฿200–500; Patpong Night Market souvenir: ฿100–500 (negotiable, standard tourist pricing); LGBT nightlife Soi 4 bar entry: typically free entry, drinks ฿120–250; DJ Station (nightclub): entry ฿200–300 includes 1 drink; Patpong 'ping pong show' entry fee: decline (tourist scam — advertised ฿10, billed ฿2,000+); Silom office co-working (FYI Center, other business centers): ฿200–500/day; Lumpini Park entry: free",
    why: "Silom's character is defined by Bangkok's most dramatic day-to-night transformation of any major Bangkok zone: (1) Silom by day — Bangkok's financial core: Silom Road is home to Bangkok's highest concentration of international banks, insurance companies, law firms, and professional services; the daytime Silom is a professional Bangkok — suited workers, business lunches at Japanese restaurants on Thaniya Road, international hotel lobbies, and the commercial density of a major Asian business district; (2) Silom by night — LGBT and nightlife transformation: after 8pm, Silom's character shifts significantly; Soi 4 Silom becomes Bangkok's most visible LGBT nightlife strip — bars, clubs, and drag shows operating openly and freely; the Patpong area activates as a tourist market and entertainment complex; the Thaniya Road Japanese entertainment area comes alive; the same streets that functioned as a financial district now operate as nightlife venues; (3) Soi 4 Silom's significance: Bangkok's LGBT community and its international visitors have made Soi 4 Silom one of Southeast Asia's most established and welcoming LGBT entertainment zones; the bars (Telephone, Balcony) operate openly and without harassment; Bangkok has no legal same-sex marriage recognition but the social reality in entertainment zones like Soi 4 is genuinely tolerant; DJ Station is Soi 4's main nightclub (gay-oriented, mixed international/Thai clientele); (4) Patpong Night Market distinction: Patpong Night Market (set up in the middle of Soi Patpong) is Bangkok's most famous tourist night market — full of Bangkok souvenir shops, counterfeit goods, and the 'ping pong show' touts that approach tourists; the market is fine to browse (watch for pickpockets, negotiate hard on prices) but the 'show' touts should be firmly declined; the upstairs establishments operate with fake menus and charge ฿2,000–5,000 for entry plus drinks — this scam has operated for decades; (5) Silom's quality restaurant scene: the area between Silom Road and Sathorn Road has some of Bangkok's best established restaurants — Issaya Siamese Club (Jim Thompson-era heritage building, garden restaurant, Jim Thompson's former residence), Blue Elephant (Thai royal cuisine, historic building), and numerous quality Thai and international restaurants along Pan Road and the connecting sois.",
    tip: "Silom practical visitor guide: (1) Accessing Silom via BTS: BTS Sala Daeng is the primary Silom access point; the station is directly above the Silom/Rama IV intersection; from Sala Daeng, Patpong Night Market is a 5-minute walk east; Soi 4 Silom LGBT strip is a 3-minute walk south; (2) Lumpini Park from Silom: Lumpini Park (Bangkok's version of Central Park) is 5 minutes walk from BTS Sala Daeng; the park is a genuine Bangkok green space used by residents for morning exercise (5–8am is peak exercise time), evening socializing, and weekend recreation; the park hosts water monitors (large lizards, non-threatening, common in Bangkok parks) and is the best easily-accessible urban green experience in central Bangkok; (3) Patpong Night Market pricing: Patpong souvenir market pricing is tourist-oriented; initial quotes are 2–3x expected final price; negotiating to 40–50% of first quoted price is reasonable for most items; T-shirts, Thai pants, magnets, and tourist items are similarly priced across all Bangkok tourist markets (Patpong, Khao San, Chatuchak tourist section); (4) Thai massage after Silom business day: Silom has numerous Thai massage shops serving after-work office workers and hotel guests (open until midnight); these are mid-tier quality but professionally managed — better than tourist zone massage shops but lower quality than dedicated spa establishments; (5) Silom to Sathorn connectivity: Silom and Sathorn districts are adjacent and connected; BTS Chong Nonsi links the two; the Sathorn pier (Sathorn/Central Pier, BTS Saphan Taksin) is 10 minutes walk from Silom's southern end — this provides easy river boat access from Silom to riverside attractions.",
  },
  {
    name: "Sathorn — Embassy Row, Riverside Luxury & Bangkok's Consular District",
    emoji: "🏛️",
    area: "Sathorn district, southern Bangkok: BTS Surasak (Sathorn Road western), BTS Chong Nonsi (Sathorn Road central), BTS Saphan Taksin (eastern Sathorn, Chao Phraya Sathorn Pier adjacent); Sathorn Road (main artery, wide boulevard with embassy compounds); South Sathorn Road (residential area with houses and small sois); Embassy compounds on Sathorn and adjacent roads: US Embassy (Wireless Road, technically Lumpini/adjacent district), UK Embassy (Wireless Road), German Embassy, French Embassy, Australian Embassy; Sathorn Unique Tower ('Ghost Tower' — abandoned luxury high-rise, no official visits permitted); Dean & DeLuca (American gourmet food store, Sathorn/Rama IV corner); COMO Metropolitan hotel (high design, Sathorn Road); Naraiphand duty-free (South Sathorn Road)",
    price: "Sathorn district costs: Sathorn Road restaurant lunch: ฿200–500; riverside dining from Sathorn (boat to nearby restaurants): ฿300–1,500; hotel stay in Sathorn (mid-range): ฿2,500–5,000; luxury riverside hotel Sathorn (Capella, Mandarin Oriental vicinity): ฿7,000–30,000+; Grab from Sathorn to Sukhumvit Asok: approximately ฿100–180 depending on traffic; Thai massage near Sathorn: ฿300–500 in residential soi shops; Dean & DeLuca coffee: ฿150–250",
    why: "Sathorn's character as Bangkok's consular and embassy district gives it a distinct character from the rest of inner Bangkok: (1) Sathorn's consular character: Sathorn Road and adjacent Wireless Road (Witthayu Road) host the majority of Bangkok's foreign embassy compounds; the combination of embassy security perimeters, tree-lined boulevards, and residential compounds creates a quieter, more spacious character than Bangkok's commercial districts; the embassy compounds are not accessible to the public but the visual character of the consular district is distinct; (2) Sathorn as riverside luxury gateway: Sathorn's southern end connects directly to the Chao Phraya River (Sathorn Central Pier, BTS Saphan Taksin); this makes Sathorn one of the most convenient bases for river transport access — river ferries to Grand Palace, Asiatique shuttle, and Wat Arun all depart from or near Sathorn Pier; riverside luxury hotels (Capella Bangkok at Charoenkrung Road/Sathorn boundary, COMO Metropolitan for design hotels) position themselves near this river access; (3) Sathorn Unique Tower — Bangkok's most famous abandoned building: the abandoned Sathorn Unique Tower (a luxury residential project abandoned during the 1997 Asian Financial Crisis) has become one of Bangkok's most photographed locations and an unofficial urban exploration destination; the Thai authorities have attempted to restrict access due to safety concerns; photography of the exterior is unrestricted, but interior access is illegal and dangerous — the building has claimed lives of urban explorers; the tower is visible from surrounding streets and from the Chao Phraya river; (4) COMO Metropolitan as Sathorn design landmark: the COMO Metropolitan Bangkok (on South Sathorn Road) is one of Bangkok's most architecturally distinctive luxury hotels — the COMO chain's signature minimalist design aesthetic is fully expressed in the property; the hotel's Nahm restaurant (by chef David Thompson) was one of Bangkok's Michelin-starred Thai restaurants before closing; the COMO Metropolitan represents Sathorn's premium design hospitality; (5) Sathorn as Bangkok resident neighborhood: beyond the embassy zone and luxury hotels, Sathorn has substantial residential character in its sois — Thai upper-middle-class families, expats in long-stay compounds, and single professionals in smaller apartments occupy the quieter Sathorn sois; the residential character makes Sathorn one of the more neighborhood-feeling inner Bangkok areas compared to the commercial Sukhumvit or tourist-heavy Rattanakosin.",
    tip: "Sathorn practical visitor guide: (1) Sathorn Pier for river access: BTS Saphan Taksin (end of Silom BTS line) leads directly to Sathorn Central Pier (Tha Sathon); this pier is Bangkok's most important river transport hub — Chao Phraya Express Boats, the free Asiatique shuttle ferry, private long-tail boat charter starting points, and river taxi access all available here; (2) Consular services at Sathorn embassies: foreign visitors requiring passport renewal, emergency travel documents, or consular assistance should locate their country's Bangkok embassy (mostly on Sathorn Road, Wireless Road, or nearby); appointment booking typically required via embassy website; emergencies contact the duty officer line listed on embassy website; (3) Sathorn's evening dining character: Sathorn Road restaurants in the evening serve a mix of embassy community, hotel guests, and Bangkok residents — the character is less tourist-oriented than Sukhumvit and more business/resident-focused; restaurant quality is generally high with less tourist markup than tourist-zone equivalents; (4) COMO Shambhala spa at COMO Metropolitan: the COMO Metropolitan's spa (COMO Shambhala) is accessible as a walk-in spa experience (treatments ฿3,000–8,000) without being a hotel guest; it is one of Bangkok's most design-focused spa spaces; (5) Sathorn security zone awareness: embassy perimeters on Sathorn Road have security infrastructure (vehicle barriers, CCTV) that makes walking along the road near embassy gates feel more constrained than typical Bangkok soi navigation; this is normal and does not indicate threat — embassy security zones are standard diplomatic practice globally.",
  },
  {
    name: "Bang Rak & Bangrak — Bangkok's Oldest International Quarter, Charoen Krung & River Heritage",
    emoji: "⛪",
    area: "Bang Rak district, central Bangkok: Charoen Krung Road (Bangkok's first road, constructed 1861–1864, runs parallel to Chao Phraya River through Bang Rak, Old Bangrak, and Chinatown areas); BTS Saphan Taksin (eastern Bang Rak); BTS Surasak (western approach); Bangrak Mosque (historic Muslim community mosque); Holy Rosary Church (Wat Kalawa — 1787, Bangkok's oldest Christian church); Bang Rak Fire Station (classic Charoen Krung building); ICON SIAM (massive mall on Thonburi bank, accessible by shuttle from Sathorn Pier); Old Bangkok Inn (heritage area); Bangkok 1899 (hotel in heritage Charoen Krung building); TCDC (Thailand Creative & Design Center — Charoen Krung section); River City Shopping Complex (antiques and art)",
    price: "Bang Rak/Charoen Krung costs: TCDC annual membership (required for full library access): ฿100 (day pass); Charoen Krung gallery visits: typically free; Old Bangkok architecture photography: free (public streets); River City antique shopping: ฿500–200,000+ depending on piece; Holy Rosary Church visit: free (donation appreciated, mass schedule); hotel accommodation in Charoen Krung heritage area: Bangkok 1899 ฿2,500–5,000; Capella Bangkok (highest luxury in the area): ฿8,000–30,000+; Asiatique shuttle ferry from Sathorn: free",
    why: "Bang Rak and the Charoen Krung corridor represent Bangkok's most layered historical urban environment and are underappreciated by most visitors: (1) Charoen Krung as Bangkok's first road: Charoen Krung Road (New Road, constructed 1861–1864 under King Rama IV at the request of foreign diplomatic missions in Bangkok) is Bangkok's first planned modern road; it was built to serve the foreign commercial and diplomatic community along the Chao Phraya riverfront; the road runs approximately 10km through Bang Rak, Talat Noi, and Chinatown; the buildings along Charoen Krung represent Bangkok's earliest colonial-era, Sino-European architectural heritage; (2) The Charoen Krung creative regeneration: since approximately 2015, Charoen Krung has experienced a creative industry regeneration — boutique hotels in renovated shophouses, independent galleries, design studios, craft coffee shops, and the TCDC (Thailand Creative & Design Center) moved from Emporium to Charoen Krung's old General Post Office building; the area now represents Bangkok's most developed 'creative district' outside of the Bang Sue area; (3) Religious heritage density in Bang Rak: Bang Rak contains Bangkok's oldest Catholic church (Holy Rosary Church, 1787, built by Portuguese traders), an established Muslim community (Bang Rak Mosque, descendant of the Cham Muslim community brought from Cambodia), and various Chinese folk religion temples; the religious coexistence along Charoen Krung reflects Bangkok's historical multi-community character; (4) River City and Thai antiques: River City Shopping Complex (a multi-story riverside mall near Charoen Krung, near Si Phraya pier) houses Bangkok's most established antiques trade — Thai antiques, Burmese lacquerware, Cambodian textiles, bronze Buddhas, and Asian art; River City hosts serious antique dealers alongside tourist-oriented shops; pieces of genuine antiquity (pre-1940 items) require Fine Arts Department export permits; (5) Asiatique as Bang Rak's major attraction: Asiatique The Riverfront (a converted historic docklands development, evening entertainment complex with restaurants, bars, carnival rides, shopping) is accessible by free shuttle ferry from Sathorn Pier; it opened in 2012 on the site of the former East Asiatic Company docks; Asiatique's historical connection to the Bangkok riverfront trade legacy gives it more context than a typical commercial mall development.",
    tip: "Bang Rak/Charoen Krung practical visitor guide: (1) TCDC for Bangkok design scene immersion: the Thailand Creative & Design Center (TCDC) in the old General Post Office building on Charoen Krung is Bangkok's best single venue for Thai design, graphic art, industrial design, and creative industry cultural programming; exhibitions rotate, permanent library of design references available to members, and the building itself (restored 1930s General Post Office) is architecturally significant; (2) Charoen Krung walking route suggestion: entering at BTS Saphan Taksin (Exit 2), walking north along Charoen Krung Road for 2–3km, visiting Holy Rosary Church (open most mornings), exploring riverside sois, gallery-hopping at independent Charoen Krung galleries, reaching Talat Noi (the heritage tinsmith neighborhood), and continuing to Chinatown provides Bangkok's best heritage walking experience; (3) Bang Rak street food on Charoen Krung sois: the sois (side streets) off Charoen Krung have established local food vendors serving the Bang Rak residential community — these are among Bangkok's most authentic urban food environments without tourist-market positioning; ordering by pointing with clear body language works in these non-tourist-oriented stalls; (4) Asiatique evening timing: Asiatique is primarily an evening destination (opens 5pm, busiest 6–10pm); the atmosphere is more pleasant than during daylight as the riverfront setting benefits from cooling evening temperatures and illuminated riverside scenery; arriving by the Sathorn shuttle ferry rather than Grab provides the visual experience of the Chao Phraya approach; (5) River City antique authentication: before purchasing antiques at River City, understand the Fine Arts Department export restriction on items deemed national heritage; for Buddhist images (important category) over 200 years old, export is prohibited regardless of purchase; dealers at River City can explain specific piece exportability status.",
  },
];

export function BangkokSathorn() {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-slate-700 mb-3">
        🏦 Bangkok inner districts — Silom financial/LGBT hub, Sathorn embassy row & Bang Rak heritage
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-slate-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-slate-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-slate-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
