const SPOTS = [
  {
    name: "Bangkok's LGBTQ+ Community & Pride Culture",
    emoji: "🏳️‍🌈",
    area: "Bangkok LGBTQ+ hub: Silom Soi 2 and Soi 4 (the traditional gay district, bars, clubs, lifestyle venues); Silom Road corridor; Pride events: Bangkok Pride (annual June parade, Silom Road); Pattaya Gay Festival (October); Trans cultural center: Saphan Kwai area; LGBTQ+ friendly venues: Thong Lo, Ekkamai, RCA nightclub cluster; resources: Rainbow Sky Association of Thailand (RSAT), Bangkok Rainbow Organization",
    price: "Silom Soi 2/4 bar cover (with drinks): ฿150–500; Balcony Bar Silom (famous LGBTQ+ bar, no cover): free–฿200; DJ Station (large club, Silom): ฿250–500 entry; Bangkok Pride parade entry: free; Transgender cabaret show (Calypso): ฿800–1,200; Go-go bar shows: ฿100–300 drink minimum; LGBTQ+ yoga/wellness event: ฿300–800",
    why: "Bangkok holds a genuinely remarkable position in global LGBTQ+ culture — a Buddhist-majority country that has developed one of Asia's most visible and vibrant LGBTQ+ communities without formal legal recognition of same-sex relationships: (1) Cultural context: Thai Buddhism's relative tolerance of gender and sexual diversity (no explicit condemnation in Thai Buddhist doctrine) combined with Thailand's historical gender traditions (kathoey — third gender — has always been part of Thai cultural fabric) created a more accommodating social environment than many comparable societies; (2) Silom Soi 2 & 4 — Asia's most established gay village: these two connecting streets in Bangkok's Silom financial district contain one of Asia's oldest established gay nightlife districts; bars, restaurants, saunas, and community gathering spaces have operated here for decades; (3) Bangkok Pride: Bangkok Pride (annual June event) has grown into one of Southeast Asia's largest Pride events; the Silom Road parade route draws hundreds of thousands of participants and observers; the Pride week events (film screenings, community gatherings, parties) extend well beyond the parade day; (4) Kathoey culture and trans visibility: Thailand's third-gender (kathoey) tradition means transgender visibility in Bangkok is extremely high by global comparison; trans women work across all service industry sectors, hold professional positions, and are part of everyday Thai life in ways that visitors from less inclusive societies often find surprising; (5) Same-sex partnership legal progress: Thailand's Marriage Equality Act, passed in 2024 and effective from January 2025, makes Thailand the first country in Southeast Asia to legalize same-sex marriage; this significant legal change reflects growing social acceptance and political will.",
    tip: "Bangkok LGBTQ+ visitor guidance: (1) Public affection context: while Bangkok's LGBTQ+ community spaces are openly welcoming, public displays of affection between same-sex couples attract varying reactions depending on location; Silom Soi 2/4 and Pride events are fully accepting; conservative religious sites and family-oriented residential neighborhoods are less so; reading the environment is the practical approach; (2) Silom timing: Silom Soi 2 and 4 operate primarily as evening destinations (bars open from approximately 9pm); daytime Silom is Bangkok's financial district with standard business character; arriving after 10pm for the most active atmosphere; (3) Trans-inclusive establishments: Bangkok's LGBTQ+ establishments are generally trans-inclusive across the spectrum; Bakkalee Cabaret (Silom), Balcony Bar, and the broader Silom community are welcoming of trans visitors and performers; (4) Beyond Silom: Bangkok's LGBTQ+ community has diversified beyond Silom's traditional gay village; Thong Lo and Ekkamai have lesbian-friendly café spaces; RCA has LGBTQ+-welcoming clubs; the broader Bangkok café scene has pride-flag-flying establishments across multiple neighborhoods; (5) LGBTQ+ health resources: The Thai Red Cross Anonymous Clinic (Henri Dunant Road) and Rainbow Sky Association of Thailand provide confidential health services and LGBTQ+-affirming healthcare for visitors and residents.",
  },
  {
    name: "Bangkok Transgender Culture — Kathoey Heritage & Identity",
    emoji: "🌺",
    area: "Bangkok kathoey cultural landscape: beauty pageants (Miss Tiffany Universe, Miss International Queen in Pattaya); professional entertainers in cabaret; hospitality industry visibility; sex education inclusion in Thai public school curriculum; trans healthcare: Bumrungrad, Yanhee Hospital (gender affirmation surgery); LGBTQ+ community organizations: Thai Transgender Alliance, Sister Foundation Chiang Mai (HIV/trans health)",
    price: "Miss Tiffany Universe broadcast (free on Thai national TV); Calypso Cabaret Bangkok (LGBTQ+-celebrating show, Asiatique): ฿900–1,400; Yanhee Hospital gender affirmation surgery (GAS) consultation: ฿3,000–5,000; SRS (male-to-female surgery) at Thai specialist hospitals: ฿200,000–450,000; Beauty queen pageant tickets: ฿500–3,000; Trans-inclusive training/workshop: ฿500–2,000",
    why: "Thailand's relationship with trans identity and kathoey culture is one of the world's most complex and visible expressions of gender diversity: (1) Kathoey definition and history: the Thai term kathoey (กะเทย) describes people assigned male at birth who identify and present as female; historically, kathoey were accepted participants in Thai traditional dance, entertainment, and religious contexts; Thai Buddhist folk tales include gender-crossing figures in spiritual narratives; (2) Miss Tiffany Universe: Thailand's national transgender beauty pageant (Miss Tiffany Universe, held annually in Pattaya) is one of the world's largest trans beauty pageants; the event is broadcast nationally on mainstream Thai television and draws significant audience; trans beauty and talent are genuinely celebrated in Thai mainstream entertainment; (3) Beauty industry dominance: trans women (particularly kathoey) have a significant cultural footprint in Thailand's beauty and fashion industries; Thai beauty pageant culture was significantly shaped by kathoey participants and aesthetic; (4) Gender affirmation surgery (GAS) in Bangkok: Thailand's specialist gender affirmation surgery hospitals (PAI — Preecha Aesthetic Institute, Bumrungrad GAS program, Yanhee Hospital) have international reputations for surgical excellence in male-to-female procedures; medical tourists from over 50 countries travel to Bangkok for GAS; lower costs (20–40% of US/European prices), experienced surgical teams, and established post-operative care infrastructure make Bangkok a leading global destination; (5) Socioeconomic reality: despite cultural visibility, many Thai trans women face discrimination in formal employment; entertainment, beauty, and sex work sectors absorb disproportionate numbers of trans women; advocacy organizations work to expand formal employment acceptance and legal protections.",
    tip: "Engaging respectfully with Bangkok's trans culture: (1) Terminology respect: using 'kathoey' is context-specific; trans women who identify primarily as women may prefer female pronouns and terms rather than kathoey; following the individual's lead is the respectful approach; (2) Photography respect: kathoey performers and entertainers in cabaret settings are typically happy to be photographed (often offering photo opportunities for tips ฿50–100); photographing trans individuals in everyday settings without consent follows the same etiquette as photographing any person; (3) Cabaret shows as community celebration: Bangkok's transgender cabaret (Calypso at Asiatique, Mambo at Siam Square, Alexey Show at Sukhumvit) present trans performance as entertainment; these shows are a gateway to visibility for Thai trans culture but represent a specific subset of trans experience; (4) Medical tourism research depth: anyone considering gender affirmation surgery in Bangkok should research extensively beyond online testimonials; verified surgeon credentials, hospital accreditation (JCI accreditation at Bumrungrad), post-operative care plans, and emergency protocols matter critically in major surgical decisions; (5) Support organizations: transgender visitors seeking community connection or health resources can contact the Thai Transgender Alliance or the Bangkok-based LGBTQ+ support network; visiting trans medical tourists benefit from pre-arranging post-operative accommodation and care coordination through the surgical hospital's international patient services.",
  },
  {
    name: "Bangkok's Lesbian Community & Women's Spaces",
    emoji: "🌸",
    area: "Bangkok lesbian and queer women's spaces: Maggie Choo's (lesbian-friendly, Silom); Scratch Dog Bar (lesbian bar, Silom); feminist café culture (Thong Lo, Ekkamai); Women's groups: Bangkok Women's Group, YWCA Bangkok; social organizations: Anjaree Foundation (lesbian rights, established 1986); academic: Faculty of Gender Studies, Thammasat University; events: Bangkok Dyke March (irregular, Pride-adjacent)",
    price: "Lesbian-friendly bars/cafés: ฿100–400/drink; Women's networking events (expat groups): free–฿300; Feminist book café events: free–฿200; LGBTQ+ film screenings: ฿150–400; Women's sport and fitness (Muay Thai for women): ฿400–800/session; Gender studies public lectures (Thammasat, Chulalongkorn): often free",
    why: "Bangkok's queer women's community has built a vibrant but less commercially visible presence compared to Bangkok's gay male scene: (1) Dee-tom (lesbian) cultural tradition: Thai lesbian identity has its own cultural vocabulary; dee (ดี้) refers to feminine-presenting lesbians while tom (ทอม, from 'tomboy') refers to masculine-presenting lesbians; this dee-tom gender expression framework differs from Western butch-femme or lesbian identities; (2) Anjaree Foundation (founded 1986): one of Asia's oldest women's same-sex rights organizations; the Anjaree Foundation's pioneering work in documenting Thai lesbian history, organizing community, and advocating for recognition established Thailand's queer women's rights movement; (3) University feminist activism: Thai universities (Thammasat, Chulalongkorn, Mahidol) have active feminist and gender studies communities; student activism around gender-based violence, workplace equality, and LGBTQ+ rights drives progressive social change; (4) Café culture and women's spaces: Bangkok's café culture has produced explicitly feminist and women-centered spaces; Ekkamai, Thong Lo, and Ari neighborhoods have queer women-friendly cafés where same-sex couples and women's social groups gather without the male-dominated bar atmosphere; (5) International expat queer women's community: Bangkok's international expat community includes a significant queer women's network; groups including Bangkok Women's Group and expat social networks organize events and social activities accessible to visitors.",
    tip: "Bangkok queer women's community access: (1) Finding community online: Bangkok's lesbian and queer women's community organizes primarily through Facebook groups, Instagram, and WhatsApp (WeChat for Chinese-speaking members); searching 'Bangkok LGBT women' or 'Bangkok lesbian community' on Facebook provides current event listings and group membership; (2) Tom-dee navigation for visitors: Western visitors should be aware that the tom-dee framework does not map directly onto Western butch-femme or gender expressions; being open to learning Thai queer women's cultural vocabulary enriches the community experience; (3) Female-only spaces respect: some Bangkok women's wellness spaces (spas, onsen, some fitness classes) are female-assigned-at-birth spaces by venue policy; trans women's inclusion policies vary; asking the establishment directly before visiting avoids misunderstanding; (4) University campus access: Thammasat and Chulalongkorn University gender studies public events are typically open to community members; checking university event pages (Facebook or official university portals) identifies upcoming public lectures, film screenings, and community gatherings; (5) Safety for visible queer women couples: Bangkok is generally safe for queer women couples; public affection is read differently on women than men due to the cultural norm of Thai women expressing non-romantic physical affection (hand-holding, close walking) regardless of orientation; queer women couples are often read as friends rather than couples, which can feel invisible but rarely produces negative responses.",
  },
];

export function BangkokLGBTQ() {
  return (
    <div className="rounded-2xl border border-purple-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-purple-700 mb-3">
        🏳️‍🌈 Bangkok LGBTQ+ guide — Pride culture, kathoey heritage & queer women's community
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-purple-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-purple-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
