const SPOTS = [
  {
    name: "Thai Buddhism — Understanding the Faith that Shapes Bangkok",
    emoji: "☸️",
    area: "Thai Theravada Buddhist landmarks: Wat Pho (reclining Buddha, massage school, oldest wat in Bangkok); Wat Phra Kaew (Temple of the Emerald Buddha, Grand Palace complex); Wat Arun (Temple of Dawn, Thonburi bank); Wat Saket (Golden Mount); Wat Benchamabophit (Marble Temple, Dusit area); Wat Traimit (solid gold Buddha, Chinatown); Wat Mahathat (Tha Phra Chan, meditation center, Vipassana programs)",
    price: "Wat Pho entry: ฿200; Wat Phra Kaew/Grand Palace entry: ฿500; Wat Arun entry: ฿100; Wat Benchamabophit entry: ฿20; Wat Traimit: ฿40; Wat Mahathat (free for meditation); Making merit at temple: any amount; Temple tour guide: ฿300–800/2 hours; Tam bun (making merit) donation: typically ฿20–100 at donation boxes",
    why: "Thai Buddhism is the most direct influence on Bangkok's culture, aesthetics, architecture, time structure, and social organization: (1) Theravada tradition: Thailand follows the Theravada (Hinayana) school of Buddhism, emphasizing personal practice and the monasteries as the primary institution of religious life; this differs from Mahayana Buddhism (China, Japan, Korea) and Tibetan Vajrayana; (2) Thai Buddhist cosmology and merit (bun): the Thai Buddhist concept of merit (bun, บุญ) — good karma accumulated through religious acts — drives Bangkok's extraordinary religious donations (temple building, offering food to monks, releasing animals, financing Buddhist projects); the belief that merit improves future lives and current fortune is a daily behavioral driver; (3) Monastic system: Thailand's Buddhist monks (phra, พระ) are revered as fields of merit; approximately 300,000 monks and novices serve in Thailand's 40,000+ temples; the practice of temporary ordination (men entering monkhood for days to months, typically before marriage or after a parent's death) means a significant proportion of Thai men have personal monastic experience; (4) Buddhist calendar and festivals: Thai Buddhist festivals define Bangkok's social calendar; Makha Bucha (full moon, Febuary/March), Visakha Bucha (full moon, May — the most sacred Buddhist holiday), and Asahna Bucha (full moon, July — marking the beginning of Buddhist Lent/Khao Phansa) are national public holidays when alcohol sales are prohibited and temple activities intensify; (5) Temple architecture typology: Bangkok's Buddhist temples (wat) follow a consistent spatial typology: the bot (ordination hall) is the most sacred space (8 boundary stones mark it as a consecrated ordination space); the viharn (sermon hall) is secondary; chedis (stupas) contain sacred relics; Mondops house specific Buddha images or scriptures; the khutho (sermon gong) marks time.",
    tip: "Visiting Buddhist temples in Bangkok: (1) Dress code enforcement: Bangkok's most visited temples (Wat Pho, Grand Palace/Wat Phra Kaew) enforce strict dress codes: shoulders covered, knees covered (sarong wraps available to borrow at Grand Palace entrance); carrying a lightweight wrap or thin long-sleeved shirt for temple visits prevents being turned away; (2) Monk interaction etiquette: speaking to monks is generally acceptable (monks often welcome conversation with foreigners to practice English); women should never touch a monk or hand anything directly to a monk (items for monks are placed on a cloth or surface for the monk to pick up); monks sitting in the first-class sections of Thai transport is normal — they have priority seating by religious convention; (3) Alms-giving (tak bat): in Bangkok neighborhoods with active temple communities, you may witness monks collecting alms early morning (typically 6–8am); participating in offering food as merit-making is possible (buying cooked food appropriate for monks at vendors near temples who sell specifically for this purpose); (4) Temple-to-café transition: many Bangkok temples now have cafes or shops within the complex (Wat Pho has a sala and shop); visiting temples during cooler morning hours (before 10am) when monks are active provides the most authentic temple atmosphere; (5) Vipassana meditation at Wat Mahathat: Wat Mahathat's Section 5 offers English-language Vipassana meditation instruction daily (morning and afternoon programs); this is one of Bangkok's few opportunities to engage with authentic monastic Buddhist practice in an English-accessible format.",
  },
  {
    name: "Thai Buddhist Merit-Making & Daily Practice",
    emoji: "🙏",
    area: "Bangkok merit-making locations: any neighborhood temple; Erawan Shrine (Brahma, not technically Buddhist but merit-making); San Phra Phum (spirit houses at all properties); Golden Buddha at Wat Traimit (Chinatown); Lak Mueang (City Pillar Shrine, near Grand Palace); release of animals: small turtles or birds near major temples; flower market (Pak Klong Talat) supplies for offering lotus, jasmine, incense",
    price: "Temple donation box: any amount (฿20–100 typical); Lotus bud offering set: ฿20–50; Incense bundle: ฿10–20; Gold leaf for applying to Buddha statues: ฿20–50; Bird release (for merit): ฿20–50 per bird; Turtle release: ฿50–200; Food offering for monks (alms food): ฿50–200; Hired monks for home ceremony: ฿2,000–10,000+",
    why: "Thai Buddhist merit-making practices pervade everyday Bangkok life in ways visitors observe without necessarily understanding: (1) The merit economy: Bangkok's extraordinary religious economy (temples receive billions of baht annually in donations from Thai people) is driven by the belief that dana (giving) generates merit; the wealthier the giver, the more elaborate the merit-making potential (founding hospitals, constructing Buddha statues, funding monks' educations); (2) Morning alms (tak bat, ตักบาตร): the morning alms procession (typically 6–8am) is one of Bangkok's most distinctive daily rituals; monks walk in procession with their alms bowls; laypeople offer sticky rice, cooked food, and money; participating requires understanding the protocol (kneel when offering, avoid touching monks); (3) Spirit houses (san phra phum, ศาลพระภูมิ): every Bangkok property from convenience stores to five-star hotels maintains a spirit house for the land spirit (Chao Thi/Phra Phum); daily offerings (flowers, water, incense, red fanta — preferred by some spirits) maintain the spirit's goodwill; Bangkok's spirit house market (craftsmen make elaborate miniature Thai house spirit dwellings) is commercially significant; (4) Lottery and merit intersection: Thailand's Government Lottery (biweekly draw) is enormously popular; Bangkokians seeking lucky lottery numbers visit specific temples and shrines believed to provide number-revealing signs; Wat Traimit, Phra Phrom (Erawan Shrine), and various city pillar shrines are frequented for this purpose; (5) Buddhist merit during life transitions: Thai Buddhism marks all major life events (birth, coming-of-age, marriage, death) with specific religious ceremonies; monks are invited to new homes, businesses, and vehicles to chant blessing verses (a distinctly Thai religious service); the sound of chanting monks at 6am in a Bangkok neighborhood marks a nearby house blessing ceremony.",
    tip: "Understanding Bangkok merit practices as a visitor: (1) Participating respectfully in offerings: visitors can participate in temple offering (dropping coins in the series of donation bowls at Wat Pho, placing lotus flowers at Buddha image base, lighting incense) without being Buddhist; treating the act as respectful engagement rather than performance for photographs is the appropriate approach; (2) Animal release ethics: the practice of releasing birds and turtles for merit (the released creatures carry merit for the releaser) has been significantly criticized by animal welfare advocates; captive-bred birds sold in small cages near temples and immediately recaptured after release is a commercial cycle; the Buddhist concept of merit from genuine liberation has been corrupted in this commercial form; (3) Red Fanta significance: Thai spirit houses often have offerings of red Fanta (carbonated strawberry drink); this tradition (spirits are believed to prefer this sweet red beverage) has become so normalized that red Fanta is the de facto standard spirit house drink offering rather than any traditional beverage; (4) Making merit at restaurants: many Bangkok restaurants participate in merit-making by providing free meals to monks and low-income individuals on specific Buddhist holy days (Wan Phra — lunar calendar Buddhist sabbath days); these days are typically marked at temple gates and restaurant entrances; (5) Buddhist art and iconography: Bangkok's Buddhist images follow precise iconographic rules (mudra — hand positions — indicate specific states or teachings; Phra Kaew is in the specific pose related to the rainy/dry season retreat); learning to read basic mudra significantly enriches temple visits by revealing what specific images are depicting.",
  },
  {
    name: "Meditation & Spiritual Retreat in Bangkok",
    emoji: "🧘",
    area: "Bangkok meditation centers: Wat Mahathat Section 5 (Phra Nakhon, Vipassana program, English); Suan Mokh International Dhamma Hermitage (Surat Thani, 10-day retreat within accessible train distance); House of Dhamma (Ladprao, monthly Vipassana); Dhammakaya Temple (Pathum Thani, 30km north of Bangkok — controversial large temple, free meditation); Urban meditation: POOJA (Ekkamai yoga and meditation); Buddhist retreat: World Fellowship of Buddhists (Bangkok headquarters, Sukhumvit 24)",
    price: "Wat Mahathat daily meditation program: free (donations welcome); House of Dhamma monthly retreat: ฿1,500–3,000; Dhammakaya free meditation program: free; World Fellowship of Buddhists meditation instruction: free; Yoga/meditation hybrid (urban studio): ฿300–800/session; 10-day Vipassana course (Suan Mokh or Goenka center near Bangkok): free (dana donation); Private Buddhist teacher consultation: typically by donation",
    why: "Bangkok offers access to meditation practice at multiple levels of intensity and commitment: (1) Vipassana (insight meditation) accessibility: the Theravada Buddhist meditation tradition of Vipassana (noting impermanence through observation of physical sensations) is the dominant meditation tradition taught in Thai temples; Bangkok's temple centers offering English-language Vipassana instruction provide direct access to a living contemplative tradition; (2) Wat Mahathat's practical Vipassana: Section 5 of Wat Mahathat (the temple adjacent to Thammasat University, visible from the river) offers free English-language sitting meditation and walking meditation instruction in daily programs; no advance booking required; the setting is authentic (a functioning Buddhist temple, not a wellness resort); (3) Dhammakaya tradition: the Dhammakaya Temple (30km north of Bangkok in Pathum Thani) represents a contemporary Thai Buddhist movement with distinct meditation techniques (focusing on the center of the body) and an elaborate architectural complex (large central stupa accommodating thousands of simultaneous meditators); controversial within Thai Buddhism for heterodox doctrine but influential; (4) Forest tradition and urban practice: Thai Buddhism's Forest Tradition (Ajahn Chah lineage, Ajahn Maha Boowa lineage) emphasizes strict monastic discipline and wilderness retreat; accessible practice informed by this tradition is available through Bangkok-based teachers; (5) Non-Buddhist wellness meditation: Bangkok's yoga studio culture has created multiple secular meditation offerings (mindfulness, breathwork, sound bath) disconnected from religious tradition; these are available at Ekkamai and Thong Lo wellness studios and provide an accessible entry point for visitors without Buddhist context.",
    action: "Wat Mahathat meditation: Section 5 of Wat Mahathat Yuwaratrangsarit, Tha Phra Chan Road — walk-in welcome, call +66-2-222-6011 for current schedule; House of Dhamma (houseofdhamma.com) for monthly Vipassana retreats with English instruction; World Fellowship of Buddhists (wfb-hq.org) — the international Buddhist organization is headquartered in Bangkok; 10-day Vipassana near Bangkok: Dhamma Kamala (suwannaphum area) via dhamma.org.",
  },
];

export function BangkokBuddhism() {
  return (
    <div className="rounded-2xl border border-amber-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-amber-700 mb-3">
        ☸️ Bangkok Buddhism guide — Thai Theravada, merit-making practices & meditation retreats
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-amber-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-amber-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
