const SPOTS = [
  {
    name: "Bangkok Contemporary Art Scene — BACC, SAC Gallery & Thailand's Visual Art Ecosystem",
    emoji: "🎨",
    area: "Bangkok Art and Culture Centre (BACC): National Stadium BTS, free entry ground floor galleries, rotating exhibitions; SAC Gallery (Sathorn): gallery-within-gallery complex, multiple spaces; Toot Yung Art Centre; About Studio/About Café (Maha Chai Road, Rattanakosin island); Cartel Artspace (Sathorn area); WTF Gallery & Café (Sukhumvit 51, long-established art space); Serindia Gallery (Sukhumvit, specializing in Southeast Asian art); 100 Tonson Foundation (early shows moved to new location, major Thai contemporary collector foundation); Art & Culture; Bangkok's gallery district shifting from Sathorn to Charoen Krung neighborhood (1000BC, Woof Pack, river-adjacent galleries)",
    price: "BACC main exhibitions: free (ground floor); ticketed exhibitions: ฿80–200; SAC Gallery exhibitions: free; gallery openings: always free; Bangkok Art Map (bangkokartmap.com) lists current exhibitions; Charoen Krung creative galleries: all free entry; WTF Gallery: free; TCDC (Thailand Creative & Design Centre, Samyan Mitrtown, national design library): ฿100/day access card; Bangkok Art Biennale (BAB, held in even-numbered years): free, dispersed across city",
    why: "Bangkok's contemporary art scene has undergone significant development and geographic consolidation since 2015: (1) BACC as anchor institution: the Bangkok Art and Culture Centre (BACC, 2008) was Bangkok's first major public contemporary art institution; the building (circular design, National Stadium BTS location) houses rotating galleries, permanent collection spaces, and art book/gift shops; BACC is the most accessible entry point for Bangkok's contemporary art scene for first-time visitors; (2) Charoen Krung's creative district emergence: Bangkok's most significant arts geography shift in the 2010s–2020s was the emergence of Charoen Krung (particularly Soi 32–36 near the Chao Phraya riverfront) as a gallery cluster; lower rents than Sukhumvit attracted galleries (1000BC, Speedy Grandma, The Jam Factory, Warehouse 30) as well as restaurants and creative studios; (3) Thailand's Bangkok Art Biennale (BAB): launched 2018, the Bangkok Art Biennale (held in October–December of even years) is Bangkok's most significant international contemporary art event; the biennale uses non-traditional venues (Wat Pho, Central Embassy, The Prelude, ICONSIAM) which makes the art encounter unexpected and genuinely integrated with the city; BAB has featured major international artists alongside Thai artists; (4) Thai contemporary art market: Bangkok has established collectors and a growing international presence at art fairs (Art Basel Hong Kong, Thailand's NADA Bangkok); Thai artists increasingly show internationally (Kamin Lertchaiprasert, Navin Rawanchaikul, Rirkrit Tiravanija — though Rirkrit spends most time internationally); (5) Thai photography and digital art: Bangkok has notable photography and digital art communities; photography festivals (Bangkok Photo Festival, Angkor Photo extended reach), graphic design studios (Somneuk Creative, Klear Creative), and the digital art community centered on video/projection mapping are distinct scenes from the gallery circuit.",
    tip: "Bangkok art scene navigation: (1) Bangkok Art Map: bangkokartmap.com aggregates current gallery exhibitions across Bangkok with opening dates and addresses — the most efficient tool for planning a Bangkok gallery circuit; (2) Opening event circuit: Bangkok gallery openings (typically Thursday or Friday evenings, 6–9pm) are Bangkok's art community social gathering; they are free, include wine and snacks, and provide genuine social access to the Thai art community; checking individual gallery Instagram and Facebook for opening announcements is the primary event discovery method; (3) TCDC library for design research: Thailand Creative & Design Centre (TCDC, Samyan Mitrtown) has the country's most comprehensive design, architecture, and creative industry reference library; the day pass (฿100) provides access to international design journals, material library (physical samples of materials for product design), and workshop space; it is a working library, not a museum; (4) Wat Pho as art heritage: Wat Pho's extensive mural and sculptural program (early 19th century, Rama III era) represents one of the largest collections of classical Thai visual art in existence; treating the temple as an art visit rather than a tourist attraction changes the nature of the engagement; (5) Art collecting in Bangkok: international collectors pursuing Thai contemporary art use galleries (SAC, 100 Tonson, Toot Yung) and auction houses (Christie's, Sotheby's, Bonhams have Southeast Asian sale categories); Bangkok's emerging Thai contemporary art market offers genuine collecting value relative to the established Western and Chinese contemporary art markets.",
  },
  {
    name: "Bangkok Classical Performing Arts — Khon Dance Drama, Likay & Traditional Music",
    emoji: "🎭",
    area: "Khon performances: Sala Chalermkrung Royal Theatre (Charoen Krung Road, restored 1933 Thai Art Deco cinema, occasional Khon and Thai classical performances); National Theatre Bangkok (Chao Phraya riverfront, near Phra Pin Klao Bridge, Thai Fine Arts Department performances); Joseph Bhakdi Foundation (touring Khon productions); Thai classical dance-drama: also performed at Erawan Shrine (Thai classical dance for deity requests); Thai traditional music: Khon Muang (northern Thai music), Lanna drum orchestras; Bangkok Khon mask makers: traditional artisans in Rachini area near Wang Na National Museum",
    price: "Sala Chalermkrung Khon performance tickets: ฿1,200–2,800 (includes English subtitle and seating categories); National Theatre Thai classical shows: ฿80–300 (significantly cheaper, less tourist infrastructure but authentic); Thai classical dance at temples (daily performances for deity requests): free to observe; Thai traditional orchestra (piphat ensemble): performances at Wat Pho, temple events, and National Theatre; Khon mask workshops: ฿500–2,000 for guided workshops at Rachini School of Fine Arts",
    why: "Thai classical performing arts represent one of Southeast Asia's most complex and developed performance traditions with direct royal patronage: (1) Khon's classification and origin: Khon (โขน) is a form of Thai masked dance-drama depicting scenes from the Ramakien (Thai adaptation of the Hindu Ramayana epic); declared UNESCO Intangible Cultural Heritage in 2018; Khon is historically a royal court performance tradition patronized directly by the Thai king; the contemporary form combines elaborate gilded costumes, traditional piphat music orchestra, and stylized narrative gesture vocabulary; (2) Sala Chalermkrung as access point: Sala Chalermkrung Royal Theatre provides the most accessible Khon performance for international visitors — English subtitles, theater seating, and a tourist-oriented production that introduces the tradition without requiring advance knowledge of Thai; productions are seasonal and tickets should be purchased in advance; (3) Thai classical music (piphat): the piphat ensemble (xylophones, gong circles, oboe, drums, cymbals) is the standard orchestral accompaniment for Khon and Thai classical drama; the music system uses a pentatonic scale and circular rhythmic patterns; hearing piphat performed live (National Theatre, temple events) is difficult to replicate through recording — the acoustic character of live piphat in a resonant space is distinctive; (4) Likay — popular Thai folk drama: Likay (ลิเก) is a more accessible popular form of Thai musical theater than Khon; Likay incorporates comedy, improvisation, popular songs, and is performed at temple fairs, commercial venues, and on outdoor stages; while less prestigious than Khon, Likay is more vibrant as a living tradition with active performers and audiences; finding a Likay performance at a temple fair (งานวัด) is a genuine Bangkok cultural discovery; (5) Contemporary intersection with classical: Bangkok's contemporary theater scene (B-floor Theatre, Democrazy Theatre Studio) engages with and subverts Thai classical performance traditions; some Thai contemporary theater productions explicitly reference Khon gesture vocabulary or Ramakien narratives in contemporary political contexts.",
    tip: "Bangkok classical arts visit planning: (1) Sala Chalermkrung ticket acquisition: tickets sell out for popular Khon productions; booking online via the Sala Chalermkrung website or by phone before arrival is strongly recommended; the theater does not have an active ticket office at all times; (2) Wat Pho's classical dance connection: Wat Pho is the original repository of Thai classical knowledge, housing the inscribed stone tablets of traditional Thai knowledge (including dance); the traditional massage school, the medical texts, and the classical arts were all transmitted through Wat Pho's institutional structure; visiting Wat Pho as a classical arts heritage site (not just as the reclining Buddha location) reframes the temple experience; (3) Temple fair (งานวัด) timing: Bangkok's neighborhood temples hold annual festivals (งานวัด) that feature Likay performances, traditional folk games, food stalls, and Thai popular entertainment; these events (typically November–March, dry season) are unscripted Bangkok cultural encounters; asking hotel staff or checking Thai-language event calendars for upcoming temple fairs surfaces these events; (4) National Museum Bangkok's classical arts collection: National Museum Bangkok (adjacent to Sanam Luang, free for foreigners on certain days) houses significant collections of historic Khon masks, classical Thai musical instruments, royal regalia, and related performing arts heritage; (5) Khon mask making as craft: the traditional craft of Khon mask making (papier-mâché base, lacquer, mirror glass, gilded decoration) is maintained at a small number of Bangkok workshops; the Rachini area near the National Museum has traditional mask-making families; participating in a mask-making workshop provides material insight into the Khon tradition beyond attending a performance.",
  },
  {
    name: "Bangkok Film & Cinema Culture — Thai Cinema History, Indie Films & Movie Theaters",
    emoji: "🎬",
    area: "Bangkok cinema chains: Major Cineplex (largest chain, Paragon, EM, Ekkamai); SF Cinema (CentralWorld, major malls); Paragon Cineplex (6 premium screens at Siam Paragon, Prestige and IMAX formats); Doc Club & Pub (Sukhumvit 24, indie film specialty bar-cinema); Lido Connect (National Stadium, 3 screens, arthouse programming); House Samyan (Samyan Mitrtown, designer cinema with art selection); Scala Cinema (Siam Square, vintage 1969 grand cinema, closed 2020 — significant in Thai cinema heritage); Cinematheque at BACC (Bangkok Art and Culture Centre, occasional film screenings); Thai film heritage: Thai National Film Archive (Salaya, Nakhon Pathom — 60km from Bangkok, requires day trip)",
    price: "Standard Bangkok cinema ticket: ฿180–320 for standard seats; IMAX (Paragon): ฿400–600; Major Cineplex premium seats (Enigma, recliner): ฿600–1,200; Doc Club indie screening: ฿200–300 plus food/drink; House Samyan premium: ฿350–500; monthly film subscription (Major Cineplex Gold): available; advance booking (Major Cineplex, SF Cinema apps): online ticketing with seat selection",
    why: "Thailand has a distinctive film culture with both commercial and independent traditions worth understanding: (1) Thai cinema history and golden age: Thai cinema has produced internationally recognized films since the 1950s; the Thai New Wave of the 2000s (Apichatpong Weerasethakul's Cannes Palme d'Or for 'Uncle Boonmee Who Can Recall His Past Lives' in 2010, Pen-ek Ratanaruang's work) brought Thai cinema significant international critical attention; (2) Thai blockbusters and commercial film: Thailand's domestic commercial cinema is robust; Bangkok-produced horror films (Thai horror is a distinct genre with strong regional export market), action films (the Ong-Bak Tony Jaa films established Thai action globally), and romantic comedies (Thailand has a significant romantic drama market) all have strong Thai domestic audiences; (3) Lido Connect as independent film hub: Lido Connect (restored from the original Lido complex on Siam Square, reopened 2021) provides Bangkok's most consistent independent and arthouse film programming; the three-screen cinema shows Thai independent films, international arthouse, and documentary work; the programming explicitly counters the mainstream multiplex model; (4) Doc Club & Pub's community function: Doc Club & Pub (Sukhumvit 24) has established itself as Bangkok's documentary film hub; monthly documentary screenings (often with filmmaker Q&A) and an international documentary library create a community of Bangkok documentary film enthusiasts; the bar-cinema format (food and drink during screenings) is informal and social; (5) King's Birthday film protocol: on significant Thai royal birthdays and national mourning days, Bangkok cinemas have historically observed restrictions on film programming or limited commercial entertainment; this is less rigorously enforced now than historically but can affect special screening events.",
    tip: "Bangkok cinema practical guide: (1) Ticket booking timing: popular Thai films and international blockbusters sell out at major Bangkok cinemas within hours of release weekend; booking via Major Cineplex or SF Cinema apps before arrival at the cinema prevents disappointment, especially for IMAX and premium seats; (2) National anthem before screenings: Bangkok cinemas (and all Thai cinemas) play the Royal Anthem with image of the King before every screening; all audience members stand for the anthem; this is not optional — visitors are expected to stand; remaining seated during the anthem can cause serious social friction and may result in police intervention in extreme cases; (3) Thai film subtitling: Thai commercial films showing in Bangkok cinemas are in Thai without English subtitles; international films typically show both in their original language with Thai subtitles and in Thai-dubbed versions; selecting the correct version (look for 'VO' meaning original version with Thai subtitle) when booking online prevents accidentally purchasing a Thai-dubbed Hollywood film; (4) Scala Cinema significance: Scala Cinema (Siam Square, 1969 single-screen grand cinema with modernist Thai architecture and gilded interior) was demolished/closed in 2020 after the property lease expired; its closure marked the end of Bangkok's grand single-screen cinema era; the Scala location is now redeveloped; (5) Thai-made film recommendations: notable Thai films for pre-trip viewing — 'Uncle Boonmee Who Can Recall His Past Lives' (Apichatpong, 2010), 'Bangkok Traffic Love Story' (commercial Thai rom-com, Bangkok geography, 2009), '13 Beloved' (Thai horror-thriller, 2006), 'Tony Jaa's Ong-Bak' (Thai martial arts, 2003), 'The Iron Ladies' (based on true story Thai volleyball team, 2000).",
  },
];

export function BangkokArts() {
  return (
    <div className="rounded-2xl border border-purple-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-purple-700 mb-3">
        🎨 Bangkok arts & culture — visual art galleries, classical performing arts & cinema culture
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-purple-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-purple-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-purple-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
