const TOPICS = [
  {
    title: "Bangkok Secondhand & Thrift Shopping — Pratunam Flea Markets, Thrift Stores & Swap Meets",
    emoji: "🧺",
    summary: "Bangkok has a thriving secondhand economy with distinct channels for different types of secondhand goods: (1) Bangkok's secondhand clothing geography: Chatuchak Weekend Market (JJ Market) is the largest and most famous secondhand clothing venue in Bangkok; specific sections of Chatuchak (particularly sections 3, 4, 5, 6 in the weekend market layout) concentrate vintage and secondhand clothing; prices have increased significantly as the vintage/thrifting culture has grown; Chatuchak secondhand now serves a more curated market rather than pure budget shopping; (2) MBK Shopping Centre secondhand: MBK (Mahboonkrong, National Stadium BTS) has multiple floors of secondhand electronics, secondhand phones, and used/refurbished goods alongside new merchandise; the electronics secondhand market at MBK (levels 4–5 particularly) provides used smartphones, laptops, and accessories; negotiation is standard and expected at MBK electronics secondhand stalls; (3) The Pratunam flea market corridor: the area around Pratunam (Ratchaprarop and adjacent sois) has market traders selling surplus factory clothing, end-of-line fashion items, and wholesale-adjacent fashion at non-thrift-store prices; these vendors are not 'secondhand' in the used sense but rather new-old-stock and factory surplus; (4) Bangkok's online thrifting market: Shopee Thailand and Facebook Marketplace have become Bangkok's primary secondhand trading platforms; Thai secondhand Instagram accounts (@thriftbkk types) aggregate vintage and thrift finds; the intersection of Thai social media and secondhand culture has created a sophisticated Bangkok vintage market; (5) Foreign brand secondhand clothing: Bangkok's thrift market has unusual opportunities for finding foreign-label secondhand clothing (particularly Japanese and Korean brands) that arrived via donation collections or secondhand import; Japanese brands (Uniqlo, Muji, more premium labels) frequently surface in Bangkok thrift due to Japanese-Thai donation relationships and secondhand import channels.",
    action: "Chatuchak Weekend Market secondhand section: Saturday and Sunday, 9am–6pm; most dense secondhand section: sections 3–6 for clothing; MBK secondhand electronics: open daily 10am–10pm; Bangkok secondhand community: Facebook groups 'Bangkok Thrift' and 'Second Hand Bangkok'; Instagram accounts with Bangkok secondhand curation: search 'thrift Bangkok', 'vintage Bangkok Thailand'; Carousell Thailand for online secondhand selling/buying; Facebook Marketplace Thailand for local pickup secondhand trading.",
  },
  {
    title: "Bangkok Antiques & Collectibles — River City, Thieves Market & What's Actually Authentic",
    emoji: "🏺",
    summary: "Bangkok's antiques market attracts serious international collectors and curious tourists, with a spectrum from genuine antiques to tourist reproductions: (1) River City Bangkok as antique hub: River City Shopping Complex (Charoen Krung, SI Phraya Pier, Chao Phraya riverfront) is Bangkok's most concentrated serious antiques center; the complex contains multiple established dealers specializing in Thai antiques (Khmer sculpture, Burmese lacquerware, Thai ceramics, Ayutthaya-period bronzes), Chinese antiques (porcelain, jade, snuff bottles), and Southeast Asian ethnographic objects; prices reflect genuine antique market rates; (2) Thieves Market (Talat Nakhon Kasem): Bangkok's informal 'Thieves Market' (named historically due to goods of uncertain origin) near Yaowarat (Chinatown) is a multi-story market for antiques, curios, old electronics, used tools, and assorted collectibles; more casual browsing and lower price points than River City; authentication of claimed antiques requires independent verification; (3) Thai antique export restrictions: the Fine Arts Department of Thailand regulates export of antique Buddha images, ancient artifacts, and culturally significant objects; purchasing antique Buddha images for export is legally restricted and requires an export permit from the Fine Arts Department; dealers at River City can navigate export permit requirements for legitimate antiques; significant penalties apply for exporting restricted antiques without permits; (4) Reproductions vs. antiques in tourist markets: Bangkok's tourist market areas (Chatuchak souvenir section, Rattanakosin souvenir shops, Khao San Road shops) predominantly sell reproduction 'antiques' — items designed to appear aged but manufactured recently; purchasing these for decorative purposes is fine; representing them as genuine antiques to others is fraudulent; (5) Speciality collectibles Bangkok markets: Bangkok has specific collectible niches beyond traditional antiques — vintage Thai advertising posters (from pre-1970 Thai commercial culture), vintage Thai currency, vintage Thai amulets (outside the existing amulet market near Wat Mahathat), vintage Thai comics, and vintage Thai fashion magazines; niche collector communities trade through Facebook groups and Line communities.",
    action: "River City Bangkok antiques: regular antique auction quarterly at River City; shop hours: daily 10am–8pm; export permit application: Fine Arts Department of Thailand (finearts.go.th) for antique export authorization; appraisal services: multiple independent appraisers can be arranged through River City dealers for third-party authentication; Thieves Market hours: daily but most active morning; approach: bring cash, budget time for multiple floors; Bangkok Antique Dealers Association members for trusted sources.",
  },
  {
    title: "Bangkok's Sustainable Fashion & Upcycling Scene — Ethical Bangkok Shopping",
    emoji: "♻️",
    summary: "Bangkok has an emerging sustainable fashion and ethical shopping movement that intersects with the city's creative and artisan sectors: (1) Sustainable Bangkok fashion overview: Thailand's sustainable fashion sector is growing but small relative to the overall fashion market; key players include SOOK Atelier (upcycled fashion, Charoen Krung area), Kloset Resort (Thai designer using sustainable practices, Emquartier), Propaganda (Thai product design brand with ethical production claims, multiple Bangkok mall locations); (2) Artisan and fair trade Bangkok: Bangkok has several organizations connecting ethically produced artisan goods from rural communities to urban buyers; Doi Tung Development Project (Royal Project, from northern Thailand hill tribes) has Bangkok outlets at major airports and Emquartier; OTOP (One Tambon One Product, government-supported rural artisan product program) products are available at dedicated OTOP shops and Queen Sirikit National Convention Centre during periodic trade shows; (3) Thai silk ethical sourcing: Thailand's silk industry (particularly northeastern Isaan region silk, Mudmee tie-dye silk, royal silk foundation weaving) has both community-supported and industrially produced versions; the difference in quality and ethical sourcing is significant; Jim Thompson (Bangkok's most internationally known Thai silk brand) uses quality Thai silk but operates commercially; the Queen Sirikit Museum of Textiles (Grand Palace area) and royal project silk weaving villages provide ethical alternatives; (4) Zero-waste Bangkok restaurants and cafés: a small but growing number of Bangkok restaurants have adopted zero-waste or reduced-packaging positions; these are typically concentrated in Charoen Krung creative district (1919 social enterprise restaurant), Sukhumvit eco-café circuit, and plant-based restaurant network; Bangkok's mainstream restaurant sector remains largely conventional in packaging; (5) Bangkok thrift as sustainability: Bangkok's secondhand clothing market (Chatuchak, online secondhand) represents the most accessible entry into sustainable fashion in Bangkok; buying secondhand from established Bangkok thrift channels extends clothing life cycle, keeps textile waste from landfill, and provides cost savings; the intersection of Bangkok thrift culture and global sustainable fashion awareness has grown the thrift market beyond budget-necessity to lifestyle choice.",
    action: "Bangkok ethical fashion destinations: Doi Tung at Suvarnabhumi Airport arrivals (hill tribe crafts, royal project); OTOP product fairs (periodic, check Bangkok calendar); Chatuchak Market handcraft sections (sections 7–8 for traditional Thai crafts, some cooperative-produced); Charoen Krung social enterprise cluster (Warehouse 30 area for design and social enterprise brands); Propaganda concept store (CentralWorld, Siam Paragon, Terminal 21) for Thai-designed durable goods; Jim Thompson Factory Sale (twice yearly, major Bangkok bargain event for Thai silk goods) for lower-cost access to established Thai silk brands.",
  },
];

export function BangkokSecondhand() {
  return (
    <div className="rounded-2xl border border-amber-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-amber-700 mb-3">
        🧺 Bangkok secondhand & antiques — thrift markets, collectibles & ethical fashion
      </div>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-amber-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-amber-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
