const TOPICS = [
  {
    title: "Bangkok Craft Beer Scene — Microbreweries, Craft Taprooms & Thailand Beer Laws",
    emoji: "🍺",
    summary: "Bangkok has developed a genuine craft beer scene despite significant legal and regulatory barriers that make Thai craft beer more expensive and harder to produce than in most countries: (1) Thailand's restrictive brewing laws — context for the craft beer market: Thailand's Liquor Act requires minimum production volume of 100,000 liters per year for commercial brewing licenses; this threshold effectively excluded small-scale craft breweries for decades (a 100,000-liter minimum is approximately 6–7x the production of typical US or European microbreweries); the law also restricts home brewing and limits licensing to large producers; the regulatory environment has been heavily influenced by incumbent beer conglomerates (Boon Rawd Brewery, ThaiBev) which dominate the Thai market through Chang, Leo, Singha, Archa, and other brands; (2) The craft beer workaround era (2010–present): Thai craft beer brands historically produced overseas (primarily at contract breweries in Germany, Czech Republic, and Vietnam) and imported the finished beer as imports; this allowed premium craft beer brands to enter the Thai market legally; example craft beer brands using this model: Chalawan Craft Beer (Thailand's first widely distributed craft brand); Full Moon Brewing; Outlaw Brewing; Sandport; Storm Brewing (Bangkok-founded, contract brewed abroad); (3) Legal changes enabling local craft brewing: Thailand's Excise Department has been gradually reforming the Liquor Act; small brewery licenses (craft brewery licenses with lower minimum thresholds) were being piloted or proposed as of 2023–2024; some Bangkok brewpubs received special venue licenses allowing on-premise production and sale; the regulatory situation continues evolving — check current status for updated rules; (4) Bangkok craft beer taprooms: Mikkeller Bangkok (Thonglor area) — international Danish craft brand with Bangkok outpost; The Session (multiple Bangkok locations, craft-focused tap room); Brew Lab (Bangkok craft beer bar with rotating taps); Craft Syndicate Bangkok (Ekkamai, craft tap selection); Beer Republic (Siam area, international and Thai craft selection); Mikkeller Bar (Thonglor area); Witch's Tavern (Thonglor, established craft beer bar); Copper Beer (Ari area); (5) Imported vs. Thai craft beer pricing: Thailand's 100% beer excise tax on imported alcoholic beverages means imported craft beer is expensive; a 330ml bottle of imported craft beer: ฿150–350 in craft bars vs. ฿40–80 for domestic macro beer (Chang, Leo, Singha) at the same venue; Bangkok craft beer enthusiasts pay 4–8x the price of domestic macro beer; the Thai craft beer produced offshore and imported (like Chalawan, Storm, etc.) occupies a middle price point of ฿100–180 per 330ml.",
    action: "Bangkok craft beer exploration: (1) Mikkeller Bangkok (Thonglor): Mikkeller operates one of its most beautiful global locations in Bangkok's Thonglor entertainment district; the selection rotates regularly and includes rare Mikkeller releases alongside local Thai craft options; pricing: ฿200–450 per glass; (2) Beer Republic (Siam area): large craft selection including Thai and international options; convenient BTS Siam proximity; appropriate for sampling multiple styles; (3) Craft beer neighborhoods: Thonglor and Ekkamai (BTS Thong Lo/Ekkamai) have the highest concentration of Bangkok craft beer bars; Ari (BTS Ari) has several craft-focused venues; Silom has mixed venues with craft options; (4) Homebrew culture: Thai homebrewing community exists despite legal ambiguity; Bangkok homebrew clubs and supply shops (search Facebook for Bangkok Homebrew Club) provide community for enthusiasts; homebrewing is technically illegal at small scale but enforcement is minimal; (5) Beer tourism context: Bangkok is not a craft beer destination comparable to Portland, Portland, or Brussels; it is however a destination where craft beer is available at interesting international standards at specific venues, making it accessible and worth exploring.",
  },
  {
    title: "Bangkok Wine Culture — Thai Wine, Natural Wine Bars & Fine Wine Import Market",
    emoji: "🍷",
    summary: "Bangkok has developed a sophisticated wine culture surprising for a tropical country with no indigenous wine tradition — driven by a combination of wealthy Thai urbanites, large international expat community, and Thailand's own wine industry: (1) Thailand's wine industry: Thailand produces wine domestically — the most surprising fact for most visitors; Thai wine exists because of: adequate altitude (600–1,800m elevation in northern Thailand) and tropical climate modification (two harvest cycles per year); key Thai wine regions: Khao Yai (Nakhon Ratchasima province, 150km from Bangkok) is Thailand's most developed wine region; PB Valley Khao Yai Winery — Thailand's most visited and awarded winery, producing Chenin Blanc, Shiraz, Tempranillo, Colombard; GranMonte Vineyard (Asoke Valley, Khao Yai) — family-owned, acclaimed for Viognier and Syrah; Siam Winery (Samut Sakhon province near Bangkok) produces Monsoon Valley brand (Thailand's most widely exported Thai wine); Hua Hin Hills Vineyard (Hua Hin area); (2) Bangkok's fine wine import market: Bangkok's high-income Thai consumer base (significant billionaire concentration, active ultra-high-net-worth demographic) supports a mature fine wine market; imported wine distributors: Amari Hotel Cellar (fine wine retail), Wine Cellar Bangkok, Fine Wines and Good Spirits, Nakorn Cellar; major hotel wine lists (Mandarin Oriental, Capella Bangkok, Four Seasons, Rosewood) carry comparable Burgundy and Bordeaux selections to comparable properties in Singapore or Hong Kong; (3) Bangkok natural wine scene: natural wine (low-intervention, minimal additives, often unfiltered/unfined) has developed a following in Bangkok's younger urban demographics; natural wine bars: Wine Pub Bangkok (natural wine-focused), Raintree (wine bar and restaurant, Thonglor), Mikkeller Bangkok also carries natural wine options; the Thai word-of-mouth wine community shares discoveries through Line groups and Instagram; (4) Wine bar culture in Bangkok: Bangkok wine bar culture is concentrated in Thonglor, Ari, and the Charoennakorn/Tha Chang riverside cluster; Bangkok wine bars increasingly emphasize: natural and biodynamic wine sourcing, Thai and regional sommeliers, pairing with Thai and fusion food; wine by the glass programs have expanded as wine literacy among young Bangkok consumers grows rapidly; (5) Thai wine tourism: Khao Yai winery visits (150km from Bangkok, 2 hours by car) have become major Bangkok excursion for Thai urban wine enthusiasts; PB Valley and GranMonte both offer: vineyard tours, wine tastings, on-site restaurants, accommodation; weekend booking in advance is required for peak season (October–January) when Khao Yai's cooler temperatures coincide with grape harvest period.",
    action: "Bangkok wine access: (1) Thai wine tasting at Bangkok restaurants: most upscale Bangkok restaurants (Thonglor, Silom, Sukhumvit) carry Thai wine options; starting with Monsoon Valley (widely available) or GranMonte provides accessible entry to Thai wine without traveling to the vineyard; (2) Khao Yai winery day trip: PB Valley Khao Yai (pbvalley.com) and GranMonte (granmonte.com) both accept advance bookings for tours and tastings; weekend departures from Bangkok by car (Grab or rental, 2 hours) or organized wine tour; the Khao Yai trip combines vineyard visit with the national park area; (3) Fine wine retail: Bangkok's wine retail sector has strong options — Amari Hotel wine shop (Silom), Central Food Hall (CentralWorld) wine section, Tops Supermarket at higher-end branches carry import wine at retail; (4) Bangkok wine education: the Thai Sommelier Association and Wine Republic Thailand offer wine certification courses in Bangkok; WSET Level 1–4 courses are available at Bangkok-based wine schools; Bangkok's wine community is English-language accessible; (5) Import wine customs: personal import of wine into Thailand is limited (as part of alcohol allowance at customs); bringing wine as a gift for Bangkok hosts works within customs limits but is not a reliable strategy for personal supply.",
  },
  {
    title: "Bangkok Whisky & Spirits Culture — Thai Whisky Heritage, High-End Bars & Spirits Imports",
    emoji: "🥃",
    summary: "Thailand has a dominant whisky and spirits culture that significantly influences Bangkok's bar scene — Thai whisky commands the dominant market share in Thailand's spirits market: (1) Thai whisky — understanding the market dominance: whisky is Thailand's dominant alcoholic spirit by volume; Thai whisky brands command approximately 80% of the domestic spirits market; key Thai whisky brands: Ruang Khao (rice whisky, very low cost, local drinking culture); Hong Thong (Thai blend, affordable, widely popular among Thai working class); Sang Som (Thai rum variant, extremely popular for mixed drinks); Mekhong (Thai rum/spirit, distinct molasses and sugarcane character); Blend 285 and Crown Custom (ThaiBev mid-range blends); Red Label, Black Label, Johnnie Walker (imported Scotch — dominant premium imported brand); (2) Thai whisky regulatory classification: Thai-produced whiskies are technically blended spirits (mixing grain spirit with malt whisky in varying proportions) rather than single malt or straight blended Scotch; the terminology 'whisky' in Thailand includes spirits that would not qualify as whisky under EU or US regulations; understanding this classification helps understand taste profiles — Thai whiskies like Mekhong and Sang Som have distinctly different character from Scotch, bourbon, or Japanese whisky; (3) Bangkok's high-end whisky bars: Vesper Bar (at The Standard Bangkok, Sukhumvit) — curated whisky and cocktail program; The Bar at Mandarin Oriental Bangkok — historic setting, extensive Scotch selection; 1826 Bar (Capella Bangkok) — premium spirits focus; Hyde & Seek (Athenee Tower, Ploenchit) — established whisky bar; Bamboo Bar (Mandarin Oriental) — live jazz plus cocktail program; (4) Japanese whisky in Bangkok: Japan's whisky renaissance has significantly impacted Bangkok's premium whisky market; Bangkok bars now commonly stock: Nikka from the Barrel, Hibiki Harmony, Yamazaki 12/18, Hakushu 12; Japanese whisky at Bangkok premium bars: ฿600–2,500+ per pour depending on expression; limited edition Japanese releases available at Bangkok specialist retailers (Amari Hotel wine and spirits, upmarket hotel shops) at significant premiums; (5) Bangkok cocktail culture integration: Bangkok's cocktail bar scene (see BangkokCocktailBar component) uses Thai spirits as distinctive local ingredients; Mekhong (Bangkok's signature spirit) appears in numerous Bangkok-original cocktails; Tom Yum Sour, Thai tea whisky sours, lemongrass-infused spirits — Bangkok bartenders have been creative with domestic spirit integration; the Asian '50 Best Bars' list includes several Bangkok cocktail bars.",
    action: "Bangkok spirits exploration: (1) Thai whisky social experience: experiencing Thai whisky culture requires observing how Thais actually drink — in groups at table service venues (not standing at a bar), ordering bottles rather than individual drinks (bottle service at table with ice bucket, mixer, and soda water), mixing as the group drinks rather than ordering premixed cocktails; the social ritual of sharing a whisky bottle with food is distinctly Thai; (2) Mekhong tasting: the most authentically Bangkok spirits experience is ordering a bottle of Mekhong (฿400–600 retail, ฿800–1,500 at bars) with soda water and ice; Mekhong's unique sweet, molasses-adjacent character (it's technically classified as a 'Thai spirit' not rum despite sugarcane base) is distinctly different from Western spirits; (3) High-end whisky bar experience: Vesper Bar at The Standard Bangkok (BTS Asok area) provides Bangkok's most curated whisky and cocktail experience; prices: ฿400–700 for cocktails, ฿600–2,500 for whisky pours; (4) Japanese whisky hunting: for Japanese whisky shopping, Amari Hotel spirits section (Amari Hotel Sukhumvit Soi 18) and the Terminal 21 spirits retailer carry notable Japanese expressions; allocations are limited; (5) Custom cocktail with Thai spirits: request from Bangkok bartenders a cocktail featuring Mekhong or Sang Som as the base spirit with Thai ingredients — Bangkok's creative cocktail bars excel at this format and it provides a distinctly local spirits experience unavailable elsewhere.",
  },
];

export function BangkokBrewing() {
  return (
    <div className="rounded-2xl border border-amber-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-amber-700 mb-3">
        🍺 Bangkok drinks culture — craft beer laws & taprooms, Thai wine from Khao Yai & whisky culture
      </div>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-amber-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-amber-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
