const SPOTS = [
  {
    name: "Latin American Food & Expat Community in Bangkok",
    emoji: "🌮",
    area: "Latin American restaurants throughout Bangkok: Sombrero Thai-Mexican fusion (multiple branches), El Gaucho Argentinean Steakhouse (Sukhumvit), Casa Latina (Sathorn), Santa Fe Steakhouse, and periodic pop-up events by Latin American community groups",
    price: "Mexican tacos/burritos: ฿200–450; Argentinean steak (per 200g): ฿600–1,500; Peruvian ceviche: ฿350–700; Brazilian churrasco (per person): ฿800–2,500; Latin cocktails (caipirinha, mojito, pisco sour): ฿250–500",
    why: "Bangkok's Latin American food scene is smaller than its Asian international food ecosystem but has grown with the city's cosmopolitan dining culture. Key Latin American presences: (1) Mexican — Bangkok's Mexican food scene spans from Tex-Mex comfort food to more authentic preparations; 'Sombrero' chain offers widely accessible Mexican food; some Sukhumvit restaurants are operated by Mexican nationals with authentic regional preparation; (2) Argentinean — Buenos Aires-style steak culture has strong representation in Bangkok through El Gaucho and similar steak restaurants; Argentinean beef (imported or domestically raised to Argentine breed standards) and chimichurri define the experience; (3) Brazilian — churrasco (Brazilian BBQ) restaurants in Bangkok include several rodizio format options (servers circulate with skewered meats); the Brazilian expat community has established a small but active food culture; (4) Peruvian — Bangkok's most under-recognized Latin food gem; Peru's fusion cuisine (Japanese-Peruvian Nikkei, Chinese-Peruvian Chifa, coastal ceviche culture) resonates with Bangkok's own fusion sensibility; (5) Colombian — small but emerging presence through Colombian expats who often operate coffee shops alongside their Colombian food traditions.",
    tip: "Bangkok Latin American food exploration: (1) Mexican sourcing challenge: Bangkok's Mexican restaurants work with locally available ingredients that approximate Mexican originals; true Mexican chili peppers, corn masa products, and specific Mexican cheeses are difficult to source; the best Bangkok Mexican restaurants acknowledge the adaptations honestly; (2) Argentinean beef: El Gaucho Bangkok imports or sources breeds that approximate the pampas-raised Argentine beef experience; the high cost is partly genuine logistics; (3) Colombian coffee culture: Bangkok has a growing number of Colombian-influenced coffee establishments; Colombia produces some of the world's most respected specialty coffee and Colombian expat-operated cafés in Bangkok often source directly from Colombian farms; (4) Latin American community events: Bangkok's Latin American community (primarily in Sukhumvit area) organizes cultural events particularly around national days (Brazil September 7, Mexico September 16, Argentina July 9) that include traditional food; (5) Pisco sour in Bangkok: Lima-style pisco sour (Peruvian grape brandy, lime, sugar, egg white, Angostura bitters) is found at the best Bangkok Peruvian restaurants and occasionally at international cocktail bars — one of the world's best cocktails and relatively under-known in Bangkok's bar scene.",
  },
  {
    name: "Bangkok Caribbean & Pacific Island Culture",
    emoji: "🏝️",
    area: "Caribbean representation in Bangkok: primarily through cocktail culture (rum cocktails, reggae-themed bars in Khao San/Banglamphu area) and occasional Caribbean food at international food festivals; Pacific Islander community small but present near international churches in Bangkok",
    price: "Rum-based cocktails (Bangkok bar): ฿250–500; Caribbean-inspired food event entry: ฿300–800; International food market entrance: ฿100–300; Jamaican jerk chicken (where available): ฿350–700",
    why: "Bangkok's Caribbean presence is primarily cultural rather than food-centered — the reggae and Caribbean music influence on Bangkok's bohemian neighborhoods (particularly Khao San Road area and alternative music venues) is stronger than the food presence. Caribbean food representation: (1) Jamaican jerk chicken: occasionally appears on Bangkok's international food circuit through pop-up events and Caribbean community cooking; the combination of scotch bonnet pepper heat, allspice, and smoke resonates with Bangkok's heat-tolerant palate; (2) Rum cocktail culture: Bangkok's cocktail bars have enthusiastically embraced Caribbean rum culture; the abundance of aged Caribbean rum (Appleton, Mount Gay, Flor de Caña, Ron Zacapa) in Bangkok's premium bars reflects global bartending's current rum appreciation; (3) Hawaiian/Pacific Islander culture: Bangkok's surfing community, particularly the digital nomad segment, maintains connections to Hawaiian and Pacific surf culture through lifestyle aesthetics; Pacific Island cultural presence is minimal but existing through specific community church congregations and small diaspora groups.",
    tip: "Bangkok reggae and Caribbean culture exploration: (1) Khao San reggae culture: Banglamphu/Khao San Road area has maintained reggae music as part of its alternative backpacker identity for decades; Bob Marley imagery, reggae bars, and occasional live reggae performances are concentrated here; (2) Thailand's reggae community: Thailand has a domestic reggae and ska music community (primarily Thai musicians) separate from the Khao San tourist scene; connecting with Thai reggae through platforms like Spotify Thai playlists reveals domestic artists; (3) Rum investment in Bangkok: Bangkok's duty-free and premium spirits shops stock exceptional aged rums that are under-represented in Asian markets; Diplomatico 25-year, Appleton 30-year, and similar aged expressions appear at Bangkok's specialist spirits retailers at competitive prices; (4) Pacific cuisine access: Hawaiian poke bowls have become Bangkok café culture staples (available at multiple bowl-style casual restaurants); this represents Pacific food culture's most accessible Bangkok expression; (5) International food festivals: Bangkok's periodic international food festivals (occasionally organized by embassies or event organizers at outdoor venues) are the best access points for Caribbean food — finding vendors from Jamaica, Trinidad, or other Caribbean nations at these events.",
  },
  {
    name: "Bangkok Australian & New Zealand Community",
    emoji: "🦘",
    area: "Aussie and Kiwi expat community: strong concentration in Sukhumvit, near international schools (NIST International School, Ruamrudee), and in Bangkok's business districts; Australian Chamber of Commerce Bangkok, the Australian Club; Anzac Day celebrations at Australian Embassy",
    price: "Australian-operated café flat white: ฿120–180; Australian pub meal equivalent: ฿350–600; ANZAC Day charity event: ฿500–2,000; Australian wine (imported): ฿1,200–5,000/bottle; Australian BBQ social event: ฿400–1,500",
    why: "Bangkok has one of Southeast Asia's largest Australian and New Zealand expatriate communities — drawn by teaching positions at international schools, business roles in multinational companies, the digital nomad economy, and Bangkok's reputation as a base for Southeast Asian travel. The community is large enough to support: (1) Australian-influenced café culture — Bangkok's specialty coffee scene has been significantly shaped by Australian barista culture (the flat white, Australian espresso standards, café brunch culture); many of Bangkok's best independent cafés are owned or managed by Australians or Kiwis; (2) Australian Chamber of Commerce Bangkok (AustCham) — active business networking for Australian businesses and professionals in Thailand; (3) ANZAC Day in Bangkok — Australia-New Zealand Army Corps Day (April 25) is observed in Bangkok with a Dawn Service at the Australian Embassy and community events; one of Bangkok's most somber and meaningful expatriate cultural events; (4) International school parents' community — Bangkok's international schools have significant Australian/New Zealand parent communities whose social networks create community cohesion; (5) Sports following — Australian sports (AFL, cricket, NRL) are followed by the Bangkok Aussie expat community through sports bars that screen Australian sporting events via Foxtel.",
    tip: "Bangkok Australian/New Zealand community connection: (1) Flat white culture: Bangkok's Australian-influenced coffee culture means the flat white (espresso with microfoam milk, smaller and more concentrated than a latte) is understood and executed well at specialty cafés in Thonglor, Ekkamai, and Ari; (2) ANZAC Day access: Bangkok's ANZAC Dawn Service is a genuinely moving experience open to non-Australians who attend respectfully; the Australian Embassy vicinity (on April 25, approximately 5–6am) is where the ceremony takes place; (3) AustCham Bangkok events: the Australian Chamber of Commerce hosts networking events, industry seminars, and social functions that are accessible to non-members as guests; attending once provides visibility into Bangkok's Australian business community; (4) Australian beef in Bangkok: the import market for Australian beef in Bangkok's premium restaurants and supermarkets (Villa Market, Gourmet Market in Siam Paragon) means Australian grass-fed and Wagyu cross beef is available for home cooking at reasonable prices; (5) Bangkok to Australia travel frequency: Bangkok is a major Qantas and Thai Airways hub for Australia-Thailand routes; the Bankgok-Sydney/Melbourne routes are among the world's busiest Australia-ASEAN connections; the Thai community in Australia and the Australian community in Bangkok create bilateral travel between these specific cities.",
  },
];

export function BangkokLatinAmerica() {
  return (
    <div className="rounded-2xl border border-green-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-green-700 mb-3">
        🌮 Bangkok international community — Latin American food, Caribbean culture & Aussie expats
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-green-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-green-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
