const TOPICS = [
  {
    title: "Bangkok Food Festivals & Annual Culinary Events — When, Where & What to Expect",
    emoji: "🎪",
    summary: "Bangkok hosts multiple significant food festivals annually that provide concentrated culinary experience beyond regular restaurant dining: (1) Bangkok Restaurant Week: held semi-annually (typically March and September), Bangkok Restaurant Week offers set menu lunches and dinners at participating restaurants (many Michelin-starred and top-ranked Bangkok restaurants participate) at fixed reduced prices (typically ฿299–999 for 2-3 course menus); the format mirrors similar events in New York and London; participation allows access to usually expensive restaurants at accessible prices; booking required, high demand for top restaurant slots; Bangkok Restaurant Week website maintains updated schedules; (2) Yaowarat Chinese New Year food festival: the annual Chinese New Year celebrations in Yaowarat (Chinatown) transform Yaowarat Road into an extended food festival for 9 days in January-February (date follows lunar calendar); street food vendors concentrate, specialty offerings not available at other times of year emerge (specific auspicious dishes, lion dance performers), and the Yaowarat visual spectacle peaks; the festival's food concentration makes it Bangkok's most atmospheric single-area food event; avoid driving to Yaowarat during Chinese New Year — Grab or MRT is essential; (3) Bangkok's Vegetarian Festival (Tesagan Gin Je): the Yaowarat-centered Vegetarian Festival (Chinese-Thai Buddhist Taoist observance, 9 days in September-October, following lunar calendar) is Bangkok's largest organized food restriction event; during the festival, yellow flag restaurants (เจ, 'jay') throughout Bangkok offer strictly vegetarian/vegan food; the festival generates Bangkok's largest temporary vegetarian food market (around Yaowarat, Tha Phra Chan Amulet Market area); Thai-Buddhist vegetarian food (jay food) is distinct from Western vegetarianism — no garlic, onion, or pungent vegetables in strict jay food; (4) Bangkok's Food and Wine Festival: the Bangkok Food and Wine Festival (BAFW, usually at a major riverside hotel venue — previously at the Anantara Riverside) features chef demonstrations, wine pairings, and food exhibits from Bangkok's top restaurants and international guest chefs; timing varies by year; tickets sold per session; this is the city's premium culinary industry event; (5) Street food events and pop-up markets: Bangkok has developed a strong pop-up and food market culture beyond permanent markets; regular events include the Artisan Bangkok (craft and food market, different Bangkok venues), Bangkok Farmers' Market (Sukhumvit area), and various weekend food pop-ups at creative spaces (The Commons Thong Lo frequently hosts food events); checking Bangkok-specific lifestyle publications (BK Magazine, Thailand Tatler) for current monthly food event listings is the best approach.",
    action: "Bangkok Restaurant Week booking: check the current year's participating restaurant list and reservation links when the event is announced; Yaowarat Chinese New Year festival dates: based on lunar calendar — usually late January or February; best access: MRT Sam Yot, walk to Yaowarat Road; Thai Vegetarian Festival dates: check taoist calendar equivalent of the 9th lunar month (September-October); Bangkok food event calendar: BK Magazine online (bk.asia-city.com), Coconuts Bangkok (coconuts.co/bangkok), and Bangkok Facebook events for current month's food events and pop-ups.",
  },
  {
    title: "Bangkok Restaurant Reservations — How to Book, Waitlists & Walk-in Culture",
    emoji: "📲",
    summary: "Bangkok's reservation culture spans from essential advance booking at Michelin establishments to walk-in only policies at authentic local restaurants: (1) Bangkok's reservation spectrum: the key distinction is understanding which Bangkok restaurants require advance booking vs. which have no reservation system; Michelin-starred and celebrity chef Bangkok restaurants (Le Du, Sühring, Sorn, Nahm, Paste) require advance bookings days to weeks ahead for weekend dinner; top mid-range Bangkok restaurants (Err Urban Rustic Thai, Baan, Soul Food Mahanakorn) recommend booking 1–3 days ahead for weekend evenings; authentic Thai restaurants, street food, and local rice-and-curry places: no reservation system, walk-in only; (2) How Bangkok restaurants take reservations: predominant booking methods for Bangkok: (a) LINE message (most Bangkok restaurants accept LINE bookings — add the restaurant's LINE ID and send the date, time, and party size); (b) phone call (still common for established Bangkok restaurants, may have limited English); (c) online booking platforms (OpenTable has limited Bangkok selection; Hungry Hub is Thailand-specific booking platform with good Bangkok coverage; EATigo offers discounts for off-peak bookings; Quandoo has some Bangkok listings); (d) email (luxury hotel restaurants, formal fine dining); (3) Bangkok's walk-in restaurant culture: the majority of Bangkok's best food (local Thai restaurants, street food, neighborhood eateries) operates entirely walk-in; Bangkok local dining culture is not reservation-oriented; attempting to reserve at local rice shops or market-style eateries will confuse the staff; embracing walk-in culture for non-Michelin Bangkok dining is more aligned with Thai restaurant culture; (4) Popular Bangkok restaurant waits: Bangkok's most popular non-reservation restaurants (Jay Fai's street stall, certain morning dim sum shops in Yaowarat, specific Chatuchak market food stalls) have substantial queues; Jay Fai (the internationally famous Bangkok street chef) requires calling at 8am for same-day booking; showing up without booking means waiting in line or being turned away; (5) Cancellation culture in Bangkok: Bangkok restaurant cancellation culture is less formalized than Western cities; not all Bangkok restaurants hold credit cards for no-show fees; however, cancelling a reservation (especially for luxury restaurants) by LINE or phone as early as possible is appropriate Bangkok dining courtesy.",
    action: "Bangkok restaurant booking platforms: Hungry Hub (hungryhub.com, best Thai-specific coverage, includes promotions); EATigo (eatigo.com, off-peak discount booking); OpenTable (limited Bangkok coverage, useful for international hotel restaurants); LINE restaurant accounts: search restaurant name on LINE or check restaurant's social media for their LINE ID; for Michelin Bangkok: direct booking via restaurant website is most reliable; Bangkok restaurant directory with reservation info: BK Magazine annual 'Best of Bangkok' issue or bk.asia-city.com restaurant section.",
  },
  {
    title: "Bangkok Late-Night Food — Best 24-Hour Eats, Midnight Markets & After-Bar Food",
    emoji: "🌙",
    summary: "Bangkok's late-night food scene is exceptional by global city standards — the city genuinely offers good eating options until 4–5am: (1) Bangkok's late-night food culture: Bangkok food operates in several time bands: (a) 10pm–midnight (still active market hours, most restaurants still serving); (b) midnight–2am (night market food, Yaowarat still active, dedicated late-night spots active); (c) 2am–5am (genuine late-night, reduced but still present, specific dedicated spots); Bangkok is genuinely different from most global cities in having quality food available at 3am without resorting to fast food; (2) Yaowarat late-night (midnight to 3am): Yaowarat (Chinatown) is Bangkok's most active late-night food zone — restaurants remain open until 1–3am, street stalls serving khao tom (congee/rice soup), satay, roast duck, and crab dishes; the night character of Yaowarat peaks after midnight when daytime crowds thin and the old-Bangkok atmosphere intensifies; (3) 24-hour Bangkok food: 7-Eleven (ubiquitous, 24 hours, hot snacks, onigiri, microwave meals — baseline reliability); McDonald's 24-hour locations (some Bangkok locations); Sizzler (certain 24-hour Bangkok locations, less common); specific establishments known for 24-hour service in Bangkok: Din Tai Fung (Siam Paragon location, extended hours but not 24-hour); Bangkok's hospital-adjacent food: areas near Bumrungrad, Bangkok Hospital, and Samitivej have 24-hour small restaurants serving hospital staff and visitors (these are the most reliable late-night quality options for non-tourist Bangkok eating); (4) After-club eating (2–5am): Bangkok's post-nightclub food options: noodle shops near Silom serving late-night party crowd (Silom area kway teow shops open until 4am); Charoen Krung Road area (khao tom shops open late for night-shift workers); Pat Pong area (some food vendors); Ratchada entertainment area food: nearby noodle and rice shops catering to Ratchada nightclub district crowd after midnight; (5) Pad Thai street stalls at night: Bangkok's pad thai stalls (particularly those along Khao San Road and Thanon Sukhumvit side streets) maintain late hours (until 2–3am) specifically for nightlife crowd hunger; the post-club pad thai (at a street stall, not a restaurant) is a Bangkok nightlife cultural experience.",
    action: "Bangkok best 3am food: (1) Yaowarat late-night food stalls (any of the existing open stalls, khao tom shops visible by the yellow light and soup steam); (2) BTS Asok area street food (vendors near BTS Asok exit operate until late for late-working Sukhumvit residents); (3) Khao San Road food vendors (open until last bars close); finding late-night Bangkok food: asking your Grab driver is genuinely effective — Bangkok Grab drivers know current late-night food spots by area; (4) Sukhumvit Soi 38 area (even though the original market relocated, the area still has late-night vendors); hospital-adjacent restaurants near Bumrungrad (Soi 3 area) are the most reliable late-night quality eating in the Sukhumvit area.",
  },
];

export function BangkokFoodFest() {
  return (
    <div className="rounded-2xl border border-amber-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-amber-700 mb-3">
        🎪 Bangkok dining meta — food festivals & events, reservation culture & late-night eating
      </h2>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-amber-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-amber-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
