const SPOTS = [
  {
    name: "Bangkok Traffic Reality — Why It's Infamous, When It's Bad & How to Avoid It",
    emoji: "🚗",
    area: "Bangkok worst traffic corridors: Sukhumvit Road (Asok to On Nut, BTS below = best alternative); Ratchadamri/Wireless Road (business district, morning/evening); Silom-Sathon (financial district, 7–9:30am and 5–7:30pm worst); Ratchaprarop/Phaholyothin (airport route, avoid 7–10am); Ladprao intersection (north Bangkok, notoriously bad); Bang Na–Trat (eastern routes, industrial zone traffic); Don Mueang corridor (northern Bangkok to airport, rush hour catastrophic); real-time traffic: Google Maps live traffic, Waze (large Bangkok user base), BTS Skytrain for Sukhumvit/Silom corridors avoids road traffic entirely",
    price: "Expressway toll (Chalermmahanakorn/Si Rat): ฿35–75 per section; BTS Skytrain (Asok to On Nut, avoids traffic): ฿37; Grab taxi (Sukhumvit, 3km in traffic, 20 min): ฿80–150 metered plus traffic surcharge possible; Expressway taxi supplement: ฿70–120 per expressway section (passenger pays tolls); MRT single journey (Sukhumvit to Lumpini): ฿25–42; Grab JustGrab (basic, metered): ฿0 booking fee; Grab Car (premium, metered): ฿20–50 booking fee",
    why: "Bangkok's traffic congestion is among the worst in Asia and understanding it prevents itinerary disaster: (1) Why Bangkok traffic is so bad: Bangkok has approximately 10 million registered vehicles (more vehicles than persons in many cities); the city's road system was not planned for this density; key factors — urban sprawl without transit coverage created car dependency; expressway construction lagged behind population growth; the historic canal-to-road conversion created an irregular street grid without the radial efficiency of planned cities; (2) Congestion windows: Bangkok's peak traffic hours are 7:30–9:30am (morning peak), 5:00–8:00pm (evening peak); lunch hours (12–1:30pm) have moderate secondary congestion; rainy season (May–October) significantly worsens traffic (flooded road diversions, reduced visibility, accidents); school-adjacent areas have sharp school-hour congestion (7:30am, 3:30pm); (3) Expressway network: Bangkok has a well-developed expressway network (Don Mueang Tollway, Chalermmahanakorn, Si Rat, Outer Ring Road) that provides faster city crossing at toll cost; expressways are most useful for cross-Bangkok trips (west to east, north to south) and airport routes; Grab and taxis typically use expressways with passenger-paid toll supplements; (4) The 30-minute vs. 2-hour variability: the same Bangkok Sukhumvit trip can be 20 minutes at 10pm or 90 minutes at 6pm; tourist itineraries that rely on road transport timing during rush hours frequently fail; building 60–90 minute buffer for any road transport during peak hours is essential; (5) GPS accuracy in Bangkok: Bangkok's elevated BTS tracks, expressways, and multi-story malls create GPS shadow zones where position accuracy degrades; Google Maps gives directions but occasionally sends routes through closed roads, under construction sections, or mall car parks; local taxi driver navigation knowledge sometimes outperforms GPS in complex routing situations.",
    tip: "Bangkok traffic navigation strategy: (1) BTS-first routing: when planning Bangkok movement, start by identifying if both origin and destination are within 10-minute walk of a BTS Skytrain or MRT station; if yes, use transit regardless of travel time comparison with road — the transit time is predictable, the road time is not; (2) Off-peak road windows: 10am–3:30pm on weekdays is Bangkok's lowest road congestion window; planning restaurant visits, museum trips, and shopping during this window allows road transport without catastrophic delays; (3) Expressway toll app: Bangkok has a tag-based expressway system (Easy Pass/M-Flow); taxis and Grab cars may already have the tag; some rental cars lack it (requiring cash lane payment); understanding the expressway entry point and toll amounts for specific routes prevents in-traffic confusion; (4) Canal boat as emergency option: for west-east crossing of central Bangkok (particularly Pratunam to Asok), the Khlong Saen Saep canal boat is the fastest option during rush hour; the boat takes approximately 25 minutes from Pratunam to Asok (Sukhumvit) versus 45–90 minutes by road; this is Bangkok's most underutilized transit option; (5) Pre-booking vs. street hailing: Grab is more reliable than street hailing during rush hour because the driver knows the destination before accepting; street-hailed taxis may refuse difficult destinations during peak hours or traffic buildup; Grab's fixed-estimate pricing also eliminates the risk of taxi meter manipulation.",
  },
  {
    name: "Bangkok Public Bus System — BMTA Routes, Raptor App & Budget Transport",
    emoji: "🚌",
    area: "Bangkok bus authority: BMTA (Bangkok Mass Transit Authority); bus types: AC (red/cream or blue/cream, ฿11–25 per journey); non-AC (orange, ฿8–15 flat fare zone); electric buses (new BMTA EV fleet, expanding 2024–2026); key routes for visitors: Route 40 (Airport to Democracy Monument to Khao San Road); Route 15 (Sanam Luang to Bangkokian Museum, riverside area); Route 2 (Victory Monument to Sanam Luang); bus app: Raptor (Thailand's bus tracking app, real-time BMTA GPS tracking); ViaBus (Thai app for bus route finding); Google Maps (has partial BMTA route coverage); challenge: inconsistent schedules, traffic delays, and limited English signage",
    price: "Non-AC bus (orange): ฿8–15 flat; AC bus (red/cream, blue/cream): ฿11–25 by zone; Night bus (O range): ฿9.50–24; Day pass (limited routes): not widely available unlike BTS; Monthly bus pass: limited options; Comparison: BTS single journey ฿16–62 vs. bus ฿8–25 for similar routes — bus is cheaper but slower",
    why: "Bangkok's public bus system is an underutilized resource for budget travelers: (1) Extensive route network: BMTA operates approximately 400+ bus routes covering Bangkok's entire metropolitan area; while the BTS Skytrain covers the core Sukhumvit and Silom corridors, buses cover outer Bangkok, cross-river routes, and areas without rail; (2) True local experience: Bangkok's public buses (particularly non-AC orange buses) provide the most unfiltered local commuter experience; route conductors collect fares with a manual ticket system; Thai commuters, market vendors, students, and workers are the primary clientele; this is Bangkok as Thai residents actually travel; (3) Air-conditioned buses as value option: BMTA's red/cream and blue/cream AC buses (฿11–25) provide reasonable travel quality for the price; AC buses to destinations like the outskirts of Bangkok, specific museum areas, and cross-city routes that BTS doesn't cover are the most practical use case; (4) Electric bus expansion: Bangkok's new electric bus fleet (entering service from 2023–2026) gradually replaces the aging diesel fleet; the EV buses (visible by design) are newer and air-conditioned; routes on the EV network provide a noticeably better experience than older diesel buses; (5) Night bus availability: unlike the BTS Skytrain (last service midnight), BMTA night buses operate through the night (limited routes, 1am–4am service); for travelers without Grab budget or in areas Grab doesn't quickly service, BMTA night buses provide an option.",
    tip: "Bangkok bus practical guidance: (1) Raptor app download: the Raptor app (available iOS and Android, developed by Chulalongkorn University) provides real-time BMTA bus GPS tracking; it shows approaching buses, route maps, and terminus information; downloading Raptor before traveling to Bangkok significantly reduces bus uncertainty; (2) Fare conductor system: Bangkok buses use manual fare collection by a conductor (not automated payment machines); the conductor comes to each passenger; paying with correct change (฿5–20 coins and notes) is appreciated; having a ฿20 note ready avoids delay; (3) Route number priority: Bangkok bus routes are numbered (1–999+); knowing the route number for your journey before boarding is essential; checking Google Maps bus routing or Raptor for the correct route number and approximate departure/arrival stops prevents getting on the wrong bus; (4) Night bus safety: Bangkok night buses are used by a mix of late-night commuters, people after late-night entertainment, and shift workers; they are generally safe with basic urban awareness; solo travelers, particularly women, may prefer Grab for late-night return transport as it provides door-to-door service and driver accountability; (5) Bus stop identification: Bangkok bus stops are marked with blue and white signs with route numbers; in busy areas, stops may have multiple signboards for different routes; identifying the correct stop position for your route number before the bus arrives prevents missing the stop.",
  },
  {
    name: "Bangkok Car Rental & Driving — Traffic Law, International License & Practical Guide",
    emoji: "🚘",
    area: "Bangkok car rental: Avis (multiple Bangkok locations, airport pick-up); Hertz Bangkok (Suvarnabhumi, Don Mueang, city center); Budget Car Rental Bangkok; Thai-local rental companies (cheaper, less English support); International Driving Permit: required for foreigners renting from recognized agencies; Thailand drives on the left; Bangkok driving requirements: IDP + home country license; parking: shopping mall underground parking (฿20–30/hour, most central Bangkok malls); street parking (pay zones, Bangkok app payment); road rules: speed limits 80km/h urban expressway, 60km/h urban road; drunk driving limit: 0.05% BAC; road tax/safety sticker must be visible on windscreen; Google Maps navigation standard for Bangkok roads",
    price: "Daily car rental (compact, from Avis/Hertz): ฿1,200–2,500/day; Daily car rental (local company): ฿600–1,200; Expressway tolls per section: ฿35–75; Fuel (regular gasoline/benzene): ฿44–52/liter; Fuel (diesel): ฿30–35/liter; Mall parking: ฿20–30/hour (free with shopping validation at many malls); International Driving Permit (from your home country): cost varies by country; Traffic fine (speed violation): ฿500–2,000; No-helmet fine (motorcycle): ฿500",
    why: "Driving in Bangkok and Thailand enables destinations not reachable by public transit: (1) When to rent vs. use transit: Bangkok's BTS/MRT covers the central tourism and business corridor well; cars are most practical for Kanchanaburi, Khao Yai, Hua Hin, or provincial Thailand where public transit is limited or absent; in central Bangkok, a rental car is usually a disadvantage (parking difficulty, traffic, no time savings over BTS); (2) Thai driving culture vs. rules: Thai traffic law exists but enforcement is variable; driving in Bangkok requires adjusting to drivers who change lanes without signaling, motorbikes that filter between lanes, and mixed pedestrian-traffic interaction at non-signalized crossings; Thai driving style rewards defensive, patient, anticipatory driving; (3) Expressway network navigation: Bangkok's expressway system (Si Rat, Don Mueang, Chalermmahanakorn, Bang Na, Outer Ring) connects Bangkok's zones efficiently when toll cost is acceptable; Google Maps typically routes via expressway when faster; selecting 'avoid tolls' option routes via surface roads (usually significantly slower); (4) Parking app payment: Bangkok has implemented app-based parking payment (EasyParking BKK and similar apps) at some street parking zones; traditional coin meters remain in many areas; mall parking is universally available but expensive in central Bangkok; (5) Mountain/river driving in Thailand: driving outside Bangkok (to Khao Yai, Kanchanaburi, Hua Hin, Rayong) reveals Thailand's well-maintained intercity road network; highway driving between Bangkok and provincial destinations is straightforward; mountain roads in Northern Thailand (Doi Inthanon, Chiang Rai) require more attention than flat central Thailand routes.",
    tip: "Bangkok/Thailand driving practical guidance: (1) International Driving Permit requirement: Thai law requires an IDP for foreign drivers; rental companies from recognized international brands verify IDP; smaller local rental agencies may be more flexible but the legal requirement still applies; obtaining an IDP from your home country automobile association before travel is straightforward (same-day issue in most countries); (2) Songthaew as supplement: in areas where renting a car for a full day is wasteful, shared songthaew (red trucks or pickup trucks with bench seating) serve specific routes in many Thai cities and tourist areas; they're cheap (฿20–50) and go to predictable destinations; flagging down and confirming destination before boarding; (3) Fuel type clarity: Thai gas stations distinguish E20 and E85 (ethanol blends), regular benzene (gasoline), and diesel; rental cars specify what fuel they require (check before filling); most modern cars use E20 or benzene; diesel vehicles (typically pickup trucks and commercial vehicles) are clearly diesel; mixing fuel types is expensive and damaging; (4) Road checkpoint awareness: Thai police conduct occasional vehicle checkpoints (particularly on routes from Pattaya and Phuket) checking license, vehicle registration, and breathalyzer; maintaining documentation in the car and being respectful at checkpoints is the correct approach; foreigners are typically waved through or subjected to brief document check; (5) Bangkok parking app: download the 'ParkingBKK' or Bangkok-specific parking apps before arrival; these apps show available parking lots, current occupancy, and facilitate mobile payment; saves time at mall parking exits.",
  },
];

export function BangkokTrafficTransport() {
  return (
    <div className="rounded-2xl border border-gray-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-gray-700 mb-3">
        🚗 Bangkok transport reality — traffic strategy, bus system & car rental guide
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-gray-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-gray-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-gray-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
