const TOPICS = [
  {
    title: "Bangkok as Thailand's Capital — Government Districts, Parliament & Political Geography",
    emoji: "🏛️",
    summary: "Bangkok is not just a city — it is Thailand's political, administrative, and ceremonial capital with a highly concentrated governmental function: (1) Bangkok's capital concentration: Bangkok concentrates Thailand's executive (Government House, Dusit Palace complex), legislative (National Assembly, Dusit), judicial (Constitutional Court, Supreme Court), and administrative functions to a degree unusual even by capital city standards; approximately 30–40% of Thailand's government employees work in Bangkok; (2) Government House (Talaeng Chan): Thailand's Government House (Sunthorn Phu Road, Dusit District) is the seat of executive power; the Prime Minister's office, Cabinet meeting rooms, and executive support agencies are located here; the Government House complex includes ornate heritage buildings (particularly the Ananta Samakhom Throne Hall, European-influenced, 1915) and modern administrative wings; (3) National Assembly of Thailand: Thailand's Parliament (National Assembly) is housed in the modern National Parliament of Thailand building (Kiakkai Road, Sam Sen area, Dusit District), moved from the old Parliament building in 2021; the new parliament complex is designed in Thai-contemporary style; public gallery access for specific sessions is theoretically available (check current rules); (4) Bangkok Metropolitan Administration: Bangkok is governed separately from Thailand's 77 provinces; the Bangkok Metropolitan Administration (BMA) is headed by the Governor of Bangkok (separately elected from the national government since 2022 after a 9-year pause in elections); the BMA manages Bangkok's city services, infrastructure, and urban planning independently of the national government; (5) Coup history and visitor implications: Thailand has experienced 12+ successful military coups since 1932; military coups have historically resulted in temporary curfews, restricted movement, and occasional airport closures; visiting Bangkok during politically uncertain periods requires monitoring news; protest areas (particularly around Government House and Democracy Monument) should be avoided during active demonstrations regardless of political cause.",
    action: "Ananta Samakhom Throne Hall (Dusit Palace complex, Royal Dusit District) for accessible historical parliament building tours; Democracy Monument (Ratchadamnoen Avenue) for historical political landmark; BACC Bangkok Art and Culture Centre (political art context frequently present); current Bangkok news for political situation monitoring: Bangkok Post, The Nation; Thailand's political situation evolves rapidly — verify current status through recent English-language news sources before travel.",
  },
  {
    title: "Thailand's Lèse-Majesté Law — What Visitors Must Understand",
    emoji: "⚠️",
    summary: "Thailand's lèse-majesté law (Section 112 of Thailand's Criminal Code) is one of the world's most strictly enforced laws protecting the monarchy and requires specific visitor understanding: (1) What the law covers: Section 112 prohibits defamation, insults, or threats against the King, Queen, Heir Apparent, and Regent; in practice, enforcement extends broadly to negative commentary about the Thai Royal Family in virtually any format; the penalty is 3–15 years imprisonment per count; cases can be filed by anyone (not just government), and complaints are investigated seriously; (2) Application to foreigners: Section 112 applies to actions in Thailand regardless of nationality; foreign nationals have been arrested, convicted, and imprisoned under this law; statements made outside Thailand that reach Thailand may also be investigated; this law represents one of the most significant legal risks for visitors engaging in political commentary while in Thailand; (3) Practical visitor guidance: visitors should: avoid commenting on Thai royal family members in public; be careful with social media posts about Thailand's royal family while physically in Thailand; treat images of the King (on currency, posters, official photographs) respectfully; not make satirical or critical comments about the monarchy even in private conversations (third parties may report); (4) Context for understanding the law's role: the monarchy is considered central to Thai national identity; Thai Buddhist concepts position the King as a symbol of national unity; understanding this cultural role (rather than approaching the law purely through a Western free speech framework) provides context for visitor behavior; (5) Currency and image respect: Thai bank notes carry the King's image; Thai cultural norms expect respectful treatment of currency (not folding with the image inside, not placing on the ground); standing for the royal anthem (played before Thai films and at certain public events) is expected and practically enforced; the national anthem is played daily at 8am and 6pm at public venues (government buildings, stations, parks) with people typically stopping to stand.",
    action: "Legal guidance: contact the Embassy of your home country immediately if arrested or questioned about any speech-related offense in Thailand; Australian, British, and US embassies have provided formal advisories about Section 112 — verify current country-specific travel advisories from official government sources before travel; in practice, tourism-focused behavior (sightseeing, eating, shopping) does not normally bring visitors into contact with this law.",
  },
  {
    title: "Bangkok's City Planning & Urban Development — The BMA Master Plan & Future Bangkok",
    emoji: "🏗️",
    summary: "Bangkok is in an active period of urban transformation with ongoing infrastructure investments reshaping the city: (1) Bangkok Comprehensive Plan: the Bangkok Comprehensive Plan (municipal zoning and land use master plan) guides Bangkok's development; the current plan designates mixed-use corridor development along BTS/MRT lines; industrial zones (Eastern Seaboard expansion); green space preservation requirements; and heritage conservation zones in Rattanakosin Island; (2) Metro expansion timeline: Bangkok's Mass Rapid Transit system is in its most ambitious expansion phase; Orange Line (Thailand Cultural Centre to Bang Khun Non, east-west), Purple Line South (Tao Poon to Ratchaburana), Yellow Line extensions, and additional stations are in various construction phases; projected completion dates for specific lines extend 2025–2030; the metro expansion will significantly affect property values and neighborhood character in currently off-grid areas; (3) Canal rehabilitation program: Bangkok has ongoing canal restoration (klang rehabilitation); targeted canal water quality improvement and canal-side public park development is a BMA priority; the Khlong Pha Nong project (north Bangkok) and various inner-city canal parks demonstrate the direction; (4) Chao Phraya riverside development: the riverside area (particularly the Charoen Krung creative district between Sathorn and the southern riverside) is undergoing rapid gentrification into boutique hotels, designer restaurants, art galleries, and creative workspace; this transition is Bangkok's most visually notable current development; (5) Bangkok's sustainability commitments: Bangkok has committed to net-zero greenhouse gas emissions by 2050 through BMA formal commitments; near-term priorities include BTS electrification, EV charging infrastructure expansion, green building standards, and waste-to-energy facilities; the gap between policy commitments and implementation progress is typical of large developing-world cities.",
    action: "BMA Bangkok website (bangkok.go.th) for official city planning documents; Bangkok mass transit authority websites (BTS, MRT, BEM, Expressway Authority) for construction timeline updates; Skyline Bangkok blog for property development and transit expansion tracking; Charoen Krung creative district self-guided walking tour for current gentrification front observation; TCDC (Thailand Creative and Design Center, Charoenkrung 29 area) for Bangkok creative economy programming.",
  },
];

export function BangkokGovernment() {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-slate-700 mb-3">
        🏛️ Bangkok governance — political geography, lèse-majesté law & city master planning
      </h2>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-slate-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-slate-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
