const TOPICS = [
  {
    title: "Bangkok Crime Reality — What Tourists Actually Face vs. Media Perception",
    emoji: "🛡️",
    summary: "Bangkok's crime profile for tourists is significantly better than media perception suggests, with specific risks that are manageable with awareness: (1) Bangkok's actual safety ranking: global safety indices (Numbeo Crime Index, EIU Safety and Security, Economist Intelligence Unit) consistently rank Bangkok as safer than most major Western cities for personal crime; violent crime against tourists is rare; property crime (theft, pickpocketing) and fraud (scams) are the most common visitor experiences; (2) Common tourist crime by type: (a) Gem scam: most sophisticated Bangkok tourist fraud — elaborate setup involving friendly strangers, a closed temple, a gem merchant, and overpriced/fake gems that 'can be resold at profit back home'; running since the 1980s, still operating; refusing to enter gem shops under any circumstance prevents this; (b) Tuk-tuk tour scam: tuk-tuk driver offers ฿10 tour of city, route requires stopping at 'free' tailor/gem/tourist shop; drivers earn fuel vouchers from shops for each tourist delivered; (c) Taxi meter scam: taxis claiming meter is 'broken' and demanding flat rate; solution: exit and find a metered taxi; (d) Card skimming: ATM card skimmers at poorly-maintained ATMs; bank ATMs inside branches are more secure than standalone ATMs; (e) Drunk drugging: in entertainment areas, accepting drinks from strangers carries drugging risk; (3) Street theft: Bangkok has minimal pickpocketing compared to European tourist cities; bag snatching from motorbikes (particularly grab-and-run) is the most common street theft; wearing bags on the side away from traffic reduces snatching risk; (4) Food/restaurant overcharging: some tourist-area restaurants don't display menus with prices (menus change when foreigners sit down); asking the price before ordering or eating where prices are posted prevents overcharging; (5) COVID-era scam evolution: Bangkok scams evolved during and after COVID; cryptocurrency scams, romance scams ('pig butchering' scams) where Bangkok-based operations targeted overseas victims increased; be skeptical of any investment opportunity introduced through social media.",
    action: "Tourist Police hotline: 1155 (English-speaking officers, 24 hours); Regular police emergency: 191; Tourist Police Division headquarters: Unico House, Silom Road, Bangkok; reporting scams: file report at nearest police station with documentation; gem/tailor scam specific report: Tourist Police Division; credit card skimming: report immediately to your issuing bank and to TripAdvisor/Google Maps reviews of the specific ATM location; US embassy Bangkok scam reports: 02-205-4000.",
  },
  {
    title: "Thai Drug Laws — Zero Tolerance, Penalties & What Bangkok Tourists Must Know",
    emoji: "⚠️",
    summary: "Thailand's drug laws are among the harshest in the world and represent the most severe legal risk for international visitors: (1) Death penalty for drug trafficking: trafficking (manufacturing, importing, exporting, selling) quantities above legal threshold results in the death penalty in Thailand; the threshold is relatively low (Class 1 narcotics: 20 grams pure/370 grams mixed methamphetamine means trafficking presumption); multiple foreign nationals have received death penalties (some commuted to life imprisonment) for drug offenses in Thailand; (2) Possession penalties: drug possession (even small quantities for personal use) results in imprisonment; Class 1 narcotics (heroin, methamphetamine, cocaine, MDMA) possession for personal use: up to 15 years imprisonment; cannabis possession: Thailand legalized cannabis for medical and commercial use in 2022 (under Food and Drug Administration framework) but possession of high-THC strains, use in public places, and under-18 use remain restricted; the law is still evolving; (3) Methamphetamine reality in Thailand: methamphetamine ('yaba,' Thai pills, and crystalline 'ice') has a major domestic trafficking and use problem in Thailand; drug sweeps by Thai police occur regularly in entertainment areas; being caught near other people who have drugs creates legal risk; (4) Random drug testing at entertainment venues: Thai police conduct random venue drug testing operations (urine tests on exit, bag searches on entry) at entertainment venues in Bangkok; those who test positive for any controlled substance face arrest regardless of where the substance was consumed; (5) Airport drug interception: Suvarnabhumi and Don Mueang airports have sophisticated drug detection; body-packing interception, sniffer dogs, and X-ray systems mean attempting to transport drugs through Bangkok airports is extremely high risk; Thailand prosecutes airport drug couriers aggressively.",
    action: "If arrested for any drug-related offense: request consular notification immediately (all detained foreign nationals have the right to notify their embassy); do not sign any Thai-language documents without translation and legal representation; contact your country's Bangkok embassy immediately; US: 02-205-4000; UK: 02-305-8333; Australia: 02-344-6300; Canada: 02-636-0540; Thailand drug legal defense: Siam Legal International, Ryn & Partners Law Firm for criminal defense; avoid carrying others' luggage through Thai airports regardless of payment offered.",
  },
  {
    title: "Bangkok Hospital & Emergency Guide — Ambulance, Insurance & Tourist Emergency Contacts",
    emoji: "🏥",
    summary: "Bangkok has excellent medical infrastructure but navigating emergencies requires preparation: (1) Emergency numbers: general emergency is 1669 (Erawan Medical Centre ambulance, English-speaking dispatcher available); police is 191; tourist police 1155; 1669 dispatches from the Erawan Medical Centre system to the nearest appropriate hospital; international-quality hospitals (Bumrungrad, Bangkok Hospital, Samitivej) also have their own ambulance services; (2) Hospital quality stratification: Bangkok's hospital quality varies enormously; the top-tier international hospitals (Bumrungrad International, Bangkok Hospital, Samitivej, Bangkok Christian Hospital, St. Louis Hospital) have JCI (Joint Commission International) accreditation and international-standard care; government hospitals (Siriraj, Ramathibodi, Chulalongkorn) are excellent for routine care but may have longer waits and less English capability; cheaper 'clinical' hospitals in tourist areas may have lower quality; (3) Bumrungrad International's emergency capability: Bumrungrad International Hospital (Sukhumvit 3, nearest BTS: Nana) has Bangkok's most internationally recognized emergency department; multilingual staff (20+ languages), international insurance billing, 24-hour emergency, and specialist availability make it the default for international medical emergencies in Bangkok; (4) Travel insurance coverage: Thailand's premium hospitals (Bumrungrad, Samitivej, Bangkok Hospital) readily accept major travel insurance direct billing; confirming insurance card and policy number at admission allows direct billing; cash payment followed by insurance reimbursement is the backup method; keeping a ฿50,000–100,000 credit card emergency limit available for medical pre-authorization covers most outpatient and short inpatient situations; (5) Medical evacuation coverage: for serious conditions requiring repatriation to home country, medical evacuation coverage (typically a travel insurance add-on) covers the ฿500,000–2,000,000+ cost of commercial medical evacuation; Bangkok is a regional medical hub with good evacuation flight infrastructure; most serious conditions are treated adequately in Bangkok's international hospitals without requiring evacuation.",
    action: "Emergency: 1669 (ambulance/EMS); 191 (police); 1155 (tourist police); Bumrungrad International Hospital emergency (24-hour): 02-667-1000, Sukhumvit 3 (BTS Nana, 5 min walk); Bangkok Hospital emergency: 1719; Samitivej Sukhumvit emergency: 02-022-2222; insurance emergency assist: call the number on your insurance card for direct billing authorization; for minor medical issues: Samitivej hospitals, Bangkok Hospital branch network, or international clinic networks throughout Bangkok; pharmacies: Boots Thailand (boots.co.th) for over-the-counter medications with English staff at many locations.",
  },
];

export function BangkokCrimeLaw() {
  return (
    <div className="rounded-2xl border border-red-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-red-700 mb-3">
        🛡️ Bangkok safety essentials — crime reality, drug laws & emergency medical guide
      </h2>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-red-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-red-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
