const SPOTS = [
  {
    name: "Bangkok Edible Insects — Street Food Fried Bugs, Markets & Thailand's Entomophagy Culture",
    emoji: "🦟",
    area: "Bangkok edible insect locations: Khao San Road area — the most tourist-accessible insect street food; insect carts are placed specifically for tourist consumption; Patpong Night Market (Silom, BTS Sala Daeng) — tourist-facing insect stall consistently present; Bang Lampu market area (near Khao San) — local-facing insect vendors with broader species selection; Chinatown/Yaowarat — some insect vendors particularly for cricket and silkworm; Don Mueang Airport area night market — local insect consumption culture without tourist premium; Chatuchak Weekend Market (food section) — various insect vendors; specialty insect food: Insects in the Backyard (Chatuchak area, established insect food café, English-friendly); Khlong Toei fresh market sometimes carries live insects for cooking purposes",
    price: "Bangkok edible insect pricing: tourist-zone insect tray (mixed fried insects, Khao San area): ฿100–200 per portion (tourist premium, 3–5x local price); local market insect vendor (Khlong Toei, outer Bangkok): ฿20–50 per portion; single insect skewer: ฿10–30; Insects in the Backyard cafe (specialty insect cuisine): ฿150–350 per dish; packaged cricket protein snacks (7-Eleven, Tops Supermarket): ฿25–60 per pack; insect protein powder (sports nutrition, specialty health stores): ฿200–500 per package; live insects for cooking (where available): ฿50–100 per 100g",
    why: "Thailand has one of the world's most developed insect eating traditions — an authentic culinary practice, not a tourist stunt, with regional variations and sophisticated preparation methods: (1) Thai insect eating (kan kin maeng) cultural context: insect consumption in Thailand is concentrated in northeastern Thailand (Isaan) and northern Thailand, where it developed as a practical protein source in agricultural communities; insects are eaten both as fresh preparation (fried, roasted, grilled) and preserved (fermented, dried); the practice migrated to Bangkok with the large Isaan migrant community that forms a significant portion of Bangkok's working population; (2) Thailand's commercially farmed insects: Thailand has developed a formal insect farming industry; approximately 20,000 insect farms operate across Thailand; most commercially farmed insects: cricket (jing reed, จิ้งหรีด) — the most commercially important; bamboo worm (rod non mai phai) — prized, delicate flavor; silkworm pupae (dok mai phai) — rich, cheese-like; mealworm (nong mai krut) — widely used in packaged snacks; grasshopper/locust (took gae, แตกแตน); (3) Bangkok insect species guide: fried bamboo worm (rort pet, rod non) — delicate, crispy, nutty flavor; most recommended for insect beginners; fried cricket (jing reed) — crunchy, light, grassy-savory; the most commonly farmed; fried silkworm (non mai) — stronger flavor, rich and creamy texture, most polarizing for beginners; fried scorpion (maeng por) — mostly theatrical at tourist venues; cooking kills venom; taste is similar to soft-shell crab; giant water bug (maeng da) — distinct flavor, used for flavoring and oil extraction rather than whole eating; (4) Insect nutrition context: Thailand's insect industry is part of a broader global entomophagy advocacy movement; crickets and mealworms provide 65–80% protein by dry weight; 2,000x less greenhouse gas than beef production per gram of protein; Thailand exports insect protein products (cricket powder, insect snacks) to Europe and North America; the Bangkok-based insect food industry has received attention from UN FAO as a model for sustainable protein; (5) Insect-flavored products without whole insects: for visitors interested in the flavor profile without eating whole insects: maeng da (giant water bug) flavoring is used in traditional Thai preparations; cricket protein snacks at 7-Eleven (Enjoy Cricket Bar brand and similar) provide insect protein in a more approachable packaged format; insect-flavored sauces are available at specialty food stores in Bangkok.",
    tip: "Bangkok insect eating guide: (1) Starting recommendation for beginners: bamboo worm (rod non) and cricket (jing reed) are the most recommended starting insects — both are dry, crispy, and have the least challenging texture and flavor for insect newcomers; avoid starting with silkworm (rich and intense) or giant water bug (distinct flavor); (2) Freshness indicator: freshly fried insects should be hot and crispy; avoid insects that appear soggy, have discoloration, or have been sitting in the sun — insect vendors at tourist-heavy Khao San Road sometimes keep product too long; (3) Tourist vs. local pricing: insect vendor trays on Khao San Road charge tourist prices (฿100–200) for small portions; the same insects at Chatuchak market food section or Khlong Toei market cost ฿20–50; (4) Insect food restaurant: Insects in the Backyard in the Chatuchak area offers a full restaurant format with insect cuisine in sophisticated presentations — appropriate for food explorers who want to try insects in a comfortable setting rather than street food context; the menu includes larb with cricket, pasta with worm, and other creative preparations; (5) Packaged insects for travel: sealed, fried insect snack packages from Bangkok supermarkets pass international customs more reliably than fresh food; cricket snack packs from Tops Supermarket or Villa Market are clean-packaged and can be taken home as a food souvenir (check destination customs regulations — Australia has strict biosecurity for food items).",
  },
  {
    name: "Bangkok's Urban Biodiversity — City Wildlife, Canal Fish & Bangkok's Unexpected Natural World",
    emoji: "🦎",
    area: "Bangkok urban wildlife locations: Lumpini Park (BTS Sala Daeng/MRT Lumpini) — Bangkok's iconic monitor lizard population (water monitor, ban ta ko; largest can exceed 2m; sunbathing in park during morning); Chatuchak Park (adjacent to Chatuchak Weekend Market, BTS Mo Chit) — monitor lizards, birds; Sukhumvit area storm drains — monitor lizard sightings in drainage systems; Bang Krachao canal network — herons, egrets, kingfishers, monitor lizards; Khlong Saen Saep canal — water birds visible from canal boats; Romklao area on eastern Bangkok periphery — wetland birds visible from elevated positions; Bang Pu (Samut Prakan, 30km from Bangkok) — seasonal migratory birds, November–March",
    price: "Bangkok wildlife viewing costs: Lumpini Park monitor lizard viewing: free (Bangkok's most accessible urban wildlife); bird observation: free (binoculars helpful, bring or rent); Bang Pu migratory bird observation (Samut Prakan province): free, transport by Grab (฿300–500 from central Bangkok); Safari World Bangkok (Minburi area, northeast Bangkok): ฿700–1,500 admission for safari and marine park combined; Khao Kheow Open Zoo (Chonburi, 90 minutes from Bangkok): ฿200–400 admission; Dusit Zoo (Dusit area, adjacent to Government House) — traditional zoo being developed as new Dusit-Rattanakosin heritage park; Bangkok's public green spaces: free",
    why: "Bangkok surprises most visitors with its urban biodiversity — a megacity that retains significant wildlife populations adapted to city living: (1) Lumpini Park monitor lizard culture: the water monitor lizards (varanids) in Lumpini Park have become one of Bangkok's iconic sights, widely photographed and discussed; the population is large (50–100 individuals of various sizes regularly visible); the lizards are habituated to humans (approach within 3–5 meters tolerated); Thais are generally accustomed to the monitors and treat them with a combination of superstitious respect and casual coexistence; the monitors are excellent swimmers (Lumpini's lake provides fish, turtles, and aquatic resources); (2) Bangkok's canal fish population: Bangkok's klong system contains significant fish populations despite water quality challenges; species include: snakehead fish (pla chon, naturally present), tilapia (introduced), Chinese carp, catfish; Bang Krachao's less-polluted canals have visibly clear water with fish visible in shallows; the canal ecosystem supports egrets and herons that hunt fish from canal banks; (3) Bangkok night wildlife: Bangkok's urban wildlife includes significant nocturnal populations: geckos (jing-joe, จิ้งจกหรือ) are present in virtually every Bangkok building; the chirping gecko sound is a constant Bangkok ambient soundscape at night; the geckos eat insects and mosquitoes, performing a significant pest control function; Asian house geckos (Hemidactylus frenatus) are different from the larger tokay gecko (tuk-gae, ตุ๊กแก) whose loud call ('tuk-GAE') gives the tuk-tuk its name onomatopoeically; (4) Bangkok birds: Bangkok's urban environment supports more bird diversity than most comparable megacities; species commonly observed: spotted dove (nok khao doi), oriental magpie robin (nok khao kwan), common myna, Eurasian tree sparrow, black-crowned night heron (common along klongs), cattle egret, purple heron; Bang Krachao provides habitat for more diverse species including kingfisher species, herons, and open grassland birds; (5) Bangkok's bat population: Bangkok has significant bat populations in temple grounds, large old trees, and cave formations within day-trip range; the largest visible bat roost near Bangkok: Khao Chong Phran Cave (Ratchaburi province, 90 minutes from Bangkok) — millions of wrinkled-lipped bats emerge at dusk in an extraordinary aerial display; the bat vortex rising from the cave mouth is one of Thailand's most spectacular natural phenomena and can be experienced as a Bangkok day trip.",
    tip: "Bangkok urban wildlife viewing: (1) Lumpini Park monitor timing: monitors are most active in the morning (7–10am) before the heat peak; they bask near the lake shore and dig in the park lawn areas; largest individuals (2m+) are usually around the larger lake; photograph safely from 3–5m — they are not aggressive unless cornered; (2) Bang Krachao for birds: cross to Bang Krachao (ferry from Klong Toei) on a bicycle and follow the canal paths — kingfishers are visible from canal bridges at dawn; bring binoculars for the best experience; the Bang Krachao green area preserves genuine wetland habitat; (3) Bat vortex at Khao Chong Phran: organize a day trip to Ratchaburi province (90 minutes from Bangkok) to arrive at the bat cave by 5:30pm (dusk viewing); millions of bats emerge continuously for 30+ minutes; absolutely free to observe from the viewing area; combine with Damnoen Saduak floating market (nearby) for a day trip; (4) Safari World Bangkok (Minburi): Bangkok's Safari World is a 2-hour drive from central Bangkok but provides accessible wildlife viewing; the Open Safari section (drive-through wildlife park) includes giraffe, zebra, cheetah, lion, and deer free-ranging; the Marine Park section has shows (verify current animal welfare standards before booking); (5) Night safari at Khao Kheow Open Zoo: Khao Kheow Open Zoo (Chonburi, 90 minutes from Bangkok by car) operates a night safari component (additional evening hours) where nocturnal animals are active; the zoo's open space and natural vegetation create a less confined zoo aesthetic than Dusit Zoo in central Bangkok.",
  },
  {
    name: "Bangkok Tropical Disease Awareness — Dengue, Rabies, Hepatitis & Bangkok Visitor Health Reality",
    emoji: "🦟",
    area: "Bangkok tropical disease context: Bangkok's urban environment has different disease risk profiles than rural Thailand; dengue transmission: present throughout Bangkok, higher risk during monsoon (May–October) when Aedes mosquito breeding increases; malaria: NOT endemic in Bangkok city; malaria risk is in border areas (Myanmar, Cambodia, Laos borders) and forested northern regions; rabies: Bangkok stray dog and cat population; Thai wildlife (bats, monkeys) in areas outside central Bangkok; food-borne illness: Bangkok's street food is generally safe but risk increases at venues with poor hygiene, unrefrigerated seafood, and raw food items; water: Bangkok tap water is technically treated but not potable; bottled water or purified water is standard",
    price: "Bangkok health prevention costs: dengue vaccine (Dengvaxia, requires prior dengue exposure history — consult travel medicine physician): ฿3,000–5,000 per dose, 3-dose series; hepatitis A vaccine: ฿600–1,200 per dose; hepatitis B vaccine series: ฿500–1,000 per dose; typhoid vaccine (injectable, 2-year protection): ฿800–1,500; Japanese encephalitis vaccine: ฿1,500–2,500 per dose, 2-dose series; rabies pre-exposure prophylaxis: ฿800–1,500 per dose, 3-dose series; travel health consultation (Bangkok Hospital travel clinic or Bumrungrad travel clinic): ฿500–1,000 per consultation; bottled water retail price: ฿6–20 per 600ml bottle at Bangkok 7-Eleven and supermarkets",
    why: "Understanding Bangkok's real health risk profile (as opposed to generic tropical disease warnings) helps visitors prepare appropriately without excessive anxiety: (1) Dengue fever — Bangkok's most significant mosquito-borne disease risk: dengue is transmitted by the Aedes aegypti mosquito, which is a daytime biter (unlike malaria mosquitoes which bite at night); Bangkok has seasonal dengue risk, highest July–October; symptoms: sudden high fever, severe joint and muscle pain (breakbone fever), rash 3–5 days after fever onset; no specific treatment (supportive care); prevention: mosquito repellent (DEET 30%+ or picaridin); long sleeves in heavily vegetated areas; no vaccine is universally recommended — Dengvaxia requires prior dengue exposure; (2) Food safety in Bangkok — the real risk: Bangkok's street food culture is generally safer than its reputation suggests because turnover is high and food is freshly cooked; the highest risk scenarios: raw seafood (oysters, raw shrimp); raw salads at venues without refrigerated transport chain; ice from tap water sources (most Bangkok ice comes from commercial ice factories with purified water — the old 'ice risk' concern has largely been addressed in Bangkok); reheated food; (3) Rabies — real but preventable: Thailand has endemic rabies; Bangkok's stray dog and cat population creates genuine exposure risk; if bitten or scratched by an unknown animal in Bangkok: clean with soap and water immediately (10 minutes), then go to Bumrungrad or Bangkok Hospital emergency for post-exposure prophylaxis (PEP) assessment; PEP is highly effective when administered promptly; Bangkok has ready access to rabies vaccine and immune globulin; pre-travel rabies pre-exposure prophylaxis is recommended for stays over 1 month or frequent Thailand visits; (4) Sexually transmitted infections (Bangkok context): Bangkok's entertainment industry creates a significant STI context for visitors; HIV, syphilis, chlamydia, gonorrhea and other STIs are present in Bangkok's entertainment district population; comprehensive safer sex practices are essential; PrEP (HIV pre-exposure prophylaxis) is available through Bangkok private clinics at low cost compared to Western countries (฿1,000–2,000/month vs. ฿10,000–30,000 in USA); anonymous HIV testing available at Bangkok's sexual health clinics (anonymous clinics exist, search 'Bangkok HIV testing'); (5) Sun and heat health in Bangkok: Bangkok's heat (35–40°C in hot season) combined with high humidity creates significant heat stress risk for visitors from temperate climates; heat-related illness progression: heat cramps → heat exhaustion → heat stroke (medical emergency); prevention: hydration (aim for 3–4 liters daily in hot season), rest in air-conditioning during 11am–3pm peak heat, avoid alcohol in sun, recognize early heat exhaustion symptoms (heavy sweating, weakness, cold skin, rapid pulse).",
    tip: "Bangkok health preparation: (1) Pre-travel vaccination: consult a travel medicine physician 4–6 weeks before Bangkok travel; typical Bangkok travel vaccination protocol: ensure Hepatitis A, Typhoid, and Hepatitis B are current; consider Japanese Encephalitis for rural Thailand side trips; rabies pre-exposure for extended stays; (2) Dengue prevention daily: apply DEET repellent (30%+ concentration) to exposed skin each morning; Aedes mosquitoes bite during day, especially at dawn and dusk; accommodation with AC naturally reduces mosquito exposure; (3) Hydration strategy for Bangkok heat: drink 3–4 liters of water daily in Bangkok; electrolyte supplements (available at Bangkok 7-Eleven as Minuto or similar rehydration drinks, ฿15–30 per bottle) help replace sodium and potassium lost through sweat; avoid excessive alcohol in sun; (4) Bangkok hospital pharmacy self-treatment: traveler's diarrhea (the most common Bangkok health issue): Bangkok pharmacies provide oral rehydration salts (ORS), loperamide (anti-motility), and ciprofloxacin or azithromycin without prescription for traveler's diarrhea management; for bloody diarrhea or high fever: seek medical care; (5) Bangkok health insurance verification: verify health insurance covers international treatment before travel; most major travel insurance covers Bangkok private hospital treatment; Bumrungrad has direct billing with most major international insurers; if uninsured: Bangkok Hospital and Bumrungrad accept deposits for treatment without insurance at competitive rates for uninsured care.",
  },
];

export function BangkokInsect() {
  return (
    <div className="rounded-2xl border border-green-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-green-700 mb-3">
        🦟 Bangkok nature & health — edible insects culture, urban wildlife & tropical disease prevention
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-green-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-green-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
