const SPOTS = [
  {
    name: "Bangkok's Muslim Community & Islam in Thailand",
    emoji: "🕌",
    area: "Bangkok Muslim community areas: Banglamphu/Phra Nakhon (old Cham-Malay community); Haroon Mosque vicinity (Charoen Krung, Silom area, Bangkok's largest mosque); Bang Rak Yai market area; Pratunam/Ratchaprasong (Arab expat community and halal food); Sukhumvit Arab/Middle Eastern restaurants (Soi 3/Nana); South Bangkok: Thon Buri, Klong San (historical Malay fishing community)",
    price: "Haroon Mosque visit: free; Masjid Omar ibn Khattab visit: free; Halal food restaurant: ฿60–300/person; Arabic street food (Soi 3 Nana): ฿80–250; Malay desserts (kanom jeen, roti): ฿30–80; Muslim community tour (guided): ฿800–2,000; Arab cultural center events: typically free",
    why: "Thailand's Muslim minority (approximately 5–7% of the national population, with significant concentration in southern provinces) has a Bangkok presence centered on distinct historical communities and religious infrastructure: (1) Thailand's Muslim identity: Thai Muslims are predominantly Malay-Thai in the deep south (Pattani, Yala, Narathiwat, Satun) and ethnically Chinese-Thai or Cham in Bangkok; the Bangkok Muslim community is diverse in ethnic origin; (2) Haroon Mosque (Masjid Haroon): Bangkok's oldest and largest mosque, established in 1830; located on Charoen Krung Road near the Chao Phraya River in an area that has been a Muslim community since Bangkok's early history; the mosque's turquoise exterior and Arabic-influenced architecture are distinctly non-Thai in character; open to respectful non-Muslim visitors outside prayer times; (3) Phra Nakhon Cham-Malay community: descendants of the Cham people (originally from central Vietnam, pushed south and eventually to Thailand as Muslim refugees over several centuries) maintain a small community in the old Bangkok areas near Democracy Monument; (4) Arab expat community in Nana: Sukhumvit Soi 3 (Soi Nana) is Bangkok's Arab Quarter — Egyptian, Lebanese, Saudi, Jordanian, Emirati, and Pakistani communities concentrated in restaurants, shops, and services catering to Arab visitors and expats; the area is distinctly Middle Eastern in atmosphere with Arabic-language signage; (5) Halal food infrastructure: Bangkok's halal restaurant network extends well beyond Thai-Muslim cooking; Egyptian, Lebanese, Pakistani, Bangladeshi, and Pan-Arab cuisine is concentrated in Nana and Silom; Pratunam has additional halal restaurants serving Bangkok's significant Muslim market from neighboring countries.",
    tip: "Bangkok Muslim community visitor etiquette: (1) Mosque visiting protocol: when visiting Haroon Mosque or any Bangkok mosque as a non-Muslim visitor, dressing modestly (full body coverage, head covering for women; long trousers for men), removing shoes at the entrance, observing quietly without disrupting prayer, and asking permission before photographing are the respectful practices; (2) Prayer time awareness: mosques in Bangkok have active prayer schedules (5 daily prayers); visiting between prayer times (most accessible: mid-morning or mid-afternoon) avoids disrupting active prayer; the mosque will signal prayer starting with the adhan (call to prayer); (3) Soi 3 food quality: Bangkok's Arab restaurants on Soi 3 and surrounding streets range from very good to tourist-oriented; restaurants packed with Arab customers (a positive signal of authenticity) rather than tourists indicate quality; asking for the daily special rather than ordering from the tourist-optimized menu often yields better results; (4) Ramadan experience in Bangkok: during Ramadan, Bangkok's Muslim communities host iftar (fast-breaking) gatherings at mosques and community centers; large-scale iftar spreads open to the public are hosted at Haroon Mosque during Ramadan; the atmosphere is distinctly communal and welcoming; (5) Thai-Muslim food on halal signs: the green crescent-moon halal sign (อาหารฮาลาล or the Arab certification symbol) on Bangkok food establishments confirms halal-certified preparation; halal certification for Bangkok restaurants is issued by the Central Islamic Committee of Thailand (CICOT).",
  },
  {
    name: "Bangkok's Sikh Community & Gurdwara Sri Guru Singh Sabha",
    emoji: "🙏",
    area: "Bangkok Sikh community: Pahurad district (historically Indian trading community), Pahurat Market; Gurdwara Sri Guru Singh Sabha (Pahurat Road, Bang Rak) — Bangkok's main Sikh temple; Indian-Thai businesses concentrated in Pahurat and Silom; Indian restaurants: Pahurat (budget, local South Asian), Sukhumvit Soi 11 and 3 (premium)",
    price: "Gurdwara visit: free (langar/community kitchen food: offered free to all visitors); Pahurat Market textile shopping: ฿100–5,000+ depending on fabric/quantity; Indian restaurant (Pahurat, local): ฿80–200/person; Indian restaurant (Sukhumvit premium): ฿300–800/person; Punjabi sweets (Pahurat): ฿50–200; Sikh community tours: typically informal, ask the gurdwara management",
    why: "Bangkok's Sikh and Indian community has been present since the late 19th century, contributing to Bangkok's commercial development and creating a visible cultural enclave: (1) Gurdwara Sri Guru Singh Sabha: Bangkok's central Sikh temple (established early 20th century) on Pahurat Road serves Bangkok's Sikh community and is one of the most beautiful religious buildings in Bangkok; the gurdwara is open to visitors of all faiths and serves langar (community free kitchen) meals; (2) Pahurat Indian Market: adjacent to Chinatown's Yaowarat district, Pahurat (often called Bangkok's Little India) contains Bangkok's concentration of South Asian textile merchants, spice dealers, and South Asian food vendors; the 3–4 block concentration along Pahurat Road and connecting sois is the entry point to Bangkok's Indian commercial community; (3) Thai-Indian community identity: Bangkok's Indian community (predominantly Sikh Punjabi, Sindhi, and Tamil) arrived as merchants, soldiers, and traders during the British colonial period; the community has deep ties to Bangkok's textile, leather goods, and gem trade; (4) South Indian community: Tamil-speaking South Indian Hindus maintain a separate community and religious organization (Sri Maha Mariamman temple near Silom, also known as the Hindu temple — a brightly colored Tamil-style temple with large gopuram sculptures); the temple's Navarathri and other Hindu festivals are among Bangkok's most colorful religious celebrations; (5) Indian cuisine geography: Pahurat provides Bangkok's most affordable and authentic Northern Indian vegetarian and non-vegetarian food; Sukhumvit (particularly Soi 3, 5, and 11) has more expensive but comparable quality Indian restaurants serving larger portions of the upper-income Arab and Indian expat community.",
    tip: "Bangkok Indian community and gurdwara visiting: (1) Gurdwara dress requirement: all visitors (regardless of faith) must cover their heads before entering the Sikh temple; head coverings (squares of orange cloth or paper) are provided at the entrance; this requirement is not optional; (2) Langar dining experience: the gurdwara's community kitchen (langar) serves free vegetarian meals to all visitors; the experience of sitting on the floor in a community hall and eating together alongside Bangkok's Sikh community is a genuinely moving cross-cultural experience; donations (any amount) support the kitchen; (3) Pahurat textile quality check: Pahurat's textile merchants carry genuine South Asian fabrics (silk, cotton, synthetic blends) as well as lower-quality substitutes; merchants specializing in South Asian customers rather than tourist foot traffic are better quality indicators; (4) Sri Maha Mariamman Temple (Hindu temple) visiting: the South Indian Tamil-style temple near Silom is easily visited alongside a Silom exploration; modest dress (knees and shoulders covered) and shoe removal apply; the temple's interior is fragrant with incense and bright with deity sculptures; (5) Pahurat-Chinatown combined exploration: Pahurat and Yaowarat (Chinatown) are adjacent and can be combined into a half-day multicultural heritage walk; the transition from Indian textile traders to Chinese goldsmiths and food stalls within a 500m walk represents Bangkok's extraordinary ethnic compression.",
  },
  {
    name: "Bangkok's Diverse Religious Landscape — Temples, Churches & Shrines",
    emoji: "⛪",
    area: "Bangkok religious diversity: Buddhist: over 400 temples throughout Bangkok; Christian: Saint Louis Cathedral (Sathorn), Holy Redeemer Church (Ruamrudee), Christian churches from multiple denominations; Jewish: Beth Elisheva Synagogue (Sukhumvit, active congregation); Hindu: Sri Maha Mariamman (Silom), Ganesha shrines throughout city; Animist shrines: spirit houses and pillar shrines at virtually every property",
    price: "Bangkok temple visits: free–฿100 entry; Church services: free; Beth Elisheva Synagogue (shabbat services): contact for current schedule; Erawan Shrine (Brahma shrine): offering materials ฿30–200; Spirit house offerings: ฿20–100; Multi-faith guided religious tour: ฿1,500–3,500; Christmas events at international hotels: free–฿5,000",
    why: "Bangkok's religious landscape is one of the world's most diverse within a dominant Buddhist framework: (1) Thai Buddhism's unique character: Theravada Buddhism in Thailand syncretizes with animist spirit beliefs (phi spirits, spirit houses, sacred trees), Hindu cosmology (Brahma, Vishnu, Indra are incorporated into Thai Buddhist iconography), and Brahmanical court ritual (the royal court maintains Brahmin priests for official ceremonies); this Thai Buddhist syncretism creates a religious landscape that differs significantly from Burmese or Sri Lankan Theravada; (2) Christian community in Bangkok: Bangkok's Christian community is multi-denominational; the Catholic community has Bangkok roots dating to the 17th century Portuguese mission; Saint Louis Cathedral (Sathorn, opened 1897) and the Portuguese-founded Holy Rosary Church (Wat Kalawa, 1891) represent the oldest continuous Christian community; Protestant denominations arrived with British and American missionaries; there are approximately 100 Christian churches in Bangkok; (3) Bangkok's Jewish community: a small but continuous Jewish community (primarily connected to business activities) has maintained a synagogue in Bangkok since the early 20th century; Beth Elisheva Synagogue in the Sukhumvit area serves approximately 200 members and hosts weekly Shabbat services; (4) Brahma shrines (san phra phrom): the Grand Hyatt Erawan shrine on Ratchaprasong is Bangkok's most famous Brahma (4-faced Brahma, Phra Phrom) shrine and one of Southeast Asia's most visited sacred sites; Thais believe the shrine grants wishes; it attracts hundreds of devotees daily across all social classes; (5) Spirit houses (san phra phum): Thailand's animist spirit house tradition requires every building (home, business, hotel) to maintain a miniature spirit house for the land spirit; these spirit houses (elaborately maintained with incense, food offerings, and floral garlands) are Bangkok's most visible expression of pre-Buddhist animist religion persisting within a nominally Buddhist society.",
    tip: "Bangkok multi-faith religious exploration: (1) Temple etiquette across all faiths: the common thread in Bangkok's diverse religious sites is physical respect — modest clothing, quiet behavior, permission before photographing sacred items or people, and following any posted instructions; these norms apply across Buddhist temples, mosques, churches, and Hindu temples; (2) Erawan Shrine observation: the Erawan Shrine's continuous stream of offerings and dancers (classical Thai dancers are hired to perform as thanks for answered prayers) provides a live observation of Thai merit-making and vow fulfillment; the atmosphere is intensely devotional rather than tourist-entertainment; (3) Temple photography ethics: photographing Buddhists during prayer or meditation in temples without their knowledge is intrusive; photographing Buddha statues is generally acceptable; photographing monks requires their consent and should not interrupt their practice; (4) Spirit house meaning: Thailand's spirit house tradition treats land spirits (phi) as real entities requiring appeasement; the ornate maintenance of spirit houses at Bangkok hotels and businesses reflects genuine religious belief, not decoration; disrespecting spirit houses (leaning on, touching, or mocking offerings) is considered genuinely offensive; (5) Bangkok's interfaith coexistence: Bangkok's management of religious diversity — with Buddhist temples, mosques, Hindu shrines, and Christian churches in close proximity — represents Thailand's historical pragmatism about religious identity; Thai national identity prioritizes ethnic-cultural Buddhism while permitting other religious practice within clear bounds.",
  },
];

export function BangkokMuslimCulture() {
  return (
    <div className="rounded-2xl border border-green-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-green-700 mb-3">
        🕌 Bangkok multicultural religion — Muslim community, Sikh temple, Christian churches & diverse shrines
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-green-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-green-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
