const SPOTS = [
  {
    name: "Khao San Road — Bangkok's Backpacker District Complete Guide",
    emoji: "🎒",
    area: "Khao San Road: Phra Nakhon District; nearest BTS: none directly (nearest is Saphan Taksin, then river boat to Phra Arthit/Banglamphu pier N13, approximately ฿50 Chao Phraya Express Boat + 5 min walk); taxi from Siam area: approximately 20–30 min; Khao San Road proper is 400m; adjacent: Rambuttri Road (parallel, quieter version of Khao San), Samsen Road (local Bangkok neighborhood behind), Wat Chana Songkhram (temple at north end); Khao San area hostels: multiple branded and independent hostels ฿200–500/dorm, ฿600–1,500/private",
    price: "Hostel dorm: ฿200–500/night; Private room (budget): ฿600–1,500; Pad thai on Khao San: ฿80–150 (above average Bangkok pricing); Mango sticky rice: ฿60–100; Bucket cocktail (Sangsom rum + mixer + energy drink): ฿150–250; Beer (bottle, Singha/Leo): ฿80–150; Thai massage on Khao San street: ฿150–250/hour; Suit tailor estimate (tourist area price): ฿3,000–8,000 (significantly above quality Sukhumvit tailors); Bus/transport information to other Thai cities: from Khao San travel agencies",
    why: "Khao San Road is both a cliché and a genuine cultural phenomenon worth understanding: (1) Global backpacker culture origin: Khao San Road became the prototype for global backpacker districts after Alex Garland's 1996 novel 'The Beach' (and the 2000 Leonardo DiCaprio film) described it as the starting point for Southeast Asian backpacker travel; the self-referential backpacker economy that Garland critiqued became more concentrated after the novel made it famous; (2) What Khao San actually is: a 400m street that has been continuously optimized for budget traveler consumption since the 1980s; clothing stalls, travel agencies, tattoo parlors, hair braiding, bar strips, hostels, exchange booths, food carts (slightly overpriced vs. Bangkok average), and nightlife are compressed into walking distance; (3) Rambuttri Road parallel: Rambuttri Road (one block north, parallel to Khao San) has the same infrastructure with slightly more Thai regular clientele and slightly less concentrated tourist saturation; the café culture on Rambuttri is more relaxed; (4) Location advantage: Khao San's location (walking distance from the Grand Palace, Wat Pho, Wat Phra Kaew, Wat Saket) makes it still one of Bangkok's best-located budget accommodation areas for heritage-focused sightseeing; (5) Evolution post-COVID: the post-COVID Khao San Road has gentrified somewhat; higher-quality hostels, better restaurant options (beyond the tourist Thai food trap), and some craft cocktail bars have emerged alongside the unchanged bucket cocktail bars and braided hair stalls.",
    tip: "Khao San Road visitor strategy: (1) Grand Palace proximity advantage: Khao San Road accommodation is 1.5km from the Grand Palace and Wat Pho; for visitors planning intensive Old Bangkok sightseeing, this proximity justifies the location even if the accommodation is less stylish than Sukhumvit alternatives; (2) Avoid eating scams: restaurants on Khao San Road proper are priced 30–50% above equivalent Bangkok street food for the same or lower quality; the exceptions are food carts and vendors on Khao San's side streets (not the sit-down restaurants); Phra Athit Road (200m north, along the river) has Thai restaurants frequented by Thammasat University students with better food and prices; (3) Night market change: Khao San's nightlife has shifted over the years; the 4am closing time that historically allowed Bangkok's latest drinking was periodically enforced at earlier hours; current operating hours for Khao San bars are subject to periodic crackdown; checking current situation via Khao San-specific Facebook groups provides up-to-date information; (4) Day vs. night timing: Khao San in the day (before 6pm) functions as a practical service hub (travel agencies, currency exchange, gear shopping, cheap Thai food); at night it becomes a concentrated bar strip; the dual function is worth understanding to use Khao San appropriately for your needs; (5) Banglamphu alternative accommodations: the broader Banglamphu neighborhood (the area surrounding Khao San, including Samsen Road and the canal-side areas) has budget accommodation that is walking distance from Khao San without being on the street itself; these locations offer quieter accommodation while maintaining the location advantage.",
  },
  {
    name: "Bangkok Budget Hostels & Guesthouses — Best Areas for Budget Travelers",
    emoji: "🏠",
    area: "Bangkok budget accommodation areas: Banglamphu/Khao San Road (budget classic, Old City access); Sukhumvit On Nut (BTS accessible, authentic Thai neighborhood, lower prices); Pratunam/Phaya Thai (central shopping access, Victory Monument BTS area); Chinatown/Yaowarat Road (character-filled, good food access, less BTS-convenient); Ari/Saphan Khwai (local residential, reasonable prices, BTS Skytrain access); Silom/Sathon budget options; airport hotel areas (Don Mueang and Suvarnabhumi area budget hotels); hostel types: dorm hostels (social, backpacker); budget guesthouses (Thai family-operated); budget apartments (monthly, great value for stays 2+ weeks)",
    price: "Dorm bed (mixed): ฿200–500; Dorm bed (female-only): ฿250–600; Private room (budget hostel): ฿600–1,500; Budget guesthouse (fan room): ฿400–800; Budget guesthouse (AC private): ฿700–1,500; On Nut BTS area studio (monthly): ฿7,000–12,000; Chinatown guesthouse: ฿500–1,200; Airbnb Bangkok (private room): ฿600–2,000; Budget apartment (monthly, Pratunam): ฿8,000–15,000; Victory Monument area guesthouse: ฿500–1,200",
    why: "Bangkok's budget accommodation market ranges from party hostels to character guesthouses, with significant neighborhood variation: (1) On Nut BTS on value equation: the Sukhumvit On Nut area (BTS On Nut, approximately 30 minutes from Siam on BTS) has Bangkok's best combination of BTS access and below-average accommodation prices; On Nut is a genuine Thai neighborhood with local markets, authentic restaurants, and convenience stores; the accommodation cost is 30–50% lower than equivalent BTS-adjacent rooms in Thong Lo or Ekkamai; (2) Chinatown guest house character: Bangkok's Chinatown (Yaowarat Road, Sampeng Lane area) has small guesthouses and Chinese-style hotels that are among Bangkok's most characterful budget accommodation; the tradeoff is MRT access (not BTS) and lower Airbnb availability; the reward is immersive Old Bangkok atmosphere; (3) Pratunam area value: the Pratunam area (central Bangkok, near shopping malls including Platinum Fashion Mall and Baiyoke Tower area) has dense budget and mid-budget accommodation with good transport access via Phaya Thai Airport Rail Link station (15 minutes to Suvarnabhumi Airport) and multiple bus routes; (4) Hostel social function: Bangkok's purpose-built social hostels (Bodega Bangkok Sukhumvit, various brands near BTS stations) function as social spaces for solo travelers and digital nomads; rooftop bars, organized social events, city tour meetups, and co-working spaces are common hostel amenities at the better Bangkok hostels; (5) Monthly apartment vs. short-term accommodation cost comparison: staying in Bangkok for 1+ months makes direct apartment rental (through Facebook groups, local agents, DD Property) significantly cheaper than hostel accumulation; a 1BR Bangkok apartment near BTS for ฿10,000–15,000/month works out to ฿333–500/night — competitive with budget hostel private rooms.",
    tip: "Bangkok budget accommodation planning: (1) Booking.com vs. walking up: Bangkok's smaller guesthouses (particularly in Banglamphu and Chinatown) often have better walk-up rates than online booking platform prices; the platform takes 15–20% commission which guesthouses sometimes pass to guests as premium; checking both online and calling direct is worthwhile for stays longer than 3 nights; (2) Fan vs. AC room decision: Bangkok's heat (typically 30–35°C year-round) makes fan rooms genuinely challenging for most Western visitors; the ฿200–500 price difference between fan and AC rooms in budget guesthouses is worth it for sleep quality and health; (3) Airport proximity accommodation: staying 1 night near Suvarnabhumi or Don Mueang airport (particularly for early morning or late night flights) is more practical and often cheaper than heading into central Bangkok; airport hotel areas have cheap transport options to the airport and good food options; (4) Female-only dorm availability: many Bangkok hostels offer female-only dormitory rooms; booking female-only dorms significantly reduces the common concern about sharing dorms with male strangers; specifying this preference in booking searches is straightforward on major platforms; (5) Check-in flexibility: Bangkok's budget guesthouses typically have check-in from 2pm; arriving early (11am–1pm) often results in room availability if the room is clean, but is not guaranteed; communicating early arrival to the property via LINE or booking platform message before arrival is the most effective approach.",
  },
  {
    name: "Bangkok's Digital Nomad Scene — Co-working, Cafés & Remote Work Community",
    emoji: "💻",
    area: "Co-working spaces: WeWork Bangkok (multiple locations, Sathorn, Asok, Ratchaphruek); HUBBA-TO (Thong Lo, lifestyle-focused); Draper Startup House (Silom, startup-oriented); True Digital Park (Punnawithi area, largest tech campus in Southeast Asia, 30,000+ sqm); The Hive Bangkok (Thong Lo, Ekkamai); KX (Knowledge Exchange, Bang Khen, government-linked); café working: Roast Coffee (T-One Building), Crimson Cup (Ekkamai), Brave Roasters (multiple), Roots Coffee (multiple); internet quality: True Move H / AIS fiber at cafés and co-working is generally excellent (100–500 Mbps); tourist SIM internet: AIS/True Tourist SIM ฿299–399 for 15–30 days unlimited data",
    price: "Co-working (daily): ฿300–700; Co-working (monthly, hot desk): ฿3,000–6,000; Co-working (monthly, dedicated desk): ฿6,000–12,000; WeWork Bangkok (monthly membership): ฿8,000–15,000; Café work (coffee purchase usually sufficient): ฿80–200; True Digital Park (free public area access, ฿350–1,000 for specific co-working zones); Internet: AIS Tourist SIM (15 days unlimited): ฿299; Home fiber internet (monthly): ฿690–1,200",
    why: "Bangkok has emerged as Southeast Asia's second-largest digital nomad hub after Chiang Mai (Nimman) by some metrics: (1) Infrastructure quality: Bangkok's internet infrastructure is genuine city-wide fiber and fast mobile data; AIS and True Move H provide reliable 4G/5G coverage throughout Bangkok and most of Thailand; co-working spaces and cafés in Bangkok consistently have 50–500+ Mbps connections; power cuts (a concern in some Southeast Asian cities) are rare in central Bangkok; (2) True Digital Park significance: True Digital Park (operated by True Corporation, Thailand's second-largest telecom) is Southeast Asia's largest technology and startup campus; the facility (in Bang Na area, Punnawithi BTS) hosts 2,000+ startups and established tech companies, provides co-working to freelancers and nomads, and has its own food hall, hotel, and event spaces; visiting TDP provides insight into Thailand's tech startup ecosystem; (3) Bangkok vs. Chiang Mai for digital nomads: Chiang Mai (northern capital) is Thailand's most established digital nomad scene with lower cost of living; Bangkok offers better international connectivity (air hub), more diverse social and cultural options, significantly more international food, but higher costs (accommodation 30–50% higher than Chiang Mai equivalent); (4) Bangkok nomad community density: the Bangkok digital nomad community (estimated 5,000–15,000 active at any time) concentrates in specific neighborhoods; Ekkamai, Thong Lo, Ari, Phrom Phong, and Silom host the densest nomad-friendly café and co-working density; co-working communities in these areas have regular social events; (5) Nomad visa considerations: Thailand introduced the Long-Term Resident Visa (LTR) for remote workers earning minimum US$80,000/year; the LTR Work-From-Thailand permit provides legal status for high-earning remote workers; lower-earning digital nomads typically operate on tourist visa exempt stays (30 days) with visa run renewals, which is technically correct for short stays but grey area for long-term residence.",
    tip: "Bangkok digital nomad practical guidance: (1) AIS vs. True Move H SIM: both AIS and True Move H tourist SIMs provide reliable Bangkok coverage; AIS has a slight edge in provincial Thailand coverage; True Move H is often marginally cheaper for tourist SIMs; either works well in Bangkok; (2) Café work etiquette in Bangkok: Bangkok café culture is nomad-friendly (laptop use is standard at most cafés); purchasing one drink every 2–3 hours is the informal expectation at quality cafés during busy periods; cafés in malls near BTS stations have more power outlets than standalone venues; (3) DTAC/NT (now merged with True): the DTAC network merged with True Move H; existing DTAC SIMs continue to work but new SIM purchases are now True Move H; the merged network has good coverage; (4) Timezone advantage: Bangkok's GMT+7 timezone provides advantageous work hours for nomads with European clients (Bangkok morning = European afternoon/evening); for US-focused nomads, Bangkok requires evening work sessions to cover US daytime; (5) Tax residency for long-stay nomads: Thailand considers residents staying 180+ days per calendar year as tax residents; Thailand's Revenue Department has strengthened enforcement of the foreign income tax rule (income brought into Thailand in the same tax year is taxable); nomads staying more than 180 days should research current Thailand tax guidelines through professional advice.",
  },
];

export function BangkokKhaoSanRoad() {
  return (
    <div className="rounded-2xl border border-yellow-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-yellow-700 mb-3">
        🎒 Bangkok budget travel — Khao San Road, hostels & digital nomad co-working scene
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-yellow-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-yellow-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-yellow-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
