const SPOTS = [
  {
    name: "Bangkok's Pakistani & South Asian Muslim Dining Scene",
    emoji: "🍛",
    area: "Pakistani restaurants Bangkok: concentrated near Sukhumvit Soi 3/1 (Arab/Muslim quarter); Nana area restaurants; Silom 'Arab Street' cluster; Sukhumvit Soi 22 area; Pakistani halal butcher shops: Nana area; Pakistani community mosque: Haroon Mosque (Charoen Krung), Assadaqah Mosque (Silom area); Pakistani cultural events: organized through embassies and community organizations; note: many restaurants serve combined Pakistani/Indian/Bangladeshi cuisine as 'South Asian'",
    price: "Biryani (full portion): ฿120–250; Karahi (chicken/lamb, for 2): ฿250–450; Seekh kebab platter: ฿180–350; Naan bread: ฿20–50; Pakistani chai: ฿40–80; Full Pakistani meal (per person): ฿200–500; Fine dining Pakistani (rare in Bangkok): ฿800–2,000; Halal butcher imported Pakistani/Australian lamb: ฿300–800/kg",
    why: "Bangkok has a small but authentic Pakistani community with restaurants serving distinctive Pakistani culinary traditions: (1) Pakistani vs. Indian food distinctions: Pakistani cuisine and Indian cuisine share many elements but differ significantly in cooking styles and regional specialties; Pakistani cuisine emphasizes meat-based dishes (beef and lamb are central, pork is completely absent), uses fewer lentil-based dishes than Indian cuisine, has stronger Central Asian influences (karahi cooking technique, seekh kebab tradition, slow-cooked nihari), and uses wheat bread (roti, naan) as the primary starch over rice; (2) Karahi as distinctive Pakistani dish: the karahi (kadai) — a cast-iron wok-like vessel — is central to Pakistani cooking; chicken karahi (murgh karahi) and lamb karahi are prepared by cooking the protein with tomatoes, ginger, and whole spices in the karahi at high heat; the Bangkok Pakistani restaurant version is authentic to this cooking method; (3) Pakistani biryani differences: Pakistani-style biryani (particularly Sindhi biryani with potatoes and spicy gravy layering) differs from South Indian biryani style; the meat-heavy, spice-forward Pakistani biryani is available at Nana area restaurants; (4) Halal certification importance: Bangkok's Pakistani restaurants operate under halal principles; all meat is halal-certified; alcohol is not served; this halal reliability makes these restaurants the preferred choice for Bangkok's Muslim community (not just Pakistanis — also Arab, Bangladeshi, Malaysian, and Thai Muslim diners); (5) Nihari and breakfast culture: nihari (slow-cooked beef or lamb shank stew, traditionally eaten for breakfast in Pakistan) is available at some Bangkok Pakistani restaurants; this long-cooking dish (typically 6–8 hours) represents the depth of Pakistani culinary tradition that extends beyond typical restaurant menus.",
    tip: "Bangkok South Asian halal dining guidance: (1) Nana area Muslim restaurant cluster: the Sukhumvit Soi 3/3/1 (Nana) area has Bangkok's highest concentration of Pakistani/South Asian/Arab restaurants; walking this area (between Nana BTS and the surrounding sois) reveals multiple options; (2) Time of visit for freshest food: most Bangkok Pakistani restaurants prepare food in large batches; visiting at lunchtime (11am–2pm) when the freshest preparation is available rather than late evening when food has been sitting is the recommended approach; (3) Lamb vs. chicken pricing: genuine lamb (not goat, which is commonly substituted in low-cost South Asian restaurants) costs more in Bangkok; asking specifically for 'lamb' and the pricing difference confirms whether the restaurant is using proper lamb vs. goat; both are legitimate ingredients but differ in flavor; (4) Pakistani sweets: gulab jamun (fried milk-solid balls in rose syrup), jalebi (fermented wheat batter fried in rings then soaked in syrup), and kheer (rice pudding) are traditional Pakistani desserts sometimes available at Bangkok Pakistani restaurants; ordering in advance or asking about daily availability; (5) Ramadan eating context: during Ramadan (the annual Islamic fasting month), Bangkok's Muslim restaurant culture shifts significantly; iftar (break-fast) meals at sundown create a celebratory dining atmosphere in the Nana and Silom Muslim quarter; joining iftar at a Bangkok mosque is open to non-Muslims through appropriate invitation or permission.",
  },
  {
    name: "Bangkok's Bangladeshi Community & Cuisine",
    emoji: "🐟",
    area: "Bangladeshi community in Bangkok: concentrated near Nana (Sukhumvit), Pratunam (wholesale market area, Bangladeshi garment buyers), Asok area; Bangladeshi restaurants: small number, overlapping with South Asian Muslim restaurant cluster; Bangladeshi community events: through embassy and community organizations; Embassy of Bangladesh: Sukhumvit Soi 31; Bangladeshi community primarily engaged in: garment trade, construction, restaurant service; significant Bangladeshi Muslim population; Thai-Bangladesh cultural exchanges: fashion trade through Pratunam wholesale market",
    price: "Bangladeshi hilsa fish curry (where available): ฿250–500 (imported hilsa is premium); Rice-based dishes: ฿80–180; Ilish bharta (mashed hilsa): ฿150–300 (seasonal/availability); Dal and vegetable dishes: ฿60–120; Full Bangladeshi meal: ฿200–450; Bangladeshi sweet shops: pithas (rice cakes) ฿30–80 each; Mishti doi (sweet yogurt): ฿40–80",
    why: "Bangkok's Bangladeshi community maintains cultural and culinary traditions in a small but cohesive community: (1) Bangladeshi culinary tradition: Bangladesh's cuisine has distinctive features within South Asian cooking; mustard oil is a fundamental cooking medium (giving a distinctive pungent flavor); fish (freshwater fish particularly) is central to Bangladeshi cuisine in contrast to Pakistan's meat emphasis; hilsa fish (ilish) — Bangladesh's national fish and a prized oily river fish — is a defining ingredient; (2) Hilsa fish significance: ilish (Tenualosa ilisha) holds deep cultural meaning in Bangladeshi culture; it is simultaneously a premium food ingredient, a cultural symbol, and a seasonal delicacy (hilsa migrates upstream during monsoon season); authentic Bangladeshi restaurants in Bangkok may import frozen hilsa from Bangladesh; (3) Pitha (rice cake) tradition: Bangladeshi cuisine includes an elaborate tradition of pitha — steamed, fried, or boiled rice cakes filled with coconut, molasses, or dal; these are particularly associated with winter festivals (Poush Mela) and are rarely found in restaurants but may be available at community gatherings; (4) Bangladesh-Thailand trade connection: Bangkok's Pratunam wholesale garment market has significant Bangladeshi buyer presence; Bangladesh is one of the world's largest garment exporters, and Bangladeshi trade buyers regularly visit Bangkok's wholesale markets; this commercial connection sustains some Bangladesh-oriented services near Pratunam; (5) Bengali language community: the Bengali language community in Bangkok (Bangladeshis and West Bengali Indians) maintains cultural connection through events and media; the Embassy of Bangladesh in Bangkok facilitates cultural events including Bengali New Year (Pohela Boishakh, April 14) celebrations.",
    tip: "Finding Bangladeshi food and community in Bangkok: (1) Restaurant identification: distinctly Bangladeshi restaurants are rare in Bangkok; most Bangladeshi community members eat at the broader South Asian Muslim restaurant cluster in the Nana area or cook at home; (2) Community gatherings as food access: the Bangladeshi community in Bangkok organizes gatherings during major festivals (Eid ul-Fitr, Eid ul-Adha, Bengali New Year); these community events are where authentic home-style Bangladeshi cooking (particularly pithas and hilsa preparation) is available; connecting through the Embassy of Bangladesh or Bangladeshi business associations provides invitation access; (3) Mustard oil in Bangkok: mustard oil (essential for authentic Bangladeshi cooking) is available at Bangkok's South Asian grocery shops (Nana area, Phaya Thai area); Indian grocery stores also carry mustard oil; (4) Fish-forward alternatives: Thai cuisine's abundant fresh water fish dishes (pla chon, pla duk) have some culinary parallel to Bangladeshi freshwater fish traditions; Thai freshwater fish preparations can partially satisfy a Bangladeshi fish cuisine craving between authentic meals; (5) Language barrier considerations: Bangladeshi community members in Bangkok who work in service roles are generally proficient in Thai and often English; in the Pratunam area, basic communication is possible in Hindi/Bengali with some of the South Asian merchant community as well.",
  },
  {
    name: "Bangkok's Afghan & Central Asian Dining — A Niche Culinary Find",
    emoji: "🥙",
    area: "Afghan restaurants Bangkok: very limited; occasional pop-ups through community gatherings; Central Asian influence cuisine: available through general Middle Eastern restaurants (Afghan, Uzbek elements); Afghan community: small expat group, presence in NGO and humanitarian worker communities; Central Asian food adjacent: some Pakistani restaurants serve kabuli pulao (Afghan-influenced rice dish); UN/humanitarian worker areas: Silom and Sukhumvit carry small populations of Central Asian workers; Afghan food cultural heritage: UNESCO-recognized buzkashi sport; pulao, mantu, bolani traditional dishes",
    price: "Afghan restaurant meals (Bangkok, if available): ฿200–500; Kabuli pulao (through Pakistani restaurants): ฿150–300; Mantu dumplings (where available): ฿150–300; Central Asian rice dishes: ฿150–350; Afghan-influenced bread (naan variations): ฿20–60; Samanak (wheat dessert, seasonal/community): typically not commercially available; Long Grain rice (for kabuli pulao home cooking): ฿80–200/kg",
    why: "Afghan and Central Asian cuisine represents one of Bangkok's most difficult-to-find culinary experiences: (1) Afghan food philosophy: Afghan cuisine sits at the intersection of Persian, Indian, Central Asian, and Middle Eastern culinary traditions; it is characterized by long-cooked meat dishes, fragrant rice preparations (pulao family), bread culture (naan, bolani flatbread), and dried fruit and nut usage in both savory and sweet preparations; (2) Kabuli Pulao's significance: the dish considered Afghanistan's national dish, kabuli pulao (rice cooked with lamb, topped with braised carrots, raisins, and pistachios), represents the Persian rice cooking tradition at its most refined; some Bangkok Pakistani restaurants serve versions of this dish; (3) Mantu dumplings: mantu (Afghan steamed dumplings with spiced beef/lamb, served with yogurt-based sauce and split pea sauce) connect Afghan cuisine to the broader Central Asian and Silk Road dumpling tradition (shared with Chinese jiaozi, Turkish manti, Mongolian buuz); this connection makes mantu interesting from a food history perspective; (4) Central Asian UN worker community: Bangkok's role as a regional headquarters for multiple UN agencies (UNESCAP, UNHCR, WHO Regional Office) means the city has a small but consistent Central Asian and Afghan professional community (humanitarian workers, development professionals, refugees with NGO connections); this community sustains informal Central Asian food preparation through home cooking and occasional community gatherings; (5) Afghan tea culture: the Afghan tea tradition (qymaq chai — creamy salt tea prepared with milk, spices, and oil, with pink color from baking soda) represents a distinctive culinary tradition rarely available in Bangkok but occasionally prepared within the Afghan community.",
    tip: "Finding Central Asian food experiences in Bangkok: (1) Community connection is the access route: unlike major world cities with established Afghan restaurant districts, Bangkok's Central Asian food access is primarily through community connection rather than commercial restaurants; connecting through expat networks that include humanitarian workers opens access to community gatherings; (2) Pakistani restaurant approximations: Bangkok's better Pakistani restaurants (particularly those catering to Karachi/Lahore style cooking) serve dishes with clear Afghan culinary influence (kabuli pulao variants, seekh kebab, qorma preparations) that approximate the broader Pashtun/Central Asian culinary tradition; (3) Home cooking ingredients in Bangkok: Bangkok's South Asian grocery stores (Nana area, Little India around Phaya Thai) carry key Central Asian cooking ingredients (dried apricots, barberries, whole spices including dried whole cumin and coriander, long grain rice varieties); the ingredients for kabuli pulao are available for home cooking; (4) Middle Eastern restaurant overlap: Bangkok's Middle Eastern restaurants (particularly Lebanese and Persian restaurants in the Sukhumvit area) cover parts of the Central Asian culinary spectrum; Lebanese meze, Persian rice dishes, and similar preparations provide partial overlap with the broader Middle East/Central Asia culinary family; (5) Thai-Afghan culinary parallels: some surprising parallels exist between Thai and Afghan cuisines: both use fresh herbs generously, both have elaborate rice traditions, and both value the combination of sweet and savory elements in the same dish; pointing these out to Thai hosts when discussing food backgrounds creates interesting cross-cultural culinary conversations.",
  },
];

export function BangkokPakistaniFood() {
  return (
    <div className="rounded-2xl border border-orange-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-orange-700 mb-3">
        🍛 Bangkok South Asian Muslim cuisine — Pakistani, Bangladeshi & Central Asian dining
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-orange-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-orange-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-orange-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
