const SPOTS = [
  {
    name: "Hiking Near Bangkok — Accessible Trails Within 3 Hours",
    emoji: "🥾",
    area: "Hiking near Bangkok: Khao Yai National Park (200km, 3h, wild elephant trails); Erawan National Park (Kanchanaburi, 200km, 3h); Khao Khitchakut National Park (Chanthaburi, 250km, 4h); Sai Yok National Park (Kanchanaburi, 190km, 3h); Bangkok urban running/walking: Lumphini Park, Benchakitti Park, Suan Rot Fai (Chatuchak area), Bueng Kum area; semi-rural: Bang Krachao (cycling+walking circuits, 30 min from central Bangkok)",
    price: "National park day hike: ฿300–400 entry (foreigner); Trail guide: ฿500–1,500/day; Khao Yai overnight guided package: ฿3,000–7,000; Lumphini Park walk: free; Bang Krachao bicycle rental: ฿60–150/hour; Multi-day trek accommodation: ฿500–3,000/night; Public transport to trailhead (Erawan from Kanchanaburi): ฿50–80",
    why: "Bangkok's flat, dense urban geography means significant hiking requires escaping to nearby national parks, but accessible trails exist within a day trip: (1) Khao Yai trail network: Khao Yai National Park's marked trail system includes multiple routes from easy (Nong Phak Chi Watchtower trail, 1.5km, flat) to challenging (Khao Yai summit trail, multi-day); wildlife encounter probability on trails is Khao Yai's primary draw over other Bangkok-vicinity hiking; overnight trekking (with park-approved guide) accesses deeper forest and higher wildlife density zones; (2) Erawan Waterfall trails: the main trail system at Erawan National Park follows the seven-tiered waterfall system (approximately 2km one-way to the seventh tier); the trail is well-maintained but steep in sections; the combination of swimming in pools at each tier with trail hiking makes Erawan unique among Bangkok day hike options; (3) Khao Sam Roi Yot (Hua Hin): the limestone karst hills of Khao Sam Roi Yot National Park (200km south of Bangkok near Hua Hin) provide trail hiking through dramatic limestone formations and wetland bird watching; the Phraya Nakhon Cave trail (3km return, 30–40 min) is the most popular but multiple longer trails access higher viewpoints; (4) Bang Krachao urban nature walk: the Bang Krachao green lung (Bangkok inner ring, across the Chao Phraya from Klong Toey) has 15+km of unpaved cycling paths through orchid farms, community gardens, and mangrove-edge environments; cycling these paths (bicycle available for hire at island entry) provides Bangkok's most accessible nature experience without leaving city limits; (5) Lumphini Park running: Bangkok's central urban park (Lumphini, Silom area) has a 2.5km perimeter running path; the park is Bangkok's most used outdoor exercise space; morning (5am–8am) and evening (5pm–7:30pm) create high-energy outdoor fitness atmospheres with hundreds of simultaneous runners, aerobics groups, and Tai Chi practitioners.",
    tip: "Bangkok hiking trip planning: (1) Early departure essential: Bangkok traffic on weekend mornings makes early departure from the city (before 6am) significantly reduce total journey time to trailheads; leaving Khao Yai National Park before 3pm avoids the Sunday evening return traffic; (2) Guide requirement for deep forest: Khao Yai and Erawan require park-approved guides for overnight trekking and some longer trails; solo trekking deeper than day-accessible trails is prohibited both for safety (wild elephant encounters require experienced response) and conservation (trail braiding from untrained hikers damages sensitive forest); (3) Footwear selection: trail hiking in Thai national parks during wet season (June–October) requires waterproof boots or shoes with significant traction; the combination of clay soil, limestone, and rain creates extremely slippery conditions on otherwise accessible trails; sandals and smooth-soled sneakers cause falls; (4) Hydration at Thai national parks: all Thai national parks sell bottled water at the entrance area and at major visitor facilities; carrying 2+ liters for day hikes is recommended; the tropical heat (typically 28–35°C) creates significant sweat volume even on shaded forest trails; (5) Bug protection: national park hiking in Thailand requires insect protection; DEET-based repellent (available at Bangkok pharmacies including Boots, ฿100–200) is effective; long sleeves and trousers are preferable to shorts on vegetated trails for both tick protection and sun protection at higher elevations.",
  },
  {
    name: "Bangkok Running Culture — Races, Clubs & Urban Running Routes",
    emoji: "🏃",
    area: "Bangkok running clubs: BKK Runners (weekly group runs, Facebook); Midnight Runners Bangkok (social running, BTS-adjacent routes); Bangkok Hash House Harriers (BHH3, weekly social run-hike, rotating venues); Running events: Bangkok Marathon (November); Color Run Bangkok; various 5K fun runs at parks and malls; major routes: Lumphini Park (2.5km loop), Benchakitti Park (1.8km loop), Suan Rot Fai (Jatujak area, 1.5km circuit), Chao Phraya river walkway, King Rama IX Park (Prawet, outer Bangkok)",
    price: "Running clubs: free (BKK Runners, Midnight Runners) to ฿150–300 membership (Hash House Harriers); Bangkok Marathon entry: ฿800–2,500 depending on distance (5K, 10K, half, full); Fun run events: ฿300–800; Lumphini Park: free; Running shoe shops (Bangkok): Supersports, RunIn (Emporium), Adidas flagship; race entry via running.in.th or event Facebook pages",
    why: "Bangkok has a surprisingly active running community despite the heat and traffic challenges: (1) Hash House Harriers Bangkok: the Bangkok chapter of the worldwide running social club (BHH3) has operated weekly for decades; the Hash combines a trail-laying run (on-on route marked with flour or chalk) in rotating Bangkok neighborhoods with post-run social gathering; the social format makes it ideal for newcomers meeting Bangkok's international community; (2) Bangkok Marathon: the annual Bangkok Marathon (typically November, when Bangkok weather is coolest) covers the Chao Phraya riverside route and passes some of Bangkok's most iconic landmarks (Saphan Taksin, Charoen Krung); considered one of Asia's more scenic city marathons; (3) Early morning running culture: Bangkok's intense heat makes running before 7am and after 6pm the practical window; the pre-dawn Lumphini Park atmosphere (5–6:30am) is distinctive — hundreds of regular runners in darkness on a lit path; (4) Night running safety: Bangkok's lit park running areas (Lumphini, Benchakitti, Suan Rot Fai) are safe at night; road running in Bangkok traffic is not recommended; (5) Running apps and routes: Strava's Bangkok segment database shows popular running routes; the Chao Phraya River walkway sections (particularly the renovated Maharaj Pier to Sanam Luang section) provide pleasant waterfront running away from traffic.",
    tip: "Bangkok running practical guidance: (1) Heat management: Bangkok's heat and humidity (typically 32–36°C, 80%+ humidity) make running pace 20–30% slower than equivalent effort in cooler climates; reducing pace expectations and prioritizing hydration prevents heat exhaustion; (2) Best months for running: November–February are Bangkok's running months; temperatures drop to 25–30°C and humidity decreases moderately; organizing races and park challenges in this window is standard; (3) Lumphini Park rules: running direction on Lumphini Park tracks is counterclockwise in the morning and clockwise in the evening (switching direction allows runners who run daily to work different muscle groups); respecting this convention avoids collisions with opposite-direction runners; (4) Sun protection for daytime runs: running in Bangkok between 10am and 4pm without sun protection causes rapid sunburn (UV index routinely 11–12 extreme); scheduling runs outside this window and using SPF50+ sunscreen for unavoidable daytime sessions is the dermatologist-standard approach; (5) Joining Hash House Harriers as a visitor: Bangkok Hash House Harriers welcome visitors and expats; the run typically starts at a pre-announced venue and participants pay a run fee (฿200–350) covering beer and post-run social gathering; no prior registration required for most runs; the route is marked and a buddy system accommodates first-timers.",
  },
  {
    name: "Cycling Bangkok & Beyond — Urban Routes to Long-Distance Rides",
    emoji: "🚴",
    area: "Bangkok cycling: Bang Krachao green lung (ferry + 15km canal loop, most pleasant urban cycling); Chao Phraya riverside path (Maharaj area to Sanam Luang, limited stretch); Khlong Bang Luang (Thonburi heritage cycling route); Lumphini Park inner cycling circuit; Long distance: Ayutthaya day ride (80km one-way); Bangkok to Hua Hin (200km, 2-day); Nonthaburi to Bangkok riverside route; cycling clubs: Critical Mass Bangkok (monthly last Friday), Tour de Nonthaburi (annual); rental hubs: Bang Krachao at island entry, Jatujak Park, limited BTS bike share at specific stations",
    price: "Bang Krachao bicycle rental: ฿60–150/hour; Lumphini Park bicycle rental: ฿60–80/hour; Quality road bicycle rental (per day): ฿800–2,000; BTS bike share (Rabbit Card): ฿10–30 per trip (limited stations); Long-distance cycling tour (Ayutthaya): ฿1,200–3,000 organized; Bicycle repair shop services: ฿50–300 typical repair; Quality bicycle purchase (second-hand): ฿3,000–15,000",
    why: "Cycling Bangkok ranges from leisurely canal-side riding to challenging long-distance touring: (1) Bang Krachao as Bangkok cycling destination: the Bang Krachao green lung island (formed by a bend in the Chao Phraya River, creating a horseshoe-shaped land area) is Bangkok's most beloved cycling destination; a ferry crosses from Klong Toey pier (฿5); the interior paths wind through orchid farms, traditional houses, mangrove corridors, and community gardens in a semi-rural environment that feels far removed from the Bangkok urban density visible from the island edges; (2) Thonburi heritage cycling: the Thonburi canal networks (accessible by bicycle from Wongwian Yai BTS or the Thonburi pier) route through historic communities, Buddhist temples, and canal-side markets that preserve a pre-development Bangkok atmosphere; cycling these routes on weekday mornings before tourist boat tours arrive maximizes the authentic neighborhood experience; (3) Bangkok to Ayutthaya cycling: the Bangkok-Ayutthaya cycling route (80km, typically done in 1 day by experienced cyclists) follows riverside paths and rural roads northward; cycling organizations (Critical Mass Bangkok, cycling Facebook groups) organize this route as a group day ride; the route is achievable for intermediate cyclists with an early start; (4) Urban bike sharing expansion: Bangkok's BTS Rabbit Card bike sharing (available at select BTS stations, expanding) provides cheap point-to-point cycling for short distances around transit stations; the system is limited but growing; (5) Critical Mass Bangkok: the monthly Critical Mass Bangkok ride (last Friday, departure from Chatuchak Park area) draws 200–500 cyclists for a group urban cycling event that temporarily takes over Bangkok road space; no registration required; showing up with a bicycle participates.",
    tip: "Bangkok cycling safety and logistics: (1) Bangkok traffic and cycling safety: cycling Bangkok streets requires high alertness; Thai traffic rarely gives cyclists right-of-way; riding assertively (claiming the lane rather than hugging the left edge where cars door-open into cyclists) is counterintuitively safer than timid riding; (2) Evening cycling timing: Bangkok's heat makes daytime cycling (10am–4pm) uncomfortable without shade; evening rides (5pm–8pm) benefit from lower sun intensity but face heavier traffic; early morning (5:30am–8am) rides combine cool temperatures with relatively light traffic; (3) Bicycle security in Bangkok: quality bicycle locks are essential for any unattended bicycle in Bangkok; U-locks with cable secondary locks are the standard security combination; locking to fixed immovable objects (not bicycle racks that can be lifted); (4) Waterproofing for wet season cycling: cycling during Bangkok's monsoon season (June–October) requires assuming rain during any 2+ hour ride; a waterproof bag cover (available at Chatuchak Market cycling stalls) protects gear; rain jackets are impractical in Bangkok heat; accepting rain and choosing quick-drying clothing is the practical approach; (5) Group ride organization: finding the Bangkok cycling community on Facebook (Critical Mass Bangkok, Bangkok Cycling Club, Bang Krachao Cycling group) provides access to organized group rides, safety in numbers for longer routes, and local route knowledge from experienced Bangkok cyclists.",
  },
];

export function BangkokHikingTrails() {
  return (
    <div className="rounded-2xl border border-green-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-green-700 mb-3">
        🥾 Bangkok outdoor fitness — hiking near Bangkok, running culture & urban cycling routes
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-green-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-green-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
