const TOPICS = [
  {
    title: "Suvarnabhumi Airport (BKK) — Complete Arrival & Departure Guide",
    emoji: "✈️",
    summary: "Suvarnabhumi Airport (IATA: BKK, pronounced 'soo-wan-na-poom') is Bangkok's primary international airport and one of Asia's busiest aviation hubs: (1) Airport scale and layout: Suvarnabhumi opened in 2006, replacing Don Mueang as Bangkok's main international airport; the main terminal is a single massive building (approximately 563,000 square meters) designed by Helmut Jahn; the airport consistently handles 55–65 million passengers annually (ranking in Asia's top 10); satellite terminals and concourses are connected via underground automated people movers (ATC, automated transit connector); (2) Arrival process at Suvarnabhumi: landing → customs and immigration hall (Level 2); Thai and ASEAN passport holders have separate fast lanes; international visitors (non-Thai) queue at standard immigration; visa-on-arrival counter (for eligible nationalities) is adjacent to immigration hall — eligible nationalities pay ฿2,000 fee; eVisa holders (Thailand Thailand e-Visa launched 2023) have dedicated counter; baggage claim is at the same Level 2 arrival hall; customs exit leads to public areas Level 1; (3) Immigration queuing reality: Suvarnabhumi immigration queues have varied significantly over years; post-2020 peak season arrivals (December–February and August) can take 1–2 hours for non-Thai passport immigration; the Thai government has expanded immigration lanes and introduced e-passport automated gates (eligible nationalities); arriving during off-peak hours (early morning or late afternoon weekday flights) significantly reduces immigration wait; (4) Suvarnabhumi's Thailand Pass era changes: Thailand's COVID-era Thailand Pass system is discontinued; current entry is standard immigration card + passport; Thailand no longer requires pre-registration for standard tourist entry; (5) Airport food, duty-free and services: Suvarnabhumi's landside and airside areas have extensive food options; duty-free shops (King Power concession) occupy much of the airside area; Thai massage available airside (gate area); prayer rooms airside; left luggage service Level 1.",
    action: "Airport Rail Link (ARL) to Bangkok: departs from Suvarnabhumi basement level B1, 29 minutes to Phaya Thai station (BTS Red Line interchange), ฿45; City Line stops at 8 intermediate stations; ARL operating hours: approximately 6am–midnight; private transfer (hotel car/Grab): typically ฿600–1,200 to central Bangkok; public airport bus (route S1, S2, S3, etc.): ฿30–60; taxi from official stand: metered taxi + ฿50 expressway + toll approximately ฿350–600 to Sukhumvit; SIM card purchase: AIS, DTAC, True Move shops at arrival Level 1; currency exchange: SuperRich (decent rate), Kasikorn Bank, Bangkok Bank at arrival level (avoid airport-only exchange booths with inferior rates).",
  },
  {
    title: "Don Mueang Airport (DMK) — Budget Airlines, Getting There & Overnight Strategies",
    emoji: "🛫",
    summary: "Don Mueang Airport (IATA: DMK) is Bangkok's secondary airport serving budget airlines and is farther north of central Bangkok: (1) Don Mueang vs. Suvarnabhumi airline allocation: Don Mueang primarily serves Thai domestic budget airlines (Nok Air, Thai Lion Air, Thai AirAsia — though AirAsia also uses Suvarnabhumi for some routes) and regional budget international routes; the allocation of airlines between DMK and BKK changes based on capacity and airline agreements; verifying which Bangkok airport a budget airline uses for a specific route is essential before booking transportation; (2) Distance and transport challenge: Don Mueang is 25km north of Bangkok's center (vs. Suvarnabhumi 30km east but with direct rail link); Don Mueang has no direct BTS/MRT connection; transport options: public bus (A1 express bus to Chatuchak, ฿30–50, approximately 45–60 minutes to BTS Mo Chit), Grab (฿250–500 depending on traffic), metered taxi (฿200–400 plus expressway tolls approximately ฿70), rail: State Railway of Thailand train to Don Mueang station (not efficient for most destinations); (3) Connecting between DMK and BKK airports: some Bangkok itineraries require connecting between the two airports; the recommended method is A1 bus to Chatuchak (BTS Mo Chit)/taxi to Suvarnabhumi or vice versa; the Amari Don Mueang Airport hotel shuttle operates between airports for guests; budget 2–3 hours minimum for the inter-airport transfer regardless of method; (4) Don Mueang overnight sleeping: Don Mueang has 24-hour access and some sleeping-chair areas; for genuine overnight pre-flight stays, Amari Don Mueang Airport Hotel is directly connected; budget travelers use the terminal lounge chairs with their luggage; Don Mueang is generally less comfortable for overnight waiting than Suvarnabhumi; (5) Don Mueang's domestic service role: Don Mueang is often the departure point for Thai domestic flights to secondary cities (Udon Thani, Khon Kaen, Ubon Ratchathani, Roi Et, Loei) on Nok Air and Thai Lion Air; for Bangkok-based travelers doing domestic Thailand circuits, Don Mueang may be the practical choice regardless of inconvenience.",
    action: "A1 bus to Don Mueang: departs from Chatuchak BTS Mo Chit/MRT Chatuchak interchange, ฿30–50, runs approximately 5am–midnight; Grab to Don Mueang from central Bangkok: ฿250–500 depending on traffic; Nok Air Don Mueang operations: nokmiles.com; Thai Lion Air: lionairthai.com; Don Mueang information: donmuengairport.com; overnight storage at Don Mueang: left luggage at Arrival Level 1.",
  },
  {
    title: "Bangkok Airport Lounges — Priority Pass, Miracle Lounge & Budget Access",
    emoji: "🛋️",
    summary: "Bangkok's Suvarnabhumi Airport has an extensive airport lounge ecosystem that travelers can access beyond premium ticket class: (1) Suvarnabhumi lounge categories: airline lounges (Thai Airways Royal Orchid Lounge, Bangkok Airways Blue Ribbon Club, Singapore Airlines SilverKris, multiple full-service carriers' lounges at specific concourses); independent commercial lounges (Miracle Lounge — most expansive independent lounge at Suvarnabhumi, Coral Executive Lounge); Priority Pass/Lounge Key affiliated lounges (multiple Suvarnabhumi lounges accessible with these programs); (2) Miracle Lounge at Suvarnabhumi: Miracle Lounge (multiple locations at Suvarnabhumi, both pre-security and post-security areas, also at Don Mueang) is the benchmark independent airport lounge in Bangkok; facilities include: shower rooms (sometimes limited hours), buffet food (Thai and international), complimentary alcohol, Wi-Fi, comfortable seating, business facilities; pricing: walk-in access approximately ฿600–800; Priority Pass holders access free (Priority Pass member of certain bank credit cards); (3) Priority Pass at Bangkok airports: Priority Pass (the global independent lounge access program) is included with premium credit cards (DBS, Standard Chartered, Citibank, American Express in various markets); Priority Pass members can access Suvarnabhumi lounges without airline ticket class requirement; Priority Pass access is valuable for frequent Bangkok transitors who do not regularly fly business class; (4) Thai credit card lounge access: Thai domestic credit cards (Bangkok Bank, Kasikorn Bank premium cards, SCB Platinum) often include complimentary airport lounge visits per year — making Bangkok airport lounge access effectively embedded in Thai banking relationships for Thai residents; (5) Walk-in lounge access economics: for 4+ hour layovers or pre-flight time, a ฿600–800 Miracle Lounge walk-in fee delivers: unlimited buffet meals (reasonable Thai-international selection), beer and spirits, shower (if available), charging stations, comfortable seating — competing favorably with equivalent airport food and drink purchases from the terminal.",
    action: "Miracle Lounge booking: miraclelounge.com or walk-in at Suvarnabhumi; Priority Pass: prioritypass.com (check if your bank credit card includes membership); Coral Executive Lounge Suvarnabhumi: walk-in or Priority Pass; Thai Airways Royal Orchid Lounge: ticket class or Star Alliance Gold; day-use shower without full lounge: some Bangkok Airport hotel facilities (Le Meridian Suvarnabhumi airport hotel) accept non-guests for shower use at ฿500–800; free lounge alternative: Suvarnabhumi's Level 4 observation deck (free access, views of runway and aircraft operations, less comfortable than lounge but free).",
  },
];

export function BangkokSuvarnabhumi() {
  return (
    <div className="rounded-2xl border border-sky-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-sky-700 mb-3">
        ✈️ Bangkok airports — Suvarnabhumi BKK guide, Don Mueang DMK & lounge access
      </div>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-sky-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-sky-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
