const SPOTS = [
  {
    name: "Best Bangkok Souvenirs — What's Actually Worth Buying",
    emoji: "🛍️",
    area: "Souvenir shopping zones: Chatuchak Weekend Market (Bangkok's largest, 15,000 stalls, weekends only); MBK Center 5th and 6th floor (electronics, Thai crafts, copy goods); Asiatique Riverfront (curated Thai craft vendors, evening market); RCA Pratunam wholesale market; Silom Market/Patpong Night Market (souvenir street market near Silom); Khao San Road market (tourist-focused); Pratunam Market (fashion wholesale); specific specialty: Thai silk (Jim Thompson store at Suriwong, Si Lom); bronze ware (Chinatown); traditional pottery (Siam Discovery, various craft stores)",
    price: "Jim Thompson Thai silk scarf: ฿800–4,000; Thai celadon ceramic (small): ฿200–800; Traditional Thai silk (per meter, from market): ฿400–2,000; Carved wooden elephant (small): ฿100–500; Thai lacquerware (quality): ฿300–2,000; Hill tribe silver jewelry: ฿200–2,000; Benjarong ceramic cup set: ฿500–3,000; Good quality Thai spice/herb set: ฿200–600; Copy bags (obvious designer copies, Pratunam): ฿200–1,000; Custom tailored shirt: ฿1,000–3,000",
    why: "Bangkok has a stratified souvenir market from tourist trinkets to genuinely valuable Thai craftwork: (1) Authenticated Thai silk: Jim Thompson Thai silk (Jim Thompson brand, operated since the 1950s as the primary commercializer of Thai silk to international market) carries authentic certified Thai silk with quality guarantees; Thai Silk Symbol certification (the golden tag) on market-purchased silk verifies authenticity; cheap 'Thai silk' without certification is often Thai-loomed but synthetic-fiber; (2) Celadon and Benjarong ceramics: Thai celadon (jade-green glazed pottery from Chiang Mai tradition) and Benjarong (five-color royal ceramic tradition) are genuine Thai craft products with historical depth; high-quality examples are appropriate gifts with both aesthetic and cultural value; buying directly from ceramic workshops (several in Chatuchak or from craft stores at Siam Discovery) avoids tourist markup; (3) Thai bronze ware: Bangkok's Chinatown area has bronze ware and metalwork shops selling traditional Thai Buddhist religious items (bells, incense holders, ceremonial bowls) and decorative objects; the Mangkon Road area within Chinatown has specialty metal shops; (4) Practical Thai herb and spice sets: curry paste sets, jasmine rice, butterfly pea flower tea, pandan products, and dried Thai herbs (galangal, kaffir lime leaves) packaged attractively are practical souvenirs that cost less than packaged tourist versions and carry genuine Thai culinary culture; Tops Market or Gourmet Market supermarkets carry quality packaged versions; (5) Custom tailoring as souvenir: Bangkok's custom tailoring industry (Sukhumvit area, particularly sois around Asok) produces made-to-measure shirts, suits, and dresses within 24–48 hours at prices significantly lower than Western tailoring; a bespoke garment is both souvenir and wearable product.",
    tip: "Bangkok souvenir buying guidance: (1) Chatuchak Weekend Market strategy: Chatuchak's 15,000 stalls require section navigation; the official Chatuchak map (available at the market entrance information booth) divides the market by category; craft and art sections (sections 1–26 approximately) are different from plant sections, food sections, and pet sections; arriving by 9am before crowds and heat reduces stress; (2) Copy goods legal status: 'copy goods' (replicas of designer brands) are illegal under Thai IP law but widely sold in tourist markets (Patpong, Pratunam, Silom); possession of copy goods is generally tolerated by Thai customs for personal use amounts; exporting them through customs carries risk; buyers should understand both the IP law context and the practical customs situation; (3) Elephant-related product ethics: traditional ivory (elephant tusk) products are illegal under CITES; some Bangkok shops still sell pre-ban ivory items with documentation; genuine antique ivory with full provenance documentation may be legally exportable with permits; recent ivory without documentation is both illegal and unethical; (4) Silver pricing in Bangkok: Thai hill tribe silver and Bangkok silverwork should be priced by weight plus craftsmanship; understanding silver price per gram context (Thai silver is typically 92.5% sterling) allows evaluation of whether prices reflect material value; significantly underpriced silver may be silver-plate rather than sterling; (5) VAT refund: Thailand's VAT Refund for Tourists program allows refunds of 7% VAT on purchases over ฿2,000 per store and ฿5,000 total, at shops displaying the 'VAT Refund' sign; processed at Suvarnabhumi Airport departure VAT refund counter; collecting receipts and VAT refund forms at purchase enables this.",
  },
  {
    name: "Bangkok Fashion Shopping — Malls, Vintage & Wholesale Districts",
    emoji: "👗",
    area: "Bangkok fashion destinations: Siam Paragon (luxury brands: Prada, Gucci, Louis Vuitton, Bottega Veneta, Hermès); CentralWorld (international mid-range: Zara, H&M, Uniqlo flagship); EmQuartier and Emporium (fashion + dining, Sukhumvit Soi 49); Icon Siam (ultra-luxury riverside mall, SOOK Siam, river access); Platinum Fashion Mall (wholesale fashion, Pratunam area); Pratunam wholesale market; vintage: Chatuchak Weekend Market vintage section; Thonglor vintage shops; Ari vintage street; local designer: Siam Discovery curated Thai designers; Asiatique Thai fashion; Bangkok street fashion: RCA/Royal City Avenue for teen fashion",
    price: "Luxury brands (Siam Paragon): international retail pricing or slightly higher import tax; Zara/H&M at CentralWorld: same as international pricing; Platinum Fashion Mall wholesale: ฿100–500 per item (minimum quantities apply); Thai designer pieces: ฿1,500–15,000; Chatuchak vintage: ฿200–2,000 per piece; Uniqlo Bangkok flagship: same as regional Uniqlo pricing; Custom tailored suit: ฿8,000–40,000; Icon Siam fashion retailers: Thai luxury and international premium brands; Bangkok street market fashion: ฿100–500",
    why: "Bangkok is Southeast Asia's premier fashion shopping destination with unmatched range from wholesale to ultra-luxury: (1) Platinum Fashion Mall's wholesale model: the Platinum Fashion Mall (adjacent to Pratunam market) operates as a wholesale-to-public hybrid; standard selling is per-item but many vendors offer discounts for bulk purchases (minimum 3–6 pieces per style); international fashion buyers (particularly from South Asia, Middle East, and Africa) come specifically to Platinum for fashion wholesale sourcing; retail tourists can purchase individual pieces at above-wholesale but below-retail pricing; (2) Thai designer scene at Siam Discovery: the Siam Discovery mall's ground and lower floors feature curated Thai fashion designers; designers like Kloset, Theatre, and Asava (established Thai luxury brands) and emerging young designers mix at Siam Discovery's premium retail concept; Thai fashion design education (at Chulalongkorn's Faculty of Fine and Applied Arts and King Mongkut's University of Technology) produces internationally competitive designers; (3) Counterfeit goods concentration: Bangkok's counterfeit fashion goods (Gucci, LV, Supreme replicas) are concentrated at specific locations (Pratunam market interior alleys, Patpong market, Silom night market); the quality ranges from obvious fakes to superficially convincing replicas; the trade is openly visible; (4) Luxury pricing Bangkok vs. home market: authentic luxury goods at Bangkok's Siam Paragon (Gucci, Prada, Hermès) are typically priced at international retail with Thai VAT (7%) included; occasionally there are slight price advantages vs. European prices due to import tax structures; the primary advantage of Bangkok luxury shopping is product availability, not significant price difference; (5) Bangkok fashion cultural context: Thai fashion culture blends Korean-influenced aesthetics (K-wave has heavily influenced young Thai fashion), traditional Thai elements (ikat textiles, Thai silk fusion), Western streetwear, and Japanese fashion influence (Harajuku-adjacent aesthetics in Thonglor/Ekkamai neighborhoods); this cultural fusion creates distinctively Bangkok fashion sensibilities.",
    tip: "Bangkok fashion shopping guidance: (1) Sizing in Bangkok: Thai fashion retail uses Asian sizing which runs small relative to Western averages; trying items on is essential; some stores carry International sizing, but Thai-size 'free size' garments often fit up to Asian small/medium frame; Platinum Fashion Mall's wholesale garments have the most rigid sizing systems; (2) Tailoring timeline: for custom tailoring requiring fittings (suits, formal dresses), budget 3–5 days minimum with 2 fittings; 24-hour turnaround tailoring (offered on Sukhumvit and near tourist areas) often results in quality compromises; Bangkok's best tailors (Pinky Tailor, Raja's Fashions, others on Sukhumvit Soi 11–13) require 3–7 days for quality results; (3) Vintage Chatuchak discovery: Chatuchak's vintage clothing section (typically sections 3–5 area) has Thailand's most diverse vintage clothing market; items range from authentic mid-century Thai traditional clothing (phaasin tube skirts, traditional Thai cotton) to curated international vintage (Levi's, band tees, vintage denim); weekend morning arrival is necessary before key pieces sell; (4) Icon Siam luxury tax refund: Icon Siam's luxury stores participate in the VAT refund program; collecting refund forms from each store and processing at the Suvarnabhumi Airport counter recovers 7% VAT on qualified purchases; (5) Designer outlet at CentralWorld: CentralWorld's upper floor periodically has outlet-style sales for Thai designer brands; sale seasons (January and July) produce significant discounts on previous-season Thai designer fashion.",
  },
  {
    name: "Chatuchak Weekend Market — The Complete Navigation Guide",
    emoji: "🏪",
    area: "Chatuchak Weekend Market (JJ Market): Kamphaeng Phet Road, Chatuchak District; access: MRT Chatuchak Park (exit 1) or BTS Mo Chit; open: Saturday and Sunday 9am–6pm (some stalls Friday 4–8pm for wholesale); Or Tor Kor Market (high-quality fresh market, open daily): adjacent, north side of Chatuchak; Clock Tower (central landmark): main navigation reference; market sections: 1–27 arranged in a rough grid; main categories by zone: section 1–4 (clothing, vintage, textiles), section 7–8 (antiques, collectibles), section 10–26 (home, furniture, ceramics, crafts), section 3–5 (pets), section 21–27 (plants and garden); food: Aor Tor Kor border area restaurants + multiple food stalls throughout",
    price: "Chatuchak market access: free; Budget meal inside market: ฿50–150; Cool refreshment (coconut ice cream, coconut water): ฿50–100; Vintage clothing: ฿200–2,000; Art print/poster: ฿200–1,500; Thai craft items: ฿100–2,000; Collectible figure (Thai, Japanese, anime): ฿200–5,000; Large antique piece: ฿2,000–50,000+; Thai ceramic: ฿150–3,000; Plant/orchid: ฿100–2,000; Chatuchak map: free at information booths",
    why: "Chatuchak Weekend Market is one of the world's largest markets and Bangkok's most comprehensive single shopping destination: (1) Scale and diversity: 15,000+ stalls across 35 acres; the market covers essentially every product category; the combination of authentic Thai handcraft, vintage and antique objects, live plants and orchids, food, art, collectibles, books, pets, and fashion in one walkable space is globally unique; (2) Vintage and antiques concentration: Chatuchak's antiques and vintage section (sections 7, 8, and parts of 1 and 26) is Bangkok's best concentration of genuine antique and vintage items; Thai wooden furniture, vintage posters, old photographs, silverwork, ethnic minority textiles (hill tribe and Laos-origin ikat), ceramics, and Buddhist religious objects are sold by specialist vendors; (3) Thai art market: Bangkok's independent artist and illustrator community sells prints, original artworks, and custom objects at Chatuchak; the market functions as an accessible gallery for work that would cost significantly more through galleries; Thai artist communities (particularly illustrators influenced by Japanese character design) have strong Chatuchak presences; (4) Orchid and tropical plant market: Thailand is one of the world's largest orchid producers; Chatuchak's plant section (saturdays most active) sells tropical plants and particularly orchids at a fraction of Western retail prices; taking orchids home requires checking import regulations (orchid phytosanitary certificate available from sellers); (5) Or Tor Kor Market adjacency: the Or Tor Kor government-managed fresh market adjacent to Chatuchak offers premium quality Thai produce, prepared food, and imported food products in a cleaner, more organized environment than standard markets; combining Or Tor Kor with Chatuchak is the most efficient way to experience both Bangkok food culture and market shopping.",
    tip: "Chatuchak Weekend Market survival guide: (1) Arrival timing is critical: arriving by 9:30am (within 30 minutes of opening) provides the most comfortable temperature (before the tropical heat peaks), least crowded aisles, and best availability of key items; arriving after 11am means navigating crowds in extreme heat; (2) Navigation strategy: the Clock Tower at the market's center is the primary navigation landmark; exiting and re-entering via the Kamphaeng Phet Road gate (MRT side) is the easiest orientation reset; the Chatuchak Weekend Market app (or chatuchakguide.com) maps individual stall locations for specific vendors; (3) Bargaining culture at Chatuchak: bargaining is expected at most clothing, craft, and souvenir stalls; opening at 60–70% of the asking price and settling around 75–85% is the typical negotiation; food, coffee, and restaurant stalls have fixed prices (not for negotiation); (4) Heat management: Chatuchak has sections with roof cover and sections that are open air; routing through covered sections during peak heat (11am–2pm) significantly reduces heat stress; several stalls sell Thai cold drinks and coconut ice cream; the Or Tor Kor Market next door is air-conditioned for breaks; (5) Pets section ethics: Chatuchak's pet section has been criticized for selling exotic pets illegally; CITES-protected species (parrots, some reptiles, turtles) are sometimes sold in the Chatuchak pet section; purchasing CITES-listed animals creates legal complications at airport customs for exporters; the pet stalls selling legal animals (Thai local breeds, common fish, permitted birds) are distinguishable by species being common types rather than unusual exotics.",
  },
];

export function BangkokSouvenirs() {
  return (
    <div className="rounded-2xl border border-orange-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-orange-700 mb-3">
        🛍️ Bangkok shopping guide — best souvenirs, fashion districts & Chatuchak market strategy
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-orange-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-orange-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-orange-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
