const SPOTS = [
  {
    name: "Bangkok Sports Bars & Expat Pubs — Where to Watch Live Sports",
    emoji: "🍺",
    area: "Bangkok sports bar districts: Sukhumvit (Nana, Asok, Thong Lo areas); Silom (expat bars); RCA (Royal City Avenue, local entertainment street); sports bars: The Sportsman Bangkok (Soi 13), Cheap Charlie's (Soi 11), The Dubliner (Silom), Robin Hood Bar (Ekkamai, British pub); local beer bar strips: Sukhumvit Soi 11, Sukhumvit Soi 33, Soi Cowboy (adult entertainment area adjacent to sports bars), Silom Soi 4; Sky bars with TV: less common, mostly ground-floor pub format; craft beer: Dukes (Sukhumvit), Mikkeller Bangkok (Ekkamai)",
    price: "Draft beer (local Singha/Leo/Chang): ฿80–150; Craft beer (Bangkok craft): ฿150–280; Import beer (Heineken, Stella): ฿120–200; Happy hour (5pm–8pm typical): often 2-for-1 or 30–40% off; Sports bar entry: typically free; Bar snacks (wings, nachos): ฿150–350; Sports bar with food menu: ฿300–800 total typical spend",
    why: "Bangkok's expat pub culture is anchored by sports viewing and provides the city's most accessible international community social environment: (1) Premier League dominance: English Premier League football is the dominant sports bar broadcast content in Bangkok; the large British expat community (Bangkok has a significant UK expat population in banking, education, and NGO sectors) drives Premier League coverage as the standard offering; Champions League, Six Nations rugby, ATP tennis, and Australian rules football are also common; (2) International sports broadcast access: Thai sports bars (particularly expat-oriented bars) typically subscribe to multiple international satellite packages enabling simultaneous coverage of different sports; the time zone (Thailand GMT+7) aligns well for watching European sports (morning broadcasts) and American sports (late night and early morning); (3) Thai domestic football (Thai League): Thai domestic football has a passionate domestic following; King Power Stadium (Leicester City parent company connection reflects Thai Royal family sports investment) and the Thai national team draws local bar attendance; (4) Bangkok bar culture etiquette: Bangkok's expat bars are generally welcoming to solo customers (bar seating culture); starting conversation with other patrons at sports bars is socially normal during live matches; Thai bar staff in expat bars are typically English-proficient; (5) Darts and bar games: Bangkok's expat pub culture includes darts leagues and pool table culture; several Sukhumvit bars have organized darts competitions (British darts — steel-tip, oche marking, scoreboard format) that form social communities of regular expat players.",
    tip: "Bangkok pub and sports bar guidance: (1) Broadcast rights complexity: specific sports events may only be broadcast in certain bars based on which bars have paid for specific broadcast packages; checking which bars have confirmed broadcast of specific matches (particularly UEFA Champions League or major boxing events) in advance via bar social media saves arriving at a bar not showing the desired content; (2) Happy hour optimization: most Bangkok expat bars offer significant happy hour discounts (2-for-1 beer, 50% off cocktails) between 5pm–8pm; arriving at happy hour start and drinking through sunset is the cost-efficient approach; (3) Thai craft beer bars: Bangkok's craft beer scene (Dukes, Mikkeller Bangkok at Ekkamai, Mahanakhon Beer Lab, Factory Beer Bangkok) provides significantly better beer quality than international or local lager brands at 1.5–2x the price; these venues attract a different demographic (professional Thai and expat, food-focused) from sports bars; (4) Avoiding overpaying in tourist areas: bars directly fronting Sukhumvit Road (particularly between Soi 4–21) frequently charge tourist-inflated prices; bars one block off the main road (down the sois) typically offer the same drinks at lower prices; (5) Bangkok pub quiz culture: multiple Bangkok bars run weekly pub quiz nights (typical: Tuesday or Wednesday evenings); The Sportsman, The Dubliner, and several Silom bars organize English-language pub quiz nights; these events provide structured social interaction for new Bangkok arrivals building social networks.",
  },
  {
    name: "Bangkok Darts Culture — Leagues, Venues & Competition",
    emoji: "🎯",
    area: "Darts venues: most Sukhumvit expat bars have steel-tip dart boards; The Sportsman (Soi 13) — organized darts league; Bangkok Darts League (BDL) organizes inter-pub competitions; JD Wetherspoon-style pub dart culture also in Silom; soft-tip electronic darts: spread across Thai entertainment venues and some international bars; Major darts venues: Soi 11 bar strip has multiple boards; dedicated darts bars in Bangkok: limited but growing; darts equipment: available at Decathlon (sports retailer in multiple Bangkok malls), Lotus's superstores",
    price: "Darts entry (bar): typically free with drink purchase; Bangkok Darts League registration: ฿500–1,000/season; Steel-tip dart set (starter): ฿500–2,000; Premium tungsten darts: ฿3,000–15,000; Electronic darts machine: pay-per-game ฿20–50; Dart flights and shafts: ฿50–200 per set; Dartboard purchase (standard): ฿800–3,000",
    why: "Darts has developed a genuine social culture in Bangkok's expat community: (1) Bangkok Darts League structure: the Bangkok Darts League (BDL) organizes regular inter-pub competitions across Sukhumvit and Silom bars; teams represent specific pubs; the league format (typically doubles, 501 format) runs across multiple evenings weekly during the main season; (2) Steel-tip vs. soft-tip split: Bangkok has both steel-tip dartboard culture (in expat pubs, traditional British darts format) and electronic soft-tip darts machines (common in Thai entertainment venues, Crown Royal type machines, coin-operated); the cultures are largely separate social groups; (3) Thai darts culture: darts has a genuine Thai domestic following; Thai darts players have achieved professional recognition in international soft-tip tournaments; Thai soft-tip darts bars (particularly in outer Bangkok and provincial cities) represent a separate but significant darts culture; (4) Social function: darts functions as a social lubricant in Bangkok's expat pub scene; the game structure (alternating throwing, extended calculation of remaining score, natural conversation breaks) facilitates socializing between strangers more naturally than drinking or watching TV; (5) Bangkok darts equipment: Decathlon Bangkok (major sports retailer) carries starter darts equipment; serious players import tungsten dart sets from UK retailers (Darts Corner, Winmau, Red Dragon) due to limited Bangkok selection at professional level.",
    tip: "Getting into Bangkok darts: (1) Finding current Bangkok Darts League information: searching Facebook for 'Bangkok Darts League' finds the current season schedule and participating venues; the league is organically organized and changes venues across seasons; (2) Steel-tip practice tips: Bangkok's wooden dartboards (sisal fiber, self-healing) require steel-tip darts; electronic boards require soft-tip darts; confirming board type before choosing darts at purchase prevents incompatibility; (3) The oche (throw line): standard steel-tip oche (throwing line) distance is 2.37m from the board face; Bangkok bars with established darts culture have this marked (look for a raised strip or tape on the floor); unofficial boards may not have an oche marked — pacing 8 normal steps from the board approximates the distance; (4) 501 game for beginners: starting at 501 points, each player subtracts their dart scores; the player must finish exactly on a double (outer ring) to win; this is the standard pub darts format in Bangkok; (5) Joining Bangkok darts leagues: contact The Sportsman Bangkok or other Sukhumvit bars with established dart teams to ask about joining as a new arrival; Bangkok darts league teams welcome new players especially early in the season when team composition is forming.",
  },
  {
    name: "Bangkok Board Game Cafés & Tabletop Gaming Scene",
    emoji: "🎲",
    area: "Board game cafés: Dice Dice Dice (Ekkamai area); Board Games Heaven (Silom Soi 4); Meeple House (Chatuchak area); Cardboard Society (Ari); Bangkok Board Game Club (monthly organized group, rotating venues); tabletop gaming: Warhammer Bangkok (miniature gaming community); Magic the Gathering: Mothership Game Center (Chatuchak); regular locations for TCG: Card Kingdom Bangkok; RPG gaming: Dungeons and Dragons groups through Facebook Bangkok Gamers Network",
    price: "Board game café entry + unlimited games: ฿100–250/person (2–3 hour session); Per-game rental: ฿50–150; Buy board games in Bangkok: Kinokuniya has selection (฿800–3,000), dedicated game shops have wider selection; Magic the Gathering draft event: ฿300–500; Warhammer painting/gaming session: space typically free, miniatures purchase required (฿300–5,000 per unit); D&D session (organized): typically free or small donation for venue",
    why: "Bangkok has a growing tabletop gaming community that provides an alternative social scene to the bar-focused expat environment: (1) Board game café culture: the board game café format (pay entry for unlimited game access from a library of 200–500+ games with staff guidance) has grown significantly in Bangkok since 2015; these spaces attract a younger, non-drinking-centered social demographic; (2) Bangkok's international board game community: Bangkok's large international community (expats, digital nomads, international students) creates demand for English-language tabletop gaming; game libraries in Bangkok board game cafés skew toward international titles (Catan, Ticket to Ride, Carcassonne, Pandemic, Terraforming Mars, Wingspan) alongside popular Thai-produced games; (3) Thai tabletop gaming growth: Thailand's domestic board game publishing industry is growing; Thai-language game publications and Thai game designers are emerging; the TGIF (Thailand Game Industry Festival) annually showcases Thai tabletop game production; (4) Magic the Gathering Bangkok community: Magic the Gathering has an established Bangkok player community; weekly draft nights and organized play events happen at dedicated game stores; the format is language-universal enough that the Bangkok community mixes international and Thai players effectively; (5) Dungeons and Dragons and RPG community: Bangkok's D&D community (organized through Facebook groups, Discord) runs regular game sessions; finding groups specifically for new arrivals (both experienced and beginner players) is possible through the Bangkok Gamers Network Facebook group.",
    tip: "Bangkok board game café and gaming venue practical guidance: (1) Calling ahead for peak times: popular Bangkok board game cafés fill quickly on Friday and Saturday evenings; calling or reserving via Line/Facebook message before arriving on weekends prevents waiting; (2) Game recommendation requests: board game café staff at Bangkok venues are typically enthusiastic about matching game recommendations to group size, experience level, and playtime preferences; asking for help selecting from the library rather than browsing independently leads to better game selection; (3) Bringing non-gaming friends: board game cafés work well for mixed groups (some gamers, some non-gamers) because lighter party games (Codenames, Dixit, Telestrations, Concept) provide entry points for non-gamers without committing to complex strategy games; (4) Bangkok gaming vocabulary: some Bangkok board game terms mix English and Thai (particularly for card plays and game actions); English-dominant gaming groups in Bangkok typically provide English instruction for any Thai game components; (5) Food and drink in board game cafés: Bangkok board game cafés typically serve café food and drinks (not full restaurant menus); checking the café's food offerings before visiting allows planning whether to eat before or combine with a meal at a nearby restaurant.",
  },
];

export function BangkokPubsGames() {
  return (
    <div className="rounded-2xl border border-amber-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-amber-700 mb-3">
        🍺 Bangkok pubs & games — sports bars, darts culture & board game café scene
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-amber-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-amber-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-amber-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
