const SPOTS = [
  {
    name: "Khao Yai National Park — Bangkok's Essential Wildlife Escape",
    emoji: "🐘",
    area: "Khao Yai National Park: 200km northeast of Bangkok (2.5–3 hours by car via Highway 1 and Highway 2); Pak Chong town is the park gateway; National Park entry point from Pak Chong: 14km; nearby accommodation: Pak Chong town hotels (budget) and resort properties inside and adjacent to park (฿2,000–15,000/night); UNESCO World Heritage Site (Dong Phayayen-Khao Yai Forest Complex); coordinates: approximately 14.4°N, 101.4°E",
    price: "Khao Yai National Park entry (foreigner): ฿400; Thai national: ฿40; Vehicle entry: ฿50; Guided wildlife tour (night): ฿500–1,500; Wildlife guide (accredited): ฿1,500–3,000/day; Haew Narok Waterfall access: included in park entry; Overnight safari (1 night + 2 days guided): ฿3,000–8,000; Budget accommodation (Pak Chong): ฿300–800; Bungalows inside park (DNP): ฿800–2,000",
    why: "Khao Yai is Bangkok's most accessible destination for genuine wildlife viewing in intact tropical forest: (1) Wildlife diversity: Khao Yai National Park contains 50+ mammal species including Asian elephant (wild population approximately 200–300), Siamese crocodile (reintroduced), white-handed gibbon, pig-tailed macaque, Sambar deer, Barking deer, jungle cat, and occasionally clouded leopard and tiger (extremely rare); the park records 300+ bird species; (2) Night safari: Khao Yai's main road after dark (park closes to visitors at 6pm but overnight lodge guests can arrange night drives with park permission) reveals nocturnal wildlife that daytime visitors never see; civets, porcupines, owls, and deer at close range in vehicle headlights; (3) Haew Narok Waterfall: the park's most dramatic feature — a 150m three-tiered cascade in primary forest; accessible by a 4km trail from the main road or by car to the parking area; the surrounding forest has wild elephants regularly sighted near the falls; (4) Prehistoric art: the park contains caves with prehistoric human habitation evidence; Bat Cave (Tham Khang Kho) near the park entrance has the largest bat colony in Thailand (approximately 2 million wrinkle-lipped free-tailed bats emerge at sunset); (5) Conservation success story: Khao Yai is Thailand's conservation anchor — wild elephant numbers have stabilized, horn-bill populations (Great hornbill, Oriental Pied Hornbill) have recovered significantly, and the park serves as breeding ground for species that populate surrounding wildlife corridors.",
    tip: "Khao Yai trip planning: (1) Best season: November–June is the best season for Khao Yai wildlife viewing; July–October (monsoon) brings heavy rain and road access limitations (park may temporarily close specific sections); (2) Guided vs. self-drive: self-driving is possible but accredited local guides significantly improve wildlife encounter rates; guides know current elephant movement zones, hornbill nest sites, and nocturnal wildlife patterns; the guide cost (฿1,500–3,000/day) is justified by encounter rate improvement; (3) Elephant road crossing: Khao Yai's park road has regular wild elephant crossings; approaching to within 30m of wild elephants is dangerous — pulling over, turning off engine and lights, and waiting is the correct protocol; honking and flashing lights can provoke charges; (4) Bus access from Bangkok: air-conditioned buses from Bangkok's Morchit (Chatuchak area) bus station to Pak Chong take approximately 3 hours (฿100–150); from Pak Chong, songthaew or taxi to the park entrance; (5) Booking accommodation in advance: accommodation near Khao Yai (particularly the popular resort cluster of Khao Yai Art Museum Farm area) fills quickly on weekends; booking at least 2 weeks ahead for weekend visits is advisable.",
  },
  {
    name: "Kaeng Krachan National Park & Thailand's Largest National Park",
    emoji: "🦅",
    area: "Kaeng Krachan National Park: 160km southwest of Bangkok (2.5–3 hours by car); in Phetchaburi Province; Kaeng Krachan is Thailand's largest national park (2,915 km2, approximately 35% of Phetchaburi Province); Phetchaburi city (historic, with palaces and temples) is 50km before the park; adjacent to Hua Hin (50km south); park headquarters at Kaeng Krachan village; Bueng Krachap Lake (dam reservoir) forms park's western boundary",
    price: "Kaeng Krachan National Park entry: ฿300 (foreigner), ฿30 (Thai); Boat rental on dam reservoir: ฿300–600/hour; 4WD jeep safari (with guide): ฿1,500–3,000; Ban Krang Camp riverside camping: ฿150–200 per person per night; DNP bungalows: ฿800–2,000; Bird watching guide: ฿1,500–2,500/day; Park interior road (private vehicle): included in entry; Phetchaburi palace visit: ฿150",
    why: "Kaeng Krachan is Thailand's most important single-site bird watching destination and the country's largest protected forest area: (1) Bird diversity record: Kaeng Krachan records 400+ bird species — the highest single-site count in Thailand; this includes rare forest species (Gurney's Pitta, a critically endangered species with few locations remaining), multiple endemic species, and enormous raptor diversity; Bird Life International lists Kaeng Krachan as one of Asia's most significant IBAs (Important Bird Areas); (2) Ban Krang Camp birding: the Ban Krang Camp area inside the park (40km from park HQ along the interior road) has the highest bird diversity; the camp's forest clearings and water sources attract forest species continuously; dawn sessions (5am–9am) produce the most species; (3) Wildlife beyond birds: Asian elephant (estimated 200+ in the park), clouded leopard, leopard cat, sun bear, and banteng (wild cattle, endangered) inhabit Kaeng Krachan; (4) Phetchaburi historical combination: the town of Phetchaburi (50km from park entrance) contains multiple historic temples and Phra Nakhon Khiri Historical Park (hilltop palace of Rama IV); combining a Kaeng Krachan wildlife day with Phetchaburi historic town exploration makes an excellent 2-day Bangkok excursion; (5) Watershed importance: the park protects the headwaters of the Phetchaburi River, providing water to Phetchaburi and Hua Hin; the park's conservation also directly benefits Bangkok's nearest beach resort.",
    tip: "Kaeng Krachan trip planning: (1) Interior road access (4WD only): the 40km interior road to Ban Krang Camp is passable only by 4WD vehicles (the track has steep rocky sections); renting a park jeep service or arranging 4WD transport through park-adjacent guesthouses is required without your own 4WD; (2) Bird watching timing: December–May is the optimal bird watching period at Kaeng Krachan; the deciduous forest is less dense, migrants from the north supplement resident species, and forest birds are more active in the cooler temperatures; (3) Camping permits: overnight camping at Ban Krang Camp requires advance booking through the DNP reservation system (ไปเที่ยว app or dnp.go.th); weekend slots fill quickly; (4) Leeches in wet season: July–October monsoon season makes the interior forest trails uncomfortable (leeches, muddy tracks, heavy rain); park activity in the wet season is best limited to the reservoir and park headquarters area; (5) Phetchaburi food stop: the town of Phetchaburi is famous for its distinctive desserts (khao chae — rice in jasmine-scented water, traditional Phetchaburi sweets); stopping for a meal in Phetchaburi on the return from Kaeng Krachan adds an authentic Thai food regional experience to the trip.",
  },
  {
    name: "Erawan National Park & Gulf Coast Day Trips from Bangkok",
    emoji: "🌊",
    area: "Erawan National Park: 200km northwest of Bangkok (3–3.5 hours by car); Kanchanaburi Province; Erawan Waterfall (7 tiers, named for 3-headed elephant of Hindu mythology); also in Kanchanaburi Province: Sai Yok National Park (Death Railway viaduct and waterfall); Gulf Coast: Hat Yao (Chonburi, 90 min), Laem Mae Phim (Rayong, 3 hours), Koh Samet (Rayong, 3.5 hours); Hin Dat Hot Springs (Kanchanaburi, 190km from Bangkok)",
    price: "Erawan National Park entry: ฿300 (foreigner), ฿30 (Thai); Erawan buses from Bangkok (Kanchanaburi bus station transfer): ฿250–350 total journey; Kanchanaburi day trip tour (from Bangkok): ฿1,200–2,000; Koh Samet ferry: ฿50 (from Ban Phe pier); Koh Samet National Park entry: ฿200 (foreigner); Hin Dat Hot Spring entry: ฿20; River Kwai Bridge: free (walk-through); JEATH War Museum: ฿40",
    why: "Bangkok's northwest (Kanchanaburi direction) and east (Rayong/Gulf direction) both offer nature escapes within day-trip distance: (1) Erawan Waterfall uniqueness: Erawan's seven-tiered emerald-green limestone waterfall (fed by the Khwae Yai River watershed) has natural pools at each tier for swimming; the lower tiers are larger and more accessible; the upper tiers (5–7) require hiking but reward with more intimate pools; fish nibbling at your skin in the clear pools is a distinctive sensory experience; (2) Tiger Cave (Tham Than Lot) at Erawan: within Erawan National Park, the Tham Than Lot cave system has a 1.4km passable section; the cave leads to an exit within the forest and requires a guide for the deepest sections; (3) Koh Samet for weekend beach: the closest significant beach destination to Bangkok (3.5 hours to Ban Phe pier, 30 minutes on boat); Koh Samet's white quartz sand and clear water (relative to Pattaya) makes it Bangkok's most popular quick beach escape; Hat Sai Kaew (main beach) is crowded on weekends; Ao Wai and Ao Kiu na Nok (southern beaches) are quieter; (4) Sai Yok National Park (Kanchanaburi): the Sai Yok Yai and Sai Yok Noi waterfalls within the park are combined with the Death Railway historic route (train from Kanchanaburi to Nam Tok, with the Wang Po Viaduct section over the River Kwai); this is Thailand's most historically significant railway journey; (5) Hin Dat Hot Springs: natural hot springs (40–50°C) at Hin Dat, 190km from Bangkok in Kanchanaburi Province; the springs flow directly into the river alongside cool water sections; a natural temperature-contrast bathing experience.",
    tip: "Gulf and western day trips from Bangkok: (1) Erawan timing: Erawan National Park caps daily visitor numbers; arriving before 9am (especially on weekends) ensures entry; weekday visits avoid crowds entirely; the park fills quickly on weekend public holidays; (2) Kanchanaburi+Erawan combination: Kanchanaburi town (Death Railway Bridge, war museums, JEATH museum) and Erawan Waterfall are 75km apart; combining both in one day requires an early start and private vehicle or pre-arranged tour; (3) Koh Samet weekend considerations: Bangkok residents flood Koh Samet on Friday–Sunday; prices (accommodation, food) are typically 30–50% higher on weekends; accommodation fills and the boat queues from Ban Phe become long; Monday–Thursday visits are dramatically more peaceful; (4) Gulf Coast driving (Rayong): the eastern seaboard route (Si Rat Expressway to Motorway 7) is straightforward by car; the Laem Mae Phim and Mab Phlong areas of Rayong have smaller beach communities (less developed than Pattaya and Koh Samet) with authentic Thai beach food; (5) Hot springs health context: Kanchanaburi hot springs are naturally hot (not temperature-controlled); spending more than 15–20 minutes in the hottest sections can cause overheating; bringing water and alternating with the cooler river sections manages the temperature exposure.",
  },
];

export function BangkokNationalParks() {
  return (
    <div className="rounded-2xl border border-emerald-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-emerald-700 mb-3">
        🌿 Bangkok national parks — Khao Yai wildlife, Kaeng Krachan birding & Erawan waterfall
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-emerald-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-emerald-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
