const SPOTS = [
  {
    name: "Bangkok's Stray Dog Situation & Community Dogs",
    emoji: "🐕",
    area: "Community (stray) dogs are found throughout Bangkok — near temples (wat dogs are traditionally cared for by temple communities), in residential neighborhoods, markets, and around major landmarks; temple communities and soi dog neighborhoods are the primary concentrations",
    price: "Soi Dog Foundation donation: any amount; Temple dog feeding (rice and scraps): ฿20–100; Vet care for community dogs (if helping): ฿500–3,000+ per treatment; Dog rescue fostering: time and food cost; SNR neutering programs: operated by NGOs (free for strays)",
    why: "Bangkok has one of Southeast Asia's largest urban stray dog populations — estimated at hundreds of thousands across the city. The Thai cultural relationship with these community dogs is complex and compassionate: Buddhist merit-making includes feeding stray dogs and cats; temple communities (wat) have traditionally served as sanctuary spaces where soi dogs are cared for by monks and temple staff; neighborhood residents often adopt informal community dog caretaker roles. The Soi Dog Foundation (a major international NGO operating throughout Thailand) runs large-scale Trap-Neuter-Return programs and coordinates with Bangkok's Metropolitan Administration on population management. Bangkok's attitude toward stray dogs differs significantly from Western approaches: euthanasia programs face strong resistance from both the religious community (Buddhist precepts against killing) and the public; consequently, population control relies on sterilization programs rather than culling. Visitors frequently encounter well-fed, relatively healthy community dogs near Bangkok's major temples (Wat Pho, Wat Phra Kaew area, local neighborhood temples) — these dogs often have an established territory and temperament recognizable to regular visitors.",
    tip: "Bangkok community dog interaction: (1) Approaching temple dogs: temple dogs are generally accustomed to human interaction but should be approached calmly and without running, which triggers chase instincts; (2) Feeding community dogs: street food vendors and market stalls often have scraps available specifically for feeding community dogs; participating in this feeding tradition connects with Bangkok's merit culture; (3) Rabies awareness: while Bangkok's urban dog population has been partially vaccinated through municipal programs, rabies is technically present in Thailand; a dog bite or scratch should be treated immediately at any Bangkok hospital's emergency room for post-exposure prophylaxis; pre-exposure rabies vaccination before visiting Thailand is advisable for those planning significant dog interaction; (4) Soi Dog Foundation volunteer opportunities: the Soi Dog Foundation (operating primarily from Phuket but with Bangkok connections) accepts volunteers for shelter and fostering programs; (5) Adoption: the Soi Dog Foundation and several Bangkok-based rescue groups facilitate international adoption of Thai rescue dogs; the process involves health testing, export permits, and coordination that typically takes 2–4 months.",
  },
  {
    name: "Bangkok Dog-Friendly Venues & Pet Culture",
    emoji: "🦮",
    area: "Dog-friendly cafés and parks: Chao Phraya riverside parks (early morning dogs allowed), Lumpini Park (early morning dog walking area), Benchakitti Park dog zone, Banyan Tree Rooftop (dog-friendly hotel), and specialty dog cafés in Ekkamai and Thonglor",
    price: "Dog-friendly café entry: ฿100–300 per dog; Dog grooming (Bangkok): ฿300–1,500; Dog spa/wash session: ฿500–2,000; Dog hotel/daycare: ฿500–1,500/day; Premium dog hotel: ฿1,500–4,000/night; Dog accessories at Chatuchak: ฿100–5,000",
    why: "Bangkok's companion dog culture has grown substantially among the middle and upper-middle class Thai urban population — creating an emerging ecosystem of dog-friendly venues, specialty pet services, and luxury pet products. Bangkok's dog culture is visible in: (1) Dog cafés and dog-friendly spaces — a category of café where small companion dogs (usually Shih Tzu, Pomeranian, French Bulldog, and similar breeds) are resident attractions or where customers can bring their dogs; (2) Lumpini and Benchakitti Parks — early morning (6–9am) Bangkok park culture includes a significant dog-walking community; dogs are technically supposed to be leashed but enforcement is selective; (3) Dog grooming industry — Thai dog grooming culture draws from both traditional grooming and the elaborate 'creative grooming' (dogs dyed in pastel colors, styled in elaborate cuts) popular in East Asian countries; Bangkok has multiple grooming salons that offer both functional and fashion grooming; (4) Dog hotels and daycare — parallel to Western pet hotel industries; premium Bangkok dog hotels offer webcam monitoring, individual runs, and special care packages; (5) Pet products market — Chatuchak Market's Weekend Market has a large pet products section; Bangkok's malls and online retailers stock international and Thai domestic pet food and accessory brands.",
    tip: "Bangkok dog owner and dog lover practical guide: (1) Traveling to Bangkok with a dog: Thailand requires pet import health certificate, rabies vaccination certification (minimum 30 days before travel), and microchip registration; advance coordination with a Bangkok veterinary practice (most large international vet clinics handle import documentation) simplifies the process; (2) Bangkok veterinary care: Bangkok has multiple international-standard veterinary clinics (Bangkok Animal Hospital, Siam Animal Hospital, and university veterinary hospitals) offering comprehensive pet care including surgery, diagnostics, and specialist referral; (3) Dog breeds in Bangkok: Bangkok's dog culture is heavily weighted toward small companion breeds and popular imported breeds (French Bulldog, Shih Tzu, Golden Retriever, Corgi); large active breeds face practical challenges in Bangkok apartment living; (4) Dog accessories shopping: Chatuchak Weekend Market's pet section has everything from basic accessories through specialty Thai-designed pet products at prices below Bangkok mall retail; (5) Dog photography in Bangkok: Bangkok's backdrops (temple entrances, canal paths, heritage architecture) create exceptional pet photography opportunities; the early morning temple area (before 8am) has low crowds and beautiful light for dog portrait photography.",
  },
  {
    name: "Bangkok Cat Cafés & Feline Culture",
    emoji: "🐱",
    area: "Cat cafés throughout Bangkok: Caturday (Ekkamai), Catcafé Bangkok (Ari), Purrfect (Siam area), and others across the city; Bangkok's Japanese-influenced cat café scene concentrates in Thonglor, Ekkamai, and Ari neighborhoods",
    price: "Cat café entry: ฿150–350 (usually includes drink); Food and drink at cat café: ฿100–350; Cat café membership: ฿500–1,500/month; Thai cat rescue donation: any amount; Cat grooming service: ฿500–1,500",
    why: "Bangkok's cat café scene imports the concept from Japan and Korea — spaces where well-socialized resident cats are housed in café environments where customers pay entry to interact with them while consuming food and beverages. Bangkok's cat cafés have developed local character alongside the Japanese-originated concept: Thai-operated cat cafés often house rescue cats from Bangkok's substantial stray population, giving the cat café format both entertainment and social welfare dimensions. Bangkok's temple cat culture parallels the dog situation — many temple communities include resident cats alongside dogs, with Buddhist merit-making extending to cat feeding. Bangkok's middle-class cat ownership culture has also grown — the practical considerations of apartment living make cats more manageable pets than dogs in Bangkok's dense urban housing, and the Korean and Japanese influence (where cat ownership has cultural cachet) drives companion cat ownership trends among younger Bangkok residents. Bangkok's cat rescue and foster community operates largely through Facebook groups where cats rescued from the street or surrendered by owners are fostered and rehomed.",
    tip: "Bangkok cat café and cat culture guide: (1) Cat café hygiene standards: Bangkok's established cat cafés maintain vaccination, regular health checks, and grooming standards for their resident cats; the cats in reputable venues are well-socialized and healthy; (2) Cat café etiquette: the same as Japanese cat café norms — no waking sleeping cats, no picking up cats against their will, no flash photography in some venues; following the house rules creates a better experience for both humans and cats; (3) Instagram cat culture: Bangkok's cat café Instagram culture is extremely active; following popular Bangkok cat café accounts reveals new openings and special events (holiday-themed decorations, new cat arrivals); (4) Cat rescue community: Bangkok's Facebook-based cat rescue community (Bangkok Cats, Stray Cat in Thailand, multiple neighborhood-specific groups) is the primary network for fostering and adopting rescued Bangkok cats; (5) Khao Manee cats: Thailand's own native cat breed, the Khao Manee (white cat with odd-colored eyes), is associated with Thai royalty and good fortune; specialty breeders exist in Bangkok, and the cats appear in some cat cafés — meeting one is considered auspicious in Thai folk tradition.",
  },
];

export function BangkokDogCulture() {
  return (
    <div className="rounded-2xl border border-amber-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-amber-700 mb-3">
        🐕 Bangkok animal culture — community dogs, dog-friendly venues & cat cafés
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-amber-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-amber-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
