const SPOTS = [
  {
    name: "Koh Si Chang — Bangkok's Closest Island Escape",
    emoji: "🏝️",
    area: "Koh Si Chang: 2.5–3 hour journey from Bangkok (bus + ferry from Si Racha, Chonburi province); small island 12km² in the Gulf of Thailand; ferry from Si Racha Pier; accommodation on island: several budget guesthouses and small resorts; transport on island: tuk tuks and motorbike rental; historical significance: former royal summer residence (Rama IV, Rama V)",
    price: "Bus from Ekamai to Si Racha: ฿100–150; Ferry Si Racha to Koh Si Chang (round trip): ฿100–200; Tuk tuk island tour (2–3 hours): ฿200–400; Motorbike rental (day): ฿200–350; Budget guesthouse room: ฿500–1,200/night; Restaurant seafood meal: ฿200–600",
    why: "Koh Si Chang is Bangkok's most underrated weekend escape — more authentic and less developed than Pattaya, closer than Koh Samet, and offering a glimpse into a Thailand without mass tourism: (1) Royal history: Koh Si Chang was King Rama V's (Chulalongkorn) summer residence; the Palace of Rama V (Phra Chudadhuj Palace) ruins with stunning coastal views are the island's main historical attraction; the island's royal history is well-documented but rarely visited by international tourists; (2) Working-class Thai island culture: Koh Si Chang's economy is based on industrial port activity (the offshore deep-water port serves Bangkok's container shipping) rather than tourism; this industrial-maritime identity means the island has preserved authentic Thai coastal town culture; (3) Chinese shrine community: the island has a significant Chinese-Thai population; the San Jao Phaw Khao Yai shrine (Phra Wihanrat cave temple, accessible by 360-degree stairs) is a major Buddhist-Chinese pilgrimage site visible from the sea; (4) Snorkeling and swimming: Hat Tham Phang (beach on the western side) offers clear Gulf of Thailand water with snorkeling when visibility is good (dry season best); the beach is small but uncrowded; (5) Seafood: Koh Si Chang's port-working community supports fresh seafood restaurants at prices significantly below Pattaya's tourist-inflated seafood prices.",
    tip: "Koh Si Chang practical navigation: (1) Si Racha transport: getting to Si Racha from Bangkok is straightforward — Ekamai Bus Terminal or Sai Tai Mai (Southern Bus Terminal) buses to Si Racha run every 30–60 minutes; the journey takes 1.5–2 hours; (2) Ferry schedule: Si Racha pier ferries to Koh Si Chang run frequently during daylight hours (approximately hourly); the last ferry from the island to Si Racha is typically 6pm; staying overnight avoids ferry timing pressure; (3) Tuk tuk island tour: Koh Si Chang's tuk tuks (three-wheeled vehicles) wait at the ferry pier and offer island circuit tours covering all major sites in 2–3 hours; negotiating a fixed price before departure avoids later pricing disputes; (4) Chinese New Year pilgrim traffic: Koh Si Chang's Chinese shrine is a major pilgrimage site during Chinese New Year (January–February); the island experiences significant visitor influx during this festival; avoiding CNY for a quiet visit is advisable; (5) Accommodation booking: accommodation on Koh Si Chang is limited; booking ahead (particularly for weekends and holidays) through Facebook messaging the guesthouses directly (most don't appear on major booking platforms) prevents arriving to no vacancy.",
  },
  {
    name: "Bang Saen Beach — Bangkok's Working-Class Beach Day",
    emoji: "🏖️",
    area: "Bang Saen Beach: 100km southeast of Bangkok (1.5–2 hours by car/bus via Highway 3), Chonburi Province; domestic Thai beach town with clear working-class Thai holiday atmosphere; adjacent to Bangsaen Marine Aquarium (government-operated) and Khao Sam Muk mountain park with sea views and monkey population",
    price: "Mini-bus from Ekamai to Bang Saen: ฿60–90; Beach umbrella and chairs rental: ฿100–200 for day; Seafood restaurant at Beach: ฿200–600/person; Grilled corn and beach snacks: ฿20–50; Day day admission at water park (if visiting): ฿250–500; Khao Sam Muk tuk tuk ride: ฿50–100",
    why: "Bang Saen beach provides a culturally authentic Thai beach experience that Pattaya's tourist industry can no longer offer: (1) Thai domestic beach culture: Bang Saen is a Thai beach for Thai families — the scene is exclusively Thai domestic tourism; extended family groups bringing their own food, Thai beach snack vendors (corn, grilled pork skewers, fresh fruit), Thai beach games, and Thai music from Bluetooth speakers create a beach experience without international tourist infrastructure; (2) Sand quality and water: Bang Saen has reasonable sand and typically safe swimming water (though water quality near Bangkok's coast is variable; checking air quality/water quality before visits is prudent); the beach extends roughly 2km in the main accessible stretch; (3) Khao Sam Muk: the small mountain overlooking Bang Saen (Khao Sam Muk, accessible by road) has a large macaque monkey population, coastal views, and a small shrine complex; the monkey management here is less controlled than tourist-oriented monkey temples — awareness of food items near monkeys is important; (4) Food culture: Bang Saen's seafood restaurants along the beachfront and inland serve Thai-price seafood in working-class Thai restaurant atmosphere; prices are noticeably lower than equivalent food in Pattaya or tourist beach resorts; (5) Weekend crowd management: Bang Saen is extremely popular with Bangkok's working-class families on weekends and Thai holidays; the beach becomes packed on these days; mid-week visits (if schedule allows) find a much emptier, more relaxed beach environment.",
    tip: "Bang Saen day trip planning: (1) Transport from Bangkok: mini-buses to Bang Saen depart from Ekamai Bus Terminal (Bangkok's eastern bus terminal) frequently; the journey on Highway 3 takes 1.5–2 hours depending on traffic; (2) Saturday morning traffic: getting out of Bangkok on Highway 3 Saturday morning involves Bangkok's weekend highway traffic; departing 6am avoids the worst congestion; (3) Beach umbrella and chairs: umbrella and chair rental from beach vendors (stationed along the beach) is the standard beach day setup; vendors approach beachgoers; agreeing on daily rate before setup prevents misunderstanding; (4) Water safety: Bang Saen's water is generally calm Gulf of Thailand (sheltered from ocean swell); the monsoon season creates occasional rip currents and warning flags; flagged swimming zone boundaries indicate lifeguard-monitored areas; (5) Return trip timing: mini-buses return from Bang Saen to Bangkok continuously; catching early afternoon transport (3–4pm) avoids weekend evening Bangkok traffic; Friday evening departures from Bangkok are most traffic-intensive and better avoided if possible.",
  },
  {
    name: "Koh Samet Weekend — Bangkok's Classic Beach Escape",
    emoji: "⛵",
    area: "Koh Samet: 3–3.5 hours from Bangkok (bus or car to Ban Phe pier, Rayong, then 30-min ferry); narrow elongated island 8km long with white quartz sand beaches; Hat Sai Kaew (main beach, most developed), Ao Phai (mid-island, popular backpacker), Ao Wai (south, quieter); national park fee applies",
    price: "Bus Bangkok–Ban Phe (Ekamai): ฿180–250; Ferry Ban Phe–Koh Samet (30 min): ฿80–200; National Park entry fee (foreigner): ฿200 per person; Budget guesthouse (Hat Sai Kaew): ฿500–1,500/night; Mid-range bungalow: ฿1,500–4,000/night; Full-service resort: ฿4,000–15,000/night; Seafood dinner: ฿300–800/person",
    why: "Koh Samet's white quartz sand beaches (some of the whitest in the Gulf of Thailand, due to the island's geological composition) and proximity to Bangkok make it the default weekend beach destination for Bangkok residents: (1) Beach sand distinction: Koh Samet's quartz sand is exceptionally fine and white — the beach quality here is genuinely superior to many Thai beaches; the island's geological composition (quartz deposits) produces the brilliant white sand; (2) Accessibility: Koh Samet is reachable in 3–3.5 hours total from Bangkok (versus 6–8 hours to Koh Samui, 5 hours to Koh Phi Phi by combined transport); it's the only decent-quality island within viable same-day round-trip distance; (3) Beach personality spectrum: Koh Samet's beaches range in character from Hat Sai Kaew (most developed, bars, restaurants, fire shows, international tourists) through mid-island coves (backpacker energy) to southern beaches (quieter, fewer facilities, longer walks from main ferry); choosing beach to match personal preference is the key planning decision; (4) National Park status: Koh Samet is inside Khao Laem Ya–Koh Samet National Park; the entrance fee (฿200 for foreigners) applies to all visitors; (5) Weekend occupancy: Koh Samet is seriously crowded on Bangkok long weekends and Thai public holidays; prices double and accommodation books weeks ahead; mid-week visits provide dramatically different experience.",
    tip: "Koh Samet trip optimization: (1) Accommodation booking horizon: for weekend visits, booking 2–4 weeks ahead is standard; for Thai public holiday weekends (Songkran, Loy Krathong, New Year), 4–6 weeks ahead or more; walk-in on holiday weekends is near-impossible; (2) Ao Wai and southern beaches: the southern beaches (Ao Wai, Ao Kaew, Ao Sang Thian) require longer island walking or motorbike/songthaew transport from the ferry pier but offer significantly more relaxed atmosphere than Hat Sai Kaew; the quality difference makes the extra 15–30 minutes worth it for non-party travelers; (3) Ban Phe pier transport: multiple ferry operators run between Ban Phe and Koh Samet with similar prices; the central pier (Tha Ban Phe) rather than the resort-operated private piers serves all public island beaches; (4) Rain forecast: the Gulf of Thailand's eastern coast (where Koh Samet sits) is sheltered from the southwest monsoon that affects Koh Samui and Gulf west coast differently; Koh Samet's weather pattern means the best weather is November–May (opposite of the Andaman coast); (5) National park hours: the national park fee checkpoint opens at 6am and closes at 6pm; arriving by ferry before 6am or after 6pm provides unofficial access without the fee (though this is technically incorrect); ferry operators arrive at any hour.",
  },
];

export function BangkokKohSiChang() {
  return (
    <div className="rounded-2xl border border-cyan-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-cyan-700 mb-3">
        🏝️ Bangkok beach escapes — Koh Si Chang, Bang Saen day trip & Koh Samet weekend
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-cyan-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-cyan-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
