const SPOTS = [
  {
    name: "Bangkok Durian Culture — The King of Fruits, Bangkok Markets & How to Buy",
    emoji: "🌵",
    area: "Bangkok durian sources: Chinatown Yaowarat Road (durian vendors evening, particularly near Tha Tien); Or Tor Kor Market (Chatuchak, highest quality premium durian, pre-cut, air-conditioned); Pak Klong Talad flower market area (also fruit, dawn); Chatuchak Weekend Market fruit section; Suan Luang Rama IX Park area fruit markets; Supermarkets: Gourmet Market (Siam Paragon, packaged premium durian); Tops Market (fresh and frozen sections); seasonal: Monthong and Chanee durian peak season is April–August in Thailand; transportation: durian is banned in many Bangkok hotels and the BTS Skytrain (by policy/social convention); Grab drivers may decline durian passengers",
    price: "Monthong durian (whole, fresh): ฿150–600/kg depending on season; Chanee durian: ฿80–300/kg; Musang King durian (Malaysian variety, imported): ฿400–1,500/kg; Premium frozen durian flesh (Or Tor Kor): ฿200–500 for packaged portion; Durian sticky rice (khao niao durian): ฿80–150/portion; Pre-cut durian (mall): ฿150–400/box; Durian ice cream: ฿60–150; Durian cake/crepe: ฿100–250",
    why: "Durian is Bangkok's most culturally significant — and polarizing — fruit: (1) Thailand's durian dominance: Thailand produces approximately 1 million tonnes of durian annually, primarily for export to China (China consumes 60%+ of Thailand's durian exports); the export demand from China has dramatically increased Thai durian prices over 2015–2025; farmers switched from rice to durian across Southern and Eastern Thailand; (2) Monthong vs. other varieties: Monthong ('golden pillow') is Thailand's most commercially grown durian variety; its thick flesh, mild smell, and sweet/creamy flavor make it the most export-friendly and beginner-accessible variety; Chanee ('gibbon') is more aromatic with complex bitter notes favored by experienced durian consumers; the Malaysian Musang King (sold at premium in Bangkok) has a more intense flavor profile that is increasingly available in Bangkok's premium markets; (3) How to select a durian: selecting a good durian requires holding the fruit and shaking it to hear whether the seeds and flesh are loose (indicating ripeness); a ripe durian emits fragrance from the seams; a dull, hollow knock when tapped suggests dry flesh; buying pre-opened durian at markets allows smell and visual inspection; Or Tor Kor's pre-cut packaged durian removes this uncertainty; (4) Thai durian eating culture: eating durian with sticky rice (khao niao durian) is Bangkok's primary fresh durian street food format; the combination of coconut-sweetened sticky rice and fresh durian flesh is a Thai dessert classic; durian smoothies and durian crepes (the paper-thin crepe variety common in Bangkok) are café-format ways to consume durian; (5) The smell controversy: durian's sulfurous, onion-custard aroma (appealing to fans, deeply offensive to non-fans) has generated Bangkok's durian etiquette culture; hotel policies against room durian consumption are common; the BTS Skytrain bans durian implicitly via its general food/drink ban; taxis may refuse passengers carrying whole durian.",
    tip: "Bangkok durian experience guide: (1) First-time durian protocol: for first-time durian tasters, start with Monthong (least intense, sweetest); choose pre-cut and vacuum-packaged durian from Or Tor Kor Market or Gourmet Market (quality-controlled, no selection required, lower entry barrier); try a small portion in an open-air environment (not enclosed spaces); durian taste experience is divisive — have no expectation either way; (2) Or Tor Kor Market for premium: Or Tor Kor Market (next to Chatuchak, MRT Kamphaeng Phet) sells Thailand's highest-quality pre-cut durian in air-conditioned, modern market context; pre-cut packages allow tasting without whole-fruit purchase commitment; or buying a single packaged portion (฿200–400) is practical for one-time visitors; (3) Durian season awareness: Bangkok has durian year-round via cold-chain logistics, but peak fresh season (April–August) produces best quality and lowest prices; off-season durian relies more on refrigeration and may be less fresh; (4) Hotel durian: most Bangkok hotels prohibit durian in rooms; consuming durian in hotel rooms violates hotel policy and may result in cleaning charges; Or Tor Kor market's outdoor seating and parks near fruit market areas are the practical places to eat purchased durian; (5) Durian versus mangosteen: Thai food legend says mangosteen (the 'queen of fruits') counteracts the heating properties of durian (the 'king'); the two fruits are often sold together at Bangkok markets during durian season; whether or not the cooling-heating interaction is physiologically real, mangosteen's flavor (sweet-sour, gentle, universally appealing) provides a pleasant contrast after durian.",
  },
  {
    name: "Bangkok Tropical Fruits — Mango Season, Rambutan & The Full Fruit Guide",
    emoji: "🥭",
    area: "Bangkok fruit purchasing locations: Or Tor Kor Market (premium, near Chatuchak); Pak Klong Talad (dawn, wholesale prices); MBK food court fruit stalls; airport shops (packaged fruit for departure); roadside fruit cart vendors throughout Bangkok; supermarkets (Tops, Gourmet Market) for cleaned and packaged; Chatuchak Weekend Market fruit section; hotel breakfast buffets (good variety for first-morning exposure); seasonal overlap: many Thai fruits are year-round but peak season dramatically improves quality and value",
    price: "Mango (fresh, peak season April–May): ฿40–100/kg; Nam Dok Mai mango (premium variety): ฿80–200/kg; Mangosteen (peak May–September): ฿60–150/kg; Rambutan (peak June–August): ฿30–80/kg; Longan (peak July–August): ฿50–120/kg; Dragon fruit (red/white, year-round): ฿40–100/kg; Lychee (peak April–June): ฿80–200/kg; Rose apple (chompu): ฿40–100/kg; Sapodilla (lamut): ฿30–80/kg; Mango sticky rice (khao niao mamuang): ฿60–120/portion; Packaged cut fruit box: ฿50–150",
    why: "Bangkok's tropical fruit ecosystem is one of the world's most diverse and accessible: (1) Mango's role in Bangkok food culture: Thailand's Nam Dok Mai mango (literally 'flower nectar') is one of the world's finest mango varieties; the variety's fiber-free, sweet-sour balance, and distinctive fragrance reach peak quality in April–May; mango sticky rice (khao niao mamuang) — ripe mango over glutinous sticky rice with coconut milk — is Bangkok's most universally loved dessert; some Bangkok mango sticky rice vendors (Mango Tango at Icon Siam, Huai Khwang market vendors) achieve cult status; (2) Mangosteen: the mangosteen (mangkhut) has a distinctive visual — the deep purple shell revealing perfectly segmented white flesh — that becomes unforgettable for first-time eaters; the flavor (sweet-sour-floral, universally appealing) makes it Bangkok's most consensus 'best fruit' for international visitors; (3) Seasonal diversity: Bangkok's tropical and subtropical positioning (13° N latitude, warm year-round) means some tropical fruit is always in season; the Bangkok fruit calendar is: mangoes (April–May), durian (April–August), rambutan/longan/lychee (May–August), mangosteen (May–September), rose apple (year-round), banana (year-round), papaya (year-round), coconut (year-round); (4) Coconut culture: fresh coconut (young green coconut with coconut water, or mature coconut for flesh) is sold throughout Bangkok as a street food drink; roadside vendors drill and insert a straw (฿30–60); the Coconut Farm (various locations) serves fresh coconut ice cream in coconut shells as a Bangkok food trend; (5) Fruit as Bangkok gift culture: Thai people commonly bring cut or bagged fruit as gifts when visiting people; Or Tor Kor Market's high-quality packaged fruit (pomelos, mangosteens, rambutans in gift-ready boxes) is Bangkok's most practical premium edible gift for international visitors.",
    tip: "Bangkok tropical fruit practical guide: (1) Mango sticky rice best timing: Bangkok's mango sticky rice is best April–June (peak mango season); outside this window, the mango quality drops while the preparation remains excellent; ordering mango sticky rice in November–February uses refrigerated or off-season mangoes; (2) Fruit freshness signals at markets: at Bangkok street fruit vendors and markets, pre-cut fruit in sealed plastic is the safest purchase for freshness verification; whole fruit requires knowledge to select; the simplest approach is buying from Or Tor Kor Market where quality control is managed by the market; (3) Rambutan vs. lychee confusion: first-time visitors often confuse rambutan (the hairy red ball) with lychee (smoother red exterior); rambutan flesh is chewier and less sweet than lychee; both are excellent but distinct; (4) Banana varieties: Bangkok markets sell 20+ banana varieties (Thailand has 30+ recognized varieties); the tiny finger-banana (kluay nam wa) is sweeter and more fragrant than the large Cavendish banana most Western visitors recognize; trying different Bangkok banana varieties is an interesting comparison; (5) Food allergy awareness: tropical fruit allergies (particularly latex-fruit syndrome affecting those with latex allergies — avocado, banana, kiwi cross-reaction group) are worth noting; papaya is a common allergen for people with grass pollen sensitivity; mango skin contains urushiol (same as poison ivy) and can cause contact dermatitis in sensitive individuals (eat the flesh, not the skin).",
  },
  {
    name: "Bangkok's Spice Market & Thai Herb Culture — Lemongrass, Galangal & More",
    emoji: "🌿",
    summary: "Bangkok's spice and herb culture underlies all Thai cuisine and offers visitors edible and botanical education: (1) The foundational Thai aromatics: Thai cooking's foundation (used in most Thai curry pastes, soups, and stir-fries) consists of lemongrass (ta-khrai), galangal (kha), kaffir lime leaves (bai makrut), Thai basil (horapa), coriander/cilantro (pak chi), garlic (kratiam), shallots (hom daeng), and fresh chilies (prik); this aromatic foundation distinguishes Thai cooking from Chinese and other Asian cuisines; fresh ingredients are non-negotiable in authentic Thai cooking (dried substitutes are considered inferior); (2) Bangkok's spice market: Bangkok's dedicated spice market area (Nakhon Kasem, 'Thieves' Market', in Chinatown, and adjacent Sampheng Lane wholesale market) has wholesale spice vendors; the Pak Klong Talad market also has herb and spice stalls; Bangkok cooking classes include herb and spice identification as standard curriculum component; (3) Thai curry paste varieties: Thailand's curry pastes (kaeng) each have distinct spice compositions; green curry (kaeng khiao wan) uses green chilies and sweet basil; red curry (kaeng phet) uses dried red chilies; Massaman curry (kaeng massaman, Southern Thai/Malay-influenced) uses cumin, cardamom, and star anise creating the most Middle Eastern-influenced Thai flavor profile; Panang curry uses peanuts; each curry paste is best understood by tasting the distinctions; (4) Galangal vs. ginger: galangal (kha) and ginger look similar but are distinct: galangal has a more intense, piney-citrus aroma versus ginger's warm-sharp profile; galangal is used extensively in Thai cooking (tom kha soup) and cannot be substituted with ginger; understanding this distinction is fundamental to understanding Thai flavor; (5) Thai herb garden tourism: some Bangkok botanical gardens and cooking schools maintain Thai herb gardens with labeled specimens; the Queen Sirikit Botanical Garden (northern Bangkok, Ngam Wong Wan area) and Chatuchak plant market have Thai herb plant vendors; buying herb plant specimens is a way to bring Bangkok food culture home to countries that permit plant imports.",
    area: "Bangkok herb and spice sources: Nakhon Kasem (Chinatown spice area); Pak Klong Talad (fresh herbs, dawn hours best); Or Tor Kor Market (premium fresh herb bundles); Chatuchak Weekend Market (plant section, JJ Market); supermarkets (Tops, Gourmet Market) for packaged/frozen herbs; Thai cooking class kitchens (herb identification component standard at Baipai Thai Cooking School, Blue Elephant Cooking School); Mahachai market (30km south, authentic fishing town market, extraordinary seafood + Thai herb supply chain context)",
    price: "Fresh lemongrass bundle: ฿10–30; Fresh galangal (100g): ฿20–50; Kaffir lime leaves (bunch): ฿10–25; Thai basil bunch: ฿10–20; Fresh green/red chilies (100g): ฿10–40; Spice paste kit (ready-made for cooking): ฿80–200; Premium packaged Thai spice set (souvenir): ฿200–500; Cooking class with herb garden tour: ฿1,200–2,500; Herb plant (lemongrass, pandan): ฿50–200 at Chatuchak plant market",
    tip: "Bangkok herb and spice exploration guide: (1) Cooking class herb identification value: Bangkok's Thai cooking classes (Baipai, Blue Elephant, Oriental Hotel, Chef Num) systematically introduce Thai herbs before cooking begins; this structured introduction to 10–15 Thai aromatics with smell/taste comparison is more educational than independent market exploration; cooking classes are one of Bangkok's best value food experiences for the knowledge density; (2) Fresh vs. dried herb quality: insist on fresh herbs in Bangkok cooking; dried lemongrass, dried galangal, and dried kaffir lime are significantly inferior to the fresh versions widely available; frozen kaffir lime leaves (sold in sealed bags at supermarkets) retain flavor better than dried; fresh is always first choice in Thailand; (3) Herb storage for travel: fresh Thai herbs can be stored for 1–2 weeks in refrigerator water (like flowers); bringing fresh lemongrass, galangal, or kaffir lime leaves to home countries is subject to agricultural import regulations; check your country's biosecurity rules; (4) Pandan (bai toey): pandan (screwpine leaf) is an underappreciated Thai aromatic deserving special mention; the sweet, vanilla-coconut aroma of pandan appears in Thai desserts (pandan-wrapped chicken, pandan sticky rice, pandan cake/cupcakes) and pandan-flavored beverages; fresh pandan is widely available at Bangkok markets; (5) Thai chili varieties and heat management: Thailand has over 20 chili varieties used in cooking; prik khi nu ('bird's eye chili') is the small, extremely hot chili (50,000–100,000 Scoville) used in Thai cooking; prik num (banana chili) is mild; understanding Bangkok restaurant ordering phrases ('mai phet' = not spicy; 'nit noi' = a little spicy; 'phet nit noi' = slightly spicy) prevents heat miscommunication.",
  },
];

export function BangkokDurianFruit() {
  return (
    <div className="rounded-2xl border border-yellow-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-yellow-800 mb-3">
        🌵 Bangkok tropical produce — durian king of fruits, mango season & Thai herb culture
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-yellow-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-yellow-800">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-yellow-800">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
