const TOPICS = [
  {
    title: "Bangkok on Instagram & TikTok — Best Photo Spots, Reels Content & Thai Creator Culture",
    emoji: "📸",
    summary: "Bangkok generates more Instagram geotag photos than virtually any other Asian city and has an active Thai social media creator economy: (1) Bangkok's Instagram-friendliness: Bangkok has an unusually high concentration of photogenic content — ornate Buddhist temples, neon-lit Chinatown alleys, rooftop skylines, colorful floating markets, street food preparation in dramatic light, and elaborate hotel interiors; the city's 24-hour activity cycle means good photography conditions at multiple times of day; (2) Most-photographed Bangkok locations (geotagged frequently): Wat Pho (temple of Reclining Buddha) — for architectural symmetry and intimate temple scale; Wat Arun from the river — particularly at sunrise or blue hour (east-facing façade receives morning light); Chinatown Yaowarat Road at night — neon-lit food vendors; Icon Siam interior — modern Thai luxury design; Bangkok rooftops (King Power MahaNakhon, Vertigo Moon Bar) — city skyline; Bang Krachao cycling routes — green against urban backdrop; (3) TikTok Thailand: Thailand has one of Southeast Asia's highest TikTok penetration rates; Thai TikTok content (particularly food content, beauty trends, and Thai celebrity culture) generates substantial regional engagement; creating Bangkok TikTok content (street food reactions, temple visits, Thai product hauls) appeals to Thai and international audiences; Bangkok-based TikTok creators have significant English-language followings; (4) Thai social media landscape: LINE is Thailand's dominant messaging platform (not WhatsApp); Facebook remains important for Thai community groups and local business; YouTube Thai-language content market is significant; Twitter/X has an active Thai political and popular culture community (Thai Twitter has historically been among the most active in Asia per capita); (5) Thai Instagram food culture: Bangkok's food photography culture (the practice of photographing food before eating, setting up multiple dishes aesthetically) is extremely active; restaurant operators in Bangkok optimize for 'Instagrammable' presentations; the Kafe de Baan Silom, Nara Thai Cuisine, and flower café format restaurants generate consistent Instagram content; Bangkok café interior design specifically targets the social media documentation market.",
    action: "Instagram geotag Bangkok search for current trending location; TikTok hashtags #bangkokfood #bangkokstreetfood #bangkoktemple for inspiration; Google Maps photo section at specific locations for preview of photographic potential; Bang Krachao cycling tour through Green Lung for content distinct from urban Bangkok; Chinatown Yaowarat Road after 7pm for optimal food stall neon photography.",
  },
  {
    title: "Bangkok Slang & Thai Internet Culture — What Thai People Actually Say Online",
    emoji: "💬",
    summary: "Thai internet language and slang represents a distinct digital culture with specific characteristics: (1) Thai script on the internet: Thai script (44 consonants, 32 vowels, 4 tone marks, no spaces between words) creates distinctive text aesthetics; Thai people online mix Thai script with romanized phonetics (used when Thai keyboard is unavailable), numbers as letters (5 = 'ha', the Thai laugh), and English loanwords; (2) Thai number slang: '555' (ha ha ha) is the Thai internet equivalent of 'LOL' — the number 5 in Thai is 'ha'; '555' appearing in any Thai online context means the person found something funny; this is one of the first things visitors notice reading Thai social media; (3) Common Thai phrases for social situations: key phrases visitors encounter: 'Sanuk' (สนุก) — fun, enjoyable (the Thai cultural emphasis on fun as a life value); 'Mai pen rai' (ไม่เป็นไร) — never mind/no problem (Thailand's famous laid-back phrase); 'Jai yen yen' (ใจเย็นๆ) — calm down/keep your heart cool (emotional regulation advice); 'Suay' (สวย) — beautiful (careful: 'suay' with different tone means 'unlucky'); 'Jing jing' (จริงๆ) — really/seriously (emphasis intensifier); (4) Thai celebrity and K-pop intersection: Thailand's entertainment culture heavily overlaps with Korean entertainment (K-pop, K-drama); Thai fans of K-pop groups are highly active online; Thai BNK48 (local J-pop franchise) has passionate fan communities; Thai YouTubers and TikTokers covering Korean culture generate substantial viewership; (5) Thai Twitter (now X) character: Thai Twitter has historically been notable for activism, fan communities (particularly around K-pop), and rapid viral spread; Thai Twitter users organize real-world charitable actions (fundraisers, mutual aid) that originate on the platform; political discussions on Thai Twitter are active given periodic Thai political turbulence; visiting Bangkok during political sensitivity periods may reveal active Thai Twitter discourse.",
    action: "LINE app download for communicating with Thai contacts (essential for Bangkok living and business); Pantip.com for Thai-language community forum discussions on topics from tech to lifestyle; Blockdit for Thai-language long-form content and articles; following Thai Instagram food accounts (@bangkokfoodie, specific Bangkok food bloggers) for current trending restaurant recommendations; Thai Google Maps reviews (written in Thai) often have more reliable restaurant ratings than English-language reviews.",
  },
  {
    title: "Bangkok's Influencer Economy — Content Creator Hotels, Collaborations & Media Scene",
    emoji: "🎬",
    summary: "Bangkok has a developed influencer and content creator commercial ecosystem: (1) Bangkok hotel influencer collaborations: Bangkok's hotel market (particularly the high-competition boutique and luxury segments) actively seeks Instagram and TikTok creator collaborations; content creators with followings above 10,000 (micro-influencer level) can approach Bangkok hotels for complimentary stays in exchange for documented social media content; Bangkok hotels (particularly in Charoen Krung boutique area and riverside properties) have dedicated PR contacts for influencer partnerships; (2) Bangkok food tour operators and creators: Bangkok's food tour operators (Mark Wiens / Migrationology, various local guides) were among the first to develop food content creator businesses in Asia; the model has expanded to hundreds of Bangkok-based food content creators across platforms; (3) Production houses in Bangkok: Bangkok has a substantial commercial production industry (Thai advertising, regional film/TV production); international brands (particularly in beauty, fashion, and F&B) produce Asian market content in Bangkok due to production quality, diversity of locations, and cost advantages; Thai production companies provide director, DP, and crew services for international projects; (4) Google Thailand rankings: Bangkok is consistently among the world's most Googled tourist destinations; 'Bangkok restaurant,' 'Bangkok temples,' 'Bangkok nightlife,' and 'Bangkok travel guide' drive enormous search volume; content creators focusing on Bangkok travel content have established search audiences; (5) YouTube Thai-language market: Thai-language YouTube content is a significant market; top Thai YouTubers have 10M+ subscribers; Bangkok-based content covers gaming, beauty, food, comedy, and lifestyle; Thai YouTube ad rates have increased as the Thai advertiser market has developed; international creators making Thai-language content (or English content about Thailand) can access this growing market.",
    action: "Influencer marketplace platforms: Tellscore (tellscore.com, Thailand's largest influencer platform) for Bangkok-based creator collaboration; MGCC (Media Group Content Creator) for Thailand market; hotel PR contacts: email the marketing or PR department of target Bangkok hotels directly with media kit; Bangkok production studios: RDG Studio, One Cool Studio for commercial production contacts; Thailand Influencer Awards (annual) for industry landscape understanding.",
  },
];

export function BangkokSocialMedia() {
  return (
    <div className="rounded-2xl border border-rose-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-rose-700 mb-3">
        📸 Bangkok digital culture — Instagram photo spots, Thai internet slang & influencer economy
      </div>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-rose-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-rose-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
