const SPOTS = [
  {
    name: "Bangkok's International Hospitals — Bumrungrad, Samitivej & Bangkok Hospital",
    emoji: "🏥",
    area: "Top Bangkok international hospitals: Bumrungrad International Hospital (Sukhumvit Soi 3, 580 beds, JCI-accredited, 58 specialty centers); Samitivej Sukhumvit Hospital (Sukhumvit Soi 49); Bangkok Hospital (multiple locations — Bangkok Hospital Medical Center in New Phetchaburi area is the largest); Vejthani Hospital (Ladprao area, major international unit); Phyathai Hospital (multiple locations); BNH Hospital (Silom area, smaller, high international patient focus); Sikarin Hospital (Ekkamai area); Paolo Hospital (multiple locations across Bangkok)",
    price: "Specialist outpatient consultation: ฿800–3,000; Emergency room visit: ฿2,000–8,000; Blood test panel (comprehensive): ฿2,000–6,000; X-ray: ฿500–2,000; MRI: ฿8,000–25,000; CT scan: ฿5,000–18,000; Overnight hospital stay (single room): ฿6,000–18,000/night at international hospitals; Day surgery (outpatient): ฿15,000–80,000 depending on procedure; Annual health checkup (comprehensive): ฿5,000–15,000",
    why: "Bangkok's private international hospital sector is one of Asia's most developed and provides high-quality care at significant cost savings vs. Western prices: (1) JCI accreditation: Bumrungrad and Bangkok Hospital hold Joint Commission International (JCI) accreditation — the international gold standard for hospital quality; JCI requires comparable standards to major US and European hospitals in terms of protocols, safety, and outcomes; (2) Medical tourism economy: Bangkok is the world's most visited city for medical tourism; Bumrungrad Hospital alone treats over 1 million patients annually (approximately 40% international); major origin countries for medical tourism include the Middle East (Saudi Arabia, UAE, Oman), US, UK, Japan, Germany, Myanmar, and Cambodia; (3) Cost comparison to Western countries: representative Bangkok international hospital costs vs. US: knee replacement surgery Bangkok ฿450,000–700,000 (US: US$30,000–50,000); heart bypass surgery Bangkok ฿700,000–1,200,000 (US: US$100,000–150,000); dental implant ฿35,000–65,000 per implant (US: US$3,000–6,000); (4) Doctor quality: Bangkok's major international hospitals have physicians trained at Thai and international medical schools; many senior physicians have additional training or certification from US, UK, Australian, or Japanese institutions; English proficiency is standard at Bumrungrad and Bangkok Hospital (less consistent at smaller private hospitals); (5) Appointment process: Bumrungrad and Bangkok Hospital accept walk-in patients but appointment scheduling (via hospital app, website, or phone) reduces wait times; emergency rooms are true emergency rooms with triage; non-emergency walk-ins to international hospitals may wait 1–3 hours during peak times.",
    tip: "Bangkok healthcare practical guidance: (1) Insurance pre-authorization: if using international health insurance (Cigna, AXA, Allianz, BUPA, Pacific Cross), requesting a guarantee of payment (GOP) letter from your insurer before non-emergency procedures prevents having to pay upfront and claim; Bumrungrad and Bangkok Hospital have dedicated insurance desks; (2) Public hospitals for residents: Bangkok's public hospitals (Siriraj Hospital, Chulalongkorn Hospital, Ramathibodi Hospital) provide equal or superior care in specialized areas (Siriraj has Thailand's strongest medical research reputation) at government-regulated prices; public hospital outpatient consultations cost ฿50–200; (3) After-hours pharmacy: Bangkok international hospitals have 24-hour pharmacies; major 24-hour pharmacies exist at major hospitals; some Boots Pharmacy locations maintain extended hours; (4) Carrying health documentation: traveling with a copy of existing medical history, current medication list (with generic names, not brand names only), and blood type facilitates care in emergency situations; (5) Language in smaller hospitals: smaller Bangkok private hospitals outside the major chains may have limited English capability; using hospital translation apps (Google Translate camera mode for Thai medical documents) and carrying pre-written Thai phrases for medical emergencies reduces communication barriers.",
  },
  {
    name: "Bangkok Dental Care — World-Class Dentistry at Fraction of Western Prices",
    emoji: "🦷",
    area: "Major Bangkok dental hospitals: Bangkok Dental Spa (multiple locations, known for comfort dentistry); BNH Dental Center (Silom area); Bangkok International Dental Center (BIDC, Phayathai area, largest dedicated dental hospital in Asia); Bumrungrad International Hospital dental department; dental clinics: Thantakit International Dental Center; Thai dental clinic network: Dental World Bangkok; specialty clinics: numerous implant, orthodontics, and cosmetic dentistry specialty practices in Sukhumvit, Silom, and Phrom Phong areas",
    price: "Dental checkup and cleaning: ฿800–2,000; Dental X-ray (panoramic): ฿500–1,500; Tooth extraction (simple): ฿500–1,500; Root canal treatment: ฿4,000–12,000 per tooth; Dental implant (single, including crown): ฿35,000–65,000; Full upper/lower dental implant arch (All-on-4 concept): ฿250,000–550,000; Porcelain veneer: ฿8,000–18,000 per tooth; Teeth whitening: ฿5,000–15,000; Dental crown (porcelain-fused-to-metal): ฿6,000–12,000; Invisalign treatment: ฿80,000–200,000",
    why: "Bangkok dental tourism is one of the world's most established dental tourism markets: (1) Cost advantage: Bangkok dental care costs approximately 30–70% less than comparable treatment in the UK, Australia, the US, or Scandinavia; the most dramatic savings are on implants, veneers, and All-on-4 full arch restorations where Bangkok costs are 25–40% of Western prices for equivalent quality; (2) BIDC (Bangkok International Dental Center): BIDC (in Phayathai area) claims to be Asia's largest dedicated dental hospital; the facility has multiple specialized departments, in-house dental laboratories for same-day or next-day crowns and veneers, and handles complex cases that might take months in Western countries in compressed 1–2 week stays; (3) Technology currency: Bangkok's major dental facilities use current technology (3D CBCT scanning for implant planning, CAD/CAM crown milling, digital smile design software, laser dentistry) equivalent to or exceeding many Western practices; (4) Dental tourism planning: the most common Bangkok dental tourism pattern is: day 1 consultation and treatment plan, days 2–5 preparation appointments (tooth preparation for crowns/veneers, implant placements), days 6–10 laboratory work period (local tourism activities), final day fitting and bonding; a 2-week Bangkok dental vacation with transformative cosmetic dentistry results is achievable; (5) Quality verification: Thai dentists undergo 5–6 years of training at dental schools (Chulalongkorn, Mahidol's Faculty of Dentistry, Srinakharinwirot); specialist training requires additional 2–3 years; requesting credentials (dental school, year of graduation, specialty training location) from treatment-planning dentists is standard practice for medical tourism patients.",
    tip: "Bangkok dental tourism guidance: (1) Communication and treatment plan documentation: requesting a detailed written treatment plan (with materials specifications, warranties, and number of appointments) before committing to treatment ensures expectations are shared; reputable Bangkok dental facilities provide written treatment plans as standard; (2) Material quality questions: for crowns and veneers, asking specifically about material brand and origin (German or Swiss ceramic, Japanese laboratory-grade zirconia) confirms quality level; domestic Thai ceramics may be equally good but the specifications should be disclosed; (3) Post-treatment follow-up: Bangkok dental clinics that serve international patients are experienced with post-treatment support via email and LINE messaging; establishing a LINE contact with your treating dentist before leaving Bangkok enables follow-up communication for any post-treatment concerns; (4) Dental implant healing period: dental implant osseointegration (healing of implant into jawbone) requires 3–6 months before permanent crown placement; if planning implant treatment, a second Bangkok visit 4–6 months after initial implant placement is required for permanent crown fitting; (5) Emergency dental in Bangkok: Bangkok's major dental hospitals provide emergency appointments; dental pain, knocked-out teeth, or broken crowns can typically be seen within same-day or next-day appointments at BIDC, Bangkok Dental Spa, and Bumrungrad dental center.",
  },
  {
    name: "Bangkok's Pharmacy Culture — What You Can Buy Without Prescription",
    emoji: "💊",
    area: "Pharmacy chains: Boots Pharmacy (UK-style pharmacy, 300+ Thailand locations, many in BTS station areas); Watsons (Hong Kong, 200+ locations); Bangkok Pharmacy chain; Hospital pharmacies (Bumrungrad, Bangkok Hospital in-house pharmacies); local drugstores: neighborhood pharmacies throughout Bangkok; 24-hour pharmacies: adjacent to major hospitals; nighttime medication access: 7-Eleven carries limited OTC medications (paracetamol, antacids, cold medication)",
    price: "Paracetamol 500mg (30 tabs): ฿30–50; Amoxicillin 500mg (10 caps): ฿50–150 (no prescription required at many Bangkok pharmacies); Anti-malarial (doxycycline, 10-day course): ฿200–400; Azithromycin (Z-pak equivalent): ฿100–300; Diazepam (prescription controlled): requires prescription in Thailand; Metformin diabetes medication: ฿50–200 for 30-day supply; Sildenafil (Viagra generic): ฿50–150 per pill without prescription at many pharmacies; Mifepristone: not available; Emergency contraception (Plan B equivalent): ฿150–300 over counter at Boots, Watsons",
    why: "Bangkok pharmacies operate in a partially deregulated environment that provides medication access different from Western countries: (1) Prescription culture reality: while Thai law requires prescriptions for prescription-classified drugs, enforcement at Bangkok pharmacies (particularly small neighborhood pharmacies vs. chain pharmacies) varies significantly; antibiotics (amoxicillin, azithromycin, doxycycline), antiparasitic medications, and some medications controlled in Western countries are commonly available over-the-counter at Bangkok pharmacies; (2) Chain pharmacy vs. independent pharmacy: Boots and Watsons pharmacy chains operate closer to international pharmacy standards (requesting prescriptions for prescription drugs); small independent Bangkok pharmacies (particularly in non-tourist neighborhoods) frequently dispense without prescriptions; (3) Travel medication access: Bangkok's pharmacies are a practical destination for obtaining travel medications before Southeast Asian travel; malaria prophylaxis (doxycycline, atovaquone-proguanil/Malarone equivalent), altitude sickness medication (acetazolamide), traveler's diarrhea antibiotics (ciprofloxacin), and comprehensive first aid supplies are available with or without prescription at Bangkok pharmacies; (4) Generic medication availability: Thailand manufactures extensive generic pharmaceuticals; the Government Pharmaceutical Organization (GPO) produces affordable generics for domestic use; branded Western medications are available at higher cost; generic quality in Thailand is generally reliable (GPO products are used throughout Thai public hospitals); (5) Imported medication considerations: bringing foreign-prescribed controlled substances into Thailand (including some ADHD medications, antidepressants, anxiety medications, and strong painkillers) requires documentation; the Thai FDA classifies substances differently than Western countries; checking Thai FDA classifications before travel prevents customs problems.",
    tip: "Bangkok pharmacy navigation guidance: (1) Medical grade quality at Boots: Boots Pharmacy in Bangkok stocks the same international pharmaceutical brands (Nurofen, Panadol, Centrum, vitamin brands) as UK Boots; quality is identical; (2) Compounding pharmacies: Bangkok has specialist compounding pharmacies (pharmacies that custom-formulate medications) for patients with specific medication requirements not met by commercial preparations; asking at major hospital pharmacies for compounding service referrals if needed; (3) Medication translation: Thai medication packaging sometimes uses Thai language only; showing a pharmacist the English medication name or active ingredient gets the equivalent Thai product; Google Translate camera mode can translate Thai medication labels; (4) Cold chain medications: insulin and other temperature-sensitive medications are available at Bangkok pharmacies but require requesting refrigerated storage confirmation; (5) Expired medication risk: neighborhood pharmacies in Thailand occasionally have older stock; checking expiration dates on packaging before purchasing and choosing high-turnover pharmacies (Boots at major BTS stations) reduces expired medication risk.",
  },
];

export function BangkokHealthcare() {
  return (
    <div className="rounded-2xl border border-blue-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-blue-700 mb-3">
        🏥 Bangkok healthcare — international hospitals, dental tourism & pharmacy access
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-blue-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-blue-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-blue-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
