const TOPICS = [
  {
    title: "Bangkok to Khon Kaen — Day Trip or Weekend, Getting There & What Makes It Worth Going",
    emoji: "🚂",
    summary: "Khon Kaen is Isaan's largest city and northeastern Thailand's commercial and university hub, making it a distinct Thai urban experience accessible from Bangkok: (1) Why Khon Kaen from Bangkok: Khon Kaen (450km northeast of Bangkok) represents the gateway to Thailand's Isaan (northeastern) region — a cultural, culinary, and geographical area starkly different from Bangkok or the tropical south; Khon Kaen offers: Isaan food culture in its authentic urban form, silk weaving heritage (mudmee silk from Chonnabot District), the Khon Kaen National Museum (prehistoric Ban Chiang cultural context), Bueng Kaen Nakhon lake (urban park), and Khon Kaen University (Northeast Thailand's largest university campus); (2) Bangkok to Khon Kaen transport: the primary options are — Udonthani-bound train: Hua Lamphong or Bang Sue Grand to Khon Kaen station (approximately 7–8 hours for daytime trains, sleeper overnight trains available); domestic flight: Bangkok Suvarnabhumi or Don Mueang to Khon Kaen Airport (KKC), approximately 55 minutes flying time, operated by Thai Airways, Nok Air, Thai AirAsia; bus: Northern (Mo Chit) Bus Terminal to Khon Kaen, approximately 6.5–7.5 hours by VIP bus; (3) Khon Kaen's culinary scene: Khon Kaen food is Isaan food in its most authentic urban form — som tum, larb, moo ping, sai krok Isaan (fermented Isaan sausage), kai yang (grilled chicken), khao niao (sticky rice); the Khon Kaen night market (Ruen Rom Night Market, First Night Market) provides concentrated Isaan food experience; (4) Khon Kaen's silk heritage: Chonnabot District (45km from Khon Kaen) is Thailand's mudmee silk (ikat-dyed handwoven silk) center; the weaving villages of Chonnabot produce silk sold throughout Thailand and globally; Khon Kaen city markets and shopping malls also have Isaan silk and cotton products; (5) Khon Kaen as university city: Khon Kaen University (founded 1964) creates a distinct city character with young population, café culture, and academic energy unusual in provincial Thai cities; the university campus is a destination in itself (large, landscaped, with museum).",
    action: "Bangkok to Khon Kaen flight: Don Mueang Airport (DMK) to Khon Kaen Airport (KKC) — Nok Air and Thai Lion Air at ฿700–2,000 one-way depending on timing; Thai Airways from Suvarnabhumi at ฿1,200–3,500; Bangkok to Khon Kaen bus: Northern Terminal (Mo Chit BTS) — Transport Company (Bor Kor Sor), departure times 7am–11pm, VIP bus ฿350–550; Khon Kaen accommodation: Pullman Khon Kaen (business hotel), Duangtawan Hotel, Avani Khon Kaen for midrange options; local transport in Khon Kaen: Grab available, songthaew (shared truck taxi) for local routes.",
  },
  {
    title: "Bangkok to Kanchanaburi — WWII History, River Kwai & Accessible Day-Trip from Bangkok",
    emoji: "🌉",
    summary: "Kanchanaburi (130km west of Bangkok) is one of the most historically significant and scenically distinctive destinations accessible as a day-trip or overnight from Bangkok: (1) Bridge over the River Kwai: Kanchanaburi's most famous landmark, the Death Railway bridge over the Mae Klong River (labeled 'River Kwai' for tourism purposes), is the preserved section of the World War II railway built with Allied prisoner of war labor under Imperial Japanese command; the bridge was constructed in 1943, partially bombed in 1945, and rebuilt post-war; visitors can walk across the bridge, visit the nearby Death Railway Museum and Research Centre, and tour the JEATH War Museum (Allied prisoner of war experience documentation); (2) Death Railway historical context: the Burma-Thailand Railway ('Death Railway') was built between 1942–1943 under brutal conditions; approximately 180,000 Asian laborers (romusha, mostly from Malaya, Java, Burma) and 60,000 Allied POWs constructed 415km of railway in 16 months; estimated 90,000–100,000 Asian laborers and 12,000–13,000 Allied POWs died during construction from disease, malnutrition, and mistreatment; Kanchanaburi's Allied War Cemetery contains the graves of 6,982 prisoners; (3) Kanchanaburi natural setting: beyond WWII history, Kanchanaburi has genuinely beautiful natural scenery — the River Kwai (Mae Klong) river system with rafting guesthouses on bamboo platforms, Erawan National Park (multiple-tier waterfalls, 3 hours from central Kanchanaburi), Sai Yok Waterfall, and tiger cave temples; (4) Elephant sanctuary access: several elephant sanctuaries in the Kanchanaburi area allow ethical visitor interaction (no riding); these provide more accessible elephant sanctuary experience than Chiang Mai for Bangkok-based visitors; research sanctuary ethics before booking (ethical sanctuaries: no riding, bathing not performances); (5) Bangkok to Kanchanaburi day-trip feasibility: Kanchanaburi is Thailand's most practical day-trip from Bangkok for historical tourism; the 130km distance allows a day visit (6am departure from Bangkok, arrive 9am, 8 hours in Kanchanaburi, return 5pm, arrive Bangkok 8pm) without excessive rushing.",
    action: "Bangkok to Kanchanaburi by train: Bangkok Noi Station (Thonburi, reach by Chao Phraya boat to Tha Chang pier then walk, or BTS to Wongwian Yai then Grab) — two WWII death railway trains daily (6:57am and 1:35pm) stopping at Kanchanaburi station and continuing along the original death railway route; journey approximately 2.5–3 hours; by bus: Southern Bus Terminal (Sai Tai Mai, accessible by BTS Wongwian Yai + Grab) — frequent departures ฿80–120, approximately 2–2.5 hours; by private transport: Grab or rental car, 1.5–2 hours via Highway 323; Kanchanaburi accommodation: luxury floating rafts on the river ฿1,200–2,500; river guesthouse ฿500–1,200; death railway museum admission: approximately ฿200 adults; Erawan National Park: ฿300 foreigner fee, songthaew from Kanchanaburi ฿50–80 per person.",
  },
  {
    title: "Bangkok to Ayutthaya — UNESCO Ancient Capital, Temple Ruins & Half-Day from Bangkok",
    emoji: "🏛️",
    summary: "Ayutthaya (80km north of Bangkok) was Thailand's second capital (1350–1767) and the political, cultural, and commercial center of the Thai kingdom at its greatest extent — its temple ruins are UNESCO World Heritage Site status: (1) Ayutthaya's historical significance: Ayutthaya was Thailand's capital for 417 years (Ayutthaya Kingdom period) until its destruction by Burmese invasion in 1767; at its peak in the 17th century, Ayutthaya was one of the world's largest cities (estimated 1 million inhabitants) and a major international trading port with Dutch, Portuguese, Japanese, Chinese, French, and Persian trading communities; the Ayutthaya Historical Park (UNESCO World Heritage, 1991) preserves the ruins of the city's former temple complexes, palace, and fortifications; (2) Key Ayutthaya sites: Wat Mahathat (famous for Buddha head encased in tree roots); Wat Phra Si Sanphet (three chedis, former royal temple, most photographed silhouette); Wat Chai Watthanaram (Khmer-style prang surrounded by Buddha figures, built 1630); Wat Lokaya Sutha (massive reclining Buddha in the open air); Ayutthaya Floating Market (modern tourist market, not historical); the Palace grounds (foundation remains); (3) Ayutthaya temple elephant: the iconic Ayutthaya image (Buddha head wrapped in banyan tree roots at Wat Mahathat) creates the most photographed Thai Buddhist image; the cultural protocol is to lower oneself below the head level of Buddha images — visiting Wat Mahathat requires crouching if photographing the Buddha head at eye level; (4) Getting around Ayutthaya: the historical park covers approximately 3x3 km; options for navigating: bicycle rental (฿50–100/day, most guesthouses and near the station), tuk-tuk charter (฿200–400 for 2–3 hour tour), long-tail boat tour of riverside temples (฿500–800 per boat); bicycle is the most common and enjoyable Ayutthaya historical park navigation method; (5) Ayutthaya day-trip value: Ayutthaya is Thailand's most accessible UNESCO World Heritage Site from Bangkok; a half-day trip (depart Bangkok 7am by train, arrive 8:30am, 5 hours at sites, return 2:30pm train, back in Bangkok 4pm) is viable and popular among Bangkok visitors.",
    action: "Bangkok to Ayutthaya by train: Bangkok Hua Lamphong or Bang Sue Grand Station — frequent departures (every 1–2 hours, 7am–8pm), ordinary class ฿15–30, approximately 1.5 hours; trains to Ayutthaya are recommended over buses (faster, more comfortable, scenic, no traffic); by bus: Mo Chit Northern Bus Terminal, minibus ฿70–100, 1–1.5 hours but traffic-dependent; Ayutthaya historical park bicycle rental: near Ayutthaya train station (south side) multiple rental shops ฿50–100/day; temple entrance fees: most Ayutthaya temples ฿50 per site (foreigner price); combined ticket available for some sites; Ayutthaya floating market: 4–5km from historical park, tuk-tuk to reach; best light for Ayutthaya photography: early morning 7–10am (golden light on red-brick ruins, before tourist crowds); avoid midday heat 11am–2pm at open-air ruins.",
  },
];

export function BangkokKhonKaen() {
  return (
    <div className="rounded-2xl border border-orange-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-orange-700 mb-3">
        🚂 Bangkok day trips — Khon Kaen (Isaan), Kanchanaburi (River Kwai) & Ayutthaya (UNESCO ruins)
      </h2>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-orange-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-orange-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
