const TOPICS = [
  {
    title: "Bangkok Tennis, Badminton & Squash — Court Access, Club Culture & Playing as a Visitor",
    emoji: "🎾",
    summary: "Bangkok has extensive racquet sports infrastructure serving both the Thai and expat communities: (1) Bangkok tennis scene: tennis has strong historical roots in Bangkok's royal and aristocratic culture (the Royal Bangkok Sports Club, founded 1901, is Bangkok's oldest tennis club with clay and hard courts); Bangkok's tennis infrastructure includes: private clubs requiring membership (Royal Bangkok Sports Club, British Club Bangkok, RBSC — expensive but top quality); hotel courts open to guests and sometimes non-guests (Dusit Thani, The Oriental, Hilton Bangkok); public courts at Bangkok sports complexes (Huamak Indoor Stadium, National Stadium Bangkok — clay courts, low-cost or free); and sport complexes in parks (Lumphini Boxing Stadium area, Chatuchak Park); (2) Badminton's dominance in Thai sport culture: badminton is Thailand's most popular participant racquet sport, significantly more widespread than tennis; Thailand has produced world-class badminton players (Ratchanok Intanon is Thailand's most decorated badminton player, multiple World Championship medalist and Olympic medalist); Bangkok badminton courts: high-quality indoor badminton halls throughout the city at affordable rates (฿60–200 per hour for court rental); badminton halls in every Bangkok district, often near BTS/MRT stations; drop-in court rental common (no membership required); major Bangkok badminton venues: Muang Thong Thani Indoor Arena, Huamak Badminton Complex, various private badminton halls near residential areas; (3) Squash in Bangkok: squash is less widespread than tennis or badminton but Bangkok has several squash facilities; Bangkok Squash Centre, British Club Bangkok squash courts, and hotel-based squash courts serve the expatriate squash community; the sport is popular among Bangkok's international business community; (4) Table tennis and sepak takraw: table tennis (ping pong) has significant Thai amateur player base; local community halls and sports centers throughout Bangkok have table tennis tables at very low cost; sepak takraw (traditional Southeast Asian volleyball/soccer-kick sport using rattan ball) is played in Bangkok parks — watching locals play sepak takraw (particularly in public park open areas) is a distinctly Bangkok sport observation; (5) Finding a playing partner in Bangkok: expat racquet sports communities use: Facebook groups ('Bangkok Tennis Players', 'Bangkok Badminton Players', 'Bangkok Squash'), Meetup.com Bangkok sports groups, and club noticeboards; hotel concierge can often arrange tennis court bookings and partner matching through the hotel's sports program.",
    action: "Bangkok racquet sports access: badminton court rental — walk into any Bangkok badminton hall and rent a court by the hour (฿80–200/hour for a 2-4 player court); courts typically available throughout the day on weekday afternoons; weekend mornings are busier; bring your own racquet or rent at the venue (฿20–50 rental); Lumpini Park tennis courts: Rama IV Road entrance area, public courts at low cost (฿30–100/hour), available to walk-in; National Stadium Bangkok: various racquet sport facilities at subsidized public rates; British Club Bangkok (Silom): reciprocal member access if you hold membership at a partner club internationally — check if your home club has reciprocal arrangement; hotel tennis: most Bangkok 5-star hotels with courts allow non-guest court booking (฿300–800/hour) — Dusit Thani, Intercontinental Bangkok, The Athenee are examples.",
  },
  {
    title: "Bangkok Running & Triathlon Culture — Park Runs, Marathons & Hash House Harriers",
    emoji: "🏃",
    summary: "Bangkok's running culture has grown substantially with a distinctive expat-and-Thai community around park running, organized races, and the legendary Hash House Harriers: (1) Lumpini Park running: Lumpini Park (57 hectares, MRT Si Lom and MRT Lumpini entrances) is Bangkok's premier running venue; the park's 2.5km perimeter path sees hundreds of runners 5–8am and 5–8pm; running culture in Lumpini mixes Thai locals (primarily evening runners), expats, and visiting tourists; the park's inner paths add additional kilometers; Lumpini provides Bangkok's most social running environment; (2) Bangkok running events calendar: the most significant annual Bangkok running events: Bangkok Marathon (annual, November, roads through historic Rattanakosin area, Saphan Phut finishing area): full 42.2km and half marathon distances; Bangsaen Marathon (Chonburi, 90 minutes from Bangkok, October) — a popular Bangkok runner destination race; Standard Chartered Bangkok Marathon and numerous charity runs are part of Bangkok's race calendar; the cool season (November–February) concentrates most Bangkok running events; (3) Hash House Harriers Bangkok — the iconic expat running social institution: the Hash House Harriers (HHH) is a global running social group founded in Kuala Lumpur in 1938 by British colonial officers; Bangkok has multiple Hash chapters: Bangkok Hash House Harriers (BHH, one of Asia's oldest chapters); Bangkok Harriettes (women's chapter); Bankok-based hashing involves a weekly run following a paper trail laid by 'hares,' culminating in beer/drinks and social time; Bangkok Hash runs are excellent for expat social integration and trail running outside Bangkok's park system; (4) Bangkok triathlon community: Bangkok has an active triathlon community centered around Thailand Triathlon Association; training groups at Lumpini Park (cycling simulation on cycling path or adjacent roads), hotel pools (for swimming training), and the Benchakitti cycling path; major Thailand triathlon events include: Laguna Phuket Triathlon (November, Phuket — popular Bangkok triathlete destination), various Ironman events in Thailand and nearby; (5) Bangkok running challenges: heat and humidity make Bangkok running more physiologically demanding than equivalent running in temperate climates; experienced Bangkok runners adjust by: running before 8am or after 5pm strictly; significantly shortening run distance and pace in hot months (April–June); using heart rate monitoring to prevent heat stress; carrying water for any run over 30 minutes in hot season; Bangkok's air pollution (February–April burning season) affects breathing during intensive outdoor exercise.",
    action: "Bangkok running community: Bangkok running Facebook groups ('Bangkok Runners', 'Hash House Harriers Bangkok') provide current event listings and route recommendations; Lumpini Park morning run: arrive 6–6:30am for optimal conditions, the 2.5km track path is marked and well-lit; Bangkok Marathon registration: Bangkok Standard Chartered Marathon (bkkmarathon.com or similar — search current year registration); Bangkok Hash House Harriers: search 'Bangkok Hash House Harriers' on Facebook for current chapter details and next run announcement; runs typically Saturday afternoon/Sunday morning; visitors welcome at Bangkok Hash runs (check with current organizers, small participation fee typically covers beverages at the 'circle' post-run); triathlon training: Benchakitti Park cycling path and the park's open water (though triathlon-specific training requires organized event for open-water swimming).",
  },
  {
    title: "Bangkok Esports & Gaming Culture — Arcades, Gaming Cafés & Thailand's Pro Gaming Scene",
    emoji: "🎮",
    summary: "Bangkok has an exceptionally vibrant gaming culture spanning traditional arcades to modern esports: (1) Bangkok gaming café culture: Bangkok's PC gaming café infrastructure is extraordinary — gaming cafés (internet cafés with high-specification gaming computers) are found throughout Bangkok at ฿20–50 per hour; each café offers top-tier gaming PCs (RTX graphics, high-refresh monitors) configured for popular esports titles (Dota 2, League of Legends, Valorant, PUBG, CS2, Minecraft); the social gaming café is a Bangkok evening staple for teenagers and young adults; gaming café clusters: Panthip Plaza (Pratunam area, BTS Chit Lom/Phetchaburi MRT — Bangkok's original technology hub, multiple gaming cafés in the building), Chatuchak area, university-adjacent areas throughout Bangkok; (2) Bangkok arcades: traditional coin-operated and IC card arcades persist in Bangkok's malls; major arcade venues: Timezone (Central World, Mega Bangna, multiple mall locations — ICE card based gaming arcade); Joypolis (if operating); dedicated crane game/UFO catcher venues (popular in Bangkok's Japanese-influenced gaming culture); rhythm game arcades (Maimai, Dance Dance Revolution, Taiko no Tatsujin — popular with Bangkok's gaming community); Bangkok's arcade culture is healthier than in most developed markets due to active teen culture and mall arcade anchoring; (3) Thailand's esports scene: Thailand has emerged as Southeast Asia's significant esports market; notable Thai professional players and teams: Natus Vincere has Thai players, Thailand-based teams compete in PUBG Mobile World League and regional Dota 2 circuits; RoV (Arena of Valor) is Thailand's most popular mobile esports title — the ROV Pro League is Thailand's premier esports event (IMPACT Arena finals); TeSL (Thailand Esports League) governs competitive gaming; (4) Bangkok gaming events: Thailand Game Show (BITEC, October–November annually) is Thailand's largest gaming convention (700,000+ visitors over the event week, PC hardware, console gaming, cosplay competition, tournament events) — the most significant Bangkok gaming cultural event; IESF World Championship regional events occasionally held in Thailand; ROV Pro League finals at IMPACT Arena are attended by tens of thousands; (5) Thai gaming culture characteristics: Thai gaming culture has a strong mobile component (Thailand is one of Asia's top mobile gaming markets) alongside PC gaming; ROBLOX is massive with Thai youth; mobile gaming titles dominate app store revenue; the social gaming café format is uniquely Thai-Southeast Asian — the communal gaming space as social hub rather than home gaming isolation; Thai gamers are generally welcoming to foreign gaming visitors in cafés and online communities.",
    action: "Bangkok gaming café access: visit any major Bangkok mall area and look for gaming café signage (typically 'Net Café' or 'Gaming Café' in English, 'ร้านเกม' in Thai); Panthip Plaza (BTS Chit Lom or MRT Phetchaburi) is Bangkok's technology shopping and gaming hub — gaming cafés throughout the complex; expect to pay ฿25–50/hour for a PC gaming session; payment is typically by the hour with no membership required; Thailand Game Show: if visiting Bangkok in October–November, check Thailand Game Show's official website for current year dates and BITEC venue program; ROV Pro League: check garena.co.th/rpl for current season schedule and IMPACT Arena event dates; arcade gaming: Central World, Mega Bangna, and CentralPlaza malls throughout Bangkok have Timezone arcades with IC card gaming — buy a Timezone card (฿100+ minimum load), activate at the card machine, and use for any arcade machine in the venue.",
  },
];

export function BangkokRacquet() {
  return (
    <div className="rounded-2xl border border-green-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-green-700 mb-3">
        🎾 Bangkok sport & gaming — racquet sports access, Hash House Harriers running & esports gaming culture
      </h2>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-green-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-green-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
