const TOPICS = [
  {
    title: "Bangkok to Hua Hin — Royal Beach Resort Weekend Escape & Getting There",
    emoji: "🏖️",
    summary: "Hua Hin (200km south of Bangkok) is Thailand's original royal beach resort and the country's most established beach destination for Bangkok weekend escapes: (1) Hua Hin's royal heritage: Hua Hin became Thailand's royal beach destination when King Rama VII built the Klai Kangwon Palace ('Far from Worries Palace') in 1929; the palace (still an active royal residence used by the royal family and not open to public tours) established Hua Hin's prestigious character that distinguishes it from more tourist-mass beach destinations; (2) Bangkok to Hua Hin transport: primary options include — train: Bangkok Hua Lamphong or Bang Sue Grand to Hua Hin station (approximately 3–4 hours, scenic journey past Gulf of Thailand, departure options from 7am to evening, rapid train ฿200–380 second class); bus: Southern Bus Terminal (Sai Tai Mai) to Hua Hin, approximately 3–3.5 hours by air-conditioned VIP bus (฿200–300); private car or Grab: approximately 2.5–3 hours via Highway 35 (Phetkasem Road), comfortable family option; Minibus/van service: Hua Hin Transport Co. and private vans from Victory Monument or Siam area, approximately 2.5 hours, ฿200–250; (3) Hua Hin as weekend destination character: Hua Hin caters to Bangkok's upper-middle-class weekend market — the town has golf courses (6 courses within 30 minutes of Hua Hin), seafood restaurants of high quality, a clean beach (some seaweed during monsoon season June–October), and the 'Night Market' walking street near the Hua Hin railway station (Thailand's most-photographed train station, Royal Hua Hin Railway Station built 1926 in classic Thai-Victorian railway architecture); (4) Hua Hin beach and activities: the main Hua Hin beach stretches approximately 5km; the central beach in front of the Centara Grand (formerly Railway Hotel, Thailand's oldest hotel, opened 1923) is the most iconic Hua Hin beach location; activities available: horseback riding on the beach (a Hua Hin tradition since its earliest resort days), kitesurfing (excellent conditions), vineyard visits (Hua Hin Hills Vineyard and Monsoon Valley Vineyard — Thailand's best-known wineries are near Hua Hin), elephant sanctuary day visits (within driving range); (5) Hua Hin accommodation for Bangkok weekend trips: the central Hua Hin accommodation market is well-developed from 5-star (Centara Grand Beach Resort & Villas, Anantara Hua Hin Resort, Intercontinental Hua Hin) to mid-range boutique resorts to budget guesthouses in the town center; weekend rates are typically 50–100% above weekday rates as Bangkok demand concentrates on Fridays–Saturdays; booking at least 2–3 weeks ahead for weekend stays at quality properties is recommended.",
    action: "Hua Hin Railway Station photographing: the Hua Hin Railway Station (built 1926, Royal Waiting Room with Thai roof design visible, the most architecturally significant Thai provincial train station) is adjacent to the town center and Night Market; photography is unrestricted; trains run through the station from approximately 6am to 10pm (multiple daily Bangkok-Hua Hin-Bangkok services); Centara Grand historical access: non-guests can walk through the lobby and gardens of the Centara Grand (formerly Railway Hotel) as it is still operating as a hotel — the heritage public areas including the veranda, pool area, and lobby are open; 1920s British colonial architectural heritage; Hua Hin Night Market: opens approximately 6pm daily, concentrated near the train station and along Dechanuchit Road; fresh seafood, Thai street food, souvenirs; best seafood at Hua Hin: the fishing pier area has multiple seafood restaurants specializing in just-caught Gulf of Thailand seafood.",
  },
  {
    title: "Bangkok to Pattaya — Beach City 90 Minutes Away & What Actually Awaits",
    emoji: "🌅",
    summary: "Pattaya (148km southeast of Bangkok) is one of Southeast Asia's most famous beach cities with a specific reputation that requires nuanced understanding for different visitor types: (1) Pattaya's realistic character: Pattaya is Bangkok's most accessible beach destination (90 minutes from Ekkamai Bus Terminal) and one of the world's most densely touristed beach cities; the city has genuinely good beaches on Jomtien and the north end; excellent seafood; watersports (diving, sailing); and extensive entertainment infrastructure; Pattaya also has Southeast Asia's largest concentrated adult entertainment zone (Walking Street) that creates a specific reputation and visitor composition; understanding which version of Pattaya is relevant to one's visit helps set expectations; (2) Pattaya beyond Walking Street: Jomtien Beach (4km south of central Pattaya) has cleaner water, less commercial density, and a more family/resident-oriented character; Ko Larn (Coral Island, accessible by boat from Pattaya pier, 45 minutes, ฿30–50 return per person) has the clearest Gulf of Thailand water near Pattaya; Sanctuary of Truth (massive wooden structure, 105m tall, religious-cultural center, partially finished construction, ฿500 admission) is one of Southeast Asia's most unusual buildings; Nong Nooch Tropical Botanical Garden (world-class botanical collection, Thai cultural shows, ฿500); (3) Bangkok to Pattaya transport: bus from Ekkamai Bus Terminal (BTS Ekkamai, then 5-minute walk to Ekkamai Bus Station, Southern Eastern, departures every 30 minutes 5am–9:30pm, ฿120–140, 2 hours depending on traffic); bus from Mo Chit Northern Bus Terminal (more departures, same price); Bangkok Pattaya Highway (Highway 7, tollway, Grab or private car approximately 90 minutes, ฿400–800 for Grab car from Bangkok, ฿150–200 total tolls); private car: 90 minutes to 2 hours depending on Bangkok departure point and highway traffic; (4) Pattaya's diving access: Pattaya's proximity to Gulf of Thailand wrecks and reef sites (Ko Lan, Man Wichai area) makes it accessible as a diving base from Bangkok; dive centers in Pattaya (Mermaids Dive Center, Planet Scuba, Oceanic Dive Center) offer daily dive trips to local sites and trips to more distant Ko Chang or Ko Tao for certified divers; the Gulf of Thailand around Pattaya has limited visibility (5–10m typically) compared to the Andaman Sea or the southern Gulf (Ko Tao area), but is accessible for convenient diving training or casual diving; (5) Pattaya accommodation diversity: Pattaya's accommodation ranges from Walking Street-adjacent party hotels to family beach resorts on Jomtien; the best family and quality-oriented accommodation is on Jomtien Beach (3–4 star Jomtien hotels at ฿1,500–4,000/night) or in the northern Pattaya/Na Jomtien area; budget accommodation in central Pattaya can be extremely inexpensive (฿400–800/night) but the party hotel environment may not suit all visitors.",
    action: "Pattaya transport from Bangkok: Ekkamai Bus Terminal is the most convenient Pattaya bus departure point for central Bangkok/Sukhumvit visitors (BTS Ekkamai, cross the road to the bus terminal); Pattaya public transport: within Pattaya, the shared songthaew (pick-up truck taxi) circulates on set routes for ฿10 per person; agree 'Baht bus' fare before boarding; Ko Larn day trip: speedboat charter from Pattaya Pier to Ko Larn approximately ฿2,500–3,500 per boat (return) or public ferry ฿30 one-way; Pattaya best beach area for non-adult-entertainment visitors: Jomtien Beach (south Pattaya, Jomtien Beach Road, significantly calmer character than Walking Street area); water sports on Jomtien: parasailing ฿500, jet ski ฿800–1,200/hour, banana boat ฿200 per person.",
  },
  {
    title: "Bangkok to Ko Chang — Remote Gulf Island with Jungle Interior & Quiet Beaches",
    emoji: "🌴",
    summary: "Ko Chang (Chang Island, approximately 315km southeast of Bangkok) is one of Thailand's largest islands and the most accessible 'underdeveloped' Gulf island from Bangkok — offering a genuine island experience without the over-commercialization of Ko Samui or the party atmosphere of Ko Phangan: (1) Ko Chang character: Ko Chang's appeal lies in its combination of mountainous jungle interior (the island is 70% national park), genuinely clear beach water on the west coast, relatively limited commercial development compared to Thailand's most-visited islands, and cooler average temperatures than the flat southern islands; the island's national park status has slowed resort development while maintaining its lush character; (2) Bangkok to Ko Chang transport: Bangkok to Ko Chang requires combining road and ferry transport — total journey: 4–6 hours; options: bus from Bangkok's Eastern Bus Terminal (Ekkamai or Mo Chit) to Laem Ngop pier (Trat province) approximately 4 hours (฿250–350), then ferry from Laem Ngop to Ko Chang approximately 30 minutes (฿100 per person, cars ฿200–300 extra); direct 'combination package' minivans from Bangkok to Ko Chang resort (including pier transfer) available through travel agencies at approximately ฿400–600 per person; (3) Ko Chang beach geography: the island's western coast has the main beaches — White Sand Beach (Hat Sai Khao, most developed, budget accommodation, party bar scene), Klong Prao Beach (mid-coast, more resort-oriented, calmer character), Kai Bae Beach (southern mid-coast, good snorkeling), Lonely Beach (southernmost developed beach, backpacker character, good budget accommodation); the eastern coast is undeveloped and inaccessible; (4) Ko Chang's jungle interior: the interior national park contains waterfalls (Klong Plu Waterfall, most accessible and most spectacular), trekking paths, and wildlife (hornbills, monitor lizards, gibbons); visiting Klong Plu Waterfall (approximately ฿200 national park fee, 30-minute walk from trailhead) provides the best easy access to Ko Chang's jungle character; elephant trekking is available on Ko Chang but ethical concerns about elephant welfare in trek operations are significant — research operators before booking; (5) Ko Chang as Bangkok long weekend destination: Ko Chang is best suited to minimum 3-night visits to justify the transport investment; 4–5 night stays allow beach relaxation + waterfall visit + snorkeling + island circumnavigation by rented motorbike or songthaew; the island is most crowded from December to February (peak Thai tourist season) and least crowded during the rainy season (June–September, when sea conditions can prevent ferry operation on rough days).",
    action: "Ko Chang transport booking: bus from Ekkamai to Laem Ngop (Trat province): Transport Company (Bor Kor Sor) at Ekkamai Eastern Bus Terminal, 5am–10pm departures; Ko Chang ferry: Car Ferry from Laem Ngop Pier (Centrepoint Pier or Ao Thammachat Pier); ferries depart every 1–2 hours approximately 6am–9pm; Ko Chang national park pass: purchased at the ferry terminal or at waterfall entry points; motorbike rental on Ko Chang: Klong Prao and White Sand Beach areas have multiple rental shops at ฿150–250/day for manual scooters, ฿250–350 for automatic (valid international driving license required but rarely checked); Ko Chang snorkeling day trips: from any Ko Chang beach, longtail boat day trips to snorkeling sites (Koh Kradad, Koh Klum) approximately ฿500–800 per person including equipment.",
  },
];

export function BangkokHuaHin() {
  return (
    <div className="rounded-2xl border border-sky-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-sky-700 mb-3">
        🏖️ Bangkok beach escapes — Hua Hin royal resort, Pattaya nuanced guide & Ko Chang island
      </div>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-sky-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-sky-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
