const SPOTS = [
  {
    name: "Bangkok's Legendary Hawker Heritage — Street Food as Cultural Identity",
    emoji: "🍜",
    area: "Street food geography: Yaowarat (Chinatown) noodle shops and night hawkers; Silom Soi 20 lunch vendors; Victory Monument night market food ring; Pratunam lunch stalls; Khao San backpacker street food row; On Nut residential Thai street food; Lat Phrao/Ratchada working-class Thai food strips; Chatuchak Market Saturday-Sunday food zone",
    price: "Boat noodles (small bowl, Yaowarat style): ฿30–60; Pad Thai (street vendor): ฿60–100; Tom yum noodles: ฿60–100; Grilled pork rice (khao moo daeng): ฿60–120; Kao man gai (chicken rice): ฿50–90; Spring rolls (street cart): ฿30–60; Grilled squid: ฿60–150; Dessert (mango sticky rice, khanom): ฿40–100",
    why: "Bangkok street food represents one of the world's great hawker traditions — the legacy of immigrant Chinese and regional Thai food vendors who developed Bangkok's outdoor cooking culture across a century of city evolution: (1) Chinese immigrant foundation: Bangkok's street food culture has deep Chinese roots; the Teochew Chinese who dominated Bangkok's early merchant class introduced noodle soups, roast meats (Chinese BBQ pork — moo daeng, roast duck), and congee that became foundations of Thai urban food culture; (2) Regional Thai diversity: Bangkok's street food reflects the regional diversity of Thailand's internal migration; Isaan (northeastern) vendors brought papaya salad, laap, and grilled meat culture; Southern Thai vendors brought richer curry-heavy preparations; Northern vendors brought khao soi and sai oua sausage to Bangkok's street food ecosystem; (3) Vendor generationalism: Bangkok's most celebrated street food vendors are typically multi-generation businesses; identifying and patronizing these generational establishments (often with visible aged family portraits and visible cooking history) produces the most authentic experiences; (4) Morning and evening cycles: Bangkok street food operates in two distinct cycles; morning vendors (5–10am, breakfast/commuter market) offer different preparations from evening vendors (5pm–midnight, post-work dinner market); a complete Bangkok street food day requires both; (5) Disappearing culture: Bangkok's street food culture has come under urbanization pressure; city authorities have periodically cleared sidewalk vendors from upscale commercial areas; the remaining street food is concentrated in wet markets, dedicated food lanes, and working-class residential neighborhoods outside the tourist corridor.",
    tip: "Bangkok street food navigation: (1) Vendor quality signals: long lines (particularly of Thai office workers or delivery drivers eating lunch, not tourist groups) indicate kitchen confidence; visible cooking workspace hygiene, fresh ingredient turnover, and well-maintained equipment distinguish quality vendors; (2) Single-item specialization: Bangkok's best street food vendors typically specialize in one or two dishes rather than offering an extensive menu; approaching a vendor who has been making the same dish for 20 years produces better results than a menu of 30 items; (3) Yaowarat night timing: Yaowarat's night hawkers begin setting up at 6pm and peak 8–11pm; arriving before 8pm finds the stalls getting started with full-freshness cooking; after midnight, vendors begin packing down; (4) Language in working-class areas: street food in non-tourist Bangkok operates in Thai; most vendors understand numbers (total cost) and basic ingredients; pointing at pictures or the food of nearby diners communicates efficiently; Google Translate camera function on Thai menus provides instant translation; (5) Cash dependency: street food in Bangkok remains primarily cash (baht only); PromptPay QR code payment is increasingly appearing at street stalls but cannot be assumed; carrying ฿500 in ฿20–50 denominations for food stall visits prevents change difficulty.",
  },
  {
    name: "Bangkok's Night Market Food Landscape",
    emoji: "🌃",
    area: "Night market food destinations: Asiatique Riverfront (Charoen Krung, BTS Saphan Taksin water taxi); Jodd Fairs (multiple locations including Dan Neramit, Jodd Fairs 2 on Ratchada); Chang Chui (creative night market, Taling Chan area); OR TOR KOR Night Market (Chatuchak area); Friday-Sunday night markets in Ratchada/Huai Khwang area",
    price: "Night market pad Thai: ฿80–150; Grilled meat skewers (per skewer): ฿30–80; Tom yum or hot pot at night market: ฿120–350; Seafood platter (medium): ฿300–800; Mango sticky rice at night market: ฿100–200; Beer (Leo, Chang, Singha at market): ฿70–120; Cocktail/fruit shake: ฿80–200",
    why: "Bangkok's night market ecosystem has evolved from purely functional street food markets to experience destinations combining food, shopping, music, and social atmosphere: (1) Jodd Fairs evolution: Jodd Fairs — Bangkok's most Instagram-famous contemporary night market format — combines container architecture, social media-optimized food vendor selection, live music, and bar culture into a hybrid night market concept that has generated multiple imitation formats across Bangkok; (2) Asiatique Riverfront: the most tourist-friendly of Bangkok's night markets; permanent riverside development combining shopping malls, restaurants, street food, live entertainment, and a Ferris wheel; BTS water taxi access from Saphan Taksin makes it the most accessible large-scale night market; (3) Chang Chui: Bangkok's most creative night market concept; built in a former industrial compound in Taling Chan; artisan vendors, art installations, food trucks, and Bangkok's most photogenic 'crashed plane' bar backdrop; more alternative audience than mainstream Asiatique; (4) OR TOR KOR Market: the government-operated agricultural market adjacent to Chatuchak has one of Bangkok's highest-quality fresh produce and food sections; day and evening operation; premium produce quality (mangoes, durian, and tropical fruits at high quality) at market prices; (5) Night market social function: Bangkok's night markets (particularly the newer Jodd Fairs-influenced formats) serve a social function for Bangkok's young working class — affordable date-night venues with atmosphere, alcohol, and food without the cost of restaurant dining.",
    tip: "Bangkok night market strategy: (1) Arrival time: Bangkok night markets typically open 5–6pm; arriving 6–7pm finds full vendor selection with manageable crowds; 8–10pm is peak crowd (particularly weekends); after 11pm, popular items sell out and vendors begin packing; (2) Weather contingency: outdoor night markets in Bangkok operate year-round but August–October wet season creates sudden rain disruption; checking weather and having an abort option matters during peak rain months; (3) Jodd Fairs parking vs. BTS: Jodd Fairs' Dan Neramit location has challenging parking; BTS-adjacent locations or Grab taxi are more practical; the Jodd Fairs 2 Ratchada location is nearer BTS infrastructure; (4) Food vendor quality variation: night market food ranges from excellent to purely visual/Instagram (large portions optimized for appearance rather than taste); the vendor selection inside a single market has significant quality variation; watching where Thai customers (not tourist groups) are queuing identifies the genuine quality within a market; (5) Night market drinking culture: Bangkok's night markets maintain a social drinking atmosphere with readily available beer and cocktails; understanding that the markets are social spaces (friends groups sharing food, couples on dates, families with children) rather than purely food-focused environments frames the experience correctly.",
  },
  {
    name: "Bangkok's Michelin Bib Gourmand — Affordable Excellence",
    emoji: "⭐",
    area: "Michelin Bib Gourmand Bangkok listings (updated annually): concentrated in Yaowarat (Chinese cuisine hawkers), Banglamphu, Silom working-class lunch spots, and specific neighborhoods where generational Thai cooking has been recognized; current listings include Jay Fai (Michelin star — khao man gai and wok cooking), multiple noodle shops, and rice curry shops in accessible-price categories",
    price: "Michelin Bib Gourmand-listed hawker meal: ฿60–400 (defining quality: 'good cooking at affordable prices'); Michelin star Bangkok dining: ฿1,500–8,000/person (Le Du, Sorn, Gaggan Anand); Jay Fai crab omelette (celebrity Michelin street): ฿900–1,200 (expensive by street standards, cheap by Michelin star standards); PAD Thai at Michelin-listed shops: ฿80–200",
    why: "Bangkok's Michelin Guide recognition since 2018 has provided an organized framework for identifying Bangkok's highest-quality traditional cooking: (1) Michelin Guide Bangkok annual publication: the MICHELIN Guide Bangkok updates annually; the Bib Gourmand category (good quality, good value — typically under ฿400) recognizes the finest traditional Thai and Chinese hawker cooking in Bangkok; this category is more practically useful than Michelin star listings for everyday food exploration; (2) Jay Fai phenomenon: Jay Fai (Charoen Krung) is Bangkok's most famous Michelin-starred street food vendor; the elderly proprietress (Jay Fai herself) wearing ski goggles while wok-cooking crab omelettes and pad kee mao over intense charcoal flame has become globally famous; 2–4 hour queues are normal; the experience is genuinely remarkable but requires planning; (3) Bangkok star restaurants: Bangkok has multiple Michelin one- and two-star restaurants representing the pinnacle of Thai culinary refinement; Le Du, Sorn (Southern Thai tasting menu), Gaggan Anand (avant-garde Indian-influenced), Saawaan (traditional Thai techniques), and Aksorn represent different approaches to contemporary Thai fine dining; (4) Pre-Michelin excellence: Michelin recognition has created prices inflation for listed vendors; some Bangkok food enthusiasts now argue the best undiscovered hawker cooking is among vendors in residential Bangkok districts that inspectors haven't visited; (5) Bangkok's food blogger ecosystem: the pre-Michelin era and Michelin-supplementary Bangkok food blogger ecosystem (Mark Wiens' migrationology, Thai food blogs by Kin Long Pai staff) provides deeper hawker restaurant knowledge than guide listings.",
    tip: "Bangkok Michelin dining navigation: (1) Jay Fai booking reality: Jay Fai's popularity means walk-in queuing (2–4 hours minimum) or advance booking through the shop's Instagram or contact; the shop sometimes closes for private events; confirming open status before traveling is practical; (2) Bib Gourmand > Michelin star for Bangkok food value: Bangkok's Bib Gourmand listings represent better value-to-experience ratio than star restaurants for most visitors; the ฿150–400 meals at Bib Gourmand hawkers deliver more authentic Bangkok food culture than ฿3,000 tasting menus; (3) Sorn reservation: Sorn (Southern Thai Michelin two-star) books out months ahead; reservation through their official booking system is required well in advance of desired date; (4) Local versus tourist prices post-Michelin: several Michelin-listed Bangkok hawkers have implemented tourist pricing after recognition; verifying that prices match those of Thai customers eating simultaneously is reasonable calibration; (5) Guide currency: the Michelin Guide Bangkok updates annually; checking the current year's listing (available on the Michelin Guide website and app) ensures listed restaurants are still operating and have maintained their listing.",
  },
];

export function BangkokHawkerCulture() {
  return (
    <div className="rounded-2xl border border-orange-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-orange-700 mb-3">
        🍜 Bangkok hawker culture — street food heritage, night markets & Michelin Bib Gourmand
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-orange-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-orange-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
