const SPOTS = [
  {
    name: "Kanchanaburi — Bridge on the River Kwai, WWII History & Death Railway",
    emoji: "🌉",
    area: "Kanchanaburi Province: 130km west of Bangkok (2–2.5 hours by car or train); main sites: Bridge over the River Kwai (JEATH War Museum, river bridge), Kanchanaburi War Cemetery (Allied POW graves, Don Rak); Death Railway (Sai Yok Noi waterfall area, Hellfire Pass Memorial Museum, Mae Klong Railway); Erawan National Park (7-tier waterfall, 70km north of Kanchanaburi town); accommodation: riverside floating raft house accommodation unique to Kanchanaburi; River Kwai Village Hotel; Kanchanaburi town center; Srinakarin Reservoir area (Khao Laem Reservoir); transport: minivan from Victory Monument BTS or Sai Tai Mai (Southern Bus Terminal); train from Bangkok Thonburi station (slow, 3 hours, historic route)",
    price: "Bangkok to Kanchanaburi minivan: ฿180–250; Train (2nd class, Thonburi to Kanchanaburi): ฿100–150; JEATH War Museum entry: ฿30; River Kwai Bridge area: free (walking bridge itself); Kanchanaburi War Cemetery: free; Hellfire Pass Memorial Museum: free (Australian-operated); Erawan National Park entry: ฿300 foreigners, ฿100 Thais; Raft house accommodation (per night): ฿500–2,500; River Kwai boat tour (2 hours): ฿600–1,200 per charter",
    why: "Kanchanaburi is Bangkok's most historically significant day trip destination, combining WWII history with natural beauty: (1) The Death Railway's history: the Thailand-Burma Railway (the 'Death Railway') was constructed by the Imperial Japanese Army during 1942–1943 using Allied POW labor (British, Australian, American, Dutch) and Asian forced laborers; approximately 16,000 Allied POWs and 90,000+ Asian laborers died during construction in brutal conditions (disease, starvation, overwork); the 415km railway was built to supply Japanese forces in Burma; the Bridge over the River Kwai at Kanchanaburi is the most recognizable surviving structure; (2) The Bridge over the River Kwai in reality: the famous bridge (made internationally known by the 1957 David Lean film) is actually over the Mae Klong River (which the 1957 renaming changed to Kwai Yai and Kwai Noi rivers after the film's fame); the current bridge is a reconstruction; the original was bombed by Allied forces; visitors can walk across the bridge (trains pass several times daily — clear the bridge for train passage); (3) Hellfire Pass Memorial Museum: operated by the Australian government, Hellfire Pass Memorial Museum (80km north of Kanchanaburi town) commemorates the Konyu Cutting — a section of the Death Railway carved through solid rock at night by torch-lit laborers; the museum is the most comprehensive and emotionally resonant Death Railway memorial; the name 'Hellfire Pass' comes from the appearance of the torch-lit night work; (4) Erawan National Park as natural counter-balance: Erawan National Park (70km north of Kanchanaburi town) has a 7-tier waterfall system with emerald-blue swimming pools at each tier; fish (doctor fish) nibble at waders' feet in the pools; the park represents the accessible nature tourism that balances Kanchanaburi's WWII history; (5) River Kwai floating raft houses: Kanchanaburi's iconic accommodation is floating raft houses on the Kwai Noi River — bamboo-and-wood platforms floating on the river; overnight stays on raft houses (with basic rooms, generators for evening power) provide a distinctly Thai waterway accommodation experience available near Bangkok.",
    tip: "Kanchanaburi visit planning: (1) Day trip feasibility: Kanchanaburi is doable as a Bangkok day trip but is better as 2 days (overnight on a raft house allows full WWII museum visits and Erawan National Park without rushing); day trips from Bangkok with minivan leave 6am and return by 7pm; (2) Hellfire Pass travel from Kanchanaburi town: Hellfire Pass is 80km from Kanchanaburi town (1 hour by songthaew or rental motorbike); the museum location requires transport planning; most tour packages include Hellfire Pass as part of a northern loop; renting a motorbike in Kanchanaburi (฿300–400/day) allows independent exploration; (3) Erawan National Park pools: Erawan's 7 pools have varying accessibility; the lower 3 pools are easiest; reaching pool 7 (the topmost) requires 2+ hours hiking from the park entrance; water shoes are recommended for pool navigation; the park entrance closes at 4pm (give yourself time to descend); (4) Death Railway train experience: the Thonburi–Nam Tok train follows the original Death Railway route through jungle and over the viaduct above the Wang Pho cliff face; this is the most atmospheric Death Railway experience available; the train is slow (3+ hours Bangkok to Kanchanaburi) but the river valley scenery is exceptional; check schedules (limited departures); (5) Kanchanaburi WWII Remembrance Week: each November 25, Kanchanaburi holds the Bridge Festival on the River Kwai with light shows on the bridge, cultural performances, and international commemorations; Australian and British veterans' groups attend; visiting during this period provides historical depth beyond the museum experience.",
  },
  {
    name: "Hua Hin — Royal Beach Town, Beach Escapes 200km from Bangkok",
    emoji: "🏖️",
    area: "Hua Hin: 200km south of Bangkok (2.5–3 hours by car; Srinakarin Toll Road); Hua Hin-Cha Am area; adjacent: Cha Am beach (15km north, quieter), Pranburi Forest Park (45km south), Sam Roi Yot National Park (60km south); transport: First class bus from Mo Chit (Victory Monument BTS area) or Southern Bus Terminal (Sai Tai Mai), ฿350–500, 3.5 hours; minivan ฿350–450, 3 hours; train from Hua Lamphong (3–5 hours, slow); direct car: Google Maps via Highway 35 and Route 4; accommodation: Le Méridien, Anantara, Intercontinental (luxury), budget guesthouses in Hua Hin town; Hua Hin Night Market (seasonal); Hua Hin Hills Vineyard (wine production, 45km inland)",
    price: "Bangkok to Hua Hin bus (1st class): ฿350–500; Bangkok to Hua Hin minivan: ฿350–450; Hua Hin budget guesthouse: ฿600–1,500; Hua Hin mid-range hotel (per night): ฿1,500–4,000; Hua Hin luxury resort (per night): ฿5,000–25,000+; Water sports (jet ski, banana boat): ฿500–1,500; Hua Hin Night Market food: ฿60–200; Hua Hin Hills Vineyard wine tasting: ฿300–600; Golf (Hua Hin area courses): ฿1,500–3,500 greens fee",
    why: "Hua Hin is Bangkok's premier beach escape for Thai middle-class families and expats, with a distinctly different character from Pattaya or Phuket: (1) Royal resort history: Hua Hin is Thailand's oldest beach resort, developed in the 1920s when the Royal Family's Klai Kangwon Palace was built here; the royal connection (the palace is occasionally used by the current royal family) gives Hua Hin a prestige association and maintained respectability that distinguishes it from Pattaya's more commercialized entertainment identity; (2) Thai domestic tourism: unlike Pattaya (which caters heavily to international mass tourism) and Phuket (international package tourism), Hua Hin has a historically higher proportion of Thai domestic tourists; Thai Bangkok residents bring families to Hua Hin for beach weekends; understanding this Thai-family atmosphere helps set expectations; (3) Hua Hin vs. Pattaya comparison: Hua Hin (Thai domestic/upmarket resort) vs. Pattaya (international mass/entertainment resort) represents the fundamental Bangkok-beach-escape choice; Hua Hin has longer, quieter beaches and less nightlife; Pattaya has more transport infrastructure and international visitor density; (4) Golf excellence: Hua Hin has some of Thailand's best golf courses (Black Mountain, Sea Pines, Springfield Royal); the combination of quality courses, reasonable fees, and beach accommodation makes Hua Hin Thailand's second golf destination after Pattaya (which also has excellent courses); (5) Hua Hin Night Market: Hua Hin's night market (concentrated on Dechanuchit Road) is one of the best in Central Thailand; it combines fresh seafood grills, local Thai food, handicrafts, and clothing stalls; the seafood (grilled prawns, crab, fresh fish) at reasonable prices represents authentic Central Gulf Coast seafood culture.",
    tip: "Hua Hin trip planning from Bangkok: (1) Weekend vs. weekday: Hua Hin on Saturday morning is flooded with Bangkok traffic (particularly long weekends); arriving Friday evening or Sunday (when Bangkok residents are returning) reduces traffic and accommodation pressure; weekday Hua Hin is dramatically quieter and prices may be 20–30% lower at smaller hotels; (2) Hua Hin vs. Cha Am: Cha Am beach (15km north of Hua Hin) has a rougher, less curated beach character with more Thai street food vendors directly on the beach; accommodation is cheaper; the beach itself is windier and less gentle than Hua Hin's main beach; Cha Am suits visitors who want a more local beach experience with less tourist polish; (3) Sam Roi Yot National Park addition: the limestone hills and freshwater marshlands of Sam Roi Yot National Park (60km south of Hua Hin) add significant variety to a Hua Hin trip; the park's Phraya Nakhon Cave (with a royal pavilion inside, photographically spectacular with light shaft through the cave ceiling) requires a morning hike; (4) Hua Hin weather windows: Hua Hin is on the Gulf Coast; the wet season brings significant rain June–October but is typically less severe than the Andaman coast; November–May is the dry season peak; Hua Hin's December–January period is cool (25–28°C), comfortable, and extremely popular; (5) Seafood restaurant selection in Hua Hin: the Hua Hin fishing harbor (Tha Hin, south of town) has seafood restaurants with fresh catch directly from boats; pricing in the harbor area is more honest than tourist-facing beachfront restaurants; Google Maps reviews for 'อาหารทะเล ทาเรือหัวหิน' (seafood Hua Hin harbor in Thai) give better local results than English searches.",
  },
  {
    name: "Khao Yai National Park — Wildlife, Waterfalls & UNESCO Heritage Day Trip",
    emoji: "🦚",
    area: "Khao Yai National Park: 200km northeast of Bangkok (2.5–3 hours by car via Mittraphap Highway or Pak Chong); Pak Chong town (gateway, accommodation hub, Pak Chong train station 30km from park entrance); within park: Haew Narok waterfall (tallest, 150m), Haew Suwat waterfall (famous from 'The Beach' movie), Nong Pak Chi observation tower (wildlife viewing, wild elephant, deer); wildlife: Asian elephant, Siamese crocodile, hornbills (Great/Wreathed), sambar deer, gaur; park zone: Thai Highland with altitude 400–1,300m (significantly cooler than Bangkok at park elevations); adjacent: Khao Yai Winery area (Italian-style Tuscan wine tourism development), GranMonte Winery, Monsoon Valley Vineyard; accommodation in/near Pak Chong: multiple glamping and eco-resort options",
    price: "Khao Yai National Park entry: ฿400 foreigners, ฿40 Thais; Vehicle entry: ฿50; Bangkok to Pak Chong bus (from Mo Chit): ฿150–200; Pak Chong to park entrance (songthaew/taxi): ฿300–600; Night safari (guided, inside park): ฿800–1,500 per person (tour operators); Full-day tour Bangkok–Khao Yai: ฿1,500–3,500 per person; Pak Chong guesthouse: ฿500–1,500; Khao Yai area resort (glamping, eco): ฿2,000–8,000; GranMonte Winery visit: ฿300–500 tasting fee",
    why: "Khao Yai is Thailand's oldest national park and arguably its most accessible UNESCO heritage wilderness: (1) UNESCO World Heritage status: Khao Yai is part of the Dong Phayayen-Khao Yai Forest Complex (UNESCO World Heritage since 2005) — 6,155 square kilometers of connected protected highland forest housing some of Southeast Asia's most significant wildlife; (2) Wild elephant encounters: Khao Yai's most sought wildlife experience is wild elephant viewing; Asian elephants (smaller than African, with smaller ears) graze near the Nong Pak Chi tower and road corridors; sightings are more likely at dawn/dusk; approaching to within 100m of wild elephants is prohibited; (3) Hornbill biodiversity: Khao Yai has 4 resident hornbill species including the Great Hornbill (significant in size, distinctive yellow-and-black bill casque); hornbills are among Southeast Asia's most charismatic birds; October–December is peak fruiting season bringing hornbill aggregations to fruiting trees; (4) Haew Narok waterfall: Haew Narok ('Hell's Gorge') waterfall at 150m is Thailand's tallest single-drop waterfall; the two-tier fall with viewing platforms provides impressive waterfall photography; the access trail (1.5km) requires basic fitness; (5) Night safari experience: Khao Yai's night wildlife (guided by tour operators, spotlight safari vehicles enter the park evening hours) reveals nocturnal wildlife: sambar deer, barking deer, civets, occasionally porcupines; the night wildlife density is higher than daytime sightings per hour; night safari bookings with registered tour operators inside Pak Chong are recommended over self-driving at night (park road safety concerns).",
    tip: "Khao Yai practical planning: (1) Independent vs. tour debate: driving to Khao Yai independently (car rental recommended from Bangkok) provides flexibility; a rented car (฿1,200–2,000/day with driver or self-drive) plus park entry allows your own schedule for the park's 2,168 square kilometers; tours (from Bangkok or Pak Chong) are more structured but include guide knowledge; (2) Pak Chong stay recommendation: a Pak Chong overnight (arriving evening, 2 full park days, departing Day 3 morning) provides both early-morning wildlife window (best wildlife activity 6–9am) and evening/night opportunities without rushing; day trips from Bangkok leave insufficient time for Haew Narok + wildlife viewing + Haew Suwat; (3) Khao Yai Winery tourism: the Khao Yai wine region (Nakhon Ratchasima Province, around Pak Chong) has developed as a tourist attraction; GranMonte Winery, Monsoon Valley Khao Yai, and PB Valley offer tastings and tours in Tuscany-inspired settings; Thai wine has improved significantly; this wine/wildlife combination creates a distinctive Khao Yai weekend; (4) Best season: Khao Yai is greenest and most dramatic in August–November when monsoon growth peaks; December–February is the dry and cool season (temperatures at elevation can drop to 10°C at night); March–May is hot and transitional; avoiding March–May for Khao Yai avoids the driest, hottest period; (5) Wildlife photography equipment: Khao Yai wildlife photography benefits from 300–500mm telephoto lens capability; wildlife encounters happen at distances requiring longer focal lengths; smartphone cameras produce limited results for wildlife; binoculars (10x42) significantly improve the wildlife viewing experience beyond naked-eye observation.",
  },
];

export function BangkokKanchanaburi() {
  return (
    <div className="rounded-2xl border border-green-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-green-700 mb-3">
        🌉 Bangkok day trips — Kanchanaburi WWII history, Hua Hin beach & Khao Yai wildlife
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-green-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-green-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
