const SPOTS = [
  {
    name: "Bangkok Cosmetic Clinic Scene — Skin, Laser & Anti-Aging",
    emoji: "✨",
    area: "Bangkok cosmetic clinic cluster: Sukhumvit (Nana, Asok, Phrom Phong, Thong Lo); Silom; Siam-Ratchadamri corridor; major hospital cosmetic departments: Bumrungrad, Samitivej, Bangkok Hospital, Yanhee Hospital (bang sue), BDMS group; medical certification: Thai Medical Council, THAICERT (Thailand Cosmetic Enhancement & Rejuvenation Association)",
    price: "Botox (per area): ฿3,000–6,000; Hyaluronic acid filler (per syringe): ฿12,000–30,000; Ultherapy (full face): ฿25,000–60,000; Thermage (full face): ฿30,000–70,000; Laser resurfacing (full face): ฿8,000–25,000; PRP (Platelet Rich Plasma): ฿8,000–15,000; Glutathione IV: ฿2,000–5,000/session; Skin whitening program (10 sessions): ฿20,000–50,000",
    why: "Bangkok's cosmetic clinic market has grown into one of Asia's largest and most competitive non-surgical cosmetic treatment markets: (1) Price competitiveness: Bangkok cosmetic treatments cost 30–60% less than equivalent treatments in Singapore, Hong Kong, Australia, or Western Europe while using identical equipment (Ulthera, Thermage FLX, Picosure, Fraxel are certified international equipment); (2) K-beauty influence on Bangkok cosmetic standards: the Korean aesthetic heavily influences Bangkok's cosmetic clinic market; double eyelid stitching, nose tip refinement without full rhinoplasty, and glass-skin glutathione programs reflect Korean cosmetic trends adapted for Thai-Asian facial features; (3) Medical tourism infrastructure: international patient coordinators (English-speaking), consultation packages (multi-specialist assessment ฿500–2,000), coordinated treatment plans, and hotel-to-clinic transport create an accessible framework for international cosmetic visitors; (4) Thai dermatology excellence: Thailand's tropical climate has produced skin specialists with exceptional expertise in hyperpigmentation, post-inflammatory marks, and Asian skin tone-specific laser parameters; Bangkok dermatologists have significant experience with treatments specific to melanin-rich skin; (5) Laser technology access: Bangkok clinics update equipment rapidly in a competitive market; Picosure, Discovery Pico, Genius RF, Morpheus8, and Ultraformer III are available at major clinics without the 2–3 year lag seen in less competitive markets.",
    tip: "Bangkok cosmetic clinic selection: (1) Medical board certification check: Thailand's cosmetic market has both certified dermatologists/plastic surgeons and unregulated practitioners; verifying that your provider is registered with the Thai Medical Council (doctor-listing available on tmc.or.th) and that their clinic is licensed (check for the displayed license) is the essential quality check; (2) Consultation investment: most reputable Bangkok cosmetic clinics charge a consultation fee (฿500–2,000) that is deducted from treatment cost if you proceed; clinics that offer free or no-consultation treatments are operating at a quality level that should raise concern; (3) Package deals vs. per-treatment pricing: Bangkok clinics heavily promote treatment packages; comparing individual treatment pricing versus package pricing and understanding what is included prevents discovering unexpected additional costs; (4) Downtime accommodation: some Bangkok cosmetic treatments (laser resurfacing, significant peels) require recovery accommodation with low sun exposure; hotel rooms with good air conditioning and privacy near your clinic simplify post-treatment recovery; (5) Pre-treatment skin screening: Bangkok's reputable cosmetic dermatologists conduct pre-treatment skin analysis (Visia skin analysis, dermoscopy) before recommending treatment protocols; clinics that recommend the same treatment package regardless of individual skin assessment are treating patients as commercial transactions rather than medical cases.",
  },
  {
    name: "Bangkok Spa & Traditional Thai Beauty Rituals",
    emoji: "🧖",
    area: "Bangkok spa clusters: Sukhumvit (day spas, Thong Lo luxury spa cluster); Silom/Sathorn (hotel spas: Capella, Rosewood, Anantara); Riverside (Mandarin Oriental Spa, Peninsula Spa); Budget: Silom back-street traditional massage; Chatuchak (foot massage clusters); Ratchathewi/Phaya Thai (Thai massage college student clinics); Phra Nakhon/Banglamphu (traditional Thai massage shops)",
    price: "Traditional Thai massage (1 hour): ฿250–500 (street shop), ฿800–2,500 (mid-range spa); Oil massage (1 hour): ฿400–800; Facial (60 min, independent spa): ฿600–1,500; Facial (luxury hotel spa, 60 min): ฿3,500–8,000; Thai herbal compress massage: ฿600–1,200; Foot reflexology (45 min): ฿200–400; Spa package (half-day, including multiple treatments): ฿3,000–8,000",
    why: "Bangkok's spa industry ranges from ฿250 street-level traditional massage to world-class luxury spa experiences that consistently rank among Asia's finest: (1) Traditional Thai massage heritage: nuad bo-rarn (ancient massage — Thai traditional massage) is a UNESCO Intangible Cultural Heritage; the technique combining acupressure, yoga-like stretching, and energy-line (sen sip) theory is distinctly different from Swedish or oil massage; Bangkok has both authentic lineage practitioners (trained at Wat Pho or Chetawan Traditional Massage School) and tourist-oriented shops; (2) Luxury hotel spa excellence: Bangkok's five-star hotel spas (Mandarin Oriental, Capella, Rosewood, Peninsula, Anantara) consistently rank among the best spas in Asia; treatment menus blend Thai traditional technique with contemporary international wellness; the spa facilities (swimming pools, steam rooms, treatment suites) match the world's best; (3) Herbal compress massage: the Thai herbal compress (luk pra kob) — a heated ball of traditional herbs applied to the body — is a specifically Thai spa technique; the anti-inflammatory and circulation properties of the compressed herbs (lemongrass, turmeric, camphor, kaffir lime) combined with heat therapy have evidence-based therapeutic effects; (4) Student clinic value: Bangkok's traditional medicine schools (Wat Pho Traditional Medical School, Chetawan Private Traditional Thai Massage School, Nuad Thai Traditional Massage Institute) offer deeply discounted treatments by students under supervision; quality is high due to instructor oversight; (5) Aromatherapy Thai product market: Bangkok has developed a significant local aromatherapy product industry (Harnn, Pañpuri, Erb, Thann, Jaspal Wellness) using Thai botanical ingredients (jasmine, ylang ylang, lemongrass, bergamot, vetiver root) at international quality with local pricing.",
    tip: "Bangkok spa and massage navigation: (1) Authentic vs. tourist trap identification: authentic traditional Thai massage shops have practitioners in medical attire (typically white or blue), separation of treatment rooms or curtained zones (not open floor), and rates posted on a menu; tourist-trap shops often feature aggressive street touts, unclear pricing, and inadequate hygiene protocols; (2) Wat Pho massage school: the Wat Pho Traditional Medical School massage clinic (at Wat Pho temple complex, Maharaj Road) is one of Bangkok's most authentic traditional massage experiences; the practitioners are certified by the school and the facility is hygienic; prices (฿420–680/hour) are below comparable quality elsewhere; (3) Booking luxury hotel spas: Bangkok's luxury hotel spas (Mandarin Oriental, Capella, Peninsula) accept non-hotel guests and typically have availability within 24–48 hours; booking directly via phone or the hotel website rather than through spa booking apps avoids third-party markup; (4) Herbal compress timing: herbal compress massage generates significant heat; scheduling after physical activity (not before sun exposure or water activities) and allowing time for the warmth to fully dissipate before outdoor activities is the most comfortable sequencing; (5) Tipping culture: Thai massage tipping is customary; ฿50–100 for budget massage, 10–15% for mid-range spa, and ฿200–500 for luxury hotel spa is the general tipping range that aligns with local practice.",
  },
  {
    name: "Bangkok Wellness Tourism — Retreats, Detox & Alternative Health",
    emoji: "🌿",
    area: "Bangkok urban wellness: Bumrungrad Health and Wellness Center; Samitivej Wellness; Bangkok Hospital Integrative Medicine; Day retreats: Panpuri Organic Spa, Divana Virtue Spa; Thai traditional medicine: Institute of Thai Traditional Medicine (Ministry of Public Health, Nonthaburi); Muay Thai training as fitness: various Sukhumvit and outer-Bangkok Muay Thai gyms",
    price: "Wellness consultation (naturopath, integrative doctor): ฿2,000–5,000; Detox program (3-day at wellness hotel near Bangkok): ฿8,000–20,000; Sound healing session: ฿800–2,000; Reiki/energy healing: ฿1,000–2,500; Thai herbal medicine consultation: ฿500–1,500; Muay Thai training session (tourist rate): ฿300–600; Colonics: ฿1,500–3,000; Infrared sauna (session): ฿400–800",
    why: "Bangkok has developed a substantial wellness and alternative health sector alongside its conventional medical excellence: (1) Thai traditional medicine integration: Thailand's Ministry of Public Health officially integrates traditional Thai medicine (nuad thai, herbal medicine, prasit-kammii birthing support, and luk pra kob thermal medicine) into the public health system; Thailand's traditional medicinal knowledge of local plants (morinda citrifolia/noni, andrographis, turmeric, and 50+ pharmacopoeia herbs) represents a distinct healing tradition; (2) Yoga and meditation centers: Bangkok has a robust yoga and meditation infrastructure serving both residents and visitors; Wanderlust, Absolute Yoga, Pure Yoga, and numerous boutique studios offer classes in Thai, English, and increasingly Korean (reflecting Korean expat demand); meditation retreats (silent Vipassana programs, typically 10-day Goenka courses outside central Bangkok) are accessible within a 2-hour drive; (3) Infrared sauna and recovery culture: Bangkok's fitness-conscious communities have adopted infrared sauna, cold plunge, and float tank wellness practices; urban recovery centers (Primal Rise, Chillax & Float, Recovery Society) serve Bangkok's athletic and lifestyle-health communities; (4) Sound healing and energy practices: Bangkok's expat and spiritual community has established a network of sound bath practitioners (singing bowl, gong, crystal bowl), Reiki practitioners, and shamanic ceremony facilitators; the Ekkamai and Silom areas concentrate these practitioners; (5) Medical wellness integration: Bangkok's premium hospitals (Bumrungrad, Samitivej) have established integrative wellness centers offering conventional health screening (comprehensive blood panels, cardiac evaluation, cancer markers) alongside wellness consultations (functional medicine approach, nutrition counseling, stress management).",
    tip: "Bangkok wellness tourism navigation: (1) Vipassana meditation access: the most widely available Vipassana meditation (10-day Dhamma program in Thai-style tradition) centers near Bangkok include Dhamma Kamala (Suwannaphum area, 45 min from Bangkok) and Wat Ram Poeng affiliates; registering through dhamma.org; no fee, but donations accepted; (2) Muay Thai training as wellness tourism: Bangkok has quality Muay Thai gyms offering non-competitive training for fitness and technique; sessions (1.5–2 hours including pads, bag work, and technique) at quality gyms provide excellent functional fitness; gyms catering specifically to tourist training (English-speaking trainers, flexible scheduling) include Fairtex in Bangkok and Yokkao Experience; (3) Thai herbal medicine quality assessment: buying Thai herbal products at reputable pharmacies (Boots, Watsons) and hospital pharmacies ensures product standardization; street vendors and some markets sell herbal products without standardized potency; Thai FDA-registered products (look for อย. registration number on packaging) meet regulated manufacturing standards; (4) Wellness hotel proximity to Bangkok: Chiva-Som (Hua Hin, 3 hours), Kamalaya (Koh Samui, 1 hour flight), and RAKxa (Bangkok, The Forestias complex) represent Thailand's internationally acclaimed wellness resort options within reasonable proximity to Bangkok; (5) Detox programs in Bangkok: hospital-based detox programs (Bumrungrad, Bangkok Dusit Medical Services) provide medically supervised cleansing programs with pathology monitoring; non-medical commercial detox programs at day spas require distinguishing between products with evidence-based support and marketing language without physiological basis.",
  },
];

export function BangkokCosmeticSurgery() {
  return (
    <div className="rounded-2xl border border-pink-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-pink-700 mb-3">
        ✨ Bangkok beauty & wellness — cosmetic clinics, Thai massage spas & wellness retreats
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-pink-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-pink-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
