const SPOTS = [
  {
    name: "Erawan Shrine (Thao Maha Phrom) — Bangkok's Most Visited Hindu Shrine & Its History",
    emoji: "🙏",
    area: "Erawan Shrine location: Ratchaprasong intersection, corner of Ratchadamri Road and Phloen Chit Road; BTS Chit Lom station (exit toward Grand Hyatt Erawan Hotel, the shrine is at the hotel corner); surrounded by: Grand Hyatt Erawan Bangkok, Central World (one of Bangkok's largest malls), Gaysorn Village (luxury mall), Amarin Plaza; Spirit houses throughout Bangkok: can be found at virtually every commercial building, hotel, home, and construction site; San Phra Phum (spirit houses) — miniature Thai-style temple structure on a pedestal in front of/beside buildings; Lak Mueang (City Pillar Shrine): Sanam Luang area, near Grand Palace — the foundational spirit pillar of Bangkok established when the city was founded in 1782",
    price: "Erawan Shrine visit: free entry; offerings (floral garlands, incense, jasmine strings, elephant figurines): ฿20–200 at vendors surrounding the shrine; traditional dance performance at Erawan: organized by devotees who have fulfilled vows (a contracted Thai classical dance troupe performs for the specific devotee), approximately ฿500–2,000 depending on dance group size; Erawan Shrine Thai classical dance schedule: ongoing throughout the day as devotees fulfill vows — timing not predictable but performances happen multiple times daily; amulet purchase near Erawan: ฿50–100,000+ depending on type and spiritual provenance",
    why: "The Erawan Shrine is not merely a tourist attraction but an actively functioning spiritual center at the heart of Bangkok's commercial district: (1) Erawan Shrine's origin: the shrine was erected in 1956 during the construction of the Erawan Hotel (now Grand Hyatt Erawan) after a series of accidents, deaths, and misfortunes plagued the construction project; a Brahmin priest recommended installing a statue of Thao Maha Phrom (the Thai representation of the Hindu creator god Brahma) to propitiate the site's spirits; once installed, the accidents ceased; the original hotel has since been replaced by the Grand Hyatt but the shrine remains as the most visited devotional location in Bangkok; (2) Thai-Hindu syncretism: the Erawan Shrine illustrates Thailand's distinctive religious syncretism — the four-faced golden Brahma (Phra Phrom, sometimes called 'Erawan' incorrectly — Erawan is actually the three-headed elephant, not Brahma) is worshipped by Thai Buddhists; this Hindu deity incorporated into Buddhist Thai practice reflects the historical influence of Brahmanism on Thai royal and religious culture; (3) How to make wishes and vows at Erawan: the devotional practice at Erawan is specific — visitors light incense sticks (usually 9 or 16, specific numbers considered auspicious), offer flower garlands, and make a specific wish; if the wish is granted, the devotee returns and fulfills a 'boon kae bon' (vow repayment) by contracting a Thai classical dance performance at the shrine; the hired dance troupe (stationed outside the shrine) then performs the contracted dances (each dance has a specific number of performers and cost); (4) The 2006 vandalism and rebuild: in 2006, a man attacked the Brahma statue with a hammer (destroying it); two street vendors who witnessed the attack beat the attacker to death; the statue was replaced within weeks with a new golden Brahma; this incident reflects the profound religious significance of the shrine to Bangkok's population; (5) Bangkok's spirit house culture: virtually every building in Bangkok has a spirit house (san phra phum) — a miniature Thai-style temple mounted on a pedestal at the corner of the property; offerings of flowers, incense, water, food, and figurines are placed daily; the spirit house honors the protective spirit of the land; new spirit houses are installed during construction according to Brahmin blessing ceremonies; Bangkok's spirit houses represent an unbroken animist-Brahmin spiritual tradition alongside formal Buddhism.",
    tip: "Erawan Shrine visit guide: (1) Best viewing time for classical dance: Thai classical dance performances (Khon dancers from contracted troupes) happen throughout the day as devotees fulfill vows; there is no fixed schedule — ask at the shrine perimeter if a performance is upcoming; arriving on weekend mornings often coincides with a busier devotional crowd and more frequent dance performances; (2) Respectful conduct at Erawan: the shrine is actively used for devotion; maintain respectful demeanor even if visiting as a tourist-observer; photographs are allowed but photographing during active worship moments with obvious intrusion is inappropriate; remove shoes not required (the shrine is on a concrete platform) but respectful dress (covered shoulders and knees) is recommended; (3) Offerings purchase: the flower garland vendors around Erawan sell jasmine garlands (phuang malai), lotus offerings, incense sets, and small elephant figurines (elephants are symbolically associated with Brahma — offering an elephant figurine is common); purchasing from these vendors supports the shrine's ecosystem; (4) Lak Mueang (City Pillar) for deeper spiritual context: Bangkok's Lak Mueang (City Pillar Shrine), near the Grand Palace at Sanam Luang, is less tourist-visited than Erawan but more deeply connected to Bangkok's foundational spiritual identity; the gilded column (Lak Mueang) represents the protective spirit of Bangkok and houses the ceremonial center of the city's spiritual life; classical dance performances here have stronger traditional character than Erawan's commercial tourism context; (5) Spirit house observation across Bangkok: the most ornate and lovingly maintained spirit houses in Bangkok are at major businesses (department stores, luxury hotels, large companies) where the spiritual efficacy of offerings is considered commercially important; Centralworld, Siam Paragon, and major Bangkok hotels maintain elaborate multi-element spirit house altars; observing the attention given to Bangkok's spirit houses across all socioeconomic levels illustrates the living relevance of Thai animist-Brahmin spiritual practice alongside formal Buddhism.",
  },
  {
    name: "Bangkok Merit-Making — Wat Visits, Monk Offerings & How Thais Relate to Buddhism",
    emoji: "☸️",
    summary: "Understanding Bangkok's actual practice of Buddhism (as lived by Thai people) differs significantly from academic or tourist Buddhism: (1) Tam boon — merit-making as daily practice: 'Tam boon' (ทำบุญ, making merit) is the most important daily spiritual act for most Thai Buddhists; the primary forms of merit-making in Bangkok include: offering food to monks at dawn (tak bat), donating to temples, releasing birds or fish (practice of merit by releasing captive animals — controversial ecologically, common culturally), buying offerings for temple spirit houses, and visiting temples to pray; merit accumulation is understood as generating positive spiritual energy that improves one's karmic trajectory; (2) Monks' alms rounds (tak bat) in Bangkok: every morning at dawn (approximately 6–7am), Buddhist monks walk their alms round collecting food offerings from laypersons; in Bangkok, the strongest tak bat culture is in older residential neighborhoods (not tourist zones) and near temples; temples with attached monk residences (many Rattanakosin area temples) have morning alms rounds visible; receiving alms from a monk (non-monks, especially women, must not touch monks) is the most direct merit-making opportunity; Bangkok visitors can observe tak bat at Rattanakosin area temples in early morning; (3) Temple donation practices: Thai Buddhists regularly donate to their neighborhood temple (wat) — funds support monks' living expenses, temple maintenance, and Buddhist education; donation amounts are personal; donation boxes at temples receive cash donations; specific merit-making donations include sponsoring gold leaf for Buddha statues, donating temple equipment, or sponsoring monks' robes (at Kathin ceremony); (4) Buddhist observance days (Wan Phra): Thailand observes Wan Phra (Buddhist holy days, occurring approximately every 7 days following the lunar calendar) when many Thai Buddhists make temple visits, observe precepts (refraining from meat, alcohol, entertainment), and perform additional merit-making; Bangkok's temples are noticeably more active on Wan Phra days; (5) The role of the monarchy in Thai Buddhism: the Thai monarchy and Buddhism are intertwined through the concept of Dhamma Raja (righteous king) and the King's role as the Defender of the Faith; Thai kings historically patronized Buddhist institutions; King Vajiralongkorn (Rama X) has been ordained as a monk (temporary ordination is a rite of passage for most Thai Buddhist men); the monarchy's connection to Buddhism reinforces Thai national identity through religious practice.",
    action: "Bangkok morning merit-making observation: Wat Pho, Wat Mahathat (near Grand Palace), and Wat Ratchabophit areas see genuine early morning tak bat activity 6–7:30am; maintain respectful distance as an observer; do not interact with or touch monks in any way; Wan Phra calendar: check any Thai Buddhist calendar app for current month's observance days; temple attendance on Wan Phra offers the most active engagement with Thai Buddhist practice; Lumpini Park merit-making: Lumpini Park has a fish and turtle pond where Bangkok residents purchase live turtles and fish at the park entrance vendors to release into the pond as merit-making — this practice continues despite ecological discussion; visiting Loha Prasat (metal palace temple, on Ratchadamnoen Klang Avenue, less visited than major temples) provides a quieter temple experience with active local Buddhist practice.",
  },
  {
    name: "Bangkok Tattoo Culture — Sak Yant Traditional Thai Tattoos & the Modern Tattoo Scene",
    emoji: "🖋️",
    summary: "Bangkok's tattoo culture spans from Thailand's ancient Sak Yant spiritual tattooing tradition to a vibrant contemporary tattoo industry: (1) Sak Yant — traditional Thai Buddhist magical tattoos: Sak Yant (สักยันต์, 'yantra tattoo') are geometric tattoos applied by Buddhist monks or Hindu Brahmin priests using a traditional sharpened rod (khem sak — hand-tapping method); the designs are yantra symbols (sacred geometric diagrams combined with Pali or ancient Khmer script) believed to confer specific spiritual powers: protection, luck, strength, attraction, or specific desired attributes; the tattoo is applied after prayer and is activated by the practitioner's blessing; (2) Where to receive Sak Yant in Bangkok: Wat Bang Phra (Nakhon Pathom province, 60km from Bangkok) is the most famous Sak Yant temple, visited by both Thais and international visitors (Angelina Jolie's highly publicized Sak Yant here established international awareness); Ajarn Noo (Ajahn Nu) is Bangkok's most internationally known Sak Yant master, operating from his studio near Bangkapi; numerous monks at Bangkok temples with Sak Yant knowledge also accept practitioners; (3) The Sak Yant process: traditional Sak Yant requires: visiting the temple or master, presenting offerings (incense, candles, sometimes areca nut, joss sticks), requesting a specific yant design (the monk/master usually selects the appropriate design based on the recipient's situation and needs), and receiving the hand-tapped tattoo with accompanying blessing mantras; there is no set price (merit offering, respectful donation appropriate); the practitioner usually communicates that the design requires certain precepts or behaviors to maintain the tattoo's power (abstaining from specific activities, foods, or behaviors); (4) Bangkok contemporary tattoo industry: Bangkok has developed a substantial contemporary tattoo scene with professional studios throughout the city, particularly in Thong Lo/Ekkamai (higher-end studios serving expat and tourist market), Ari, and areas near Khao San Road (heavy tourist concentration, quality varies widely); international tattoo artists regularly guest at Bangkok studios; Thai tattoo artists have gained international reputation for fine-line work, watercolor techniques, and intricate detail; (5) Getting tattooed in Bangkok practical considerations: quality Bangkok tattoo studios (for non-Sak-Yant work) maintain the same hygiene standards as international studios — new needle per client, sterilized equipment, fresh ink caps; Bangkok has reputable studios with portfolios visible on Instagram; pricing for contemporary tattoo work at quality Bangkok studios: ฿2,000–5,000 per hour for established artists; simpler pieces ฿800–2,000; walk-in availability depends on studio and artist — booking ahead for specific artists is recommended.",
    action: "Sak Yant at Wat Bang Phra: requires transport to Nakhon Pathom province (organized tour from Bangkok ฿1,000–2,000 per person, or self-transport by train to Nakhon Pathom station then Grab); Wat Bang Phra's monks tattoo visitors on temple premises (no appointment needed, arrive early morning); offerings for monks: jasmine garlands, incense, candles; the Wat Bang Phra Sak Yant Festival (annual, March) is when thousands gather for group blessings and can trigger trance-like states in participants — this event is a significant Thai cultural spectacle; Sak Yant alternative (non-temple): several Bangkok Sak Yant practitioners offer sessions outside the temple context; Ajarn Noo's studio is bookable via LINE/social media; for contemporary tattoo studios in Bangkok: Nimit Tattoo (Thong Lo), Ink Vaders (research current reputable studios via Instagram searches for Bangkok tattoo); tattoo healing in Bangkok heat: Bangkok heat accelerates tattoo healing but also increases risk of inflammation from sun exposure — keep fresh tattoos out of direct sun and properly moisturized.",
  },
];

export function BangkokShrine() {
  return (
    <div className="rounded-2xl border border-yellow-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-yellow-700 mb-3">
        🙏 Bangkok spiritual life — Erawan Shrine & spirit houses, Buddhist merit-making & Sak Yant tattoos
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-yellow-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-yellow-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-yellow-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
