const SPOTS = [
  {
    name: "Bangkok Sunrise & Golden Hour — Best Spots for Morning Light Photography",
    emoji: "🌅",
    area: "Bangkok's best sunrise photography locations: Wat Arun (Temple of Dawn) from the east bank (Tha Tien Pier, riverside walk) — golden hour light hits the iconic prang tower perfectly from 6:30–8am; Saphan Phut (Memorial Bridge) — lower view of Wat Arun from the bridge itself, less crowded than Tha Tien; Asiatique riverfront — long Chao Phraya riverside view at dawn (6–7:30am when no crowds, docks lit in morning haze); Golden Mount (Wat Saket) summit at 7:30–9am — panoramic Bangkok view from the hill with morning city haze atmosphere; Charoenkrung Road morning walk — old Bangkok atmosphere with minimal traffic at 6–8am; Bangkapi area canal (Khlong Saen Saep, 6–8am boat activity) for Bangkok water life photography; Flower Market (Pak Klong Talat) 3–7am for Bangkok's most active wholesale commerce photography; Tha Chang Pier area 6–8am for monk alms round photography (Rattanakosin area temples)",
    price: "Bangkok early morning photography access: Wat Arun ferry crossing (Tha Tien to Wat Arun): ฿5 per person; Wat Arun entrance during regular hours: ฿100; sunrise/early morning (before 8am) entry is sometimes free before ticket booth opens (arrive 6am to test); Wat Saket (Golden Mount) sunrise entry: ฿50; Flower Market (Pak Klong Talat): free to walk through, no ticket; Chao Phraya express boat (for river transit): ฿15–40; Grab to early morning location: expect ฿80–200 depending on distance (Bangkok traffic starts 7:30–8am, earlier is faster and cheaper); photography equipment rental in Bangkok: camera rental shops near Silom and Chatuchak areas",
    why: "Bangkok's early morning hours offer an entirely different city than the midday tourist experience: (1) Bangkok's optimal photography window: Bangkok's photography light windows are strict — golden hour at sunrise (6–8am) and sunset (5–7pm, though monsoon clouds make sunset variable); the 11am–3pm harsh midday light flattens Bangkok's ornate temple surfaces and creates heavy shadows; most Bangkok photography guides recommend morning shooting as primary; (2) Wat Arun (Temple of Dawn) morning logic: Wat Arun's name literally translates as 'Temple of Dawn' — it was named for being seen from the Chao Phraya River at dawn as approaching boats saw the prang tower catching first light; the temple's Chinese porcelain mosaic surface reflects and refracts morning light differently from midday; best viewing/shooting angles: from the opposite east bank (Tha Tien Pier area, the riverside promenade), the prang catches golden light with the Chao Phraya in the foreground; (3) The flower market before dawn: Pak Klong Talat (flower market, near Memorial Bridge, MRT Sanam Chai) operates through the night with peak wholesale activity from midnight to 4am; the visual environment (thousands of cut flowers, garland-makers, wholesale buyers with mobile carts, truck unloading) is extraordinary for documentary photography; visiting the flower market at 3–5am provides Bangkok's most visually dense photography environment while requiring early wakeup; (4) Bangkok morning market ecosystem: neighborhood wet markets (talat sod) throughout Bangkok operate 5–9am with peak activity 6–8am; morning markets document Bangkok's food supply chain — vendors arranging produce, wholesale buyers, motorbike delivery networks, early worker customers; the Saphan Daeng market (Samrong area, BTS Samrong line, walkable from station), Or Tor Kor's early morning activity, and neighborhood markets near Ari or Ekkamai BTS are accessible to visitors staying on the BTS line; (5) Bangkok rooftop sunrise: several Bangkok rooftop venues open for breakfast with views: Lebua State Tower (Sky Bar area, breakfast service from 7am — check current schedule), Arun Residence Hotel's rooftop (Tha Tien area, river view, breakfast service), and hotel-specific rooftop breakfast programs throughout the Charoenkrung and Silom areas; hotel rooftop breakfast sunrise (6:30–8am) provides controlled, comfortable access to Bangkok's morning light.",
    tip: "Bangkok sunrise photography logistics: (1) Transport to sunrise locations: Grab availability is excellent in Bangkok from 4am onward; pricing before 6am is lower than peak hours (no surge pricing at early morning); specify destination clearly in Grab app (Tha Tien Pier rather than just 'Wat Arun'); (2) Flower market (Pak Klong Talat) practical: arrive 2–4am for peak wholesale chaos (most visual but requires very early night); 4–6am is still active but calming; 6–8am vendors close and day vendors set up; the market is safe for visitors at all hours (vendor crowd provides safety); bring a camera with good low-light capability (available light is incandescent/fluorescent wholesale lighting before dawn); (3) Wat Saket sunrise tickets: the Golden Mount summit provides Bangkok's best elevated sunrise view; the mountain's 300+ steps require physical ability; arrive before 8am when the sunrise light is active; the temple opens at approximately 7:30–8am (check current hours); (4) Monk alms round documentation: photographing the morning alms round (tak bat) at Rattanakosin area temples requires respectful, non-intrusive positioning; maintain 3–5 meter distance from the giving ritual; do not use flash; do not position yourself between the layperson giving and the monk receiving; the photography itself is not prohibited but disruption of the ceremony is inappropriate; (5) Weather considerations: Bangkok's clearest skies for sunrise photography are in November–February (cool dry season); the monsoon season (May–October) provides dramatic cloud formations but more variable sunrise conditions; haze season (February–April, burning season) creates atmospheric softness that produces painterly photography conditions at golden hour but reduces distant view clarity.",
  },
  {
    name: "Bangkok Street Photography — Neighborhoods, Ethics & What Makes Bangkok Uniquely Photogenic",
    emoji: "📸",
    area: "Bangkok's most photogenic street photography neighborhoods: Talat Noi (narrow sois, heritage shophouses, Thai-Chinese characters, mural art — consistently ranked Bangkok's best street photography neighborhood); Yaowarat/Chinatown (commercial intensity, Chinese signage, market vendors, food stalls — classic Bangkok street energy); Banglamphu/Khao San area (backpacker culture meets Thai residential life, Khao San Road itself + Soi Rambuttri's more relaxed atmosphere); Phra Khanong/Ekkamai residential streets (less-photographed, authentic Bangkok working-class neighborhood character); Pak Klong Talat flower market at dawn (3–6am); Bang Krachao 'Green Lung' cycling paths and village areas (rural Bangkok character within the city boundary); On Nut area morning markets (Japanese expat community meets Thai residential life); Charoenkrung Soi 42 area (heritage buildings, artisan workshops, new creative businesses)",
    price: "Street photography access costs: all listed neighborhoods: free (public streets); Talat Noi area cafés for rest/coffee: ฿60–150; Yaowarat evening (dinner budget): ฿150–400; Bang Krachao bicycle rental: ฿60–100 per day at ferry landing; mural photography tours (if using organized tour for the mural districts): ฿500–1,200 for guided mural walks; professional photography workshop in Bangkok: ฿2,000–8,000 for group day workshop; photography equipment theft insurance: Bangkok's street markets (bag snatching by motorcycle) is a genuine risk — secure camera straps and awareness of surroundings",
    why: "Bangkok's street photography potential is extraordinary precisely because of the visual density that can feel overwhelming to live in: (1) What makes Bangkok photogenic: Bangkok's street life layers: (a) physical — dense signage mixing Thai script, Chinese characters, English transliterations, and corporate logos; ornate temple architecture visible from mundane streets; canal-side wooden architecture beside glass towers; (b) human — market vendors' physical displays of arranged produce/goods; spirit house rituals at road level; monk robes as color accents; motorcycle taxis' orange vests; (c) temporal — Bangkok's rapid development creates juxtaposition of old shophouses next to new towers, traditional vendors beside global brand stores; (2) Talat Noi for depth: Talat Noi (the 'small market' heritage neighborhood south of the main Yaowarat road) is consistently identified by serious Bangkok street photographers as the city's richest neighborhood for documentary work; the density of 19th-century Thai-Chinese shophouses, active traditional trades (auto parts workshops, printing shops, tinsmith workshops), and increasingly — heritage cafés attracting a young Thai creative class — creates layered photographic subjects; murals added throughout the neighborhood in recent years provide color composition elements; (3) Street photography ethics in Thailand: photographing Thai people in public is legally permitted; however, photographing monks (particularly in devotional contexts) without respectful distance is inappropriate; photographing Buddha images in disrespectful ways risks legal complications under laws prohibiting disrespect to Buddhism; asking permission before photographing individual market vendors is respectful (though not required); offering to show the image on your camera display is universally appreciated and usually produces warmth; (4) Bangkok's light and color: Bangkok's visual environment is intensely saturated by international standards — the combination of tropical light intensity, bright paint colors on shophouses and signage, Thai decorative traditions (golds, reds, greens in temples and spirit houses), and commercial signage creates photographic subjects with unusual color density; shooting in RAW and adjusting saturation down in post-processing often produces more accurate renditions than JPEG processing; (5) Street food photography: Bangkok's street food environment is among Asia's most photographically rich — the visual presentation of Thai dishes (herb garnishes, chilies, aromatic leaves, contrast of sauces against white rice), the cooking process (wok flames, smoking coal grills, noodle pulling), and the vendor/diner interaction all provide layered photographic subjects; morning market cooking setups (6–9am) are the richest food photography context with best light.",
    tip: "Bangkok street photography practical: (1) Lens recommendation: a 35mm or 50mm equivalent (on full-frame) is the most versatile Bangkok street photography focal length — close enough to capture detail without invasion, wide enough for environmental context; for Yaowarat night photography, fast glass (f/1.4–f/2) is useful; (2) Camera security: Bangkok has bag/camera snatching from motorcycles on busy streets — wear camera straps around neck rather than shoulder; in market areas, hold camera deliberately; busy Chatuchak and tourist zone pickpocketing is a known risk; (3) Best camera settings for Bangkok streets: for daytime market photography — f/8, ISO 400, 1/500s as a starting point; for low-light night market work — f/2.8 or wider, ISO 1600–3200, accept motion blur for documentary effect or embrace freeze-motion with higher ISO; (4) Smartphone photography in Bangkok: Bangkok's strong Wi-Fi and cellular coverage throughout tourist areas makes cloud backup during the day practical; smartphone cameras (iPhone, Samsung) produce impressive Bangkok street images and attract less attention from subjects than larger cameras; (5) Photo editing Thai images: Bangkok's scenes often benefit from slightly reduced exposure in editing (the tropical light tends to overexpose highlights on Thai temple gold and white temple walls); bringing out shadow detail reveals the narrative content in darker market areas.",
  },
  {
    name: "Bangkok's Most Instagrammed Spots vs. Reality — Managing Expectations at Popular Locations",
    emoji: "🤳",
    area: "Bangkok's most visited photography locations: Grand Palace (No. 1 — 8–14 million visitors/year, extremely crowded 9am–2pm); Wat Pho (reclining Buddha — consistently top-10 global Instagram temple, managed crowds but significant line); Wat Arun from river (east bank riverfront, accessible and rewarding at all hours); Chatuchak Weekend Market (photography crowds build after 11am, pre-10am is manageable); Bang Krachao cycling (Instagram-worthy: green lanes, local market, village temples — genuinely uncrowded outside weekends); Golden Mount/Wat Saket panorama (less Instagram-famous than other temples but better panoramic access); Phra Nakhon area streets (Bamrung Mueang Buddha Street, heritage streets less Instagram-affected); Temple of the Emerald Buddha interior (no photography allowed inside the ubosot, only exterior)",
    price: "Bangkok major attraction current fees (verify before visiting — fees periodically increase): Grand Palace/Wat Phra Kaew: ฿500 per person; Wat Arun: ฿100 per person; Wat Pho: ฿200 per person; Golden Mount (Wat Saket): ฿50; Jim Thompson House: ฿200 (adult); National Museum: ฿200 (foreigner price); Vimanmek Mansion (when open): included in Grand Palace ticket; Museum of Siam: ฿100; Erawan Museum (Samut Prakan, south of Bangkok): ฿400; MOCA Bangkok (Museum of Contemporary Art): ฿250; Safari World (outer Bangkok): ฿1,000–1,500 for combined zoo/marine park",
    why: "Managing Bangkok photography expectations at major spots prevents disappointment and guides toward more rewarding alternatives: (1) Grand Palace photography reality: the Grand Palace complex is extraordinary but the photography challenge is severe — crowds (particularly tour groups from Chinese and Korean markets) arrive by 9am; interior temple (Wat Phra Kaew, home to the Emerald Buddha) prohibits photography inside; the most photographed exterior elements (the golden chedis, the green temple roofline) are stunning but require patience and positioning to isolate from the crowd; arriving at 8am (opening time) provides 30–45 minutes before the crowd peaks; late afternoon (3–4pm) sees some crowd reduction; the Grand Palace complex is genuinely worth visiting despite crowds; (2) Wat Arun — actually manages crowd well: Wat Arun's riverside position (requiring ferry crossing) naturally limits tourist volume relative to its photographic fame; the exterior mosaic work and the climb to the top terraces are accessible during moderate crowds; the best photography of Wat Arun is NOT from inside the complex but from the opposite bank (Tha Tien Pier area) — this angle is also free of admission fees; (3) The uncrowded Bangkok photography alternative: Bangkok has extraordinary photography beyond the Instagram circuit; Talat Noi neighborhood, Khlong Toei market (Bangkok's largest fresh market, NOT tourist-visited, challenging but extraordinary), the Dusit area heritage buildings, Nonthaburi's old town market — all provide Bangkok's authentic visual content without crowd competition; (4) Chatuchak photography timing: Chatuchak Weekend Market has serious photography potential in specific sections (craft vendors, antique stalls, plant sections, the interior covered alley areas); best photography timing is before 10am when crowd density is manageable; by noon the market is at tourist-density and photographic composition requires more patience; (5) Bangkok's lesser-photographed visual treasures: Klong Lat Mayom floating market (Taling Chan district, weekend only) — genuinely functional canal-side market without heavy tourist overlay; Wat Ratchanatdaram (Ratanachai/Democracy Monument area) — ornately decorated temple with Loha Prasat (metal castle) — regularly overlooked by tourist circuits; Pak Klong Talat's wholesale flower market at dawn — maximum Bangkok visual density with minimum tourist photography competition.",
    tip: "Bangkok photography crowd management: (1) Grand Palace: arrive before 8:30am (gates open 8am); use the gate nearest to Na Phra Lan Road (the main entrance has longer queues); the first 30 minutes are the most navigable; (2) Dress code strictly enforced at Grand Palace, Wat Pho, and Wat Arun: shoulders and knees must be covered; temple sarongs available for rent at the entrance (฿50–100, leave deposit) but bringing your own lightweight long pants/scarf is more comfortable; (3) Alternative to Chatuchak crowds: Or Tor Kor Market (adjacent to Chatuchak MRT) is Bangkok's premium fresh food market without the tourist photography crowd — more authentic, fewer competing cameras; (4) Bang Krachao on weekdays: the 'Green Lung' cycling area is genuinely peaceful on weekday mornings (Tuesday–Thursday); weekend mornings see Bangkok residents cycling; avoid weekend afternoons when it becomes significantly busier; (5) Seasonal photography: Bangkok's monsoon season (June–September) creates dramatic cloud formations that complement the city's vertical skyline — some of Bangkok's best skyline photography happens during or after afternoon monsoon rains when the air is washed clear and the light is extraordinary.",
  },
];

export function BangkokSunrise() {
  return (
    <div className="rounded-2xl border border-orange-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-orange-700 mb-3">
        🌅 Bangkok photography guide — sunrise spots, street photography ethics & instagrammed locations reality
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-orange-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-orange-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-orange-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
