const SPOTS = [
  {
    name: "Bangkok's Muslim Community — Masjid, Muslim Markets & Thailand's Southern Connection",
    emoji: "🕌",
    area: "Bangkok Muslim community centers: Haroon Mosque (Charoenkrung 36, oldest mosque in Bangkok, 1830s, near Silom area); Masjid Bangkok Noi (Thonburi, across river); Masjid Tonson (Ploenchit, near Rama I Road); Masjid Mekah (Nana, Sukhumvit area); Bangkok Central Mosque (Din Daeng); Muslim food district: Nana area (Sukhumvit 3, concentrated South Asian + Arab Muslim community); Ban Krua (traditional Muslim weaving village, adjacent Pathum Wan, beside National Stadium BTS); On Nut area mosques; Phra Khanong Muslim community; Suan Luang district; Samut Prakan Muslim communities",
    price: "Haroon Mosque entry: free (open to non-Muslim visitors outside prayer times, modest dress required); Ban Krua weaving workshop tour (community-organized): free–฿100 suggested donation; Nana area Muslim restaurants: ฿80–200/dish (similar to Bangkok average, halal certified); Muslim-specific products: Haroon mosque area shops and supermarkets carry Indonesian, Malaysian, Middle Eastern packaged goods; Bangkok Islamic Center publications: minimal cost",
    why: "Bangkok has a significant Muslim community representing approximately 6–7% of Bangkok's population with centuries of history: (1) Bangkok's Muslim origin stories: Bangkok's Muslim community predates the city itself; Muslim merchants (Arab, Malay, Indian) traded along the Chao Phraya from the Ayutthaya Kingdom period (14th–18th century); the Ban Krua community (the traditional Cham Muslim weaving village directly adjacent to Bangkok's National Stadium) was established by Cham Muslims from Cambodia who aided Thai King Taksin in wars; the community has maintained continuous residence for 200+ years in the same location; (2) Thailand's deep south Muslim majority: southern Thailand (Pattani, Yala, Narathiwat provinces, adjacent to Malaysia) is majority Malay-Muslim; the relationship between Bangkok's central Thai-Buddhist government and the southern Muslim separatist movement is a sensitive ongoing political issue; the Bangkok Muslim community is mostly Thai-Muslim (not Malay separatist aligned), but understanding this context provides essential background; (3) Haroon Mosque's community function: Haroon Mosque (established 1830s, rebuilt multiple times, current structure from 2004) serves as the center of Bangkok's Arab/South Asian Muslim community; the mosque has a significant number of Pakistani, Bangladeshi, and Arab worshippers alongside Thai Muslims; non-Muslim visitors are welcomed outside the 5 daily prayer times; observing Friday prayers (the largest attendance) from respectful distance outside provides a significant Bangkok cultural observation; (4) Ban Krua's unique status: Ban Krua (บ้านครัว) is one of Bangkok's oldest established communities, a Muslim weaving village that has managed to survive the commercial development of adjacent Pathum Wan district; the community still produces traditional Thai-Muslim textiles; visits (organized through the community) provide access to cottage-industry textile production; (5) Bangkok's Arab community in Nana: the Sukhumvit 3 (Nana) area has Bangkok's most visible Arab expat community; Middle Eastern restaurants, hookahs lounges, Arabic-language signage, and Halal food shops create a distinctly different Bangkok neighborhood character; the area serves Arab tourists (particularly from Gulf countries) and Bangkok's resident Arab community.",
    tip: "Bangkok mosque and Muslim community visit guidance: (1) Haroon Mosque visiting protocol: non-Muslim visitors are welcome to view the mosque exterior and learn about Bangkok Muslim history; entering the mosque for prayer observation requires invitation or prior arrangement with the mosque administration; women must wear hijab (bring or purchase one at adjacent shops); men must remove shoes and wear long trousers; (2) Ban Krua access: Ban Krua is directly accessible from the National Stadium BTS station (walk north, cross the canal bridge); the community is small and unpublicized; approaching the community respectfully during daylight hours (9am–4pm) and visiting the weaving households that display silk and cotton cloth is the standard approach; (3) Friday prayer timing in Nana: the Nana area's mosque (Masjid Mekah, adjacent to Nana BTS) has Friday midday prayer (Jumu'ah) with significant attendance from the South Asian and Arab community; the area around the mosque is busy and parking-restricted during Friday prayer (approximately 12pm–1:30pm); this is worth noting for Sukhumvit area navigation; (4) Ramadan in Bangkok: during Ramadan (Islamic month of fasting), Bangkok's Muslim community has visible cultural changes; evening iftar (fast-breaking) at sunset creates festive atmosphere at Haroon Mosque and Nana area Muslim restaurants; visitors are sometimes welcomed to share iftar meals; the community's hospitality during Ramadan evening is distinctive; (5) Bangkok Muslim food safety for travelers: the Thai government's Halal certification system (Central Islamic Council of Thailand) certifies restaurants and food products with a halal logo; looking for the official Thai halal certification logo (rather than self-declared halal) provides the most reliable halal assurance; the Nana area South Asian restaurants are predominantly halal in practice even without formal certification due to community standards.",
  },
  {
    name: "Bangkok's Hindu & Sikh Community — Erawan Shrine, Sri Mahamariamman Temple",
    emoji: "🛕",
    area: "Bangkok Hindu & Sikh sites: Sri Mahamariamman Temple (Silom Road, also called Wat Khaek, Tamil Hindu temple founded 1879); Erawan Shrine (Ratchaprasong intersection, Brahman-Hindu deity Phra Brahma, Bangkok's most famous non-Buddhist religious site); Vishnu Shrine (Ratchadamri Road, near Lumpini); Narayana Shrine (multiple locations); Ayyappan Temple (Silom area); Central Sikh Temple (Surat Thani Road area, near Silom); Indian community concentration: lower Sukhumvit, Silom/Bangrak area; Nana area: diverse South Asian businesses; Pahurat Indian Market (Phahurat Road, near Grand Palace area, Bangkok's 'Little India')",
    price: "Sri Mahamariamman Temple entry: free; Erawan Shrine entry: free; Thai classical dance offering at Erawan (sponsor): ฿60–240 per dance performance; garland offerings (marigold/jasmine): ฿20–100; Pahurat Indian Market: Indian textiles, spices, and products at wholesale-adjacent pricing; Silom area Indian restaurants: ฿150–400/dish for curry meals; silk purchases for puja: available at Sri Mahamariamman area shops",
    why: "Bangkok's Hindu heritage is deep and visible throughout the city's religious architecture: (1) Hindu-Buddhist synthesis in Thai culture: Thai Buddhism (Theravada) coexists with significant Hindu cosmological elements; Thai royal ceremony, traditional dance (Khon), and many temple design elements draw from Hindu mythology (Ramayana/Ramakien, the Four-Faced Brahma deity Erawan); the synthesis is not syncretic borrowing but deep historical integration from the Khmer period (Angkor) and Indian merchant influence; (2) Sri Mahamariamman Temple: founded by Tamil Hindu merchants in 1879, Silom's Sri Mahamariamman Temple (Wat Khaek in Thai) is Bangkok's oldest and most active Hindu temple; the temple's architectural style (South Indian Dravidian gopuram/tower) is visually distinct from Thai Buddhist temples; the temple is active with daily puja offerings; Thai Buddhists also visit the temple as a merit-making destination (the syncretic behavior is well-established); (3) Erawan Shrine's Brahman-Hindu identity: Erawan Shrine's central figure is Phra Phrom (Brahma in the 4-faced form); the shrine was built according to Brahman (Hindu priestly) ritual prescription, not Buddhist ritual; the Thai classical dancers who perform at the shrine perform for Brahman cosmological deities; this Brahman element within Bangkok's Thai-Buddhist city is significant cultural complexity; (4) Pahurat 'Little India': Bangkok's Pahurat area (Phahurat Road, near the Grand Palace and Chinatown) is a compact district of Indian textile merchants, spice shops, and Sikh and Hindu community organizations; the area developed as South Indian and Punjabi merchants established wholesale operations for textiles, gold, and spices in the early 20th century; (5) Sikh community: Bangkok has an established Sikh community (Punjabi origin) centered on the Central Sikh Temple (Silom area); the Sikh tradition of free community food (langar) at Gurdwara is maintained; the community is small but has maintained distinct identity for over a century.",
    tip: "Bangkok Hindu and Sikh site visits: (1) Sri Mahamariamman Temple dress requirements: the temple requires modest dress (shoulders covered, lower body covered to at least knee) for all visitors; rental of temple garments is sometimes available at the entrance; the temple's interior features elaborate South Indian sculptural programs — understanding the iconography (Mariamman as Devi/goddess of rain and disease protection, the subsidiary shrines to Ganesh, Murugan) enriches the visit; (2) Erawan Shrine photography etiquette: photography at Erawan Shrine is permitted and common; the active ceremonial atmosphere (vendors selling garlands, worshippers praying, Thai dancers performing) creates a continuous photographic scene; photographing active worshippers in close-up without permission is considered intrusive; photographing the shrine itself from the perimeter is universally acceptable; (3) Pahurat market visiting: Pahurat Indian Market is most active on weekdays (wholesale buyers active); weekend visits are accessible for retail; the market sells Indian textiles (sari, salwar kameez fabric, silk) at significantly below retail prices; understanding which section sells what (clothing fabric is separate from spice/food sections) before entering reduces navigation confusion; (4) Sikh Gurdwara visit: Bangkok's Gurdwara welcomes non-Sikh visitors; head covering is required inside (provided at entrance); the tradition of langar (free community meal served to all visitors regardless of religion) means visitors can participate in a simple community meal; calling ahead to confirm visiting hours and langar timing is recommended; (5) Brahman rituals in Thai ceremony: Bangkok's royal ceremonies (Royal Ploughing Ceremony, Royal Barge Procession) involve Brahman priests (brahmin, a hereditary priestly class maintained by the Thai royal court) performing Hindu-origin rituals alongside Buddhist monks; this dual religious function in state ceremony is unique to Thailand and provides a window into how Hindu cosmology was incorporated into Thai statecraft.",
  },
  {
    name: "Bangkok's Christian Community — Churches, Missionaries & Colonial History",
    emoji: "⛪",
    area: "Bangkok Christian sites: Assumption Cathedral (Charoen Krung 38, Bangkok's oldest Catholic church, 1821 original foundation, present structure 1910, French Gothic); Holy Rosary Church (Wangnoi Pier, near Memorial Bridge, Portuguese Catholic community, 1787); Christ Church Bangkok (Convent Road, Silom, Anglican/Episcopal, established 1864, British community); Alliance Française (Sathorn, French cultural hub adjacent to Catholic community history); Bangkok's international Christian churches: multiple non-denominational and evangelical congregations serving expat communities; Korean evangelical churches near Korean expat areas; Christian hospitals: McCormick Hospital (Chiang Mai origin), Bangkok Christian Hospital (Silom area, Christian mission founding)",
    price: "Assumption Cathedral visit: free; Holy Rosary Church visit: free; Sunday service attendance: always free and welcome; Bangkok Christian Hospital (BCH) services: medical fees apply, Christian mission heritage; Christmas celebrations at major churches: free public events; Christian English-language services: multiple Sunday morning services (check specific churches for times and denominations)",
    why: "Bangkok's Christian heritage connects to Thailand's history of Western missionary and colonial contact: (1) Portuguese legacy: Bangkok's oldest Christian communities trace to Portuguese traders and missionaries; the Holy Rosary Church (Tha Kien, near Memorial Bridge, established 1787) was built by the Portuguese community immediately after Bangkok's founding in 1782; the Portuguese (who had assisted King Rama I in political refuge) received land and worship rights; the current ornate 19th-century structure is a significant baroque church; (2) French Catholic mission history: French Catholic missionaries (particularly MEP — Missions Etrangères de Paris) established Bangkok's Catholic educational institutions; Assumption College (Christian Brothers school), Assumption University, and various Bangkok private schools trace Catholic mission founding; (3) Protestant missionary legacy: American Protestant missionaries (from Presbyterian and other denominations) arrived in Thailand in the 1830s; the missionary medical work (establishing Thailand's first Western-medicine hospitals) and educational contribution (Silpakorn University has mission school heritage) affected modern Thai education and healthcare significantly; (4) Christ Church Bangkok as expat community anchor: Christ Church Bangkok (Anglican, Convent Road, Silom) has served Bangkok's British and English-speaking expat community continuously since 1864; English-language services, burial records, and community functions provide heritage continuity for the British community in Bangkok; (5) Modern evangelical growth: Thailand's evangelical Protestant and charismatic church community has grown significantly since 1980 (though Christians remain less than 1% of Thailand's population); Bangkok has large multi-campus international churches (Hope Bangkok, Abundant Life Church) with significant Thai and international congregations; Korean evangelical churches near Ekkamai serve the Korean community.",
    tip: "Bangkok church visits and Christian heritage exploration: (1) Assumption Cathedral visiting: Assumption Cathedral (Bangrak, Charoen Krung 38, near Sathorn) is Bangkok's most architecturally significant Catholic church; the French Gothic interior (stained glass, ornate altar) is well-maintained; visiting during weekday morning hours (not service times) allows quiet appreciation; the adjacent Assumption College and the surrounding Old Bangrak area constitute Bangkok's historical Catholic district worth exploring on foot; (2) Holy Rosary Christmas: Holy Rosary Church's Christmas celebrations (particularly Midnight Mass, December 24–25) are attended by both Bangkok Catholics and non-Catholic Thais interested in the cultural event; the church's Christmas decoration is elaborate; (3) Sunday English services: Bangkok's international English-language churches serve as social anchors for the expat community; attending a Sunday service (regardless of personal faith) provides exposure to Bangkok's expat community self-organizing; most churches welcome visitors without expectation; (4) Bangkok Christian Hospital history: Bangkok Christian Hospital (BCH, Silom Road, established 1949 by American Protestant missionary organization) maintains its religious identity while operating as a full modern hospital; the hospital's lower prices relative to international-branded hospitals and its English-language capability make it an option for Bangkok visitors; (5) Church heritage walks: walking from Holy Rosary Church (Wangnoi Pier) along the river north to Assumption Cathedral (Charoen Krung 38) and continuing to Haroon Mosque (Charoen Krung 36) passes through Bangkok's most concentrated religious heritage corridor; within 2km, the walk crosses Portuguese-origin Catholic, French-influenced Catholic, and Thai Muslim religious architecture — a cross-cultural heritage walk unavailable in any Western city.",
  },
];

export function BangkokIslamicCulture() {
  return (
    <div className="rounded-2xl border border-teal-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-teal-700 mb-3">
        🕌 Bangkok religious diversity — Muslim community, Hindu temples & Christian heritage
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-teal-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-teal-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-teal-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
