const SPOTS = [
  {
    name: "Bangkok Condo vs. House — What Foreigners Can (and Cannot) Own in Thailand",
    emoji: "🏢",
    area: "Bangkok foreign property ownership: condominiums legal for foreign ownership (49% foreign quota limit per building); land and houses not legal for foreign ownership outright; legal foreign structures: long-term land lease (30 years + 30-year renewable options), Thai company structure (complex, legal risk), FETF (Foreign Exchange Transfer Form) for condo purchase; property search: DDproperty.com (Thailand's largest property portal, English available), FazWaz (international focus, English primary), Hipflat (condo specialist), Dot Property Thailand; major Bangkok residential areas for expats: Sukhumvit 10–63 corridor (international focus), Silom/Sathon (business district), Sathorn (luxury, embassies), Ari/Samsen Nai (younger expat, local character), Thong Lo/Ekkamai (Japanese expat concentration), On Nut (value BTS area), Ratchada/Ladprao (Thai middle-class area, lower expat density)",
    price: "Bangkok condo purchase price: ฿70,000–350,000/sqm depending on area and quality; Sukhumvit prime (Asok, Phrom Phong, Thong Lo): ฿150,000–350,000/sqm; On Nut/Udom Suk: ฿80,000–130,000/sqm; New development launch (off-plan): typically 10–20% below completed building price; Studio (30sqm) typical: ฿2.5M–6M; 1BR (45–55sqm) typical: ฿4M–12M; 2BR (70–90sqm) typical: ฿6M–20M; Gross rental yield Bangkok: 3–6% typical; Transfer fee: 2% of appraised value; Specific Business Tax: 3.3% (if sold within 5 years); Stamp duty: 0.5% (if held 5+ years); Agent commission: typically 2–3% (paid by seller)",
    why: "Bangkok's condominium market is one of Asia's most foreigner-accessible real estate markets: (1) Legal foreign ownership: Thai law allows foreigners to own condominium units outright (freehold) with the only restriction being that no more than 49% of a building's saleable area can be foreign-owned; the remaining 51% must remain in Thai hands; a condominium with the full foreign quota sold is often called 'quota full' and requires either finding a quota that has opened through resale or purchasing via a Thai entity; (2) FETF requirement for foreign purchase: foreigners purchasing Bangkok condos must demonstrate that the purchase funds originated outside Thailand; the Foreign Exchange Transfer Form (FETF or Tor Tor 3) from the receiving Thai bank documents this; the FETF must be obtained at the time of fund transfer — retroactive documentation is not accepted; this requirement ensures the purchase is funded by foreign-sourced income or savings (not Thai-sourced funds); (3) Bangkok vs. provincial property: Bangkok condominiums in prime locations (Sukhumvit, Silom) have maintained values better than provincial Thai resort markets (Pattaya, Phuket) which experienced more significant value corrections; Bangkok's large domestic rental demand (from Thai professionals and expats) provides more stable rental income than resort markets; (4) Leasehold alternative for land: foreigners wanting a house with land access must use the 30-year leasehold structure (registered with the Land Office) with optional 30-year renewal clauses; the legal enforceability of renewal clauses is debated among Thai property lawyers; consulting a Bangkok property lawyer (not just a real estate agent) before entering a leasehold arrangement is strongly recommended; (5) Off-plan Bangkok condo market: Bangkok's active new condominium launch market offers off-plan units at developer pricing (often 10–20% below completed building prices); off-plan purchases require deposits (typically 10–30%) with construction completion risk; major Thai developers (Sansiri, AP Thailand, Ananda, Supalai) have completion track records; smaller developers carry higher completion risk.",
    tip: "Bangkok property purchase practical guidance: (1) Due diligence on building's foreign quota: before committing to purchase any Bangkok condo, verify the current foreign quota availability at the Condominium Juristic Person (the building's management); also verify the exact unit's registered ownership (Thai or foreign quota); this can be checked at the Land Office or through the building management; (2) Transfer fee and tax calculation: Bangkok property transactions have significant transfer costs: 2% transfer fee + either 3.3% SBT (if sold within 5 years of last transfer) or 0.5% stamp duty + withholding tax (calculated on assessed value); getting precise cost calculations for a specific property before signing prevents surprises; (3) Property agent selection: Bangkok has thousands of real estate agents operating with minimal regulation; licensed agents (from the Real Estate Broker Association of Thailand, REBA) provide a baseline credential; expat communities on Facebook (Bangkok Expat Properties) and review sites help identify reputable agents; be aware that Bangkok real estate agents are typically paid by the seller and incentivized toward higher prices; (4) Rental management if non-resident: purchasing Bangkok property for rental requires either self-management (requiring physical presence) or professional property management (typically 8–12% of rental income as management fee); reputable Bangkok property managers (DDproperty management, Prism Property, specialist firms) handle tenant finding, maintenance, and legal compliance; (5) Thai inheritance planning for foreign condo owners: foreign-owned Thai condominiums can be inherited by foreign beneficiaries; however, Thai succession law and the condominium act's foreign quota rules apply; foreign heirs may need to sell within a specific period if the foreign quota in the building is already full; consulting a Bangkok lawyer specializing in property with foreign succession planning before purchase addresses this risk.",
  },
  {
    name: "Bangkok Long-Term Rental — Serviced Apartments vs. Condos vs. Houses",
    emoji: "🏠",
    area: "Bangkok long-term rental areas by expat profile: Japanese community: Thong Lo, Ekkamai, Phrom Phong (Japanese schools, restaurants, cultural institutions); American/European community: Sathorn, Silom, Wireless Road (embassies, offices); Korean community: Ekkamai, Sukhumvit 63; Family-oriented (international schools): Sukhumvit 71 (Phra Khanong, near Bangkok Prep and NIST), On Nut area, Phra Khanong; Budget expat: Ari, Ratchathewi, On Nut, Udom Suk; Thai-mixed residential: Lat Phrao, Bang Khen, Ram Inthra; Serviced apartment brands: Amari Residences, Somerset, Citadines, Ascott, Oakwood; rental platforms: Hipflat, DDproperty, Facebook Marketplace Bangkok, Baania.com, Thai-language apartments.com",
    price: "Studio apartment (35–45sqm, no furniture): ฿7,000–18,000/month; Studio (furnished, BTS access): ฿10,000–25,000/month; 1BR apartment (50–65sqm, furnished): ฿15,000–40,000/month; 2BR apartment (70–90sqm, good area): ฿25,000–70,000/month; Serviced apartment (with daily cleaning, amenities): ฿25,000–100,000/month; Townhouse (3 floors, 120–180sqm, with garden): ฿25,000–60,000/month; Monthly condo with pool/gym (mid-range): ฿15,000–35,000; Security deposit: 2 months; Advance rent: 1 month; Total move-in cost: 3 months rent upfront",
    why: "Bangkok's long-term rental market offers extraordinary value relative to major Western cities: (1) Value proposition: a Bangkok two-bedroom apartment near BTS with pool, fitness center, and security for ฿30,000–40,000/month (approximately USD $850–1,100) has no direct equivalent value in London ($3,500+), New York ($4,000+), or Sydney ($3,000+); this value makes Bangkok one of the world's best quality-of-life-per-dollar cities for long-term renters; (2) Serviced vs. conventional rental: serviced apartments include daily room cleaning, concierge, utilities management, and hotel-like amenities at ฿25,000–60,000/month; conventional condo rentals require the tenant to arrange utilities (electricity, water, internet), hire cleaning services, and manage maintenance themselves but offer more space for the price; the choice reflects how much management the renter wants to handle; (3) Unfurnished vs. furnished rental market: Bangkok has both furnished (most common for expat-targeting buildings) and unfurnished rentals; unfurnished units are often 15–25% cheaper but require furniture investment; for stays under 2 years, furnished rental is typically more economical; for longer stays, purchasing furniture (IKEA Bangkok, second-hand Facebook marketplace Bangkok groups) and unfurnished rental provides better value; (4) Townhouse market: Bangkok's townhouse rental market (3-4 story townhouses in Thai residential neighborhoods) offers significantly more space than apartments for similar or lower cost; the tradeoffs are typically: less international community, less proximity to BTS, need for vehicle, more maintenance responsibility; for family-oriented or space-prioritizing expats, townhouse rental in Bang Kapi, Ratchada, or outer Sukhumvit areas provides enormous living space at budget prices; (5) Lease negotiations: Bangkok landlords typically want 1-year leases; negotiating longer leases (2–3 years) in exchange for rental rate discounts (5–15%) is possible; fully furnished rental where the tenant wants to substitute their own furniture requires explicit lease permission; damage liability for furnished rentals requires inventory documentation at move-in.",
    tip: "Bangkok rental process practical guide: (1) Lease language and translation: Bangkok residential leases are typically in Thai; English lease addendums or full English translations are common in expat-targeting buildings but not guaranteed in local Thai landlord situations; having a Thai-English bilingual person review any Thai-language lease clause before signing is essential for understanding termination conditions, damage liability, and utility charge structure; (2) Electricity billing: Bangkok electricity billing for condo/apartment rentals varies significantly; Bangkok Metropolitan Electricity Authority (MEA) direct billing (the rate is ฿3.50–4.50/unit depending on usage volume) vs. landlord billing (sometimes ฿5–7/unit, building profit margin) creates significant cost differences; asking whether the electricity rate is MEA direct or landlord billed is an important rental negotiation point; (3) Internet provider installation: Bangkok's two major residential fiber internet providers are AIS Fiber and True Move H Fiber (both offer 100Mbps–1Gbps residential plans, ฿690–1,200/month); some Bangkok condo buildings have exclusive provider contracts; asking about internet provider availability before rental commitment (particularly for remote workers with provider preferences) is practical; (4) Pet-friendly rental difficulty: the majority of Bangkok condo rentals explicitly prohibit pets; finding pet-friendly Bangkok rentals requires specific search filtering; Facebook group 'Pet Friendly Apartments Bangkok' has curated listings; landlords in smaller townhouse situations are often more flexible than large condo buildings with juristic person rules; (5) Room condition documentation: photographing every pre-existing damage (walls, appliances, furniture) with timestamps at move-in and sending the photos to the landlord by LINE immediately after moving creates an irrefutable record; this documentation prevents deposit deduction disputes at lease end; this is Bangkok expat community's most consistently recommended practice.",
  },
  {
    name: "Bangkok International Schools — ISB, NIST, Shrewsbury & Costs Overview",
    emoji: "🎓",
    area: "Bangkok international schools map: north Bangkok (Phra Khanong to Ekkamai): NIST International School (Sukhumvit 15), Bangkok Prep School (Sukhumvit 71 area), KIS International School; south Sukhumvit: Shrewsbury International School (Charoen Krung 60, secondary), HeadStart International School; Sathorn/Silom: St. Andrews International School Bangkok, Assumption College; Bangkok International School (BISC, Sukhumvit 107); Chatuchak area: ISB International School of Bangkok (Nichada Thani, Pak Kret, north Bangkok, largest campus, most American curriculum); Nonthaburi: Bangkok Patana School (near ISB area); transport: most international schools operate bus services covering major expat residential areas; British Council, American school, French school, German school, Japanese school KJTS (Ekkamai area) for specific language-curriculum schools",
    price: "ISB (International School of Bangkok, American curriculum): ฿650,000–900,000/year tuition + registration; NIST International School (IB): ฿600,000–850,000/year; Bangkok Patana School (IB + British): ฿550,000–750,000/year; Shrewsbury (British curriculum): ฿450,000–650,000/year; HeadStart (IB): ฿450,000–650,000/year; Additional fees: registration, development fees, activity fees; compare: Singapore equivalent international school ฿1.2–2.5M/year; Bangkok schools 30–60% below Singapore equivalent; School bus (annual): ฿100,000–200,000 depending on route; Lunch program (if applicable): ฿40,000–80,000/year",
    why: "Bangkok's international school ecosystem is one of Southeast Asia's most comprehensive: (1) Curriculum diversity: Bangkok offers essentially every major international curriculum; IB (International Baccalaureate) at NIST, Bangkok Patana, HeadStart; American curriculum at ISB, BISC; British curriculum at Shrewsbury, Bangkok Patana; Cambridge at multiple schools; French curriculum at Lycée Français; German curriculum at Deutsche Schule Bangkok; Japanese curriculum at multiple Japanese schools; Korean curriculum at Korean International School; (2) Bangkok vs. Singapore international school comparison: Singapore's international school system has longer reputation and certain rankings advantages; Bangkok's equivalent schools cost approximately 40–60% less; Bangkok's quality has improved significantly and several Bangkok schools (NIST, Bangkok Patana) appear on international school rankings; for cost-conscious expats, Bangkok-based international education represents significant savings; (3) ISB's unique campus: ISB (International School of Bangkok) at Nichada Thani (Pak Kret, north Bangkok) operates on a large suburban campus with full American high school facilities (sports complexes, performing arts center, extensive facilities); the Nichada Thani gated community surrounding ISB houses a significant American/international expat residential community; (4) Waiting list reality: Bangkok's most popular international schools (NIST, ISB, Bangkok Patana) have significant waiting lists; newly-arrived expats may spend 6–12+ months on waiting lists; planning international school enrollment requires starting the application process before or immediately upon arrival; (5) Thai private school as alternative: Bangkok's elite Thai private bilingual schools (Assumption College, Satri Wittaya, Bangkok Christian College, and high-profile bilingual programs at Thai schools) offer bilingual Thai-English education at 30–60% below international school costs; these schools provide Thai language and cultural immersion alongside English instruction and may suit families planning multi-year Bangkok stays.",
    tip: "Bangkok international school selection process: (1) Application timing: ISB and NIST have annual application windows (typically October–February for the following academic year starting August); applications submitted outside this window go directly to waitlist position; moving Bangkok to school start before August provides the best enrollment chances; (2) Location vs. school priority: deciding whether to prioritize proximity to the chosen school (housing near ISB's Pak Kret campus, or near NIST on Sukhumvit 15) versus preferred residential area is a common expat challenge; most schools provide comprehensive bus routes that service major expat residential areas; the bus commute typically runs 45–90 minutes each way; (3) School visit mandatory: every Bangkok international school offers open days and parent visits before enrollment decisions; visiting in-person provides information impossible to assess from websites — school culture, student body diversity, campus condition, teacher interaction quality, cafeteria, facilities; committing to Bangkok international school fees without visiting is extremely risky; (4) Curriculum portability: if the expat family anticipates moving to another country, choosing an internationally portable curriculum (IB Diploma at NIST or Bangkok Patana) rather than a country-specific curriculum (US, UK) reduces transition friction at the next destination; IB is recognized by universities worldwide; (5) Thai language requirement: many Bangkok international schools now require a Thai language curriculum component (by Thai government mandate); this provides practical Thai language exposure; for shorter-stay expat families, the Thai language requirement varies in depth; some families view the Thai language component positively (useful for daily Bangkok life and cultural understanding) while others prefer to maximize home language instruction time.",
  },
];

export function BangkokHousingRent() {
  return (
    <div className="rounded-2xl border border-violet-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-violet-700 mb-3">
        🏢 Bangkok expat housing — condo ownership rules, long-term rental guide & international schools
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-violet-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-violet-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-violet-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
