const TOPICS = [
  {
    title: "Rattanakosin Island — Bangkok's Historic Core, Royal Grand Palace & Buddhist Heritage",
    emoji: "👑",
    summary: "Rattanakosin Island (Phra Nakhon district) is the original Bangkok urban core, established when King Rama I moved the capital from Thonburi across the Chao Phraya River in 1782: (1) Rattanakosin's geographic definition: Rattanakosin Island is bounded by the Chao Phraya River on the west and south, and by two canals (Khlong Banglamphu on the north, Khlong Ong Ang on the east) forming an artificial island; the island contains Bangkok's most significant royal, religious, and historical monuments within a concentrated 2–3km walkable zone; (2) Grand Palace compound (Phra Borom Maha Ratcha Wang): the Grand Palace is Bangkok's single most-visited attraction — a walled complex containing the Emerald Buddha Temple (Wat Phra Kaew), the former royal residence buildings, the Dusit Maha Prasat throne hall, and numerous royal halls; the Emerald Buddha (Phra Kaew Morakot) is Thailand's most sacred Buddhist image (carved from a single jade nephrite stone approximately 66cm tall, dressed seasonally by the Thai monarch); the Grand Palace complex has not been a primary royal residence since 1925 but remains the ceremonial heart of the Thai state; admission: ฿500 (foreigners), dress code enforced (no shorts, sleeveless shirts; wraps available at entrance); open daily 8:30am–3:30pm; (3) Wat Pho (Temple of the Reclining Buddha): immediately south of the Grand Palace, Wat Pho (Wat Phra Chetuphon Wimon Mangkhalaram) contains the massive Reclining Buddha (46m long, 15m tall, covered in gold leaf, the soles of the feet inlaid with 108 mother-of-pearl symbols of the Buddha); Wat Pho is also the historical center of Thai traditional medicine education; admission ฿200; open daily 8am–6:30pm; the traditional massage school within Wat Pho's grounds is accessible for traditional massage (฿260–310 for 30 minutes); (4) Sanam Luang and surrounding civic space: Sanam Luang (Royal Field, north of Grand Palace) is the large ceremonial space traditionally used for royal cremations, festivals (Vegetarian Festival, kite season March–April), and government ceremonies; the open space and the surrounding administrative buildings (Ministry of Defense, Silpakorn University — Thailand's foremost fine arts university, National Museum) create the civic character of Rattanakosin; (5) Banglamphu and Khao San Road adjacency: the Banglamphu area (north of Rattanakosin Island, Khao San Road) connects historically to Rattanakosin but culturally represents the backpacker district development since the 1970s; the connection means Khao San Road visitors often walk into Rattanakosin for morning temple visits.",
    action: "Rattanakosin timing: arrive at Grand Palace before 9am to beat tour groups; the complex is most crowded 10am–2pm (tour bus peak); Grand Palace opening hours: 8:30am–3:30pm, last entry 3pm; wear respectable clothes or rent a wrap at the entrance; combined Rattanakosin walking route: Grand Palace (2 hours) → Wat Pho (1 hour) → riverside lunch at Wang Lang Pier ferry to Thonburi side for lunch at local market → return; Wat Arun (Temple of Dawn, Thonburi side, ฿100 admission) is a 5-minute cross-river ferry from Tha Tien Pier (฿6); the 3 temples (Grand Palace/Wat Phra Kaew + Wat Pho + Wat Arun) form the essential Rattanakosin circuit; National Museum (free Wednesday): open Wednesday–Sunday 9am–4pm, exceptional Thai art and archaeology collection.",
  },
  {
    title: "Phra Nakhon & Banglamphu — Old Bangkok Neighborhoods, Amulet Market & Democracy Monument",
    emoji: "🏘️",
    summary: "Beyond the Grand Palace, Phra Nakhon district contains Bangkok's most historically layered neighborhood fabric: (1) Khao San Road's transformation: Khao San Road has evolved from a 1970s-1980s budget traveler street with cheap guesthouses and used bookstores into a full entertainment zone; modern Khao San has accommodation across multiple price tiers, Thai and international food, bar culture (ranging from backpacker beer bars to cocktail spots), live music venues, street food, and the characteristic Bangkok backpacker social scene; the road's energy is unique and worth experiencing even without staying there — most organic Bangkok traveler-meeting opportunities happen on Khao San; (2) Tha Prachan and the Amulet Market: Tha Prachan Pier (next to Thammasat University) hosts Bangkok's largest and most authentic amulet market — Thai Buddhist amulets (phra kreung) are powerful objects in Thai religious culture; the market has hundreds of vendors selling amulets ranging from ฿20 common mass-produced pieces to hundreds of thousands of baht for historically significant pieces blessed by famous monks; the buyers are primarily Thai (the market serves Thai religious practice, not tourist shopping); navigating the amulet market as an observer provides insight into Thai Buddhism's material culture; (3) Democracy Monument and political history: Democracy Monument (Mo 1939, Corrado Feroci Italian-Thai design) stands at the center of Ratchadamnoen Klang Avenue (Bangkok's Champs-Élysées equivalent); the monument represents the 1932 constitutional transition; surrounding area is the historic center of Thai political protest (1973, 1976, 1992, 2010 demonstrations); the area has powerful contemporary political history significance in addition to architectural heritage; (4) Phra Sumen Fort and canal heritage: the historic Phra Sumen Fort (1783, octagonal watchtower at the intersection of Khlong Banglamphu and Chao Phraya River) is one of two surviving original Bangkok defensive fortifications; the small Santichaiprakarn Park around the fort is a relaxed Bangkok garden space used by residents; the canal waterway (Khlong Banglamphu) provides context for Bangkok's historic water-based urban life; (5) Bamrung Mueang Road's religious supply market: Bamrung Mueang Road (east of Sanam Luang, running toward the Chinese temple area) is Bangkok's 'Buddha Street' — the entire road is lined with shops selling religious supplies, Buddha images (small to large), monk robes, temple incense, ceremonial objects, and religious paraphernalia; a fascinating window into Thailand's active Buddhist commercial and religious material culture.",
    action: "Khao San Road timing: Khao San is evening-oriented (5pm–3am peak) but manageable all day; the street itself is 200m short (don't expect it to be huge); surrounding streets (Rambuttri Road, Soi Rambuttri, Chakraphong Road) are less chaotic and have better restaurants; Tha Prachan Amulet Market: busiest Saturday–Sunday mornings 8am–noon; Tha Prachan pier accessible by Chao Phraya Express Boat (Maharaj Pier then walk) or by walking from Sanam Luang/Grand Palace area; Bamrung Mueang Road: MRT Sam Yot then walk west; Saochingcha area (Giant Swing, near Bamrung Mueang): the Giant Swing (Sao Ching Cha, red wooden structure) is a ceremonial swing used historically in Brahmin Hindu ceremonies at Wat Suthat Temple across the street — visit both for the heritage context.",
  },
  {
    title: "Dusit — Bangkok's Royal District, Throne Hall & Tree-Lined Boulevard Character",
    emoji: "🌳",
    summary: "Dusit district (northwest of Rattanakosin) is Bangkok's most planned and architecturally European-influenced district, developed primarily under King Rama V (1868–1910): (1) Rama V's urban planning vision: King Chulalongkorn (Rama V) traveled extensively in Europe (the first Thai monarch to do so) and returned with a vision for a European-style royal and governmental district; Dusit was designed with wide boulevards (Ratchadamnoen Avenue was modeled after the Champs-Élysées), royal palaces in a European palace park style, and European neoclassical government buildings; the contrast between Rattanakosin's traditional Thai architecture and Dusit's European-influenced style reflects the two phases of Bangkok's development; (2) Vimanmek Mansion (Amornpiman Mansion complex): Vimanmek Teak Palace (within the Dusit Palace compound) is the world's largest solid teak building — a three-story, 72-room Victorian-style palace built in 1901 by King Rama V; the palace was moved from Koh Si Chang island to Bangkok and served as Rama V's residence until 1906; now a museum open to the public (dress code enforced, traditional Thai music performances within the grounds); admission included with Grand Palace ticket or ฿150 separately; open Tuesday–Sunday 9:30am–3:15pm; (3) Royal Dusit Palace grounds (Dusit Zoo — now relocated): the former Dusit Zoo location (Chitralada Palace grounds adjacent area) is undergoing transformation; Dusit Zoo has relocated to a new site; the green boulevard approach to Dusit Palace and the Chitralada Royal Villa (King's working residence, not open to public) remains the heart of Dusit's royal character; (4) Ratchadamnoen Avenue as Bangkok's ceremonial boulevard: Ratchadamnoen Klang Avenue (the wide tree-lined boulevard connecting Sanam Luang/Royal Field to Democracy Monument and continuing toward the Royal Plaza) is Bangkok's most formal ceremonial space — used for royal ceremonies, National Day parades, and public celebrations; the boulevard architecture (government buildings, military facilities, judicial complex) represents Bangkok's Beaux-Arts influenced phase under Rama V; (5) Ananta Samakhom Throne Hall: the Ananta Samakhom Throne Hall (within the Royal Dusit Palace grounds, facing the Royal Plaza) is Bangkok's most spectacular European-style royal building — Italian Renaissance architecture, Carrara marble, frescoed domes, built 1907–1915 by Italian architects commissioned by Rama V; the throne hall is used for royal ceremonies and national occasions; open to the public as the SUPPORT Museum (Thai handicraft and royal-project exhibition), admission ฿150.",
    action: "Dusit district access: BTS does not reach Dusit directly; options: Grab from Khao San Road (10 minutes, ฿60–80) or taxi; from Ratcha Prarop MRT station, walk or Grab; klong boat on Khlong Saen Saep extends west but not directly to Dusit; Vimanmek Palace hours: Tuesday–Sunday 9:30am–3:15pm, closed Monday; Ananta Samakhom Throne Hall: check current opening hours as national ceremonial events may cause temporary closure; Royal Dusit Palace admission: included with Grand Palace ticket for some venues; Dusit area photograph opportunity: the Royal Plaza (Sanam Luang of Dusit — equestrian statue of King Rama V) provides the clearest view of Ananta Samakhom Throne Hall's facade; early morning (7–9am) light is best for architectural photography.",
  },
];

export function BangkokOldCity() {
  return (
    <div className="rounded-2xl border border-orange-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-orange-700 mb-3">
        👑 Bangkok historic districts — Rattanakosin royal core, Banglamphu old city & Dusit royal boulevard
      </div>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-orange-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-orange-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
