const SPOTS = [
  {
    name: "Thonburi — The Former Capital Across the River, Wat Arun & Canal Communities",
    emoji: "🛶",
    area: "Thonburi district (Krung Thep Yai, Bangkok Noi, Bangkok Yai, Khlong San districts on the west bank of the Chao Phraya River): Wat Arun (Temple of Dawn, west bank opposite Tha Tien Pier, BTS Wongwian Yai then transfer, or cross-river ferry ฿6); Bangkok Noi canal (Khlong Bangkok Noi — entry point for long-tail boat canal tours); Khlong Bangkok Yai canal; Royal Barges National Museum (Khlong Bangkok Noi, traditional Thai royal ceremonial barges preserved, ฿200 admission); Wat Rakhang (Temple of the Bells, historic, near river); Wangderm Palace (former Thonburi-period royal palace, Siriraj Hospital area); Siriraj Hospital (Thailand's oldest hospital, large medical complex, includes 5 medical museums); Wang Lang Market (traditional Bangkok residential market, Siriraj Pier area)",
    price: "Thonburi access costs: cross-river ferry Tha Tien to Wat Arun: ฿6; Chao Phraya Express Boat to Thonburi piers: ฿15–40; long-tail boat canal tour 1–1.5 hours: ฿1,500–2,000 per boat (capacity 6–8 people, negotiate at Tha Chang or Banglamphu piers); Wat Arun admission: ฿100; Royal Barges National Museum: ฿200 adults; Siriraj Hospital Medical Museums (collection of 5 museums including Dr. Sood Sangvichien Forensic Medicine Museum): ฿200 per museum or combination ticket",
    why: "Thonburi is Bangkok's original capital location (under King Taksin, 1767–1782) and represents a fundamentally different urban experience from Bangkok proper: (1) Thonburi's historical pre-eminence: after the fall of Ayutthaya to Burmese invasion (1767), General Taksin led the reunification of Thailand and established Thonburi as the new capital; Thonburi's capital period lasted only 15 years (1767–1782) before King Rama I moved the capital across the river to Bangkok; Thonburi therefore preserves a pre-Bangkok royal and religious heritage; (2) Canal community character: Thonburi's most distinctive feature is its preserved canal (klong) community character; unlike Bangkok proper where many canals were filled for roads, Thonburi retains functioning water-community infrastructure — canal-side wooden houses, klongs used for transport and daily life, floating garden communities; the long-tail canal tour experience is the most authentic remaining interface with Bangkok's original water-city character; (3) Wat Arun's visual significance: Wat Arun (Temple of Dawn, Wat Arun Ratchawararam) is Bangkok's most visually distinctive temple — the central 79-meter Khmer-style prang (tower) is encrusted with Chinese porcelain fragments and colored glass; the temple is best viewed from the Bangkok side of the river (Tha Tien Pier area) at dawn and dusk; crossing to Wat Arun for interior exploration (₿100) allows climbing the steep steps to mid-prang level for river views; (4) Royal Barges Museum's historical significance: the Royal Barges National Museum (Khlong Bangkok Noi) preserves Thailand's royal ceremonial barge fleet — 8 principal barges used in the Royal Barge Procession (Krabuang Ruea Phra That Buang Fai); the Suphannahong (Golden Swan) royal barge is the most famous — 46m long, carved golden swan prow, one of the world's most elaborate ceremonial boats; the procession is held only for major royal events (last held 2019 for King Rama X's coronation celebration); the museum allows visitors to appreciate these exceptional craft objects; (5) Wang Lang Market for authentic Thonburi food: Wang Lang Market (near Siriraj Hospital, Wang Lang Pier) is one of Bangkok's most active authentic traditional markets — primarily serving the Siriraj Hospital community (patients' families, hospital workers, Thonburi residents); the market operates primarily in the morning and is almost entirely Thai-oriented with minimal tourist influence; exceptional Thai traditional food at local pricing.",
    tip: "Thonburi exploration practical guide: (1) Optimal Thonburi access strategy: take the Chao Phraya Express Boat to Maharaj Pier (Grand Palace/Wat Pho side), then cross the river by small passenger ferry (฿3–5) to Wang Lang Pier (Thonburi side); from Wang Lang Pier, the immediate area has the Wang Lang Market and access to Siriraj Hospital area; alternatively, the Tha Tien to Wat Arun ferry (฿6) is the most direct tourist crossing; (2) Long-tail canal tour from Banglamphu Pier: the canal tour entry at Banglamphu Pier (near Khao San Road, Tha Phra Atit pier) offers long-tail tours into Bangkok Noi and Bangkok Yai klongs; these tours are negotiated directly with boat operators; establishing a fixed price before boarding is essential; the standard negotiated tourist price is ฿1,500–2,000 for 1.5 hours per boat (not per person); (3) Siriraj Hospital medical museums (optional niche): Siriraj's medical museum complex includes the Forensic Medicine Museum (with preserved pathological specimens including mummified serial killer Si Quey), anatomical collections, and medical history exhibits; these are unusual Bangkok tourism experiences that attract visitors interested in dark tourism and medical history; not recommended for sensitive visitors; (4) Wat Arun climbing protocol: Wat Arun's main prang has steep stairs (approximately 70-degree angle) at the climbing section; visitors must dress modestly (cover shoulders and knees); ascent is possible to the first major platform level; the descent is accomplished using rope handholds along the steep incline; (5) Thonburi Golden Buddha at Wat Pak Nam: Wat Pak Nam Phasi Charoen (in Thonburi's inner area, approximately 5km from the riverside) contains the largest indoor Buddha statue in the world (69m green jade-like glass statue within the temple's enormous chedi); less visited than riverside temples but accessible by MRT Blue Line extension (Bang Khae area) or by Grab; a genuinely spectacular but less tourist-busy alternative to central Bangkok's temple circuit.",
  },
  {
    name: "Bangkok Chinatown (Yaowarat) — The Original Bangkok Commercial Heart & Food Paradise",
    emoji: "🏮",
    summary: "Yaowarat (Bangkok's Chinatown) is one of the world's oldest and most vibrant Chinese urban communities, established by Thai-Chinese traders before Bangkok's 1782 founding: (1) Yaowarat's historical depth: Bangkok's Chinese community has been present since before the establishment of Bangkok itself — Chinese traders settled at the original Rattanakosin trading post; when Rama I moved the capital to Bangkok Island in 1782, the Chinese community was relocated slightly south to the area now known as Yaowarat/Sampeng; Yaowarat's commercial character has continued for over 240 years; the Thai-Chinese community (now approximately 14% of Thailand's population) originated substantially from this settlement; (2) Yaowarat Road's commercial character: Yaowarat Road (the main artery) is lined with gold shops (highest concentration in Southeast Asia), dried goods and spice traders, seafood restaurants (famous for shark fin and abalone, though shark fin now increasingly controversial), and Chinese-Thai family businesses in their third to seventh generation of operation; the daytime character is commercial and working; the evening/night character transforms into Bangkok's most atmospheric food zone; (3) Talat Noi — Yaowarat's heritage neighborhood: immediately south of the main Yaowarat Road, Talat Noi (literally 'small market') is a preserved heritage neighborhood of traditional Chinese trades (tinsmiths, auto parts dealers, boat engine mechanics) in 19th and early 20th-century shophouses; the area has received creative regeneration (small cafés in heritage buildings) while retaining its traditional trade character; Talat Noi is Bangkok's best-preserved traditional Chinese commercial heritage neighborhood; (4) Yaowarat food culture: Yaowarat is Bangkok's most celebrated food destination for specific items — dim sum (morning, Hua Seng Hong and other dim sum houses on Yaowarat Road); khao lam (Thai sticky rice in bamboo cylinder); ba jang (Chinese rice dumplings); roast duck and roast pork (hanging in shopfront windows); pla gapong tod (deep-fried sea bass); and the famous hoy tod (oyster omelette); evening street food extends down side sois with seafood stalls; (5) Yaowarat temple density: the neighborhood contains multiple Chinese shrines and Buddhist temples — Wat Mangkon Kamalawat (Dragon Lotus Temple, the most important Bangkok Chinese Buddhist temple), Leng Buai Ia Shrine (Guanyin Goddess), and numerous smaller clan association shrines; these temples are active religious centers for the Thai-Chinese community rather than primarily tourist destinations.",
    action: "Yaowarat access: MRT Hua Lamphong (exit then walk north on Charoen Krung Road and turn into Yaowarat Road, 10-minute walk); MRT Sam Yot or MRT Wat Mangkon (new Blue Line extension, walks directly into Yaowarat); by boat: Chao Phraya Express Boat to Ratchawong Pier (near Yaowarat entrance); evening food timing: Yaowarat is best for food from 6pm onwards when the street food stalls set up alongside the established restaurants; morning timing: weekday mornings 7:30–10am for dim sum at Hua Seng Hong or similar dim sum houses on Yaowarat; Songkran (Thai New Year) and Chinese New Year are Yaowarat's two annual peak moments — the neighborhood fills with celebrations; peak Yaowarat navigation: avoid driving (streets close), take MRT or Chao Phraya boat, walk from the landing.",
  },
  {
    name: "Bang Sue & Chatuchak — Bangkok's Northern Hub, Weekend Market & New Station Area",
    emoji: "🏟️",
    summary: "The Bang Sue / Chatuchak area in northern Bangkok represents both the city's largest transport hub and its most celebrated weekend market: (1) Bang Sue Grand Station — Bangkok's new railway center: Bang Sue Grand Station (Krung Thep Aphiwat Central Terminal, opened 2021, full service from 2023) is Bangkok's new central railway terminus, replacing Hua Lamphong for mainline intercity rail services; the station is one of Southeast Asia's largest railway stations — capacity 600,000 passengers/day, multiple rail lines (MRT Blue Line, MRT Purple Line, Airport Rail Link, mainline national rail, future high-speed rail connections); the station's architecture (by Advanced Rail Alliance and Thai architects) is a substantial public building; (2) Chatuchak Weekend Market: Chatuchak Weekend Market (JJ Market, open Saturday and Sunday 9am–6pm) is one of the world's largest weekend markets — approximately 15,000 stalls across 35 sections covering 35 acres; the market covers: housewares, clothing, antiques, plants, food, pets (pet section, ethical concerns noted for some animals), books, Thai crafts, vintage, and almost everything else imaginable; the market is organized in a grid with numbered sections; navigation requires a systematic approach (zone map available at the entrance and digitally) as it is easy to lose orientation; (3) Or Tor Kor Market adjacent premium: directly opposite the Chatuchak Weekend Market entrance (BTS Mo Chit side), Or Tor Kor Market (Auditory General's Market) is Thailand's highest-quality government-supervised fresh market — the produce, fresh seafood, and prepared food quality at Or Tor Kor exceeds any Bangkok supermarket; prices are higher than typical markets but the quality difference is substantial; particularly notable for: fresh Thai fruit, premium dry goods, specialty Thai ingredients, prepared royal Thai cuisine, and regional Thai specialty foods; Or Tor Kor is open daily (unlike Chatuchak) and is a recommended destination regardless of Chatuchak visit; (4) Chatuchak Park: Chatuchak Park (immediately adjacent to the weekend market, behind Mo Chit BTS and Chatuchak Park MRT) is Bangkok's largest urban park — ponds, tree coverage, exercise areas, and weekend recreational activities; the park is used primarily by Bangkok residents (not tourist-oriented); adjacent Queen Sirikit Park (smaller, more formal garden) provides additional green space; (5) Bang Sue's evolution: the Bang Sue area (previously industrial, lower income district) is experiencing significant development pressure following the Grand Station opening; new commercial and residential projects are emerging in the station's vicinity; the area's connection to all major Bangkok rail lines makes it increasingly strategic for Bangkok's urban development.",
    action: "Chatuchak Weekend Market logistics: BTS Mo Chit or MRT Chatuchak Park (better exit for the market itself) or MRT Kamphaeng Phet (another market entrance); arrive 9–10am on Saturday for best selection before midday heat and crowds; Chatuchak heat management: the market is outdoors with minimal shade; plan visits in early morning or late afternoon; hat, sun protection, and hydration essential; buy water from the market's own water stations rather than bottled water (higher cost, more waste in the market context); Or Tor Kor Market hours: daily 6am–6pm (some sections open later); accessible from MRT Chatuchak Park exit 1 directly; Bang Sue Grand Station access: MRT Bang Sue station connects to Bang Sue Grand Station (they are the same station complex on the MRT Blue Line); the station complex is extremely large — allow 15 minutes transit within the station when changing between rail types.",
  },
];

export function BangkokThonburi() {
  return (
    <div className="rounded-2xl border border-indigo-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-indigo-700 mb-3">
        🛶 Bangkok beyond the river — Thonburi canals & Wat Arun, Yaowarat Chinatown & Chatuchak north
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-indigo-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-indigo-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-indigo-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
