const SPOTS = [
  {
    name: "Thai Skincare & K-Beauty in Bangkok",
    emoji: "✨",
    area: "Watsons (50+ Bangkok branches), Boots Pharmacy (widespread), EVEANDBOY (Siam, Asiatique, many malls), Villa Market (Sukhumvit), Korean beauty shops in Siam and Pratunam areas, and specialty Asian beauty importers",
    price: "Watsons house brand skincare: ฿100–600; Korean sheet mask (box of 10): ฿250–800; Premium Korean serum (30ml): ฿1,500–6,000; Japanese sunscreen (SPF50+): ฿350–1,200; Thai herbal skincare (Erb, Harnn): ฿300–2,500",
    why: "Bangkok is one of Asia's best cities for skincare shopping — combining Thai domestic brands, Korean beauty imports, Japanese pharmaceutical skincare, and Western brands at prices competitive with or below Korean or Japanese street prices. The Bangkok skincare market is driven by: (1) Thailand's own robust skincare industry — Thai skincare brands developed specifically for dark-skinned, high-UV, high-humidity tropical skin needs; (2) K-beauty enthusiasm — Bangkok's cosmopolitan population has enthusiastically adopted Korean beauty routines; Korean brands are widely distributed; (3) Japanese skincare accessibility — Japanese brands with strong clinical efficacy (Hada Labo, Biore, Anessa, Curel) are widely available at Bangkok pharmacies; (4) Watsons and Boots as skincare department stores — both chains have Bangkok branch network coverage far exceeding any Western city's equivalent pharmacy density; (5) Bangkok's high-UV reality — SPF skincare products are consumed at genuinely high rates in Bangkok's 11–12 UV index environment; the local demand ensures excellent availability and competitive pricing across UV protection products.",
    tip: "Bangkok skincare shopping practical guide: (1) Thai skincare for tropical climate: brands developed specifically for Thai skin and climate (Mistine, Snail White, AR Mistine, various pharmacy-brand Thai skincare lines) are formulated for high humidity; they perform better in Bangkok's conditions than many Western skincare products designed for temperate climates; (2) Sunscreen priority: Bangkok's UV index regularly reaches 11–12 (extreme); high-SPF mineral or hybrid sunscreen is the most important skincare step in Bangkok; Japanese and Korean sunscreens available in Bangkok offer superior elegance (non-whitening, non-greasy) compared to many Western equivalents; (3) Watsons house brand value: Watsons Thailand's own brand skincare (moisturizers, serums, sheet masks, cleansers) offers remarkable quality at budget prices; these are made for the Thai market and work well in tropical conditions; (4) EVEANDBOY stores: Bangkok's most comprehensive specialty beauty retail chain, with particularly strong K-beauty selection, in-store testing, and staff who can advise on product selection; (5) Duty-free at Suvarnabhumi: Bangkok's Suvarnabhumi Airport duty-free has an excellent skincare selection including Thai brands and premium international brands; comparing prices against street-side mall prices before committing to a purchase provides the best value.",
  },
  {
    name: "Bangkok Aesthetic Skin Treatments",
    emoji: "💉",
    area: "Aesthetic and dermatology clinics throughout Bangkok: widespread in Sukhumvit (Asok, Phrom Phong, Thonglor zones), Silom, and in premium mall-adjacent locations; chain clinics (APEX, Better Skin, various) and independent dermatologist-led practices",
    price: "Botox consultation: ฿0–1,000; Botox per unit: ฿350–700 (vs. ฿1,000–2,000/unit in USA); Dermal filler per 1ml syringe: ฿8,000–20,000; Laser skin rejuvenation (face): ฿3,000–15,000 per session; Hydrafacial: ฿4,000–10,000; PRP skin treatment: ฿8,000–20,000",
    why: "Bangkok has become a globally recognized destination for aesthetic skin treatments — offering a combination of internationally trained practitioners (many dermatologists and aesthetic physicians training in the USA, South Korea, or Europe), FDA-approved products (Allergan Botox, Galderma Restylane, Juvederm fillers), and pricing 40–70% below equivalent treatments in the USA, UK, or Australia. The Bangkok aesthetic treatment landscape: (1) Injectables (Botox and fillers) — the most significant price differential from Western markets; quality is equivalent when using a board-certified dermatologist or plastic surgeon; (2) Laser treatments — fractional CO2 lasers, pico lasers, and long-pulsed Nd:YAG lasers for pigmentation, acne scarring, and rejuvenation are widely available; (3) Thread lifts — non-surgical face lifting using dissolvable sutures; Bangkok has surgeons with high procedure volume in this technique; (4) Chemical peels and facials — extensive range from clinical-grade superficial peels through trichloroacetic acid deep peels; (5) Skin lightening treatments — Thailand's strong demand for skin brightening products has generated extensive clinical experience with melanin reduction treatments; glutathione IV infusion and topical treatment is widely practiced.",
    tip: "Bangkok aesthetic treatment safety guide: (1) Board certification matters: seek dermatologists (แพทย์ผิวหนัง) or plastic surgeons (ศัลยแพทย์ตกแต่ง) for injectable treatments rather than aesthetic nurses or technicians; credentials should be verifiable through the Thai Medical Council; (2) Product authentication: insist on unopened vials for Botox/filler treatments with lot numbers that can be verified against manufacturer databases; counterfeit injectable products exist in Bangkok's aesthetic market; (3) APEX Profound and established chains: Bangkok's chain aesthetic clinics (APEX, Absolute, THINK Clinic) have standardized protocols and multiple locations; they offer predictability if less personalization; (4) Sun avoidance post-laser: Bangkok's intense UV environment requires strict sun avoidance and SPF 50+ protection for 2–4 weeks after most laser treatments; planning laser treatments with adequate indoor recovery time is essential; (5) Combination treatment planning: Bangkok's aesthetic physicians often suggest combination treatment protocols (Botox + filler + laser) in a single visit; being prepared to receive multiple recommendations and to accept or decline each independently provides informed decision-making.",
  },
  {
    name: "Thai Herbal Skincare & Natural Beauty Traditions",
    emoji: "🌿",
    area: "Erb (Asiatique, Central, various malls), Harnn & Thann (high-end malls and spas), Pañpuri (premium hotels and malls), Lanna spa brand products, and traditional herbal apothecaries in Chinatown and Old Bangkok",
    price: "Thai herbal soap: ฿80–350; Turmeric skincare products: ฿200–800; Pañpuri facial oil: ฿1,500–4,000; Harnn body treatment (spa format): ฿2,000–5,000; Traditional herbal compress (spa): ฿1,500–3,000",
    why: "Thailand's traditional herbal medicine tradition has been translated into a contemporary luxury skincare and spa product industry that stands among the most sophisticated in Southeast Asia. Key Thai botanical ingredients: (1) Turmeric (ขมิ้น, kamin): anti-inflammatory and skin brightening; used in traditional Thai massage oil preparations and face masks; extensively incorporated into modern Thai skincare formulations; (2) Tamarind (มะขาม, ma kham): alpha hydroxy acid source from tamarind pulp; traditional exfoliating agent in Thai beauty rituals; (3) Jasmine (มะลิ, mali): calming fragrance with a distinct aromatherapy profile; Thai jasmine absolute is one of the most prized fragrance ingredients; (4) Pandan (ใบเตย, bai toei): distinctive green fragrance used in herbal steam and bath preparations; (5) Lemongrass (ตะไคร้, ta khai): antimicrobial and refreshing; widely used in Thai spa preparations; (6) Butterfly pea (อัญชัน, anchan): vivid blue antioxidant pigment used in both culinary and cosmetic applications. Premium Thai botanical skincare brands (Pañpuri, Harnn, Erb, Lush Atelier Thailand) have developed internationally recognized products that package these traditional ingredients in contemporary formulations with sensory sophistication.",
    tip: "Thai herbal beauty shopping guide: (1) Airport value at departure: Pañpuri and Harnn have dedicated shops at Suvarnabhumi Airport duty-free; their products are the same quality as in-city mall stores without the carry-on liquid concern (if purchased in the duty-free zone); (2) Traditional vs. contemporary: traditional Thai herbal products (at Pak Khlong Talat herb section, traditional pharmacies in Old Bangkok) are significantly cheaper than premium branded versions while containing many of the same botanical ingredients; (3) Turmeric staining risk: fresh or raw turmeric can stain skin and fabric yellow; commercial Thai skincare formulations that include turmeric have typically processed the ingredient to remove excess curcumin staining risk while retaining anti-inflammatory benefits; (4) Spa product connection: Bangkok's best Thai spas (Oriental Hotel Spa, Four Seasons Bangkok Spa, various independent luxury wellness centers) often sell the product lines they use in treatments at on-site retail shops; sampling treatments before purchasing products creates confidence in the formulation quality; (5) Authentic natural vs. 'natural' marketing: Thailand's beauty market has both genuinely botanical formulations and products that use 'herbal' or 'natural' as marketing language with primarily synthetic active ingredients; examining ingredient lists (INCI names) distinguishes authentic botanical content from marketing.",
  },
];

export function BangkokSkincare() {
  return (
    <div className="rounded-2xl border border-fuchsia-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-fuchsia-700 mb-3">
        ✨ Bangkok skincare — Thai & K-beauty shopping, aesthetic treatments & herbal traditions
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-fuchsia-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-fuchsia-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
