const TOPICS = [
  {
    title: "Bangkok Alcohol Laws — Purchasing Hours, Restrictions & Buddhist Holiday Bans",
    emoji: "🍺",
    summary: "Thailand's alcohol regulations are unlike most Western countries and have caught many visitors by surprise: (1) Alcohol selling hours: alcohol sales in Thailand are legally restricted to two time windows daily — 11am–2pm and 5pm–midnight; outside these hours, legally compliant shops (7-Eleven, Lotus's, Tops, most restaurants) will decline to sell alcohol; the law applies to all retail points including convenience stores; some bars and restaurants have licensed exceptions for their specific premises but this is distinct from general retail; (2) Buddhist holiday alcohol bans: Thailand enforces complete alcohol sales prohibitions on specific Buddhist holidays — Makha Bucha (Magha Puja), Visakha Bucha (Visakha Puja, the most important Buddhist holiday), Asanha Bucha, and the beginning of Buddhist Lent (Khao Phansa/Wan Ok Phansa, 3 months); on these days, no retail alcohol sales, and most bars/restaurants stop serving alcohol; visitors should plan around Buddhist holiday dates when visiting; (3) Election day bans: Thai law prohibits alcohol sales during official election periods (typically 6am on election day to midnight or the following day); Bangkok elections and major national elections both trigger this restriction; tourists are sometimes surprised by alcohol bans during Thai elections that receive little international publicity; (4) What is legally unrestricted: drinking alcohol that was previously purchased is not illegal during restricted periods; hotel rooms, private spaces, and pre-purchased stock can be consumed at any hour; restrictions apply to sales, not consumption; (5) Enforcement and consequences: 7-Eleven and chain convenience stores are strictly compliant; smaller independent shops and some underground vendors may be more flexible during restricted hours; police do occasionally check; fines for illegal sales fall on the seller, not the buyer.",
    action: "Buddhist holiday calendar: check the Thai Ministry of Culture calendar or search 'Thailand Buddhist holidays [year]' before planning Bangkok nightlife; pre-purchasing alcohol before Buddhist holiday: buy alcohol the day before to have hotel room stock; apps for checking Thai holidays: Thailand holiday calendar apps or Google Calendar with Thai public holidays overlay; major Buddhist holiday date pattern: based on lunar calendar so dates shift annually; Wan Ok Phansa (end of Buddhist Lent, late October) marks the return of full alcohol service after the 3-month reduced period.",
  },
  {
    title: "Bangkok Sober Travel — Alcohol-Free Nightlife, Mocktails & Sober-Friendly Experiences",
    emoji: "🥤",
    summary: "Bangkok offers extensive experiences that don't require alcohol and has excellent non-alcoholic drink culture: (1) Thai fresh juice and smoothie culture: Bangkok's fruit smoothie and fresh juice culture is excellent and widely accessible; fresh watermelon juice, coconut water, sugarcane juice (pressed at market stalls), butterfly pea flower drinks (nam dok anchan, vivid blue-purple with lime creating color change), Thai iced tea (cha yen, sweet orange tea), and fresh-pressed tropical fruit combinations are available at street stalls for ฿25–60; (2) Bangkok's tea culture: Thailand has a developing specialty tea culture alongside its established coffee culture; authentic Thai-style milk tea preparation (condensed milk, evaporated milk, tea leaves brewed in sock filter) is different from international bubble tea; Northern Thai tea culture (Chiang Rai teas, Oolong varieties grown at altitude) has created a Bangkok specialty tea café scene; (3) Sober-accessible Bangkok nightlife: Bangkok has genuinely fun sober nightlife options — Chatuchak Night Market (Friday evenings), Asiatique The Riverfront (shopping and entertainment riverside, alcohol served but sober participation fully possible), ICONSIAM shopping complex evening entertainment, rooftop bars with mocktail menus, cultural performances (Sala Chalermkrung Khon, traditional dance), night temple visits, and night food market exploration; (4) Non-alcoholic beverage ordering at Bangkok bars: Bangkok's bar culture has developed better non-alcoholic options as global sober-curious trends have reached the city; many Bangkok cocktail bars now make genuinely excellent virgin cocktails or mocktails; asking for 'virgin' [cocktail name] or 'without alcohol' is understood at most English-language Bangkok bars; (5) Recovery community in Bangkok: Bangkok has active international recovery communities; AA Bangkok (Alcoholics Anonymous Bangkok) has English-language meetings (check aathailand.org); SMART Recovery Bangkok; expat recovery communities connect through Facebook groups and international church communities; the large expat population creates sufficient community for regular meetings.",
    action: "Non-alcoholic drink specialties to try in Bangkok: nam dok anchan (butterfly pea flower drink), fresh coconut water (ma prao on), thai ice tea (cha yen), sugarcane juice (nam oy), fresh guava juice (nam farang), herbal Thai drinks (ya dong herbal medicine shots, non-alcoholic versions available); Thai herbal beverages: various Thai herbal drink vendors offer traditional health beverages (lemongrass, ginger, pandan); AA Bangkok meetings: aathailand.org for schedule; sober-friendly Bangkok community: Facebook 'Bangkok Sober' groups for expat sober social events.",
  },
  {
    title: "Bangkok Smoking Laws — Designated Areas, Vaping Restrictions & Where You Can Smoke",
    emoji: "🚭",
    summary: "Thailand has strict anti-smoking laws that are more rigorously enforced than many Southeast Asian neighbors: (1) Smoking prohibition scope: smoking is prohibited in all air-conditioned public spaces (restaurants, shopping malls, bars, nightclubs, public transportation, offices, hospitals, government buildings, and most indoor spaces); Thailand's anti-smoking laws have been progressively strengthened since 2002 and are genuinely enforced; (2) Designated smoking areas: Bangkok venues that allow smoking must provide designated outdoor smoking areas (typically: marked area with ashtray, outdoors, at least 5 meters from building entrances); some Bangkok bars, particularly those with outdoor seating concepts, effectively accommodate smokers in their outdoor areas; Bangkok's night markets and street food areas are generally outdoor and smoking behavior varies (some areas have designated smoking spots marked with yellow signs); (3) Vaping and e-cigarette ban: Thailand has an outright ban on electronic cigarettes, vaping devices, and related products — both importing and using e-cigarettes is illegal in Thailand; this is among the strictest vaping policies in the world; penalties include fines and potential jail time; the ban is occasionally enforced at airports and venues; visitors who vape are strongly advised to leave vaping devices at home rather than bring them to Thailand; (4) Cigarette availability: standard tobacco cigarettes are legal and widely available at 7-Eleven, convenience stores, and tobacco shops; Thai tobacco brands (Falling Rain, Krisnadha) are available alongside international brands (Marlboro, L&M, Lucky Strike); prices are moderate vs. Western countries (฿60–120 per pack for most brands); (5) Shisha and hookah: hookah/shisha cafés exist in Bangkok (particularly around Nana area serving the Arab tourist market) in a gray legal area; technically outdoor shisha in entertainment areas is tolerated rather than fully legal; enforcement is inconsistent; some Thai tourist areas (Khao San Road area) have shisha venues that operate openly.",
    action: "Thai Anti-Smoking Act penalties: fines of ฿2,000–5,000 for smoking in prohibited areas (applied inconsistently but increasingly enforced); airport vaping risk: Suvarnabhumi customs inspects for vaping devices — leaving devices at home is the only safe approach; designated smoking apps/maps: no reliable Bangkok smoking area map exists; asking venue staff or looking for yellow-marked smoking area signs is the standard approach; international travelers: switching to nicotine patches or gum for Thailand travel duration avoids all restriction issues; smoking allowance per person bringing cigarettes to Thailand: 200 cigarettes (one standard carton) maximum — excess cigarettes will be confiscated at customs.",
  },
];

export function BangkokAlcohol() {
  return (
    <div className="rounded-2xl border border-stone-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-stone-700 mb-3">
        🍺 Bangkok alcohol & smoking — purchase laws, sober travel & smoking restrictions
      </h2>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-stone-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-stone-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
