const SPOTS = [
  {
    name: "Indian Food in Bangkok — From Nana to Nirvana",
    emoji: "🍛",
    area: "Sukhumvit Soi 11 and surrounding area (Nana — Bangkok's South Asian neighborhood): Indian, Pakistani, Bangladeshi, and Sri Lankan restaurants along Soi 11, Soi 3/1; Little India scattered through Silom, Pahurat (Indian Textile District near Saphan Han), and Sukhumvit Soi 3 community area",
    price: "Thali set meal at Nana Indian restaurant: ฿180–350; Biryani (large portion): ฿180–350; Tandoor bread basket: ฿80–150; North Indian vegetarian meals: ฿150–400; Pakistani BBQ platter: ฿350–800; South Indian dosa at budget spots: ฿80–200",
    why: "Bangkok's South Asian food scene is centered on two distinct geographic communities: (1) Sukhumvit Soi 3/Nana area — Bangkok's most concentrated South Asian community, where Indian, Pakistani, Bangladeshi, and Sri Lankan restaurants operate for the substantial South Asian Muslim expatriate and worker population; the area serves both restaurant dining and takeaway, and operates largely on halal principles; (2) Pahurat (Indian Textile District) — Old Bangkok's fabric market area near Chinatown contains a longer-established Sikh and Hindu Indian community with South Indian and North Indian vegetarian restaurants embedded in the textile market environment. Regional diversity at Bangkok's Indian restaurants is genuine: (1) North Indian (Mughal tradition) — tandoor cooking (chicken tikka, paneer tikka, naan bread), curries (dal makhani, butter chicken, lamb rogan josh), and biryani; (2) South Indian — dosa, idli, sambar, coconut-based curries; (3) Pakistani — halal BBQ culture, karahi gosht, seekh kebab; (4) Sri Lankan — coconut milk curries, string hoppers, kottu roti. Bangkok's Indian food quality-to-price ratio is excellent; the community restaurants serving the South Asian worker population offer authentic cooking at very low prices.",
    tip: "Bangkok South Asian food navigation: (1) Nana area best access: BTS Nana station provides direct access to Sukhumvit Soi 3 and adjacent streets where the South Asian food concentration is highest; the restaurant density along Soi 3/1 (beside the Arab Street stretch) offers multiple options within 100 meters; (2) Halal certification: virtually all restaurants in the Nana South Asian area serve halal food (Islamic dietary law compliance); checking for halal certificates in windows confirms status; (3) Pahurat Indian veg community: Pahurat's Sikh temple (Gurdwara Siri Guru Singh Sabha) and surrounding fabric market restaurants serve North Indian vegetarian food that represents the older, Hindu/Sikh Bangkok Indian community's cuisine rather than the primarily Muslim Nana area; (4) Mango sticky rice with a twist: Bangkok's Indian sweet shops (mithai shops) in Pahurat and Nana areas sell traditional Indian sweets (barfi, gulab jamun, rasgolla, jalebi) that differ completely from Thai dessert traditions — a side-by-side comparison is an interesting Bangkok food experience; (5) Biryani feast culture: Bangkok's Pakistani community biryani events (often announced through community networks) produce some of the largest and most authentic biryani preparations accessible in Bangkok.",
  },
  {
    name: "Sri Lankan & Bengali Cuisine in Bangkok",
    emoji: "🦐",
    area: "Sri Lankan restaurants: concentrated in Sukhumvit (Nana area) with Sri Lankan community restaurant presence; Bengali/Bangladeshi food in the Nana/Sukhumvit Soi 3 area serving Bangkok's significant Bangladeshi worker population",
    price: "Sri Lankan rice and curry set: ฿150–350; Kottu roti: ฿150–300; String hoppers with accompaniments: ฿150–300; Bengali fish curry meal: ฿150–350; Bangladeshi biryani (large): ฿200–400",
    why: "Bangkok's Sri Lankan and Bangladeshi food communities are smaller and less visible than the North Indian/Pakistani presence but represent distinct culinary traditions within the South Asian ecosystem. Sri Lankan cuisine at Bangkok's small Sri Lankan community restaurants features: (1) Rice and curry — the fundamental Sri Lankan meal format; multiple curries (fish, chicken, vegetable) served alongside rice; more coconut milk and pandan-infused than North Indian curries; (2) Kottu roti — Sri Lanka's national street food; chopped roti stir-fried with egg, vegetables, and protein on a flat iron griddle with a rhythmic chopping sound that doubles as ambient marketing; (3) String hoppers (idiyappam) — pressed rice noodle rounds steamed and eaten with coconut milk curry; delicate and light compared to most South Asian breads; (4) Sri Lankan tea culture — Sri Lanka produces some of the world's most respected teas (Ceylon tea); Bangkok's Sri Lankan community maintains this tea culture connection. Bangladeshi cuisine at Nana area restaurants serves the substantial Bangladeshi labor community with familiar home cooking: fish curries using freshwater fish species common in Bangladeshi rivers (different fish than Thai freshwater varieties), rice-heavy meals, and dal preparations.",
    tip: "Bangkok Sri Lankan and Bengali cuisine finding: (1) Community restaurant discovery: Sri Lankan and Bangladeshi restaurants in Bangkok are primarily word-of-mouth community establishments without significant English-language online presence; walking Sukhumvit Soi 3/1 and asking at South Asian community shops provides better results than Google Maps for these cuisines; (2) Sri Lankan tea: bringing awareness of Ceylon tea's categories (high-grown vs. low-grown, specific estate single-origins) to a conversation at a Sri Lankan community restaurant often reveals access to genuine Ceylon tea unavailable in Bangkok's café culture; (3) Bangladeshi fish curries: Bangladesh's freshwater fish curry tradition uses species (ilish/hilsa, rohu, katla) that don't appear in Thai restaurants; these are distinct culinary experiences even for visitors familiar with Indian food; (4) Sri Lankan New Year (April): Bangkok's Sri Lankan community celebrates Sinhalese New Year in April with community gatherings and traditional food preparation that occasionally opens to community-adjacent outsiders; (5) Nana community hub timing: the South Asian community restaurant strip in Nana area is busiest during Ramadan evenings (iftar and suhoor dining) when the restaurants become social gathering spaces for the Muslim South Asian community.",
  },
  {
    name: "Nepali, Tibetan & Himalayan Culture in Bangkok",
    emoji: "⛰️",
    area: "Nepali restaurants and cultural spaces: several Nepali-operated restaurants scattered through Bangkok (primarily Sukhumvit and near Silom); Tibetan refugee community presence; Himalayan craft shops in Chatuchak and international bazaar areas of Bangkok",
    price: "Nepali dal bhat tarkari set: ฿150–350; Momos (Nepali/Tibetan dumplings, 10 pieces): ฿150–350; Thukpa noodle soup: ฿150–300; Nepali kheer (rice pudding): ฿80–200; Yak cheese (imported): ฿400–1,500; Himalayan craft purchase: ฿300–10,000+",
    why: "Bangkok's small Nepali and Tibetan community creates access to a distinct Himalayan culinary and cultural tradition within the South Asian ecosystem. Key food experiences: (1) Momos — the Nepali/Tibetan dumpling that is the Himalayan region's most universally beloved street food; filled with minced meat (pork, chicken, water buffalo) or vegetables; served steamed or pan-fried with spicy sesame or tomato dipping sauce; the cooking tradition arrived in Bangkok via Nepal's diaspora workers and Tibetan refugees; (2) Dal bhat — Nepal's national meal; rice (bhat) with lentil soup (dal), vegetable curry, and pickle (achar); the humble foundation of Nepali everyday cooking; (3) Thukpa — Tibetan/Nepali noodle soup; hearty, warming broth with noodles, vegetables, and meat; a completely different noodle tradition from Thai soups; (4) Sel roti — traditional Nepali ring doughnut made from rice flour; found at Nepali community events. Cultural artifacts: Tibetan craft traditions (singing bowls, thangka paintings, mantra mani wheels, prayer flags) are available at Bangkok's alternative craft shops and Chatuchak Market through both Nepali and Tibetan vendors.",
    tip: "Bangkok Himalayan community access: (1) Nepali worker community: Bangkok's Nepali community is significant (Nepal is a major source of labor migration to Thailand); finding community restaurants requires looking beyond obvious Sukhumvit tourist strips to residential neighborhood areas and near construction zones; (2) Momo variations: the best Bangkok momos are at community restaurants serving the Nepali diaspora rather than at tourist-oriented 'Himalayan cuisine' restaurants; the flavor profiles (spice balance, wrapper thickness, dipping sauce) differ significantly; (3) Chatuchak Himalayan crafts: Chatuchak Weekend Market has multiple vendors selling Tibetan/Nepali craft items — singing bowls, thangka paintings, jewelry, textiles; quality and authenticity vary widely; (4) Singing bowl selection: authentic hand-hammered Tibetan singing bowls (versus machine-pressed) produce specific resonance qualities; vendors who demonstrate specific tones for healing or meditation contexts understand their product; (5) Himalayan tea culture: Butter tea (Tibetan po cha — salted butter churned with black tea) and sweet spiced milk tea (chay) are consumed at Nepali community gatherings; these are rarely on Bangkok menus but accessible through community connections.",
  },
];

export function BangkokSouthAsianFood() {
  return (
    <div className="rounded-2xl border border-orange-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-orange-700 mb-3">
        🍛 Bangkok South Asian cuisine — Indian Nana district, Sri Lankan & Nepali community food
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-orange-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-orange-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
