const SPOTS = [
  {
    name: "Bangkok Monthly Budget — Realistic Cost Breakdown at 3 Lifestyle Levels",
    emoji: "💰",
    area: "Bangkok cost of living varies dramatically by lifestyle choice. This breakdown covers 3 realistic monthly budget levels for a single person living in Bangkok (not short-term tourist): Budget (local lifestyle, minimal tourist spending), Mid-range (expat comfortable, occasional luxury), and Premium (luxury expat with all comforts). All figures in Thai Baht per month. Currency reference as of late 2025: USD 1 ≈ ฿35; EUR 1 ≈ ฿38; GBP 1 ≈ ฿44; AUD 1 ≈ ฿22; JPY 100 ≈ ฿23; KRW 1000 ≈ ฿26",
    price: "Budget lifestyle total: ฿25,000–40,000/month (≈$700–1,150); Mid-range expat total: ฿60,000–100,000/month (≈$1,700–2,850); Premium expat total: ฿150,000–300,000+/month (≈$4,300–8,500+); Budget rent (On Nut, non-BTS-adjacent): ฿7,000–12,000; Mid-range rent (Sukhumvit, BTS-adjacent, 1BR furnished): ฿20,000–40,000; Premium rent (Thong Lo, 2BR luxury): ฿50,000–120,000; Budget food (street food + local restaurants): ฿8,000–15,000; Mid-range food (mix local + occasional Western): ฿20,000–35,000; Premium food (restaurants, delivery, import groceries): ฿40,000–80,000",
    why: "Bangkok's cost of living structure differs from Western cities in ways that require recalibration: (1) Labor cost compression: Thai labor costs (the price of services delivered by Thai workers) are dramatically lower than Western equivalents; this means: cleaning services (฿400–800/session vs. $50–150 Western), transport (฿100–300 Grab rides vs. $20–40 Uber), food preparation (฿50–200 meals vs. $15–40 Western equivalent); the labor cost advantage is the primary reason Bangkok delivers dramatically better quality of life per dollar vs. Western cities at equivalent spending levels; (2) Housing relative to income: Bangkok housing costs relative to a Thai median income are actually quite high; for Western expats with foreign income, Bangkok housing is extremely affordable; a ฿25,000/month apartment absorbs 100% of Thai minimum wage (approximately ฿10,000–12,000 in Bangkok) but only 5–10% of a $60,000 USD salary; (3) Inflation trajectory: Bangkok's cost of living has increased noticeably from 2020 to 2025; post-COVID recovery, baht weakening impact on import prices, and increasing wages have pushed both food and accommodation costs upward; the ฿50 street food price point that defined Bangkok budgeting in 2015 is now more often ฿70–100; (4) Category-specific cost variation: some categories are barely cheaper than Western equivalents in Bangkok; electronics (Apple products, imported electronics) are at or near Western prices due to Thai import duties; imported food (European cheese, wine, non-Thai packaged food) is 1.5–3x Western prices; international chain restaurants (McDonald's, Starbucks) are 60–80% of Western pricing; (5) Digital nomad sweet spot: Bangkok offers exceptional quality-to-cost for remote workers with income above $2,500/month USD; at ฿90,000/month ($2,500), a Bangkok remote worker can afford: BTS-adjacent 1BR apartment (฿20,000), healthy mix diet (฿25,000), transportation (฿5,000), gym (฿2,000), occasional restaurants (฿15,000), and savings; the same $2,500 in London, New York, or Sydney would not cover rent.",
    tip: "Bangkok cost optimization strategies: (1) Street food vs. restaurant cost multiplier: a basic Thai street food meal (khao man gai, pad kra pao rice, boat noodles) costs ฿50–100; the same dish in a sit-down restaurant with AC is ฿150–300; in a mall food court it is ฿100–200; eating street food for breakfast and lunch while treating restaurant meals as evening occasions dramatically reduces food costs without sacrificing quality (street food quality is often superior); (2) Electricity cost management: Bangkok's electricity rate (฿3.5–4.5/unit, higher in non-direct-billed condos) makes air conditioning the largest variable cost for Bangkok living; high air conditioning usage in a Bangkok apartment can add ฿3,000–8,000/month to costs; natural ventilation during cooler hours (early morning, late evening, November–February season) reduces AC dependency; setting AC at 26°C rather than 22°C creates significant savings over a month; (3) BTS pass vs. per-ride cost: frequent BTS users (10+ trips/week) benefit from Rabbit Card reloadable transit card; the Rabbit card provides 0% fare discount but eliminates the need for exact fare at machines; combining BTS with canal boat (30–60% cheaper) for specific corridors (Pratunam-Asok) reduces monthly transit cost; (4) Supermarket vs. wet market food costs: fresh produce purchased at local wet markets (Klong Toey, Or Tor Kor) or Lotus's/BigC hypermarkets costs 40–70% less than equivalent produce at Villa Market or Gourmet Market (which cater to expat income); Thai produce (vegetables, tropical fruits, local chicken) costs are roughly equal across channels; (5) Healthcare cost as budget variable: Bangkok international hospital care is significantly cheaper than Western healthcare but still significant in absolute terms; outpatient consultation at Bumrungrad (฿1,000–3,000), specialist consultation (฿2,000–6,000), and common procedures add up; travel insurance or Thai health insurance (Cigna, Pacific Cross, Thai-branded plans at ฿15,000–40,000/year) significantly reduces the healthcare budget uncertainty.",
  },
  {
    name: "Bangkok Money — ATMs, Exchange Rates, Transferwise & Banking Practicalities",
    emoji: "💳",
    area: "Bangkok ATM availability: every 7-Eleven (6,000+ Thailand-wide) has ATM; major banks (Kasikorn/KBank, Bangkok Bank, SCB, Krungthai) ATMs at all BTS Skytrain stations; SuperRich, Vasu, and major currency exchange shops at Pratunam, Victory Monument, airports, Silom; Aeon Financial ATMs (no Thai bank fee); exchange comparison: banks (worst rate), SuperRich (consistently excellent rates), airport exchange (poor); wire transfer: Wise (TransferWise), CurrencyFair, and Bangkok Bank's international transfer service; Thai bank account opening for foreigners: Bangkok Bank (easiest), Kasikorn (KBank, excellent app), SCB (good digital banking)",
    price: "Thai bank ATM fee for foreign cards: ฿220 per transaction (across all Thai banks since 2018 uniform fee policy); Aeon ATMs: some charge ฿150–180; Airport exchange (Suvarnabhumi): rates approximately 3–5% below commercial exchange; SuperRich Thailand: rates approximately 1–2% below interbank; Wise transfer fee (USD to THB): 0.4–0.8% of transfer amount; Bangkok Bank international wire transfer receipt (deposited from abroad): ฿200 fee; Kasikorn KBank international transfer (outgoing): ฿500–1,000 per transfer; Western Union Bangkok locations: Major malls and agencies; MoneyGram: available but limited vs. Wise",
    why: "Bangkok's cash-dominant economy requires active money management strategy: (1) Thailand's cash-dominant culture: Thailand remains significantly cash-dominant despite rapid digital payment adoption; PromptPay QR codes are widely accepted at street food stalls, markets, and small businesses; however, cash is still required at many smaller vendors, traditional markets, temple donations, tuk-tuks, and many street food carts; carrying ฿1,000–3,000 in cash for daily expenses is practical; (2) ATM fee management: the uniform ฿220 Thai ATM fee (charged by all Thai bank ATMs to foreign cards since 2018) makes frequent small ATM withdrawals expensive; withdrawing larger amounts (฿5,000–10,000) per ATM transaction reduces the percentage cost; some foreign bank accounts reimburse foreign ATM fees (Charles Schwab US, Starling UK, Revolut, Wise); (3) SuperRich exchange advantage: Bangkok's SuperRich Thailand exchange booths (recognizable by orange/yellow branding, located throughout Bangkok including Sukhumvit and Pratunam areas) consistently offer the best retail foreign exchange rates in Bangkok — approximately 1–2% better than bank exchanges and 3–5% better than airport exchanges; for large cash exchanges, this margin is significant; (4) Wise for international transfer: for expats and remote workers receiving international income into Bangkok, Wise (formerly TransferWise) typically provides the best value transfer combination (mid-market exchange rate + small percentage fee); Wise transfers to Thai bank accounts arrive within 1–2 business days; the alternative of Bangkok Bank international transfer receipt is also reliable but slower; (5) Thai bank account opening value: opening a Thai bank account (most recommended: Kasikorn KBank for the excellent K PLUS mobile app; Bangkok Bank for international wire transfer convenience) provides: PromptPay registration, domestic ATM access without ฿220 foreign fee, local payment infrastructure, and currency conversion at bank rates rather than exchange booth.",
    tip: "Bangkok money management practical guide: (1) Card security in Bangkok: magnetic stripe card skimming at standalone ATMs remains a risk; using ATMs inside bank branches (not street-facing machines) or airport ATMs reduces risk; chip-and-PIN cards (not magnetic stripe) are more secure; monitoring bank statements immediately after Bangkok ATM use catches unauthorized transactions early; (2) 100-baht breakdown for daily Bangkok life: a practical Bangkok daily cash budget for a budget traveler: ฿60 (morning coffee/tea at street stall) + ฿80 (street food lunch) + ฿80 (street food dinner) + ฿50 (BTS 1 segment) + ฿30 (water, snacks) = ฿300/day minimum comfortable budget; mid-range: add ฿200–400 for AC restaurants, more transport, entertainment; (3) Large denomination notes: Bangkok's street food and small vendors often cannot change 1,000-baht notes; having ฿20–100 notes available for small purchases prevents the awkward change problem; banks provide small denominations; exchange booths give 100-baht notes; ATMs dispense 1,000-baht notes (largest denomination); (4) Counterfeit note awareness: Thai bank note counterfeiting is rare but exists; Thai bank notes have multiple security features (color-shifting ink, watermarks, holographic strips on 100-baht and above); feeling unusual texture or seeing irregular printing on received notes is a signal for inspection; (5) Currency prediction and timing: the Thai baht has historically been one of Asia's more stable currencies (managed by the Bank of Thailand's active intervention policy); for visitors converting large sums, spreading the exchange across multiple days and exchange rates rather than single large exchange reduces timing risk.",
  },
  {
    name: "Bangkok Cheap vs. Expensive — Same Experience, Very Different Prices",
    emoji: "⚖️",
    area: "Bangkok price duality examples: Khao San Road Pad Thai ฿150 vs. Thip Samai Pad Thai ฿180 (Thip Samai wins quality); ChatuchakMarket Pad Thai ฿60 (excellent, local); Starbucks Bangkok ฿155–220 vs. Thai coffee stall ฿25–45 (both caffeine); BTS Skytrain ฿16–62 vs. tuk-tuk ฿200–600 (BTS superior speed/cost); Erawan Shrine free vs. Madame Tussauds Bangkok ฿890 (Erawan more culturally significant); Lumphini Park exercise free vs. Anytime Fitness ฿800/month (both exercise); Chatuchak Weekend Market local restaurant ฿60/plate vs. adjacent mall food court ฿150/plate (Chatuchak usually tastier); Wat Pho ฿200 vs. art museum ฿200 (very different cultural experiences)",
    price: "Bangkok price comparison examples: Thai street massage ฿150–200/hour vs. Health Land Spa ฿550/2hours vs. Mandarin Oriental Spa ฿5,000/treatment; 7-Eleven sandwich ฿45 vs. Boots meal deal ฿130 vs. bakery cafe sandwich ฿200; Singha beer (7-Eleven, bottle) ฿68 vs. Singha beer (sports bar, bottle) ฿200 vs. Singha beer (rooftop bar) ฿350; Thai mango sticky rice (street, perfect quality) ฿70 vs. Mango Tango icon Siam ฿250; Grab motorbike ฿30–60 vs. Grab car ฿90–200 vs. Grab premium ฿200–500 (all same destination)",
    why: "Bangkok's most important financial insight for visitors is that price and quality often have an inverted relationship compared to Western expectations: (1) The street food supremacy paradox: Bangkok's most genuinely excellent food is typically cheap and served in unpretentious environments; a ฿60 bowl of boat noodles at the right boat noodle shop is superior to the same dish at ฿300 in a tourist restaurant; the tourist restaurant is trading on presentation, AC, and English menus rather than culinary quality; this price-quality inversion is Bangkok's most important food insight; (2) When expensive is genuinely better in Bangkok: some categories have genuine quality correlation with price — luxury spa treatments (Health Land vs. street massage), international hospitals vs. local clinics, premium supermarket ingredients vs. budget alternatives, quality tailoring vs. tourist tailor shops; knowing which categories have real quality scaling helps spending decisions; (3) Activity price vs. cultural value: Bangkok's most culturally valuable experiences (Erawan Shrine, Chatuchak market, Pak Klong Talad flower market, monk alms, river boat crossing to Wat Arun) are either free or minimal cost; some of Bangkok's most expensive tourist experiences (Madame Tussauds, some dinner cruises, tourist-packaged activities) deliver less authentic Bangkok experience than the free alternatives; (4) The AC pricing multiplier: air conditioning (which Bangkok's heat genuinely requires) consistently marks the price difference between local and tourist venues; street food: ฿60–100; AC food court: ฿120–200; AC sit-down restaurant: ฿200–400; this is the central Bangkok price structure pattern; (5) Tipping culture and service charge: Thailand does not have a mandatory tipping culture; service charge (10% or 'SC' on restaurant bills) is added by mid-range and upscale restaurants and goes to the restaurant, not necessarily the servers; additional tipping (฿20–100 for good service) is appreciated but not expected; massage tipping ฿50–100 is considered polite but not mandatory; hotel bellhop ฿50–100 per bag.",
    tip: "Bangkok value optimization rules: (1) Eat where Thais eat: the most consistent Bangkok food value rule — restaurants where the majority of diners are Thai (not tourist-majority restaurants) almost always deliver better quality at lower price; if you look around and see mostly foreigners, recalibrate; (2) Hotel bar vs. neighborhood 7-Eleven spirits: Bangkok's hotel bars charge international-level prices for beer and spirits (฿300–600 for a Singha beer, ฿500–2,000 for cocktails); the same Singha beer from the 7-Eleven downstairs costs ฿68; the optimal Bangkok strategy for drinking budget management is neighborhood pre-loading before nightlife venues; (3) Mall cinema vs. neighborhood cinema: Bangkok's shopping mall cinemas (Major Cineplex, SF Cinema, Paragon Cineplex) have great facilities but premium prices (฿200–500 for standard seats, up to ฿1,200 for luxury screening); neighborhood cinemas in outer Bangkok districts charge ฿100–150 for the same films; (4) Museum free days: Bangkok's major national museums (National Museum Bangkok, Museum of Siam) have reduced or free entry days for Thai nationals; foreigners typically pay ฿200–300; however, the Museum of Siam offers free entry (managed by the Thai Heritage area authority) — verifying current free entry policies before visiting saves the admission cost; (5) Transport timing economics: Grab surge pricing during Bangkok rush hour (7–9am, 5–8pm) can increase standard fares 40–80%; BTS fares never surge; for consistent-cost commuting, BTS is not only faster but also provides price certainty that Grab during peak hours does not.",
  },
];

export function BangkokCostOfLiving() {
  return (
    <div className="rounded-2xl border border-emerald-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-emerald-700 mb-3">
        💰 Bangkok cost of living — monthly budget breakdown, money management & price vs. value guide
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-emerald-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-emerald-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-emerald-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
