const SPOTS = [
  {
    name: "Hun Lakhon Lek (Royal Marionette Theater) — Bangkok's Traditional Thai Puppet Art",
    emoji: "🎭",
    area: "Joe Louis Theatre: Asiatique the Riverfront Night Market (Charoen Krung Road, Asiatique Pier from Saphan Taksin BTS); traditional hun lakhon lek puppets also performed at: National Theatre Bangkok (Rachini Road, Sanam Luang area) during cultural festivals; Wat Pho cultural performances on special occasions; puppet tradition origin: Khruu (master) Joe Louis (Sakorn Yangkheosod) developed hun lakhon lek into a performance art form; Thai Puppet Center at Si Thamma School (less accessible to tourists); the hun krabok (rod puppet) tradition: older form, shorter puppets operated from below with visible rods",
    price: "Joe Louis Theatre Asiatique: approximately ฿1,200–1,500 per adult for performance with dinner or ฿700–900 for performance only (prices vary by package); traditional puppet performance at National Theatre: ฿80–500 depending on seat tier and performance type; hun lakhon lek workshop (when available): approximately ฿1,500–3,000 for hands-on puppet operation lesson; puppet souvenir purchase: folk craft-quality hun krabok puppets: ฿300–1,500 at Chatuchak Weekend Market; museum-quality or artist-crafted hun lakhon lek figures: ฿5,000–50,000+",
    why: "Thai traditional puppet theater represents a disappearing performance art that was historically central to Thai royal court entertainment: (1) Hun lakhon lek — the Thai royal marionette form: hun lakhon lek (เชิดหุ่นหลวง, royal puppet) is the most sophisticated form of Thai puppetry, using highly crafted marionettes approximately 50–80cm tall, each operated by three puppeteers (two holding control bars, one for additional articulation) visible onstage in black clothing; the puppets perform episodes from the Ramakien (Thai adaptation of the Ramayana epic), lakhon (classical court drama), and traditional folk tales; the puppets have articulated faces (moving eyes, mouths) and elaborate traditional Thai costumes matching classical court performance dress; (2) The near-extinction and revival: hun lakhon lek essentially disappeared from active performance during the mid-20th century; the form was revived by Khruu (Master) Joe Louis (Sakorn Yangkheosod, 1934–2004), who spent decades reconstructing the craft and training new puppeteers; the Joe Louis Theatre, continued after his death by his students, is Bangkok's primary venue where this art form is kept alive; without continued support and audience, the form faces extinction risk again; (3) The Ramakien and Thai puppet narrative: the Ramakien stories performed through hun lakhon lek are drawn from Thailand's national literary epic (adapted from the Hindu Ramayana); the performances dramatize battles between the god-hero Phra Ram and the demon king Totsakan; the demon characters (yak) are the most visually dramatic — large, elaborately decorated, painted faces; understanding that puppet theater was the original way the Ramakien epic was presented to the Thai public (before print, film, or television) contextualizes its cultural importance; (4) Hun krabok — the older folk puppet form: hun krabok (ถุงหุ่นกระบอก, rod puppet) is an older and more theatrical Thai puppet form — puppet is smaller (25–35cm), operated by an internal rod from beneath; performances are traditionally more comedic and vernacular than the court-style hun lakhon lek; hun krabok is more accessible as a folk entertainment form; (5) Thai shadow puppetry (nang) — the southern connection: while not Thai puppet theater in the strictest sense, southern Thailand's nang talung (shadow puppet theater, from Nakhon Si Thammarat) represents another major Thai puppetry tradition; large shadow leather figures (nang yai, used in royal court) and smaller regional figures (nang talung) are cultural forms; Bangkok visitors can see nang yai at the National Museum and Fine Arts Department exhibits.",
    tip: "Experiencing hun lakhon lek in Bangkok: (1) Joe Louis Theatre at Asiatique is the most accessible performance but the tourist-oriented setting (dinner theater at a riverfront mall) reduces cultural authenticity; however, the actual puppet performance quality and craftsmanship remain genuinely excellent; (2) National Theatre Bangkok alternatives: occasional hun lakhon lek and traditional performance programs at the National Theatre (near Grand Palace/Sanam Luang) offer lower prices and more culturally grounded settings; check the Fine Arts Department (กรมศิลปากร) website or call for current program schedule — performances are irregular; (3) Puppet appreciation at the National Museum: the National Museum Bangkok (Na Phra That Road, near Grand Palace) has historical puppet examples including large nang yai shadow puppet leather figures and older traditional puppets; viewing these provides the historical context that performance attendance doesn't; (4) Joe Louis Theatre performance booking: book online in advance (Asiatique is a popular dinner destination, performances may sell out on weekends); performance approximately 70 minutes; (5) Chatuchak Weekend Market for puppet crafts: several Chatuchak stalls (sections dealing in Thai crafts, section 26 area) sell decorative hun krabok-style puppet figures as collectable crafts; the craftsmanship quality varies widely — look for pieces with articulated (not rigid) features for display quality.",
  },
  {
    name: "Khon Mask Dance Theater — Bangkok's Most Spectacular Classical Performance Tradition",
    emoji: "👺",
    area: "Primary Khon performance venues in Bangkok: Sala Chalermkrung Royal Theatre (Charoen Krung Road, Ratchawong area, near Chao Phraya, MRT Wat Mangkon) — the primary venue for large-scale Khon productions; Sala Chalermkrung is a 1930s Art Deco cinema-converted performance venue; SALA Rattanakosin (hotel venue for smaller Khon-format performances); Jim Thompson House occasional cultural performances; Khon performances at major Buddhist and royal holidays at National Theatre; Thai Cultural Centre (Huai Khwang) for major Khon productions by the Fine Arts Department; Siam Niramit (Ratchada area) — Thai cultural mega-show incorporating Khon elements within larger production",
    price: "Sala Chalermkrung Khon performances: ฿800–1,500 per ticket depending on seat position and production scale; Fine Arts Department National Theatre productions: ฿80–500 (subsidized cultural institution pricing); Siam Niramit (Ratchada): ฿1,500–2,200 for the dinner show package (includes Khon-influenced cultural spectacle, 80-minute performance, optional dinner); Jim Thompson House occasional Khon events: varies by event; UNESCO inscription impact: Khon was inscribed on UNESCO Intangible Cultural Heritage list in 2018 — this has increased visibility and government support but ticket prices vary by venue",
    why: "Khon (โขน) mask dance theater is Thailand's most elaborate and visually spectacular classical performing art form: (1) What Khon is: Khon is a classical Thai dance-drama performed in elaborate costumes and distinctive masks; traditionally performed exclusively at the royal court, Khon dramatizes episodes from the Ramakien epic; the characters are divided into types: human characters (phra — male noble, nang — female noble), demon characters (yak — demons, with large colorful elaborately decorated masks), monkey warrior characters (ling — monkeys, also masked), and divine beings; the masks themselves are works of art, typically lacquered with colored glass mosaic inlays; (2) The choreography and training: Khon performers train for years to achieve the precise body movements, hand positions (mudra-like in precision), and spatial patterns; the choreography is codified — specific movements correspond to specific emotional states or narrative actions; female characters perform in head ornaments (without full-face masks) with equally precise stylized movement; male-human and divine characters also perform without full-face masks; only yak (demon) and ling (monkey) characters wear full-face masks; (3) Musical accompaniment: live performance accompaniment uses the piphat ensemble — traditional Thai classical orchestra (ranat ek xylophone, khong wong gong circle, pi oboe, drums, and percussion); narrators/singers (who recite the story and dialogue) accompany the masked performers who do not speak; the interplay of the masked performers' gestural language and the sung narration creates the distinctive aesthetic; (4) Khon's royal and religious significance: Khon was historically performed exclusively for the royal court — the Ramakien's narrative of Phra Ram's divine victory over the demon Totsakan carried religious and monarchical significance (the king embodied Phra Ram's divine authority); Khon's expansion to public performance and commercial venues is a relatively recent development; the royal family continues to patronize major Khon productions at Sala Chalermkrung; (5) Khon costume as material culture: the Khon costumes are themselves extraordinary — embroidered silk, gilded decorative elements, elaborate headdresses (chada crown-like structures); the costumes for major characters may require hours to put on and cost millions of baht to produce; the costume-making craft (including the mask-making tradition) is a separate specialized craft maintained by Fine Arts Department artisans.",
    tip: "Khon viewing experience: (1) Sala Chalermkrung is Bangkok's best Khon venue for regular visitors — the Art Deco theatre is beautiful, productions are well-staged, and the company maintains the tradition at the highest level; check salachalermkrung.com for current production schedule (typically runs episodes in sequence during the season); (2) Choose episode strategically: the Ramakien has many episodes; productions featuring the battle scenes (yak/ling characters in combat) are the most visually dramatic; the introductory 'synopsis' episode may not showcase the most striking costuming; ask the box office about which characters appear in the current production; (3) Bring binoculars if sitting in the upper tier: at Sala Chalermkrung, the mask details (colored glass work, gilded details) are extraordinary up close; the theater is medium-sized but binoculars enhance the mask appreciation from middle/back rows; (4) Royal Patronage performances: occasionally Khon performances are given under royal patronage at special events; these are the highest-standard productions but require social connection to attend; the Fine Arts Department posts annual production schedule through their social media channels; (5) Siam Niramit (Ratchada area): a separate mega-production (not purely Khon but incorporating classical Thai performance within a large tourist cultural show format) provides a higher-production-value but less culturally focused alternative for visitors who want spectacle over cultural depth.",
  },
  {
    name: "Bangkok's Traditional Crafts Ecosystem — Where to See, Learn & Buy Authentic Thai Handicrafts",
    emoji: "🪔",
    area: "Major Bangkok craft zones: Charoenkrung Road area — river-adjacent craft workshops (gold leaf, lacquerware, traditional textile shops); Jim Thompson House museum shop (Siam area, authentic traditional Thai textiles); Narayphand (government craft shop, traditional Thai handicrafts, Ratchadamri Road, near Central World); SUPPORT Foundation (royal-patronage social enterprise selling authentic northern Thai hill tribe crafts and central Thai textiles, multiple Bangkok locations); River City Bangkok antique section (authentic antique Thai crafts, ceramics, Buddha art — subject to export restrictions); Chatuchak Weekend Market sections 7-8, 10-11 (authentic craft vendors among tourist goods — requires careful selection); Pak Klong Talat (flower market, Pak Klong Talat pier area) for fresh flower craft culture; Maharat Night Bazaar near Tha Maharaj (Tha Maharaj Pier, near Grand Palace) for riverside craft market",
    price: "Traditional Thai craft price reference: gold leaf for Buddha gilding (wat temple visits): ฿10–50 per sheet; traditional Thai silk fabric (Jim Thompson, high-end): ฿800–5,000+ per meter; SUPPORT Foundation hill tribe textiles: ฿200–5,000 depending on piece complexity; traditional nielloware (decorative silver work with black inlay, Southern Thai craft): ฿300–3,000; benjarong (traditional five-color ceramic ware, high quality): ฿500–10,000 per piece; traditional lacquerware (black lacquer on wicker or carved wood with gold motifs): ฿200–15,000 depending on quality and size; celadon ceramics (Northern Thai tradition, green-glazed): ฿150–3,000 per piece",
    why: "Bangkok is the commercial hub for Thailand's extraordinary traditional handicraft traditions, though the visitor challenge is distinguishing authentic craft from mass-produced tourist goods: (1) Thailand's craft traditions and their regions: Thai traditional handicrafts are geographically specific — benjarong (five-color palace ceramics, Central Thai, produced primarily in Samut Sakhon); nielloware (southern tradition, Nakhon Si Thammarat origin); celadon (northern, Chiang Mai/Lampang origin); mudmee silk (Isaan ikat-pattern silk, Khon Kaen and Surin traditions); triangular pillow and northern textile weaving (hill tribe traditions); traditional Thai lacquerware (central and northern traditions, related to Burmese and Lao traditions); (2) Gold leaf and temple craft economy: gold leaf (sold at temples and craft shops throughout Bangkok) is applied to Buddha images by merit-makers; Bangkok has small gold leaf workshops in the Charoenkrung area (river district) that have operated for generations; observing the workshop process reveals the labor intensity of traditional craft production; (3) The SUPPORT Foundation — royal-patronage craft marketplace: the SUPPORT Foundation (Foundation for the Promotion of Supplementary Occupations and Related Techniques of Her Majesty Queen Sirikit) markets authentic hill tribe and traditional crafts made by members of the rural and hill tribe communities under quality supervision; this is one of Bangkok's most reliable sources for ethically produced authentic traditional crafts without concern for mass-production substitution; (4) Craft certification and authenticity challenges: the Bangkok tourist craft market is substantially flooded with mass-produced imitations of traditional crafts (machine-made 'silk', factory-produced 'hand-painted' ceramics, non-traditional 'traditional' items); reliable authenticity markers: hand-weaving shows slight irregularity in pattern (machine-made is perfectly regular); genuine silk vs. synthetic can be tested (silk burns with a protein-char smell, synthetic melts); provenance documentation from SUPPORT Foundation or reputable dealers; (5) Bangkok craft workshops for hands-on learning: several Bangkok craft programs teach traditional skills: traditional Thai cooking at cooking schools (Silom Thai Cooking School, Blue Elephant, Amita Thai Cooking Class); traditional flower arrangement (at some Bangkok hotels); traditional silk weaving (Jim Thompson Farm in Khorat, organized day trips); basic silk weaving demonstrations at certain Chatuchak stalls.",
    tip: "Bangkok craft shopping guide: (1) Narayphand (Ratchadamri Road, near Central World) is the government-operated Thai handicraft center with quality assurance — prices are fair and authenticity is guaranteed; particularly useful for buying traditional benjarong ceramics, traditional Thai jewelry, and high-quality traditional textiles; (2) Jim Thompson House and shop: the Jim Thompson brand (founded by American expat James H.W. Thompson who revived Thai silk trade from 1950s) is Bangkok's most prestigious silk retailer; Jim Thompson products are authentic (hand-woven silk) though not inexpensive (and not traditional in design — Jim Thompson stylized traditional silk for Western market); (3) Chatuchak Weekend Market craft navigation: most authentic crafts at Chatuchak are in the outer ring sections (sections 7, 8, 10, 11 — less trafficked, more specialist vendors); the inner ring and gate-adjacent areas have higher tourist goods density; (4) Ceramic craft spotting: Chatuchak has several genuine ceramic artists selling original work alongside mass-produced ceramics; look for: signed pieces (artist signature indicates individual maker), slight imperfections in glaze (hand-applied glaze), variation within the displayed pieces (identical-looking pieces indicate mold-production); (5) Export awareness: certain antique Thai crafts (particularly Buddha images, antique ceramics, and antiquities more than 100 years old) require export permits from the Fine Arts Department; River City Bangkok's antique dealers are generally knowledgeable about which pieces require permits; buying from reputable dealers ensures proper documentation.",
  },
];

export function BangkokPuppet() {
  return (
    <div className="rounded-2xl border border-rose-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-rose-700 mb-3">
        🎭 Bangkok traditional performance — hun lakhon lek puppet theater, Khon mask dance & Thai handicrafts
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-rose-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-rose-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-rose-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
