const TOPICS = [
  {
    title: "Bangkok VPN & Internet Censorship — What's Blocked, What's Legal & Digital Freedom",
    emoji: "🔒",
    summary: "Thailand has selective internet censorship and content restrictions that visitors using VPNs should understand: (1) Thailand's internet censorship scope: Thailand operates under the Computer Crime Act (2007, amended 2017) which gives the government broad powers to block websites; content blocked in Thailand includes: some political content critical of the monarchy (lèse-majesté related), certain gambling sites, and historically piracy sites; Thailand is NOT in the same restrictive category as China (Great Firewall), Iran, or Russia — mainstream international websites (Google, Facebook, Instagram, YouTube, Netflix, WhatsApp, Line) are freely accessible; (2) VPN legal status in Thailand: VPN use in Thailand is not explicitly illegal; the Computer Crime Act creates liability for accessing content that is illegal under Thai law even via VPN, not for using VPN tools themselves; in practice, tourists using VPNs for personal privacy or to access home-country streaming services are not targeted by Thai authorities; (3) Streaming and content access: Netflix Thailand has a different content library than US/UK Netflix (Thai content is stronger, some US content missing); using VPN to access home-country Netflix library is technically against Netflix's terms of service but not illegal in Thailand; Hulu, Disney+, Amazon Prime regional restrictions apply in Thailand and VPN is commonly used to circumvent these; (4) Censored content categories: websites genuinely blocked in Thailand include some criticism of royal family members, certain gambling platforms, piracy sites (torrent trackers), and historically some political opposition sites; everyday tourist use of the internet is unaffected by Thai censorship; (5) Thailand's internet speed context: Bangkok's internet infrastructure is well-developed; 4G/5G mobile coverage throughout Bangkok is excellent; most Bangkok cafés, hotels, and coworking spaces have fiber-broadband Wi-Fi (100–1,000 Mbps); bandwidth is generally not a limitation for remote work from Bangkok.",
    action: "Reliable VPN providers for Thailand: ExpressVPN, NordVPN, Surfshark, ProtonVPN, Mullvad (privacy-focused) — all work in Thailand; Thai ISP blocked sites: relatively minimal vs. Asia's most restrictive countries; mobile data Thailand: True Move H, AIS, DTAC all offer 30-day tourist SIM with 15–30GB data from ฿299–499 at Suvarnabhumi airport arrival hall; eSIM option: Airalo, Truemove eSIM, AIS eSIM for compatible devices without physical SIM swap; Bangkok internet speed testing: fast.com or speedtest.net to verify connection quality.",
  },
  {
    title: "Bangkok Apps You Need — LINE, Grab, Wongnai & The Essential Digital Stack",
    emoji: "📱",
    summary: "Bangkok's digital ecosystem runs on a specific set of Thai and international apps that are essential for practical city navigation: (1) LINE as Bangkok's primary communication platform: LINE (Japanese messaging app) is the dominant communication app in Thailand (approximately 44 million Thai users); virtually all Bangkok businesses, service providers, and individuals use LINE as their primary messaging and scheduling channel; booking Bangkok restaurants, nail salons, hospitals, language tutors, and almost any service happens via LINE; installing LINE with a phone number-registered account is functionally required for extended Bangkok engagement; (2) Grab as Bangkok's primary ride-hailing and delivery app: Grab (Singapore-founded, Southeast Asia dominant app) is Bangkok's primary app for taxi/car rides (GrabCar), motorcycle taxis (GrabBike), food delivery (GrabFood), grocery delivery (GrabMart), and financial transfers (GrabPay); Grab has higher Bangkok market penetration than any international equivalent; (3) Wongnai as Bangkok's food review platform: Wongnai (Thailand's Yelp equivalent, in Thai language) has more comprehensive Bangkok restaurant reviews than any international platform; Google Maps Bangkok reviews are decent but less complete than Wongnai for local Thai restaurants; the Wongnai app with auto-translate is useful for non-Thai readers; (4) Bangkok-specific navigation apps: Google Maps Bangkok is generally accurate for BTS/MRT routing; BTS SkyTrain official app for real-time BTS status; Raptor for bus tracking (new, improving); Moovit for multi-modal Bangkok transport routing; (5) Thai mobile banking apps: for Bangkok residents (not short-term tourists), KBank K PLUS (Kasikorn Bank's mobile banking app) and SCB Easy are the primary banking apps; PromptPay (QR payment system) through these apps is how many Bangkok payments work; foreign visitors can register their own bank card in Grab for payment without needing Thai bank accounts.",
    action: "Essential app install list for Bangkok: (1) LINE messenger; (2) Grab; (3) Google Maps (Thailand region maps downloaded offline); (4) Wongnai (Thai food, some English); (5) BTS SkyTrain app; (6) Raptor bus (if planning bus use); (7) IQAir or AirVisual (air quality); (8) your travel insurance app (emergency contacts); optional but useful: Agoda/Booking.com for last-minute hotel; Airbnb (limited Bangkok inventory due to regulations); Klook (activities booking); Thai translation app (Google Translate with camera function for menus); optional Thai app: Shopee Thailand for Bangkok delivery; Foodpanda as Grab Food alternative.",
  },
  {
    title: "Bangkok WiFi & Mobile Data — Coverage, SIM Cards & Working Remotely",
    emoji: "📶",
    summary: "Bangkok's digital connectivity for visitors is among Asia's most comprehensive: (1) Bangkok's Wi-Fi culture: Bangkok has extremely high coffee shop Wi-Fi density; virtually every Bangkok café (international chains and local Thai cafés) offers complimentary Wi-Fi with purchase; coworking spaces (Bangkok is one of Southeast Asia's largest coworking markets) have guaranteed high-bandwidth connectivity; 7-Eleven has free Wi-Fi (AIS-network, registration required via Thai mobile number or social login) at most locations; (2) Thai mobile SIM options for visitors: three major operators — AIS (largest, best rural coverage), True Move H (competitive urban pricing, excellent Bangkok and tourist area coverage), DTAC (now merged with True); tourist SIMs available at Suvarnabhumi and Don Mueang airports from the arrival hall shops; most tourist SIMs offer 15–30GB data valid for 30 days at ฿299–499; (3) 5G coverage in Bangkok: 5G network coverage exists in Bangkok's central districts (AIS and True Move H have deployed 5G in key Bangkok areas); 5G SIMs are available; speeds in covered areas reach 300–800 Mbps; practical difference for most visitor usage: 4G (50–150 Mbps in Bangkok) is entirely adequate for video calls, streaming, and remote work; 5G provides speed advantage mainly for large file transfers; (4) eSIM options for Bangkok: eSIM-compatible devices (iPhone XS+, Google Pixel 3+, Samsung Galaxy S20+, many recent devices) can activate Thai SIMs digitally before arrival; Airalo marketplace, Truemove eSIM (purchase at airport), and AIS eSIM are reliable options; activating an eSIM in Thailand is possible at the airport; (5) Bangkok remote work connectivity assessment: Bangkok's connectivity is excellent for remote work by developing country standards and competitive with Western cities; the primary connectivity challenges are: 7-Eleven and street-level free Wi-Fi with variable quality (bandwidth shared, VPN performance reduced); some older Bangkok hotels have poor in-room Wi-Fi despite good room rates (room connectivity varies significantly within the same hotel); coworking spaces provide the most reliable bandwidth for professional remote work.",
    action: "Airport SIM purchase: AIS, True Move H, and DTAC shops at Suvarnabhumi arrival Level 1 (before exit); eSIM Thailand options: Airalo (airalo.com), Truemove H eSIM (buy at airport or online pre-arrival); Bangkok coworking Wi-Fi reliability: Hubba Ekkamai, The Hive (multiple Bangkok locations), Samyan Mitrtown coworking, HUBBA-TO for consistent bandwidth; testing internet speed: fast.com for Netflix servers (good test for streaming bandwidth), speedtest.net for general speed; hotel Wi-Fi tip: request room closest to Wi-Fi access point at check-in — Bangkok hotel room signal quality varies significantly by room location.",
  },
];

export function BangkokVPN() {
  return (
    <div className="rounded-2xl border border-violet-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-violet-700 mb-3">
        📱 Bangkok digital life — VPN & internet censorship, essential apps & mobile connectivity
      </div>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-violet-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-violet-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
