const SPOTS = [
  {
    name: "Bangkok Go-Kart Tracks — Indoor & Outdoor Racing Venues",
    emoji: "🏎️",
    area: "Bangkok go-kart venues: SpeedPark Bangkok (On Nut area, Sukhumvit 77, one of Bangkok's most established tracks); EasyKart Bangkok (indoor electric kart track, Central Westgate mall, Nonthaburi — Bangkok periphery); Fastlane Karting (Bang Na, near IKEA, outdoor track); Bangkok Racing Circuit (Minburi area, outer eastern Bangkok, closed/changed management over years — verify before going); Pattaya International Circuit (90km from Bangkok, legitimate racing venue used for track days); Central Westgate karting (north Bangkok, accessible via MRT/BTS interchange then Grab); additional indoor karting: various Go-Kart entertainment venues inside Bangkok's major entertainment complexes",
    price: "SpeedPark Bangkok: ฿200–350 for 10-minute session; EasyKart Central Westgate: ฿250–400 for session; helmet rental included at most Bangkok tracks; additional sessions typically discounted at ฿150–250 each; safety briefing: mandatory at all venues; minimum age restrictions: typically 10–12 years depending on track; adult karts vs. junior karts: separate tracks at multi-track venues; corporate event packages: ฿1,500–3,000 per person for group racing packages",
    why: "Bangkok's go-kart scene serves a distinct market combining expat leisure, local Thai racing enthusiasts, and family entertainment: (1) Indoor electric karting advantage: Bangkok's extreme heat makes indoor, air-conditioned electric kart tracks (like EasyKart at Central Westgate) more comfortable during midday hours than outdoor petrol tracks; electric karts are quieter and cleaner while providing adequate speed for recreational racing; (2) Thai motorsport culture: Thailand has produced international-level motorsport drivers (most notably Alexander Albon — half-Thai Formula 1 driver for Williams Racing); Thai motorsport culture is genuine and serious; karting is considered an entry point to motorsport for Thai children from wealthy families; Bangkok has a motorsport fanbase that follows Formula 1, MotoGP, and touring car racing seriously; (3) SpeedPark Bangkok's established history: SpeedPark has operated near On Nut area for years and is one of Bangkok's most consistently operational karting venues; the outdoor track uses petrol karts with genuine speed; race events and competitive lap timing attract local racing enthusiasts beyond the tourist-family market; (4) Pattaya International Circuit for serious track day: visitors serious about motorsport can arrange track days at Pattaya International Circuit (BIC, approximately 90 minutes from Bangkok by car); BIC hosts motorcycle track days (the primary market), occasional car track days, and has a legitimate circuit layout; (5) Corporate team building market: Bangkok's go-kart venues have developed a significant corporate team-building business alongside retail visitors; expat corporate groups (particularly Japanese, Korean, and European MNC Bangkok offices) book karting events as team activities.",
    tip: "Bangkok karting practical advice: (1) Outdoor track heat management: outdoor karting in Bangkok (like SpeedPark) during March–May peak heat requires sun protection and hydration management; sessions are short (10 minutes) which is manageable; wearing long sleeves (provided or self-supplied) protects from exhaust and track debris; closed-toe shoes are mandatory at all Bangkok kart tracks; (2) Traffic and arrival planning: SpeedPark Bangkok (On Nut area) is accessible from On Nut BTS station via Grab/taxi; Central Westgate (EasyKart) is a journey of 60–90 minutes from central Bangkok by BTS+MRT or Grab but is within a major shopping complex with extensive food options if waiting time occurs; (3) Minimum age/height reality: Bangkok's karting venues apply minimum age and height rules; calling ahead to confirm current rules prevents disappointment for families with young children; some venues have 'bambino' karts for very young children at slower speeds; (4) Session booking during peak times: weekend afternoons and public holidays are the busiest times at Bangkok karting venues; arriving at opening (typically 10am) or booking ahead via phone avoids the longest waits; (5) F1 viewing in Bangkok: for motorsport fans who can't get to a circuit, Bangkok's many sports bars (Cheap Charlie's, Q Bar, Levels, The Sportsman) show Formula 1 live broadcasts with significant Thai expat/tourist viewership; Singapore Grand Prix (typically September, similar time zone) and Japan Grand Prix are the most-watched races in Bangkok bars due to timing convenience.",
  },
  {
    name: "Bangkok Muay Thai — Learn to Train, Authentic Fights & Cultural Context",
    emoji: "🥊",
    area: "Bangkok Muay Thai gyms: Fairtex Gym (Bangplee, southern Bangkok outskirts, Thailand's most internationally known brand, also in Pattaya); Tiger Muay Thai (Phuket, not Bangkok — but the brand); Sor. Vorapin Gym (Khao San Road area, central Bangkok, tourist-accessible training); Charn Chai Muay Thai (Lad Phrao area, more authentic working-class gym, lower prices); Rajadamnern Stadium (Ratchadamnoen Nok Avenue, oldest Muay Thai stadium in Thailand, founded 1941); Lumpini Boxing Stadium (new location: Ram Intra Road, relocated from original Lumpini location); MBK Fight Night (Chatuchak, weekly tourist-oriented fight show); Bangkok's authentic gym scene: hundreds of gyms across Bangkok's outer districts used by Thai fighters training professionally",
    price: "Tourist Muay Thai training session (drop-in): ฿500–800 for 1.5–2 hour class; multi-day packages: ฿3,000–8,000 per week; Rajadamnern Stadium fight night tickets: ฿1,000–3,000 depending on seating (ringside vs. upper gallery); Lumpini Stadium tickets: ฿1,000–3,500; MBK Fight Night tourist shows: ฿1,200–2,500 (includes dinner); authentic local Muay Thai at provincial events outside Bangkok: ฿200–500; private training sessions at Bangkok gyms: ฿800–2,000/hour",
    why: "Muay Thai is both Thailand's national sport and one of the world's most effective combat sports — understanding it at depth goes beyond a tourist attraction: (1) Muay Thai's cultural status: Muay Thai (ศิลปะมวยไทย, the Art of Eight Limbs — using fists, elbows, knees, shins) is central to Thai male identity; historically, Muay Thai was a military training system and royal entertainment; the current modern sport form (with boxing rings, referees, weight classes) developed in the early 20th century during the reign of Rama VII; (2) The two main Bangkok stadiums: Rajadamnern Stadium (Ratchadamnoen Nok, 1941, the older venue) and Lumpini Boxing Stadium (relocated from the original Lumpini Park location to a new Ramkhamhaeng Road stadium in 2014) are the two main professional Muay Thai venues in Bangkok; both hold regular weekly fight programs (Rajadamnern typically Mon/Wed/Thurs/Sun; Lumpini Tues/Fri/Sat — verify current schedules as these change); professional Thai gambling on the fights happens at both venues through vocally active betting sections in the crowd; (3) Tourist vs. authentic fights: Bangkok offers a range of Muay Thai viewing from highly tourist-oriented shows (MBK Fight Night, IMPACT Arena shows) to authentic stadium fights; tourist shows feature shorter rounds, more theatrical presentation, and English commentary; Rajadamnern and Lumpini stadium fights feature professional Thai fighters, gambling crowds, and Muay Thai music (sarama — the traditional piphat ensemble that plays continuously during fights at increasing tempo); (4) Training as cultural immersion: participating in Muay Thai training (even one session at a tourist-friendly Bangkok gym) provides genuine insight into the sport; the Wai Kru Ram Muay (pre-fight ritual dance, honoring trainer and ancestors) and Ram Muay (unique style per trainer lineage) are taught even in tourist sessions; (5) Bangkok's professional fighter ecosystem: Bangkok's outer districts house dozens of professional Muay Thai training camps; fighters from across Thailand, Myanmar, Cambodia, Laos, and internationally relocate to Bangkok to train; the professional Muay Thai circuit is interconnected with Thai gambling networks and has complex governance.",
    tip: "Bangkok Muay Thai visitor guide: (1) Stadium gambling observation: attending a professional Muay Thai fight at Rajadamnern or Lumpini exposes visitors to Thailand's active gambling culture; the crowd sections actively betting (usually the cheaper upper gallery seats) use complex hand signal systems for odds communication; this is illegal technically but openly practiced; observing but not participating is the recommended visitor approach; (2) Choosing training gym: tourist-oriented gyms near Khao San Road (Sor. Vorapin, other Banglamphu area gyms) are the most accessible for short-stay visitors; more serious training (for visitors staying 1–4 weeks) benefits from slightly less tourist-optimized gyms in outer Bangkok (Charn Chai, Jockey Gym); the training quality difference is real — Khao San area gyms have many tourist students vs. working-class gyms with Thai fighters; (3) Fight night seating strategy: at Rajadamnern Stadium, the ringside seats (most expensive) provide proximity to the fighting and the traditional experience; the cheaper upper gallery has the active Thai gambling crowd, the loudest atmosphere, and the most authentic stadium culture; first-time visitors often enjoy the gallery experience more than ringside despite lower price; (4) Pre-fight rituals importance: the Wai Kru Ram Muay performed before each fight is a complete ritual performance of cultural significance; each fighter has an individual Ram Muay style reflecting their camp's lineage; this pre-fight ritual segment is often more culturally informative than the fight itself; (5) Female Muay Thai: women's Muay Thai has grown significantly in Thailand and internationally; Bangkok has multiple gyms with strong female instruction; female tourists can train Muay Thai at all tourist-oriented Bangkok gyms with no gender restriction in training.",
  },
  {
    name: "Bangkok Rock Climbing & Bouldering — Indoor Walls & Nearby Crags",
    emoji: "🧗",
    area: "Bangkok indoor climbing: Boulder Thailand (multiple locations, Ekkamai, Siam, On Nut — Bangkok's largest bouldering chain); Climb Central Bangkok (Lumphini, near Siam area); The Toprope Bangkok (outer Bangkok, varies location); ClimbSiam (Sathorn area, older established gym); X-Climb (Victory Monument area); outdoor climbing near Bangkok: Khao Yai area limestone crags (2.5 hours north); Kaeng Krachan area; best outdoor climbing: Krabi province (7+ hours drive or flight from Bangkok, world-class sport climbing at Railay and Ton Sai); Chiang Mai climbing (7+ hours north, Crazy Horse Buttress); Sam Roi Yot (south of Bangkok, 3 hours, climbing on coastal limestone)",
    price: "Boulder Thailand day pass: ฿350–450 (shoes included at some locations); Boulder Thailand monthly membership: ฿1,200–1,800; Climb Central day pass: ฿300–400; shoe rental: ฿50–80; harness rental (for top-rope): ฿50; beginner lesson (2 hours): ฿800–1,500; lead climbing course (3–6 sessions): ฿3,000–6,000; Krabi guided outdoor climbing day trip: ฿1,500–2,500; outdoor climbing gear (harness, shoes, helmet): available at climbing gyms and some Outdoor/sports shops in Bangkok",
    why: "Bangkok's indoor climbing scene has expanded significantly since 2018, making it a viable urban sport even without access to outdoor crags: (1) Bouldering's Bangkok growth: bouldering (rope-free climbing on short walls with crash pad landings) has grown substantially in Bangkok's urban fitness culture; the short-session format (no rope setup required) suits Bangkok's time-compressed lifestyle; Boulder Thailand's multi-location model has made bouldering accessible without requiring dedicated climbing gym travel; (2) Bangkok's climbing community: Bangkok's climbing community is international and socially active; a significant proportion are expat residents and long-term digital nomads; Bangkok climbing gyms function as social venues with post-session social gatherings; the community is welcoming to visiting climbers regardless of nationality; (3) Krabi's world-class context: visitors to Bangkok who are serious climbers often combine a Bangkok city stay with a Krabi trip (flight approximately 1.5 hours from Suvarnabhumi); Krabi's Railay and Ton Sai beaches have 600+ sport climbing routes on limestone pillars rising directly from Andaman Sea beaches — one of Southeast Asia's finest climbing environments; the Bangkok climbing community organizes Krabi trips regularly; (4) Heat management in Bangkok climbing: Bangkok's heat makes outdoor climbing at nearby crags uncomfortable during March–May; the high season for outdoor climbing in central Thailand is November–February (cooler, dry); Bangkok's indoor climbing venues solve the heat problem but replace it with the tradeoff of artificial routes vs. real rock; (5) Progression path: Bangkok's indoor gyms provide complete beginner-to-intermediate progression; Boulder Thailand in particular has graded routes from VB (beginner) through V8+ (advanced) with route setting that changes monthly to prevent staleness.",
    tip: "Bangkok climbing practical guide: (1) Boulder Thailand location selection: Boulder Thailand's Ekkamai location (BTS Ekkamai, 5-minute walk) is the most central and busiest; the On Nut location (BTS On Nut) is larger with more variety; both are 5-10 minutes from BTS stations making them genuinely accessible without Grab; (2) Peak hours at Bangkok gyms: Bangkok climbing gyms are most crowded 6–10pm on weekdays (after office hours) and 10am–2pm on weekends; arriving at opening (10am or 11am) on weekday mornings gives maximum wall access; (3) Community and route information: Bangkok climbing gyms' Instagram accounts and LINE groups post new route setting announcements; following Boulder Thailand, Climb Central Bangkok, and the Bangkok Climbers Facebook group gives access to route setting news, trip announcements, and the social calendar; (4) Gear shopping Bangkok: Bangkok has limited but growing dedicated outdoor/climbing gear retail; Basecamp Outdoor (Silom area) stocks some climbing gear; international brands (Black Diamond, La Sportiva) are available at Bangkok climbing gyms' pro shops and some outdoor specialty stores; prices are higher than home country for climbing gear; (5) Transition to Krabi: Bangkok climbing gyms are good environments to ask about the current Krabi trip calendar; many Bangkok climbers organize regular Krabi weekends; Krabi's town center has budget-friendly guesthouses that serve as climbing base; the low season (June–October) is wet with some rain days but Krabi climbing continues year-round as caves and overhanging routes remain climbable.",
  },
];

export function BangkokGoKart() {
  return (
    <div className="rounded-2xl border border-red-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-red-700 mb-3">
        🏎️ Bangkok action sports — go-karting, Muay Thai & indoor rock climbing
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-red-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-red-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-red-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
