const SPOTS = [
  {
    name: "Bangkok Skyscrapers & Observation Decks — Best Panoramic Views",
    emoji: "🏙️",
    area: "Bangkok panoramic viewpoints: King Power MahaNakhon (314m, 78th floor, glass floor observation deck, Chong Nonsi BTS); Baiyoke Tower II (309m, Bangkok's second tallest, Pratunam area, rotating observation deck floor 84); The Dome at State Tower (Silom, known from The Hangover Part II film, bar at summit); Vertigo and Moon Bar (Banyan Tree Hotel, 61st floor, Sathon Road); AboveEleven (33rd floor, Sukhumvit 11); VS-BKK (52nd floor, 'VS the Most Amazing Venue', Silom); Lebua at State Tower (Silom, restaurant/bar floor); Icon Siam river views; Asiatique Ferris wheel (35m, river bank); Wat Saket (Golden Mount) for 360° ground-level elevated views",
    price: "King Power MahaNakhon (SkyWalk with glass floor): ฿870 adult; Baiyoke Tower II (observation deck + buffet package): ฿850–1,200; Baiyoke Tower (observation deck only): ฿300–500; Vertigo Moon Bar (minimum spend): ฿600–1,000 drink minimum; AboveEleven rooftop bar (minimum spend): ฿500–800; Lebua Sky Bar (minimum spend): ฿600–1,000; Asiatique Ferris Wheel: ฿250–350; Wat Saket (Golden Mount): ฿20 entry; VS-BKK (minimum spend): ฿500–1,000",
    why: "Bangkok's skyline views provide some of Asia's most dramatic city panoramas: (1) King Power MahaNakhon glass floor: the MahaNakhon building's glass floor observation deck (installed at 314m on the 78th floor) allows standing on a transparent glass panel with Bangkok visible directly below; the psychological impact of the glass floor is genuinely significant; the pixel-design exterior of the MahaNakhon building is itself photographically distinctive from city level; (2) Golden hour versus blue hour: Bangkok skyline photography has two optimal windows; golden hour (5:30–7pm, when the low sun illuminates Bangkok's glass buildings in warm light) and blue hour (20–45 minutes after sunset when sky retains deep blue while city lights begin brightening); both windows create distinct moods; the transition period (sunset to blue hour) at a skybar is the ideal position; (3) Lebua sky bar's film fame: the Lebua at State Tower's Sky Bar (66th floor, 200m elevation) appeared in The Hangover Part II (2011); the film used the bar as the setting for the rooftop pool scene; the fame increased international tourism to the bar despite Bangkok having objectively higher bars; (4) Free vs. paid views: Wat Saket (Golden Mount) provides a free elevated 360° Bangkok view from 80m; the view is limited by shorter height but the historic temple context (viewing Bangkok from a Buddhist hill temple) is irreplaceable; the Chatuchak Park MRT area also has open elevated views; (5) Hotel pool bar views: Bangkok's many rooftop hotel pool bars (Holiday Inn Express Sukhumvit, etc.) provide city views with minimum spends of ฿300–500 (less than dedicated observation decks); these views are typically lower elevation but combine swimming, food, and viewing.",
    tip: "Bangkok viewpoint strategy: (1) Best timing for MahaNakhon: King Power MahaNakhon's glass floor observation deck is most dramatic after dark (when city lights create depth and the glass floor is maximally disorienting); however, arriving 30 minutes before sunset captures both golden hour and night city transition from the same position; (2) Cloud cover management: Bangkok's wet season (May–October) has afternoon clouds that can obscure panoramic views; checking weather apps and planning viewpoint visits for mid-morning on clear days is more reliable than evening visits during monsoon season; (3) Rooftop bar dress code: Bangkok's rooftop bars (Vertigo, Lebua, AboveEleven) enforce dress codes (smart casual minimum — no flip flops, no shorts, no tank tops); hotels explicitly enforce these codes and will turn away dressed-inappropriately visitors; packing specific footwear and clothing for evening rooftop bars avoids disappointment; (4) Helicopter tours: Bangkok has helicopter tour operators providing aerial views of Bangkok by helicopter (typically ฿15,000–30,000 for 20–30 minutes); this is the most comprehensive aerial perspective but at premium cost; (5) Drone photography regulations: flying personal drones over Bangkok requires Civil Aviation Authority of Thailand (CAAT) registration and specific flight area approval; flying near the Grand Palace, government buildings, and central Bangkok without permits is prohibited and enforced; hired professional drone operators with proper permits provide aerial footage for commercial or personal use.",
  },
  {
    name: "Bangkok at Night — City Lighting, Tuk Tuk Rides & After-Dark Navigation",
    emoji: "🌃",
    summary: "Bangkok's transformation after dark creates a different city experience: (1) Night light culture: Bangkok invests substantially in decorative lighting; the Chao Phraya riverfront (Asiatique, Icon Siam, and various pier areas), major BTS station areas, and shopping mall exteriors are dramatically lit; Chinatown's (Yaowarat) neon-lit signage and food stalls create one of Asia's most visually dense nightscapes; (2) Tuk tuk at night: while tuk-tuks are Bangkok's quintessential tourist vehicle, nighttime tuk tuk rides in Bangkok have a specific charm; the open vehicle and (slightly) cooler night air, combined with the visual stimulation of lit Bangkok streets, create a memorable urban experience; negotiating tuk tuk price before riding is essential (set price before entering, expect ฿200–600 for typical tourist routes at night); (3) Bangkok's 24-hour city zones: Bangkok has genuine 24-hour zones; 7-Eleven stores (6,000+ Thailand locations) are genuinely 24/7; night markets and late food areas include Sukhumvit Soi 38 (closing around 2am), Chinatown (active until midnight), and RCA (Royal City Avenue, club area until 2am); (4) Night bus routes in Bangkok: Bangkok's bus system operates limited overnight services; the night buses (O-range fare, ฿9.50–24) cover major routes but with reduced frequency; for late-night travel between locations not walkable, Grab is more practical than bus after midnight; (5) Safety after midnight: Bangkok's central tourist areas (Sukhumvit, Silom, Khao San Road) are safe after midnight with normal urban awareness; the most common late-night risks are: overpriced taxi drivers (using meters prevents overcharging, Grab is safer), drunk driving accidents from unlit motorcycle taxis, and misjudging distances on foot in an unfamiliar city.",
    area: "Bangkok night activity zones: Chinatown Yaowarat Road (dinner + street food, until midnight); Sukhumvit Soi 11 bar strip (late night, 11pm–2am); RCA Royal City Avenue (club district, midnight–2am); Asiatique Riverfront (evening market, 5pm–midnight); Soi Cowboy (entertainment district, 9pm–1am); Silom area bars (mixed, until 1am); Khao San Road (backpacker bar strip, until 2am); 24-hour food: Sukhumvit area stalls (some until 3am); Chinatown street food (late); Pratunam area (24h garment market activity)",
    price: "Tuk tuk ride (tourist rate at night): ฿200–600 negotiated; Night market food: ฿60–200/dish; Bar entry (some): ฿200–400 with drink; Night bus fare: ฿9.50–24; Grab at night: 20–50% surge possible but still meters; Chinatown street food meal at 11pm: ฿100–250; Night club entry: ฿300–600 typically; 7-Eleven convenience food: ฿30–150",
    why: "Bangkok's nighttime personality is as distinct as its daytime character: (1) Chinatown at night: Yaowarat Road's evening atmosphere (from 7pm onward) transforms the street from regular daytime commerce into one of Bangkok's most vibrant food and nightlife experiences; the gold shop signs remain lit in red and gold; seafood restaurants set up large crustacean displays on the sidewalk; locals and tourists mix at street food stalls eating grilled squid, roast duck, dim sum, and shark fin soup (ethically controversial but culturally significant); (2) The midnight Bangkok food scene: Bangkok's late-night food culture (midnight–3am) consists of specific restaurant types; night markets near club areas (RCA, Ekkamai, Thong Lo), post-bar Thai food spots (particularly grilled seafood and pork neck restaurants on Sukhumvit area sois), and convenience store microwave meals serve Bangkok's night owls; this culture is distinctly Thai and unlike Western late-night food options; (3) River at night: the Chao Phraya River at night reflects the lights of Wat Arun and the riverfront buildings; dinner cruises provide the most immersive river-at-night experience; the Asiatique pier area (with the Ferris wheel lit) and Icon Siam's riverside terrace are non-cruise alternatives for evening river viewing; (4) Bangkok's blue LED street lighting: Bangkok's street lighting upgrade in recent years introduced cool blue-white LED lighting throughout major roads; this lighting affects photography (creating a distinctive modern Bangkok city aesthetic) and navigation (very bright, good visibility); (5) Late temple visits: some Bangkok temples have evening visiting hours; Wat Pho is open until 10pm; the atmosphere of major temples at night (far fewer tourists, occasional monks chanting) provides a different experience than peak daytime hours.",
    tip: "Bangkok after-dark practical guidance: (1) Mobile phone navigation at night: Bangkok's soi numbering system (odd and even numbered sois on opposite sides of main roads, not always sequential) is confusing in daylight and more disorienting at night; Google Maps navigation with turn-by-turn audio is the most practical night navigation tool; (2) Alcohol and food budget planning: Bangkok's bar and restaurant pricing varies enormously at night; street food and local restaurants maintain daytime prices; rooftop bars and nightclubs have steep pricing; setting a specific budget for drinking and night entertainment in advance prevents unexpected overspending; (3) Motorbike taxi safety at night: Bangkok's orange-vested motorcycle taxi drivers remain available throughout the night; at night, both driver and passenger visibility decreases; wearing a helmet (always insist on one), riding at reduced speed, and avoiding extreme drunken motorcycle taxi use reduces accident risk; (4) Booking return transport in advance: late-night transport from Khao San Road, Asiatique, and RCA is reliably available through Grab; during peak times (1–2am when clubs close) Grab surge pricing increases and waiting time increases; opening the Grab app and booking before leaving the venue is better than standing outside looking for taxis; (5) Chinatown street food hygiene at night: the highest-quality Chinatown street food vendors typically sell out by 10pm; vendors still operating after 10:30pm have either high demand or slower turnover; choosing vendors with active cooking and visible ingredient freshness is the standard hygiene assessment.",
  },
  {
    name: "Bangkok Dawn & Early Morning — Monks, Markets & Sunrise Views",
    emoji: "🌅",
    summary: "Bangkok's pre-dawn and early morning hours (4:30am–8am) offer experiences unavailable at any other time: (1) Monk alms procession (tak bat) at dawn: Bangkok's traditional neighborhoods (particularly Banglamphu near Khao San Road, Chinatown, and Thonburi) have active monk alms processions starting at 5:30–6:30am; monks in saffron robes walk in procession with alms bowls; laypeople offer sticky rice and cooked food; the visual of saffron-robed monks against Bangkok's early morning blue light is photographically distinctive; (2) Flower market at 3am: Bangkok's wholesale flower market (Pak Klong Talad, near Memorial Bridge/Saphan Phut) is most active between 2am and 6am when wholesale buyers arrive; arriving at 3am at the flower market means walking through towers of fresh-cut orchids, roses, lotus, jasmine, and exotic tropical flowers in the darkness; an extraordinary sensory experience; (3) Fish market dawn: Bangkok's fish markets (Klong Toey Port area's wholesale fish market) activate at 4–6am with trucks and dealers; this is Bangkok's most authentic pre-dawn commercial experience; (4) Bangkok Noi train market (Talat Rot Fai): the original 'train market' in Bangkok Noi (Sirindhorn Road area) opens as early as 6am on weekends for vintage and food; (5) Sunrise photography from river: the Chao Phraya River at dawn (5:30–7am) has the most dramatic light for photography; Wat Arun (Temple of Dawn, facing east) was specifically built to receive dawn light; the early river boats (Chao Phraya Express Boat beginning at 5:45am) allow positioning on the water at sunrise.",
    area: "Bangkok dawn activities: Pak Klong Talad (flower market, Memorial Bridge) active 2–7am; Monk alms procession (tak bat): Banglamphu 5:30–7am, Yaowarat/Chinatown 6–7am; Klong Toey wet market: 4–7am; Talad Thai (Rangsit, large produce market): 24h but peak at 4–7am; Chatuchak Or Tor Kor (adjacent) dawn food: 5:30am onwards; Sanam Luang dawn: government guards and morning exercise groups at 5–7am; BTS first train: 5:15am; first Chao Phraya Express Boat: approximately 5:45am; 7-Eleven and Family Mart: genuinely open at any hour",
    price: "Pak Klong Talad entry: free; Monk alms offering set (purchased from stall near temple): ฿50–150; Dawn Chao Phraya Express Boat: ฿15–30; Klong Toey wet market: free; Or Tor Kor Market fresh food (dawn quality): ฿50–200; Early morning coffee at Thai café: ฿30–60 (standard Thai coffee/tea); Bangkok traditional breakfast (jok rice porridge, or khanom krok): ฿40–80",
    tip: "Bangkok dawn experience planning: (1) Safety at 3am for flower market: Bangkok's Pak Klong Talad area at 3am is busy with commercial activity; the area is safe for dawn market visits with standard urban awareness; the commercial activity (buyers, sellers, trucks) means the area has more people at 3am than many Bangkok neighborhoods at 9pm; (2) Alms giving etiquette: if participating in monk alms giving (tam bun, making merit), purchasing a specific alms set (rice and food suitable for monks) from vendors near temples rather than offering unpackaged food from street stalls; kneeling to offer (so your offering hands are below monk's eye level) and not touching the monk follow the correct protocol; (3) Dawn photography light quality: Bangkok's dawn (approximately 6am year-round in the tropics) occurs almost exactly the same time every day; the warm light lasts only 15–20 minutes before the sun rises high enough to create harsh midday-quality light; arriving at positions (Chao Phraya river bank, Wat Arun exterior) 30 minutes before sunrise time allows the full golden window; (4) Thai breakfast experience: 5:30–7am is the peak time for authentic Thai breakfast culture; jok (rice porridge/congee), patongko (Chinese doughnuts), khanom krok (coconut rice pancakes), and traditional Thai coffee from roadside vendors are available at morning market areas; these vendors close by 8–9am; (5) Night before planning: attending a 3am flower market or 5:30am alms procession requires either arriving late the previous night and staying awake or setting a very early alarm from accommodation within walking distance; planning accommodation location with the dawn activity destination is the most practical approach.",
  },
];

export function BangkokViewpoints() {
  return (
    <div className="rounded-2xl border border-indigo-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-indigo-700 mb-3">
        🏙️ Bangkok skyline & time of day — observation decks, nightlife & dawn experiences
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-indigo-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-indigo-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-indigo-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
