const TOPICS = [
  {
    title: "Bangkok Maternity Care — Pregnancy Medical Services, Hospitals & Expat Birth Planning",
    emoji: "🤰",
    summary: "Bangkok is one of Asia's premier destinations for expat maternity care, combining high-quality obstetric services with experienced international patient facilities: (1) Bangkok's top maternity hospitals: Samitivej Hospital (Sukhumvit Soi 49) — particularly strong for obstetrics and neonatology; large expat maternity community (Japanese, Korean, Western); Samitivej Sukhumvit and Samitivej Srinakarin campuses both offer comprehensive maternity services; private delivery rooms with labor support; Bumrungrad International Hospital — comprehensive obstetrics department; international patient coordinator for birth planning; neonatal intensive care unit (NICU); Bangkok Hospital — maternity center at multiple campuses; BDMS hospital group; Mission Hospital (Mahesak Road) — Bangkok missionary hospital with strong maternity tradition; (2) Bangkok obstetric costs (private hospitals): standard natural birth at Samitivej or Bumrungrad: ฿80,000–150,000 total (includes: pre-natal care, delivery room, 2–3 day hospital stay); cesarean section: ฿150,000–250,000+; NICU costs if required: ฿20,000–50,000+ per day (varies significantly by requirement); antenatal care visits: ฿2,000–5,000 per visit; recommended insurance: comprehensive international health insurance (Cigna, Aetna, BUPA, Allianz) with maternity coverage and minimum 10-month waiting period pre-conception for maternity benefits to apply; (3) Thai government hospital alternative: for lower-cost maternity care, Thai government hospitals (Chulalongkorn Hospital, Siriraj Hospital) provide high-quality care at 70–80% lower cost; waiting times are longer and English communication is more limited; appropriate for Thai-language-capable patients and those without comprehensive insurance; (4) Birth registration for foreign nationals: babies born in Bangkok to foreign nationals require: birth certificate from the hospital; registration with the baby's parents' home country embassy in Bangkok; Thailand allows registration of foreign births at embassies (US Embassy, British Embassy, Australian Embassy all have birth registration services); the baby receives the nationality of the parents (not Thai nationality for most circumstances); dual nationality considerations vary by home country law; (5) Bangkok prenatal care ecosystem: comprehensive prenatal care equivalent to Western standards available at private Bangkok hospitals; standard prenatal package: regular OB/GYN visits, ultrasound (4D ultrasound available), NIPT testing (non-invasive prenatal testing, advanced chromosomal screening, approximately ฿15,000–30,000), glucose tolerance test, anatomy scan; most Bangkok private hospital OB teams are board-certified with subspecialty credentials (maternal-fetal medicine, reproductive endocrinology available at larger centers).",
    action: "Bangkok maternity care planning: (1) Hospital selection: visit 2–3 Bangkok maternity hospitals before choosing; ask about: specific OB/GYN credentials, neonatology support if complications arise, birth plan flexibility (partner present, water birth availability, delayed cord clamping), insurance direct billing arrangements; (2) Insurance timing critical: maternity insurance benefit waiting periods (typically 10–12 months) mean insurance must be in place before pregnancy begins for maternity coverage to apply; retroactive coverage is not available; contact insurance broker before trying to conceive; (3) Samitivej Sukhumvit maternity tour: Samitivej Hospital offers maternity ward tours for expectant parents — arrange through the hospital's international patient center; the tour includes: labor room, delivery room, post-natal ward, NICU; allows informed decision-making; (4) Embassy birth registration timeline: contact your home country embassy in Bangkok within 1 month of birth to understand the birth registration timeline and requirements; some embassies have appointment waiting times; US citizens: contact the American Citizen Services unit at the US Embassy; (5) Breastfeeding and new parent support: Samitivej Hospital and Bumrungrad have lactation consultants; Bangkok has an active La Leche League chapter for breastfeeding support; Bangkok Parent Network Facebook group connects new expat parents.",
  },
  {
    title: "Bangkok Fertility Treatment — IVF Costs, Thailand's Surrogacy Law & Reproductive Tourism",
    emoji: "🌸",
    summary: "Thailand's fertility medicine sector is one of Asia's most developed, combining high medical standards with costs significantly lower than Western equivalents: (1) Thai fertility clinic landscape: Bangkok's leading fertility clinics: Praram 9 Hospital IVF Center; Bangkok IVF Center (Bangkok Hospital Group); Vejthani Hospital Reproductive Medicine; Bumrungrad IVF Center; Samitivej Fertility Center; Thai-Chinese context: Thai reproductive medicine draws significantly from Japanese, Taiwanese, and Korean reproductive medicine influences and many senior Thai reproductive endocrinologists trained in these countries; (2) IVF cost comparison (Bangkok vs. international): Bangkok IVF cycle (fresh): ฿80,000–150,000 all-inclusive (medications included); equivalent USA: ฿400,000–700,000 equivalent; equivalent UK: ฿350,000–500,000 equivalent; equivalent Australia: ฿450,000–650,000 equivalent; Bangkok's IVF cost differential (60–75% lower) represents approximately ฿300,000–500,000 savings per cycle, making international IVF tourism to Bangkok economically significant even after flight and accommodation; (3) Frozen embryo transfer (FET): FET cycle in Bangkok: ฿30,000–60,000 (lower cost than fresh cycle, no medication for stimulation); couples who have banked embryos from a previous cycle can return to Bangkok for FET at significantly lower total cost; (4) Thailand surrogacy legal status: Thailand passed a Commercial Surrogacy Prohibition Act in 2015 following high-profile international cases that attracted negative press attention (Baby Gammy case, among others); commercial surrogacy is now illegal in Thailand; altruistic surrogacy (between closely related individuals with no commercial compensation) exists in a gray legal area; for intended parents seeking surrogacy, Cambodia, Laos, and Georgia are among alternative destinations; (5) Egg freezing and fertility preservation in Bangkok: egg freezing (oocyte cryopreservation) in Bangkok: ฿80,000–120,000 per cycle including medications; Bangkok has become a destination for younger international women (particularly Japanese, Korean, and Western) seeking egg freezing at lower cost than home countries; storage fees: ฿10,000–25,000 per year; Bangkok's fertility clinic infrastructure supports international patients who bank eggs in Bangkok for future use with Thai clinic protocols compatible with international clinic requirements.",
    action: "Bangkok fertility care access: (1) Clinic consultation: most Bangkok IVF centers offer initial consultation (remote video or in-person) before travel; bring complete reproductive history, prior IVF records if applicable, and partner's semen analysis if available; (2) Bangkok IVF cycle timing: an IVF cycle requires approximately 2–3 weeks in Bangkok (ovarian stimulation, monitoring, retrieval, transfer or freezing); planning accommodation near the clinic is important; Sukhumvit area (near Bumrungrad) and Ratchadapisek area (near Vejthani) have appropriate serviced apartment options; (3) Single-parent and same-sex couples: Thailand's private fertility clinics generally treat single women (using donor sperm) and, with some variation, same-sex female couples; same-sex male couples face surrogacy law barriers; confirm current clinic policy directly as regulations and clinic policies evolve; (4) Donor gametes in Bangkok: egg donation programs in Bangkok: eggs from Thai or international donors available through clinic donor programs; anonymity standards vary; sperm donation available from Thai and international donor banks; Bangkok fertility clinics can generally match donor characteristics (height, skin tone, education background); (5) International coordination: Bangkok's leading fertility clinics have experience coordinating with international doctors for pre-screening, monitoring before travel, and post-Bangkok care; ask the Bangkok clinic about their international coordination protocol before choosing.",
  },
  {
    title: "Bangkok Pediatric Healthcare — Children's Hospitals, Vaccinations & Travel Health for Families",
    emoji: "👶",
    summary: "Bangkok's pediatric healthcare infrastructure is comprehensive and experienced with international families, reflecting the large expat community and medical tourism sector: (1) Bangkok's top pediatric hospitals: Samitivej Srinakarin Hospital Pediatric Center — arguably Bangkok's most comprehensive pediatric facility; the Bumrungrad Kids Hospital — dedicated pediatric wing within Bumrungrad International; Bangkok Hospital Pediatric Center; Phyathai 2 Hospital pediatric department; Children's Hospital (Lad Yao, government hospital — the primary national referral pediatric hospital for complex cases); Siriraj Children's Hospital (government, Pinklao area — large public pediatric center); (2) Pediatric emergency in Bangkok: for a child requiring emergency care in Bangkok: Bumrungrad Hospital Emergency Department (Sukhumvit Soi 3) — 24-hour pediatric emergency with immediate physician access; Samitivej Hospital (Sukhumvit Soi 49) — 24-hour pediatric emergency with pediatric intensivists; Bangkok Hospital (multiple locations) — 24-hour emergency with pediatric capability; wait times at private hospitals for pediatric emergencies are typically under 30 minutes for triage; (3) Childhood vaccination in Bangkok: Bangkok's travel medicine and pediatric clinics can administer all standard and travel vaccinations; vaccines relevant to Thailand travel for children: Hepatitis A and B (standard), typhoid (oral or injectable), rabies pre-exposure prophylaxis (3-dose series, important given Thailand's stray dog population), Japanese Encephalitis (2-dose series for longer stays), meningitis; Bangkok Hospital's travel medicine clinic and Bumrungrad travel clinic provide comprehensive vaccination assessment; (4) Bangkok's stray dog and rabies reality: Bangkok and Thailand have significant stray dog populations; rabies is endemic in Thailand (wildlife reservoir); for children visiting Bangkok, pre-exposure rabies prophylaxis is strongly recommended by international travel medicine guidelines for stays over 1 month; if a bite or scratch from an unknown animal occurs: clean thoroughly with soap and water immediately, then seek Bumrungrad or Bangkok Hospital emergency department immediately for post-exposure prophylaxis assessment; (5) Pediatric medication access in Bangkok: many common pediatric medications (Calpol/paracetamol, antihistamines, basic antibiotics) are available over-the-counter at Bangkok pharmacies without prescription; bring your own supply of any prescription medication and any pediatric medicine the child takes regularly; dosing standards are consistent with international standards.",
    action: "Bangkok pediatric healthcare planning for families: (1) Pre-travel health check: consult your home-country pediatrician before Bangkok travel; obtain vaccination records, ensure all required travel vaccinations are administered; ask about prophylactic antibiotics for traveler's diarrhea in children (destination-specific protocols vary); (2) Samitivej Kids registration: if staying in Bangkok for more than a short visit with children, registering as a patient at Samitivej Pediatric Center creates a patient record that facilitates any required care; the registration process requires passport and insurance information; (3) Bangkok pediatric pharmacy strategy: carry adequate supply of: Calpol liquid or equivalent paracetamol for children (the brand is available in Bangkok Boots but bringing familiar medication is reassuring); oral rehydration salts (critical for traveler's diarrhea dehydration); any prescribed medication; insect repellent appropriate for children (DEET 10–30% for children over 2 months); (4) Animal safety with children: advise children on animal interaction in Bangkok: no petting stray dogs or cats; no feeding monkeys (where monkeys are present near temples in outer Bangkok and day-trip areas); immediate report if any contact with unknown animal; Bangkok's street cats are generally low-risk but stray dogs warrant more caution; (5) International school health services: Bangkok's international schools (ISB, NIST, Bangkok Patana, Harrow) have on-campus health centers with nurses and physician access; for children attending Bangkok schools, the school health center serves as a primary healthcare access point for minor illnesses and injury during school hours.",
  },
];

export function BangkokPregnant() {
  return (
    <div className="rounded-2xl border border-pink-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-pink-700 mb-3">
        🤰 Bangkok maternal & family health — maternity care, IVF & fertility tourism & pediatric healthcare
      </div>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-pink-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-pink-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
