const SPOTS = [
  {
    name: "Loi Krathong — Bangkok's Most Beautiful Festival on the Chao Phraya",
    emoji: "🪔",
    area: "Loi Krathong timing: full moon of the 12th Thai lunar month (typically November); Bangkok Loi Krathong venues: Sanam Luang (near Grand Palace, largest organized event); Asiatique Riverfront (riverside setting with fireworks); Chao Phraya riverside (multiple piers for krathong floating); Lumphini Park (lake setting, popular local choice); Siam Paragon and shopping mall events (indoor celebration setups); Chao Phraya cruises on the night (advance booking required); outer Bangkok: Wat Pho-adjacent riverfront for authentic atmosphere without mall commercial setting",
    price: "Krathong float purchase (banana leaf, traditional): ฿50–200; Decorated krathong (more elaborate): ฿150–500; Fancy commercial krathong (large, with decorations): ฿500–2,000; Loi Krathong river cruise dinner: ฿1,500–4,000 per person; Sanam Luang event: free (public event); Asiatique Loi Krathong event: free entry (restaurant/shopping spend); Lumphini Park: free; Biodegradable krathong (fish-food base): ฿80–300",
    why: "Loi Krathong is Bangkok's most visually spectacular traditional festival and a UNESCO-recognized cultural practice: (1) Festival meaning: Loi Krathong (ลอยกระทง — 'float a basket') involves floating decorated baskets (krathong) made from banana stems, banana leaves, and flowers on waterways as an offering to the water goddess (Mae Khongkha) and as symbolic release of misfortune; the floating krathong carries away bad luck and sins as it travels on the current; (2) Chao Phraya as celebration venue: the Chao Phraya River is Bangkok's primary Loi Krathong venue; thousands of krathongs float simultaneously from piers throughout Bangkok; the sight of thousands of candlelit floating baskets moving downriver is genuinely extraordinary; the Grand Palace and Wat Arun visible in the background of riverside venues creates a surreal festival atmosphere; (3) Yi Peng lanterns in Bangkok: while Yi Peng sky lantern releasing is most associated with Chiang Mai (where mass releases of sky lanterns in the same festival period create breathtaking photography), Bangkok also has some sky lantern releasing events; the Sanam Luang event occasionally includes sky lantern sections; mass sky lantern releases are now restricted in many areas due to aviation safety concerns but small-scale releases continue; (4) Krathong materials and environmental impact: traditional krathong were made of banana stems (fully biodegradable); commercial krathong often use foam (polystyrene) which pollutes waterways; Bangkok authorities have encouraged biodegradable krathong; fish-food krathong (compressed fish food that fish consume after the candle extinguishes) represent the most eco-friendly choice; (5) Sanam Luang official event: Bangkok's official Loi Krathong celebration at Sanam Luang (the ceremonial field near the Grand Palace) includes traditional performances, Thai classical dance, ceremonies, and supervised krathong floating at the Chao Phraya; this is the most culturally complete Loi Krathong experience in Bangkok.",
    tip: "Loi Krathong Bangkok visit strategy: (1) River venue booking for dinner cruises: the most photogenic Loi Krathong experience is from a Chao Phraya dinner cruise (Chao Phraya Princess, Manohra) that positions the vessel on the river during peak floating time (8–10pm); these cruises fill immediately when bookings open in October — advance booking is essential; (2) Canal alternatives to main river: quieter Loi Krathong floating experiences can be found on Bangkok's canal network (Khlong Saen Saep, Khlong Bangkok Noi in Thonburi); these locations have fewer crowds than the main Chao Phraya piers and a more intimate neighborhood festival atmosphere; (3) Festival timing variation: Loi Krathong's date changes each year based on the lunar calendar; checking the exact 2024/2025/2026 date in advance is necessary as tourist coverage sometimes uses inaccurate dates; official Bangkok date is announced by the BMA (Bangkok Metropolitan Administration); (4) Candle fire hazard: krathong floating uses real candles (often accompanied by three incense sticks); boats, floating debris, and crowded riverside areas create fire hazard in combination with floating candles; releasing krathong without candles (using LED lights, which many vendors now sell) reduces fire risk while maintaining the visual effect; (5) Photography from Saphan Taksin bridge: the Taksin Bridge (Saphan Taksin, adjacent to the BTS station) provides an elevated vantage point over the Chao Phraya for photographing the krathong density on Loi Krathong night; arriving 1–2 hours before sunset secures position on the bridge viewing area before crowds arrive.",
  },
  {
    name: "Makha Bucha, Visakha Bucha & Buddhist Holidays in Bangkok",
    emoji: "🕯️",
    area: "Major Thai Buddhist holidays: Makha Bucha (full moon, February/March — Buddhist Lent beginning); Visakha Bucha (full moon, May — most sacred Buddhist day, commemorating Buddha's birth, enlightenment, and death); Asanha Bucha (full moon, July); Khao Phansa (Buddhist Lent/Vassa beginning, one day after Asanha Bucha); Ok Phansa (Buddhist Lent end, full moon, October); candlelight procession locations: Wat Phra Kaew and Grand Palace perimeter, Wat Pho, Wat Benchamabophit (Marble Temple), Wat Indrawihan; nationwide alcohol prohibition: all three major Buddhist holy days (Makha, Visakha, Asanha Bucha) + Wan Phra (weekly Buddhist sabbath days)",
    price: "Temple candlelight walk-around (Wien Tian): free participation at all major temples; Candle set for Wien Tian (at temple gate): ฿20–50; Temple merit-making donation: any amount; Buddhist holiday flowers and incense for offering: ฿20–80; Alcohol prohibition note: all licensed alcohol sales and venues are prohibited (no restaurants, bars, clubs, convenience stores can sell); Orchid and flower offerings at temple: ฿20–100",
    why: "Bangkok's Buddhist holiday calendar creates unique cultural experiences not available on ordinary days: (1) Wien Tian (candlelight circumambulation): on major Buddhist holidays (especially Makha Bucha and Visakha Bucha), Bangkok's major temples host Wien Tian — the practice of walking three times clockwise around the main temple building holding candles, lotus flowers, and incense; these processions (typically beginning at 7–8pm and lasting 1–1.5 hours) create an extraordinary atmosphere of thousands of participants slowly circling illuminated temple buildings; (2) Visakha Bucha significance: Visakha Bucha is Thai Buddhism's most sacred holiday; it commemorates the three major events of Siddhartha Gautama's life (birth, enlightenment, and parinibbana/death) all occurring on the same lunar date; the nation-wide observance means Visakha Bucha has the most elaborate Wien Tian processions and greatest temple attendance; (3) Alcohol prohibition reality: Thailand's alcohol prohibition on major Buddhist holidays is rigorously enforced; police check licensed premises; convenience stores pull alcohol from shelves; hotels cannot serve alcohol to guests (even in room service); bars and clubs are closed; the alcohol prohibition is often overlooked in travel advice but significantly affects plans involving restaurant dining with wine or evening bar culture; (4) National public holiday impact: Buddhist holidays are national public holidays in Thailand; government offices, many businesses, and schools close; tourist attractions generally remain open; BTS and MRT operate with modified schedules (often reduced frequency); (5) Royal family participation: Thai royal family members participate in major Buddhist holiday ceremonies, particularly at Wat Phra Kaew and Wat Ratchabophit; on these days, the Grand Palace area may have additional security and crowd management for royal ceremony times.",
    tip: "Thai Buddhist holiday visitor guidance: (1) Plan ahead for alcohol prohibition: if visiting Bangkok on a major Buddhist holiday, plan dining and evening activities that do not require alcohol; hotel in-room minibars are also typically emptied or sealed; alcohol purchased the previous day can be consumed privately in accommodation; (2) Wien Tian participation as visitor: visitors may participate in Wien Tian at Bangkok temples; buy the candle/lotus/incense set at the temple gate (staff will indicate where); walk in the same direction as other participants (clockwise); dress modestly (shoulders and knees covered); walking the circumambulation genuinely and respectfully (not treating it as a photo opportunity) is more welcome; (3) Afternoon vs. evening temple timing: Buddhist holiday afternoons (3–5pm) have the most intensive temple activity as monks chant and laypeople make offerings; the Wien Tian begins at dusk; arriving at 4:30pm provides time to observe the afternoon ceremony before the evening procession; (4) Wan Phra (weekly Buddhist holy days): beyond the major annual holidays, Thailand observes Wan Phra (Buddhist sabbath) approximately every week based on lunar calendar; alcohol is prohibited on these days as well; Bangkok convenience stores display signs indicating upcoming Wan Phra dates; (5) Photography during Wien Tian: candlelight procession photography requires slow shutter speed; using the candle flames in the frame creates atmospheric imagery; asking permission before photographing faces (many participants are in deep meditative state during Wien Tian) is appropriate.",
  },
  {
    name: "Bangkok's International & Modern Festivals — Wonderfruit, Design Week & Pride",
    emoji: "🌈",
    summary: "Beyond traditional Thai festivals, Bangkok hosts a growing calendar of contemporary cultural events: (1) Bangkok Pride (June): the Bangkok LGBTQ+ Pride parade and celebrations (typically June) have grown significantly since Thailand passed the Marriage Equality Act in 2025; the Bangkok Pride event now draws international attention and participation; the parade route (varying by year, typically Silom area and central Bangkok) is accompanied by parties at Silom Soi 2/4 venues and international performer concerts; (2) Bangkok Design Week (January, Charoen Krung): the annual Bangkok Design Week (BKKDW, typically late January) transforms the Charoen Krung heritage district into an open exhibition of Thai and international design; installations occupy historic buildings, warehouses, and streets; the event showcases architecture, product design, fashion, typography, and culinary design from Bangkok's creative community; (3) Bangkok International Film Festival (October–November): BIFF screens international and Thai independent cinema at multiple Bangkok venues; the festival provides access to art house, documentary, and international films not commercially released in Thailand; (4) River City Bangkok Art & Antique Fair (monthly auctions): River City Bangkok (riverside mall, Charoen Krung/Yannawa area) hosts monthly antique auctions and art fairs alongside its permanent antique galleries; the quarterly major auction events attract serious Thai and international art/antique collectors; (5) Thailand International Motor Expo (November–December): held annually at IMPACT Arena (northern Bangkok), the Motor Expo is the largest automotive event in Southeast Asia; the event attracts 1.5 million visitors and serves as the launch platform for new car models entering the Thai market; the Motor Expo represents Bangkok's status as Southeast Asia's most important automotive market.",
    tip: "Bangkok contemporary festival guidance: (1) Wonderfruit (Pattaya, December) and its Bangkok connection: while Wonderfruit (the sustainable arts and music festival) is held at a venue near Pattaya (2.5 hours from Bangkok), the festival's transportation options (organized buses from Bangkok) and accommodation packages make it accessible as a Bangkok-based extension; Wonderfruit is one of Asia's most influential sustainability-focused arts events; (2) LGBTQ+ calendar variance: Bangkok Pride timing and format varies year to year based on organizer planning; checking the Bangkok Pride community social media (Bangkok Pride Facebook, Bangkok Rainbow) for the current year's dates and events is essential; (3) Bangkok Art Biennale (October–February, biennial): the Bangkok Art Biennale (BAB) takes place every two years; the biennale uses Bangkok's temples, public spaces, historic buildings, and commercial spaces as exhibition venues; contemporary international art installations in Bangkok's most iconic locations create an extraordinary intersection of heritage and contemporary culture; (4) Thai festival photography ethics: major Thai festivals (Loi Krathong, Vienna Tian, Songkran) are heavily photographed; being conscious of not blocking participants for photography and not invading personal religious moments with cameras maintains respectful visitor status; (5) Festival visa consideration: for visitors timing trips around major Bangkok festivals, accommodation prices increase 2–4x for Songkran (April) and Loi Krathong (November); booking accommodation 3–6 months in advance for these dates prevents both sold-out situations and peak pricing.",
    area: "Bangkok international festivals: Bangkok Design Week (January, Charoen Krung); Bangkok Pride (June, Silom area); Bangkok International Film Festival (October–November, various Bangkok cinema venues); River City Antique Fair (monthly, Charoen Krung); Thailand International Motor Expo (November–December, IMPACT Arena Nonthaburi); Bangkok Art Biennale (October–February, biennial, multiple Bangkok locations); Wonderfruit (December, Chon Buri near Pattaya); Art Bangkok (May, various); Bangkok Jazz Festival (free events, Lumpini Park, periodic); TEDxBangkok (periodic)",
    price: "Bangkok Design Week: free to walk around, some venues charge entry ฿100–300; Bangkok Pride: free parade, party events ฿300–1,500 entry; Bangkok Art Biennale: most venues free; River City auction and fair: free entry to browse, participation in auction requires registration; Motor Expo entry: ฿50 daytime; jazz and free concerts: free; Wonderfruit ticket: ฿5,000–15,000 depending on package",
    why: "Bangkok's contemporary cultural calendar complements the traditional festival calendar with internationally relevant events: (1) BKKDW as design tourism: the Bangkok Design Week has established Bangkok's Charoen Krung district as a design destination; the 1900s-era heritage buildings, Chinese merchant shophouses, and riverside warehouses of Charoen Krung have been progressively adapted into galleries, creative offices, and restaurants; BKKDW amplifies this transformation annually; (2) Pride's political context: Bangkok Pride's growth is intertwined with Thailand's progressive marriage equality legislation (effective 2025); the parade represents a rare case of Southeast Asian LGBTQ+ rights advancement and has attracted both celebration and international media attention; Bangkok's LGBTQ+ community has a long history of visibility despite previous lack of legal recognition; (3) Art Biennale's temple installations: the Bangkok Art Biennale's practice of placing international contemporary art installations within active Buddhist temples (Wat Pho, Wat Arun, Wat Yannawa) creates a dialogue between Buddhist sacred art tradition and contemporary global art that is unique to Bangkok; (4) River City antiques' international market: River City Bangkok's antique market attracts regional buyers from Japan, Taiwan, Korea, and the US for Thai and Southeast Asian art, ceramics, textiles, and Buddha images; prices reflect international collector market values; (5) Motor Expo's Thai consumer culture: the Motor Expo's 1.5 million visitors (out of Bangkok's 10 million residents) demonstrates Thailand's automotive culture intensity; Thailand is a right-hand drive country that is also the regional manufacturing hub for Japanese car brands (Toyota's largest export production is from Thailand); the Motor Expo embodies Thailand's role in the global automotive industry.",
  },
];

export function BangkokLoiKrathong() {
  return (
    <div className="rounded-2xl border border-yellow-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-yellow-700 mb-3">
        🪔 Bangkok festivals — Loi Krathong, Buddhist holidays & international cultural events
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-yellow-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-yellow-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-yellow-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
