const SPOTS = [
  {
    name: "Bangkok's Artisan Bakery Scene — French, Japanese & Thai Fusion",
    emoji: "🥐",
    area: "Artisan bakery clusters: Ari (BTS Ari station — Bangkok's neighborhood café and bakery hub); Ekkamai–Thonglor (BTS corridor, high-end lifestyle bakeries); Charoen Krung creative district (heritage-building bakeries); Silom Japanese bakery row; Asoke area Japanese bakeries serving office worker breakfast demand",
    price: "Croissant (artisan): ฿60–150; Japanese shokupan (white bread, per loaf): ฿150–350; Sourdough (750g): ฿150–280; Pain au chocolat: ฿70–160; Tart (fruit/custard): ฿90–200; Thai-flavor bakery item (pandan, butterfly pea, coconut): ฿60–150; Bread-making class (half day): ฿1,800–4,500",
    why: "Bangkok's bakery scene has undergone a dramatic quality transformation — the combination of Japanese bakery technique, French pastry tradition, and Thai ingredient creativity has produced Bangkok artisan bakeries that rank among Asia's best. Key drivers: (1) Japanese shokupan culture: Japan's premium white bread (shokupan) revolution has arrived fully in Bangkok; multiple Bangkok bakeries specialize in the pillowy, milk-enriched Japanese loaf with precise crumb structure; the Japanese-Thai bakery influence runs deep in Bangkok through both Japanese-operated and Thai-owner bakeries using Japanese technique; (2) Croissant excellence: Bangkok has developed serious croissant culture; the best Bangkok croissants (at bakeries in Ari, Ekkamai, and specific Charoen Krung spots) produce the caramelized exterior and layered honeycomb interior that defines a properly laminated croissant; (3) Sourdough movement: Bangkok's specialty coffee culture has been accompanied by a parallel artisan bread movement; long-fermentation sourdough from small-batch bakers has created a Bangkok sourdough community with serious hobbyist home bakers and professionals; (4) Thai-ingredient bakery creativity: the most distinctly Bangkok contribution to global bakery culture is the fusion of French/Japanese technique with Thai ingredients: pandan sourdough, butterfly pea croissants, coconut custard tarts, pineapple cream buns, lemongrass financiers; (5) Bread subscription culture: Bangkok's artisan bakers have pioneered bread subscription models (pre-order Thursday, pick up Saturday) that mirror the Japanese artisan bakery model and have created stable revenue for quality-focused small bakers.",
    tip: "Bangkok bakery navigation: (1) Best bakery timing: artisan bakeries in Bangkok sell out fast; arriving early (opening hour: typically 8–10am) guarantees access to whole loaf items and specialty pastries; afternoon visits find reduced selection; (2) Ari neighborhood bakery crawl: the Ari BTS area (Phahon Yothin Road and adjacent sois) concentrates Bangkok's most café-integrated bakeries; walking from BTS Ari covers 6–10 bakeries and cafés within 500 meters; (3) Japanese bakery district near Asoke: Sukhumvit Soi 21 (Asoke) and the streets around Sukhumvit Soi 24–26 have multiple Japanese-operated bakeries serving the Japanese office worker community; these produce authentic Japanese bakery style (melon pan, curry bread, anpan) rather than Western-fusion items; (4) Bangkok baking community: Bangkok has active home baker communities on Facebook and LINE that organize ingredient sharing, sourdough starter exchange, and baking technique workshops; the sourdough home baker community is particularly active post-COVID; (5) Ingredient sourcing: Bangkok's specialty flour (Type 00, bread flour, high-protein flour), quality butter (French Isigny Ste-Mère butter, European butter types), and fresh yeast are available at Makro (professional wholesale), imported food sections of Villa Market and Gourmet Market (Siam Paragon), and online via Lazada/Shopee.",
  },
  {
    name: "Dessert Culture — Thai Sweets, Patisserie & Ice Cream in Bangkok",
    emoji: "🍮",
    area: "Thai sweets (khanom): throughout Bangkok at fresh markets, Chatuchak, and traditional khanom vendors; French patisserie: Siam Paragon food hall, EmQuartier Helix food zone, and standalone patisseries in Thonglor; Thai artisan ice cream: Thonglor neighborhood (Frostbite, Guss Damn Good); Filipino-style halo-halo: Nana/Sukhumvit area Filipino community dessert shops",
    price: "Traditional Thai khanom set (market): ฿30–100; Mango sticky rice (seasonal, peak March–June): ฿80–200; French patisserie (tart, éclair, macaron): ฿120–350; Artisan ice cream single scoop: ฿80–180; Thai ice cream sandwich (ไอติมกะทิ): ฿30–80; Shaved ice with toppings (Thai bing): ฿50–120; Durian desserts: ฿80–500",
    why: "Bangkok's dessert ecosystem is among Southeast Asia's most complex — traditional Thai khanom (sweets) traditions dating to the Ayutthaya period coexist with Japanese patisserie technique and the city's own creative ice cream culture: (1) Thai khanom tradition: traditional Thai sweets are among the world's most technically demanding — khanom chan (layered sticky rice sweets with pandan coloring), khanom krok (coconut rice pudding cups), khanom buang (crispy crepes with coconut cream and egg yolk), and thong yip/foi thong (egg yolk sweets in royal court tradition) represent sophisticated cooking traditions; (2) Mango sticky rice seasonality: the relationship between Bangkok's mango season (Mahachanok mangoes peak in March–June) and the Thai sticky rice tradition produces the world's most beloved tropical dessert at its best in this specific seasonal window; (3) Japanese patisserie influence: Bangkok's Japanese influence on pastry has created technically precise Japanese-Thai fusion desserts — matcha roll cakes, yuzu tarts, hojicha cheesecake — available at standalone patisseries and in department store food halls; (4) Thai artisan ice cream: Thailand's tropical fruit abundance creates natural ice cream flavor inspiration; Bangkok's artisan ice cream shops (using fresh coconut, Thai basil, lychee, jackfruit, durian) push ice cream into distinctly Thai flavor territory; (5) Durian dessert culture: Bangkok's durian dessert culture (durian sticky rice, durian soft serve, durian cream puffs) challenges and rewards in equal measure.",
    tip: "Bangkok dessert exploration: (1) Mango sticky rice timing: the best mango sticky rice is available from street vendors and restaurants when Thai Mahachanok or Nam Dok Mai mangoes are in season (February–June); off-season mango sticky rice uses less flavorful imported or greenhouse mangoes — noting the season significantly affects the experience; (2) Traditional khanom finding: traditional Thai sweets are most authentically found at fresh morning markets (talat sot) and at vendor carts near temples, not at tourist-facing dessert shops; the morning market in residential Bangkok (not tourist areas) stocks daily fresh khanom made by neighborhood khanom producers; (3) Durian approach: Bangkok's durian street stalls (particularly in Yaowarat and Pak Klong Talat) sell durian by weight with on-the-spot opening; the complex fragrant smell of fresh durian (objectionable to many on first encounter, addictive to converts) is part of the experience; (4) Coconut ice cream at Chatuchak: the roasted coconut shell-served Thai coconut ice cream at Chatuchak Market represents the most photogenic and authentic version of Thailand's traditional coconut ice cream; (5) Tub Tim Krob: a classic Thai dessert of water chestnuts coated in red-dyed tapioca flour served in coconut milk with shaved ice — one of Thailand's most texturally interesting and visually distinctive desserts, available at traditional Thai dessert shops throughout Bangkok.",
  },
  {
    name: "Bangkok's Bread Culture — Bakery-Hopping & Thai Breads",
    emoji: "🍞",
    area: "Bangkok bread traditions: Chinese-influenced bakeries (khanom pang) in Chinatown (Yaowarat) and wholesale bread market in Banglamphu; Thai coconut cream bread (khanom pang sangkaya) as street food; steamed buns (sala pao) from Chinese bakeries and dim sum shops; Western artisan bread at specialty cafés throughout Bangkok",
    price: "Thai coconut cream bread (2 pieces): ฿30–60; Chinese steamed bun (sala pao): ฿15–50; Chinese bakery sweet bread: ฿25–60; Artisan sourdough loaf: ฿150–280; Japanese white bread loaf: ฿150–350; Multigrain or seeded loaf: ฿200–400",
    why: "Bangkok's bread culture spans multiple traditions that coexist distinctly: (1) Thai street bread (khanom pang): Thai street vendors sell white bread rounds and long loaves with distinctive Thai preparations — sweetened condensed milk spread, kaya (coconut jam), pandan butter, or simply served with fried eggs and nam jim (dipping sauce); the Thai-Chinese bread tradition (enriched soft white bread similar to East Asian white bread) dominates Bangkok's everyday bread consumption; (2) Chinese bakery tradition: Bangkok's Chinese-influenced bakeries (particularly in Yaowarat and Banglamphu) produce sweet buns, pork floss bread, red bean buns, and egg tarts in the Hong Kong-Chinese bakery tradition; (3) Sala pao (Chinese steamed buns): Bangkok's Chinese bakeries and dim sum restaurants produce steamed buns (pork, red bean, vegetable fillings) that represent one of Bangkok's most accessible everyday snacks; (4) Artisan Western bread: the Bangkok artisan bakery community produces sourdough, baguettes, ciabatta, and focaccia for the international community and Thai food enthusiasts who have developed Western bread taste; (5) Khanom pang sangkaya: coconut cream-filled bread rolls are one of Bangkok's most beloved sweet snacks; the combination of soft white bread with pandan-scented coconut cream is a distinctly Thai preparation.",
    tip: "Bangkok bread culture navigation: (1) Khanom pang cart recognition: look for wheeled carts with white compartmentalized bread trays — these are Bangkok's traditional bread vendors offering the classic Thai bread experience with various spreads; typically found near BTS stations, markets, and university areas in early morning; (2) Chinatown bakery concentration: Yaowarat's Chinese bakeries concentrate near the Yaowarat Road main street and in the lanes running north from it; early morning (7–10am) is when fresh products are available; (3) Sala pao steaming: fresh steamed sala pao from Chinese dim sum shops should be consumed within 20 minutes of steaming for best texture; reheated pao lose the characteristic soft-wet interior; (4) Artisan bread subscription: Bangkok's best artisan bread bakeries offer subscription models (pre-order, weekly pickup); for Bangkok residents who want regular access to quality sourdough, bread subscriptions at consistent quality are the most reliable route; (5) Bread varieties at Bangkok bakeries: the variety of bread types at Bangkok's artisan bakeries often includes styles not commonly seen elsewhere — turmeric bread with Thai spicing, butterfly pea flower-colored rolls, pandan-matcha swirl loaves that emerge from Thailand's ingredient-forward creative bakery culture.",
  },
];

export function BangkokBaking() {
  return (
    <div className="rounded-2xl border border-amber-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-amber-700 mb-3">
        🥐 Bangkok bakeries & desserts — French-Japanese artisan breads, Thai khanom & ice cream
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-amber-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-amber-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
