const SPOTS = [
  {
    name: "Bangkok's Key Thai Ingredients — Where to Buy & How to Identify Galangal, Kaffir Lime & More",
    emoji: "🌿",
    area: "Bangkok ingredient markets: Or Tor Kor Market (Chatuchak area, BTS Mo Chit — Bangkok's highest-quality fresh produce market; premium ingredients at slightly higher prices; clean, organized, English-friendly); Khlong Toei Market (Bangkok's largest wet market, lower prices, authentic chaos, dawn to 10am); Pak Klong Talat (flower and vegetable wholesale, Charoen Krung near Memorial Bridge, midnight to 4am for flower trading but vegetable section open daytime); Yaowarat (Chinatown — dried ingredients, preserved goods, Chinese herbs blending into Thai cooking supplies); Siam Paragon Gourmet Market (supermarket, premium ingredients, reliable quality, tourist-friendly); Tops Supermarket (reliable imported and domestic ingredients); Villa Market (Sukhumvit-area expat-oriented supermarket with international ingredients); Big C and Tesco Lotus (large hypermarkets, good domestic ingredient selection at budget prices)",
    price: "Bangkok fresh ingredient pricing (market rates): galangal (kha): ฿20–40 per 200g; kaffir lime leaves (bai makrut): ฿10–20 for 20–30 leaves; lemongrass stalks (ta-khrai): ฿15–30 for bundle of 10; Thai basil (horapa): ฿10–15 per bundle; holy basil (krapao): ฿10–15 per bundle; bird's eye chili (prik kee nu): ฿20–40 per 100g; fingerroot (krachai): ฿30–50 per 100g; fresh turmeric (kha min): ฿20–30 per 100g; shrimp paste (kapi): ฿40–80 per 100g; palm sugar (nam tan pip): ฿30–60 per block; dried shrimp (kung haeng): ฿80–150 per 100g; tamarind paste (makham piak): ฿30–50 per 100g; fish sauce (nam pla): ฿25–60 per bottle",
    why: "Understanding Thai cooking ingredients requires distinguishing between ingredients that look similar to Western equivalents but are entirely different: (1) Galangal vs. ginger: galangal (kha, ข่า) is the root used in Thai soups (tom kha, tom yum) and curry pastes; it is NOT interchangeable with ginger despite visual similarity; galangal has a sharp, piney, medicinal quality while ginger is warm and sweet; galangal is harder and fibrous — not typically eaten directly (steeped or used as an aromatic); krachai (fingerroot, Chinese ginger) is a third related root with different flavor profile; (2) Thai basil varieties: Thai cooking uses THREE distinct basil varieties, not interchangeable: horapa (Thai basil, anise-like, used in red and green curry, stir-fries) — the most commonly exported Thai basil; krapao (holy basil, stronger, slightly spicy, use in pad krapao; crucial difference in flavor — the dish is named for this specific basil); maenglak (lemon basil, citrusy, lighter, used in some soups and salads); Western 'Thai basil' in international markets is typically horapa but is sometimes confused with Italian basil; pad krapao made with the wrong basil is fundamentally different; (3) Fresh vs. dried/powdered kaffir lime: kaffir lime leaves (bai makrut, ใบมะกรูด) are used fresh in Thai cooking; the double-lobed leaf structure is distinctive; the leaves release volatile oils when torn (not cut) for maximum flavor; the rind of kaffir lime fruit is used in curry pastes; do not substitute with kaffir lime powder — the fresh leaf's volatile compounds are not preserved in dried form; (4) Palm sugar vs. other sugars: palm sugar (nam tan pip, น้ำตาลปี๊บ) is traditional in Thai cooking for its distinctive caramel-like, lightly smoky sweetness; it differs from white sugar, brown sugar, coconut sugar, and cane sugar in flavor; Thai recipes often specify palm sugar precisely because the flavor contribution is distinctive; coconut sugar (increasingly available internationally) is an acceptable substitute in some applications; (5) Fish sauce quality tiers: nam pla (fish sauce) ranges dramatically in quality; indicators of quality: color (amber to light brown, not dark black), transparency (can see through it), first press vs. later extraction (similar to olive oil press quality); Tiparos and Megachef are reliable Thai brands; Tra Chang ('Scale brand') is the artisanal high-end Thai fish sauce; the depth of flavor and saltiness varies between brands — recipes calibrated for cheap fish sauce may be oversalted with premium fish sauce.",
    tip: "Bangkok ingredient shopping and identification: (1) Or Tor Kor Market for quality ingredients: the produce at Or Tor Kor (opposite Chatuchak Weekend Market, BTS Mo Chit) is visibly higher quality than standard markets — fresher, better sorted, cleaner; prices are 20–40% higher than Khlong Toei but English communication is easier and quality is consistent; (2) Fresh herb bundles: Thai herb bundles (lemongrass, kaffir lime leaf, galangal — often pre-assembled for tom yum or tom kha soup) are sold at most Bangkok markets as ready-to-use packages; for ฿30–50 you can buy a pre-assembled soup herb bundle with exactly the ingredients needed; (3) Ingredient identification strategy: use Google Lens or Thai-English food reference apps to identify unfamiliar market ingredients; Or Tor Kor staff (more than other markets) can sometimes assist in English or via translation apps; (4) Taking ingredients home: most Thai dried ingredients (dried shrimp, dried chilies, palm sugar, fish sauce in sealed bottles) clear international customs without issues; fresh herbs and roots (galangal, lemongrass) may face plant import restrictions in some countries (Australia is especially strict); dried forms are safer for international travel; (5) Premium ingredient shops: Gourmet Market at Siam Paragon and EmQuartier carry premium Thai ingredients for those who want quality assurance over price optimization; premium shrimp paste, high-quality fish sauce, and fresh herbs available in a supermarket format more comfortable for visitors unfamiliar with wet market navigation.",
  },
  {
    name: "Bangkok's Curry Paste Universe — 12 Regional Thai Curries & Where to Buy Authentic Pastes",
    emoji: "🍛",
    area: "Bangkok curry paste retail: Mae Ploy brand (widely available at all Bangkok supermarkets — Tops, Villa, Big C, Foodland; most commonly exported Thai curry paste brand globally; paste quality is reliable but standardized); Mae Sri (premium Thai curry paste brand, available at Gourmet Market Siam Paragon and Or Tor Kor); fresh-ground curry paste: Or Tor Kor Market vendors grind curry paste to order (watch them grind in stone mortar — superior to pre-packaged); Khlong Toei Market also has fresh-ground paste vendors; fresh paste at Chatuchak Weekend Market (food section); cooking school pastes: most Bangkok cooking schools (Silom Thai Cooking School, Blue Elephant Cooking School) sell their own curry paste after class",
    price: "Bangkok curry paste pricing: Mae Ploy sachets (commercial grade): ฿25–50 per 100g sachet; Mae Ploy tubs (larger catering): ฿100–200 for 400g; premium paste (Mae Sri, organic): ฿60–120 per 100g; fresh-ground market paste: ฿40–80 per 100g (Or Tor Kor); Blue Elephant ready-to-use paste (premium export brand): ฿100–180 per bottle; cooking class recipe paste (homemade): sometimes sold at ฿60–100 per pack; fresh coconut milk from market: ฿15–25 per fresh young coconut, pressed coconut milk ฿30–50 per 250ml; Chaokoh or Aroy-D canned coconut milk: ฿25–45 per 400ml can",
    why: "Thailand's regional curry traditions are more diverse and distinct than most international visitors realize from restaurant exposure to just green, red, and yellow curry: (1) Bangkok's accessible curry types: the most commonly served Thai curries in Bangkok and most internationally — green curry (kaeng khiao wan): coconut milk base, fresh green chilies, kaffir lime, lemongrass, slender green eggplants, sweet basil; red curry (kaeng daeng): dried red chilies, roasted shrimp paste, lemongrass; massaman curry: Muslim-influenced, dried Persian spices (cinnamon, cardamom, star anise), peanuts, less heat than green; panang curry: dry, rich coconut cream base, thicker than green or red; yellow curry (kaeng kari): turmeric-forward, Indian-influenced, mild; (2) Regional Thai curries less commonly seen in Bangkok's tourist-facing restaurants: kaeng som (Thai sour curry — no coconut milk, sour from tamarind or turmeric leaf, thin broth, popular in southern Thailand); kaeng pa (jungle curry — no coconut milk, very spicy, wild vegetables, northern Thailand character); kaeng khanun (jackfruit curry, northern Thailand); kaeng phet (just means spicy curry, the base descriptor for many types); kaeng liang (vegetable and shrimp paste curry, very mild, central Thailand); (3) Paste composition differences: Thai curry pastes use aromatic rhizomes (galangal, lemongrass, krachai) and dried or fresh chilies as base; key paste elements: shrimp paste (kapi) — the umami backbone of most Thai curries; toasted coriander seed — background layer; fresh vs. dried chili ratio determines fresh vs. dried character; roasted vs. fresh shallot and garlic affect flavor depth; (4) Fresh vs. canned coconut milk: Thai curries cooked with fresh-pressed coconut milk (from grated fresh coconut) have dramatically different texture and flavor than curries made with canned coconut milk; the fat-water emulsion in fresh coconut milk behaves differently when heated — the cream separates for frying, which is the technique of cracking coconut cream to fry curry paste (done with Chaokoh or similar canned full-fat coconut cream too, but with better fat content); using lite coconut milk prevents proper emulsion behavior; (5) Southern vs. northern vs. central Thai curry styles: Southern Thai curries: often coconut milk-free (or minimal), extremely spicy, dried spice-influenced, yellow from turmeric; northern Thai curries (khao soi, the only coconut-based northern curry — plus non-coconut variants): more Chinese and Burmese flavor influence; central Thai curries: the international standard Thai curry style, balanced heat and sweetness, coconut milk-based.",
    tip: "Bangkok curry paste shopping: (1) For cooking at home internationally: Mae Ploy is the most available Thai curry paste brand internationally and the standard Bangkok cooking school reference; buy the 400g tubs at Bangkok Big C (cheapest price) to take home; most Thai curry pastes survive international customs as sealed packaged food products; (2) For quality evaluation in Bangkok: compare side-by-side from: (a) commercial Mae Ploy packet (baseline), (b) Or Tor Kor fresh-ground paste, (c) cooking class demonstration paste; the fresh-ground paste has noticeably brighter, more complex aroma because the aromatic volatile compounds have not oxidized; (3) Thai supermarket coconut section: Chaokoh full-fat coconut cream (the bright red label, thicker, higher fat) is the correct product for Thai curry; coconut milk (lighter blue label) is lower fat and used for dishes where separation is not desired; lite coconut milk is not appropriate for authentic Thai curry technique; (4) Regional curry exploration in Bangkok: Bangkok's regional Thai restaurant scene allows tasting curries rarely seen in international markets — Krua Apsorn (Samsen Road area) for central Thai kaeng liang and traditional dishes; Baan Phadthai (Charoen Krung) for a range of traditional preparations; (5) Massaman curry for beginners: Massaman (Muslim-influenced, gentle spices, very mild heat) is the most internationally approachable Thai curry and the most forgiving for home cooking; store-bought Massaman paste from Mae Ploy requires only chicken or beef, potato, peanuts, and coconut milk to produce an authentic result.",
  },
  {
    name: "Bangkok's Street Food Condiment Table — Nam Prik Pao, Sauces, Pickles & the Four-Condiment Set",
    emoji: "🫙",
    area: "Bangkok condiment culture is omnipresent: the four-condiment table set (khrueang prung, เครื่องปรุง) appears at virtually every Bangkok street food restaurant; the condiment bottles and jars vary by cuisine — noodle shops, rice-and-curry shops, and som tum stalls each have their specific condiment configuration; specialty condiments: Yaowarat (Chinese-style sauces, fermented bean products, oyster sauce varieties); Or Tor Kor Market (premium nam prik pastes, artisanal condiments); Villa Market and Tops Supermarket (broader selection for home cooking, international sauces); Chatuchak Weekend Market (specialty condiments, regional Thai products, packaged artisanal nam prik)",
    price: "Bangkok condiment pricing (retail/market): Sriracha (Si Racha — the original Thai version): ฿35–60 per bottle (note: American-style Huy Fong Sriracha is a US product, not Thai Sriracha; authentic Thai Sriracha is less acidic); nam prik pao (roasted chili paste in oil): ฿40–80 per jar (Maepranom or Pantainorasingh brands); fish sauce (Tiparos standard, 700ml): ฿35–55; oyster sauce (Maekrua or Healthy Boy): ฿45–80 per bottle; sweet chili sauce (nam jim kai, Maeploy): ฿40–70 per bottle; fermented rice (khao mark): market specialty, ฿15–30 per portion; soy sauce (Thai varieties — thin, dark, sweet, seasoning): ฿30–50 each; prik nam pla (fish sauce with fresh chilies): ubiquitous free condiment at Thai restaurants",
    why: "Thai condiment culture is one of the most nuanced aspects of Thai food — the four-condiment table set fundamentally changes how Thai food is consumed compared to Western restaurant conventions: (1) The four-condiment set (khrueang prung): every Thai noodle shop and many rice-and-curry shops place a tray with four condiments on the table; standard configuration: (a) prik nam pla — fresh Thai chilies floating in fish sauce (add for salt + heat); (b) prik nam som — chilies in rice vinegar (add for sour + heat); (c) prik pon — dried chili flakes (add for heat); (d) nam tan — white sugar (add for sweetness); the customer completes the dish to personal preference — Thai restaurant food is meant as a starting point, not a finished presentation; this is why Thais always adjust their food at the table; (2) Nam prik — Thailand's paste condiment tradition: nam prik (น้ำพริก) is a broader category of chili-based condiment pastes used as dips for vegetables and accompaniments to rice; hundreds of regional nam prik varieties exist; most common: nam prik kapi (fermented shrimp paste chili dip), nam prik pao (roasted chili paste, also used in cooking), nam prik num (northern Thailand roasted green chili dip), nam prik ong (northern Thai ground pork and tomato dip); nam prik culture is central to Thai home cooking and regional identity; (3) Prik nam pla — the universal Thai table sauce: fish sauce with fresh sliced bird's eye chilies (prik kee nu) is the most used Thai table condiment; found at virtually every Thai restaurant table; the ratio of chilies to fish sauce and the type of chilies used varies by restaurant and customer preference; adding prik nam pla to a Thai dish adds salt + umami + heat simultaneously; (4) Soy sauce ecosystem: Thai cuisine uses multiple soy sauce types: si yu kao (thin soy sauce) — light color, salty, for stir-fries; si yu dam (dark soy sauce) — thick, slightly sweet, for color and caramel flavor; si yu wan (sweet soy sauce) — very thick, sweet, for noodle dishes; seasoning sauce (Maggi and Golden Mountain brands — umami-forward, often used in Thai-Chinese cooking and some stir-fries); these are not interchangeable and Thai recipes typically specify which type; (5) Nam jim dipping sauces: beyond table condiments, Thai food uses specific nam jim (dipping sauce) preparations for different foods: nam jim seafood (fresh chilies, garlic, lime, fish sauce, sugar — for grilled fish and seafood); nam jim kai (sweet chili sauce — for chicken satay and spring rolls); peanut sauce (for satay); nam jim kratiam (garlic-pepper in vinegar — for Chinese-style Bangkok food).",
    tip: "Bangkok condiment culture navigation: (1) Mastering the four-condiment table: when eating Thai noodles (pad see ew, pad Thai, boat noodles, kuay tiao varieties) taste first before adding condiments; adjust with: a small pinch of sugar if too bland or tart, few drops of prik nam pla if too sweet, few drops of prik nam som if too oily; this sequential tasting-and-adjusting is how Thais eat; (2) Nam prik shopping: the Maepranom brand produces some of Bangkok's most consistent commercial nam prik products; for artisanal regional nam prik, Or Tor Kor Market has vendors selling northern and southern Thai varieties vacuum-packed for travel; (3) Sriracha truth: the green-cap Huy Fong Sriracha familiar in the USA is an American product created by a Vietnamese-American in California; authentic Thai Sriracha (from the Si Racha district in Chonburi province) is different — less sour, more rounded; buying authentic Thai Sriracha in Bangkok (Shark and Sriraja Panich brands) provides the genuine reference; (4) Sweet soy sauce for home cooking: Kwong Hung Seng (ABC brand) sweet soy sauce (the thick, almost molasses-like syrup) is essential for authentic pad see ew noodle texture — one of the few ingredients not easily substituted; buy at Chinatown (Yaowarat) or specialty Asian grocery; (5) Condiment tastings: several Bangkok cooking schools (Silom Thai Cooking School, Asia Scenic Thai Cooking School) include condiment and paste identification as part of their market tour component; this provides guided context for understanding what you're seeing and buying at the market before the cooking class.",
  },
];

export function BangkokIngredient() {
  return (
    <div className="rounded-2xl border border-lime-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-lime-700 mb-3">
        🌿 Bangkok cooking deep-dive — Thai ingredients identification, regional curry pastes & condiment culture
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-lime-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-lime-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-lime-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
