const TOPICS = [
  {
    title: "Thai Traditional Medicine (TTM) — Herbal Remedies, Massage Theory & Wat Pho School",
    emoji: "🌿",
    summary: "Thai Traditional Medicine (TTM) is a complete medical system distinct from both Western biomedicine and Chinese Traditional Medicine, with Bangkok's Wat Pho as its most accessible entry point: (1) TTM's theoretical foundation: Thai Traditional Medicine is built on the concept of four elements (earth, water, wind, fire) and 10 sen (energy pathways similar to Chinese meridians but with distinct mapping); health represents balance between these elements; disease represents imbalance; treatment combines herbal medicine, therapeutic massage, dietary therapy, and spiritual practice; (2) Wat Pho Traditional Medicine School: Wat Pho temple (Temple of the Reclining Buddha, Rattanakosin Island) is the recognized center of Thai Traditional Medicine preservation; the temple's walls contain stone tablets with TTM medical texts carved in the 1830s (commissioned by Rama III); the Wat Pho massage school provides accredited massage therapy training; (3) Pharmacopoeia and herbal tradition: Thailand's official TTM herbal pharmacopoeia includes hundreds of plants; notable Thai medicinal herbs: krachai dam (black ginger, considered performance-enhancing), fingerroot, andrographis (fah talai jone, used for respiratory and fever management), morinda citrifolia (noni fruit), mangosteen rind (antioxidant research), and the iconic Thai herbal compress ball (luk pra kob) containing turmeric, ginger, lemongrass, and kaffir lime; (4) Thai herbal compress therapy: the luk pra kob (herb compress) is heated and applied to muscles and joints; it combines heat therapy with aromatic herbal compounds that penetrate the skin; the treatment addresses muscle pain, tension, and circulation; the distinctive aroma of a luk pra kob treatment (lemongrass, camphor, turmeric) is a recognizable Thai spa sensory marker; (5) TTM vs. modern Thai healthcare: modern Thai hospitals use Western biomedical protocols; TTM is practiced at government hospitals as complementary medicine (Ministry of Public Health recognizes TTM practitioners); the integration of TTM in Bangkok's hospital system includes specific TTM outpatient departments at government hospitals and TTM-certified practitioners.",
    action: "Wat Pho Thai Traditional Massage School (watpomassage.com) for massage courses (registration, curriculum, certification); Institute of Thai Traditional Medicine (ITTM) at Siriraj Hospital for academic TTM; Abhaibhubejhr Hospital (Prachinburi Province, 2 hours from Bangkok) for the most comprehensive TTM herb production and clinical center; Bangkok TTM herbal products: most health shops near Wat Pho, Or Tor Kor Market pharmacy sections; traditional herbal compresses as Bangkok souvenir: available at Chatuchak and most tourist shops.",
  },
  {
    title: "Bangkok Spa & Wellness Circuit — Thai Massage, Luxury Spas & Detox Programs",
    emoji: "💆",
    summary: "Bangkok's wellness industry spans from street-level ฿150 foot massage to ฿20,000 luxury multi-day retreat: (1) Street massage shops: Bangkok's most accessible massage experience is the ubiquitous massage shops (typically ฿150–300/hour for Thai massage or ฿250–400 for oil massage) found throughout tourist areas; quality varies significantly; reputable street massage shops have visible certification from the Wat Pho or Health Land schools, visible practice registration, and professional linens; (2) Health Land Spa: Health Land is Bangkok's most respected chain spa (4 Bangkok locations: Asok, Sathorn, Ekkamai, On Nut); known for consistent quality, trained therapists, clean facilities, and reasonable pricing; the Thai massage at Health Land (฿550/2 hours) is considered the benchmark for mid-range Bangkok massage; (3) Luxury hotel spas: Bangkok's luxury hotel spas (Mandarin Oriental Spa, Four Seasons Chao Phraya Spa, The Peninsula Spa, Banyan Tree Spa) provide 5-star wellness experiences in exceptional settings; treatments range ฿3,000–12,000+; the Mandarin Oriental Spa (oldest, most prestigious) has a dedicated spa building on the river side; (4) Wellness retreats near Bangkok: Kanchanaburi Province, Samut Prakan, and the Bang Na area have dedicated wellness retreat centers offering multi-day detox programs; programs may include juice fasting, colonic irrigation, yoga, meditation, and TTM treatments; international health tourists increasingly visit Bangkok for wellness retreat programs; (5) Foot reflexology culture: Thai foot reflexology (nuat tao in Thai, reflecting the mapped reflex zones of the foot corresponding to body systems) is a specific practice distinct from regular foot massage; the practitioner uses a wooden stick and thumb pressure to work specific reflexology points; foot reflexology shops are concentrated in tourist areas; ฿250–400/hour is the typical Bangkok price.",
    action: "Health Land Spa (healthlandspa.com) for consistent quality mid-range Bangkok spa (Asok, Sathorn, Ekkamai, On Nut locations); At Ease Massage near BTS Asok for reliable tourist-area quality; RarinJinda Wellness Spa (Chiang Mai flagship, Bangkok location) for premium certified Thai spa; Thann Sanctuary (Siam Center) for luxury aromatherapy; Bangkok detox retreat: check Absolute Sanctuary (Ko Samui-based, closest Bangkok program) or Kamalaya Ko Samui; Shopee/Lazada Thai wellness product purchase for home use of Thai herbal products.",
  },
  {
    title: "Bangkok Beauty Clinics & Medical Aesthetics — Skin Whitening, Botox & Thailand's Beauty Culture",
    emoji: "✨",
    summary: "Bangkok's aesthetic medicine and beauty treatment industry is one of Asia's largest and most accessible: (1) Thailand's beauty culture context: Thai beauty standards historically value pale skin (glao/khiao in Thai, literally 'white-yellow') as a marker of social status (outdoor laborers tanned; indoor educated/wealthy stayed pale); this cultural value drives a massive cosmetic whitening industry; Thai retail shelves are dominated by whitening skincare products; international brands modifying products for Thai market often add whitening components to match consumer preference; (2) Bangkok skin whitening clinics: Bangkok has thousands of skin whitening/brightening clinics offering glutathione intravenous (IV) drips (controversial, limited clinical evidence), laser brightening treatments, and whitening injection programs; clinics in tourist areas and Bangkok shopping malls (particularly MBK, Siam, and Pratunam area) market aggressively to Thai clients; international visitors should approach medical aesthetics at Bangkok walk-in clinics with significant caution; (3) Botox and filler pricing: Bangkok's medical aesthetics clinics (many JCI-accredited or hospital-affiliated) offer Botox, hyaluronic acid fillers, and thread lifts at 40–70% below US/European pricing; reputable Bangkok aesthetics clinics (such as those affiliated with Bumrungrad, Samitivej, or Bangkok Hospital) provide verifiable credentials and consistent products; pricing: Botox per area ฿3,000–8,000 (vs. US$400–1,000/area); filler per syringe ฿8,000–25,000; (4) Thailand's plastic surgery tourism: beyond the specific clinics mentioned (gender-affirming surgery), Thailand is a general plastic surgery tourism destination; rhinoplasty, blepharoplasty (double eyelid surgery, the most popular procedure in Thailand), breast augmentation, and liposuction are performed at internationally competitive prices; the 'Asian beauty' procedures (double eyelid surgery, nose slimming) are extremely developed in Bangkok due to domestic demand; (5) Medical aesthetics caution: Bangkok's unregulated aesthetic clinic sector includes clinics with unqualified practitioners offering medical procedures; walking in to a high-street clinic for injectable treatments without research is risky; verifying that injectors are medical doctors or licensed nurses, that products are verifiably from registered manufacturers, and that clinics have demonstrated emergency protocols is essential safety due diligence.",
    action: "Bumrungrad International Hospital aesthetic center for highest-standard Bangkok plastic surgery; KTOP Clinic (multiple Bangkok locations, popular with Thai-Korean aesthetic patients) for verifiable Korean-trained aesthetics; Nirunda Laser and Aesthetic Center (established, long-running) for mid-range certified aesthetics; The Key Clinic by Dr. Nonn for face structure contouring; Thailand Medical Tourism Council (tmtc.or.th) for accreditation verification; avoid walk-in MBK/Pratunam clinics for injectable treatments without prior research and credential verification.",
  },
];

export function BangkokTraditionalMedicine() {
  return (
    <div className="rounded-2xl border border-teal-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-teal-700 mb-3">
        🌿 Bangkok wellness — Thai traditional medicine, spa culture & medical aesthetics
      </h2>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-teal-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-teal-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
