const SPOTS = [
  {
    name: "Bangkok's Klong Network — Canal History, Khlong Saen Saep & Thonburi Canals",
    emoji: "🚤",
    area: "Bangkok's canal network: Khlong Saen Saep (main commuter canal, runs east-west through central Bangkok, 18km, Pratunam to Minburi); Thonburi canal network (west bank, traditional stilt houses, Khlong Bangkok Noi, Khlong Bangkok Yai, Khlong Dan); Bang Krachao canals (southeast of Bangkok, 'Green Lung' island, cycling route); Chao Phraya River (main artery, meanders south through Bangkok); Khlong Phadung Krung Kasem (canal surrounding central Rattanakosin island); major canal boat piers: Pratunam (Khlong Saen Saep), Asok, Phaya Thai, Silom; Bangkok ferry piers: Sathorn/Central Pier, Maharaj Pier N9, Wang Lang N10; Khlong Bang Luang (Thonburi, artist village area)",
    price: "Khlong Saen Saep canal boat (Pratunam to Asok): ฿12–25; Khlong Saen Saep full journey (Pratunam to Minburi East terminal): ฿25–35; Chao Phraya Express Boat (within central Bangkok): ฿15–50; Tourist Boat (orange flag, unlimited day): ฿50 flat; Thonburi canal private long-tail boat charter (2 hours): ฿1,500–2,500; Bang Krachao canal cycle + boat crossing: ฿20 (ferry) + ฿80 (bicycle rental); Khlong Bangkok Yai dinner cruise: ฿800–2,000; private canal tour: ฿500–1,500/hour",
    why: "Bangkok was once called the 'Venice of the East' — a canal-city where klongs (canals) were the primary transportation network: (1) Canal city history: Bangkok in the 19th century had over 200km of klongs serving as roads; canal commerce (floating markets, canal-side workshops, fish ponds) was the economic basis of the city; the Rama IV and Rama V modernization era (1850s–1900s) converted many klongs to roads as the city adopted land-based transportation; approximately 50km of canals remain, now used for commuter boats and remnant canal life; (2) Khlong Saen Saep efficiency: the Khlong Saen Saep express boat is one of Bangkok's most efficient public transport options; running parallel to Sukhumvit Road (one of Bangkok's most traffic-congested corridors), canal boats travel the same distance in 25 minutes that may take 45–90 minutes by car during rush hour; the boats are crowded but functional for western Bangkok to Pratunam to eastern area travel; (3) Thonburi canal life preservation: Bangkok's Thonburi district (west bank of Chao Phraya) retains more intact canal-side traditional life than the east bank; Thonburi canal tours (2-hour long-tail boat trips) navigate through canals with wooden stilt houses, canal-side orchid farms, small temples, and local community life that represents Bangkok's pre-automobile urban form; (4) Bang Krachao 'Green Lung': the Bang Krachao area (a U-shaped river peninsula in Phra Pradaeng District, accessible by short ferry from Klong Toey) is Bangkok's most significant green space — a 'green lung' of 12 square kilometers of urban forest, market gardens, and canal networks preserved within the city; cycling Bang Krachao's canal-side paths is one of Bangkok's most distinctive recreational activities; (5) Floating market remnants: traditional floating markets (damnoern Saduak, 100km west of Bangkok) are primarily tourist-oriented today; within Bangkok proper, Khlong Lat Mayom floating market (weekend, Taling Chan district, west Bangkok) is the most authentic remaining market accessible by Bangkok transit.",
    tip: "Bangkok canal navigation guide: (1) Khlong Saen Saep boat etiquette: canal boats have plastic curtains that passengers drop on command to prevent spray from getting wet; when the boat conductor signals to drop curtains, do so immediately or get wet; the system is efficient once understood; bags and electronics should be protected before the trip; (2) Thonburi canal tour departure piers: Thonburi private long-tail boat tours depart from Tha Chang pier (adjacent Wat Phra Kaew/Grand Palace area) or Saphan Phut pier (Memorial Bridge); negotiate price before boarding, confirm the tour includes specific canals (Khlong Bangkok Noi and Khlong Bang Khun Sri for orchid farm area), and agree on duration; (3) Bang Krachao ferry: the Bang Krachao green lung is reached by local ferry (ท่าเรือคลองเตย Klong Toey pier, or ท่าบางน้ำผึ้ง Bang Nam Phueng pier); the ferry is a basic passenger boat operating every 10–20 minutes; bicycle rental on Bang Krachao side; the area has minimal English signage so offline Google Maps download is essential; (4) Rainy season canal flooding: Bangkok's rainy season (May–October) causes periodic canal flooding; canal boat services may temporarily halt during heavy rain; Khlong Saen Saep boat service stops in heavy rain conditions; having alternative transport plans during rainy season is practical; (5) Canal pollution reality: Bangkok's klongs have undergone major water quality improvement programs since the 1990s; Khlong Saen Saep is significantly cleaner than historical baselines but remains an urban waterway (not swimmable); splash from canal boat is undesirable if it contacts face or eyes; the Bangkok Metropolitan Administration has active canal rehabilitation programs.",
  },
  {
    name: "Bangkok's Floating Markets — Damnoen Saduak, Amphawa & Authentic vs. Tourist",
    emoji: "🛶",
    area: "Floating markets near Bangkok: Damnoen Saduak (100km west, Ratchaburi Province, most famous, most tourist-oriented, 2-hour drive); Amphawa Floating Market (100km southwest, Samut Songkhram Province, weekend only Friday–Sunday evening, more authentic, canal-side); Taling Chan Floating Market (12km west in Bangkok proper, weekend, most accessible, local clientele mix); Khlong Lat Mayom (west Bangkok, weekend, community market, authentic); Bang Nam Phueng Market (Bang Krachao, weekend, minimal tourist presence, local organic market); Wat Sai (Khlong Bangkok Noi area, weekend morning); Klong Hae (southern Thailand, Songkhla area, different character); Ayutthaya area markets",
    price: "Damnoen Saduak boat ride (mandatory for navigation): ฿300–500/person; Damnoen Saduak entry: free but boat ride commercial; Amphawa ferry boats: ฿30–100/short trip; Amphawa weekend food: ฿40–150 per item; Taling Chan Floating Market (free entry, weekend): food ฿50–200; Bangkok minivan to Damnoen Saduak: ฿250–400 from Khao San area; private car (Grab/taxi to Damnoen Saduak): ฿600–1,200 one way; tour package (Damnoen + Rose Garden + Mahanakhon trip): ฿1,500–2,500 per person",
    why: "Bangkok's floating market tradition represents an important Thai cultural heritage that has evolved significantly: (1) Historical floating market context: floating markets were the central commerce model of canal-society Thailand; buying, selling, and food preparation all occurred from boats; the Damnoen Saduak canal system was specifically built in Rama IV era as an irrigation/transport canal; floating markets developed organically along the canal as trading points; (2) Damnoen Saduak's tourist transformation: Damnoen Saduak is the most famous and most visited floating market in Thailand; the market has been almost entirely tourist-oriented for decades; vendors sell from boats primarily for photo opportunities; prices are 2–5x above Bangkok market prices; the experience is genuine in that the canal, boats, and produce are real, but the market exists primarily for tourist consumption rather than local commerce; (3) Amphawa as the authentic alternative: Amphawa Weekend Market (Samut Songkhram Province, 100km from Bangkok) operates Friday–Sunday evenings and is a mix of tourist and local clientele; the evening market on canal-side walkways (with canal boats available, including firefly boat tours at night) provides more genuine floating market character; Amphawa town itself has architectural heritage and a riverside community; (4) Taling Chan as the accessible local option: Taling Chan Floating Market (within Bangkok's Taling Chan District, weekend mornings) is the best option for visitors short on time; it combines floating vendors selling food with canal-side restaurant seating; Thai local families and visitors mix; the market is not tourist-optimized and prices are Bangkok-normal; (5) Firefly tours from Amphawa: a distinctive Amphawa evening activity is the firefly boat tour (approximately 8–10pm); the Amphawa canal system's mangrove trees have established firefly colonies that light the riverbanks; seeing synchronous Southeast Asian fireflies from a canal boat at night is one of Thailand's most memorable natural experiences.",
    tip: "Floating market planning guide: (1) Damnoen Saduak timing (if you go): arrive by 8am before tour buses arrive; the market is at its relative best 7–9am before the crowd builds to midday peak; morning is also better light for photography; the boat ride is genuinely required for market navigation as the canal is the market corridor; (2) Amphawa overnight: spending Friday or Saturday night in Amphawa (guesthouses along the canal, ฿500–1,500) allows evening market and early morning market (Saturday/Sunday) without the 5am wake-up required for a one-day Bangkok-Amphawa day trip; Amphawa's canal-side guesthouse character (many historic wooden Thai commercial buildings converted to accommodation) adds to the experience; (3) Taling Chan logistics: Taling Chan Floating Market is reached by taxi/Grab (approximately ฿200–350 from central Bangkok) or by Khlong Saen Saep canal boat to Khlong Bangkok Noi connection (complex but possible); the market runs Saturday–Sunday from approximately 9am–2pm; (4) Language barrier at authentic markets: Taling Chan and Khlong Lat Mayom vendors have minimal English; Google Translate camera mode and showing smartphone photos of food items ordered resolves most communication; prices are displayed numerically and payment is cash; (5) Combining with Nonthaburi: Amphawa and Damnoen Saduak can be combined with Nonthaburi (30-minute Chao Phraya Express Boat from Bangkok) for a multi-day central Thailand river exploration; Nonthaburi has canal markets and a different day trip character from the Rattanakosin/Banglamphu tourist core of Bangkok.",
  },
  {
    name: "Bangkok's River Economy — Port of Bangkok, Trade History & Chao Phraya Commerce",
    emoji: "⚓",
    area: "Bangkok port and river commerce: Port of Bangkok (Klong Toey, main container port, south Bangkok; one of Southeast Asia's busiest ports); Klong Toey wholesale market (adjacent port, Thailand's largest fresh market, 4am–8am activity); Asiatique The Riverfront (former Bangkok Port site, now evening market/tourist zone, Charoen Krung area); Bangkok River City (antiques and premium market, riverside, Si Phraya area); Saphan Phut Night Bazaar (Memorial Bridge, weekend midnight market); Pak Klong Talad (Flower Market, near Memorial Bridge/Yodpiman Pier); Bangkok International Trade and Exhibition Centre (BITEC, Bang Na, expo venue); international trade routes historically via Chao Phraya to Gulf of Thailand",
    price: "Klong Toey market (public, no entry fee): free; River City Bangkok (antiques, shopping): free entry, individual purchase price; Asiatique Ferris Wheel: ฿250–350; Asiatique entry: free; Klong Toey port area (security perimeter, public cannot enter working port); Bangkok River City antiques auction (periodic): buyer's premium 15–20%; BITEC trade fair (varies by show): ฿200–500 typical trade fair entry",
    why: "Bangkok's commercial identity has been defined by the Chao Phraya River since its founding in 1782: (1) Ayutthaya to Bangkok trade continuity: when Bangkok became Thailand's capital in 1782 (replacing Ayutthaya, destroyed by Burmese invasion in 1767), the Chao Phraya River's commercial role transferred to the new city; Bangkok's original commercial district (Sampeng Lane in current Chinatown) was established by Chinese merchants who came to Bangkok as trade partners; (2) Western commercial influence along the river: the 19th century saw Bangkok's riverfront developed by Western commercial interests; Portuguese, British, French, and Dutch trading houses established offices and warehouses along the Chao Phraya (the surviving architecture of Old Customs House, the East Asiatic Company Building, and various riverside warehouses represents this commercial heritage); Charoen Krung Road (Bangkok's first paved road, 1862) was built to connect Western commercial areas to the river; (3) Klong Toey port's current significance: the Port of Bangkok at Klong Toey handles approximately 1 million TEU (container units) annually; the port is one of Southeast Asia's busiest though increasingly overshadowed by newer, deeper ports at Laem Chabang (80km south, near Pattaya); Klong Toey's wholesale fresh market (active 4–8am) remains the supply chain origin for Bangkok's fresh food retail; (4) Asiatique's port-to-tourism transition: Asiatique The Riverfront occupies the former East Asiatic Company port facilities on the west Chao Phraya bank; the 11-hectare site was converted to an evening lifestyle/shopping destination; the riverfront warehouse architecture (brick arches, original structures) is preserved as the setting; (5) Thai Chinese business community: Bangkok's commercial economy was built substantially by Chinese-Thai immigrant families (often called Sino-Thai); the dominant Thai business families (Chirathivat/Central Group, CP/Charoen Pokphand, TCC/Charoen Sirivadhanabhakdi) all have Chinese-Thai immigrant origins; understanding this demographic (which controls the majority of Thailand's largest private companies) is essential to understanding Bangkok's business culture.",
    tip: "Bangkok river commerce exploration: (1) Klong Toey market safety and timing: Klong Toey wholesale fresh market (open from 2am–9am) is Bangkok's most authentic commercial market; visitors are welcome as observers; early hours (4–6am) are peak activity; the market has no tourist infrastructure (no English signs, no tourist pricing, Thai-only interactions) but is safe; arriving by taxi/Grab (BTS does not reach Klong Toey market directly) at 5am for peak activity photography; (2) River City antiques: the River City complex (Si Phraya Pier, near Oriental Hotel/Mandarin Oriental area) hosts Bangkok's premium antique dealers across multiple floors; this is the legitimate high-end antique and art market (Thai antiques, Southeast Asian art, Burmese lacquerware, Khmer bronze) at auction and gallery pricing; (3) BITEC Bangkok as industry access: Bangkok International Trade and Exhibition Centre hosts trade fairs covering food industry (THAIFEX, one of Asia's largest food trade shows), manufacturing (Manufacturing Expo), and jewelry (Bangkok Gems and Jewelry Fair, March and September, over 50,000 buyers); industry professionals and serious buyers attend these trade shows for business access to Bangkok's manufacturing and agriculture sectors; (4) Chao Phraya development history walk: walking from Asiatique pier south to north (Asiatique → Tha Din Daeng → Sathorn Central → Si Phraya → Rajawongse → Tha Chang) covers Bangkok's most historically dense riverside; interpretive history requires prior reading as signage is minimal; the walking distance is approximately 3km; (5) Bangkok River Heritage Museum: a Bangkok River Museum documenting the Chao Phraya's commercial and cultural history exists at the Museum of Siam (Sanam Chai area); understanding the river's historical role enriches river cruises, canal visits, and walking the riverside.",
  },
];

export function BangkokCanalLife() {
  return (
    <div className="rounded-2xl border border-cyan-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-cyan-700 mb-3">
        🚤 Bangkok waterways — canal commuting, floating markets & Chao Phraya river history
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-cyan-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-cyan-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-cyan-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
