const SPOTS = [
  {
    name: "Orthopedic Surgery & Joint Replacement in Bangkok",
    emoji: "🦴",
    area: "Bumrungrad International Hospital (Sukhumvit Soi 3), Bangkok Hospital (New Phetchaburi Road), Samitivej Sukhumvit Hospital, BDMS Wellness Clinic, Vejthani Hospital (Ramkhamhaeng) — all operate accredited orthopedic departments with JCI certification",
    price: "Orthopedic consultation: ฿1,500–4,000; X-ray + MRI diagnostics: ฿8,000–25,000; Total knee replacement (one knee): ฿350,000–650,000; Total hip replacement: ฿380,000–700,000; ACL reconstruction: ฿120,000–220,000; Arthroscopic surgery: ฿80,000–200,000",
    why: "Bangkok has established itself as one of Asia's premier medical tourism destinations for orthopedic procedures — combining internationally trained surgeons (many with fellowship training in the USA, UK, Germany, or Japan), JCI-accredited hospital infrastructure, and procedure costs at 40–70% below Western equivalents. Thailand's orthopedic sector receives substantial medical tourism traffic for: (1) Joint replacement (total knee and hip arthroplasty) — Thailand's orthopedic surgeons perform high volumes of joint replacements using prosthetics from the same manufacturers (Zimmer Biomet, DePuy Synthes, Stryker) used in Western hospitals; (2) Sports medicine procedures — ACL reconstruction, meniscus repair, rotator cuff surgery, and cartilage restoration performed by orthopedic surgeons who also serve as medical consultants for Thai professional sports teams; (3) Spine surgery — degenerative disc disease, spinal stenosis, and disc herniation treatments from spine specialists; (4) Trauma and fracture management — Bangkok's international hospitals manage complex fractures for both residents and tourists who sustain injuries in Thailand. The quality of care, nursing ratios, and patient accommodation at Bangkok's top international hospitals significantly exceed what's available at cost-equivalent facilities in most Western countries.",
    tip: "Bangkok orthopedic medical tourism considerations: (1) Pre-trip planning for elective procedures: sending medical imaging (MRI, CT, X-rays) and medical history to the Bangkok hospital's international patient center before arrival enables surgeon consultation and pre-authorization in advance; (2) Recovery planning: major orthopedic surgery (joint replacement) requires extended hospital stay (3–5 days inpatient) plus weeks of rehabilitation; planning a Bangkok stay of 3–6 weeks around a joint replacement is standard for medical tourists; (3) Physical therapy access: Bangkok's major hospitals have inpatient and outpatient physical therapy departments; independent physiotherapy clinics throughout the city provide continued rehabilitation care; (4) Second opinion culture: international hospitals in Bangkok welcome patients bringing prior surgical records and seeking second opinions before committing to procedures; this is a legitimate and expected use of Bangkok's medical infrastructure; (5) Medical visa: Thailand issues medical visas (Non-Immigrant O Medical) for patients who provide documentation of planned procedures; the visa allows 90 days with extensions for extended recovery.",
  },
  {
    name: "Sports Rehabilitation & Physical Therapy Bangkok",
    emoji: "💪",
    area: "Hospital-based physiotherapy at major international hospitals, specialized sports physiotherapy clinics in Sukhumvit and Silom, sports performance centers at elite Bangkok gyms, and sports medicine clinics serving Bangkok's expat athletic community",
    price: "Physiotherapy session (45 min): ฿1,500–3,500; Sports massage (therapeutic, 60 min): ฿800–2,500; Dry needling/acupuncture (30 min): ฿600–1,500; HIFES muscle therapy session: ฿2,000–5,000; Comprehensive sports injury assessment: ฿3,000–6,000; 10-session physiotherapy package: ฿10,000–25,000",
    why: "Bangkok's sports physiotherapy and rehabilitation sector has developed to serve both the resident expat athletic community (Muay Thai practitioners, triathletes, marathon runners, CrossFitters) and medical tourists continuing rehabilitation after orthopedic surgery. Bangkok sports physio clinics offer the full spectrum of physical therapy modalities: manual therapy (joint mobilization, soft tissue techniques), exercise prescription, electrotherapy (ultrasound, TENS, shockwave therapy), dry needling, sports massage, and return-to-sport programs. Several Bangkok physiotherapy clinics are operated by Western-trained physiotherapists (Australian, British, Dutch, South African) who bring international approaches to the Bangkok market; these clinics particularly serve the expat community seeking communication-compatible care. The cost advantage is significant: a physiotherapy session in Bangkok costs approximately 30–50% of equivalent sessions in Australia, UK, or USA, making Bangkok a viable location for extended rehabilitation programs that would be financially restrictive at home.",
    tip: "Bangkok sports physiotherapy practical guide: (1) Physio vs. Thai massage: traditional Thai massage (nuad phaen boran) and sports/therapeutic massage are different modalities; sports physiotherapy uses assessment-based treatment plans; Thai massage uses traditional energy-line techniques; both have value but for specific injury rehabilitation, a physiotherapist's approach is more appropriate; (2) Western-trained physiotherapists: Bangkok has physiotherapy clinics staffed by physiotherapists trained and registered in Australia, USA, UK, and other countries; these practitioners use evidence-based approaches familiar to international patients; asking about training background at booking is appropriate; (3) Muay Thai injury specialists: Bangkok has physiotherapists who specialize in Muay Thai training injuries (shin splints, knee injuries, shoulder injuries) — particularly valuable for international fighters training at Bangkok's Muay Thai camps; (4) Running injury rehabilitation: Bangkok's growing running community has generated physio practices that specialize in running gait analysis and running-related injury management; these clinics often have treadmill assessment equipment; (5) Hospital vs. private clinic: hospital-based physiotherapy (at Bumrungrad, Samitivej, Bangkok Hospital) offers comprehensive diagnostic imaging access alongside therapy; private independent clinics offer more appointment flexibility and sometimes more personalized attention.",
  },
  {
    name: "Bangkok Pain Management & Spine Care",
    emoji: "🏥",
    area: "Pain management clinics at major international hospitals, specialized back pain and spine clinics, pain management centers with interventional procedures, and wellness clinics incorporating integrative pain management approaches throughout Bangkok",
    price: "Pain management consultation: ฿2,000–5,000; Epidural steroid injection: ฿15,000–35,000; Nerve block procedure: ฿10,000–30,000; Platelet Rich Plasma (PRP) injection: ฿8,000–25,000; Radiofrequency ablation: ฿25,000–60,000; Comprehensive pain management program: variable",
    why: "Chronic pain management — particularly spine-related pain (lower back, neck, sciatica), joint pain, and neuropathic pain — is an increasingly prominent reason for medical tourism to Bangkok. Thailand's pain management capabilities span: (1) Interventional pain procedures — epidural steroid injections, selective nerve root blocks, facet joint injections, and radiofrequency ablation for chronic spine pain; these procedures are performed by anesthesiologists who have completed pain management fellowship training; (2) Regenerative medicine approaches — platelet-rich plasma (PRP) injections, prolotherapy, and stem cell therapy (Thailand's regulatory framework allows certain regenerative procedures that are more restricted in the USA/EU); (3) Multidisciplinary pain clinics — combining pain medicine, physiotherapy, psychology, and complementary approaches within one program; (4) Traditional Thai and integrative approaches — Ruesi Dat Ton (Thai hermit yoga), herbal compress therapy, and acupuncture integrated with conventional pain management at wellness-focused clinics. Bangkok's pain management practitioners include specialists who trained in the USA, UK, Australia, and Germany, bringing international fellowship-level expertise to Bangkok's cost environment.",
    tip: "Bangkok pain management navigation: (1) Document your history: bringing detailed medical records (imaging reports, previous treatment attempts, medications tried) to Bangkok pain management consultations enables more productive first appointments; (2) Regenerative medicine considerations: Thailand allows some regenerative procedures (including certain stem cell applications) that face stricter regulation in Western countries; seeking these procedures should involve careful research of the clinic's evidence base and practitioner qualifications; (3) MRI accessibility: Bangkok's hospitals and independent diagnostic imaging centers offer MRI scanning without the appointment wait times common in public healthcare systems; same-day or next-day MRI scheduling is standard; (4) Second opinions value: Bangkok's concentration of pain management specialists makes it practical to obtain multiple consultant opinions before committing to invasive procedures; (5) Integrative options in Bangkok: Bangkok's wellness culture creates access to integrative pain management approaches (traditional Thai medicine, acupuncture, herbal therapy) alongside conventional medicine; exploring a combination may produce outcomes not available with purely conventional or purely traditional approaches.",
  },
];

export function BangkokOrthopedic() {
  return (
    <div className="rounded-2xl border border-blue-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-blue-700 mb-3">
        🦴 Bangkok orthopedic & rehabilitation — joint surgery, sports physio & pain management
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-blue-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-blue-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
