const SPOTS = [
  {
    name: "Bangkok Accessibility Reality — Honest Assessment for Mobility-Impaired Travelers",
    emoji: "♿",
    area: "Bangkok accessibility landscape: BTS Skytrain (all stations have elevators — some with history of breakdown frequency); MRT Metro (newer, generally better maintained elevators); accessible accommodation: most international hotels (Marriott, Hilton, Hyatt properties) have fully accessible rooms with roll-in showers; sidewalk conditions: highly variable — central tourist areas (Sukhumvit, Silom) have intermittent wheelchair-accessible surfaces with broken tiles, raised curbs, and construction obstacles; accessible temples: Wat Pho has partial accessibility (main areas); Grand Palace: limited wheelchair accessibility (historic buildings with steps); accessible restaurants: most ground-floor restaurants in hotels and shopping malls; street food: standing-only setups inaccessible for wheelchair users",
    price: "Accessible hotel rooms (wheelchair accessible): international standard ฿3,000–12,000/night; Accessible taxi (modified van, booking required): Grab Assist service available; BTS elevator: free (included in ticket); Airport wheelchair assistance: free (request at check-in or upon booking); Private accessible vehicle with driver: ฿2,000–5,000/day; Accessibility-focused tour operators in Bangkok: ฿3,000–8,000/day",
    why: "Bangkok is a genuinely challenging destination for travelers with mobility impairments but is achievable with preparation: (1) The contrast between formal and actual accessibility: Bangkok's formal accessibility infrastructure (elevator laws for BTS stations, accessibility requirements for new construction) exists but enforcement and maintenance are inconsistent; elevator out-of-service situations are common enough to require always having alternative access routes planned; (2) BTS vs. MRT accessibility: the BTS Skytrain system has elevators at all stations (though reliability varies) and was designed before comprehensive accessibility standards; the MRT Metro (newer) has generally better accessibility infrastructure; the Airport Rail Link has wheelchair access; (3) Hotel accessibility quality: Bangkok's international hotel sector has genuine accessibility capability; major brands (Marriott, Hilton, IHG, Hyatt) have roll-in shower accessible rooms; requesting photos of the specific accessible room configuration before booking prevents mismatched expectations; (4) Street navigation reality: Bangkok's sidewalks are the primary barrier for wheelchair users; uneven tiles, open drains, food vendor carts blocking paths, and construction (constant in Bangkok) create navigation challenges; planning routes using Google Maps satellite view to identify potential obstacles and preferring shopping mall interior routes (air-conditioned, level, maintained) reduces barriers; (5) Human assistance culture: Thai people's helpfulness (offering assistance, explaining elevator locations, helping navigate obstacles) partially compensates for infrastructure limitations; asking for assistance in Bangkok is generally met with genuine help rather than frustration.",
    tip: "Planning an accessible Bangkok trip: (1) Contact hotels directly before booking: call or email the specific hotel to ask for exact measurements of accessible room features (doorway width, turning radius in bathroom, grab bar positions); international hotel chains have accessibility coordinators who can provide photos; (2) Use Grab for all transportation: Grab's app-based system (Grab Assist for wheelchair-accessible vehicles) is more reliable for accessibility than negotiating with street taxis; (3) Shopping mall navigation strategy: Bangkok's interconnected shopping malls (Siam Paragon, CentralWorld, EmQuartier, Emporium) are flat, air-conditioned, and connected to BTS stations via accessible bridges; routing through malls for significant distances reduces outdoor sidewalk navigation significantly; (4) Accessible Bangkok tours: a small number of Bangkok tour operators specialize in accessible tours (using accessible vans, choosing step-free venues, pre-scouting locations for wheelchair access); finding these operators through disability travel communities (Wheel the World, accessible travel Facebook groups) is more reliable than general tour operators; (5) Water transport accessibility: the Chao Phraya tourist boats and some canal boat services are not wheelchair-accessible (boarding requires navigating floating gangways with no consistent accessibility); planning river routes requires checking specific pier accessibility in advance.",
  },
  {
    name: "Bangkok for Deaf & Hard of Hearing Visitors",
    emoji: "👂",
    area: "Deaf community in Bangkok: National Association of the Deaf in Thailand (NADT); Thai Sign Language (TSL — distinct from other sign languages, has its own grammar and vocabulary); Bangkok's deaf community centered around schools for the deaf; TSL interpreter services: available through NADT and professional interpreter agencies; Deaf-accessible accommodation: standard hotels with visual fire alarms, text messaging apps via smartphone; deaf-owned businesses: growing small number in Bangkok, find through Thai Deaf community social media",
    price: "TSL interpreter: ฿1,500–3,000/hour (professional); Apps: Google Translate live caption (free), Otter.ai (free tier); Deaf-friendly tour operators: ฿3,000–8,000/day; Communication apps for travel: Ava (captioning), speech-to-text built into Android/iOS; SMS or LINE messaging for hotel communication: free",
    why: "Bangkok's communication infrastructure is relatively accessible for deaf and hard of hearing visitors with adaptation: (1) Thai Sign Language (TSL): TSL is a distinct sign language with its own grammar; it is not related to American Sign Language (ASL) or British Sign Language (BSL); basic tourist communication does not require TSL as Bangkok's visual and written communication options (menus with photos, pointing at items, using translation apps) function well for most tourist interactions; (2) Visual communication abundance: Thai food culture's heavy use of pictorial menus, item displays (market food stalls where you point at dishes), and visual signage makes restaurant and market navigation easier for deaf visitors than in cultures with primarily verbal ordering systems; (3) Smartphone translation use: the combination of Google Translate (text-to-text translation, camera-based text translation for signs and menus), text messaging in LINE (Thailand's dominant messaging app), and captioning apps significantly reduces communication barriers in Bangkok; (4) Bangkok's written English in tourist areas: Bangkok's tourist infrastructure areas (Sukhumvit, Silom, Chinatown, major temples) have substantial English written signage; this written communication advantage helps deaf visitors navigate tourist Bangkok; (5) Thai deaf community visibility: Thailand's deaf community has visibility in Bangkok (deaf-owned coffee shops, deaf staff at some services, deaf school events); connecting with this community can enhance cultural exchange for deaf visitors.",
    tip: "Communication strategies for deaf visitors in Bangkok: (1) Download Google Translate with Thai language pack offline before arriving (Thai characters are not always romanized and offline access helps in low-connectivity situations); (2) LINE app is universal in Thailand: having LINE installed allows text communication with any Bangkok business or hotel; more Thais have LINE than email; (3) Pre-arrange hotel communication preferences: informing hotels in advance about communication preferences (text messaging, visual alerts for fire alarms) allows hotels to prepare; major international hotels have experience with deaf guest communication; (4) Emergency preparedness: saving the Tourist Police (1155) as a LINE contact and knowing that text communication is possible with Thai emergency services reduces communication barriers in emergencies; (5) Bangkok's BTS announcements: BTS Skytrain announcements are both audio and displayed on screens at many stations (though not all); major stations on the tourist routes (Siam, Asok, Silom) have strong visual display systems.",
  },
  {
    name: "Bangkok Accessible Food, Markets & Attractions",
    emoji: "🍜",
    area: "Wheelchair-accessible Bangkok food options: shopping mall food courts (floor level, wide aisles); Eathai (Central Embassy basement — accessible escalators + elevator); Or Tor Kor Market (Chatuchak area, open market, mostly flat surface, accessible by MRT Kamphaeng Phet exit 2 elevator); accessible attractions: MOCA Bangkok (museum of contemporary art, wheelchair accessible); Bangkok National Museum (partial accessibility); Siam Ocean World (accessible); SEA LIFE Bangkok (accessible); Chocolate Ville (outdoor restaurant village, mostly flat); Icon Siam (riverside mall, fully accessible including river taxi pier with assistance)",
    price: "Icon Siam (fully accessible mall, river pier access): entry free, shops and restaurants at normal prices; Siam Ocean World: ฿990–1,200; SEA LIFE Bangkok (Siam Paragon): ฿600–990; MOCA Bangkok: ฿250; Or Tor Kor Market: free (market entry), food ฿80–300; Eathai food hall (Central Embassy): food ฿80–500; Accessible restaurant in hotel: typically ฿200–1,000",
    why: "Bangkok has specific accessible venues and food experiences that work well for visitors with mobility and sensory limitations: (1) Shopping mall food culture accessibility: Bangkok's extensive air-conditioned shopping mall food hall culture (Eathai at Central Embassy, food courts at Siam Paragon, Central Chidlom food hall, Icon Siam Sooksiam Thai food hall) offers Thai food in accessible, flat, air-conditioned environments; these food halls feature the same Thai food available at street stalls in settings that work for wheelchairs; (2) Icon Siam river access: Icon Siam mall has Bangkok's most accessible luxury riverside destination; the mall's pier-level accessibility (river shuttle boat from Sathorn pier has adapted boarding assistance for wheelchairs) connects the mall to the BTS network; inside Icon Siam, the Sooksiam section is a Thai market atmosphere (floating market aesthetic, Thai food vendors, handicrafts) in a flat, maintained indoor environment; (3) Or Tor Kor Market accessibility: the government-managed fresh market adjacent to Chatuchak Weekend Market (MRT Kamphaeng Phet) has the best accessibility of Bangkok's traditional markets; the floor surface is level, the aisles are wide, and the organized layout reduces navigation complexity; the market sells prepared Thai food, fresh fruit, and traditional Thai food products; (4) Museums with accessibility: MOCA Bangkok (Museum of Contemporary Art, northern Bangkok near Chatuchak) has elevator access and ramped galleries showcasing 900+ pieces of Thai art; the museum's modern building was designed with more accessibility in mind than historic buildings; (5) Sky-level Bangkok views accessibility: Bangkok's accessible observation decks (Baiyoke Tower 2 observation deck has elevators, King Power MahaNakhon Sky Walk has fully accessible access including elevators to the glass floor observation deck) provide Bangkok's skyline experience without requiring climbing.",
    tip: "Making the most of accessible Bangkok attractions: (1) Or Tor Kor Market timing: arriving at Or Tor Kor Market before 9am avoids the crowds that make navigation difficult; weekday morning visits have the most accessible navigation space; (2) Icon Siam river boat accessibility: the river shuttle between Icon Siam and Sathorn Central Pier provides wheelchair access (boarding assistance available from Icon Siam pier staff); communicating the need for assistance in advance allows staff to prepare the accessible boarding arrangement; (3) Accessible Bangkok walking food tours exist: a small number of tour operators offer accessible food tours using vehicles (not walking) between Bangkok food locations; searching specifically for 'accessible food tour Bangkok' through disability travel platforms identifies these operators; (4) Temple accessibility at Wat Pho: Wat Pho (the reclining Buddha temple adjacent to the Grand Palace) has the best general accessibility of Bangkok's historic temples; the main reclining Buddha complex is on ground level; the surrounding temple complex is largely flat but has uneven paving; (5) Weather and accessibility: Bangkok's heat (particularly May–September) adds an additional physical challenge for travelers managing chronic conditions; air-conditioned shopping malls provide relief and accessible routes between outdoor tourist sites.",
  },
];

export function BangkokDisabilityAccess() {
  return (
    <div className="rounded-2xl border border-blue-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-blue-700 mb-3">
        ♿ Bangkok accessibility guide — mobility, deaf travel & accessible attractions
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-blue-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-blue-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-blue-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
