const TOPICS = [
  {
    title: "Bangkok Plastic Surgery Tourism — Rhinoplasty, Eyelid Surgery & What Makes Thailand a Destination",
    emoji: "💉",
    summary: "Bangkok is one of Asia's major medical tourism destinations for cosmetic surgery, combining JCI-accredited hospitals, internationally trained surgeons, and pricing significantly below Western equivalents: (1) Bangkok's plastic surgery cost comparison: rhinoplasty (nose job) in Bangkok: ฿40,000–120,000 ($1,100–3,400) vs. $6,000–15,000 in the US; double eyelid surgery (Asian blepharoplasty): ฿30,000–80,000 vs. $3,000–8,000 US; facelift: ฿80,000–250,000 vs. $10,000–30,000 US; breast augmentation: ฿80,000–180,000 vs. $6,000–12,000 US; these represent 70–80% cost reduction even accounting for travel costs from Western countries; (2) Hospital tier for cosmetic surgery: the safest Bangkok cosmetic surgery environment is within JCI-accredited or BOI-certified hospitals (Bumrungrad's Cosmetic Surgery Centre, Bangkok Hospital's Cosmetic Surgery Unit, Samitivej, BNDC — Bangkok Nose and Dental Centre); choosing budget clinics or unlicensed providers creates significant medical risk; Thailand has experienced rare but documented adverse outcomes from unaccredited cosmetic providers; (3) Thai aesthetic trends: Bangkok's cosmetic surgery market reflects Thai (and broader Asian) aesthetic preferences — double eyelid surgery (making monolid eyes appear to have a crease, consistent with East Asian beauty standards) is the most common procedure in Thailand; nose jobs focus on bridge height (augmenting the traditionally flat bridge common in Southeast Asian ethnicity); skin whitening procedures and chemical peels are also very common alongside surgical options; (4) Recovery logistics: Bangkok is well-suited for surgical recovery due to availability of private nursing, hotel-based recovery programs, and proximity to follow-up care; multiple Bangkok hospitals have partnered with nearby recovery hotels (sometimes hospital-run guesthouses) for post-operative recuperation; flying within 7–14 days of major surgery is medically inadvisable (deep vein thrombosis risk) — planning sufficient Bangkok recovery time is essential; (5) Medical verification requirements: verifying surgeon credentials before committing to surgery in Bangkok requires checking: Thai Medical Council registration, board certification in plastic surgery, hospital privileges at an accredited facility, before/after patient portfolio with authentic cases, and consultation consultation process quality.",
    action: "Thailand's Medical Tourism Authority: MTA (meditour.or.th); Thai Society of Plastic and Reconstructive Surgeons for surgeon verification; JCI-accredited Bangkok hospitals: Bumrungrad, Bangkok Hospital, Samitivej, BNH; Medical Tourism Corporation coordinates Bangkok medical tourism packages; Thailand Board of Investment (BOI) medical center certification is a quality indicator; AVOID: unlicensed clinics advertised via social media without clear hospital affiliation; consultation before commitment: reputable Bangkok plastic surgeons provide in-person consultations at no or low cost (฿1,000–3,000 credited toward surgery).",
  },
  {
    title: "Bangkok Wellness Retreats — Detox Programs, Fasting & Holistic Health Centers",
    emoji: "🌿",
    summary: "Bangkok and its surroundings have developed a significant wellness tourism sector beyond day spas: (1) Bangkok's urban wellness options: Bangkok proper has multiple medical wellness centers offering IV vitamin therapy, hyperbaric oxygen therapy, gut health programs, and comprehensive health screening packages; Absolute You (multiple Bangkok locations) and other health optimization centers serve Bangkok's expat health-conscious market with Western-standard wellness protocols; (2) Near-Bangkok wellness retreats: the area around Bangkok (particularly Hua Hin, Kanchanaburi, and Khao Yai) has established wellness retreat centers offering multi-day programs; Kamalaya Wellness Sanctuary (Koh Samui, not adjacent but Thailand's most internationally recognized wellness resort), Dharadhevi (Chiang Mai), and smaller Bangkok-accessible retreats serve different budget levels; (3) Thai detox tradition: Thai traditional medicine includes herbal steam baths, abdominal massage (chi nei tsang), and digestive health treatments that have genuine physiological basis within the Thai traditional medicine framework; Wat Pho (Bangkok) trains traditional massage practitioners; detox programs combining Thai traditional medicine with modern health screening create an integrated wellness product; (4) Fasting retreat protocols: Thailand has attracted international wellness tourists seeking medically supervised fasting programs (juice fasting, water fasting, intermittent fasting protocols in a supportive retreat environment); Bangkok's proximity to beach and mountain retreat environments enables combined urban health screening + countryside retreat programs; (5) Bangkok's health screening as wellness tourism: Bangkok's international hospitals offer comprehensive health screening packages (full body check, cardiac evaluation, oncology screening, eye and dental examination, all in one or two days) at prices 50–70% below Western equivalents; Bumrungrad's Executive Health Check ($200–500), Bangkok Hospital's Comprehensive Health Screening, and Samitivej's Health Screening Programs serve health-conscious tourists combining Bangkok visits with preventive health investment.",
    action: "Bangkok wellness program booking: request a booking list from Bangkok Hospital Group, Bumrungrad International, or Samitivej Hospital for health screening packages; Thailand Retreats (thailand-retreats.com) aggregates day-to-extended retreat options near Bangkok; fasting retreat booking: advance reservation required for medically supervised programs (minimum 3–7 days typical program length); Bangkok health clinics: Absolute You (absoluteyou.com), iSanook (Sukhumvit, lifestyle medicine), Theera Wellness; Hua Hin wellness resort options within 3-hour drive from Bangkok.",
  },
  {
    title: "Bangkok Eye Care & Glasses — LASIK Surgery, Optical Shops & Contact Lens Market",
    emoji: "👁️",
    summary: "Bangkok has a thriving eye care market that attracts both local patients and international medical tourists: (1) LASIK and refractive surgery pricing: LASIK eye surgery in Bangkok costs ฿35,000–80,000 per eye ($1,000–2,300) vs. $1,500–3,000 per eye in the US; Bangkok's LASIK market has specialized centers with Alcon, Zeiss, and Wavelight platforms; SMILE (Small Incision Lenticule Extraction) is available at Bangkok's premium eye centers; FemtoLASIK (bladeless LASIK) is standard at most Bangkok eye centers; (2) Bangkok optical shops: Bangkok's optical market is massive — Victor Optical (Siam area, budget to mid-range), Silom Optical (Silom, long-established), Index Optical Group (established chain), and mall-based international opticians (Bausch and Lomb shops) provide the full spectrum; Bangkok frames pricing is significantly below Japanese or Western optical pricing for similar quality; (3) Contact lens accessibility: Bangkok is one of the world's most contact-lens-accessible markets; 7-Eleven and Watsons sell contact lens solution and some brands of daily contacts; specialty contact lens retailers (colored contacts, Korean brands popular in Thailand's beauty market) are concentrated in Siam Square and Hua Mum areas; (4) Eye examination quality in Bangkok: Bangkok's private hospital ophthalmology departments (Phyathai, BNH, Bumrungrad, Bangkok Hospital) maintain international examination standard; specialty conditions (retinal surgery, glaucoma management, corneal disease) are treated to international standard at Bangkok's major teaching hospitals (Siriraj, Ramathibodi); (5) Colored contact lens culture in Bangkok: Thai beauty culture has a significant colored contact lens market; circle lenses (enlarging the iris appearance) and color-shift lenses are widely available and purchased without prescription through Thai optical shops; visitors seeking cosmetic contacts can find extensive Bangkok selection at Siam Square optical booths and beauty supply shops.",
    action: "Bangkok LASIK centers: Bangkok Eyes Laser Vision Center (Asoke), Asia Medical Eye Center, Rutnin Eye Hospital (Asoke, oldest and most established Bangkok eye hospital, founded 1963); pricing consultation: all Bangkok LASIK centers provide free initial consultation and examination to determine candidacy before pricing; post-LASIK travel timing: most LASIK protocols recommend avoiding air travel for 24 hours minimum (eye pressure changes) and avoiding swimming for 2 weeks; optical shopping: MBK Shopping Centre level 4 has concentrated budget optical shops; Siam Paragon and CentralWorld have higher-end optical chains.",
  },
];

export function BangkokSurgery() {
  return (
    <div className="rounded-2xl border border-blue-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-blue-700 mb-3">
        💉 Bangkok medical tourism — plastic surgery, wellness retreats & eye care
      </div>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-blue-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-blue-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
