const SPOTS = [
  {
    name: "Chao Phraya River — Bangkok's Living Highway",
    emoji: "⛴️",
    area: "Chao Phraya River Express Boat: operates N1 (Pak Kret) to S4 (Saphan Taksin) with multiple piers; Chao Phraya Tourist Boat (orange flag): Central Pier (Sathorn) to Phra Arthit Pier; cross-river ferries (khram) at multiple points; Maharat Pier, Wang Lang Pier, Tha Tian Pier (Wat Po vicinity), Phra Arthit Pier (Banglamphu), Si Phraya Pier (close to Chinatown); private dinner cruises departing Central Pier",
    price: "Chao Phraya Express Boat (single fare): ฿15–40 depending on service type; Tourist Boat day pass: ฿200; Cross-river ferry (khram): ฿3–5; Dinner cruise (Chaophraya Cruise, River Cruise): ฿800–2,000/person including buffet; Private charter boat (per hour): ฿1,500–4,000; Longtail boat klang tour (1 hour): ฿1,200–2,000 for the boat",
    why: "The Chao Phraya River is Bangkok's original artery — the reason Bangkok was founded at this specific location and the infrastructure that made Bangkok Asia's most significant port city in the 19th and early 20th centuries: (1) Working river transport: the Chao Phraya Express Boat (white/yellow/orange flags indicating different service levels and stops) is a genuine commuter waterway transport system; riding the regular commuter express boat (not the tourist boat) alongside Thai office workers and market vendors during morning and evening rush is the most authentic way to experience the river; (2) Historic architectural riverside: Bangkok's most significant historical buildings face the Chao Phraya; passing by boat you see Wat Arun (Temple of Dawn, eastern bank), Grand Palace walls (eastern bank), Wat Pho, the Portuguese Embassy (one of Bangkok's oldest foreign missions), the Oriental Mandarin Hotel (1876), Wat Rakang, and multiple colonial-era riverside mansions in sequence; (3) River canal network (khlong): Bangkok's surviving canal network connects to the Chao Phraya through multiple entry points; longtail boat tours of Bang Krachao and the Thonburi canals (particularly Khlong Bangkok Yai and Khlong Bangkok Noi) access this surviving pre-road Bangkok urban structure; (4) Chao Phraya dinner cruise: evening dinner cruises on the Chao Phraya provide Bangkok's most romantic viewing of the river-flanking landmarks illuminated at night; Wat Arun lit up at night is one of Bangkok's most iconic images; (5) River pollution context: the Chao Phraya carries significant urban runoff and industrial discharge; swimming is inadvisable (locals don't swim in the main river); the government's ongoing Chao Phraya deep-cleaning projects show steady improvement; eating riverside fish requires source awareness.",
    tip: "Chao Phraya River navigation: (1) Tourist Boat vs. commuter boat: the orange-flag Tourist Boat (฿200 all-day pass) operates on a slower schedule with audio commentary and serves only major tourist piers; the regular express boat (฿15–40 per ride) is faster, cheaper, and serves more piers but requires knowing which pier flag color serves your destination; (2) Longtail boat booking: longtail boat (rua hang yao) canal tours are booked at Tha Chang Pier (near Grand Palace), Tha Tian Pier, and Phra Arthit Pier; negotiating fixed price before departure and agreeing on duration and stops prevents mid-tour price changes; (3) Sunset positioning: for Chao Phraya sunset photography, positioning on the east bank (Charoen Krung side) allows shooting Wat Arun with western sun backlight during golden hour; (4) Ferry etiquette: Chao Phraya Express Boat boarding and alighting at piers happens quickly (30–60 second stops); positioning near the bow or stern for faster exit helps during crowded peak hour; (5) Cross-river ferries for Thonburi access: small cross-river ferries (khram) at multiple points provide ฿3–5 crossings to the Thonburi bank; these ferries are the most direct access to Wat Arun, Wang Lang market, and Thonburi neighborhood food.",
  },
  {
    name: "Bangkok's Canal (Khlong) Heritage — Surviving Water City",
    emoji: "🚣",
    area: "Bangkok canal (khlong) network: Bangkok Yai and Bangkok Noi (Thonburi, preserved canal neighborhoods); Khlong Saen Saep (central Bangkok east-west express boat service, Bang Kapi to Tha Chang); Khlong Om (Nonthaburi, north Bangkok; Buddhist temple canal communities); Khlong Bang Krachao (the green lung — cycling canal island, accessible from Klong Toey pier by ferry)",
    price: "Khlong Saen Saep Express Boat (single fare): ฿12–21; Bang Krachao bicycle rental (at island shops): ฿60–150/hour; Canal walking tour (self-guided): free; Guided canal walking tour: ฿800–2,500; Kayak/canoe rental (at specific points): ฿400–800/hour; Thonburi longtail boat canal tour: ฿1,200–2,000 for the boat",
    why: "Bangkok's canal network represents the surviving remnants of a city that was once called the 'Venice of the East' — before road construction systematically filled its waterways: (1) Khlong Saen Saep: Bangkok's east-west canal express boat service (Saen Saep Canal) is a genuinely useful commuter route through central Bangkok; running from Rajdamri (near Amarin Plaza) to Wang Burapha in the west; the boat's speed through central traffic congestion makes it faster than road transport for this route; (2) Thonburi canal community: the west bank canals of Thonburi preserve an older Bangkok lifestyle — canal-side wooden houses, orchid farms, Buddhist temples accessible only by water, and community markets that operate by boat; this Thonburi canal world is completely different from Bangkok's modern east bank development; (3) Bang Krachao cycling via canal: the Bang Krachao 'green lung' is entirely surrounded by canals; the ferry crossing from Klong Toey pier traverses a section of Chao Phraya; once on the island, the interior canal paths (accessible by bicycle) wind through flooded gardens and traditional orchid and fish farms; (4) Canal markets: Bangkok's floating market tradition (historically operating on canal networks) survives in modified form at Taling Chan Floating Market (Taling Chan, accessible from the city by BRT or taxi) and Khlong Lat Mayom (Phutthamonthon area); these Thai-local markets are distinct from the tourist-oriented floating markets near Bangkok; (5) Canal traditional houses: sections of Bangkok's Thonburi canals still have original canal-side houses built on stilts directly over the water; the architectural tradition of Thai water-side housing visible here is disappearing as maintenance challenges lead to demolition.",
    tip: "Bangkok canal exploration: (1) Saen Saep Boat orientation: Khlong Saen Saep Express Boat piers don't have English signs at all stops; counting piers from a known point or using the Saen Saep Express Boat app helps navigate; commuters are typically willing to indicate your stop if you show them your destination on paper; (2) Thonburi canal tour early morning: Thonburi canal longtail tours at 7–9am access the working canal community — market boats, school boats, monks' alms boat routes — that defines traditional canal life; afternoon tours miss this daily routine activity; (3) Bang Krachao flood timing: Bang Krachao's interior paths can flood significantly during late October–November peak monsoon; checking conditions before visiting and wearing footwear appropriate for shallow water is practical during flood season; (4) Canal noise: Bangkok's surviving canals are loud; longtail boat engines are extremely loud (earplugs are useful if noise sensitive) and diesel-scented; the noise and smell are part of the authentic experience but worth knowing in advance; (5) Taling Chan Market timing: Taling Chan Floating Market operates Saturday–Sunday from approximately 8am–4pm; combining the market visit with a canal boat ride (offered at the market) creates the most complete floating market canal experience.",
  },
  {
    name: "Bangkok Riverside Architecture & Heritage Districts",
    emoji: "🏛️",
    area: "Bangkok riverside heritage: Charoen Krung Road (Bangkok's first paved road, 1864); Si Phraya (Bangrak) old commercial buildings; Talat Noi (Teochew Chinese community neighborhood, heritage buildings and shrines); French Embassy and Portuguese Embassy heritage precincts; Bangrak area Customs House; BACC river-adjacent cultural district; Flower Market (Pak Khlong Talat, riverside)",
    price: "Self-guided heritage walk: free; Guided heritage walking tour: ฿500–2,000; Tha Tien community tour: ฿400–1,200; Museum entry (various heritage museums): ฿30–150; Architecture photography walk (self-guided): free; Boat to access specific areas: ฿5–50",
    why: "Bangkok's riverside heritage districts contain the most architecturally significant and historically rich streetscapes in the city: (1) Charoen Krung Road heritage: Bangkok's oldest road runs from the Grand Palace area south to Bang Krachao; the 19th century commercial buildings along this road include European colonial-era architecture, shophouse rows, and the surviving infrastructure of Bangkok's trade economy that pre-dates Sukhumvit's existence; (2) Talat Noi (Little Market) neighborhood: one of Bangkok's most authentic Chinese-Thai heritage neighborhoods; the Teochew Chinese community's 19th century shophouses, clan associations, and temple network are well-preserved and make Talat Noi the most rewarding heritage walk neighborhood accessible from tourist Bangkok; (3) Si Phraya / Bangrak: the Bangrak district between Si Phraya and Saphan Taksin contains Bangkok's former commercial heart — customs houses, merchant warehouses, the old French and British extraterritorial communities' infrastructure; (4) Portuguese legacy: the Portuguese were Bangkok's first European trading partner; the Portuguese Embassy and adjacent Catholic community (Santa Cruz Church, the oldest Catholic church in Bangkok, established 1770) represent the earliest European community in the city; (5) Flower market riverside: Pak Khlong Talat's riverside location made it accessible by boat (traditionally how flowers came from upcountry farms); the market's riverside area shows the surviving connection between waterway transport and Bangkok's wholesale trade infrastructure.",
    tip: "Bangkok riverside heritage exploration: (1) Talat Noi heritage timing: Talat Noi's authentic atmosphere is best preserved on weekday mornings when the neighborhood operates as a working community; weekend evenings bring Bangkok's young creative crowd to the area's cafés and bars which change the atmosphere significantly; (2) Guided vs. self-guided heritage walks: Bangkok's English-language heritage walk guides (organized through Bangkok Tourism Division and private operators) provide historical context depth that self-guided exploration misses; the Charoen Krung and Talat Noi areas specifically benefit from guide knowledge; (3) Shrines on the way: Bangkok's Chinese-Teochew community shrines (san jao) are embedded in Talat Noi's shophouse fabric; many are accessible but have visiting etiquette (remove shoes, no pointing at Buddha images, modest dress) that is respected by respectful visitors; (4) Architecture photography: Bangkok's riverside heritage buildings have excellent photographic quality; the combination of aged facades, canal reflections, and contemporary Bangkok life creates compelling street photography conditions; morning light (7–10am) from the east produces the best facade lighting on the river's east bank buildings; (5) Community respect in Talat Noi: Talat Noi is a functioning residential and working neighborhood that happens to have heritage interest; the community is increasingly aware of being a photography destination; respecting residential privacy and asking permission for portrait photography is the appropriate approach.",
  },
];

export function BangkokRiverLife() {
  return (
    <div className="rounded-2xl border border-blue-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-blue-700 mb-3">
        ⛴️ Bangkok river life — Chao Phraya Express, canal networks & riverside heritage walks
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-blue-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-blue-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
