const TOPICS = [
  {
    title: "Bangkok's Train Network — Hua Lamphong, Bang Sue Grand Station & Thailand Rail History",
    emoji: "🚂",
    summary: "Bangkok's railway infrastructure sits at a fascinating intersection of colonial-era heritage and rapid modernization: (1) Hua Lamphong Station's heritage: Hua Lamphong (Krung Thep Aphiwat Historical Station, Rama IV Road) is Bangkok's original main railway terminus, opened in 1916 with Italian neoclassical architecture; the station's elegant vaulted roof, stained glass windows, and historic scale make it one of Bangkok's most architecturally significant buildings; after the opening of Bang Sue Grand Station (2021), Hua Lamphong lost its function as the primary intercity terminus; it now operates as a heritage station with some regional services while future use is under discussion; (2) Bang Sue Grand Station (Krung Thep Aphiwat Station): opened partially in 2021, Bang Sue Grand Station (near Bang Sue BTS station, north Bangkok) is designed to become Thailand's primary rail hub — connecting existing rail lines, airport link, and future high-speed rail; the station is designed for 600,000 passengers/day at full capacity; currently the station is operational but significantly under its future capacity as high-speed rail connections remain under construction; (3) State Railway of Thailand (SRT) network: Thailand's national rail network extends to all major cities — Chiang Mai (8–12 hours by overnight train), Udon Thani (9–11 hours), Hat Yai (17–18 hours), Surat Thani (11–12 hours for Koh Samui ferry connection), Nakhon Ratchasima/Korat (5–6 hours); third-class (non-AC) and second-class (AC sleeper) and first-class (private sleeper cabin) options exist for most routes; (4) Bangkok's intercity rail value: Thailand's train network offers exceptional value-to-distance on sleeper routes — an overnight second-class sleeper from Bangkok to Chiang Mai costs approximately ฿700–1,500 vs. ฿2,000–4,000 for a budget airline ticket; the train journey also eliminates the airport-to-city cost and time at both ends; (5) Train punctuality and planning: Thailand's rail system has a reputation for delays, particularly for northern route services; building buffer time into train-dependent travel plans is recommended; checking SRT's official schedule and live status at the station is more reliable than third-party aggregators for current delay information.",
    action: "SRT online ticket booking: seat61.com (international overview and booking links), thairailway.com; official SRT: railway.co.th (Thai language primarily); Bang Sue Grand Station location: MRT Bang Sue station (Purple Line), BTS Mo Chit then bus; Hua Lamphong location: MRT Hua Lamphong station (Blue Line); intercity train booking advice: book 3–7 days ahead for popular weekend overnight routes (Bangkok-Chiang Mai Friday nights); travel agent booking: many Bangkok travel agents and hostels can book SRT tickets for a ฿100–200 service fee.",
  },
  {
    title: "Bangkok's BTS & MRT — Comprehensive Metro Guide, Lines & Navigation",
    emoji: "🚇",
    summary: "Bangkok's rapid transit network has expanded dramatically and now covers most tourist and residential areas of the city: (1) BTS Skytrain system overview: Bangkok's BTS Skytrain operates two main lines — Sukhumvit Line (N/E direction, Mo Chit to Kheha/Bearing, 35 stations including all major Sukhumvit tourist areas, Siam interchange, Asok, Nana, Phrom Phong, On Nut, Bearing) and Silom Line (runs from National Stadium through Siam interchange, Sala Daeng, Chong Nonsi, Wongwian Yai, extending to Bang Wa in the west and Bang Mot in the south); (2) MRT (Metropolitan Rapid Transit) lines: MRT Blue Line (circular route connecting Hua Lamphong, Sukhumvit/Asok interchange, Chatuchak Park, Bang Sue, completing the outer ring to Lak Song/Tha Phra); MRT Yellow Line (monorail, Samrong/On Nut interchange to Lat Phrao, serving eastern Bangkok's residential and commercial areas); MRT Pink Line (Light Rail, under expansion); (3) Airport connections: Suvarnabhumi Airport to central Bangkok: Airport Rail Link (ARL) to Phaya Thai station (connection to BTS, 29 minutes, ฿45 maximum); Don Mueang Airport to BTS: no direct rail — take Bangkok BUS express or Grab; the Airport Rail Link's City Line stops at multiple intermediate stations (Lat Krabang, Ramkhamhaeng, Makkasan/Phetchaburi) providing additional connection points; (4) Rail interchange complexity: Bangkok's rail system requires understanding key interchange points — Siam Station (BTS Sukhumvit/Silom Lines interchange); Asok/Sukhumvit (BTS Asok + MRT Sukhumvit); Sala Daeng/Silom (BTS Sala Daeng + MRT Silom); Chatuchak Park/Mo Chit (BTS + MRT); Bang Sue (MRT + SRT National Rail); Phaya Thai (BTS + Airport Rail Link); (5) BTS fare system: BTS fares are distance-based (฿16–62 for BTS Skytrain); fares are calculated per section; Rabbit Card (stored-value smart card, also works on Bangkok buses and can be used at some shops) eliminates the need for exact fare at machines; top-up machines at all stations; MRT uses a different fare system (token-based for Blue Line, or stored value card).",
    action: "BTS navigation app: BTS SkyTrain app (official), Google Maps (integrates BTS/MRT routing), Moovit; Rabbit Card purchase: any BTS station, initial ฿30 card + deposit + top-up; MRT card: MRT Purse (stored value for Blue/Yellow/Pink Lines), purchased at MRT stations; Bangkok transit map: BMTA (bangkokbusline.com) for bus + rail integration; transit fare calculator: bts.co.th/transit-fare-calculator; BTS operating hours: approximately 6am–midnight daily; MRT operating hours: approximately 6am–midnight; plan according to last train times when nightlife extends past midnight.",
  },
  {
    title: "Bangkok Bus Routes — BMTA Network, Raptor App & Getting Around Like a Thai",
    emoji: "🚌",
    summary: "Bangkok's bus network is the most extensive public transport layer in the city but is rarely used by visitors due to complexity — understanding it unlocks cheaper and slower but authentic Bangkok mobility: (1) BMTA bus network scale: Bangkok Mass Transit Authority (BMTA) operates 400+ bus routes covering all Bangkok districts including areas not served by BTS/MRT; the network is genuinely city-wide but routes are complex to navigate without local knowledge; (2) Bus fare structure: Bangkok buses have two main fare categories — non-AC (orange buses, red buses): fixed fare ฿8–15 regardless of distance; AC buses (blue-cream, red-AC, white-blue): distance-based ฿10–24; the non-AC buses are the cheapest form of Bangkok public transport; (3) Raptor app as navigation tool: the Raptor app (Thai government-supported, free iOS/Android) provides real-time GPS tracking of Bangkok buses (BMTA) on a map; the app shows where buses currently are on each route; a significant advance over the previous situation (no tracking, unpredictable arrival times); the app was released 2022–2023 and has meaningfully improved bus usability; (4) The bus route grid: Bangkok's bus routes follow a partially logical grid structure with routes numbered by geographic sector; Sukhumvit-adjacent routes (numbers in certain ranges) cover different corridors than Rattanakosin routes; understanding which route numbers serve which corridors reduces the learning curve; (5) Bus advantages over BTS: Bangkok's buses connect destinations without BTS/MRT coverage (most outer districts); buses travel along surface roads providing city views and neighborhood experience; the canal boat + bus combination for certain corridors (crossing west-east across the city without BTS connection) reduces cost significantly.",
    action: "Raptor app: iOS and Android, free (Thai government bus tracking app); BMTA official route finder: bmta.co.th (Thai-language primarily); Bangkok bus assistance: asking at bus stops or showing Google Maps destination to BMTA conductors usually produces helpful route direction; bus payment: carry small bills (฿20, ฿50) — conductors issue tickets from change purses; some AC buses use EMV card payment (Rabbit Card) but non-AC buses typically use cash only; canal boat (Khlong Saen Saep): orange flag boats along Bangkok's main east-west canal complement buses for certain cross-city routes; Pratunam pier to Asok pier takes approximately 20 minutes by canal boat vs. 45–60 minutes by road during traffic.",
  },
];

export function BangkokRailway() {
  return (
    <div className="rounded-2xl border border-indigo-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-indigo-700 mb-3">
        🚂 Bangkok transit — national rail heritage, BTS/MRT metro network & bus navigation
      </div>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-indigo-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-indigo-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
