const SPOTS = [
  {
    name: "Thai Silk & Traditional Textiles in Bangkok",
    emoji: "🧵",
    area: "Thai silk and textile in Bangkok: Jim Thompson House & Flagship Store (Surawong); Thai Craft Museum (adjacent Jim Thompson House); OTOP (One Tambon One Product) government retail in Chatuchak Weekend Market; Pak Klong Talat (wholesale fabric district near Yaowaraj); Pahurat district (South Asian fabrics alongside Thai); Pratunam fashion district (wholesale cloth); Chatuchak Section 4 (handmade textiles, northern Thai weavings); Golden Place (government-sponsored Thai craft stores near Grand Palace area)",
    price: "Jim Thompson Thai silk (per meter): ฿800–3,000; OTOP Thai silk (per meter): ฿300–800; Mudmee silk (Isaan ikat, per meter): ฿200–600; Pha khao ma (traditional farmer cloth, sarong): ฿150–400; Northern Thai hill tribe woven textiles: ฿200–2,000; Professional woven bag (hill tribe): ฿300–1,500; Thai cotton fabric (per meter): ฿100–300; Batik (Thai-Malay style): ฿150–500 per piece",
    why: "Thai textile traditions represent some of Southeast Asia's most technically sophisticated weaving and dyeing arts, with distinct regional styles: (1) Thai silk heritage: Thai silk production uses silkworm-farmed threads woven into distinctly Thai patterns; the northeastern province of Korat (Nakhon Ratchasima) is the primary silk production region; Thai silk's characteristic sheen and tensile strength come from its unique two-layered thread structure; Jim Thompson's 1950s marketing established Thai silk globally; (2) Mudmee (ikat) weaving: Isaan's ikat silk tradition (mudmee) involves resist-dyeing threads before weaving to create complex geometric patterns; different districts of Khon Kaen, Maha Sarakham, and Udon Thani have distinctive mudmee pattern traditions; Bangkok's better textile shops carry certified mudmee from named weaving communities; (3) Northern Thai hill tribe textiles: Karen, Hmong, Akha, and Lahu hill tribe textile traditions each have distinct patterns (Hmong's reverse-appliqué paj ntaub embroidery; Karen's backstrap-loom striped cotton; Akha's elaborate silver-bead and color-band decoration); Bangkok's Chatuchak Market and specialty stores carry authentic hill tribe products; (4) Pha khao ma versatility: Thailand's traditional striped cotton cloth (pha khao ma) was historically a working man's waistcloth but is now recognized as a design-classic Thai textile; used as sarong, head wrap, baby carrier, and shopping bag by Thai farmers; high quality hand-woven versions from specific Suphan Buri weaving communities command premium prices; (5) Contemporary Thai textile design: Bangkok has a growing contemporary textile design community (Thitipoom, Jaspal, Thai craft stores at Siam Discovery) that reinterprets traditional Thai weaving patterns in modern fashion applications; silk-cotton blends, naturally dyed fabrics, and sustainably sourced textiles represent the premium contemporary Thai textile market.",
    tip: "Thai textile shopping guidance: (1) Authenticity verification: Thai silk certification includes the Thai Silk Symbol (a woman at a loom inside a Thai flag outline) issued by the Department of International Trade Promotion; products labeled 'Thai Silk' without this certification may be blended with synthetic fiber; (2) Jim Thompson vs. OTOP pricing reality: Jim Thompson prices reflect design, quality control, and brand premium; OTOP (One Tambon One Product) government-certified products from the same weaving communities at Chatuchak sell at 40–70% lower prices for equivalent base quality; the difference is largely brand and retail infrastructure; (3) Washing Thai silk: Thai silk should be hand-washed in cold water with gentle soap or dry-cleaned; machine washing damages the fiber; buying silk that will face difficult care is a functional consideration; (4) Textile investment logic: handmade Thai ikat silk (mudmee, 6–8 meters at 100% silk) represents significant artisan labor (1–2 weeks of weaving for one length); prices from ฿1,500–6,000 for full fabric length reflect genuine craft value; comparison shopping between Chatuchak OTOP and mall textile stores helps calibrate fair pricing; (5) Hill tribe craft fair trade: purchasing hill tribe textiles through fair trade organizations (Thai Tribal Crafts cooperative, Doi Tung Royal Project) ensures artisan prices are captured by the weaving communities rather than Bangkok intermediary mark-up.",
  },
  {
    name: "Bangkok Celadon, Benjarong & Thai Ceramics",
    emoji: "🏺",
    area: "Bangkok ceramics retail and craft: Chatuchak Weekend Market (Section 14–15 area for ceramics); Celadon House (Ratchadapisek); Chitralada Products (royal craft support, products from royal project workshops); Petchaburi Road antique and ceramic shops; Naraiphan (government craft store, Ratchadamnoen/Ratchaprasong); Old ceramic town: Ratchaburi (70km from Bangkok); Benjarong production: Samut Sakhon workshops",
    price: "Benjarong tea set (6 cups, authentic): ฿3,000–15,000; Mass-produced Benjarong (tourist market): ฿200–1,500; Celadon vase (small, tourist quality): ฿300–1,500; Celadon vase (Chiang Mai studio, art quality): ฿1,500–8,000; Sangkhalok antique ceramic (verified): ฿2,000–30,000+; Contemporary Thai ceramic bowl (artist-studio): ฿500–3,000; Traditional water jar (craft quality): ฿300–800",
    why: "Thailand's ceramic traditions span ancient Sangkhalok pottery through royal Benjarong ware to contemporary ceramic art: (1) Benjarong (five colors) royal ceramic: Benjarong is Thailand's royal ceramic tradition; Chinese porcelain blanks (historically imported from Jingdezhen, now made in Thailand or imported from China) are hand-painted with specific Thai patterns using five traditional colors (red, yellow, green, blue, white) in dense decorative schemes; Benjarong production remains concentrated near Bangkok (Samut Sakhon); (2) Sangkhalok (Sukhothai Kingdom ceramics): Sangkhalok pottery from the Sukhothai-period kilns of Si Satchanalai (14th–15th century) is among Southeast Asia's most significant archaeological ceramic tradition; authenticated antique Sangkhalok pieces are museum-quality; Bangkok's antique market has many reproductions; genuine pieces are verified through thermoluminescence testing; (3) Chiang Mai celadon: northern Thailand's contemporary celadon (fired earthenware with green-gray glaze) industry produces quality studio ceramics; Bangkok shops (particularly Chatuchak and Celadon House) import Chiang Mai celadon; (4) Contemporary Thai ceramic scene: Bangkok has a growing studio ceramic art community (workshops in Ekkamai, Thong Lo, and Ari areas) influenced by Japanese folk pottery aesthetics and Korean onggi tradition; studio pottery workshops offer wheel-throwing experiences (฿500–1,500 for a session) alongside retail of finished pieces; (5) Ratchaburi ceramic town: the town of Ratchaburi (70km from Bangkok) is Thailand's largest ceramic production hub (primarily large storage jars, water urns, and planters) with a distinct blue dragon jar tradition; a Ratchaburi day trip provides access to wholesale ceramic production.",
    tip: "Thai ceramics shopping and authentication: (1) Benjarong quality levels: authentic Benjarong uses fine imported porcelain blanks, natural mineral pigments, and multiple kiln firings; mass-produced Benjarong uses ceramic blanks, commercial paints, and single firing; the differences are visible in color depth (authentic is richer), gold application (authentic uses real gold leaf), and weight (authentic feels heavier); (2) Chatuchak Section 14–15 for ceramics: the Section 14–15 area in Chatuchak Weekend Market has Bangkok's best concentration of ceramics vendors; this section has both contemporary studio ceramics and antique reproductions; genuine antiques require expert authentication and provenance documentation; (3) Workshop experience value: Bangkok's studio ceramic workshops (typically 2–3 hours, including wheel time and glazing) provide hands-on craft experience regardless of the finished result's quality; the learning experience justifies the ฿500–1,500 cost even for beginners; (4) Antique ceramic verification: any antique ceramic worth significant investment should be authenticated by Silpakorn University's archaeology department or a certified Thai antiquities assessor; export of antique ceramics from Thailand requires Fine Arts Department approval (export without approval is illegal); (5) Storage jar purchases: Ratchaburi's large ceramic storage jars (typically 60–150 cm tall, used for water storage and garden features) are impractical souvenirs but excellent garden purchases for Bangkok residents; transport to Bangkok by pickup truck can be arranged through Ratchaburi ceramic shops.",
  },
  {
    name: "Bangkok Craft Beer & Artisan Goods — Bangkok Made",
    emoji: "🍺",
    area: "Bangkok artisan goods: Ekkamai Artisan Market (monthly); One Night Only Market (Sukhumvit artisan); Mahanakhon cube artisan goods; ICONLUXE Bangkok (Iconsiam) — contemporary Thai design; Craft beer taprooms: Mikkeller Bangkok (Ekkamai), Tawandang (giant Thai brewery taproom, Rama 3), Chatuchak Craft Beer vendors; Artisan food market: Farm to Table pop-up markets (BTS stations, monthly); Designer craft: TCDC (Thailand Creative & Design Center, Emporium) for inspiration",
    price: "Bangkok craft beer (taproom pint): ฿180–350; Imported craft beer (bottle): ฿200–400; Bangkok artisan coffee roast (250g): ฿280–550; Artisan soap set (local Thai brands): ฿180–450; Handmade ceramic mug (Bangkok studio): ฿400–900; Artisan jam/condiment: ฿120–300; Original print (Thai artist): ฿500–5,000+; Thai designer tote bag: ฿300–800",
    why: "Bangkok's artisan economy has expanded significantly with the emergence of a Thai creative class: (1) Bangkok craft beer: Thailand's legal restrictions on alcohol production (minimum production volumes that preclude nanobrewery operations) have historically suppressed the craft beer market; foreign-produced craft beer (Mikkeller, collaboration brews) and legal Thai microbreweries (Doi Brewing, Chalawan, Sandport) fill Bangkok taprooms; craft beer culture has grown rapidly despite regulatory constraints; (2) Thai artisan food renaissance: Bangkok's artisan food market has grown to include specialty items reflecting Thai ingredients; locally roasted Thai-grown coffee (beans from Chiang Rai highlands), artisan Thai palm sugar and coconut sugar products, specialty Thai chili condiments, and fermented Thai food products (traditional pastes, pickles) are sold at Bangkok's artisan markets; (3) Thai designer goods market: Bangkok's young designer community creates products from Thai materials using contemporary design language; natural latex goods, banana fiber textiles, coconut shell tableware, and recycled plastic fashion items reflect Thai designer sustainability interest; (4) TCDC (Thailand Creative & Design Center): the TCDC at Emporium (Sukhumvit 24) is Thailand's primary design inspiration and resource center; its materials library (available by membership) is used by Bangkok designers; exhibitions, workshops, and design events are open to the public; the TCDC bookshop is Bangkok's best design publication resource; (5) Artists' market culture: Bangkok's pop-up artisan market scene (Artbox, One Night Only, monthly street markets in Ekkamai and Ari) provides direct artist-to-buyer commerce outside the retail-intermediary traditional structure; buying directly from Bangkok artists and craftspeople provides both better prices and genuine maker connection.",
    tip: "Bangkok artisan economy participation: (1) Craft beer regulatory context: Thai alcohol production law (2008 Beer Act) requires minimum 10-million-liter annual production for licensing, effectively prohibiting microbreweries; smaller volumes are produced offshore (some Bangkok craft beer brands contract-brew in Laos or internationally); this regulatory context explains why 'Bangkok craft beer' is often technically produced outside Thailand; (2) Artisan market scheduling: Bangkok's artisan markets operate on irregular schedules; confirming specific dates through the event's Instagram or Facebook before visiting (some events run monthly, some seasonally) avoids wasted trips; (3) Artisan pricing negotiation: unlike fixed-price retail, Bangkok's artisan markets often have some pricing flexibility (10–20% reduction for cash, multiple-item purchase); asking politely is appropriate; (4) Thai-natural dye products: Bangkok's artisan textile producers using indigo (plant-dyed), natural sappan wood red, and turmeric yellow dyes on cotton and silk produce genuinely unique products; natural dye colors are visually distinct from synthetic; asking 'natural dye?' (สีธรรมชาติ?) clarifies production method; (5) TCDC membership for design professionals: TCDC membership (Annual: ฿300–500) provides access to the materials library, specialized design publications, and professional-grade design tools; worthwhile for Bangkok-based designers and architects even for short stays.",
  },
];

export function BangkokHandicraft() {
  return (
    <div className="rounded-2xl border border-yellow-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-yellow-700 mb-3">
        🧵 Bangkok crafts & artisan goods — Thai silk, Benjarong ceramics & Bangkok-made artisan products
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-yellow-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-yellow-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
