const SPOTS = [
  {
    name: "Bangkok Street Photography — The Ultimate Urban Canvas",
    emoji: "📸",
    area: "Primary street photography zones: Yaowarat (Chinatown) for neon-lit evening culture; Khlong Toey community market for authentic daily life; Flower Market (Pak Khlong Talat) for before-dawn color; Bang Lamphu/Khao San for backpacker culture intersection with traditional Bangkok life; Thonburi riverside communities; Dusit palace district for colonial-era architecture + daily life intersections",
    price: "Street photography requires only camera + budget for transport; BTS/MRT single journey: ฿16–59; Tuk tuk or grab for tight areas: ฿50–200; Printing/developing services (Bangkok photo labs): ฿300–2,000 for prints; Bangkok street photography workshop (if taking one): ฿1,500–6,000; Memory cards at MBK/Pantip: ฿200–2,000",
    why: "Bangkok is consistently ranked among the world's top 5 cities for street photography — the combination of visual density (signage, color, people in constant motion), cultural contrast (ancient temple gates behind 7-Eleven convenience stores), temporal layers (pre-dawn market preparation intersecting with late-night nightlife culture), and the general openness of Thai culture to being photographed in public creates an extraordinary photographic environment. Key Bangkok street photography advantages: (1) Light: Bangkok's tropical light creates dramatic shadows at golden hour (6–7am, 5–6:30pm); the overcast season (August–October) produces even, non-harsh light ideal for long days of shooting; (2) Pace: Bangkok's street life operates nearly 24 hours; pre-dawn market activity (3–6am at flower and wholesale markets) offers unique imagery unavailable in slow-closing European cities; (3) Cultural diversity: within 2 kilometers, a Bangkok photographer can capture Chinese temple ceremonies, Muslim morning prayer culture, Thai Buddhist monk alms rounds, modern hipster café culture, and traditional textile market activity; (4) Transport photography: Bangkok's BTS Skytrain infrastructure, Chao Phraya river ferries, and tuk tuks create movement-based photographic subjects unavailable in car-centric cities; (5) Signage and typography: Bangkok's bilingual Thai-English signage, hand-painted Chinese characters on Chinatown storefronts, and the visual complexity of Thai script creates typographic photographic possibilities unique to the city.",
    tip: "Bangkok street photography practical guide: (1) Best morning shoot locations: Pak Khlong Talat flower market (3–6am, sellers arriving, color explosion), BTS station commuter rush (7:30–9am), and monk alms rounds in residential neighborhoods (5:30–7:30am) represent Bangkok's three most distinctive morning photography environments; (2) Legal context: photography in public spaces is legal in Thailand without restriction; photographing inside temples requires respectful behavior and occasional fee payment (most major temples charge ฿50–100 entry); (3) Khlong Toey market authenticity: Bangkok's largest wholesale fresh market (open from midnight through morning) is one of the most authentic street photography environments in Southeast Asia — far from tourist areas, genuine commercial Bangkok life; (4) Camera theft awareness: street photography gear should avoid conspicuous display in dense tourist areas; mirrorless systems with less ostentatious appearance than DSLR with large telephoto lens attract less theft attention; (5) Print labs in Bangkok: Bangkok has multiple professional-grade photo printing services (in Silom and near Pantip Plaza) for printing street photography work at competitive prices compared to European labs.",
  },
  {
    name: "Bangkok Photography Equipment & Camera Shopping",
    emoji: "🎯",
    area: "Camera retail in Bangkok: Fortune Town IT Mall (Ratchadaphisek — Bangkok's camera market hub); Pantip Plaza (Pratunam — general IT including cameras); Foto File (multiple Bangkok branches — Fujifilm authorized); Power Buy / Central retail camera sections; used camera market on Silom (smaller but active); Sukhumvit Soi 51 area (professional camera rental services)",
    price: "Sony A7 series (latest gen, Thailand retail): typically 5–15% below US MSRP; Fujifilm X series (gray market available at Fortune Town): 10–20% below European prices; Used camera at Fortune Town: ฿5,000–80,000 depending on model/condition; Camera bag (peak design style at local stores): ฿2,000–8,000; Memory card (fast UHS-II, 256GB): ฿1,500–3,000; Camera rental (per day, professional mirrorless): ฿800–2,500",
    why: "Bangkok is Asia's second-best camera shopping destination (after Tokyo/Osaka) for combining price competitiveness with selection variety. Key Bangkok camera shopping advantages: (1) Fortune Town IT Mall: Bangkok's dedicated camera and photography equipment market; multiple floors of camera vendors including both authorized dealers and gray market importers; the gray market pricing for Japanese cameras (Sony, Fujifilm, Canon, Nikon) is often 10–20% below European retail; (2) Used camera market: Fortune Town's used camera section (international brands resold by Thai dealers) offers Japanese cameras at significant discounts compared to new; checking body condition and shutter count is essential; (3) No customs advantage (important caveat): Thailand does not have the VAT refund advantage of Japan; Bangkok's camera prices reflect duty-paid retail; cameras are cheaper than in Europe but typically not cheaper than US or Japan for identical models; (4) Lens selection: Bangkok's authorized dealers stock major lens systems; Sigma Art series, Tamron, and Tokina lenses are available at competitive prices; (5) Camera rental: Bangkok has camera rental services (particularly near Sukhumvit and in the photography community area) for renting professional-grade cameras and lenses at daily rates — useful for photographers visiting Bangkok who want to travel light.",
    tip: "Bangkok camera shopping strategy: (1) Fortune Town 5th–6th floor: these floors house the highest concentration of camera vendors; comparing prices between multiple vendors on the same day within Fortune Town is efficient before purchasing; (2) Gray market warranty: gray market camera imports have manufacturer warranty only in their origin country (Japan or Hong Kong); Bangkok gray market cameras sell with 'local warranty' from the Thai dealer rather than Sony Thailand / Fujifilm Thailand international warranty; understand what coverage this provides before purchasing; (3) Used camera inspection: for used cameras at Fortune Town, requesting a demonstration (checking shutter count via app, reviewing sample images) before purchasing is standard and accepted practice; (4) Photography tour vs. workshop: multiple Bangkok street photography guides offer tours of Bangkok's photographic neighborhoods rather than technical workshops — useful for photographers who know their gear but want local neighborhood guidance; (5) Camera strap and accessories: Bangkok's accessory market (leather camera straps, cage rigs, follow focus systems) available at Fortune Town and Pantip Plaza is significantly less expensive than equivalent accessories in Western markets.",
  },
  {
    name: "Bangkok Film Photography & Darkroom Culture",
    emoji: "🎞️",
    area: "Film photography in Bangkok: Photogram (Sukhumvit area — film photography specialist, development, printing, workshop); Lomography Bangkok (licensed store in Siam area); film purchasing at Central Chidlom camera section, photo labs scattered through Bangkok's inner neighborhoods; darkroom community spaces through Bangkok art university programs",
    price: "35mm color film (Kodak Gold 200, roll): ฿150–300; 35mm color film (Kodak Portra 400, roll): ฿350–600; 120 medium format film roll: ฿250–500; C-41 color development (per roll): ฿150–300; E-6 slide development (per roll): ฿300–500; Black and white development (per roll): ฿200–400; Scanning (per roll): ฿150–400",
    why: "Bangkok's film photography community is one of Southeast Asia's most active — the analog photography revival that swept global creative communities from 2015 onward has strong Bangkok expression: (1) Thai film photography community: Bangkok's film photographers organize through Instagram (#ThaiFilmCamera, #BangkokFilm), Facebook film photography groups, and periodic meet-ups that produce collaborative zines and exhibitions; (2) Development labs in Bangkok: multiple Bangkok photo labs offer film development services including E-6 (slide film) — development options available in Bangkok that have disappeared from many Western cities; (3) Film supply: 35mm film is stocked at several Bangkok photo specialty retailers and Lomography Bangkok; 120 medium format film is available though supply varies; 4x5 large format film is special-order; (4) Lomography culture: Lomography's Thailand official store supports the analog-creative photography community; Lomography cameras (Diana, LC-A, Lomo'Instant) and their cross-processed, vignette-heavy aesthetic have an active Thai following; (5) Street photography and film: Bangkok's environment is particularly well-suited for street photography on film; the city's light levels are adequate for ISO 400 film without flash in most conditions.",
    tip: "Bangkok film photography community access: (1) Photogram Bangkok: this specialty film photography shop is the community hub for Bangkok's analog photography scene; the shop staff are knowledgeable about film photography and can connect visitors with the Bangkok film community; (2) Film development timing: plan 2–5 business days for film development and scanning at Bangkok labs; rushing development is possible at some labs for a premium; (3) Film in tropical climate: Bangkok's heat and humidity affect film storage; keeping unused film rolls in a sealed bag in hotel/apartment refrigeration prevents heat damage; (4) Thai pinhole photography: Thailand has a niche but enthusiastic pinhole photography community; film pinhole photography is practiced by Bangkok photographers interested in the slow, contemplative photographic process; (5) Expiration date film: Bangkok's photography community trading groups occasionally source and sell expired film (both color and black and white) at discounts with predictable results for experienced film photographers; expired film produces distinctive color shifts and grain enhancement that have aesthetic value in specific photography contexts.",
  },
];

export function BangkokStreetPhotography() {
  return (
    <div className="rounded-2xl border border-gray-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-gray-700 mb-3">
        📸 Bangkok street photography — urban canvas, camera shopping & film photography culture
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-gray-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-gray-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
