const SPOTS = [
  {
    name: "Lat Phrao — Bangkok's Northern Residential Hub, MRT Yellow Line & Local Community Feel",
    emoji: "🏘️",
    area: "Lat Phrao district, northern Bangkok: Lat Phrao Road (main artery running northeast from downtown toward Don Mueang airport direction); MRT Yellow Line (Lat Phrao 83 / Lat Phrao 101 / Phawana stations, opened 2023); Central Lat Phrao (shopping mall, long-established Bangkok local mall), The Mall Ngamwongwan (nearby, large traditional mall), Union Mall (popular for vintage and secondhand fashion); Lat Phrao Soi 71/101 residential communities; Bang Sue Grand Station (western edge, new main Bangkok train hub); Victory Monument (south, expressway access); Chatuchak Park (south-southwest, adjacent to Chatuchak Weekend Market)",
    price: "MRT Yellow Line fares (Lat Phrao area): ฿15–42 depending on distance; Grab car from Lat Phrao to Siam: approximately ฿80–150 depending on traffic; apartment rental in Lat Phrao: ฿8,000–20,000/month for 1-bedroom (significantly lower than Sukhumvit equivalent); serviced apartments Lat Phrao: ฿15,000–35,000/month; food at Lat Phrao local markets: ฿40–120 per dish (authentic local pricing, not tourist pricing)",
    why: "Lat Phrao represents a side of Bangkok that most short-term visitors never encounter — the authentic, middle-class Thai residential Bangkok that most of the city's 11 million residents actually inhabit: (1) Lat Phrao's residential character: Lat Phrao is one of Bangkok's most densely populated residential districts, home primarily to Thai middle-class families, government workers (Government Complex on Chaeng Wattana Road nearby), and long-term Bangkok residents; the area has minimal tourist infrastructure (few English menus, no tourist pricing, authentic Thai daily life); (2) MRT Yellow Line opening Lat Phrao: the 2023 MRT Yellow Line connected Lat Phrao more directly to Bangkok's transit network; Lat Phrao now has three Yellow Line stations (interchange with MRT Blue Line at Lat Phrao station), improving accessibility for commuters and making the area more attractive for residential Bangkok; (3) Union Mall and Bangkok vintage fashion: Union Mall (between Lat Phrao Road and nearby streets) has emerged as Bangkok's most popular venue for vintage and secondhand fashion — multiple floors of secondhand clothing, vintage Japanese and Western brands, streetwear; the venue draws younger Bangkok shoppers specifically for vintage/thrift culture; (4) Lat Phrao's food market culture: the Lat Phrao district has dense neighborhood market (talat) culture — morning markets, evening walking markets, and established local restaurants catering to residential Thai customers rather than tourists; the food quality-to-price ratio is among Bangkok's best in this district type; (5) Lat Phrao as Bangkok's 'real life': the district represents Bangkok's vast middle residential belt — the Bangkok that most residents experience daily — in contrast with the tourist-centric zones of Silom, Sukhumvit, and Rattanakosin.",
    tip: "Lat Phrao area practical tips: (1) Union Mall vintage access: Union Mall is best reached by taxi from BTS Mo Chit (15 minutes, ฿60–100) or by MRT Yellow Line to Lat Phrao stations; the mall is most active on weekends (11am–8pm); the vintage section occupies upper floors — elevator to the top floor then work downward; (2) Central Lat Phrao for local Bangkok retail: Central Lat Phrao (large mall on Lat Phrao Road) is where local Bangkok families shop rather than tourists — restaurants inside are authentic Thai prices, food court has excellent local options; (3) Lat Phrao morning market timing: Lat Phrao's best neighborhood morning market experience is 7–9am (markets thin out by 10am as the Bangkok heat intensifies); asking a hotel or Airbnb host about the nearest talat kaew (local community market) to their location is the best way to find authentic morning food markets in Lat Phrao; (4) MRT Yellow Line to Chatuchak: from Lat Phrao Yellow Line stations, the MRT Blue Line interchange at Lat Phrao station connects to Chatuchak Park and Mo Chit stations (Chatuchak Weekend Market access) in approximately 5 minutes — making Lat Phrao a practical base for weekend Chatuchak visitors.",
  },
  {
    name: "Bangkok On Nut — Expat Suburb, International Community & East Sukhumvit Living",
    emoji: "🌆",
    area: "On Nut (Udom Suk) area, eastern Sukhumvit district: BTS On Nut station and BTS Udom Suk station (Sukhumvit Line, eastern end); Ekkamai BTS (nearby, more entertainment-focused); On Nut area: Tesco Lotus On Nut (large hypermarket), Big C On Nut (another hypermarket), Samitivej Hospital On Nut (private hospital); Seenspace On Nut (lifestyle complex, coffee and restaurants); Punnawithi area; Bang Na area (further east, more suburban); expressway access points for road travel; Hua Mak community (further east, less developed for expat living)",
    price: "Accommodation On Nut / Udom Suk: apartment rental ฿12,000–25,000/month 1-bedroom (lower than Asok/Phrom Phong despite only 10 BTS stops away); luxury condo On Nut: ฿25,000–50,000/month; local restaurant meals On Nut: ฿60–150/dish; Japanese restaurant On Nut: ฿200–600/meal (large Japanese expat community has driven authentic Japanese restaurant cluster); 7-Eleven and Tesco proximity: within 100m from most On Nut residential buildings",
    why: "On Nut has emerged as one of Bangkok's most practical expat residential areas over the past decade, with a specific character that distinguishes it from Sukhumvit's more tourist-oriented inner sections: (1) On Nut's practical expat appeal: On Nut's appeal is driven by the intersection of: (a) BTS Sukhumvit Line access (30–40 minutes to Siam, Asok, business areas); (b) significantly lower rental costs than inner Sukhumvit (Nana, Asok, Phrom Phong); (c) large supermarket access (Tesco Lotus On Nut hypermarket is one of Bangkok's largest, Villa Market branch in the area); (d) growing local restaurant and café scene; (e) lower tourist density than inner Sukhumvit; (2) Japanese expat community concentration: On Nut has one of Bangkok's highest concentrations of Japanese expat residents; this has driven the development of authentic Japanese restaurants, Japanese grocery stores (including Fuji Supermarket), and Japanese-language services in the area; Japanese ramen, izakaya, and sushi quality in On Nut is notably high compared to most Bangkok areas; (3) Bang Krachao cycling gateway: BTS On Nut (or nearby BTS stations) is one of the access points for reaching the Bang Krachao 'Green Lung' cycling area across the river — the Klong Toei pier connecting to Bang Krachao is approximately 15 minutes by Grab from On Nut BTS; (4) On Nut's café and food evolution: what was primarily a residential area 10 years ago now has a developed independent café culture (Seenspace On Nut, numerous independent coffee shops), gym/wellness facilities (Jetts 24 Hour Fitness, Carnival Fitness nearby), and expanding restaurant options; (5) On Nut's long-stay visitor appeal: visitors planning 1–4 week Bangkok stays increasingly choose On Nut-area accommodation for its value-to-accessibility ratio — paying 30–40% less than Phrom Phong rents for equivalent living standard with only slightly longer commute to tourist areas.",
    tip: "On Nut residential living practical tips: (1) BTS On Nut station orientation: On Nut BTS has two exits serving different directions of Sukhumvit — Exit 1 toward Tesco Lotus/main residential sois, Exit 2 toward 77 (On Nut) area; getting lost between these exits is common for new arrivals; (2) Tesco Lotus On Nut for comprehensive shopping: Tesco Lotus On Nut hypermarket (5 minutes walk from BTS On Nut) has the most comprehensive grocery selection in the On Nut area including international products, Thai market goods, electronics, clothing, pharmacy — one-stop shopping for extended Bangkok residence; (3) On Nut food market timing: the night market area near On Nut BTS (behind the station) is active from approximately 5pm to midnight; the range includes Thai street food, grilled items, dessert stalls, and local sit-down restaurants at neighborhood prices (฿60–120 per dish); (4) Japanese grocery for authentic Japanese products: Fuji Supermarket (On Nut area) stocks Japanese imported groceries, fresh fish, Japanese condiments, snacks, and ready-made Japanese foods — serving the local Japanese community and visitors seeking Japanese products at reasonable prices; (5) Safety and infrastructure On Nut: On Nut is considered a safe Bangkok residential area; flooding risk is moderate (eastern Bangkok lower elevation) — checking flood reports during rainy season (May–October) is advisable for ground-floor properties.",
  },
  {
    name: "Bangkok Don Mueang — Airport Area, Northern Bangkok & Budget Airline Hub",
    emoji: "✈️",
    area: "Don Mueang area, northern Bangkok: Don Mueang International Airport DMK (25km north of central Bangkok, 15km north of Victory Monument); Si Kan MRT station (Purple Line, near Don Mueang area, not directly adjacent); Rangsit area (north of Don Mueang, Pathum Thani province — technically outside Bangkok proper); Lak Si district (administrative area encompassing Don Mueang); nearby: Royal Thai Air Force Museum, Dusit Zoo (older location), Royal Turf Club (historic horse racing venue); Future Park Rangsit (large mall in Rangsit, accessible from Don Mueang airport direction); A1 airport bus from Don Mueang to Mo Chit BTS/Victory Monument: ฿30–50, approximately 30–45 minutes",
    price: "Don Mueang to central Bangkok transport costs: A1 bus ฿30–50; taxi meter: ฿200–350 (depending on traffic, with potential expressway toll ฿25–75); Grab from Don Mueang to Sukhumvit: ฿200–450 depending on traffic; hotel near Don Mueang (budget traveler stopover): ฿400–1,200/night (significantly cheaper than inner Bangkok); late-night Don Mueang accommodation: Amari Don Mueang (connected to airport, premium), D Varee Xpress Makkasan or similar budget to midrange options; budget airline prices ex-Don Mueang: Nok Air, Thai Lion Air, Thai AirAsia domestic routes ฿500–2,500",
    why: "Don Mueang Airport's role in the Bangkok transport ecosystem requires specific understanding for budget and regional travelers: (1) Don Mueang's budget airline role: Don Mueang (DMK) primarily serves budget airlines and low-cost carriers in Southeast Asia; airlines based at Don Mueang include: AirAsia (Thai AirAsia), Nok Air, Thai Lion Air, Scoot, and others; premium full-service airlines predominantly use Suvarnabhumi (BKK); a Bangkok trip combining arrival at Suvarnabhumi and departure from Don Mueang (or vice versa) requires inter-airport transfer — a commonly underestimated logistical challenge; (2) Don Mueang to Suvarnabhumi inter-airport transfer: the two Bangkok airports are 60–70 km apart with no direct rail connection; inter-airport transfer options: taxi/Grab (60–90 minutes in normal traffic, 120+ during rush hour, ฿300–500 + expressway); airport shuttle bus (A1 to Mo Chit BTS then Airport Rail Link to Suvarnabhumi, total 90–120 minutes, ฿80–100 total); recommended minimum transfer time at Don Mueang/Suvarnabhumi: allow minimum 2.5–3 hours for inter-airport transit; (3) Don Mueang area as northern Bangkok gateway: Don Mueang airport's northern Bangkok position makes it the practical gateway for travelers heading to northern Thailand destinations (Chiang Mai, Chiang Rai, Udon Thani) — many budget airline routes from Don Mueang serve these northern cities; (4) Don Mueang transit logistics: some Bangkok visitors do a 'Don Mueang overnight' — arriving late at Don Mueang, staying in an adjacent hotel, and taking an early morning connection or bus north; the airport has a 24-hour transit hotel (SleepBox); (5) Don Mueang's own identity: beyond airport logistics, the Don Mueang area (Lak Si district) is a substantial residential and commercial area for northern Bangkok residents, with local markets, hospitals, and community infrastructure serving the district independently of the airport.",
    tip: "Don Mueang airport and area practical guide: (1) Night transport from Don Mueang: after midnight, the A1 bus stops running; Grab or meter taxi (with the meter on and expressway route agreed) is the only viable option from Don Mueang to central Bangkok late at night; surge pricing applies via Grab during peak demand (post-midnight flight arrivals can cause temporary surge); (2) Don Mueang check-in timing: Don Mueang is a smaller, simpler airport than Suvarnabhumi; domestic check-in 90 minutes before departure, international check-in 2–2.5 hours before departure is adequate; the airport becomes very crowded during budget airline peak hours (early morning and evening domestic flights); (3) Expressway timing from Don Mueang: the expressway (toll road) significantly reduces Don Mueang to central Bangkok travel time — agree on 'take expressway' with taxi driver and budget ฿25–75 for tolls; the alternative surface road (Viphavadi Rangsit Road) can be extremely congested during rush hours; (4) Don Mueang food and amenities: Don Mueang has a food court on the departure level (international terminal) and convenience shops; quality is modest compared to Suvarnabhumi; the best food near Don Mueang is in the Lak Si area outside the airport (Grab Delivery viable from airport hotel); (5) Don Mueang transit hotel: for travelers with long layovers or early morning connections, the SleepBox in Don Mueang's international terminal (hourly rate) provides transit accommodation without leaving the airport.",
  },
];

export function BangkokLadprao() {
  return (
    <div className="rounded-2xl border border-cyan-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-cyan-700 mb-3">
        🏘️ Bangkok outer districts — Lat Phrao local life, On Nut expat suburb & Don Mueang area
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-cyan-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-cyan-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-cyan-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
