const SPOTS = [
  {
    name: "Bangkok Cosplay Scene & Anime Culture Hub",
    emoji: "🎭",
    area: "Cosplay events in Bangkok: Animate Store (Siam Square Soi 3 — Japan's largest anime retail chain in Thailand), MBK Center 6th floor (cosplay costume shops), Central World Japan Pop Culture events, Thailand Game Show (Bang Na, annual October event), J-Culture Bangkok events; cosplay community gathering at various Bangkok malls during anime season releases",
    price: "Cosplay costume (simple, local production): ฿500–3,000; Cosplay costume (high-quality, imported): ฿3,000–15,000+; Cosplay wig: ฿300–2,000; Cosplay accessories (prop weapons, armor): ฿500–10,000+; Event entry (Thailand Game Show): ฿150–350; Photography session at cosplay event: ฿500–3,000",
    why: "Bangkok is Southeast Asia's most active cosplay city — the intersection of Japan's cultural influence on Thai youth, Thailand's strong animation and manga fandom, and Bangkok's vibrant convention and event culture has created a cosplay community that rivals those in Japanese or Korean cities. Key Bangkok cosplay ecosystem elements: (1) Animate Thailand (Siam Square): the official Thai branch of Japan's Animate chain is Bangkok's cosplay headquarters — carrying figures, manga, merchandise, and cosplay supplies alongside the store's regular anime/game retail; (2) Thai cosplayer community: Thailand's cosplay community (the Thai Cosplay Association and regional clubs) is one of Asia's most active; Thai cosplayers regularly rank in international cosplay competitions including the World Cosplay Summit (WCS) where Thailand has won multiple times; (3) Thailand Game Show (TGS): Bangkok's largest gaming and pop culture convention; held annually in October/November at BitEC (Bang Na); includes dedicated cosplay competitions, Japanese game developer presence, and cosplay photographer zones; (4) J-Culture Bangkok: quarterly Japanese culture events at major Bangkok venues celebrate anime seasons and game releases with cosplay-friendly environments; (5) Character café events: Bangkok's character cafés (dedicated to specific anime or game franchises) operate on limited-time pop-up formats following Japanese model.",
    tip: "Bangkok cosplay community navigation: (1) Siam Square is cosplay central: Siam Square's pedestrianized area and surrounding malls (Siam Center, Siam Paragon, MBK) concentrate the cosplay costume retail, figure shops, and spontaneous weekend cosplay gatherings; the Siam Square area on weekend afternoons often has cosplayers visiting Animate or doing casual cosplay photoshoots; (2) Thai cosplay Facebook groups: Bangkok's cosplay community is organized through Facebook groups (search 'Thailand Cosplay' or 'Thailand Cosplay Association') which announce events, organize photoshoot sessions, and share community resources; (3) Cosplay costume sourcing: Bangkok's MBK Center has multiple floors of individual vendors selling cosplay costumes and accessories at competitive prices; quality varies significantly; (4) Photography at events: cosplay event photographers in Bangkok operate on a mutual-interest basis; most cosplayers welcome photography during events (asking permission first is standard practice); (5) WCS Thailand: the World Cosplay Summit Thailand preliminaries represent Bangkok's highest-level cosplay competition; attending WCS Thailand as a spectator provides exposure to the highest craft-level cosplay in the Bangkok scene.",
  },
  {
    name: "Bangkok Gaming Cafés & Esports Culture",
    emoji: "🎮",
    area: "Gaming cafés (net cafés) throughout Bangkok — concentrated in areas near universities (Silom, Ramkhamhaeng, Ladphrao), Siam Square, and Sukhumvit youth corridors; Esports venues: MCC Hall (Mahachak Esports), True Arena Hua Mak, True Digital Park; arcade game centers in Seacon Square, MBK, and CentralWorld",
    price: "Gaming café per hour: ฿20–50; Gaming café per day unlimited: ฿200–400; Esports event audience ticket: ฿200–800; Arcade game (per play): ฿20–50; VR gaming experience (15 min): ฿200–500; PC gaming peripherals (Bangkok price comparison to Japan): typically 10–20% cheaper for mainstream brands",
    why: "Bangkok's gaming culture bridges casual café gaming, competitive esports, and arcade culture — creating multiple engagement points for gaming enthusiasts: (1) Net café culture: Thailand's internet café (net café) tradition, while diminishing with widespread home internet, remains active near universities and in areas where youth recreation space is limited; these cafés offer modern gaming PCs, popular titles (Valorant, CS2, League of Legends, PUBG, Roblox), and social gaming environments; (2) Thai esports: Thailand has a competitive esports ecosystem; the Thai national esports team participates in SEA Games (esports became an SEA Games medal event); Bangkok hosts international esports tournaments including Valorant Pacific League matches; (3) True Arena Hua Mak: Bangkok's dedicated esports arena (8,000+ capacity) hosts major esports events; (4) Arcade culture: Japanese-style arcade centers (with UFO catcher machines, medal games, rhythm games like Dance Dance Revolution and Taiko no Tatsujin, and photo booth machines) are active in Bangkok's major malls; Japanese rhythm game culture is particularly active in Bangkok's youth gaming community; (5) Mobile gaming dominance: Thailand's most popular gaming platform is mobile; RoV (Realm of Valor — Thailand's dominant MOBA), PUBG Mobile, and Free Fire have massive Thai player bases.",
    tip: "Bangkok gaming culture access: (1) RoV Thai server: Garena's Arena of Valor (known as RoV in Thailand) is Thailand's most popular competitive game with a massive Thai-language community; playing on the Thai server gives insight into Thai gaming culture and the game's most competitive Asian server; (2) Arcade rhythm game community: Bangkok's rhythm game community (particularly DDR, IIDX, Pop'n Music, and Taiko no Tatsujin players) is tightly organized and accessible through gaming arcade Facebook and Discord communities; (3) Gaming peripheral shopping: Bangkok's Pantip Plaza (Pratunam area, IT shopping center) and the IT sections of major malls sell gaming peripherals (mice, keyboards, headsets) at prices competitive with Japan and often better than Europe/Australia for mainstream brands; (4) Esports venue seating: major esports tournaments at MCC Hall and True Arena are ticketed events; tickets sell out for significant matches (Thai team matches in regional tournaments); monitoring tournament organizer websites for Bangkok events provides advance ticket access; (5) Thai-developed games: Thailand has a growing indie game development scene; Bangkok game jams and Thai game developer community events (accessible through Game Developers Association of Thailand) provide windows into locally produced Thai game culture.",
  },
  {
    name: "Bangkok Manga, Comics & Illustration Culture",
    emoji: "📚",
    area: "Manga retail in Bangkok: Kinokuniya Thailand (Paragon, EmQuartier — Japanese and English manga); Se-Ed Bookstore chains (Thai-language manga); Naiin (Thai-language manga publisher); manga cafés scattered through Bangkok university districts; comic art education at Bangkok's fine arts universities and independent illustration schools",
    price: "Japanese manga (Thai translation, per volume): ฿80–150; Japanese manga (English import, per volume): ฿200–350; Artbook (anime/manga official): ฿500–3,000; Manga café (hourly rate): ฿40–80; Illustration course (per session): ฿500–2,000; Art supplies (at Central Art supplies stores): ฿50–5,000+",
    why: "Bangkok's manga and comics culture is the most developed in Southeast Asia — driven by the formal Thai manga publishing industry (Se-Ed, Jamsai, Siam Inter Comics), Thai-language translation of virtually all major Japanese manga titles, and an active Thai creator community producing original Thai comics (manhwa-influenced and western comic-influenced): (1) Thai manga translation industry: major Japanese manga publishers have Thai-language licensing agreements; almost every significant Japanese manga series available in Japan appears in Thai translation within months of Japanese release; (2) Thai webcomics: Thailand has a thriving original webcomic community; platforms like WEBTOON Thailand, Facebook-native comics, and Thai creator aggregators host thousands of original Thai-language comics; some Thai creators have gained international recognition; (3) Manga cafés: Thai-language manga cafés (ร้านหนังสือการ์ตูน) scattered through Bangkok's residential and university areas offer complete manga library access for hourly fees — a dying format in Japan but still active in Bangkok; (4) Thai illustration community: Bangkok's illustration community (organized through Thailand Creative & Design Center events and online communities) bridges manga influence with international illustration practice; (5) Kinokuniya Bangkok: Japanese bookstore Kinokuniya at Siam Paragon and EmQuartier stocks Japanese-language manga, artbooks, and design books imported directly from Japan — serving Bangkok's Japan-fluent manga readers.",
    tip: "Bangkok manga and comics navigation: (1) Thai manga at Se-Ed: Se-Ed Bookstore (found throughout Bangkok) is the primary retail point for Thai-language manga; the selection covers virtually all current major Japanese manga series in Thai translation at reasonable prices; (2) WEBTOON Thailand: Korea's webtoon platform has a major Thai creator and reader community; following Thai creators on WEBTOON LINE reveals Thailand's original comic creator output; (3) Bangkok Comic Con equivalent: Bangkok hosts periodic pop culture conventions (similar to Japan's Comiket but smaller scale) where independent Thai comic creators sell original doujinshi-style work and fan comics; these are announced through Thai cosplay and anime Facebook communities; (4) Digital manga services: LINE Manga Thailand (the Thai-language manga subscription service from LINE) offers access to hundreds of titles digitally; this is how many Bangkok manga readers now consume content rather than physical purchase; (5) Art supply sourcing for illustrators: Bangkok has strong art supply availability through Central Art & Craft (Central retail chain), Ji Art Supply (various Bangkok locations), and Amazon Thailand for imported professional illustration tools; prices are competitive with Singapore and better than Australia/Europe for major illustration supply brands.",
  },
];

export function BangkokCosplay() {
  return (
    <div className="rounded-2xl border border-violet-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-violet-700 mb-3">
        🎭 Bangkok otaku culture — cosplay events, gaming cafés & manga communities
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-violet-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-violet-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
