const TOPICS = [
  {
    title: "Bangkok Contemporary Art Scene — Galleries, Art Fairs & Where Thai Artists Show Work",
    emoji: "🎨",
    summary: "Bangkok has developed a substantial contemporary art ecosystem since the early 2000s: (1) The Bangkok art district geography: Bangkok's contemporary art scene is geographically diffuse rather than concentrated in a single district; major gallery clusters: River City Bangkok (art auction house and gallery complex, Si Phraya Road, riverside); Warehouse 30 (Charoenkrung Road 30, heritage warehouse converted to art/creative space, Charoenkrung area); Bangkok Art and Culture Centre (BACC, Siam area, public contemporary art museum); 100 Tonson Gallery (Langsuan area, private gallery, strong secondary market representation); NOVA Contemporary (Silom, contemporary Thai and Southeast Asian art); (2) Thailand's art market structure: Thailand has a functioning secondary market for modern and contemporary art; Thai artists selling internationally include: Natee Utarit (German gallery representation, significant European sales), Yuree Kensaku (feminist-themed contemporary work), Rirkrit Tiravanija (Thai artist, internationally one of the most significant Southeast Asian artists, often creates relational art experiences); (3) Bangkok Art Biennale (BAB): Bangkok Art Biennale has grown since its launch (2018) into one of Southeast Asia's most significant contemporary art events; the Biennale uses Bangkok's temples, historic buildings, and public spaces as exhibition sites rather than conventional white-cube spaces; this integration of contemporary art with Buddhist and royal heritage spaces is Bangkok's most distinctive curatorial approach; BAB typically occurs October–February during Bangkok's cool season; (4) Thai traditional art and contemporary practice intersection: Bangkok's contemporary art scene has a productive tension between international contemporary art practices and Thailand's extraordinarily rich traditional art tradition (lacquerwork, mural painting, temple sculpture, textile arts); the most interesting Thai contemporary artists often work within or against this traditional context; Prateep Kochabua (photorealism against Thai Buddhist and local settings), Somboon Hormtientong (Buddhist pop art), Jakkai Siributr (textiles informed by Buddhist and Thai material culture); (5) Street art and public art: Bangkok's street art scene concentrates in Charoen Krung/Yaowarat areas (Bangkok's most creative street art density), the Chula–Sam Yan area (university art school influence), and along BTS routes where commissioned public art appears; Mural Bangkok (annual mural project, Charoenkrung area) has produced large-scale permanent public artworks; the Talat Noi neighborhood's converted shophouses host numerous mural-format artworks visible from the street.",
    action: "Bangkok Art & Culture Centre (BACC): Siam Square (across from MBK, National Stadium BTS), the publicly funded contemporary art museum is free to enter the building though some exhibitions charge; check current exhibition schedule (varies); BACC rooftop book café is a Bangkok art community gathering point; Warehouse 30: Charoenkrung Road 30 (Grab recommended from Charoen Krung pier or riverside), creative complex with permanent gallery tenants and rotating exhibitions, excellent café; River City Bangkok: Si Phraya Pier, art auction house (Asian Art Auction holds regular preview exhibitions) and commercial galleries; street art walking: Talat Noi and Charoenkrung Soi 28-38 areas have the highest mural/street art density; Bangkok Art Biennale: check bangkokartbiennale.com for next edition dates (runs October–February cycle years).",
  },
  {
    title: "Bangkok Film & Cinema — Thai Cinema History, Art House Films & Where to Watch",
    emoji: "🎬",
    summary: "Thai cinema has its own rich history and Bangkok's contemporary film scene offers both Thai cinema and international art house film access: (1) Thai cinema's golden age and current scene: Thailand's film industry began in the late 1920s; the Thai film industry's most internationally significant period runs approximately 2000–2015, when directors like Apichatpong Weerasethakul (Cannes Palme d'Or for Uncle Boonmee Who Can Recall His Past Lives, 2010) brought Thai cinema to international art house prominence; Pen-Ek Ratanaruang (Last Life in the Universe), Wisit Sasanatieng (Tears of the Black Tiger), and Nonzee Nimibutr (Nang Nak) also achieved international recognition; (2) Thai mainstream cinema: mainstream Thai commercial cinema follows formulaic horror, romantic comedy, and action genres; Thai horror films (particularly Shutter, 2004) achieved international distribution and influenced global horror conventions; Thai comedy and romance productions are commercially significant domestically; the film industry finances through Thai broadcast networks (Channel 3, GMM Grammy);  (3) Documentary and independent Thai film: Bangkok hosts Bangkok Documentary Festival (BKDOC) and Silk Screen (Thai film festival focused on independent work); Bangkok's documentary filmmakers have produced internationally recognized work on Thai social issues including Tongpan (early documentary on poverty in Isaan), and more recently work by young Thai documentary filmmakers; (4) Bangkok cinema-going culture: Bangkok has multiple cinema chains: Major Cineplex (dominant chain, multiplex theaters throughout Bangkok malls), Central (mall-anchored multiplexes), SF Cinema; premium formats: IMAX at Paragon Cineplex (Siam Paragon) and Major Cineplex Central Westgate; Lido Connect (rebuilt on the former Lido Cinema Siam Square site) is the closest Bangkok has to an art house cinema in the central area; SF Cinema at various locations occasionally programs independent and art house releases; (5) Bangkok film locations for cinephiles: Bangkok itself is a frequently used film location for international productions — The Man with the Golden Gun (1974, Bond film) filmed in part in Bangkok; The Beach (2000, Leonardo DiCaprio) used Thai locations; Hangover Part II (2011) used Bangkok extensively; Bangkok-set films from Thai directors use Yaowarat, Rattanakosin, and Sukhumvit locations as recurring visual motifs; Bangkok's visual distinctiveness (canal-side buildings, temple spires, neon streets) makes it one of world cinema's most recognizable settings.",
    action: "Art house cinema in Bangkok: Lido Connect (Siam Square Soi 2, BTS Siam) shows independent and international films (check current schedule — programming changes monthly); Doc Club by Mailchimp (small screening venue, Charoenkrung area, Doc Club also distributes international films on Thai streaming); Film Archive (Thai Film Archive, Salaya, Nakhon Pathom province — outside Bangkok but accessible by bus from Southern Bus Terminal) has screening programs of restored Thai classic films; Bangkok Documentary Festival: annual event, check bkdoc.com for next edition; streaming access: Netflix Thailand has Thai film selection; iQIYI and WeTV have Thai series and films; cinema pricing: standard Bangkok multiplex ฿150–230 per ticket (฿180–350 for IMAX/premium); Major Cineplex Happy Member Thursday discounts.",
  },
  {
    title: "Bangkok Music Scene — Classical Thai Music, Live Music Venues & Indie Bangkok Bands",
    emoji: "🎵",
    summary: "Bangkok's music scene ranges from classical Thai court music to a vibrant indie scene to Bangkok's world-class classical Western music infrastructure: (1) Classical Thai music (piphat and mahori): traditional Thai classical music uses primarily wind, percussion, and string instruments not found in Western orchestras; key instruments: ranat ek (lead xylophone), khong wong yai (large gong circle), pi (oboe-like instrument), khlui (bamboo flute); traditional Thai music performances can be heard at: cultural dinner performances at tourist-oriented venues, the National Theatre Bangkok (Rajini Road, near Sanam Luang — free or low-cost classical performances during cultural events), Silpakorn University (Tha Phra Chan, near Grand Palace) which has music faculty performances; Thailand's traditional music education is maintained through university conservatories; (2) Bangkok indie and alternative music: Bangkok's independent music scene is centered around several venues: RCA (Royal City Avenue) — Bangkok's entertainment mega-block with multiple live music clubs; Thonglor/Ekkamai — concentration of intimate live music bars and venues; Fat Radio (online, broadcast but with event presence) is Bangkok's most influential indie music media; Mono music and GMM Grammy dominate mainstream; independent Thai artists cross into regional Southeast Asian recognition; (3) Bangkok jazz scene: Bangkok has an established jazz culture dating from the mid-20th century (American military presence during Vietnam War era left jazz imprint on Thai popular music); Saxophone Pub (Phayathai area, Victory Monument adjacent, operating since 1987) is Bangkok's most iconic jazz venue — eclectic, not pretentious, regular jazz and blues performances seven days a week; Brown Sugar Jazz Boutique (Sathon area); jazz-influenced Thai music blends with traditional Thai instruments create Bangkok's most original musical genre; (4) Classical Western music in Bangkok: Thailand Philharmonic Orchestra (TPO) performs at Mahidol University Music College Concert Hall (Salaya campus) and occasional Bangkok venues; Bangkok Symphony Orchestra performs at Thailand Cultural Centre (Huai Khwang MRT); Bangkok is one of Southeast Asia's strongest markets for Western classical music (significant audience from Japanese expat community, Korean expat community, and Thai upper middle class); (5) Thai pop and contemporary music: Thai pop music (luk thung, mor lam for country/folk traditions; Thai pop and T-pop for contemporary mainstream) has undergone international expansion — Thai indie bands like Slot Machine, Bodyslam, Big Ass, Potato have strong regional followings; 'T-pop' groups oriented toward K-pop-style production (4EVE, PROXIE) are increasingly targeting Southeast Asian market; Bangkok's live music calendar: weekends at Thonglor bars, rooftop venues, RCA clubs throughout the week.",
    action: "Live music access: Saxophone Pub (Victory Monument BTS area, every night) — Bangkok's most accessible regular live music, jazz/blues/funk, cover charge minimal; RCA (Royal City Avenue, Rama IX area, take Grab): weekend nights; FAT festival and other annual indie music events at Thunder Dome or Bitec exhibition halls (check current year calendar); Thonglor bar scene for intimate live music: Smalls (Thonglor Soi 10), The BKK Social Club (live music rotates), Beam (Sukhumvit 52 area, electronic music orientation); Thailand Cultural Centre (Huai Khwang MRT) for classical Western music — check Bangkok Symphony Orchestra program; traditional Thai music: National Theatre near Sanam Luang announces free performances during national holidays and cultural calendar events; check local expat event aggregators (Bangkok Events, BK Magazine events section) for current live music schedule.",
  },
];

export function BangkokModernArt() {
  return (
    <div className="rounded-2xl border border-fuchsia-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-fuchsia-700 mb-3">
        🎨 Bangkok arts & culture — contemporary art galleries, Thai cinema history & live music scene
      </h2>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-fuchsia-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-fuchsia-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
