const SPOTS = [
  {
    name: "Bangkok New Year's Eve — Countdown Celebrations, Fireworks & Where to Celebrate",
    emoji: "🎆",
    area: "Bangkok NYE major celebration zones: CentralWorld (Ratchaprasong intersection, largest free public NYE countdown in Bangkok, capacity 100,000+, annual fireworks show); Asiatique The Riverfront (Chao Phraya riverside, ticketed and free zone NYE events, fireworks over river); Iconsiam (Thonburi side, riverside NYE event with international level fireworks); Silom/Patpong area (entertainment district NYE); Khao San Road (backpacker NYE, free street party, very crowded, international traveler concentration); hotel rooftop NYE parties: Lebua State Tower, Vertigo Banyan Tree, Above 11, Sky Bar Sirocco — all with premium pricing; Bangkok restaurants: many Bangkok restaurants offer special NYE dinner menus; Chinatown Yaowarat: unique NYE atmosphere from the Chinese-Thai community",
    price: "CentralWorld public NYE countdown: free (public space); Iconsiam NYE event: free (riverside public area) + premium ticketed sections; Bangkok rooftop bar NYE packages: ฿3,000–15,000 per person including drinks; hotel NYE gala dinner: ฿3,000–10,000+ per person; budget NYE Bangkok: Khao San Road street party is free; 7-Eleven champagne (Moët & Chandon split): ฿350–450; Thai domestic beer 7-Eleven: ฿60–70; Grab surge pricing NYE midnight: expect 2–5x standard rates; BTS Skytrain NYE extended service: typically runs until 2am on December 31",
    why: "Bangkok's New Year's Eve is one of Southeast Asia's most celebrated countdown events with distinct options at different budget and atmosphere levels: (1) CentralWorld countdown's scale: Bangkok's central NYE event at CentralWorld (Ratchaprasong intersection, the nexus of Sukhumvit and Rama I Road) draws 100,000+ people annually; the free public countdown with professional fireworks show and live entertainment is comparable to major global NYE events; the scale creates crowd management challenges — arriving before 8pm is necessary to secure a reasonable viewing position; (2) Bangkok's international NYE character: Bangkok's NYE crowd is uniquely international; the mix of European backpackers, Japanese and Korean tourists, Middle Eastern visitors, Chinese tourists, and Thai celebrants creates a genuinely cosmopolitan atmosphere unlike any single-nationality-dominant event; (3) Rooftop bar NYE experience stratification: Bangkok's rooftop bar NYE scene has clear stratification — ultra-premium (Lebua Sky Bar's Galaxy Ball at ฿10,000–15,000+ per person), premium (most Sukhumvit rooftop bars at ฿3,000–8,000), and accessible (Above-11, Nest Bar at ฿2,000–4,000 with drinks included); all provide skyline views with varying degrees of firework visibility; (4) Khao San Road's backpacker NYE tradition: Khao San Road NYE is Bangkok's longest-running international backpacker gathering; the street closes to vehicle traffic, DJ stages set up along the road, and 100,000+ international travelers fill the area; alcohol is freely sold from street vendors; the atmosphere is high-energy but significantly less refined than rooftop alternatives; (5) Transport logistics NYE midnight: Bangkok's midnight transport situation is one of the biggest NYE planning considerations; BTS typically extends to 2am; Grab and taxi surge pricing (3–5x normal rates) means pre-booking return transport or planning walking routes from Silom/Sukhumvit accommodation to venues is the best strategy.",
    tip: "Bangkok NYE practical planning: (1) Crowd safety at CentralWorld: Bangkok's CentralWorld NYE has had crowd crush incidents in the past; maintain awareness of crowd density, identify exit routes before crowds peak, and stay with your group; the perimeter of the CentralWorld event area has better circulation than the central zone directly in front of the stage; (2) NYE accommodation booking: Bangkok hotels and hostels typically add NYE surcharges (50–200% premium) to December 31 bookings; booking well in advance (2–3 months) secures better rates and availability; popular party hostels (Lub d Bangkok, HQ Hostel near Khao San) fill months in advance for NYE; (3) Dress code for Bangkok NYE venues: Bangkok's premium NYE events at rooftop bars and hotel gala dinners typically have smart-casual to formal dress codes; confirm dress requirements before purchasing tickets; Khao San Road NYE is fully casual; (4) Firework viewing positions: Bangkok's NYE fireworks launch from multiple locations (CentralWorld complex, Iconsiam riverside, Asiatique); firework photography works best from distances of 200–500 meters with wide-angle lenses; the Taksin Bridge and riverside areas provide firework viewing with river reflections for Iconsiam's show; (5) Bangkok NYE vs. Chiang Mai: visitors considering Thailand NYE celebrations should note that Chiang Mai's Yi Peng Lantern Festival (which sometimes coincides with NYE depending on lunar calendar) involves thousands of paper lanterns released simultaneously — a visually spectacular and distinctly Thai alternative to Bangkok's countdown events; the lantern festival's lunar timing (not fixed to December 31) means NYE and Yi Peng sometimes coincide and sometimes do not.",
  },
  {
    name: "Bangkok Chinese New Year — Yaowarat Celebrations, Lion Dances & Thai-Chinese Culture",
    emoji: "🧧",
    area: "Bangkok Chinese New Year center: Yaowarat Road (Chinatown), Bangkok's largest and most elaborate Chinese New Year celebration; secondary celebrations: Samphanthawong district, Bang Rak area, throughout Bangkok's Chinese-Thai community neighborhoods; Chinese shrines citywide: Leng Buia Ia shrine (Yaowarat), Santichon Shrine (Chinatown), Chinese clan associations (Teochew, Hakka, Cantonese associations all hold NYY events); shopping mall CNY decorations: major Bangkok malls begin Chinese New Year decorations 2 weeks before the holiday; Iconsiam CNY events (targeting Chinese tourists); CentralWorld CNY; Bangkok's best lion dance performances: Yaowarat Road continuous performances on CNY eve and day 1; Wat Mangkon Kamalawat (Yaowarat's largest Buddhist temple, strong Chinese character)",
    price: "Yaowarat Chinese New Year celebration: free (public street); lion dance performances: free to observe; temple visits: free (donations welcome); limited edition CNY products at major Bangkok brands: premiums apply; Bangkok hotel CNY dining (set menus for family reunion dinner): ฿2,000–8,000/person; yee sang (prosperity salad toss, Malaysian-Singaporean Chinese tradition, also found in Bangkok): ฿800–2,000 at restaurants offering CNY menus; special CNY desserts and pastries at Yaowarat bakeries: ฿50–300",
    why: "Chinese New Year is Bangkok's most spectacular annual festival with genuine cultural depth reflecting Thailand's Chinese-Thai heritage: (1) Thailand's Chinese-Thai population: approximately 14–15% of Thailand's population is ethnically Chinese or part-Chinese; Bangkok has the highest concentration, with significant Chinese-Thai communities in Yaowarat, Samphanthawong, Bangrak, and throughout business communities across the city; the political, business, and cultural elite of Thailand includes a substantial Chinese-Thai component; (2) Yaowarat CNY's authenticity: Bangkok's Chinatown CNY celebration is one of Asia's most genuine and accessible Chinese New Year festivals; unlike many Chinatown CNY events in Western cities (which are community-organized in diaspora contexts), Yaowarat's celebration is a living community event where Thai-Chinese families come specifically to worship at ancestral shrines, perform merit-making, and join family reunion dinners; the experience is genuine rather than performed for tourist benefit; (3) Thai royal family participation: the Thai royal family traditionally visits Yaowarat during Chinese New Year, a practice reflecting both the Chinese-Thai heritage of the royal family (the Chakri dynasty has Chinese royal lineage) and the political symbolism of royal recognition of the Chinese-Thai community; royal visits create security perimeters and advance timing uncertainty — checking news before visiting on specific days; (4) Bangkok's 9 days vs. 1 day Chinese New Year: Chinese New Year celebrations in Bangkok extend across multiple days; the most intense are the eve (reunion dinner night), day 1 (lion dance performances, temple visits), and day 15 (Lantern Festival/Chap Goh Mei closing of CNY season); visiting Yaowarat across multiple CNY days provides different experiences; (5) Bangkok's CNY food culture: Chinese New Year food in Bangkok involves specific symbolic dishes — long noodles (longevity), whole fish (surplus), steamed glutinous rice cakes (nian gao, year improvement), turnip cake (lo bak gao), and the reunion dinner as family gathering ritual; Yaowarat's restaurants are full during CNY and advance booking is essential for family reunion dinner seats at established Chinese restaurants.",
    tip: "Bangkok Chinese New Year visit planning: (1) Best CNY timing in Yaowarat: the CNY celebration peaks on the eve night (family reunion dinner rush, 6–10pm, restaurants absolutely packed) and day 1 morning (temple worship, lion dance performances starting at 9am); arriving in Yaowarat on the afternoon of CNY day 1 (after the morning temple rush subsides, 2–5pm) provides good lion dance viewing, festival atmosphere, and slightly manageable crowds; (2) Yaowarat road navigation CNY: Yaowarat Road closes to vehicle traffic during major CNY celebrations; BTS Hua Lamphong is the nearest station (then taxi or walk to Yaowarat area); the Chao Phraya express boat (River City or Oriental Pier) also connects nearby; (3) Photography of lion dances: Bangkok's CNY lion dance performances (typically performed by Teochew or Cantonese lion dance troupes hired by businesses to bring good luck) are highly photogenic; the drums, cymbals, and firecrackers are loud — prepare for the sound; the lion dance route through Yaowarat's narrow sois provides close-range photography opportunities; (4) Chinese New Year date calculation: Chinese New Year date changes annually (based on the lunisolar calendar, typically falling January–February); booking flights and accommodation well in advance for CNY is essential as Bangkok hotels near Yaowarat fill quickly; some years multiple public holidays cluster around CNY creating longer Bangkok celebration periods; (5) CNY red envelope etiquette: the ang pau (red envelope) tradition (monetary gift in red envelope, symbolizing good luck) is observed in Bangkok's Chinese-Thai community; visitors to Chinese-Thai friends' homes during CNY may receive ang pau from elders; reciprocating with a small ang pau from visitors is not expected but always welcomed.",
  },
  {
    name: "Bangkok Songkran & Thai New Year — Water Festival, Tradition & Modern Celebration",
    emoji: "💦",
    area: "Bangkok Songkran major water zones: Khao San Road (most intense tourist water fights, continuous 13–15 April); Silom Road (closed to traffic, water fight zone, popular with Thai-LGBTQ community and international tourists); Rattanakosin area (Grand Palace, traditional Songkran ceremonies alongside water); Sukhumvit Soi 11 area (international community water gathering); Thong Lo area (Thai-millennial, cocktail-venue adjacent, more controlled water atmosphere); Asiatique (riverside Songkran festival, fireworks at night); traditional Songkran: Wat Pho, Wat Phra Kaew area for religious ceremonies and Buddha image bathing; Chiang Mai (additional option 8-hour bus from Bangkok, considered more 'traditional' but very crowded in recent years)",
    price: "Songkran public water fight: free entry to water fight streets; water guns (กระบอกฉีดน้ำ) at 7-Eleven and convenience stores: ฿30–200 depending on size; water storage bucket: ฿20–60; waterproof bag or phone case: essential, ฿100–300; Songkran party events (Silom stage events, venue parties): free (public street) to ฿500–2,000 for venue entry; Songkran hotel accommodation surge: Bangkok hotels add Songkran premiums of 50–150%; booking weeks in advance is essential; white powder (talc, used in water fights alongside water): sold at street stalls ฿10–30",
    why: "Songkran (Thai New Year, April 13–15, some years extended) is Bangkok's most globally recognized festival and the world's largest annual water fight: (1) Songkran's dual character: Songkran (สงกรานต์, derived from Sanskrit Sankranti, solar new year transition) has two simultaneous faces — the traditional face of family reunions, temple merit-making, elder respect rituals, and Buddha image washing; and the modern face of Bangkok's water fight street parties, which have grown into one of Southeast Asia's largest annual tourist events; (2) The traditional Songkran significance: the core Songkran rituals involve: washing Buddha images with scented water (rod nam phra) to 'welcome the new year'; offering water blessings to elders (the gently pouring water on their hands, not throwing it); building sand pagodas at temples (to 'return sand' to the temple grounds, replacing sand carried out on devotees' shoes throughout the year); releasing fish and birds as merit-making; these traditions occur at Bangkok's temples simultaneously with the water fights; (3) Bangkok's water fight evolution: Bangkok's Songkran water fights have evolved from neighborhood bucket throwing to organized street events with DJs, foam parties, and international tourist participation; Silom Road and Khao San Road close to vehicle traffic and become pedestrian water fight zones for 3–5 days; the tourist impact has been significant — Songkran is now the single largest annual event for Bangkok tourism, matching global New Year's celebrations; (4) Songkran 2025+ and crowd safety: Songkran crowd incidents have historically included electrocution risk (from water and exposed wiring), traffic accidents, and excessive alcohol-related incidents; Bangkok authorities have increasingly tightened safety measures; the celebration remains spirited but infrastructure has improved; (5) Songkran timing and weather: April 13–15 falls in Bangkok's hottest month (April peak heat, 38–40°C); the Songkran water fight provides genuine relief from the heat; traditional logic: the water throwing represents washing away the old year and cooling the hottest period; the monsoon has not yet arrived in April, so Songkran water fights happen under sunny blue skies.",
    tip: "Bangkok Songkran practical guide: (1) Waterproof everything: Songkran participation requires accepting that everything will be completely wet; strategy — use a waterproof phone case or bag (non-negotiable), carry minimal cash in a waterproof wallet, wear quick-dry clothing (not cotton, which stays wet), wear sandals or closed-toe water shoes (broken glass on some streets), secure glasses with a strap; (2) The powder (นวล) protocol: white talcum powder is used at Songkran to apply cooling, fragrant designs on faces and arms as a blessing gesture; its application should be gentle and welcomed rather than forced; refusing powder application from strangers is acceptable; some participants dislike powder on their faces (eye and lung irritation) and can indicate this; (3) Camera and electronics protection: DSLR and mirrorless cameras are fully incompatible with Bangkok's open water fight zones; using a smartphone in a waterproof case, waterproof action camera (GoPro), or simply not bringing electronics to the water fight zone protects equipment; Bangkok has many camera repair shops but water damage is often irreparable; (4) Traditional vs. water fight locations: visitors seeking the traditional Songkran experience should visit Bangkok's temples (Wat Pho, Wat Benchamabophit) in the morning hours (7–11am) before the water fight zones reach peak activity; the overlap of traditional ceremony and water celebration at some temple locations creates an authentic dual-experience; (5) Songkran road safety: Bangkok's traffic accident rate increases significantly during Songkran due to drunk driving (beer and whiskey are part of Songkran celebration culture); using BTS Skytrain, MRT, or Grab (less surge than NYE but still elevated) for transport to and from water fight zones avoids drunk-driving exposure; pickup truck bed transport (common in provincial Songkran) is illegal in Bangkok but remains an accident risk in outer districts.",
  },
];

export function BangkokNewYear() {
  return (
    <div className="rounded-2xl border border-red-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-red-700 mb-3">
        🎆 Bangkok annual celebrations — New Year's Eve, Chinese New Year & Songkran water festival
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-red-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-red-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-red-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
