const SPOTS = [
  {
    name: "Bangkok Thai Herbal Medicine — Traditional Medicine Shops, Ya Dong & TCM",
    emoji: "🌿",
    area: "Bangkok Thai herbal medicine locations: Yaowarat Chinatown (highest concentration of traditional Chinese medicine (TCM) shops, herbal pharmacies, and dried ingredients; Hualamphong MRT or Sam Yot MRT); Pak Khlong Talat market area (fresh herbs in addition to flowers); Or Tor Kor Market (high-quality fresh herbs and specialty Thai ingredients, Mo Chit BTS); Banglamphu area near Khao San (traditional Thai pharmacies); Tha Prachan area near Thammasat University (traditional remedy sellers near the pier); traditional ya dong carts (herbal liquor shots) throughout Bangkok's older markets; Ya Dong sellers in Pak Klong Talat and Chatuchak Weekend Market area",
    price: "Bangkok traditional herbal medicine cost indicators: Traditional Thai massage + herbal compress: ฿400–800 per session (herbal compress additional ฿100–200 over standard massage); herbal steam sauna (at Wat Pho's Traditional Medical School): ฿200–400; ya dong (herbal spirit shot at market stands): ฿30–50 per shot; Chinese herbal medicine consultation at Yaowarat pharmacy: ฿200–1,500 depending on complexity and prescription; dried herbs at Yaowarat: varies widely by herb — common ones ฿50–300 per 100g; Thai herbal tea sachets (commercial, supermarket): ฿60–200 for packaged sets; traditional herbal balm (tiger balm Thai equivalent brands, Ya Dom smelling salts, White Flower oil): ฿50–200 at any pharmacy",
    why: "Bangkok's traditional herbal medicine system operates at the intersection of Thai and Chinese medical traditions, representing a significant parallel healthcare system: (1) Two herbal traditions in Bangkok: Bangkok operates with two distinct but overlapping herbal medicine traditions — Thai traditional medicine (nuad thai, ya thai, TTM — based on Buddhist and Ayurvedic influences, using locally sourced herbs) and Traditional Chinese Medicine (TCM — brought by Bangkok's Thai-Chinese community, using Chinese herbs and diagnostic frameworks); the two traditions coexist and are sometimes combined; (2) Yaowarat's herbal pharmacy ecology: Bangkok's Chinatown (Yaowarat) has the highest concentration of traditional Chinese herbal pharmacies in Thailand; these shops carry dried Chinese herbs (some imported, some Thai-grown), prepared patent medicines, ginseng, cordyceps, dong quai, and other TCM ingredients; consultations with trained Chinese herbalists are available at established Yaowarat pharmacies; the shops serve the local Thai-Chinese population as well as visitors; (3) Wat Pho as traditional medicine center: Wat Pho (Wat Phra Chetuphon) is not only a famous Buddhist temple but the historical center of Thai traditional medicine and Nuad Thai (Thai massage) codification; the Wat Pho Traditional Medical School (within the temple grounds) offers courses in Thai massage, Thai traditional medicine, and herbal treatment; the school's clinic offers herbal steam (ya steam) and traditional herbal compress (luk pra kob) treatments; (4) Ya dong culture — Bangkok's herbal street shots: ya dong (หย่าดอง, herbal spirits) are a Bangkok working-class health tradition — vendors at market carts prepare herbal-infused rice liquor mixtures claimed to have tonic properties (energy, blood building, sexual vitality); the combination of alcohol, exotic herbs, and claimed health benefits makes ya dong stands cultural attractions as much as health products; sold at small cups ฿30–50; a Bangkok food and culture experience; (5) Thai traditional medicine integration with modern care: Thailand's Ministry of Public Health formally recognizes Thai Traditional Medicine alongside Western medicine; Thai government hospitals have Thai Traditional Medicine departments; integrated care (Western diagnosis + traditional treatment) is commonly practiced by Thai patients; Bumrungrad and Bangkok Hospital networks have integrated wellness and traditional medicine services.",
    tip: "Bangkok herbal medicine practical guide: (1) Wat Pho herbal steam and compress: the Wat Pho Thai Traditional Medical School clinic (entrance from within Wat Pho complex) provides herbal compress massage (luk pra kob) — a heated cloth bundle of Thai herbs applied to muscles — and herbal steam rooms; this is among Bangkok's most authentic traditional medicine experiences; book in advance for specific treatments; (2) Ya dong safety context: ya dong stands in Bangkok markets are the cultural experience, not a primary healthcare strategy; the herbal spirits provide no clinically validated health benefits; trying ya dong at a busy Bangkok market (observing the vendor, checking the carts' hygiene) is a cultural Bangkok experience; (3) Buying Thai herbal products at pharmacies: Thai pharmacies (Boots Thailand, Watson's Thailand, independent pharmacies) carry standardized Thai herbal products — ya dom inhalers (Thai inhaler smelling salts — iconic palm-sized cylinders used by Thais to combat nausea and dizziness), Tiger Balm variants, Counterpain cream (local equivalent of Bengay/Voltaren), and various Thai herbal preparations as gifts or personal use items; (4) Ya dom — Bangkok's essential herbal item: ya dom (ยาดม) are Thai herbal inhalers — small tubes filled with herbs (usually menthol, camphor, peppermint, borneol combination) used by Thais constantly for dizziness, nausea, headache, smell management; they are the most ubiquitous Bangkok Thai herbal product and make excellent practical souvenirs; brands: PUTTHARAKSA brand (original), Po air ya dom; price: ฿30–80 at any 7-Eleven or pharmacy; (5) Consulting Bangkok TCM practitioners: for genuine traditional Chinese medicine consultations in Bangkok, Yaowarat pharmacies with in-house practitioners provide authentic consultation; most communicate in Thai and Chinese with limited English; Google Translate camera function or a Thai-speaking companion facilitates consultation; the quality of TCM advice varies by practitioner experience — established multi-generation Yaowarat pharmacies generally have higher practitioner quality.",
  },
  {
    name: "Bangkok Spa & Wellness — Luxury Spa Experiences, Thermal Facilities & Body Treatments",
    emoji: "🛁",
    area: "Bangkok luxury spa locations: major hotel spas (Mandarin Oriental's The Oriental Spa — Bangkok's most prestigious spa property; Banyan Tree Spa — 57th floor, skyline views; COMO Shambhala at COMO Metropolitan; The Peninsula Spa; Anantara Riverside Bangkok Resort Spa; Capella Bangkok's Auriga Spa); standalone destination spas: Divana Signature Spa (Sukhumvit Soi 25, garden environment, award-winning); Devarana Spa (within Dusit Thani area); HARNN Heritage Spa (multiple Bangkok locations, Thai botanical products); Oasis Spa (multiple Bangkok locations, mid-range quality/price); mid-tier: Let's Relax (multiple locations, reliable chain), Health Land (Asok and other locations, traditional focus)",
    price: "Bangkok spa pricing tiers: budget traditional Thai massage: ฿200–400/hour (street-level shops, variable quality); mid-tier wellness spa: ฿800–2,000 for 60-90 minute treatment (Let's Relax, Health Land, Oasis); boutique destination spa: ฿2,000–5,000 for 60-120 minute signature treatment (Divana, HARNN, Devarana); hotel spa flagship: ฿3,500–12,000 per treatment (Oriental Spa, Banyan Tree Spa); full-day spa packages: ฿5,000–20,000 at premium properties including meal, multiple treatments, facility use; Thai herbal steam add-on: ฿200–500 typically; couple's room availability: most mid-to-premium spas have double-treatment rooms",
    why: "Bangkok's spa industry has evolved into a globally recognized wellness destination with specific strengths: (1) Bangkok's spa price-quality positioning: Bangkok's mid-tier destination spa category (฿1,000–3,000 per treatment) offers quality that rivals or exceeds Western $200–400 treatments; the combination of Thai massage tradition, skilled therapists trained in certified programs, high-quality imported product lines, and competitive labor costs creates exceptional value at the mid-tier level; (2) Thai herbal compress differentiation: the distinctive Bangkok spa treatment is the luk pra kob (Thai herbal compress) — a heated muslin bundle filled with Thai herbs (camphor, lemongrass, kaffir lime, galangal, prai herb) applied to the body after massage; the treatment combines the physical effects of heat therapy with the aromatic and pharmacological properties of Thai herbs; this treatment is specifically Thai and unavailable authentically elsewhere; (3) Thai massage technique distinction: Thai massage (nuad thai) is fundamentally different from Swedish or sports massage — it involves no oil, is done through clothing or loose garments, uses point pressure (sen energy lines concept), and incorporates stretching (yoga-like positions applied by the therapist); a 2-hour traditional Thai massage at a quality Bangkok spa is among Thailand's most culturally authentic and physically beneficial wellness experiences; (4) Bangkok spa facility standards at premium level: Bangkok's hotel spas and premium standalone spas typically offer: dedicated consultation at intake, temperature-controlled environments, pre-treatment steam or sauna, foot ritual before treatment, post-treatment tea/refreshments, and therapists with certified training (Traditional Thai Massage certification programs, hotel spa training standards); (5) Finding quality vs. tourist trap massage shops: the Bangkok massage shop quality spectrum is wide; indicators of quality: pre-treatment consultation, clean treatment rooms (not curtained off sections of shops), uniform-wearing licensed therapists, no pressure for add-ons, professional intake process; red flags: price negotiation at door, immediately available without appointment, pressure sales.",
    tip: "Bangkok spa practical guidance: (1) Divana Signature Spa for independent destination spa: Divana Spa (Sukhumvit Soi 25 location — the main original branch) provides Mandarin Oriental-quality ambiance at significantly lower prices; the private sala-style treatment rooms in a garden setting, coupled with Divana's proprietary Thai botanical product line, create one of Bangkok's best independent spa experiences; booking at least 2 days ahead recommended for weekends; (2) Health Land for traditional value: Health Land (Asok Sukhumvit location most convenient) is Bangkok's most reliable mid-tier traditional Thai massage chain — consistently trained therapists, clean facilities, no tourist price discrimination; 2-hour traditional Thai massage ฿600–700; booking by phone or walk-in; (3) Pre-booking hotel spa for couples: Bangkok hotel spas release promotional spa packages that include couple's treatment room, meal credit, and checkout spa facility use; booking directly with hotel spa team (not through third-party apps) sometimes unlocks unpublished packages; (4) Tipping at Bangkok spas: tipping is expected at Bangkok spas and is the primary earnings supplement for therapists; 10–20% of treatment price is standard (฿100–200 for mid-tier, ฿200–500 for premium); tipping envelope provided at end of treatment or cash left with therapist directly; (5) Timing for Bangkok spa visits: Bangkok spas are quietest on weekday mornings (10am–12pm); busiest Friday–Sunday evenings (after 5pm); hotel spas specifically busiest during check-in/out days (Saturday) and quietest Tuesday–Wednesday; booking ahead for weekend times is essential at popular spas.",
  },
  {
    name: "Bangkok Muay Thai Training — Gyms for Tourists, Classes for Beginners & Fight Camps",
    emoji: "🥊",
    area: "Bangkok Muay Thai gyms (tourist/visitor-friendly): Muay Thai Institute (Rangsit, north Bangkok, closest to official training), Lanna Muay Thai (Silom area, central Bangkok, popular with foreigners), Core Muay Thai (Khao San Road area, backpacker-friendly), Sitsongpeenong (Din Daeng area, established camp), Kaewsamrit Muay Thai (Ari area, established traditional camp), YOKKAO Training Center (Sukhumvit area, modern gym, Bangkok-centric), Fairtex Muay Thai (Sukhumvit Soi 50, gym + shop); fight viewing: Rajadamnern Stadium (Ratchadamnoen Nok Avenue, Mon/Wed/Thu nights, most authentic, some English instructions), Lumpini Boxing Stadium (new location in Ram Intra, Bangkok north, Tue/Fri/Sat nights), IMPACT Arena (international fight cards occasionally)",
    price: "Bangkok Muay Thai training pricing: drop-in class (foreigner-friendly gyms): ฿500–800 per session; weekly training package (traditional gym, 2 sessions/day): ฿3,000–6,000/week; monthly training package (serious training): ฿8,000–20,000/month; personal trainer session: ฿800–2,000 per hour; Rajadamnern fight ticket: ringside ฿2,000–3,000, standard ฿1,200–1,500 (foreigner price, includes free drink at some shows); Lumpini Stadium ticket: similar pricing; one-day/single class Muay Thai: many Bangkok tourist-oriented gyms offer 1.5–2 hour beginner class with gloves provided ฿400–700",
    why: "Muay Thai occupies a unique position as Bangkok's both culturally significant sport and accessible tourist activity: (1) Muay Thai's cultural importance: Muay Thai (Thai Boxing) is Thailand's national sport and a form of cultural heritage; it is practiced as both a martial art and competitive sport; Thailand has an active professional Muay Thai circuit with regular fights at Bangkok's main stadiums; the ritual elements (Wai Kru Ram Muay pre-fight ceremony honoring teachers) add cultural significance beyond sport; (2) Bangkok's accessible training infrastructure: Bangkok has the world's most developed Muay Thai training infrastructure; dozens of gyms across the city range from traditional Thai camps (training Thai fighters alongside tourists) to tourist-focused modern gyms (English-speaking trainers, beginner-friendly curriculum, air-conditioned); both types offer value for different objectives; (3) Traditional gym vs. tourist gym distinction: traditional Bangkok Muay Thai camps (Kaewsamrit, Sitsongpeenong, and similar) train actual Thai professional fighters; tourists train alongside them at lower intensity; these camps offer authentic immersion but less English support and more intense training culture; tourist-oriented gyms (Lanna, YOKKAO, Core) provide English instruction, structured beginner curriculum, and lower-intensity pace appropriate for fitness tourists; (4) Single session vs. fight camp: the Bangkok Muay Thai spectrum ranges from a single 90-minute beginner session (experience the sport, learn basic technique, appropriate fitness) to full fight camps (3–6 months, 2 sessions daily, preparation for professional or amateur fight); most tourists engage at the single-session to one-week end of this spectrum; the fight camp end serves serious martial arts students; (5) Watching authentic Muay Thai at Rajadamnern: the Rajadamnern Stadium (1945, Bangkok's oldest boxing stadium) hosts authentic professional Thai fights on specific evenings; the crowd is primarily Thai gamblers and fight fans; the ringside betting culture (hand signals indicating bets between the crowd), the traditional music (sarama — a specific Muay Thai musical accompaniment), and the fight skill on display are genuinely different from tourist fight shows; attending a real stadium fight is recommended as Bangkok's most authentic sport-cultural experience.",
    tip: "Bangkok Muay Thai practical guide: (1) For beginners: the most important consideration is choosing a gym where English-speaking instruction is available; gyms like Core Muay Thai (near Khao San), Lanna Muay Thai (Silom), or YOKKAO Training Center (Sukhumvit) provide beginner-appropriate English instruction; show up in shorts and a t-shirt, all equipment is provided for first sessions; (2) Attending Rajadamnern vs. Lumpini: Rajadamnern is in central Bangkok (Ratchadamnoen Avenue near Democracy Monument, accessible by taxi from Khao San ฿60–100); Lumpini Boxing Stadium is now in Ram Intra (northern Bangkok, less convenient); Rajadamnern is the recommended first stadium fight experience for Bangkok visitors due to central location; buy tickets at the stadium door (no advance booking required for standard seats, ringside can be booked via LINE); (3) What to expect at a stadium fight: a typical Rajadamnern night has 8–10 fights across different weight classes; fights typically go full 5 rounds unless knockout or stoppage; the early fights (6–7pm) feature younger/less experienced fighters; the main event fights (9pm onwards) feature top-ranked Thai fighters; arriving at 7pm catches a full evening of fights; (4) Photography at Rajadamnern: camera policies vary — standard cameras allowed from seated positions; flash photography discouraged; the action is fast so burst mode and fast shutter speed improve fight photography results; ringside seats provide best photography angles but maximum crowd noise and betting activity; (5) Muay Thai shorts as Bangkok souvenirs: traditional Thai Muay Thai shorts (bright colors, embroidered designs) are iconic Bangkok souvenirs; Chatuchak Weekend Market, Fairtex brand shops, and Yokkao shops in Sukhumvit carry authentic Thai Muay Thai shorts; price: ฿300–600 for standard quality; ฿800–2,000 for premium embroidered cotton.",
  },
];

export function BangkokHerbal() {
  return (
    <div className="rounded-2xl border border-green-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-green-700 mb-3">
        🌿 Bangkok wellness deep dive — herbal medicine & TCM, luxury spa guide & Muay Thai training
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-green-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-green-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
