const TOPICS = [
  {
    title: "Thai Laws Visitors Must Know — Drug Laws, Public Behavior Rules & Cultural Legal Obligations",
    emoji: "⚖️",
    summary: "Thailand's legal system imposes obligations and prohibitions on visitors that are significantly more serious than in many Western countries: (1) Drug laws — Thailand's most serious visitor legal risk: Thailand has extremely severe drug penalties; possession of small amounts of recreational drugs (including amounts typical for personal use in countries where substances are decriminalized) can result in imprisonment; Thailand maintains the death penalty for drug trafficking (though in practice, life imprisonment is more common for foreigners in trafficking cases); Bangkok has active nightlife drug culture in tourist areas but this is managed through periodic police raids; foreign embassies consistently warn their citizens about the severity of Thai drug laws; if offered drugs in Bangkok, the offer may come from police informants working for fines/commissions; (2) Lèse-majesté (Section 112 CPC) — royal family criticism: Thailand's lèse-majesté law makes any insult, defamation, or threat to the King, Queen, Heir Apparent, or Regent a criminal offense punishable by 3–15 years imprisonment per offense; this law applies to foreigners in Thailand; social media posts critical of the royal family (even made in Thailand on foreign accounts) have resulted in foreign prosecution; destroying currency (which bears the King's image) can theoretically be prosecuted under this law; (3) Public behavior laws: nudity in public (including beaches, temples) is illegal; urinating in public is illegal; taking Buddha images out of Thailand without a permit is restricted (large images, antiques); Buddha tattoos on feet or used disrespectfully are culturally offensive but not always legally actionable; temple dress codes (covering shoulders and knees) are enforced at major temples; gambling is illegal in Thailand except at licensed venues (horse racing at Royal Turf Club, government lottery, some card games); engaging in illegal gambling can result in arrest; (4) E-cigarette and vaping laws: electronic cigarettes and vaping devices are illegal in Thailand (banned under Consumer Protection Board regulations) — possession can result in fine or imprisonment; this is actively enforced at Thai airports and is a common reason for confiscation from visitors; (5) Professional services protection: taking employment in Thailand without a valid work permit (including digital nomad work in Thailand) is technically illegal under Thai labor law; 'education visas' (tourist ED visas obtained through language schools) used for long-term residence while working remotely exist in a gray area; Thailand is developing a Long-Term Resident (LTR) Visa for remote workers that provides legal status for this activity.",
    action: "Bangkok legal compliance checklist: (1) Research current drug law status before arrival — Thai law changes; check your country's embassy travel advisory for current enforcement emphasis; never carry or use recreational drugs in Thailand; (2) Royal family: positive or neutral treatment of royal family topics only; do not make, share, or engage with negative royal content on social media while in Thailand; (3) Vaping: do not bring electronic cigarettes to Thailand; the airport customs (both arrival and departure) actively confiscates these; disposable e-cigarettes carried in luggage are confiscated; (4) Buddha images: purchasing Buddha images for respectful home display is generally acceptable; Department of Fine Arts permits are required for antique Buddha images over 100 years old; major retailers (airport shops, licensed tourist vendors) handle permit documentation; (5) If arrested in Bangkok: immediately request to contact your country's embassy (embassy consular access is a right under the Vienna Convention; Thai police are required to allow this contact); do not sign any documents without translation assistance; embassies cannot get you out of legal trouble but can provide consular support and recommend lawyers; Bangkok lawyer referrals available through most embassies.",
  },
  {
    title: "Bangkok Traffic Law & Motorcycle Safety — Road Rules, Accidents & Insurance Reality",
    emoji: "🏍️",
    summary: "Bangkok road safety and traffic law is significantly more complex for visitors than airport pamphlets suggest: (1) Bangkok traffic fatality context: Thailand has one of the world's highest road traffic fatality rates per capita (approximately 22,000 deaths per year nationally); Bangkok roads are dangerous by international standards; motorcycle accidents account for the largest share of traffic fatalities; tourist motorcycle accidents are a significant source of serious visitor injury; (2) Motorcycle rental on Koh Samui/other Thai destinations vs. Bangkok: renting and riding a motorcycle in Bangkok is not recommended for visitors unfamiliar with Bangkok traffic; Bangkok's traffic density, road switching, and local driving culture (yielding hierarchy different from Western conventions) creates high accident risk for untrained riders; in contrast, rental motorcycles on quieter Thai island destinations (Koh Samui, Phuket Beach roads) are common but still accident-prone; (3) Thai traffic driving conventions: Thai traffic drives on the LEFT (same as UK, Australia); red lights are treated more as guidelines than absolute rules by motorcycles and some vehicles; u-turns at dedicated u-turn points (common on major Bangkok roads) are part of standard routing; songthaew and bus lane entitlement is observed selectively; road priority in practice follows vehicle size (larger vehicle typically yields last, not first); giving way to entering traffic is uncommon; (4) Traffic fines and police stops: foreigners in Thailand can be stopped and fined for traffic violations; traffic police tend to be stationed near major intersections during campaign periods; standard fines for visible violations (running red light, wrong-way entry, no helmet, lack of license): ฿200–2,000; 'on-the-spot' fine payments to traffic police are common (controversial but widespread); if stopped as a foreigner without a valid license for the vehicle type being operated, fines can be significantly higher; (5) Travel insurance and accident coverage: Thailand's compulsory third-party vehicle insurance (Por Ror Bor) provides minimal coverage; tourist rental agreement insurance coverage typically has strict limitations; many visitor travel insurance policies have exclusions for motorcycle accidents when no valid motorcycle license is held in the home country; check your travel insurance coverage terms carefully before renting any vehicle; comprehensive Thai vehicle insurance is available but usually not provided for tourist rentals without additional cost.",
    action: "Bangkok road safety for visitors: (1) Don't rent a motorcycle in Bangkok specifically — Grab and taxi are the appropriate Bangkok transportation; if motorcycling in resort areas, wear a helmet at all times (legal requirement, ฿400 fine without, and genuinely protective); (2) Seatbelts: mandatory in front seats, strongly recommended in rear (Thai taxis typically have functioning rear seatbelts); (3) Crossing Bangkok streets: Bangkok's roads can be crossed at marked crosswalks (traffic typically slows for pedestrians at marked crossings) or via BTS/MRT walkway overpasses; major Bangkok intersections have pedestrian signals but compliance by motorcycles is imperfect; crossing at the orange-vest motorcycle taxi zones (motorcycle taxis stationed on major corners) provides a verbal warning system — motorcycle taxis alert each other as pedestrians cross; (4) If involved in a Bangkok traffic accident: do not move vehicles if anyone is injured (Thai traffic law); call 191 (police) and 1669 (medical); contact your embassy if serious; contact your insurance company immediately; (5) Grab app for safe Bangkok transport: Grab (dominant ride-share) provides licensed drivers with GPS tracking — both safer and more accountable than street taxis (though street taxis are also generally safe for most journeys).",
  },
  {
    title: "Bangkok Nightlife Legal Reality — Bar Laws, Closing Times & What's Actually Regulated",
    emoji: "🌙",
    summary: "Bangkok's nightlife operates within a regulatory framework that visitors frequently misunderstand: (1) Official Bangkok bar and club closing times: Thai law specifies venue closing times based on venue classification and location; entertainment venues (bars, clubs) in designated 'entertainment zones' can operate until 2am; venues outside entertainment zones must close at midnight; Bangkok's entertainment zones: Thong Lo/Ekkamai area, Silom Soi 4 and surrounding area, Ekkamai RCA area (Royal City Avenue), Nana entertainment area, Patpong; the government periodically enforces these rules through raids ('anti-nightlife' enforcement campaigns) that cause temporary early closures even in entertainment zones; police enforcement is inconsistent and varies by political climate; (2) Thailand's entertainment venue classification: entertainment venues in Thailand must have a specific Entertainment Place License; operating without the license or selling alcohol during prohibited hours is the technical basis for most enforcement actions; the 'entertainment licensing' framework is often used selectively; (3) Alcohol sales restrictions: Thai law prohibits alcohol sales during specific hours (2am–11am nationally) and all day on Buddhist holidays and election days; convenience stores observe the sales restriction — 7-Eleven, Lawson, and Family Mart do not sell alcohol during restricted hours; some Buddhist holidays (Makha Bucha, Visakha Bucha, Asahna Bucha, Khao Phansa — entering Buddhist Lent) are full alcohol prohibition days when alcohol sales are banned at all venues including bars and restaurants; (4) Bangkok alcohol prohibition day calendar: approximately 4 major Buddhist holidays per year have full alcohol prohibition; additionally, national elections trigger election-day alcohol bans; the specific dates follow the lunar calendar and change annually; check a Thai holiday calendar app before planning specific nightlife activities; (5) Sex tourism and related legal issues: Bangkok has a visible sex entertainment industry that operates in legal gray areas; adult entertainment venues (gentlemen's clubs, go-go bars) operate commercially but many specific acts and arrangements are technically illegal under Thai law (though enforcement is inconsistent and politically influenced); sex work involving payment is illegal under Thai law; human trafficking is a serious issue the Thai government and NGOs work to combat; visitors should be aware that participating in transactions that facilitate exploitation creates both legal risk and ethical harm.",
    action: "Bangkok nightlife practical: (1) Check Buddhist holiday calendar before nightlife planning: apps like 'Thailand Public Holidays' or Bangkok expat Facebook groups announce upcoming alcohol-prohibition holidays; being caught with alcohol purchased after sales cutoff at a restaurant is not usually a visitor issue (restaurants often serve from pre-purchased stock); (2) After 2am options: after official closing time, some Bangkok venues transition to 'private club' status (technically member-access, in practice often accessible for a cover charge); this legal gray zone is navigated by venue operators — visitors should understand they're in an ambiguous enforcement zone after 2am; (3) Rooftop bars vs. street bars: Bangkok's rooftop bars (Sky Bar, Vertigo, Moon Bar, Octave) consistently close at 1am regardless of the 2am entertainment zone rule (higher compliance standard due to high-profile hotel involvement); street-level entertainment venues in designated zones tend to operate closer to or past 2am; (4) Drink driving: Thailand has 0.05% BAC drink driving limit (stricter than some Western countries); traffic police operate alcohol checkpoints periodically; Grab is the standard Bangkok solution for nighttime transportation — avoids both drink-driving risk and taxi negotiation at late hours; (5) Venue closure uncertainty: Bangkok nightlife venues close and move at high frequency; verify current operating status for specific venues through recent Google Maps reviews before planning a visit.",
  },
];

export function BangkokLegal() {
  return (
    <div className="rounded-2xl border border-gray-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-gray-700 mb-3">
        ⚖️ Bangkok legal essentials — drug laws, traffic rules, nightlife regulations & what visitors must know
      </h2>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-gray-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-gray-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
