const SPOTS = [
  {
    name: "Bangkok Retirement Visa (Non-OA & Non-OX) — Eligibility, Financial Requirements & Process",
    emoji: "🛂",
    area: "Thailand retirement visa application: Thai embassies/consulates in home country (for initial Non-OA from abroad); Royal Thai Embassy in Bangkok: Wireless Road, Lumphini (for in-country visa matters); Thai Immigration Bureau: Chaeng Wattana Government Complex, Northern Bangkok (main Bangkok immigration office, serves most visa extension applications); local immigration offices in Bangkok: Laksi District (near Chaeng Wattana), Srinakarin Road office (Bang Na area); One Stop Service Center: Chaeng Wattana (immigration and various government services)",
    price: "Non-OA Retirement Visa initial fee: approximately ฿2,000 at Thai embassy abroad; annual extension within Thailand: ฿1,900; financial requirement Option 1: ฿800,000 Thai bank deposit (must be seasoned in Thai bank at least 60 days before extension, and not fall below ฿400,000 during the year); financial requirement Option 2: monthly income/pension of ฿65,000/month evidenced by embassy income verification letter or bank transfers; financial requirement Option 3: combination — income + deposit totaling ฿800,000 equivalent; health insurance requirement (Non-OX): ฿40,000 outpatient coverage + ฿400,000 inpatient coverage minimum required for Non-OX (extended visa type); type O-A base visa: 1-year validity, multiple re-entry (with re-entry permit purchased within Thailand ฿1,000 single / ฿3,800 multiple); immigration reporting: 90-day reporting requirement (can be done online at imm.immigration.go.th, by mail, or in person)",
    why: "Thailand's retirement visa system has established requirements but contains specific details that create compliance challenges for retirees: (1) The ฿800,000 deposit rule mechanics: the seasoning requirement (60+ days in Thai bank before extension, no dips below ฿400,000 during the year) creates practical banking discipline requirements; the deposit must be in a Thai bank account in the applicant's name; Bangkok Bank and Kasikorn Bank (KBank) are the most commonly used banks for retirement visa deposit accounts; the bank will issue a letter confirming the deposit balance for immigration; (2) The income verification alternative: retirees with verifiable pension income (Embassy-certified income letter, required from home country embassy in Bangkok — not all countries offer this service) can use the ฿65,000/month income route; the US Embassy Bangkok does not provide income certification letters; UK Embassy does provide income letters; Australian Embassy does not provide income letters; each country has specific policy — this must be verified for specific nationality; (3) Insurance requirement evolution: Thailand has periodically tightened health insurance requirements for retirement visa holders; the current requirement (for certain visa categories) includes minimum coverage thresholds; private international health insurance (Pacific Cross, AXA, CIGNA, LMG Insurance) covering Thailand and meeting minimum thresholds is the standard approach; (4) 90-day reporting and compliance: Non-OA visa holders must report to immigration every 90 days; failure to report results in ฿5,000 fine and flags the immigration record; online reporting (imm.immigration.go.th) is available and works for most cases; the online system has technical failures — backup plan is postal or in-person reporting; (5) Retirement visa agents: many Bangkok expats use licensed immigration agents (visa agents) for annual extension paperwork; agents charge ฿5,000–15,000 for extension assistance; using a legitimate agent (verify they are licensed with the Thai Law Society or Lawyers Council of Thailand) simplifies the process but doesn't change the underlying requirements.",
    tip: "Bangkok retirement visa practical guide: (1) Bangkok Bank for retirement deposit: Bangkok Bank (BBL) is the traditional preferred bank for retirement visa deposit accounts; staff at Bangkok Bank's main branch (Silom) and branches near Chaeng Wattana immigration are experienced with retirement visa banking requirements; opening a Bangkok Bank account requires a non-immigrant visa already in hand; (2) Immigration appointment booking: Chaeng Wattana Immigration Bureau handles very high volume; arrive early (7–8am for 8:30am opening) for same-day service; online appointment booking is available through the Thai Immigration website (appointment availability varies — check well in advance of visa expiry); (3) TM47 90-day report filing: the TM47 form for 90-day reporting can be filed online, by registered mail (mailed at least 15 days before due date), or in person; most Bangkok retirees use online reporting successfully; if online fails, postal reporting is the practical backup; (4) Long-term resident visa (LTR) as alternative: Thailand's Long-Term Resident Visa (introduced 2022) offers a 10-year visa for certain qualifying retirees (passive income over $80,000/year or qualifying investments); the LTR has more stable requirements but higher income thresholds — it is a superior option for qualifying retirees; Thailand Board of Investment (BOI) oversees the LTR program; (5) Property ownership context: Thailand does not generally permit foreigners to own land freehold; retirement visa holders can own Thai condominium units (in buildings with appropriate foreign ownership quota) but cannot own land or houses directly; long-term property structures include: condo ownership (preferred), Thai spouse ownership, 30-year leasehold, or company structures (each with legal complexity and risk).",
  },
  {
    name: "Bangkok Expat Healthcare — International Hospitals, Insurance & Medical Cost Reality",
    emoji: "🏥",
    area: "Bangkok international hospitals (primary): Bumrungrad International Hospital (Sukhumvit Soi 3, Nana BTS adjacent, largest and most internationally known); Bangkok Hospital (Phetchaburi Road, Thonglor BTS vicinity, Bangkok Dusit Medical Services network); Samitivej Sukhumvit Hospital (Sukhumvit Soi 49, Phrom Phong BTS); BNH Hospital (Convent Road, Silom/Sala Daeng BTS adjacent, owned by Australian entity); Vejthani Hospital (Ramintra, northeast Bangkok, aviation medical specialist); Bangkok Hospital Siriroj (Thonburi); Vibhavadi Hospital (north Bangkok); secondary level: BDMS Wellness Clinic (Wireless Road), Medcare (multiple locations), Altitude Medical Clinic (Thong Lo)",
    price: "Bangkok international hospital cost indicators: standard GP consultation: ฿1,200–2,500 depending on hospital; specialist consultation: ฿2,000–5,000; blood panel (comprehensive): ฿3,000–8,000; CT scan: ฿8,000–20,000; MRI: ฿12,000–35,000; hip replacement (illustrative): ฿250,000–450,000 (vs. $40,000–80,000 in US, £15,000–30,000 in UK); cardiac bypass surgery: ฿300,000–600,000; international health insurance covering Bangkok: Pacific Cross Thailand (popular for retirees), Cigna Global, AXA International Expatriate, April International — annual premiums: ฿40,000–200,000+ depending on age, coverage level, deductible",
    why: "Bangkok's international hospital system is among Asia's most developed and is a primary motivation for retirement in Thailand: (1) Bangkok's hospital quality context: Thailand's top hospitals (Bumrungrad, Bangkok Hospital network) have Joint Commission International (JCI) accreditation (the international equivalent of US Joint Commission hospital accreditation); the medical technology at these hospitals is equivalent to North American and European hospitals; Bangkok's international hospital system treats both Thai patients and medical tourists; (2) Bumrungrad's international patient system: Bumrungrad specifically has extensive international patient services — multiple floors of specialist clinics, international patient center handling insurance billing, translation services for many languages, pharmacy, dental, optics, and ancillary services within the same complex; some Bangkok retirees use Bumrungrad as their primary medical home base; (3) Health insurance vs. self-pay for Bangkok retirees: the calculation Bangkok retirees make is: Thai domestic rates are substantially below Western rates; some retirees choose high-deductible international insurance (covering catastrophic events — surgery, cancer treatment) and self-pay for routine care; others choose comprehensive international health insurance (higher premium, full coverage); the self-pay model works for healthy retirees with sufficient reserves; the insurance model provides cost certainty for medical events; (4) Bangkok Hospital MedConsult app: Bangkok Hospital network has a telemedicine and appointment scheduling app (HDcare and BHSmile apps, as well as the Bangkok Hospital app) enabling online consultation and appointment management; Bumrungrad has international patient portal; both systems can handle pre-authorization for insurance claims; (5) Dental care in Bangkok for retirees: Bangkok dental care quality is high and costs are 40–70% below Western equivalents; dental tourism is a parallel industry to medical tourism; Bumrungrad has an in-house dental clinic; standalone Bangkok dental clinics (Thantakit, Dental Republic) offer competitive quality and pricing; dental implants, porcelain crowns, and cosmetic dentistry are frequently sought by Bangkok retirees and medical tourists.",
    tip: "Bangkok international healthcare practical guide for residents: (1) Registering with a home hospital: Bangkok retirees should establish a primary care relationship at one Bangkok hospital — creating a patient file, uploading prior records, and registering emergency contacts; this ensures continuity of care and avoids being 'new patient' at every visit; Bumrungrad, Samitivej, and Bangkok Hospital all offer annual health membership packages; (2) The Bangkok health check package industry: Bangkok's international hospitals actively market comprehensive health checkup packages (annual health screenings including bloodwork, imaging, cardiac evaluation) at ฿8,000–50,000 depending on scope; these packages are popular with both Bangkok retirees and medical tourists seeking comprehensive health screening below Western pricing; Bangkok Hospital's Executive Check-up and Bumrungrad's Executive Health packages are the most established; (3) Emergency ambulance in Bangkok: the most reliable ambulance services for international patients are operated directly by the major hospitals; calling Bumrungrad's emergency line (02-667-2999) or Bangkok Hospital (02-310-3000) will dispatch their own medical transport team; the government 1669 emergency line dispatches ambulances but response time and English capability varies; (4) Pharmacy access in Bangkok: Bangkok has exceptional pharmacy access — Boots Thailand (registered UK-brand pharmacy, English-speaking pharmacists at many branches) and Watsons Thailand provide licensed pharmacy services with broader pharmaceutical availability than many Western countries; many medications requiring prescription in Western countries are available OTC in Thailand; (5) Insurance claims at Bangkok hospitals: direct billing to international insurers works at major Bangkok hospitals — patients present their insurance card at admission, hospital bills the insurer directly; Pacific Cross, AXA, Cigna, and most international insurers have direct billing arrangements with Bumrungrad and Bangkok Hospital network; save Explanation of Benefits (EOB) documents for all Bangkok medical expenses for foreign tax purposes if relevant.",
  },
  {
    name: "Bangkok Retirement Communities — Where Expat Retirees Live, Social Scene & Daily Life",
    emoji: "🌇",
    area: "Primary Bangkok expat retiree neighborhoods: Sukhumvit (Nana/Asok area for value, Phrom Phong for mid-range, Thong Lo/Ekkamai for premium); Silom/Sathorn (business district but popular for long-term rental value, adjacent to BNH Hospital); Phra Khanong/On Nut (budget-conscious expat retirees, lower cost than inner Sukhumvit); Ari neighborhood (Phahon Yothin area, northern BTS, quieter, popular with Japanese expats and some Western retirees); Sathorn/Yan Nawa (south Bangkok, river access, mixed residential/luxury); Thonburi side (Bang Rak Noi area, quieter suburban Bangkok lifestyle, lower costs, across river from central Bangkok)",
    price: "Bangkok retirement cost of living estimates (monthly, excluding rent): modest retiree lifestyle ฿25,000–40,000/month (local food, public transport, limited entertainment); comfortable retiree lifestyle ฿50,000–80,000/month (mix of local and international dining, AC transport, entertainment); premium retiree lifestyle ฿100,000–200,000+/month (fine dining, private car/driver, premium apartment, golf); rent for 1–2 bedroom apartment: Sukhumvit inner ฿18,000–50,000; Sukhumvit outer ฿10,000–25,000; Ari/quieter areas ฿12,000–30,000; serviced apartment with maid service: ฿25,000–100,000/month",
    why: "Bangkok's expat retiree community is one of Southeast Asia's largest and most established, with specific characteristics that reflect Thailand's long history as a retirement destination: (1) Western expat retiree community concentration: Bangkok's primary Western expat retiree community concentration is in the Sukhumvit corridor (BTS Asok through Phrom Phong to Thong Lo/Ekkamai); the Sukhumvit concentration reflects: BTS access, English-language services availability, Bumrungrad Hospital proximity, international supermarket access (Villa Market, Tops Market on Sukhumvit), established expat social infrastructure; (2) Social infrastructure for Bangkok retirees: Bangkok's expat retiree social scene has significant organized infrastructure — multiple expat clubs (Bangkok Rotary, Bangkok Hash House Harriers, national expat social clubs), English-speaking Buddhist temples, expat church communities, golf clubs with English culture, and the American Women's Club of Thailand; the Expat Club Bangkok, German Club, Swiss Society, and numerous nationality-specific groups provide community; (3) Bangkok vs. Chiang Mai retirement: the classic Thailand retirement debate is Bangkok vs. Chiang Mai; Bangkok advantages: medical care quality, airport access, cultural activities, diverse dining; Chiang Mai advantages: lower cost of living, cooler temperatures, more relaxed pace, strong expat community; Pattaya is a third option (beach access, extremely large expat community, lower cost); most Bangkok retirees value the city's infrastructure and medical access; (4) Long-stay apartment negotiation: Bangkok's apartment rental market strongly favors long-term renters (6-month to 1-year contracts); discounts of 20–30% below monthly rates are common for 1+ year contracts; unfurnished or lightly furnished apartments also available at lower rates for retirees with own furniture (from shipping or Bangkok furniture purchase); (5) Practical daily life structure for Bangkok retirees: typical Bangkok retiree daily rhythm: morning coffee and newspaper at local café or hotel lobby; afternoon activities (gym, pool, temples, errands, social); evening dining and entertainment; the 'Bangkok slow pace' of managing heat (avoid midday outdoor activity), AC environments, and neighborhood familiarity creates a rhythm that differs significantly from tourist Bangkok experience.",
    tip: "Bangkok retirement daily life tips: (1) Finding the expat social scene: the quickest way into Bangkok's expat retiree social community is joining the Bangkok Expats Club (Facebook group, regular meetups), attending Hash House Harriers social runs (the most inclusive Bangkok expat social institution, accepts all fitness levels, social emphasis), and connecting with nationality-specific expat groups; (2) Supermarket delivery as Bangkok retiree service: Bangkok supermarket delivery (Villa Market online, Tops Online, Grab Mart, Lotus's online) is extremely well-developed; fresh groceries delivered within 1–2 hours; many Bangkok retirees do weekly digital supermarket shopping and reserve personal market visits for fresh produce at morning markets; (3) Driver services for Bangkok retirees: Bangkok car ownership for expat retirees is complicated (international driving license required, traffic, parking); alternatives: (a) dedicated driver hire (฿15,000–30,000/month for full-time driver with car); (b) daily driver booking through agencies; (c) Grab for all transport; (d) BTS/MRT + motorbike taxi combination; many Bangkok retirees develop personal driver relationships for predictable transport; (4) Banking for Bangkok retirees: Kasikorn Bank (KBank) has the best digital banking infrastructure (K PLUS app with English interface); Bangkok Bank has the best international wire transfer capabilities and long history with expat banking; both require Thai visa documentation to open; (5) Bangkok retiree legal considerations: having a will registered with Thai authorities (for Thai assets including condo ownership) and updated home-country will is recommended for Bangkok retirees; expat-focused law firms (Tilleke & Gibbins, Chandler MHM, Baker McKenzie Bangkok all have expat advisory practices) provide estate planning services adapted to Thai law requirements.",
  },
];

export function BangkokRetiree() {
  return (
    <div className="rounded-2xl border border-teal-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-teal-700 mb-3">
        🛂 Bangkok retirement guide — visa process, international healthcare & expat community life
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-teal-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-teal-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-teal-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
