const SPOTS = [
  {
    name: "Ballet & Classical Dance Training in Bangkok",
    emoji: "🩰",
    area: "Royal Academy of Dance affiliate studios in Bangkok, English-medium ballet schools in Sukhumvit and Silom areas, Thailand Cultural Centre dance programs, and international school performing arts departments",
    price: "Ballet class (adult beginner, per class): ฿500–1,200; Children's ballet (monthly): ฿2,500–6,000; Adult ballet monthly unlimited: ฿3,500–8,000; Ballet intensive workshop: ฿5,000–15,000; Ballet shoes (Bangkok purchase): ฿800–3,000; Leotard/dancewear: ฿500–3,000",
    why: "Bangkok has a established ballet and classical dance training sector — somewhat smaller than the city's vibrant contemporary dance and Thai traditional dance scenes but with significant institutional presence. Key elements: (1) Royal Academy of Dance affiliated schools: several Bangkok studios operate under RAD (Royal Academy of Dance, UK) examination system, providing internationally recognized grade progression for students from children through adults; (2) International school programs: Bangkok's large international school sector (ISB, Ruamrudee International School, Harrow Bangkok, etc.) includes performing arts departments with ballet programs; these create demand for qualified ballet teachers and studio space; (3) Thai classical dance connection: Bangkok's traditional Thai classical dance (Ram Thai) training institutions — most formally at the National Theater and university fine arts departments — provide parallel training for Thai students who may also study ballet; (4) Adult beginner ballet: the adult beginner ballet market in Bangkok has grown with the global ballet fitness trend (ballet barre classes, adult recreational classes); multiple studios offer genuine adult-oriented beginner programs that differ from children's syllabi.",
    tip: "Bangkok ballet access for visiting dancers and families: (1) Drop-in class access: several Bangkok ballet studios offer drop-in adult classes for visiting students who provide their training background; contacting studios via email or LINE before arrival to confirm drop-in policies avoids wasted trips; (2) Children's ballet for expat families: arriving expat families with children in ballet training can continue their child's RAD or ISTD progression in Bangkok; confirming which examination syllabus a potential Bangkok studio uses before enrollment ensures continuity; (3) Pointe shoe fitting in Bangkok: Bangkok has limited specialist pointe shoe fitting expertise compared to London or New York; serious ballet students typically bring their own fitted pointe shoes rather than purchasing in Bangkok; (4) Dance floor quality: classical ballet requires specific sprung wood or semi-sprung floor construction for injury prevention; visiting studios before committing to training there to assess floor quality is advisable; (5) Thai classical dance exposure: adult dancers visiting Bangkok interested in experiencing Thai classical dance can attend Royal Thai Government Cultural Shows at Thailand Cultural Centre or Sala Chalermkrung, and some studios offer introductory Thai classical dance workshops for visitors.",
  },
  {
    name: "Contemporary Dance & Movement Arts in Bangkok",
    emoji: "💃",
    area: "Contemporary dance studios in Bangkok: B-Floor Theatre, Patravadi Theatre (Thonglor), Bangkok Dance Center, various contemporary studios in the Ekkamai/Thonglor creative district, and university dance departments (Chulalongkorn, Silpakorn)",
    price: "Contemporary dance class (per class): ฿400–1,000; Workshop with visiting international choreographer: ฿1,500–4,000; Monthly unlimited (contemporary studio): ฿3,000–7,000; Contact improvisation session: ฿300–600; Dance therapy class: ฿500–1,500; Youth contemporary program (monthly): ฿2,500–5,000",
    why: "Bangkok's contemporary dance community has developed a distinctive identity over the past two decades — not purely Western modern dance and not purely Thai classical, but a creative space where Thai choreographers and international artists collaborate in exploring movement. Key institutions: (1) B-Floor Theatre — Bangkok's most influential alternative theater and dance company; internationally recognized, creating work that interrogates Thai social and cultural material through physical theater and dance; (2) Patravadi Theatre — Thonglor's river-adjacent performing arts complex; has hosted experimental dance and performance work for decades and is the physical home of several Bangkok dance companies; (3) Bangkok International Performing Arts Meeting (BIPAM) — an annual festival that brings international dance and performance artists to Bangkok; creates intensive workshop and performance opportunities for the local community; (4) University contemporary dance: Chulalongkorn and Silpakorn University fine arts programs include contemporary dance; the university dance communities produce Bangkok's next generation of Thai dance artists; (5) Contact improvisation community: Bangkok has a small but active contact improvisation (CI) practice community that gathers weekly.",
    tip: "Bangkok contemporary dance engagement: (1) B-Floor workshops: B-Floor Theatre periodically opens their rehearsal and training processes to the public through workshops; following their social media provides access to these less-publicized events; (2) BIPAM festival timing: the Bangkok International Performing Arts Meeting typically occurs annually (usually in October/November); timing a Bangkok visit to coincide with BIPAM provides intensive exposure to the international dance community; (3) Thai university dance community: approaching Chulalongkorn University's faculty of fine arts and performing arts or Silpakorn's art education department (in English, by email) can yield observation or participation opportunities in undergraduate dance programs; (4) Movement and meditation intersection: Bangkok's yoga and meditation communities increasingly intersect with somatic movement practices (Body-Mind Centering, Feldenkrais, Authentic Movement); several Bangkok yoga studios offer these adjacent movement practices; (5) Expat dance community: Bangkok's expat dance community organizes through Facebook groups (Bangkok Dancers, Bangkok Salsa and Bachata community) and informal networks that provide social dance opportunities across styles.",
  },
  {
    name: "Thai Classical Dance — Khon, Lakhon & Traditional Arts",
    emoji: "👸",
    area: "Thai classical dance institutions: Silpakorn University Fine Arts Department, Thailand Cultural Centre (Huai Khwang), National Theatre (Tha Chang area), Chalermkrung Royal Theatre (Old Bangkok), and traditional dance schools associated with major temples",
    price: "Cultural show with Thai classical dance: ฿800–3,000; Introductory Thai classical dance workshop (3 hours): ฿1,500–4,000; Short-term intensive Thai dance class (1 week): ฿5,000–15,000; Khon mask purchase (decorative): ฿2,000–50,000+; Thai classical costume rental (photos): ฿1,000–3,000",
    why: "Thai classical dance — particularly Khon (masked drama performed to the Ramakien epic, Thailand's version of the Ramayana) and Lakhon (court dance drama with distinct female performance traditions) — represents one of the world's great classical performance traditions. UNESCO inscribed Khon on its Intangible Cultural Heritage list in 2018, acknowledging the thousands of years of court dance tradition that has been maintained through institutional transmission at Silpakorn University and the fine arts schools. The tradition is living: the Chalermkrung Royal Theatre in Old Bangkok presents Khon performances with elaborate costumes, live piphat orchestra, and full narrative storytelling drawn from the Ramakien; the National Theatre presents periodic classical performances; and university end-of-year performances present the next generation of trained Thai classical dancers. Specific features: (1) The Khon masks — elaborate papier-mâché masks representing specific characters with distinct colors and designs; the monkey god Hanuman (white), the demon Totsagan (Ravana, gold), and the hero Phra Ram (green) each have specific iconographic characters; (2) The hand gestures (ram) — trained over years, each gesture communicates specific meaning within the narrative; (3) The live piphat orchestra — the traditional Thai ensemble of xylophones, gongs, and pi (reed instrument) that accompanies performance.",
    tip: "Experiencing Thai classical dance in Bangkok: (1) Chalermkrung Royal Theatre: the most accessible venue for authentic Khon performance for international visitors; the performances include LED screens with English subtitles for the Ramakien narrative; booking in advance through the theatre website or major Bangkok hotel concierges ensures access; (2) Cultural show alternatives: several Bangkok dinner-show venues (Sala Rim Nam at Mandarin Oriental, Baan Khanitha) present shorter Thai classical dance excerpts alongside dinner; these are less deep but more accessible for visitors with limited time; (3) Silpakorn University public performances: the university presents formal end-of-year performances where student performers at advanced levels present Khon and Lakhon; these are significantly cheaper than commercial performances; (4) Workshop participation: introductory workshops at Silpakorn's open programs or through Bangkok cultural tourism operators provide hands-on exposure to the hand gestures and movement foundation; the experience develops respect for the technical depth; (5) Khon mask as authentic souvenir: a handmade Khon mask from an artisan workshop (available at Chatuchak Weekend Market and artisan shops) represents a genuinely culturally significant Bangkok souvenir; asking about the artisan's process and the character represented adds meaning to the object.",
  },
];

export function BangkokBallet() {
  return (
    <div className="rounded-2xl border border-pink-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-pink-700 mb-3">
        🩰 Bangkok dance culture — ballet, contemporary dance & Thai classical Khon performance
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-pink-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-pink-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
