const SPOTS = [
  {
    name: "Shooting Ranges in Bangkok — Legal Firearm Experiences",
    emoji: "🎯",
    area: "Bangkok shooting ranges: BB Gun Club & Paintball venues in Pattanakarn area, Onyx Shooting Range (Sukhumvit), Shooting Center at RCA area, Ratchaphiphat Shooting Range (government police-operated, Vibhavadi), Lucky Luke (Pattanakarn) — primarily in outer Sukhumvit and eastern Bangkok",
    price: "Handgun shooting package (50 rounds, rental + supervisor + safety gear): ฿1,500–3,000; Rifle shooting package: ฿2,500–5,000; Shotgun experience (clay pigeon): ฿2,000–4,000; Full shooting experience package (multiple firearms, 2 hours): ฿4,000–12,000; Safety training course (4 hours): ฿2,000–5,000",
    why: "Bangkok has a legal civilian shooting range industry that allows tourists and residents to experience firearm use under strictly supervised conditions — operating under Thailand's Firearms Act which permits regulated shooting at licensed ranges with firearms owned by range operators: (1) Legal framework: shooting at Bangkok's licensed ranges is fully legal for both Thai nationals and foreign visitors; visitors present passport/ID and sign safety documentation before participating; (2) Firearm variety: Bangkok ranges typically stock handguns (Glock 17, Glock 19, SIG Sauer P226, 1911 variants), semi-automatic rifles (AR-15 platform), and shotguns; experienced range masters provide safety instruction before every session; (3) Why Bangkok for shooting: Bangkok's ranges offer shooting experiences with calibers and firearm types restricted in many European countries and Japan; this creates specific demand from European and Japanese visitors wanting to experience firearms legally; (4) Safety protocols: professional Bangkok ranges emphasize safety procedures (ear and eye protection required, range hot/cold protocols, RO supervision at all times); incidents at licensed Bangkok ranges are extremely rare due to strict operating protocols; (5) Paintball and laser tag: Bangkok's non-firearm combat sports venues (paintball at RCA area, laser tag at multiple mall-adjacent venues) offer lower-intensity competitive shooting experiences.",
    tip: "Bangkok shooting range guidance: (1) Booking in advance: Bangkok's better shooting ranges operate by appointment; walk-in availability exists but advance booking secures preferred session times and firearm availability; (2) Supervisor quality matters: the quality of the range safety officer (RSO/range master) varies significantly between Bangkok ranges; a knowledgeable RSO who explains technique and safety beyond the minimum instructions creates a better experience; (3) Corporate and group events: Bangkok shooting ranges actively market corporate team-building events (half-day shooting experience packages); if visiting with a group, corporate package pricing often includes more rounds at better effective cost per round; (4) Ratchaphiphat Police Range: the government-operated police shooting range is less tourist-oriented but available to civilians through proper registration; it offers more basic facilities at lower cost for visitors primarily interested in the shooting experience rather than the venue; (5) Firearm ownership in Thailand: understanding that shooting range experiences are distinct from firearm ownership in Thailand (which requires Thai citizenship plus specific licensing) helps set expectations; range firearms cannot leave the facility.",
  },
  {
    name: "Archery & Ax Throwing in Bangkok",
    emoji: "🏹",
    area: "Archery studios in Bangkok: multiple dedicated archery studios in Sukhumvit area (Archery Bangkok, BKK Archery), mall-based archery practice courts in Central Ladprao and other major malls; ax throwing (newer trend): emerging Bangkok venues in Ekkamai/Thonglor lifestyle corridor",
    price: "Archery beginner lesson (1 hour including equipment): ฿600–1,200; Archery practice session (30 minutes, equipment rental): ฿400–800; Archery monthly membership: ฿3,000–8,000; Ax throwing session (30–60 minutes): ฿600–1,500; Compound bow equipment purchase (entry level): ฿8,000–25,000; Traditional recurve bow set: ฿3,000–15,000",
    why: "Bangkok's archery scene spans both traditional Asian archery practice and modern sport archery — providing meaningful activity for both casual visitors wanting a one-time experience and serious practitioners training for competition: (1) Modern recurve sport archery: Thailand's national archery program (Thai archery team competes internationally) has created coaching infrastructure; Bangkok's dedicated archery studios have certified coaches teaching FITA recurve technique for sport competition; (2) Korean-style archery culture: the Korean archery tradition (which dominates Olympic recurve archery) has influenced Bangkok's archery training culture; several Bangkok studios specifically emphasize Korean archery methodology; (3) Traditional Thai archery: traditional Thai bow and arrow practice (inspired by historical warfare archery) is preserved in cultural programs; less common in Bangkok than in Chiang Rai/northern Thailand, but the Bangkok cultural archery community exists; (4) Compound bow hunting culture: Thailand's legal hunting culture (for specific wildlife categories in designated areas) has created a compound bow community in Bangkok; some Bangkok archery studios cater specifically to compound bow hunters; (5) Ax throwing as social activity: the Canadian/American ax throwing bar format (walk-in, supervised, social) has arrived in Bangkok's lifestyle district; venues combine ax throwing with craft beer for group entertainment.",
    tip: "Bangkok archery access: (1) First-session structure: all Bangkok archery studios run first sessions as guided beginner experiences with instruction before unsupervised practice; expecting this structured introduction and not rushing past safety instruction creates better shooting technique; (2) Competition pathway: Bangkok archery studios affiliated with the Archery Association of Thailand track and field clubs can provide information on local competition at provincial and national level for visitors wanting to pursue competitive archery; (3) Equipment import considerations: serious Bangkok archery practitioners typically purchase equipment in Bangkok (generally cheaper than importing from international retailers due to shipping + duty) or in South Korea (the global center of competitive recurve archery equipment production); (4) Barebow trend: barebow archery (recurve without sights or stabilizers) has gained popularity globally and in Bangkok's archery community as a traditional technique revival; several Bangkok studios offer dedicated barebow instruction; (5) Evening archery: Bangkok's indoor archery studios allow evening sessions; this makes after-work archery practice in Bangkok viable in a way that outdoor ranges (dependent on daylight) are not.",
  },
  {
    name: "Escape Rooms & Immersive Entertainment in Bangkok",
    emoji: "🔐",
    area: "Escape rooms concentrated in mall entertainment zones: Siam Square One, EmQuartier basement, Central Festival Eastville; dedicated escape room venues in Ari, Thonglor; virtual reality escape rooms in RCA/entertainment corridor; murder mystery dinner shows at Bangkok's international hotels",
    price: "Standard escape room (2–6 players, 60 minutes): ฿700–1,800/group; Premium/horror escape room: ฿1,500–3,500/group; VR escape room experience: ฿800–2,000/person; Murder mystery dinner (at hotel): ฿2,500–6,000/person; Immersive theatre experience: ฿800–2,500/person",
    why: "Bangkok's escape room and immersive entertainment industry has grown significantly since 2015 — the city now has over 100 escape room venues ranging from mall-based to dedicated standalone venues: (1) Thai production quality: Bangkok's best escape rooms feature production design influenced by Thailand's strong film and TV production industry; set design quality at premium Bangkok venues rivals Japanese and Korean escape rooms; (2) Thai-themed rooms: unique Bangkok escape rooms use Thai cultural and historical settings (Ayutthaya historical mysteries, Thai ghost horror themes, royal court intrigue) unavailable elsewhere; (3) Horror/supernatural themes: Thai horror culture (with strong supernatural belief in ghosts, spirits, and cursed objects) creates particularly immersive horror escape room experiences; Thai ghost horror themes are distinctive from Western horror tropes; (4) English availability: Bangkok's tourism-facing escape rooms offer English game master narration and English clue materials; the better venues provide full English translation rather than just translated materials; (5) Group size flexibility: Bangkok escape rooms typically accommodate groups of 2–10 players; larger group bookings can often book adjacent rooms for team versus team competition.",
    tip: "Bangkok escape room selection: (1) Difficulty rating awareness: Bangkok escape rooms use inconsistent difficulty rating systems; asking specifically about the average completion rate (% of groups that complete the room) provides a more reliable difficulty indicator than 3/5 stars ratings; (2) Thai horror rooms for experience seekers: Bangkok's Thai ghost-themed escape rooms with jump scares, live actors, and darkness-based navigation are among the most genuinely frightening escape experiences in Asia for visitors willing to engage with Thai supernatural themes; (3) Advance booking essential for weekends: popular Bangkok escape rooms book out 1–2 weeks ahead for weekend evenings; booking platforms like Klook or direct venue booking pages are the fastest booking method; (4) Murder mystery at hotels: Bangkok's international hotels periodically run murder mystery dinner theatre experiences that combine Western-style mystery theatre with Thai hospitality; these are announced through hotel event calendars; (5) Newer venues vs. established chains: Bangkok's escape room industry has rapid turnover; newer venues often have fresher set design and newer puzzle technology; checking venue review recency on Google Maps (comparing 2024+ reviews vs older reviews) avoids recommending venues that have declined in quality.",
  },
];

export function BangkokShootingRange() {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-slate-700 mb-3">
        🎯 Bangkok recreational activities — shooting ranges, archery & escape rooms
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-slate-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-slate-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
