const SPOTS = [
  {
    name: "Thai Fermented Foods — Pla Ra, Kapi & Padaek: The Fermented Backbone of Thai Cuisine",
    emoji: "🍶",
    area: "Bangkok fermented food sources: Or Tor Kor Market (Mo Chit MRT, premium food market — best quality kapi, pla ra, and fermented products from around Thailand); Chatuchak Weekend Market (food sections) — good selection of regional fermented products; Pak Klong Talat (market area near Memorial Bridge) for wholesale fermented fish products; Or Tor Kor's fishery section specifically: multiple vendors specializing in authentic kapi (shrimp paste) from different regions; neighborhood wet markets (talat sod) throughout Bangkok: fresh fish and fermented seafood products for local cooking at market price; Yaowarat (Chinatown): fermented/preserved Chinese ingredients (salted fish, preserved vegetables, fermented tofu, doubanjiang) at Chinese grocery shops",
    price: "Bangkok fermented food price guide: premium kapi (shrimp paste) from Or Tor Kor: ฿80–300 per 500g depending on quality and region of origin; pla ra (fermented freshwater fish, Isaan style): ฿50–150 per 500g at market; pla kem (salted fish): ฿50–200 depending on fish type; fermented soybean (tao jiao, Chinese-influenced): ฿30–80 per 200g; shrimp paste (kapi) at 7-Eleven or supermarket: ฿25–80 (mass-produced quality); premium fish sauce (naam pla) at Or Tor Kor: ฿80–300 per 700ml; Tiparos brand (standard tourist-facing fish sauce): ฿35–60 per 700ml at any supermarket",
    why: "Fermented ingredients are the invisible foundation of Thai cooking — understanding them transforms understanding of the cuisine: (1) Kapi (fermented shrimp paste) — the cornerstone: kapi (กะปิ) is made from small shrimp fermented with salt for months to years until the mixture becomes a pungent, deeply umami paste; every Thai regional cuisine uses kapi in different ways; kapi is an essential ingredient in many Thai curry pastes, nam phrik (chili dipping sauces), and is the base for the most beloved Thai dipping sauce — nam phrik kapi; different regions produce distinctly different kapi: kapi from Rayong (eastern Thailand) is drier and more intensely shrimp-forward; kapi from coastal areas is often darker and more pungent; roasting kapi briefly before use amplifies its flavor; (2) Pla ra (fermented freshwater fish) — Isaan's flavor backbone: pla ra (ปลาร้า) is salted fermented freshwater fish — fish packed in salt with roasted rice bran and left to ferment for months to years; pla ra is the defining flavor component of Isaan cuisine; it appears in: papaya salad (some variations use pla ra rather than fish sauce), naam prik pla ra dipping sauce, kaeng pla ra (fermented fish curry), and throughout Isaan cooking; pla ra has a powerful fermented odor that is considered deeply appetizing in northeastern Thailand's food culture; for visitors, pla ra represents the most challenging and rewarding flavor frontier of Thai cuisine; (3) Padaek (Lao-style fermented fish): padaek (ปลาแดก) is the Lao version of fermented fish, with chunks remaining visible rather than fully dissolved; Isaan region (historically part of the Lao cultural sphere) uses padaek interchangeably with pla ra; the cultural continuum between Isaan and Laos is expressed clearly in shared fermented fish traditions; (4) Thai fish sauce (naam pla) — liquid fermented anchovy: naam pla (น้ำปลา) is the Thai equivalent of Southeast Asia's universal fish sauce — fermented anchovy with salt, pressed and filtered to produce an amber liquid of extraordinary savory depth; naam pla quality varies dramatically: premium artisanal naam pla (aged 12–24 months, made from coastal anchovies, Rayong or Pattaya coast production) has complex flavor far beyond mass-produced versions; Tiparos, Megachef, and Squid brand are standard commercial products; premium naam pla from Or Tor Kor provides a reference point for authentic quality; (5) Fermented vegetables and condiments: Thai cuisine uses numerous fermented vegetable preparations: pak dong (pickled vegetables); mu yong (fermented pork); naem (fermented pork sausage, eaten raw when fresh — requires careful sourcing); phak kard dong (pickled mustard greens, Chinese-Thai influence, used in boat noodles); the interplay of fresh, fermented, and pickled components creates the flavor complexity that distinguishes authentic Thai cooking from simplified versions.",
    tip: "Exploring Bangkok fermented ingredients: (1) Or Tor Kor Market kapi tasting: arrive at Or Tor Kor (Mo Chit MRT area) before noon; the market's fishery/dried goods section has multiple kapi vendors; it is common and acceptable to taste kapi before purchasing — experienced vendors will offer small samples; comparing kapi from different producers reveals the regional flavor variation; (2) Pla ra introduction: the most accessible way to experience pla ra is in papaya salad (som tam) with pla ra (specify 'som tam pla ra' at an Isaan restaurant or food stall); the pla ra in papaya salad is cooked lightly in the preparation, reducing the fermented intensity while preserving the depth; (3) Fish sauce quality comparison: purchase one bottle of premium naam pla (฿150–250 at Or Tor Kor) alongside a standard commercial bottle (฿35 at 7-Eleven) and compare in a simple preparation (naam prik or as salad dressing) — the quality difference is immediately apparent; (4) Chinese fermented ingredients at Yaowarat: Yaowarat's Chinese grocery shops stock fermented black bean (tao si), doubanjiang (Sichuan chili bean paste), preserved mustard greens (tang chai), and fermented tofu (tao hu yee) — these Chinese fermented ingredients pervade Thai-Chinese cooking in Bangkok and understanding them provides access to a significant part of Bangkok's food ecosystem; (5) Naem (fermented pork sausage): naem (แหนม) — fermented raw pork wrapped in banana leaves or plastic — is a northern and Isaan specialty sold at markets; eating naem raw (as it's traditionally eaten when freshly made) requires trusting the source (market freshness, proper preparation); cooked naem is safe; the fermented funk + pork combination is distinctive and divisive.",
  },
  {
    name: "Bangkok Michelin Scene — Understanding the Thai Fine Dining Revolution",
    emoji: "⭐",
    area: "Bangkok Michelin-starred restaurant locations: Jay Fai (22 Mahachai Road, Banglamphu, near Khao San Road — 1 star, street food legend); Nahm (Como Metropolitan Hotel, 27 South Sathorn Road, Sathorn — 1 star); Le Du (399/3 Silom Road — 1 star, modern Thai); Sra Bua by Kiin Kiin (Siam Kempinski Hotel, Rama I Road — 1 star, modernist Thai); Paste Bangkok (Gaysorn Village mall, Ploenchit — 1 star, regional Thai cuisine); Gaggan Anand (68/1 Lane 1, Soi Ari 5 — 2 stars, progressive Indian in Bangkok); Hua Hin-based chefs with Bangkok presence; Bib Gourmand listed (good value) restaurants: extensive list covering market vendors, traditional restaurants, and specialty noodle shops; full list at guide.michelin.com — Bangkok added to Michelin Guide in 2018",
    price: "Bangkok Michelin starred dining price ranges: Jay Fai: ฿600–1,500 per person (street food quality, Michelin recognition drove prices up from Jay Fai's original street pricing); Le Du: omakase/tasting menu ฿1,800–3,500 per person; Nahm: ฿2,500–4,000 per person for dinner tasting menu; Sra Bua by Kiin Kiin: ฿3,000–5,000 per person tasting menu; Gaggan Anand: ฿4,000–7,000 per person for full tasting menu (20+ courses); contrast with Bib Gourmand listed vendors: Jay Fai was originally ฿200–400 before Michelin; current Bib Gourmand vendors ฿80–400 per dish; Bangkok's Michelin dining ecosystem spans 3 orders of magnitude in price",
    why: "Bangkok's Michelin recognition (2018) accelerated an existing fine dining revolution that had been building since the early 2000s: (1) Jay Fai — the most famous street vendor: Jay Fai (Ruan Pos, aged 70s) operates a charcoal wok station at her original Mahachai Road address; her specialties: khai jeaw poo (crab omelet, ฿800+, famous for crispy exterior/silky interior), pad kee mao (drunken noodles with seafood), tom yum seafood; the Michelin star created an 8–14 hour wait situation; reservation system now exists (Facebook); the story of a solo charcoal-cooking street vendor receiving a Michelin star is Bangkok's most famous food narrative internationally; (2) The Thai fine dining movement context: Thai fine dining had been developing at Bangkok's luxury hotels for decades (Mandarin Oriental Sala Rim Naam, Shangri-La's Salathip) but the emergence of chef-driven independent Thai restaurants using classical Thai techniques with modern presentation began around 2010–2015; Nahm's chef David Thompson (British chef, expert in historical Thai cooking using rare recipes) established the legitimacy of Thai cuisine at fine dining level; Thai chefs (Bee Satongun at Paste, Thitid Tassanakajohn 'Chef Ton' at Le Du) have since built internationally recognized restaurants expressing regional Thai cuisine at highest culinary level; (3) Modern Thai cuisine philosophy: the most interesting Bangkok fine dining uses historical Thai recipes (from palace cuisine manuscripts, regional family traditions, and documented recipes from before Western food influence) as the foundation; ingredients sourcing from specific regional producers (specific chili varieties from northern Thailand, heritage rice varieties, wild-harvested herbs) provides flavor depth impossible with standardized commercial ingredients; the contrast between this ingredient-specific cooking and tourist-facing pad thai is enormous; (4) Bangkok Michelin Bib Gourmand — the practical value list: the Bib Gourmand designation (good food at moderate price, under approximately ฿1,000 per person) covers Bangkok's most interesting affordable restaurants; the Bib Gourmand list includes specific noodle shops, curry rice shops, and market vendors that local food critics consider best in class; this list is more practically useful for most Bangkok visitors than the starred restaurant list; (5) Reservations in Bangkok fine dining: Gaggan Anand typically requires weeks-to-months advance booking; Jay Fai requires reservation via Facebook (limited daily covers); Le Du and Paste accept shorter advance reservations; walk-in is possible at some starred restaurants for lunch service.",
    tip: "Bangkok Michelin dining strategy: (1) Jay Fai reservation essential: without a reservation (Facebook-based, reply to recent posts requesting tables), the wait at Jay Fai is 4–8+ hours; with a reservation, arrive on time; the crab omelet (khai jeaw poo) is the signature dish — ordering at least one is expected; (2) Bib Gourmand as entry point: the Michelin Bib Gourmand list is updated annually; current list at guide.michelin.com/th/en (filter by Bangkok, Bib Gourmand); these restaurants offer the quality of Bangkok's best food at accessible prices (฿300–800/person range); (3) Le Du wine program: Le Du has Bangkok's strongest natural wine program alongside its modern Thai menu — worth checking for wine-with-Thai-food pairing if wine matters to your experience; (4) Timing Bangkok fine dining reservations: March–May (hot season) and July–September (rainy season midweek) have lowest demand at Bangkok fine dining — easiest reservation availability; December–January (cool season, Western holiday period) is peak — book at least 4–6 weeks ahead for starred restaurants; (5) Pre-dinner drinks at Bangkok hotel bars: starting with cocktails at the Bamboo Bar (Mandarin Oriental), Long Bar (Shangri-La), or Lobby Lounge (Peninsula) before a fine dining reservation extends the experience into Bangkok's storied hotel culture.",
  },
  {
    name: "Bangkok Durian & Exotic Fruit Culture — Seasonal Fruits, Durian Geography & Market Timing",
    emoji: "🍈",
    area: "Bangkok durian geography: or Tor Kor Market (Mo Chit MRT) — premium durian, cleaned and boxed, highest quality, year-round premium varieties; Pak Klong Talat market area — bulk durian trade; Charoenkrung/Talat Noi area fruit vendors; Chatuchak Weekend Market food section — seasonal durian vendors; Durian season (May–August primarily): roadside durian vendors appear throughout Bangkok; durian orchards: Nonthaburi (Bangkok's northern boundary, historically famous for Mon Thong durian); Chanthaburi province (southeast, durian capital of Thailand, 3 hours from Bangkok); Rayong durian market; Bangkok's street fruit cart ecosystem: ubiquitous throughout the city (mobile carts or fixed stands at intersections and market entrances)",
    price: "Bangkok fruit price reference: mon thong durian (premium variety): ฿150–400 per kg (season price), ฿200–600/kg out of season; kan yao durian (smaller, intense flavor): ฿500–2,000 per kg at peak; durian musang king (Malaysian variety, sold in Bangkok): ฿400–2,000 per kg; mangosteen (when in season, April–August): ฿60–150 per kg; rambutan: ฿30–80 per kg in season; dragon fruit (pitaya): ฿40–120 per kg; Thai mango (Nam Dok Mai variety, April–June peak): ฿50–150 per kg; pomelo (year-round): ฿40–80 each; jackfruit (cut and ready to eat): ฿20–50 per bag at street carts; longan (Chiang Mai production): ฿50–100 per kg in season; sala (snakefruit, year-round): ฿30–70 per kg",
    why: "Bangkok's tropical fruit culture is one of Asia's richest and most commercially developed: (1) Thai durian varieties and their personalities: the Mon Thong variety (monthong, 'golden pillow') dominates Thai commercial durian production and export — creamy, sweet, mild sulfur, thick flesh; Gan Yao ('long stem') is the connoisseur variety — smaller, more intensely flavored, bitter-sweet complex notes, significantly higher price; Chani is the smallest and most pungent; Thai durian connoisseurship evaluates: flesh color (pale yellow to golden — deeper gold indicates ripeness), texture (creamy vs. fibrous), smell intensity (more pungent ≠ better; balanced aroma is prized), seed size (smaller is better), sweetness balance (overly sweet is considered low quality); (2) Durian seasonality and Bangkok timing: Thailand's main durian season runs April–August; the orchards in Chanthaburi (Thailand's durian capital) peak late May–July; Nonthaburi's historical durian orchards (Mon Thong's origin area) are being replaced by property development; Bangkok's Or Tor Kor Market sells premium durian year-round using cold chain supply; seasonal fresh-off-tree durian is available May–August at Bangkok markets at much lower prices; (3) Mangosteen — the 'Queen of Fruit': the mangosteen (mangkhut) grows opposite durian season and is often called the natural palate cleanser for durian; the mangosteen's distinctive purple shell protects a white segmented flesh of extraordinary floral sweetness with slight tanginess; eating durian and mangosteen in sequence is a classic Thai pairing; mangosteen season: May–August, coinciding with durian; (4) Bangkok's year-round tropical fruit landscape: some fruits are available year-round: papaya (malako), pineapple (sapparot), banana (kluay — multiple Thai varieties, thinner and more flavorful than commercial Cavendish), dragon fruit (pitaya — red and white varieties); seasonal highlights: Thai mango (Nam Dok Mai, Keow Savoey varieties) peaking April–June; longan (lamyai) June–August; rambutan (ngo) May–September; lychee (linchee) April–June; (5) Bangkok street fruit carts — the city's snack infrastructure: Bangkok's mobile and fixed fruit carts provide cleaned, cut, and seasoned fresh fruit in plastic bags; the most popular presentation: green mango (mamuang) sliced and seasoned with salt/sugar/chili dip (phrik kluea, a seasoning powder); papaya in similar format; seasonal fruit ready to eat; the ฿20–30 per bag price point makes Bangkok's fresh fruit one of the city's most accessible food pleasures; the seasoning powder (phrik kluea — essentially a sweetened chili salt) is an acquired taste that enhances fruit acidity.",
    tip: "Bangkok durian experience guide: (1) First-time durian: purchase pre-portioned, cleaned durian at Or Tor Kor Market (฿50–200 per box depending on quantity); the cleaned boxed format allows controlled tasting without the intimidation of whole fruit handling; Mon Thong is the safest variety for first-time tasters — milder, creamier, less pungent; (2) Hotel durian policy: virtually all Bangkok hotels prohibit durian in rooms (the smell permeates fabric and air for days); eat durian at the market or in outdoor areas; (3) Durian ice cream at Chatuchak: several Chatuchak vendors sell durian ice cream, durian sticky rice (khao niao thurian), and durian with sticky rice + coconut milk — these preparations integrate durian into formats more accessible to cautious tasters; (4) Mango sticky rice (khao niao mamuang): Bangkok's most beloved dessert uses ripe sweet Nam Dok Mai mango with glutinous rice and sweetened coconut cream; best April–June during mango season; Or Tor Kor Market vendors and specialty mango sticky rice shops maintain quality standards year-round; (5) Fruit market timing: Or Tor Kor Market operates 6am–8pm; best selection and atmosphere 7–10am when fresh arrivals are being displayed; the market's premium positioning means the most unusual and highest-quality fruits (sala, lamut sapota, mariana plum, langsat, santol) are usually available alongside common varieties.",
  },
];

export function BangkokFermented() {
  return (
    <div className="rounded-2xl border border-green-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-green-700 mb-3">
        🍶 Bangkok food depth — fermented Thai ingredients, Michelin fine dining scene & tropical fruit culture
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-green-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-green-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
