const SPOTS = [
  {
    name: "Bangkok to Chiang Mai — Thailand's North, Mountain Culture & The Full Journey",
    emoji: "🏔️",
    area: "Chiang Mai, capital of Chiang Mai Province, northern Thailand: 700km north of Bangkok; Chiang Mai International Airport (CNX, 15-minute drive from old city); Chiang Mai Railway Station (Chiang Mai Nimmanhaemin Road end direction, 10 minutes from old city center); Chiang Mai Old City (square moat-bounded historic core, major temples, walking street); Nimmanhaemin Road (the coffee shop, gallery, and café district, Chiang Mai's trendiest area); Doi Suthep (mountain temple 15km west of Chiang Mai, elevation 1,080m); Night Bazaar area (commercial evening market zone); Warorot Market (Kad Luang, traditional covered local market)",
    price: "Bangkok to Chiang Mai transport costs: flight (AirAsia, Nok Air, Thai Airways) from Bangkok (Don Mueang or Suvarnabhumi): ฿500–3,500 one-way depending on advance booking and airline; overnight sleeper train (Bangkok Hua Lamphong/Bang Sue to Chiang Mai, approximately 12–13 hours): 2nd class air-conditioned sleeper ฿700–1,000 one-way (advance booking via thairailwayticket.com or at station); VIP bus (Northern Bus Terminal, Bangkok to Chiang Mai, approximately 10 hours): ฿500–700; accommodation Chiang Mai old city: guesthouse ฿400–800/night; boutique hotel ฿1,200–3,000; luxury resort (near Doi Suthep or Ping River): ฿3,000–12,000+",
    why: "Chiang Mai is Thailand's second city in cultural significance and the hub of the country's mountainous northern region, offering Bangkok visitors a fundamentally different Thailand experience: (1) Chiang Mai's Lanna heritage: Chiang Mai was founded in 1296 as the capital of the Lanna Kingdom — a Northern Thai kingdom that was culturally, linguistically, and politically distinct from Bangkok's central Siamese kingdom; Lanna (Northern Thai) culture has its own language (Kham Mueang), distinct Buddhist art style (Lanna Buddha images differ from Central Thai style), and historical heritage preserved in Chiang Mai's 300+ temples; (2) Old City temple density: Chiang Mai's Old City (surrounded by a moat and remnants of its original walls) contains approximately 30 temples within a 2km square area; the most significant: Wat Phra Singh (Lanna-style ubosot, gilded stucco, the city's most important active temple), Wat Chedi Luang (partially restored 15th-century chedi, 60m tall at its original height before 1545 earthquake damage), Wat Chiang Man (Chiang Mai's oldest temple, founded 1296); (3) Doi Suthep — Chiang Mai's mountain and sacred temple: Wat Phra That Doi Suthep (accessible by songthaew from Chiang Mai, or private car), perched at 1,080m on Doi Suthep mountain, is Chiang Mai's most revered temple; the 300-step naga staircase (or cable car alternative) leads to the gilded chedi visible from much of Chiang Mai; the mountain setting and the Chiang Mai valley views from the temple are exceptional; access: songthaew from Chang Phueak bus station approximately ฿80–100 per person, 30 minutes; (4) Chiang Mai's café culture and creative scene: Nimmanhaemin Road (Nimman) is Chiang Mai's contemporary lifestyle district — independent coffee roasters, design studios, boutique fashion, and galleries; Chiang Mai has developed one of Southeast Asia's most sophisticated specialty coffee cultures, with multiple Chiang Mai-based roasters using Thai and Myanmar highland arabica; the Nimman area's café culture rivals Bangkok's most developed coffee districts; (5) Chiang Mai as digital nomad and long-stay destination: Chiang Mai's combination of lower cost than Bangkok (30–50% cheaper), better climate (cooler, less humid, dramatically cooler November–February), excellent café infrastructure, strong expat community, and proximity to nature has made it the #1 Southeast Asia digital nomad destination; CAMP coworking (Maya Mall, free Wi-Fi with purchase), MANA coworking (popular with international nomads), and numerous café-coworking hybrids provide work infrastructure.",
    tip: "Chiang Mai practical guide for Bangkok visitors: (1) Overnight train as recommended Bangkok-Chiang Mai experience: the overnight sleeper train from Bangkok (departs 6–8pm, arrives Chiang Mai 7–9am) is genuinely comfortable in 2nd class air-conditioned sleeper (convertible seat-to-bunk berths); the train provides a Thai rail experience, arrival at Chiang Mai station at daybreak, and eliminates the need for hotel accommodation that night; booking 1–2 weeks ahead is advisable for weekend departures; (2) Old City walking circuit: the Old City temples are navigable on foot or by rental bicycle (฿50–100/day at multiple Old City bicycle shops); the moat loop road (3–4km perimeter) provides orientation; early morning (7–9am) temple visits see monks' alms rounds and are cooler; (3) Chiang Mai Sunday Walking Street: Wualai Road (every Sunday 4–9pm) is Chiang Mai's best walking street — silver craft workshops and silver sellers (Wualai Road is Chiang Mai's traditional silversmithing area), northern Thai food, handicrafts, and live music; less commercial than the Saturday Night Bazaar; (4) Elephant sanctuary logistics: ethical elephant sanctuaries near Chiang Mai (Elephant Nature Park — most internationally known, Ethical Elephant Encounters, Elephant Jungle Sanctuary) book up weeks ahead for weekend dates; booking directly through sanctuary websites provides the most accurate ethical information; day trips from Chiang Mai typically 8am–5pm with transport included; (5) Doi Suthep timing: Doi Suthep temple is most crowded on weekends and Thai holidays; weekday morning visits (before 10am) are the most manageable; wear modest dress (shoulders and knees covered, wraps available at the temple entrance).",
  },
  {
    name: "Bangkok to Phuket — Thailand's Island Province, Andaman Sea & When to Go",
    emoji: "🏝️",
    summary: "Phuket (862km south of Bangkok) is Thailand's largest island and the country's most internationally known resort destination, requiring understanding of its distinct seasons and geographic character: (1) Phuket's geographic character: Phuket is an island (connected to the Thai mainland by Sarasin Bridge) in the Andaman Sea; the island has distinctly different beaches on its west coast (facing the open Andaman Sea) and east coast (sheltered Phang Nga Bay, mangroves, quieter water); Patong Beach is Phuket's most developed, most touristy, and most party-oriented beach; Kata and Karon beaches offer more beach with calmer tourist density; Surin, Bangtao, and Naithon (northern Phuket) are more upscale; (2) Bangkok to Phuket: always fly. The distance (862km) makes ground transport impractical for most visitors; Bangkok-Phuket flights: Suvarnabhumi (BKK) or Don Mueang (DMK) to Phuket International Airport (HKT); multiple daily departures on AirAsia, Thai Airways, Bangkok Airways, Nok Air, Thai VietJet; flight time approximately 1 hour 20 minutes; ticket prices: ฿800–4,000 one-way depending on advance purchase and season; book 3–6 weeks ahead for peak season (December–February) and at least 2 weeks ahead otherwise; (3) Phuket seasons: understanding Phuket's seasonal character is essential — high season (November–April): clear water, calm seas, excellent diving visibility, peak pricing, crowds on Patong; shoulder season (May–June, September–October): reasonable conditions, lower pricing, some wind; low/monsoon season (June–September): significant rainfall, rough seas on west coast, some rough weather, dangerous swimming on some beaches; Similan Islands National Park (exceptional diving, 60km northwest of Phuket) is closed low season; (4) Phuket's areas and character distinction: Patong (main tourist strip, Walking Street, densest commercial development, largest party scene, highest hotel density) vs. Kata/Karon (good beaches, some commercial development, better beach space) vs. Kamala and Surin (luxury resort area) vs. Bangntao (longer beach, mixed luxury and budget) vs. Old Phuket Town (historic Sino-Portuguese shophouse architecture, growing creative scene, excellent food, the most culturally authentic Phuket area); (5) Phuket accommodation tier: Phuket's accommodation ranges from very budget (Patong guesthouses ฿400–800) to some of Thailand's most expensive resorts (Amanpuri Resort, Trisara, Sri Panwa, Paresa, all ฿15,000–80,000+ per night); the mid-range quality resort tier (฿3,000–8,000 per night with pool) is extensive and well-developed, particularly on Kamala and Kata beaches.",
    action: "Phuket airport to beach area transport: from Phuket International Airport (HKT): taxi/private car approximately 45 minutes to Patong (฿600–800), 30 minutes to Surin/Kamala (฿400–600); airport shuttle bus to Patong and other areas (฿100–180, shared, slower); Grab Thailand operates in Phuket but airport pickup may require walking to the public area; Phuket transport between beaches: Grab is the most reliable inter-beach transport; songthaew (shared truck) from Patong to Old Town approximately ฿40–60; rental car (฿600–1,200/day from major rental companies at airport) is practical for independent Phuket exploration; motorcycle rental (฿200–400/day at beach shops) is common among independent travelers; Phuket diving operators: SSI/PADI dive centers at all major Phuket beaches; Similan Islands day trip from Phuket (October–May only): speed boat day trips approximately ฿2,500–4,000 per person.",
  },
  {
    name: "Bangkok to Ko Samui — Gulf Island, Coconut Palms & The Southeast Thailand Route",
    emoji: "🥥",
    summary: "Ko Samui (Koh Samui, 685km south of Bangkok) is the Gulf of Thailand's most developed island destination, accessible via flight or combination bus/ferry from Bangkok: (1) Ko Samui character and development level: Ko Samui is Thailand's second most internationally known island after Phuket; the island has developed resort infrastructure, multiple distinct beach areas with distinct characters, an established international airport (USM, Bangkok Airways-operated and Bangkok Airways-dominated), and the tourist infrastructure expected of a major Thai island destination; the most important distinction: Ko Samui and Phuket have different sea seasons — when Phuket's Andaman side is in monsoon (June–September), Ko Samui's Gulf side is in high season; and when Ko Samui has its rainy season (November–January, specifically the northeast monsoon), Phuket is in high season; (2) Bangkok to Ko Samui transport: (a) flight: Bangkok (Suvarnabhumi or Don Mueang) to Ko Samui Airport (USM) — Bangkok Airways flies Suvarnabhumi to Ko Samui direct (approximately 1.5 hours, ฿2,000–6,000 one-way, Bangkok Airways premium price); Thai Airways and Bangkok Airways operate this route; no budget airlines land at Ko Samui (Bangkok Airways owns the airport); (b) budget alternative: fly to Surat Thani (SUR, budget airlines from Don Mueang/DMK: AirAsia, Nok Air, ฿800–2,500) then bus/ferry combination (approximately 2 hours total from Surat Thani Airport to Ko Samui); (c) overnight bus+ferry: Bangkok Sai Tai Mai to Surat Thani overnight bus (8–9 hours, ฿300–600) then morning ferry to Ko Samui; (3) Ko Samui beach areas: Chaweng Beach (most developed, widest, best nightlife, highest commercial density, also most crowded and highest scam density); Lamai Beach (second largest, more relaxed than Chaweng, still developed); Bophut (Fisherman's Village, more upscale, boutique resort character, excellent Friday night walking street); Choeng Mon (northern tip, quieter, beautiful water, family-oriented); Maenam (north coast, less developed, quieter, good long-stay character); (4) Ko Phangan proximity: Ko Phangan (known for Full Moon Party on Hat Rin beach) is 30 minutes by speedboat from Ko Samui; day trips or overnight trips to Ko Phangan are easily arranged from Samui; the Full Moon Party (held monthly around the full moon at Hat Rin Sunrise Beach) attracts 15,000–25,000 people and has specific safety considerations; (5) Ang Thong National Marine Park: Ang Thong National Marine Park (approximately 42 uninhabited islands, spectacular karst limestone formations and emerald lagoons, 30km northwest of Ko Samui, closed during monsoon) is Ko Samui's most spectacular day-trip destination; accessible only by organized tour or chartered boat; the most iconic image is the Emerald Lake (Talay Nai) saltwater lake within Ko Mae Ko island.",
    action: "Ko Samui budget transport: fly Don Mueang to Surat Thani (DMK→SUR, AirAsia/Nok Air, ฿800–2,000) then take Surat Thani Airport to ferry pier transfer (combined ticket available at airport, approximately ฿150–200) then Raja Ferry or Seatran Ferry to Ko Samui (approximately 1.5–2 hours, ฿200); total journey from Bangkok: approximately 3.5–4.5 hours; Ko Samui taxi note: Ko Samui has notoriously expensive and unmetered taxis; always agree on price before departure or use Grab (now operating on Ko Samui); Ko Samui to Ko Tao (best diving in the Gulf): high-speed catamaran from Ko Samui (Maenam pier) to Ko Tao via Ko Phangan, approximately 2.5 hours (฿600–900); Ko Samui accommodation recommendation: Bophut and Choeng Mon for family and quality-oriented visitors avoiding Chaweng's party zone; Chaweng for nightlife-seeking visitors.",
  },
];

export function BangkokChiangMai() {
  return (
    <div className="rounded-2xl border border-emerald-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-emerald-700 mb-3">
        🏔️ Bangkok to Thailand's top destinations — Chiang Mai north, Phuket Andaman & Ko Samui Gulf
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-emerald-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-emerald-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-emerald-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
