const SPOTS = [
  {
    name: "Thai Spirits — Mekhong, Ruang Khao & Local Liquor Culture",
    emoji: "🥃",
    area: "Thai spirits available throughout Bangkok: Ruang Khao white spirit (everywhere), Mekhong and SangSom rum-whiskey blends (all convenience stores, bars, restaurants); specialty Thai spirits at Tops Supermarket and Villa Market; local speakeasy-style bars featuring Thai ingredients spirits in Ekkamai and Ari neighborhoods",
    price: "Ruang Khao (750ml, convenience store): ฿120–160; Mekhong (700ml): ฿280–350; SangSom (700ml): ฿350–420; Hong Thong (Thai blend): ฿320–400; Sato (Thai rice wine, per bottle): ฿50–150; Lao khao (home-distilled, informal market): varies; Craft Thai gin (Chalong Bay, Iron Balls): ฿1,200–2,500/bottle",
    why: "Thailand's domestic spirits industry has a complex character — ranging from the ubiquitous cheap white spirits consumed by Thai working class to internationally recognized premium craft spirits that won global awards: (1) Ruang Khao (White Elephant): Thailand's best-selling alcoholic beverage; a white cane spirit fermented from molasses; extremely cheap; the foundational spirit of Thai working-class drinking culture; mixed with soda water, ice, and a wedge of lime it becomes the Thai 'cocktail' consumed at sidewalk restaurants nationwide; (2) Mekhong and SangSom: Thailand's two major 'whiskey' spirits (actually classified as rum by international standards due to sugar cane base); amber-colored with vanilla-caramel sweetness; mixed with Coke and ice at Thai birthday celebrations and bar culture; (3) Sato: traditional Thai fermented rice wine made from glutinous rice; cloudy, sweet-sour, and low-alcohol; consumed in rural Thailand and available at markets; (4) Lao khao: 'white rice liquor'; home-distilled strong clear spirit; legally ambiguous when home-produced but commercially available; stronger and less refined than Ruang Khao; (5) Premium Thai craft spirits: the 2010s saw emergence of internationally competitive Thai craft spirits — Iron Balls Gin (Bangkok-based, using Southeast Asian botanicals), Chalong Bay Rum (Phuket, sugarcane-based), and Thai vodka/gin producers at Ekkamai distillery.",
    tip: "Bangkok spirits culture navigation: (1) Thai drinking ritual: Thai social drinking at restaurants typically orders spirits by the bottle (not by the glass) with a bucket of ice, soda water, and mixers; sharing a SangSom or Ruang Khao bottle at the table is the social drinking format; understanding this ordering culture prevents confusion at local Thai restaurants; (2) Beer + spirits combo: Thai drinking culture often combines spirits (Ruang Khao/Mekhong) with Leo or Chang beer; the spirit is drunk between beer sips rather than mixed together; (3) Iron Balls Gin experience: Iron Balls Distillery (Ekkamai area) has a tasting room and distillery tour showing Bangkok's craft spirits scene; their gin uses lemongrass, galangal, and other Thai botanicals that connect the spirit to Thai culinary tradition; (4) Alcohol price structure: Thailand levies significant alcohol excise tax which makes imported spirits (Jack Daniels, Jameson, Hendrick's) expensive relative to local equivalents; Thai-produced spirits benefit from lower effective taxation and represent significantly better value; (5) Night market spirits: fresh fruit spirits (barrel-aged lychee, mango, tamarind infused spirits) sold at Bangkok weekend markets represent informal Thai spirits culture; quality varies; consuming at the market rather than purchasing for transport reduces the ambiguity of informal production.",
  },
  {
    name: "Bangkok Cocktail Culture — Asian-Inspired Mixology",
    emoji: "🍹",
    area: "Cocktail bar concentration: Chinatown (Yaowaraj) cocktail bars, Silom creative cocktail corridor (Maggie Choo's, Smalls, Tropic City), Ekkamai/Thonglor experimental bar scene (Teens of Thailand, The Bamboo Bar, Found Bangkok), Sukhumvit hotel rooftop bars (Moon Bar, Vertigo, Above Eleven), community bar scene in Ari and Phahon Yothin",
    price: "Cocktail at craft bar (Ekkamai/Thonglor): ฿350–600; Cocktail at hotel bar (Sky Bar, Above Eleven): ฿550–900; Mocktail at specialty bar: ฿250–450; Thai herbal cocktail (lemongrass gin, galangal): ฿350–500; Soft opening cocktail event: sometimes free; Bar snack/food: ฿150–400",
    why: "Bangkok's cocktail scene is internationally recognized — the city consistently places multiple bars in Asia's 50 Best Bars rankings and has produced award-winning bartenders who work with Thai ingredients and Asian flavor profiles: (1) Thai-ingredient cocktail philosophy: Bangkok's best cocktail bars champion the use of Thai culinary ingredients (lemongrass, galangal, kaffir lime, pandan, butterfly pea flower, tamarind, Thai basil) in cocktail applications — creating genuinely unique flavor profiles not replicated in European or American cocktail bars; (2) Asia's 50 Best Bar recognition: Bangkok consistently places multiple bars in Asia's 50 Best Bar rankings; Teens of Thailand (Ekkamai), Smalls (Silom), and Tropic City have received recognition; this international credibility reflects genuine bartending craft quality; (3) Speakeasy culture: Bangkok has developed a speakeasy aesthetic in cocktail bars — hidden entrances, unmarked doors, and reservation-required access at select bars create exclusive atmosphere that has become part of Bangkok's cocktail identity; (4) Low-ABV and no-ABV cocktail trend: Bangkok's cocktail scene has adopted global low/no-alcohol cocktail trend with genuine enthusiasm; bars like Teens of Thailand offer full mocktail menus with the same ingredient complexity as alcoholic cocktails; (5) Hotel bar quality: Bangkok's international hotel bars (The Bamboo Bar at Mandarin Oriental — one of Asia's oldest legendary bars, Moon Bar at Banyan Tree, Above Eleven at Fraser Suites) maintain high standards with professional bartender teams and premium spirits selections.",
    tip: "Bangkok cocktail bar navigation: (1) Thonglor-Ekkamai corridor for best craft cocktails: the stretch between Thonglor and Ekkamai BTS stations contains Bangkok's highest concentration of internationally recognized cocktail bars; walking this corridor (mostly accessible via BTS and short walks) provides the most efficient route through Bangkok's craft cocktail geography; (2) Reservation required for top bars: Bangkok's best cocktail bars (Teens of Thailand, Found Bangkok, 23 Bar & Gallery) require reservations during weekends and peak evenings; booking same-day via their Instagram DMs or official booking links is standard practice; (3) Butterfly pea flower exploration: the deep blue Cabralea canjerana (butterfly pea flower, dok anchan in Thai) is perhaps the most visually distinctive Thai cocktail ingredient; natural pH-indicator properties cause it to turn from blue to purple when acidic ingredients (lime juice, tonic) are added; many Bangkok bars use this for color-changing cocktails; (4) Price context: Bangkok cocktail prices (฿350–600) represent very good international value compared to equivalent quality craft cocktails in Tokyo (¥1,800–2,500), Singapore (S$25–35), or London (£16–22); (5) Bar food culture: Bangkok cocktail bars have moved toward serious bar food (beyond nuts and olives); several recognized bars serve food menus that deserve attention alongside cocktails.",
  },
  {
    name: "Bangkok Tea Culture — From Cha Yen to High Tea",
    emoji: "🍵",
    area: "Thai tea culture: traditional Thai tea (cha yen) everywhere — roadside vendors, restaurants, 7-Eleven; specialty tea cafés in Ari, Ekkamai (notably several Taiwanese bubble tea brands); Japanese matcha cafés near Japanese community (Sukhumvit Soi 49–63); traditional Chinese tea at Yaowarat teahouses; high tea at colonial-era hotels (Mandarin Oriental Authors' Lounge, Peninsula Bangkok)",
    price: "Cha yen (Thai iced tea, street vendor): ฿25–50; Specialty bubble tea (Gong Cha, Tiger Sugar, Koi): ฿80–180; Japanese matcha latte (at café): ฿150–280; Chinese tea service (gongfu cha, per person): ฿200–600; High tea set (at Mandarin Oriental): ฿1,500–3,500/person; Premium loose-leaf tea (purchase at tea shop): ฿500–5,000/100g",
    why: "Bangkok's tea culture operates simultaneously at multiple registers — from the ubiquitous orange cha yen (sweetened Thai tea with condensed milk over ice) found at every roadside food vendor to the refined gongfu cha service at traditional Chinese teahouses to the colonial-era high tea tradition preserved at Bangkok's historic hotels: (1) Cha yen as Bangkok identity: Thai iced tea (made from Thai tea blend — black tea with star anise and tamarind, sweetened with condensed milk, poured over ice) is the signature Bangkok beverage; widely available, incredibly cheap, intensely satisfying; (2) Bubble tea penetration: Taiwanese bubble tea culture has completely saturated Bangkok's café culture; the number of bubble tea brands operating in Bangkok (Taiwanese: Gong Cha, Tiger Sugar, Koi, 50 Lan; Thai: Cha Tra Mue) is extraordinary; (3) Specialty coffee crossover: Bangkok's specialty coffee café culture has been accompanied by equivalent specialty tea development; several Bangkok tea cafés source single-estate teas from Thai highland tea gardens (Doi Chaang, Doi Inthanon areas) as well as Japanese and Taiwanese teas; (4) Traditional Chinese tea culture: Bangkok's Yaowarat Chinatown has maintained traditional Chinese tea culture; teahouses serving gongfu cha (small-cup ceremonial preparation) using high-quality oolongs and pu-erh represent the authentic Chinese merchant-class tea tradition; (5) Mandarin Oriental High Tea: Bangkok's most iconic high tea at the Authors' Lounge (Mandarin Oriental's original 1879 riverside wing) represents the colonial-era British tea culture adaptation; serving to an international audience of Bangkok visitors and residents.",
    tip: "Bangkok tea culture experiences: (1) Cha Tra Mue — the original Thai tea brand: the orange Thai tea brand found everywhere is Cha Tra Mue (the hand brand); their flagship store in Bangkok serves the same tea at shop quality rather than street vendor preparation; understanding the brand's history reveals Thai tea's modern commercial origins; (2) Thai highland tea: Thailand produces tea at altitude in Chiang Rai and Chiang Mai provinces; Bangkok specialty tea shops and café chains (Kopi De Choze, some specialty cafés) carry Thai highland tea that competes with Taiwanese and Japanese teas in quality; (3) Teahouse exploration in Yaowarat: walking Yaowarat's older streets and entering teahouses that serve the Chinese merchant community (rather than tourist-facing establishments) provides access to genuine gongfu cha culture; many of these establishments welcome walk-in customers who show interest in tea rather than just a meal; (4) High tea reservation: Mandarin Oriental's Authors' Lounge high tea requires advance reservation (minimum several days ahead); the dress code is smart casual; the river view setting is part of the experience; (5) Cold brew tea: Bangkok's heat has made cold brew tea (long-steep cold water extraction) a popular preparation; several Bangkok specialty tea cafés offer cold brew Japanese greens and oolongs that showcase the method's clarity of flavor.",
  },
];

export function BangkokSpirits() {
  return (
    <div className="rounded-2xl border border-amber-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-amber-700 mb-3">
        🥃 Bangkok drink culture — Thai spirits, award-winning cocktail bars & tea traditions
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-amber-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-amber-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
