const SPOTS = [
  {
    name: "Bangkok's Pre-Dawn & Dawn Ritual Scene — 4am Markets, Monk Alms & Wholesale Flower Trading",
    emoji: "🌅",
    area: "Bangkok's authentic pre-dawn locations: Pak Klong Talat Flower Market (Memorial Bridge area, Charoen Krung Road — peak activity midnight to 5am; a different world at 3am when fragrant flower mountains are at their highest); Khlong Toei Wholesale Market (Khlong Toei area — Bangkok's largest wholesale market, most active 1–5am; incredible scale of produce transfer); or Tor Kor Market dawn vendors (Chatuchak area, dawn to 8am early retail); Wat Bowon Niwet (Banglamphu area) — pre-dawn prayer 5:30–6am; Bang Rak Noi Market (western bank of Chao Phraya, smaller, more local dawn market); Maeklong Railway Market (Samut Songkhram province, 90 minutes from Bangkok) — morning market on active rail line",
    price: "Bangkok dawn experience costs: Pak Klong Talat flower visit: free (no admission), purchase flowers if desired (phuang malai garland from ฿10–25 each); Khlong Toei wholesale: free to walk through, not retail but purchasing small amounts is possible; transport to pre-dawn Bangkok sites: Grab at 3am from Sukhumvit or Silom: ฿80–200 depending on distance (Grab operates 24/7); tuk-tuk at dawn can be negotiated for round-trip flower market visits; monk alms-giving participation (tak bat): purchasing alms food from vendors adjacent to temples ฿50–200 for a prepared alms tray; professional photography service for dawn Bangkok shoots: ฿1,500–5,000 for guided dawn photo tour",
    why: "Bangkok's pre-dawn culture is one of the city's most fascinating and least-visited dimensions — the city operates on multiple simultaneous time zones, with a pre-dawn economy that serves the city's 10+ million people: (1) Pak Klong Talat at 3am — Bangkok's most atmospheric nocturnal experience: Bangkok's wholesale flower market operates essentially around the clock but reaches its zenith between midnight and 5am when the bulk of flower cargo arrives, is sorted, and wholesaled to florists, market vendors, temple offerings suppliers, and hotel decorators; the pre-dawn Pak Klong Talat is visually stunning — mountains of white and yellow flowers (dok mali jasmine, dok krai lotus, dok phikun, dok ruk), the sharp fragrance overwhelming the night air, workers moving with headlights through the dark market lanes; visiting at 3am provides an entirely different Bangkok experience than any tourist-facing attraction; (2) Bangkok's dawn monk alms procession (tak bat): Buddhism's morning alms tradition (Buddhist monks receive food donations from lay people each morning) creates a ritualistic dawn procession in Bangkok's neighborhoods; the tradition is best observed in areas with significant Thai Buddhist residents (not tourist zones): Bang Rak, Banglamphu (without the Khao San tourist element), and residential sois off the main roads; monks in saffron robes move in single file at dawn (5:30–7am); the correct alms-giving protocol: participants face the monk's path, remove shoes, and make offerings with both hands presented low; (3) Bangkok's dawn food market ecosystem: Bangkok's morning food preparation ecosystem begins between 2am and 4am as market vendors receive wholesale ingredients, restaurants prepare mise en place, and the street food infrastructure for the day comes alive; rice congee (jok) shops open before dawn; early morning boat noodle vendors set up by 6am; Chinese dim sum (tim sum) operations begin by 5:30am in Yaowarat; the pre-dawn food economy is largely invisible to tourist-hours Bangkok visitors; (4) Bang Nam Phueng Floating Market dawn (weekend): the Bang Krachao mini floating market begins operating around 7am on weekends — crossing by ferry at 6:30am provides the freshest, least-crowded version of this local market; arriving by 7am means encountering the market before tour groups arrive; (5) Bangkok dawn photography — the professional's window: Bangkok's professional photographers and photojournalists work the pre-dawn and golden-hour windows; the combination of morning mist over the Chao Phraya, backlit temple silhouettes, and the monk procession creates the visual Bangkok most often seen in professional photography publications; the challenge: these conditions exist for 30–45 minutes at most; arriving early is non-negotiable.",
    tip: "Bangkok dawn experience logistics: (1) Pak Klong Talat timing: arrive between 2am and 4am for peak activity; wear shoes you don't mind getting wet (market floor is damp); bring cash for flower purchases; Grab works well for transport at this hour (pool/car service available); photograph respectfully — the workers are there to work, not be photographed; (2) Monk alms protocol: if participating in tak bat (giving alms to monks): prepare food offerings the night before or buy from vendors near the temple at dawn; use appropriate alms items (cooked rice, packaged food, not raw ingredients); never touch a monk (especially critical for women); do not stand higher than the monk during the giving; consult a Thai friend or hotel concierge for current local tak bat locations in residential areas rather than tourist-stage versions near Khao San; (3) Dawn transport safety: Grab is the recommended transport at pre-dawn hours in Bangkok; motorcycle taxis are available but navigation and safety at 3am is better with a Grab car; tuk-tuks at this hour are available near major hotels; (4) Dawn food: after Pak Klong Talat, the Tha Chang area near the Grand Palace has khao tom (rice porridge) vendors open by 5am; the Prang Sam Yod area (near Khao San) has 24-hour food stalls; Yaowarat (Chinatown) operates with 24-hour food culture; (5) Combining dawn activities: the most efficient dawn experience: taxi to Pak Klong Talat at 3am (explore until 4am), walk or taxi to Wat Pho area for 5:30am temple opening and Chao Phraya dawn view (Wat Arun across the river at golden hour), move to Tha Chang or nearby for dawn food by 7am — this sequence covers three distinct Bangkok dawn environments in one morning.",
  },
  {
    name: "Bangkok's Midnight Snack Culture — 24-Hour Restaurants, Late-Night Dim Sum & All-Night Markets",
    emoji: "🌙",
    area: "Bangkok 24-hour food hubs: Yaowarat (Chinatown, MRT Hua Lamphong or BTS Saphan Taksin + ferry) — the most vibrant midnight food scene in Bangkok; multiple operators open until 2–4am; Sukhumvit Soi 38 (now Soi 36, the original market relocated but area retains 24-hour character); Asiatique after-hours (select vendors remain until very late); Silom area (multiple 24-hour restaurants serving entertainment district traffic); On Nut area (Bangkok's most 24-hour suburban zone, various cuisines); Lat Phrao Road (northern Bangkok, 24-hour noodle shops and rice porridge); 7-Eleven (every 24 hours, Bangkok has the world's highest 7-Eleven density — approximately 15,000+ stores nationally, Bangkok metro has thousands; prepared food available at all hours)",
    price: "Bangkok midnight food pricing: Yaowarat late-night: pad thai ฿50–100; roasted duck over rice ฿80–150; seafood congee ฿70–120; oyster omelet ฿80–120; deep-fried squid ฿120–200; 24-hour restaurant standard Thai meal: ฿60–150 per dish; Silom-area late-night (tourist-facing): ฿100–250 per dish; late-night dim sum (tim sum, Yaowarat): ฿15–40 per basket; 7-Eleven midnight items: ready meals ฿35–80, bakery ฿15–50, convenience hot food ฿25–60; McDonald's (24 hours at many Bangkok locations): ฿100–180 per meal; IHOP-equivalent (international breakfast chains): ฿200–400",
    why: "Bangkok is one of the world's great midnight food cities — the combination of heat that drives activity later in the day, Buddhist culture that created night market traditions, and a 24-hour urban population creates a genuine nocturnal food ecosystem: (1) Yaowarat midnight dining as Bangkok's best food street experience: Yaowarat (Chinatown) transforms after 9pm as the daytime commerce closes and food stalls take over the sidewalks; by midnight, Yaowarat is at its most atmospheric — neon signs, cooking smoke, dim sum carts, roasted duck displayed in restaurant windows, tables spilling onto the street; the midnight Yaowarat experience is distinctly different from the tourist-hour version; key midnight Yaowarat spots: T&K Seafood (street corner, recognizable by the crowd, ฿150–400 for grilled or fried seafood dishes); Mangkorn Khao (Chinese-style bird's nest soup and dim sum); Jok Prince (congee institution, serves until late); (2) Late-night dim sum (tim sum) culture: Bangkok's Chinese-Thai community maintains a dim sum culture that extends well past midnight at specific Yaowarat establishments; Bangkok's dim sum differs from Hong Kong or Singaporean dim sum in Chinese-Thai adaptation — more Thai chili presence, different wrapper textures; order at 1am what would be difficult to find in most international cities at that hour; (3) 7-Eleven as Bangkok's universal 24-hour infrastructure: Bangkok's 7-Eleven stores are a cultural institution beyond convenience store norms; at midnight, Bangkok's 7-Eleven serves: pressed toast with spreads (an institution), microwaved rice meals, convenience noodle cups, fresh-ish bakery items, and the ubiquitous cold Thai tea; many Bangkok residents (particularly those in entertainment and service industries working late shifts) eat midnight meals at 7-Eleven as a practical food culture element, not ironic; (4) Bangkok's entertainment zone food ecosystem: the Silom/Patpong area, Sukhumvit Soi 11–21 entertainment zone, Thonglor, and RCA (Royal City Avenue) all develop late-night food cultures supporting the entertainment venue customers; Sukhumvit road-side vendors, noodle shops along Soi 21, and pad thai carts near entertainment venues operate until 2–4am on weekends; (5) After-midnight wet markets: the largest Bangkok fresh markets operate through the night — Khlong Toei wholesale (1–5am), Pak Klong Talat (midnight–5am), Talat Neon (2–5am, northern Bangkok) — serving the Bangkok restaurant and food service industry; these are not retail environments but visiting them provides an extraordinary glimpse of the food supply chain.",
    tip: "Bangkok midnight food navigation: (1) Yaowarat midnight strategy: the best Yaowarat midnight food approach is walking the main Yaowarat road and the perpendicular Yaowarat Soi 11 (Sampeng Lane area) between 10pm and 1am; the crowd and cooking activity guides you to what's active; avoid places with entirely empty tables at midnight in an otherwise active area (the crowd signals freshness); (2) Transport at midnight: Grab remains the most efficient midnight transport; Bangkok's BTS and MRT shut down by midnight (approximately 11:45pm–midnight depending on station and day); at midnight, transport options: Grab (reliable), metered taxi (available on major roads), tuk-tuk (negotiate price in advance), motorcycle taxi (fastest but no luggage capacity); (3) 7-Eleven meal kit mastery: Bangkok 7-Eleven's hot table items (rotating by store) include cup congee, fried chicken, corn on the cob, steamed pork buns; the coffee machines produce surprisingly decent Americano and espresso at ฿25–45; the combination of 7-Eleven coffee + a fresh pastry at a 24-hour 7-Eleven is a legitimate midnight option in Bangkok; (4) Safety at midnight: Bangkok's major entertainment and food zones are populated and generally safe at midnight; less-trafficked sois after midnight require standard urban awareness; stick to populated main roads and use Grab rather than walking to empty streets for transport; (5) Midnight markets beyond food: Chatuchak Weekend Market (Saturday–Sunday) has a specific night market component (Friday night section, ~6pm–midnight, separate from the daytime weekend market); Jodd Fairs (Ratchada, Din Daeng area) night market operates late (until midnight or beyond on weekends) for shopping and food.",
  },
  {
    name: "Bangkok Overnight — Sleeping Under Bangkok's Bridges, 24-Hour Infrastructure & Unexpected Night Venues",
    emoji: "🏙️",
    area: "Bangkok's overnight infrastructure: 24-hour businesses beyond food: major hospitals (Bumrungrad, Samitivej, Bangkok Hospital — 24-hour emergency and selected outpatient); 24-hour pharmacies (Boots at major malls, some Watsons); 24-hour convenience retail (7-Eleven, FamilyMart, Lawson 108 throughout Bangkok); 24-hour gyms (Fitness First 24 at select Bangkok locations, Jetts Fitness); overnight karaoke venues; 24-hour pet clinics (selected veterinary emergency clinics); 24-hour car services and rental shops (major chains at Suvarnabhumi Airport); overnight bus services from Bangkok to major Thailand destinations; sleeper trains from Bangkok to Chiang Mai, Hat Yai, and Ubon Ratchathani departing overnight",
    price: "Bangkok overnight transport and services: overnight bus Bangkok to Chiang Mai (state railway-operated VIP bus): ฿600–900 per seat; overnight train Bangkok to Chiang Mai (sleeper berth): ฿500–1,300 depending on class (lower berth, air-conditioned first class is most comfortable option); airport shuttle at night: Suvarnabhumi Airport Rail Link (S1-A8) runs until 11:48pm; overnight Grab to airport: from central Bangkok ฿300–600 depending on traffic; 24-hour pharmacy: standard Thailand prescription medications available without prescription (many antibiotics, malaria prophylaxis, pain medications) at Boots and Watson at prices significantly below Western equivalents; overnight gym access (Jetts Fitness 24-hour membership): ฿500–800/month",
    why: "Understanding Bangkok's 24-hour city character helps both in planning efficient travel and appreciating the city's extraordinary temporal complexity: (1) Bangkok's overlapping population schedules: Bangkok's official population of 10+ million operates on radically overlapping schedules — the agricultural-origin dawn economy (markets, temple morning activities), the standard business day (9am–6pm), the entertainment economy (6pm–3am), the service and healthcare overnight economy (24 hours), and the transport infrastructure economy (Suvarnabhumi airport operates 24 hours as a major Asia hub); these schedules create a city that never truly stops, only shifts its center of gravity; (2) Overnight train culture: Thailand's sleeper train network connecting Bangkok to Chiang Mai, Hat Yai (border with Malaysia), and northeastern destinations operates as genuine overnight transport with real social culture; the overnight train Bangkok to Chiang Mai (14–16 hours, departing 6–8pm from Hua Lamphong or Bangkok Thonburi station, arriving 7–10am) is a classic Thailand experience; the journey through central plains and the northern highlands is scenically rewarding with dawn views; second-class air-conditioned sleepers (upper/lower berth) cost ฿500–1,000 and provide a genuine rail adventure; (3) 24-hour pharmacy access as Bangkok visitor advantage: Thai pharmacies' more relaxed prescription requirements mean Bangkok visitors can access medications (antibiotics for traveler's diarrhea, malaria prophylaxis for regional travel, pain management medications) at low cost without a prior prescription; 24-hour pharmacy access at Suvarnabhumi Airport (domestic terminal Boots), Bumrungrad Hospital pharmacy, and major commercial areas means medication access at any hour; (4) Bangkok's gambling underground (context only): Thailand prohibits gambling with limited exceptions (state lottery, horse racing at Royal Turf Club); a significant underground gambling economy exists in Bangkok (card games, sports betting, Muay Thai betting); this underground economy has its own night geography but is not tourist-accessible and carries legal risk; the context is relevant for understanding a slice of Thai nightlife that exists but is invisible to tourist-facing venues; (5) Airport overnight stays: Suvarnabhumi Airport is a 24-hour facility with food, retail, and lounge access; transit passengers and budget travelers regularly use the airport for overnight stays between flights; the terminal is air-conditioned, reasonably safe, and has multiple sleeping spots (departure gate seating areas are used by transit passengers for sleeping); Don Mueang Airport (primarily domestic + LCC) has more limited facilities for overnight stays but remains accessible.",
    tip: "Bangkok overnight planning: (1) Overnight train booking: Thailand Railway bookings can be made 60 days in advance at railway.co.th or at Hua Lamphong Station; popular overnight trains (Bangkok to Chiang Mai, Bangkok to Hat Yai) sell lower berths first; book 3–4 weeks in advance for weekend departures; (2) 24-hour pharmacy navigation: Suvarnabhumi Airport's Boots pharmacy (accessible without boarding pass in domestic terminal area) is the most convenient 24-hour pharmacy for immediate medication needs; for prescription-level medications, Bumrungrad's 24-hour pharmacy dispenses without delay for genuine medical needs; (3) Airport food at 3am: Suvarnabhumi Airport's food court (above Arrivals, 4th floor) operates until approximately 11pm; after midnight, the 7-Eleven within the terminal and selected airport restaurant operators serve reduced menus; McDonald's at some Suvarnabhumi gates operates 24 hours; (4) Overnight bus comfort: VIP overnight buses from Bangkok (Mo Chit Northern Bus Terminal for Chiang Mai route, Sai Tai Mai Southern Bus Terminal for Ko Samui/Hat Yai) have fully reclining seats on better operators; bring: blanket or light layer (buses are cold), earplugs, eye mask, snacks (bus rest stops offer limited food options); (5) Unexpected 24-hour Bangkok: Bangkok's flower arrangement studios (many Pak Klong Talat adjacent), some printing shops (Silom area), select engineering workshops, and a significant number of Bangkok's massage and traditional Thai massage shops operate on extended or 24-hour schedules supporting the city's overnight service economy.",
  },
];

export function BangkokDawn() {
  return (
    <div className="rounded-2xl border border-violet-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-violet-700 mb-3">
        🌅 Bangkok 24-hour city — pre-dawn flower markets & monk alms, midnight food culture & overnight infrastructure
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-violet-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-violet-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-violet-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
