const TOPICS = [
  {
    title: "Bangkok Gold Shopping — Yaowarat Gold, Thai Gold Standards & Investment vs. Fashion Gold",
    emoji: "🪙",
    summary: "Bangkok is one of the world's most important gold trading centers and Yaowarat (Chinatown) has the highest concentration of gold shops in Southeast Asia: (1) Thai gold purity standards: Thai gold is sold in two primary standards — 96.5% purity (Thai gold, 23 karat equivalent, marked 'Baht gold') and 99.9% purity (24 karat, sold as investment gold ingots); Thai '96.5% gold' is distinctly different from Western 18k or 22k gold jewelry; the 96.5% standard creates a distinctive warm orange-yellow color and softer metal; Thai gold jewelry is designed for gold's intrinsic value, not primarily as fashion; (2) Bangkok gold pricing structure: Thai gold shops price gold by 'baht' weight (1 baht = 15.16 grams of gold); the gold price board displayed at every Thai gold shop shows the current buy (ขาย) and sell (ซื้อ) price per baht weight in Thai baht currency; the buy/sell spread (profit margin) is transparent and publicly displayed; gold prices track the London gold market spot price adjusted for the baht/USD exchange rate; (3) Yaowarat gold shop density: Yaowarat Road's gold shops (most operated by Thai-Chinese families, established for generations) create one of the most concentrated gold shopping environments in Asia; dozens of gold shops line Yaowarat, many open until 8–9pm; the density creates competitive pricing and easy comparison; (4) Fashion gold vs. investment gold in Bangkok: Bangkok offers both fashion-oriented gold jewelry (in lower purity gold, silver, or gold-plated) at tourist-oriented jewelry shops and genuine high-purity Thai gold at Yaowarat shops; the distinction is important: Yaowarat shops sell genuine Thai gold whose value closely tracks gold market price; tourist jewelry shops often sell fashion pieces with minimal gold content at prices based on design, not metal value; (5) Gold as Thai financial instrument: Thai gold shopping is largely investment-motivated rather than purely fashion-motivated; Thai families use Yaowarat gold shops to buy gold when prices are favorable and sell back when needing liquidity; the gold shop system acts as a form of accessible savings/investment vehicle for Thai working-class families; this context explains the straightforward price display and minimal design premium above raw gold value.",
    action: "Yaowarat gold shopping access: MRT Sam Yot or MRT Wat Mangkon station; Hua Lamphong MRT then walk; Chao Phraya express boat to River City then walk; best time to visit: mornings (9am–12pm) before tourist crowds, gold shops open 9am; verifying gold authenticity: reputable Yaowarat shops provide certificates; the displayed price board is reliable (backed by government monitoring); avoid gold sold without proper paperwork; Aurora Jewelry (Yaowarat's prominent gold shop) and multiple family-run establishments all follow the same pricing transparency system; selling gold back in Bangkok: any Thai gold shop will buy back gold, showing the buyback (ขาย) price per baht weight on their boards.",
  },
  {
    title: "Bangkok Gems & Semi-Precious Stones — Rubies, Sapphires & Avoiding Gem Scams",
    emoji: "💎",
    summary: "Thailand is one of the world's historically important gem trading nations, creating both genuine opportunities and significant tourist fraud risks: (1) Thailand's gem industry heritage: Thailand was historically the world's largest ruby and sapphire trading center; the Chanthaburi province (southeastern Thailand) and Kanchanaburi are traditional ruby and sapphire mining and trading areas; Bangkok's Silom area (particularly Silom Road and Surawong Road) concentrated gem traders and is still home to established gem trading companies; (2) Legitimate Bangkok gem trade: Thailand's gem trade industry includes internationally certified gem labs (GIA, Gübelin, SSEF), established gem trading companies, and the Bangkok Gems & Jewelry Fair (biannual international trade show at IMPACT Arena); the legitimate trade operates at a professional level with certified stones and proper documentation; (3) Bangkok gem scam — the most sophisticated tourist fraud: the Bangkok gem scam is one of the world's longest-running tourist frauds (active since at least the 1980s, possibly earlier); the basic structure: friendly stranger approaches tourist near major landmark, claims tourist is lucky because gems are tax-free for export today only, offers to take tourist to 'government gem shop'; gems are sold at massively inflated prices, often with false certification; the Thai tourist police and media regularly cover this scam but it continues because it is sophisticated and the psychological manipulation is effective; the rule: never enter a gem shop based on a stranger's invitation regardless of how genuine they seem; (4) Ruby and sapphire investment reality: natural unheated rubies and sapphires from Thailand/Burma are legitimate investment gems when properly certified by internationally accredited labs (GIA, Gübelin); however, most gems sold at retail Bangkok tourist prices are: heat-treated (enhanced), synthetic (lab-created), or glass imitation; distinguishing these without proper gemological equipment and expertise is impossible for non-experts; (5) Bangkok's legitimate gem purchasing: visitors serious about purchasing gems should use established gem dealers (member firms of the Thai Gem and Jewelry Traders Association), require GIA or equivalent certification for any significant purchase, and consider the purchase as comparable to buying art (requires expertise, not impulse).",
    action: "Thai Gem and Jewelry Traders Association: tjta.or.th for member firm directory; Bangkok certified gem dealers: Philip Treacy (Silom), Pranda Jewelry (established Thai jeweler), Alex Jewelry; GIA gemological certification: gia.edu for certified Bangkok stone verification; Bangkok Gems & Jewelry Fair: held twice yearly at IMPACT Arena, Nonthaburi; gem scam reporting: Tourist Police 1155; avoiding scam critical rule: NEVER follow strangers to gem shops regardless of story; for gem information: Asian Institute of Gemological Sciences (AIGS) in Bangkok provides gemological courses and authentication services.",
  },
  {
    title: "Bangkok Souvenir Shopping — What to Buy, Where to Buy & Quality vs. Tourist Trap",
    emoji: "🛍️",
    summary: "Bangkok souvenir shopping requires distinguishing between genuinely Thai-made quality items and mass-produced tourist merchandise: (1) Quality Thai crafts worth buying: real muang silk (ikat weave, from northeastern Isaan region, distinctly different from mass-produced glossy silk); hand-carved teak items from Chiang Mai (not Bangkok market mass production); hill tribe handwork (from northern Thailand, sold at quality craft shops and foundation-supported outlets); Thai cotton (particularly indigo-dyed, handwoven); ceramic benjarong (Thai court ceramic tradition, five-color enamel); spirit house miniatures (for decorative use); Thai silk home textiles; (2) What NOT to buy as 'Thai craft': most Chatuchak and Khao San Road tourist market items come from mass production in Vietnam, Cambodia, Myanmar, or Chinese factories; stone carvings (non-Thai origin), generic 'handmade' jewelry with no craftsperson provenance, 'Buddha amulets' sold by weight rather than tradition, and most 'silk' scarves (often polyester or Chinese silk rather than Thai); (3) Where to buy quality Thai crafts: SUPPORT Foundation shops (royal project, authentic Thai craft with artist attribution, multiple Bangkok locations); Narayana Phand (Ratchaprasong area, government-curated Thai crafts collection); Chatuchak Weekend Market sections 7–8 (craft section, mixed quality but some genuine artisans); certified Thai silk from Jim Thompson (premium, authentic, not the cheapest but reliable quality); (4) Supermarket as Bangkok souvenir source: Bangkok's Tops Market (Siam Paragon, Central Embassy basement), Villa Market, and Gourmet Market carry high-quality uniquely-Thai products that make excellent gifts — Thai curry pastes (Mae Ploy brand, Maesri brand, better than export versions sold abroad), fish sauce (Tiparos, Megachef for premium quality), coconut products (Mae Ploy coconut cream), Thai chili sauces, pandan extract, high-quality Thai rice (jasmine, black rice); (5) Chatuchak souvenir section realities: Chatuchak Weekend Market has both genuine craft sections and tourist-souvenir sections; items marked as 'handmade in Thailand' or 'fair trade' in sections 7–8 are more likely authentic than items in the market's tourist-facing sections near the main gates; prices are negotiable throughout Chatuchak but the negotiation culture is softer than stereotyped — initial prices for craft items are often close to real value.",
    action: "Authentic Thai craft shops: SUPPORT Foundation shop (Government House area and at various Bangkok locations); Chatuchak craft sections: arrive at opening (8–9am Saturday or Sunday) for best selection before tourist crowds; Jim Thompson Silk: flagship on Surawong Road (Monday–Sunday 9am–9pm); Royal Orchid Sheraton and riverside hotels stock quality Thai craft shops; airport souvenir shopping (Suvarnabhumi) has quality Thai packaged food products — good last-minute purchasing; Thai herbal products: Doi Kham (Royal Project brand), OTOP products at Suvarnabhumi arrivals; customs rules: Thai antiques require export permits; fresh fruit, meat products not allowed back into most countries.",
  },
];

export function BangkokGold() {
  return (
    <div className="rounded-2xl border border-yellow-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-yellow-700 mb-3">
        🪙 Bangkok shopping gems — gold in Yaowarat, gem trade & quality Thai souvenirs
      </div>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-yellow-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-yellow-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
