const SPOTS = [
  {
    name: "Bangkok Best Souvenirs — What to Actually Buy vs. Tourist Trap Items to Skip",
    emoji: "🎁",
    area: "Bangkok quality souvenir shopping locations: Or Tor Kor Market (MRT Chatuchak Park, opposite the weekend market) — premium Thai food products, quality condiments, packaged Thai herbs, regional food specialties; Narayphand Government Craft Shop (Ratchadamri Road, near CentralWorld) — government-regulated craft quality standards, fair pricing, one-stop traditional craft shopping; River City Bangkok antique and art mall (Si Phraya Pier area, Charoen Krung) — antiques, contemporary Thai art, décor, silver work; Jim Thompson House Shop (adjacent to Jim Thompson House Museum, BTS National Stadium) — quality Thai silk products, well-authenticated, appropriate for silk fabric purchase; Chatuchak Weekend Market (Saturday–Sunday, BTS Mo Chit or Chatuchak Park) — Section 1: antiques and collectibles, Section 2: plants and ceramics; Asiatique Riverfront (evening complex) — arts, crafts, clothing, though increasingly tourist-oriented",
    price: "Bangkok souvenir value benchmarks: Jim Thompson Thai silk scarf (authentic, 100cm x 100cm): ฿800–2,500; Narayphand lacquerware tray (genuine Thai craftsmanship): ฿500–3,000; benjarong porcelain teacup set (5 pieces): ฿800–4,000; packaged Thai herb tea sets (gift packaging): ฿150–500; Or Tor Kor quality nam prik set (3–4 varieties): ฿200–500; Maepranom nam prik pao (roasted chili paste, premium) — popular gift: ฿80–120 per jar; Thai ceramics from Chatuchak: ฿80–500; elephant-print parachute pants (tourist staple, Khao San area): ฿100–300; muay thai shorts (authentic training grade): ฿350–800; handmade Thai amulet (Buddha image, temple quality): ฿50–500+",
    why: "Bangkok souvenirs range from genuine craftsmanship to Chinese-manufactured tourist items — understanding which is which dramatically improves what you bring home: (1) High-value Bangkok authentic souvenirs: Thai silk (genuine Thai silk production is from Thai silkworms fed on mulberry leaves, hand-woven on traditional looms; machine-made or synthetic 'Thai silk' is a different product entirely; the Jim Thompson brand provides authenticated Thai silk; the telltale signs of genuine Thai silk: irregular texture that catches light at different angles, slight variation in thread tension, natural color variation); handmade ceramics (genuine benjarong porcelain uses a 5-color enamel technique on white porcelain developed in the Ayutthaya period; production centers at Ban Bung Tao, Bangkok Yai; genuine pieces have hand-painted designs with slight irregularity vs. mechanical screen-printing); Thai amulets (Phra Phim, Phra Somdej and others — genuine religious items purchased from temple shops; the amulet market at Tha Phra Chan pier is the authentic trading center); (2) Tourist trap souvenir categories: mass-produced elephant-print cotton items (fabric produced in India or China, assembled in Thailand — not a Thai craft product); generic bronze Buddha statues (mass production in China, sold throughout Bangkok tourist zones; genuine Thai Buddhist iconography follows specific mudra conventions and is made by Thai craftspeople); fake 'Jim Thompson' silk (counterfeits are common at market stalls; genuine Jim Thompson has heat-stamped authentication and is sold through official shops only); (3) Or Tor Kor Market for food gifts: Bangkok's best food souvenirs from Or Tor Kor Market: premium fish sauce (Tra Chang gold label); artisanal nam prik varieties; dried Thai chili packages (dried prik kee nu, prik chee fah — excellent for cooking); premium Thai herb tea collections; dried fruit (sapta — various tropical fruits; genuinely Thai processing); these food products are authentic, well-packaged, and airport-compatible as sealed food items; (4) Bangkok craft shopping value: Narayphand Government Craft Shop (Ratchadamri Road near Big C) provides a reliable quality baseline — the government-backed shop was established to promote genuine Thai handicrafts with consistent quality; prices are fixed (no negotiation required), quality is certified, English signage is clear; it's not the most exciting shopping environment but provides the most reliable authentic craft purchase in Bangkok; (5) What not to bring from Bangkok: coral and sea shells (illegal to export from Thailand, CITES protected); Buddha images exported from Thailand require a Fine Arts Department permit — exporting without permit is illegal; antiques over 50 years old require export certification from the Fine Arts Department; ivory (illegal internationally); wildlife products (illegal, significant penalty).",
    tip: "Bangkok souvenir strategy: (1) Jim Thompson for silk: the Jim Thompson House Museum shop (Soi Kasem San 2, BTS National Stadium area) sells authenticated Jim Thompson silk products; the museum setting itself is worth visiting before shopping; prices are fixed and fair for genuine Thai silk; check outlet stores for discounted products from previous seasons; (2) Chatuchak for ceramics and collectibles: Section 1 (antiques and collectibles, Saturday–Sunday) is the best source for genuine vintage Thai ceramics, old Buddha images, and craft items; Sunday morning is best; vendors may negotiate on price for multiple item purchases or larger amounts; bring cash; (3) Or Tor Kor for food souvenirs: food gifts from Or Tor Kor are the most universally appreciated Bangkok souvenirs — everyone can appreciate Thai condiments and teas; Or Tor Kor is open Tuesday–Sunday, morning through early afternoon; (4) Airport souvenir strategy: Suvarnabhumi Airport's retail area has surprisingly good selection of packaged Thai food items and some craft products, but at a premium (20–40% above Bangkok market prices); king power duty-free carries packaged Thai items; if running out of souvenir-buying time, the airport has adequate backup options; (5) Export documentation: if purchasing antiques at River City Bangkok or other dealers, ask for export documentation; reputable dealers provide documentation routinely; undocumented antiques over 50 years old cannot legally leave Thailand and may be confiscated at customs.",
  },
  {
    name: "Bangkok Market Shopping Map — Chatuchak, Or Tor Kor, Pratunam & the Right Market for Each Need",
    emoji: "🛍️",
    area: "Bangkok's market geography: Chatuchak Weekend Market (MRT Chatuchak Park or BTS Mo Chit; Saturday and Sunday 9am–5pm; 15,000+ stalls across 35 sections; 8,000 square meters); Pratunam Market (clothing wholesale, BTS Chit Lom + 15min walk or Grab; 7 days, morning to evening); Platinum Fashion Mall (Pratunam adjacent, multi-floor wholesale-to-retail clothing mall); MBK Center (Siam area, 5 floors, mobile phones and accessories, fashion, goods at negotiable prices); Sampeng Lane (Chinatown, wholesale goods, accessories, electronics components, fabric); Pahurat Market (Indian fabric district, Wang Burapa area, near Chinatown); Bobae Market (wholesale clothing, Samret area; excellent for garment exports); Talad Neon (Phetchaburi Road intersection, night market concept, 7 days, 5pm–2am)",
    price: "Bangkok market price benchmarks: Chatuchak clothing (typical): ฿100–500 per item; Chatuchak antiques: ฿200–10,000 depending on item; Chatuchak housewares: ฿50–3,000; Pratunam wholesale clothing (minimum purchase often 2+ of same style): ฿50–200 per piece; Platinum Fashion Mall retail: ฿150–400 per garment; Sampeng Lane wholesale accessories: ฿10–50 per piece, minimum quantities apply; bargaining context: Chatuchak has negotiating culture (10–20% discount commonly accepted, do not over-negotiate small items under ฿100); Pratunam wholesale requires minimum quantity for wholesale price; MBK phones and electronics: negotiate always (10–20% below first quote normal); Sampeng Lane: minimum quantities must be purchased at wholesale price",
    why: "Bangkok's market ecosystem serves multiple purposes — tourist retail, wholesale supply chain, and local daily commerce — and knowing which market serves each need prevents frustration: (1) Chatuchak Weekend Market as Bangkok's ultimate market experience: Chatuchak is the world's largest weekend market by stall count and a genuine Bangkok institution; the 35-section layout covers: Section 1 (antiques, collectibles, amulets), Section 2 (plant market, ceramics), Sections 3–12 (clothing, accessories, vintage), Sections 13–26 (home goods, ceramics, art, furniture), Sections 27–35 (food section, pet section); the overwhelming scale (a full morning barely covers 20% of the market) and the genuine mix of tourist-facing and local-facing vendors makes it a 4–6 hour expedition; arrive by 10am to avoid the worst heat and find parking (applies to those driving); Saturday is slightly less crowded than Sunday; (2) Pratunam — Bangkok's clothing wholesale district: Pratunam is Bangkok's center for mass-market clothing supply at near-wholesale prices; the area around Pratunam intersection (Phetchaburi Road and Ratchaprarop Road) has become Bangkok's densest clothing retail zone; suitable for: buying large quantities of fashion items at low per-piece prices; replica brand goods (sold openly in some sections despite legal restrictions); fast fashion at 70–80% below international mall pricing; Platinum Fashion Mall consolidates this wholesale-to-retail market in a more organized air-conditioned format; (3) MBK Center — Bangkok's electronics and mobile market: MBK Center's upper floors (4th–6th floors primarily) contain Bangkok's most concentrated mobile phone, accessories, and consumer electronics market; pricing is significantly below major mall retail for identical products; iPhone accessories, phone cases, Bluetooth equipment, cables, and secondhand phones are available at negotiated pricing; useful for: buying legitimate accessories, getting phone issues repaired, purchasing SIM cards, sourcing electronics components; not appropriate for buying expensive electronics without warranty assurance; (4) Sampeng Lane (Chinatown wholesale): Sampeng Lane is Bangkok's oldest wholesale market corridor — a narrow lane packed with stalls selling accessories, party supplies, fabric, electronics components, and general goods in minimum quantity; not tourist-oriented; minimum purchase quantities apply; useful for event decorators, small business owners, and visitors who can absorb the minimum quantities; (5) The weekend market schedule calendar: the critical Bangkok market planning fact — Chatuchak is Saturday and Sunday ONLY; arriving on a weekday finds only the permanent plant section and some food vendors; Or Tor Kor is open all week (closed Monday); Pratunam, Sampeng, Pahurat operate daily; Talad Neon operates nightly; planning Bangkok market visits around the weekend schedule maximizes variety.",
    tip: "Bangkok market navigation: (1) Chatuchak navigation: the Chatuchak market map is available at the market office near the main gates; Google Maps works inside the market with adequate GPS signal; the market is organized by section (section numbers visible on signs); note your entry gate (numbered 1–4 on main Kamphaeng Phet roads) for return navigation; the central food section (noodles, coffee, fruit, Thai snacks) provides a rest and refuel point when market fatigue sets in; (2) Chatuchak negotiation culture: negotiating price is expected for items over ฿200; a 10–20% reduction request is generally accepted; do not negotiate item prices below ฿100 (it's bad form and inefficient); the best negotiation moment is when looking ready to walk away rather than actively asking for a discount; (3) Pratunam heat management: Pratunam is one of Bangkok's hottest shopping zones — covered but not air-conditioned; schedule for 7–9am (cooler, fresh stock arrival) or shift to Platinum Fashion Mall for the air-conditioned alternative at identical pricing; (4) Chatuchak Section 2 plant market: Bangkok's Chatuchak plant market (Section 2, permanent operation including weekdays but larger Saturday–Sunday) is one of Asia's most diverse tropical plant markets; orchids, anthuriums, bonsai, succulents, and Thai flowering plants at 10–30% of Singapore or Hong Kong equivalent prices; lightweight small orchid plants travel in carry-on luggage in many countries (check destination plant import rules); (5) Market time management: Chatuchak = minimum 4 hours, ideally 6 hours; Pratunam district = 2–3 hours; MBK = 1–2 hours; Or Tor Kor = 1–2 hours; combining Chatuchak + Or Tor Kor as one day (both BTS Mo Chit/Chatuchak area) is the most efficient Bangkok market day.",
  },
  {
    name: "Bangkok Antique Hunting — Authentic vs. Reproduction & The Tha Phra Chan Amulet Market",
    emoji: "🏺",
    area: "Bangkok antique and collectible locations: River City Bangkok (Si Phraya Pier, near Saphan Taksin BTS; dedicated 4-floor antique and art mall with established dealers; Sunday antique market in the basement); Chatuchak Weekend Market Section 1 (antiques and collectibles, Saturday–Sunday); Tha Phra Chan Amulet Market (Phra Chan Road, riverside walk opposite Thammasat University, near Grand Palace; open daily 7am–6pm approximately — the world center of Thai Buddhist amulet trading); The Streets of Charoen Krung (walkable antique and gallery cluster in the creative Charoen Krung district); H Gallery Bangkok (established contemporary Thai art gallery); Bangkok art galleries in Ari and Sathorn — contemporary Thai art rather than antiques; Nakhon Kasem (Chinatown, historically Bangkok's antique market; reduced antique character now, but still has some established shops)",
    price: "Bangkok antique and collectible price ranges: Tha Phra Chan amulet (common types): ฿50–500; collector-grade amulets (authenticated, provenance): ฿1,000–millions; River City antique (smaller pieces): ฿500–10,000; larger furniture or sculpture: ฿5,000–500,000+; Chatuchak vintage ceramics (Thai-Chinese export ware): ฿200–5,000; reproduction Buddha image (resin or bronze replica): ฿500–5,000; contemporary Thai painting (emerging artist): ฿5,000–50,000; established Thai contemporary artist: ฿50,000–5,000,000+; photography prints (limited edition, Thai photographers): ฿3,000–30,000; amulet case/frame accessories: ฿50–500",
    why: "Bangkok has a developed antique trade with complex authenticity challenges and specific cultural categories unique to Thai collecting: (1) Thai Buddhist amulets — Bangkok's unique collecting culture: Thai amulet collecting (phra khrueang, พระเครื่อง) is a major cultural practice unique to Thailand; amulets are believed to have protective and lucky properties; the amulet market at Tha Phra Chan is the global center of this trade; amulets range from common mass-produced types (worth tens of baht) to authenticated rare Ayutthaya-period pieces worth millions of baht; the amulet trade has its own authentication culture, specialized publications (amulet magazines), and deep expertise requirements; for visitors, observing the market is fascinating; purchasing requires expert guidance for any amount above ฿500 as authentication is complex; (2) Old Sukhothai and Ayutthaya ceramics: genuine antique Thai ceramics from the Sukhothai and Ayutthaya periods (13th–18th centuries) are collector-grade items sold through specialized dealers; authentic pieces require Fine Arts Department export certificates; reproductions (often very good quality) are widely sold at Chatuchak and Nakhon Kasem without this certification; the price differential between authentic antique ceramics and good reproductions can be significant — buying reproductions as decorative items is legitimate but misrepresentation is common; (3) River City Bangkok for safer antique purchase: River City's established dealers have reputations to protect and legal documentation practices for significant purchases; the Sunday antique market at River City (lower floors, 8am–3pm) brings additional sellers in a curated environment; payment by credit card is generally accepted (unlike market stalls); (4) Contemporary Thai art as a collecting alternative: Bangkok's contemporary art scene (galleries in Charoen Krung, Ari, Silom) offers legally cleaner purchases of original Thai artwork with clear provenance; major Thai contemporary artists: Kamol Phaosavasdi, Thavibu Gallery artists, Bangkok Art and Culture Center exhibitions; the contemporary art market in Bangkok has grown significantly since 2010; (5) Export restrictions for Bangkok antiques: Thailand prohibits export of: Buddha images and religious iconography (requires Fine Arts Dept permit, rarely granted for commercial sale); antiques over 50 years old without permit; all antique coins; reputable River City dealers provide appropriate documentation for legal purchases; buyers purchasing from street markets without documentation assume legal risk.",
    tip: "Bangkok antique shopping guidance: (1) River City Sunday market: the Sunday antique fair at River City (lower floors, 8am–3pm) is the most organized Bangkok antique browsing experience; air-conditioned, English-speaking sellers common, credit cards accepted; arrive by 9am for best selection; (2) Tha Phra Chan amulet market visiting: the Tha Phra Chan amulet market is best visited as an observation and cultural experience rather than a purchasing destination for inexperienced buyers; the market stretches along the river road near Thammasat University; the dedicated amulet collectors and dealers here have decades of expertise; (3) Chatuchak Section 1 strategy: the antique section opens slightly later than the fashion sections (many dealers arrive by 9:30–10am); Saturdays have a slightly different seller mix than Sundays; the early-morning pre-rush (9–10am) allows unhurried examination before the crowds; (4) Reproduction quality assessment: Bangkok's reproduction market produces high-quality replicas of Thai antiques; for decorative purposes, a well-made Sukhothai ceramic reproduction from Chatuchak is perfectly acceptable when purchased at a price reflecting reproduction status; the issue only arises when reproductions are misrepresented as originals; asking directly (is this original or reproduction?) and observing the dealer's answer is an imperfect but useful filter; (5) Thai art authentication: for purchasing contemporary Thai art above ฿50,000, request: artist's certificate of authenticity, gallery invoice with artist name, title, and date; for very significant purchases, Thavibu Gallery and HH Gallery maintain professional authentication standards comparable to international gallery norms.",
  },
];

export function BangkokSouvenirShop() {
  return (
    <div className="rounded-2xl border border-orange-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-orange-700 mb-3">
        🎁 Bangkok shopping intelligence — authentic souvenirs, market-by-market guide & antique hunting
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-orange-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-orange-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-orange-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
