const SPOTS = [
  {
    name: "Bangkok Japanese Sake Scene — Sake Bars, Importers & Thai Sake Appreciation Culture",
    emoji: "🍶",
    area: "Bangkok sake locations: Thong Lo (BTS Thong Lo, Sukhumvit Soi 55) — highest concentration of Japanese sake bars and izakaya with extensive sake lists; Ekkamai (BTS Ekkamai) — adjacent to Thong Lo, expanding Japanese food/drink culture; Silom's Thaniya Road (the Japanese entertainment area in Silom, traditionally Japanese-expat facing); dedicated sake bars in Bangkok: Thong Lo and Ekkamai area Japanese establishments; Nihonshu Lab (sake specialist, Bangkok); hotel Japanese restaurants: Okura Prestige Bangkok (Japanese hotel, serious sake program), Park Hyatt Bangkok (Japanese restaurant with imported sake selection); sake retailers: Villa Market (some imported sake, especially Phrom Phong/Thong Lo branches), Japanese grocery stores in On Nut and Phrom Phong area",
    price: "Bangkok sake pricing: house sake at izakaya (small carafe/tokkuri): ฿150–300; premium sake by glass at specialist sake bars: ฿200–800 per glass; sake flight (4–6 pours) at sake-focused venues: ฿600–1,500; bottle of premium Japanese sake (imported, retail at Villa Market): ฿800–3,000 depending on grade (junmai, daiginjo, etc.); sake tasting events: ฿500–2,000 per person at periodic Bangkok sake education events; Japanese restaurant sake pairing dinner: ฿2,000–5,000+ per person at premium hotel Japanese restaurants",
    why: "Bangkok's sake culture has grown organically with the city's large Japanese resident population and Thai curiosity about Japanese food culture: (1) Bangkok's sake market context: Japan's sake exports to Thailand have grown significantly as Bangkok's Japanese food scene developed; Thailand receives substantial sake imports (particularly junmai and ginjo grades) supported by the Thai-Japanese population and Thai consumer interest in Japanese culture; Bangkok sake culture lags Tokyo and international major cities but has achieved genuine quality and diversity at the top tier; (2) Izakaya as Bangkok's primary sake venue: the Japanese izakaya (casual bar-restaurant) format is the standard Bangkok sake delivery mechanism; Bangkok's Thong Lo/Ekkamai izakaya cluster maintains serious sake lists covering junmai, junmai ginjo, junmai daiginjo categories alongside the essential accompanying food (yakitori, sashimi, edamame, karaage); the izakaya experience integrates sake naturally as part of a food-focused evening; (3) Sake appreciation education in Bangkok: Bangkok hosts periodic sake education events through Japanese cultural organizations (Japan Foundation Bangkok) and specialized restaurants; Thai consumers show genuine interest in sake beyond just drinking — the complexity of nihonshu (sake) production, regional variation (Niigata vs. Kyoto vs. Fushimi styles), and food pairing principles have attracted Bangkok's food-enthusiast community; (4) Thai sake producers?: there are no commercially significant Thai domestic sake producers (sake requires specific rice and water conditions closely associated with Japan); all quality sake in Bangkok is imported from Japan; the import price premium makes Bangkok sake more expensive than Japanese prices for equivalent products; (5) Sake varieties available in Bangkok: Bangkok's specialist sake retailers and izakaya cover the key sake categories: junmai (pure rice sake, no added alcohol, fuller body), ginjo (higher milled rice, more delicate), daiginjo (most highly milled, aromatic, premium), nigori (cloudy, unfiltered, sweeter), nama (unpasteurized, fresh, requires refrigeration); seasonal sake (shiboritate — new season sake, arriving November–December) is less commonly found in Bangkok but available at specialist importers.",
    tip: "Bangkok sake practical guide: (1) Ordering sake in Bangkok izakaya: if the sake menu is in Japanese only (common at Thai-Japanese izakaya), the server can usually recommend; specifying preference between 'karakuchi' (dry) and 'amakuchi' (sweet) and rough price point gets a usable recommendation without requiring label literacy; (2) Sake temperature in Bangkok context: sake can be served cold (reishu), room temperature (jo-on), or warm (kanzake); in Bangkok's climate, cold sake is the most commonly served and most practical; premium daiginjo is almost always served cold to preserve aromatics; hot sake is traditional winter comfort in Japan but less contextually appropriate in Bangkok heat; (3) Sake and Bangkok food pairing: sake's umami and slight acidity make it a natural pairing for Bangkok's Japanese food scene; beyond izakaya food, sake pairs well with many Thai dishes (tom kha's coconut notes, raw fish, light seafood preparations); Bangkok's cross-cultural sake-Thai food pairing experiments are worth exploring; (4) Bangkok sake retail for taking home: Villa Market's Phrom Phong and Thong Lo branches carry the best Bangkok sake retail selection; calling ahead to check current availability before making a specific sake trip is advisable as sake import timing varies; temperature-controlled storage for premium sake is required — buying for immediate consumption is better than attempting Bangkok long-term sake storage without proper cellar conditions; (5) Bangkok sake tasting events: the Japanese Embassy Bangkok, Japanese Cultural Center, and specialist sake importers periodically organize sake tasting events; checking the Japan Foundation Bangkok (jfbkk.or.th) website and Japanese Community Bangkok social media for upcoming events provides access to educational sake tastings at reasonable prices.",
  },
  {
    name: "Bangkok Rum & Tropical Spirits — Thai Rum, Craft Spirits & The Tropical Cocktail Scene",
    emoji: "🍹",
    summary: "Thailand produces rum and Bangkok's craft cocktail scene has created serious exploration of tropical spirits: (1) Thai rum producers: Thailand grows sugar cane and has a small but growing rum distillery sector; Chalong Bay Rum (Phuket-produced, widely available in Bangkok) is Thailand's most internationally recognized rum; Phraya Rum (produced in Thailand, blend) is another Bangkok-accessible Thai rum brand; international rum brands are imported and available at Bangkok's better bars (Mount Gay, Appleton, Plantation, Ron Zacapa, El Dorado); (2) Bangkok craft cocktail integration of Thai rum: Bangkok's leading craft cocktail bars have incorporated Thai spirits as part of an 'Asian spirits' narrative — using Thai rum, Thai-produced spirits (Mekhong, Regency whisky) in cocktails that reflect Thai flavor profiles; bars like the Bamboo Bar (Mandarin Oriental), BKK Social Club, and Vesper Bangkok use Thai ingredients (kaffir lime, galangal, butterfly pea flower, lemongrass) to create Thai-inflected craft cocktails; (3) Chalong Bay Rum Bangkok access: Chalong Bay Rum (the clearest quality Thai rum) is available at Bangkok's Villa Market (spirit section), specialty liquor shops, and most cocktail bars that list craft spirits; the rum is named after Chalong Bay in Phuket (where it is distilled) and is made from fresh sugar cane juice rather than molasses, creating an agricole-style rum; (4) Bangkok's spirits taxation context: Thailand applies high excise tax on spirits; all spirits in Bangkok are subject to this taxation; imported spirits are subject to import duty additionally; the result is that premium imported spirits in Bangkok cost 30–50% above their home-country retail prices; Thai-produced spirits (Mekhong, Regency, Thai rum) are taxed differently (lower rate) and have price advantage over imports; (5) Bangkok's tropical cocktail culture: Bangkok's cocktail scene has embraced tropical and Asian ingredient integration — butterfly pea flower (known in Thai as dok anchan, turns bright blue or purple depending on pH) is particularly Bangkok-cocktail-famous; color-changing gin and tonic with butterfly pea flower is one of Bangkok's most photographed cocktail images; Thai herbs in cocktails (galangal, kaffir lime leaf, lemongrass) have created a distinct Bangkok cocktail vocabulary beyond standard Western cocktail lists.",
    action: "Bangkok craft cocktail bars with Thai spirits and tropical ingredients: Vesper Bangkok (Silom/Sathorn area, Asia's 50 Best Bars listed, creative Thai-influenced cocktails); BKK Social Club (Rosewood Bangkok hotel, high-concept bar program); Bambu Bar (Mandarin Oriental, historic Bangkok cocktail bar); Rabbit Hole (Ekkamai, high volume but solid cocktail program, popular with foreigners); Sugar Ray (Ekkamai, casual cocktail bar, accessible quality); Chalong Bay Rum purchase in Bangkok: Villa Market Sukhumvit branches stock it in the spirits aisle; Bangkok liquor stores with good craft spirits: Foodland Supermarket spirit section has better craft selection than Villa Market at some locations.",
  },
  {
    name: "Bangkok Whisky Culture — Thai Whisky, Soda Water Service & Whisky Bars",
    emoji: "🥃",
    summary: "Thai whisky has a distinct character and occupies a central place in Bangkok's social drinking culture: (1) Thai whisky's unique market position: Thailand has its own domestically produced whisky sector; Thai 'whisky' (technically a spirit blend, as most Thai 'whiskies' contain a mix of malted grain, sugar cane molasses, and sometimes rice spirit) is different from Scotch, American, or Japanese whisky; major Thai 'whisky' brands: Mekhong (the original, brown spirit, lower price), Regency (ThaiBev, midrange), Ruang Khao (low-price rice spirit/whisky blend, local market), and most importantly: (2) Hong Thong, Blend 285, and the pub culture: the mid-tier Thai whisky market (Hong Thong, Blend 285, Sangsom — technically a rum but consumed as whisky in Thai culture) forms the foundation of Bangkok's pub and bar drinking culture; these spirits are consistently consumed as a 'set' — a bottle purchased for the table, shared with soda water and ice (bot-style drinking), and consumed over the course of the evening; this bottle service/sharing model is Thailand's dominant drinking culture model at local pubs and restaurants; (3) Thai pub (Pub/Bar) culture: Thai pubs are different from Western bars — typically: full food menu alongside drinks (not just snacks), bottle purchase rather than drink-by-drink ordering (table buys a 750ml bottle of whisky and a crate of soda water), shared consumption across the table with fresh ice, music (often live or DJ), and long evenings (7pm to midnight+); the pub model creates a very social, communal drinking experience; tourist-oriented bars on Khao San Road/Sukhumvit have adapted this toward Western expectations but traditional Thai pubs operate on this model; (4) Bangkok's premium whisky and Japanese whisky scene: Bangkok's luxury hotel bars and specialist whisky bars (there are several Bangkok 'whisky bars' with serious imported collections) carry premium Scotch single malts, bourbon, and — particularly popular in Bangkok's Japanese-influenced premium spirits market — Japanese whisky (Nikka, Suntory Yamazaki, Hakushu, Hibiki); Japanese whisky in Bangkok benefits from proximity to Japan and the large Japanese expat population driving import supply; (5) Bangkok whisky tax context: imported whisky in Bangkok is expensive due to excise and import taxes; Scotch single malt that costs ฿1,000 in the UK or USD $50 in the US can retail in Bangkok at ฿2,500–3,500; duty-free purchase at arrival in Thailand allows 1 liter tax-free (declare more for additional fee); Bangkok's King Power duty-free is an alternative for airport-purchased spirits.",
    action: "Bangkok whisky bars with serious imported selection: Three Monkeys Bar (Sukhumvit, whisky-focused); Woo Bar and Bamboo Bar (Mandarin Oriental, classic Bangkok premium bar experience); Bangkok's resident whisky community: the Bangkok Whisky Club (Facebook group) organizes tastings and events; Japanese whisky in Bangkok retail: Fuji Supermarket (On Nut branch) sometimes carries Japanese whisky selection; Tokyo Mart (Japanese import grocery); premium spirits retail: the best Bangkok premium spirits selection is at Villa Market (Phrom Phong) and at airport duty-free (better selection at Suvarnabhumi BKK than Don Mueang DMK); Thai whisky for cultural experience: order a bottle of Hong Thong + soda water + ice at any Thai pub to experience the standard Thai pub drinking model; cost for a table of four sharing one bottle: approximately ฿500–800 total.",
  },
];

export function BangkokSake() {
  return (
    <div className="rounded-2xl border border-red-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-red-700 mb-3">
        🍶 Bangkok drinks culture — Japanese sake scene, Thai rum & tropical cocktails, Thai whisky culture
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-red-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-red-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-red-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
