const TOPICS = [
  {
    title: "Bangkok Couples Travel — Romantic Spots, Date Experiences & Honeymoon Planning",
    emoji: "💑",
    summary: "Bangkok offers a genuinely diverse romance portfolio that spans from classic luxury to unexpected intimate experiences: (1) Bangkok romantic restaurant tier structure: Bangkok's most romantic dining divides into: (a) Michelin-starred intimacy — Le Du (New Thai cuisine, intimate basement setting), Sühring (German-Thai tasting menu, heritage villa), Côte by Mauro Colagreco (Capella Hotel, Mediterranean); (b) rooftop romance — Vertigo & Moon Bar (Banyan Tree, 61st floor open-air, no reservation required for drinks but dinner requires booking), Mezzaluna (Lebua State Tower, 65th floor, dress code applies), Sirocco (Lebua, the famous hangout from The Hangover Part II); (c) river-view dining — Mandarin Oriental Terrace (the original Bangkok luxury riverside), Peninsula Hotel (Chao Phraya sunset views), The Author (floating pontoon dining, intimate); (d) unexpected romantic — Issaya Siamese Club (Jim Thompson-era house, garden setting), Blue Elephant (heritage building, Silom, Thai royal cuisine); (2) Bangkok date-night activities beyond dinner: sunset river ferry to see temples at golden hour (board at Sathorn at 5:30pm); couple's massage (recommended: Being Massage, Divana Sanctuary, or Let's Relax for mid-tier romance); Thai cooking class for two (Baipai Thai Cooking School, Blue Elephant cooking school); flower markets at Pak Khlong Talat (Yodpiman Flower Market, midnight to 4am is most atmospheric); canal boat tour at dusk (private long-tail boat charter approximately ฿1,500–2,000); (3) Bangkok honeymoon hotel positioning: Bangkok's luxury hotel landscape is exceptional — Mandarin Oriental (legendary property, asking prices ฿15,000–80,000+/night, river view rooms prioritize romance), Peninsula Bangkok (across river from Rattanakosin, quieter than central Bangkok locations), Capella Bangkok (smaller, intimate luxury, Bangrak area), COMO Metropolitan (design hotel, Sathorn), 137 Pillars Suites (all-suite boutique, Sukhumvit, smaller property = more personalized service); (4) Bangkok cultural romance: watching classical Thai dance (Sala Chalermkrung Royal Theatre, Thursday evenings for authentic Khon performance, dress respectfully) provides authentic Thai arts experience; the Lumpini Park sunrise (5:30–7am, exercise and morning light, free) creates a Bangkok shared experience; (5) Budget romantic experiences in Bangkok: free or low-cost romantic Bangkok: watching Wat Arun at sunset from the Tha Tien Pier side (free, best 5:30–7pm); street food dinner for two on Yaowarat at night (under ฿500 total, atmospheric neon and crowds); temple visit at early morning (Wat Pho at 8am before crowds, ฿200 entry each).",
    action: "Bangkok romantic dinner booking: OpenTable, Hungry Hub, or direct hotel website for Michelin/fine dining (book 2–4 weeks ahead for premium venues on weekends); couples Thai massage recommendation: Divana Signature Massage (Sukhumvit Soi 25, quiet spa setting, 2-hour package ฿1,500–2,200/person); rooftop bar peak timing: arrive before sunset (5:30–6pm) for best light photography and beat the queue (Vertigo, Sirocco, Three Sixty Jazz Lounge all get crowded after 7pm); Bangkok honeymoon package hotels: all major luxury hotels have specific honeymoon packages (room upgrade, welcome amenity, spa credit) — book as 'honeymoon' specifically to activate these packages.",
  },
  {
    title: "Bangkok Marriage — Thai Wedding Tradition, Foreigner Marriage Process & Legal Steps",
    emoji: "💍",
    summary: "Getting married in Bangkok involves navigating both Thai legal requirements and cultural considerations for Thai-foreigner couples: (1) Legal marriage registration in Bangkok: Thailand allows foreigners to legally marry in Thailand through civil registration at a District Office (Amphoe); the process requires: (a) Affidavit of Freedom to Marry (certified by your home country's embassy in Bangkok — US Embassy requires appointment, cost $50, provides certified letter confirming no existing marriage); (b) translation and notarization of the affidavit into Thai (private translators, legal firms, or Amphoe District Office translators); (c) presentation of passport and affidavit at chosen Bangkok Amphoe; marriage certificate issued same day in Thai; (d) recognizing the Thai marriage in home country: the Thai marriage certificate must be legalized through Thai Ministry of Foreign Affairs (Legalisation Division, Chaeng Wattana), then taken to your home country's embassy for apostille/recognition; (2) Bangkok Amphoe offices for foreigner marriage registration: Silom District Office (Amphoe Bang Rak, located in Bang Rak District — this is the most commonly used Amphoe for tourist/expat marriages in Bangkok, efficient with foreigner paperwork); Khlong Toei District Office (alternative, less foreigner traffic); Sathon District Office; each Amphoe has slightly different processing efficiency; Bang Rak Amphoe is the traditional choice for Bangkok foreign marriages; (3) Thai traditional wedding elements: a Thai-foreigner couple in Bangkok may have a traditional Thai wedding ceremony (separate from civil registration) — traditional elements include the Khan Maak procession (groom's family carrying engagement gifts), Sai Monkhon (white string looped around couple's heads), water-pouring blessing ceremony (rod nam sang), Buddhist monk blessings (optional but traditional), and Yod Phae (monk's white thread ceremony); these ceremonies are significant cultural events requiring preparation and typically held at a family home or hotel; (4) Bangkok wedding venues: Bangkok has extensive wedding venue infrastructure — international hotels with full wedding planning services (Mandarin Oriental, Shangri-La, Anantara Riverside, Marriott Marquis); outdoor venues (Samut Prakan Bang Nam Phung garden venues, riverside garden settings); rooftop ceremony venues; and temple compound ceremonies for traditional contexts; (5) Dowry (sin sod) considerations in Thai-foreigner marriage: sin sod (bride price/dowry paid by groom's family to bride's family) is a Thai cultural tradition; amounts are symbolic of the groom's financial capacity and the bride's social status; amounts range from ฿100,000 to millions of baht depending on family backgrounds; negotiation is expected and handled through family representatives (yai nai — the matchmaker/negotiator role); foreigner understanding of sin sod as symbolic honor-price (rather than sale) reduces cultural friction.",
    action: "Bangkok Amphoe Bang Rak address: Charoen Krung Road area near Saphan Khao BTS Silom Line; embassy affidavit appointment: US Embassy Bangkok appointment line 02-205-4049 or usembassy.gov/th; UK Embassy Certificate of No Impediment: ukba.homeoffice.gov.uk relevant section; Australian Embassy Certificate of Freedom to Marry: australia.or.th; Thai Ministry of Foreign Affairs document legalization: Chaeng Wattana office, appointment required via consular.mfa.go.th; Bangkok wedding planners for international couples: Angie Silon, HoiAn Belle, Bangkok Wedding by Thom; recommended Bang Rak Amphoe marriage process: arrive with all documents by 9am on a weekday, process typically takes 1–2 hours.",
  },
  {
    title: "Bangkok Solo Female Travel — Safety, Social Scene & Navigating the City Alone",
    emoji: "👩",
    summary: "Bangkok is generally considered safe for solo female travelers with specific awareness of the city's context: (1) Bangkok safety assessment for solo women: Bangkok has lower rates of violent crime against tourists (male or female) compared to many global cities; the primary risks for solo female travelers are non-violent: tourist scams, overcharging, harassment from tuk-tuk drivers and bar touts, and unwanted attention in nightlife areas; physical safety concerns are real but statistically less common than non-violent nuisances; (2) The high-risk Bangkok zones for solo women at night: the tourist entertainment zones — Khao San Road (backpacker zone, heavily intoxicated crowds), Nana Plaza/Soi Cowboy area (sex tourism concentration), Patpong (night market and sex tourism mix) — are areas where solo female travelers face more harassment and unwanted attention; awareness of these zones and navigation of them with purpose (rather than drifting through) reduces incidents; (3) Solo female travel Bangkok practical safety: always tell someone your location when going out at night; use Grab for transport (provides tracking and accountability vs. random taxis); avoid accepting food or drinks from strangers (drink spiking is documented in Bangkok nightlife, primarily in mixed-gender party environments); maintain basic digital location sharing with a trusted contact; Thailand has dedicated tourist police (1155 English hotline, booths at major tourist areas); (4) Bangkok solo female social scene: Bangkok has a substantial and welcoming solo female traveler community; Hostel social events (Lub d, The Yard, Bodega Hostel Bangkok) provide safe social introductions; solo female Facebook groups for Bangkok travelers (Bangkok Girls Collective, Women of Bangkok) provide city knowledge and social connections; cooking classes, yoga retreats, and Muay Thai camps all attract solo female travelers and provide social context; (5) Cultural respect reducing risk: dressing modestly outside beach/tourist areas (shoulders and knees covered near temples, residential areas) reduces unwanted attention; respectful behavior in Thai cultural contexts generally receives respectful treatment in return; Thai cultural codes around 'face' mean most Thai men will respect a clear, polite, but firm 'no' expressed without aggression.",
    action: "Bangkok solo female traveler resources: Women of Bangkok Facebook group (community advice, meetups); solo female-friendly Bangkok neighborhoods: Ari (quiet, residential, low harassment), Silom during day (business area, safe), Phrom Phong/Thong Lo (upscale residential Sukhumvit, relatively calm); recommended solo female accommodation: hostels with active social programs (Lub d, The Yard) for social connections; standalone boutique hotels in Ari or Phrom Phong for private secure experience; emergency resources: Tourist Police 1155 (English 24-hour); Bangkok's best solo female Facebook group activity: check Bangkok Expats women-focused groups for current meetup schedules; Muay Thai camp for women: Lanna Muay Thai (Silom area classes), Core Muay Thai (Khaosan area) both have structured female-friendly training sessions that double as social introductions.",
  },
];

export function BangkokRomance() {
  return (
    <div className="rounded-2xl border border-pink-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-pink-700 mb-3">
        💑 Bangkok love & relationships — romantic experiences, marriage process & solo female travel
      </h2>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-pink-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-pink-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
