const TOPICS = [
  {
    title: "Bangkok Royal Ceremonies — What They Are, When They Happen & Can You Watch",
    emoji: "👸",
    summary: "The Thai monarchy conducts regular ceremonial events in Bangkok that are occasionally visible to respectful observers: (1) The Thai royal ceremony calendar: the Thai royal household conducts ceremonies throughout the year on the Buddhist and royal calendars; major royal ceremonies include: Coronation Day (May 4–6, King Rama X's coronation 2019, not annually but commemorated); Royal Barge Procession (very infrequent — last 2019 for coronation, 2012 for Diamond Jubilee, 2006 for 60th anniversary of reign — occurring only for extraordinary royal occasions); Ploughing Ceremony (Raek Na Khwan, Royal Field/Sanam Luang, annually in May — marks the start of the agricultural season, public viewable from Sanam Luang); Loi Krathong and royal participation in Bangkok festivals; (2) Royal Ploughing Ceremony (Raek Na Khwan): the Ploughing Ceremony held annually at Sanam Luang (Royal Field) in May (exact date determined by Brahmin astrologers) is the most accessible royal ceremony for visitors; the ceremony involves royal oxen ploughing a sacred furrow on Sanam Luang while Brahmin priests chant; then the oxen are offered seven types of food/drink and their choices predict the year's agricultural fortune; the ceremony is both Hindu-Brahmin and royal in character, one of Bangkok's oldest continuing court ceremonies; public viewing is possible from the Sanam Luang perimeter; (3) The Royal Barge Procession — Bangkok's most spectacular ceremony: the Royal Barge Procession (Krabuang Ruea) is one of the most spectacular royal ceremonies in the world; approximately 52 barges carrying thousands of oarsmen in traditional court dress transport the King along the Chao Phraya River; the procession occurs only for the most exceptional royal occasions and cannot be predicted years ahead; viewing positions along the Chao Phraya River banks and from the Chao Phraya express boats provide best visibility; (4) Lèse-majesté awareness and royal family in public: Thailand's lèse-majesté laws (Section 112 of the Penal Code) make any criticism of the royal family — even by foreigners in private contexts — a criminal offense in Thailand with imprisonment of 3–15 years per offense; visitors should be aware that positive public discussion and respect for the royal family is the safe approach; when the royal family motorcade passes, bystanders typically stop and show respect; (5) Buddhist royal ceremonies at Wat Phra Kaew: the King leads specific religious ceremonies at the Temple of the Emerald Buddha (Wat Phra Kaew) including the three seasonal changing of the Emerald Buddha's raiment — the royal robes are changed by the King himself three times per year at the beginning of each Thai season; these ceremonies are closed to the public but the Grand Palace visits at other times allow seeing the Emerald Buddha in its seasonal robes.",
    action: "Royal Ploughing Ceremony attendance: check the Thai Royal Household Bureau announcement (typically confirmed 2–4 weeks before the event in May); Sanam Luang is open and the ceremony is observable from the perimeter; arrive 1–2 hours before ceremony start for positioning; respectful dress (not shorts or tank tops) strongly recommended; Royal Barge Procession: when announced (very infrequent), positions along the Chao Phraya River at Phra Pinklao Bridge area, the area between Phra Pin Klao Bridge and Phra Phuttha Yodfa Bridge, provide viewing; Chao Phraya Express Boats are usually suspended during the procession; Sanam Luang for royal ceremony observation generally: the Royal Field is the civic ceremony space — also used for royal cremation ceremonies (when these occur) and annual Wan Chakri (Chakri Day, April 6, commemoration of Chakri dynasty founding).",
  },
  {
    title: "Bangkok Graduation Season — Ceremonies at Sanam Luang & Thai University Culture",
    emoji: "🎓",
    summary: "Bangkok's university graduation ceremonies (piti rap prathinniyabat) are elaborate formal events that provide a window into Thai academic culture and the monarchy's role in education: (1) Thai graduation ceremony uniqueness: Thai university graduation ceremonies are presided over by royal family members — for the most prestigious universities (Chulalongkorn University, Thammasat University, Mahidol University, Kasetsart University), the King or royal family member personally presents diplomas to graduates; this creates a scale and formality unlike graduation ceremonies in most countries; Chulalongkorn University's graduation ceremony at Sanam Luang (across from the university) is particularly large (the university has approximately 40,000 students); (2) The seasonal graduation calendar: Thai university graduations are clustered in specific months — typically November through January for the major universities; the period creates a distinctive Bangkok visual — graduates in formal academic dress (black academic gowns with university-specific accessories, sashes, and insignia) are visible throughout central Bangkok and particularly around the universities and Sanam Luang; (3) Thai academic dress and photography culture: Thai graduation photography is an elaborate cultural practice — graduates hire professional photographers for multi-day photo sessions; the photography includes formal shots at the university, landmark photos at Sanam Luang or Grand Palace, and commemorative images; photography studios specializing in graduation photos are common near major universities; graduates and families celebrate extensively with dinners and family gatherings; (4) Sanam Luang during graduation season: the large open Sanam Luang grounds serve as a staging area for graduation photography (graduates come in groups to photograph with the Grand Palace backdrop); the visual of thousands of graduates in academic dress against Bangkok's royal heritage is unusual and striking; (5) International student community: Bangkok's universities have growing international student communities (Chulalongkorn International programs, Thammasat, ABAC, Mahidol International College); international students participate in the same graduation ceremony traditions including the royal presentation (for Chulalongkorn students, this involves the King or royal family member).",
    action: "Viewing Bangkok graduation season: November–January at Sanam Luang (early morning, 7–10am, before the Bangkok heat intensifies) provides the clearest view of graduation photography gatherings; Chulalongkorn University's campus (adjacent to BTS Siam) is open for walking through the campus; the university's central area has a large King Rama V statue and formal buildings; Graduation photography observation: completely non-intrusive; Thai graduates and families are generally happy to share the celebration with friendly observers; photography of graduation groups is acceptable with polite non-intrusion.",
  },
  {
    title: "Bangkok Funerals — Buddhist Funeral Traditions, Cremation Customs & Temple Crematoriums",
    emoji: "🕯️",
    summary: "Thai Buddhist funeral customs are among Bangkok's most culturally distinct practices and visitors may inadvertently observe or be invited to participate: (1) Thai Buddhist funeral structure: Thai Buddhist funerals typically last multiple days (3, 7, 50, or 100 days for different merit-making phases); the core ceremony involves: (a) merit-making ceremonies at the home or temple over several evenings (Buddhist monks chant, merit accumulated for the deceased); (b) final cremation ceremony (Phra Ratcha Phithi Phloengsop or community cremation); Bangkok's older temples (Wat Arun, Wat Suthat, Wat Pho and many neighborhood temples) all have crematoriums on the grounds; (2) Merit-making for the dead: central to Thai Buddhist funeral culture is the belief that living family members can transfer merit to the deceased; the chanting monks at the funeral home conduct pujas that generate merit; family members observe precepts during the mourning period; white is the traditional Thai mourning color (not black); formal mourning dress is white or black for different contexts; (3) Royal cremations at Sanam Luang: the royal cremation is among Thailand's most elaborate ceremonies; King Bhumibol's (Rama IX) royal cremation in 2017 was attended by hundreds of thousands of Thais and involved a massive temporary crematorium structure at Sanam Luang; the crematorium took months to construct with intricate traditional Thai artistic designs and was dismantled after the ceremony; royal cremations are extremely rare national events; (4) Temple crematoriums in Bangkok: virtually every Buddhist temple in Bangkok has a crematorium (sometimes ornately decorated, sometimes simple); the crematoriums operate regularly for community funerals; visitors walking temple grounds may encounter cremation ceremonies in progress; maintaining respectful behavior (quiet, not photographing unless clearly acceptable) and keeping appropriate distance is appropriate; (5) Cultural attitudes toward death in Thai Buddhism: Thai Buddhism has a more open relationship with death than many Western secular cultures; the rebirth/karma framework means death is a transition, not an ending; this leads to pragmatic engagement with death ceremonies; merit accumulated during the mourning period is genuinely significant for the family; the social aspect of gathering to support the family through the mourning period creates strong community bonds through the funeral ceremony.",
    action: "Observing Thai funeral customs: visitors staying near neighborhoods with active temples may hear the sound of chanting from evening merit-making ceremonies — this is a normal part of Bangkok residential life; respectful non-participation (walking nearby, not entering during active ceremony) is appropriate; Wat Suthat and Wat Saket (Golden Mount) have crematoriums that are occasionally active — approach with full respect; royal cemetery: Wat Ratchabophit (Ratchabophit Road, near the Grand Palace) serves as the burial/urn site for Thai royalty who are not given full cremation honors; beautifully decorated Victorian-Gothic temple compound with royal memorial tablets.",
  },
];

export function BangkokCeremony() {
  return (
    <div className="rounded-2xl border border-purple-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-purple-700 mb-3">
        👸 Bangkok ceremonies — royal events & viewing, graduation season & Buddhist funeral culture
      </h2>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-purple-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-purple-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
