const SPOTS = [
  {
    name: "Bangkok Money & ATMs — Fees, Best Exchange Rates & Avoiding Tourist Currency Traps",
    emoji: "💸",
    area: "Bangkok ATM locations: virtually every convenience store (7-Eleven, Lawson, Family Mart), every bank branch, every shopping mall, most hotel lobbies, and most BTS/MRT stations; Bangkok ATM density is extremely high — in tourist areas (Sukhumvit, Khao San, Siam) ATMs are rarely more than 50–100m apart; Bangkok currency exchange kiosks: SuperRich (multiple locations — orange and green branded, different franchises, both reputable): Ratchaprasong area, Siam Square, and other central locations; Vasu Exchange (competitive rates, Silom area); airport exchange: Suvarnabhumi Airport has multiple exchange booths at arrivals — better rates than hotel, though slightly less than city center; Don Mueang Airport exchange: available but rates less competitive than central Bangkok",
    price: "Bangkok money costs: Thai ATM foreign card withdrawal fee: ฿220 per withdrawal (imposed by Thai banks on ALL foreign cards regardless of card tier, as of 2020); this fee applies to every ATM withdrawal from a foreign card; strategic response: withdraw larger amounts less frequently to minimize per-transaction fee impact; ฿220 on ฿5,000 withdrawal = 4.4% fee vs ฿220 on ฿1,000 = 22% fee; SuperRich exchange rate spread: approximately 0.5–1% from mid-market rate (very competitive); hotel exchange rate: typically 3–5% below market — avoid for large amounts; airport exchange (arrivals): approximately 1.5–2.5% below market — acceptable for immediate cash needs",
    why: "Bangkok's currency exchange ecosystem is more nuanced than the standard ATM-only advice: (1) The ฿220 Thai ATM fee reality: since 2017, ALL Thai bank ATMs charge a ฿220 foreign transaction fee regardless of your card type; premium cards with no ATM fees only waive the foreign bank's own fee, not Thailand's ฿220 surcharge; this fundamentally changes the math for frequent small withdrawals; optimal strategy is fewer, larger withdrawals rather than frequent small ones; (2) SuperRich vs. ATM rate comparison: SuperRich currency exchange shops offer exchange rates typically 1–3% better than ATM withdrawal rates after factoring in the ฿220 fee and your home bank's exchange rate; for large amounts (฿5,000+), SuperRich consistently beats ATM; (3) Dynamic Currency Conversion (DCC) — Thailand's tourist currency trap: when using a foreign card at Thai ATMs or point-of-sale terminals, you may be offered the choice to pay in your home currency rather than Thai Baht; always choose to pay in Thai Baht; choosing your home currency activates DCC which applies an unfavorable exchange rate (typically 3–7% worse); decline DCC every time; (4) Thai Baht denominations: ฿1,000 (brown, largest), ฿500 (purple), ฿100 (red), ฿50 (blue), ฿20 (green), coins: ฿10, ฿5, ฿2, ฿1; Bangkok's street food and market vendors often prefer exact change or ฿100 bills — carrying ฿50 and ฿100 bills for market and street food is more practical than ฿1,000 bills; (5) Digital payment in Bangkok: Bangkok's PromptPay QR code payment system is widely used among Thai residents but requires a Thai bank account; for visitors, cash is still the most universally accepted; credit cards (Visa/Mastercard) are accepted at most hotels, shopping malls, and higher-end restaurants; many street food vendors and market stalls are cash-only; Grab app payments use international credit cards.",
    tip: "Bangkok money management: (1) Withdrawal strategy: withdraw ฿5,000–10,000 per ATM visit to minimize the ฿220 per-transaction fee impact; most Bangkok ATMs dispense ฿3,000–30,000 per transaction; (2) SuperRich locations: the SuperRich orange and green branches are at CentralWorld (easy access from BTS Chit Lom), at Siam Square One area, and several Sukhumvit locations — Google SuperRich Bangkok for nearest current location; exchange is immediate (no waiting); bring passport for amounts over ฿30,000; (3) Wise or Revolut cards: Wise, Revolut, and Charles Schwab US are the most widely used foreign cards in Bangkok for minimizing fees; Wise and Revolut still pay the ฿220 Thai ATM fee but offer mid-market exchange rates; Charles Schwab US account refunds all ATM fees globally including the ฿220 Thai fee; (4) Airport exchange on arrival: exchanging ฿2,000–3,000 at the airport on arrival provides immediate cash for transport and initial expenses without the ATM fee; the airport rate is acceptable for this small amount; (5) Cash safety in Bangkok: carrying more than ฿10,000 in cash at one time creates unnecessary risk in crowded tourist areas; Bangkok has bag-snatching from motorcycles and pickpocketing in crowded markets; keep daily spending cash in an easily accessible pocket and remaining cash secured.",
  },
  {
    name: "Bangkok PromptPay & Cashless Thailand — Thai Digital Payment Ecosystem Explained",
    emoji: "📱",
    area: "Thai digital payment infrastructure: PromptPay QR codes displayed at most restaurants and cafes, many market stalls, many taxis (QR code on the meter), parking facilities, government service payment points, and virtually all retail; LINE Pay (integrated into the LINE messaging app) available at registered merchants; TrueMoney Wallet used for top-up and online payments; Rabbit LINE Pay (linked to the rabbit transit card system); AirPay and ShopeePay for e-commerce payments; 7-Eleven Bangkok accepts Visa/Mastercard contactless at most locations; Grab app accepts international credit cards (Visa/Mastercard) for cashless rides and food delivery",
    price: "Thai digital payment costs: PromptPay transactions — free for consumers (no fee); Grab app payment — standard Grab pricing (no surcharge for card payment); 7-Eleven contactless — standard item pricing; KBank K PLUS tourist account (if still available): check for current fees at KBank branch or airport; international credit card at Bangkok malls and hotels — may have foreign transaction fee (typically 1.5–3% from your home bank, not the Thai merchant); currency conversion at point of sale — zero if you choose Thai Baht payment (avoid DCC); TrueMoney tourist wallet: check current limits and fees",
    why: "Thailand's digital payment infrastructure has transformed Bangkok commerce in the last 5 years, with significant implications for both residents and visitors: (1) PromptPay — Thailand's universal QR payment system: PromptPay is Thailand's inter-bank real-time payment system where residents link their national ID or phone number to a PromptPay account at any Thai bank; QR code-based payments allow instant money transfer between any Thai bank accounts; the system has achieved near-universal adoption among Bangkok businesses and consumers; (2) Bangkok's QR payment adoption across sectors: younger Thais conduct most transactions via QR payments rather than cash; older vendors in traditional markets still primarily accept cash; (3) Visitor limitations with Thai digital payments: as a visitor without a Thai bank account, PromptPay is not accessible; opening a Thai bank account as a visitor requires passport plus work permit or non-immigrant visa — tourist visas are not sufficient for most banks; non-immigrant visas (business, retirement) can open basic accounts at SCB, Kasikorn Bank (KBank), Bangkok Bank, or Krungthai Bank; (4) International cards at Bangkok merchants: Visa and Mastercard contactless payment works at most malls, hotels, and larger restaurants throughout Bangkok; AMEX is accepted at most 5-star hotels and large retailers but less commonly at independent restaurants; UnionPay acceptance is expanding significantly in Bangkok driven by Chinese tourism demand; (5) Bangkok's cash ecosystem: despite digital payment growth, cash remains essential for street food vendors, traditional markets, motorcycle taxis, and many neighborhood shops; maintaining ฿500–1,000 in small bills allows seamless payment at these venues.",
    tip: "Bangkok visitor digital payment: (1) Grab app for cashless Bangkok: the Grab app accepts international credit cards for Grab rides and Grab food delivery — the most useful cashless system for visitors; set up Grab before arriving in Bangkok; (2) KBank K PLUS tourist account: Kasikorn Bank has offered a tourist digital payment option for short-term visitors — check current availability at KBank branch at Suvarnabhumi Airport arrival hall; requires passport; provides limited digital wallet functionality; (3) 7-Eleven contactless: Bangkok 7-Eleven branches accept Visa/Mastercard contactless at most locations — useful for daily purchases, phone top-up (DTAC, AIS, True Move H top-up cards), and convenience items without cash; (4) Hotel and hospital payments: most Bangkok hotels, hospitals, and shopping malls accept international cards without issue; inform your bank of Thailand travel dates before departure to prevent fraud blocks; (5) QR code observation: even without using PromptPay, observing how Thais pay is culturally interesting — the smartphone-to-QR exchange at Bangkok markets and restaurants represents the complete digitization of daily commerce that happened remarkably quickly from 2018–2023.",
  },
  {
    name: "Bangkok Cost of Living — What It Really Costs to Live in Bangkok at Different Budget Levels",
    emoji: "🏙️",
    area: "Bangkok budget geography: street-food Bangkok (outer residential areas, local markets, minimal AC); mid-range expat Bangkok (BTS/MRT-accessible, Sukhumvit mid-range, local and international mix); comfortable expat Bangkok (prime Sukhumvit, Silom, Sathorn); luxury Bangkok (branded serviced apartments, embassy-area houses, premium everything); Bangkok's cost structure creates parallel lifestyle tiers within the same city boundaries; cost comparison benchmark cities: Bangkok luxury is approximately 50–70% of equivalent Singapore or Hong Kong cost; Bangkok mid-range is approximately 30–40% of equivalent London or New York; Bangkok street-level is approximately 10–20% of Western city equivalent",
    price: "Bangkok monthly cost tiers: street-level resident (฿15,000–25,000/month): shared or basic studio room ฿3,000–7,000, street food ฿50–100/meal, motorbike/bus transport; mid-range single expat (฿40,000–80,000/month): 1BR Sukhumvit condo ฿15,000–25,000, mixed dining ฿150–500/meal, Grab/BTS transport ฿2,000–4,000, gym ฿800–2,000, health insurance ฿1,500–3,000; comfortable expat (฿80,000–150,000/month): 2BR prime condo ฿30,000–50,000, quality restaurant dining, comprehensive health coverage; luxury (฿150,000+/month): luxury apartment/house ฿60,000–200,000, private driver, Michelin dining, international school per child ฿33,000–67,000/month",
    why: "Bangkok's cost structure differs dramatically by budget level, creating multiple parallel cities within the same geographic area: (1) Street-level Bangkok budget (฿15,000–25,000/month): a single person can live adequately in Bangkok on ฿15,000–25,000/month by eating primarily at street food and market restaurants (฿50–100/meal), sharing or renting a basic studio in outer Bangkok (฿3,000–7,000/month), using public transport (BTS/MRT monthly pass ฿1,150–1,600, motorcycle taxi ฿15–30/trip); this is approximately how Bangkok's working class residents live; Thai minimum wage is approximately ฿354/day (as of 2024); (2) Mid-range expat Bangkok (฿40,000–80,000/month): 1-bedroom condo in Sukhumvit area (฿15,000–25,000/month), mixed local and international restaurants (฿150–500/meal), gym membership (฿800–2,000/month), BTS and Grab transport (฿2,000–4,000/month), health insurance (฿1,500–3,000/month), entertainment (฿5,000–10,000/month); (3) Comfortable Bangkok expat (฿80,000–150,000/month): 2-bedroom condo in prime Sukhumvit/Silom area (฿30,000–50,000/month), dining at quality restaurants 3–5x/week (฿500–2,000/meal), premium gym, comprehensive health insurance, domestic helper 2x/week (฿2,000–4,000/month); (4) Bangkok luxury (฿150,000+/month): luxury serviced apartment or expat house (฿60,000–200,000/month), Michelin-level dining regularly, private driver or car with driver (฿30,000–60,000/month), private international school for children (฿33,000–67,000/month per child); (5) Bangkok cost trajectory: Bangkok's cost advantage over Singapore and Hong Kong has been narrowing since 2015 as premium property and international dining prices converge toward regional peers; the street-food and local transport tier remains extremely affordable by international standards.",
    tip: "Bangkok budget planning: (1) Cost resources: Numbeo.com Bangkok (user-submitted cost data useful for baseline comparison), Bangkok Expats Facebook group for current real-world cost benchmarks; (2) Accommodation cost discovery: Hipflat.co.th (condo rental listings and market data), DDproperty.com (broader rental listing database); (3) Monthly visitor budget template: accommodation ฿25,000–80,000 (mid-range to luxury), food ฿15,000–40,000 (street food to restaurant mix), transport ฿3,000–8,000, activities/attractions ฿5,000–15,000, shopping/miscellaneous ฿10,000–50,000; total visitor budget approximately ฿58,000–193,000 per month depending on lifestyle standard; (4) Bangkok's best cost-value zones: Ari neighborhood (BTS Ari) has strong value for mid-range expat lifestyle — quality cafes, local restaurants, accessible market food all within 500m; On Nut (BTS On Nut) provides lower-cost Sukhumvit-area living with Japanese community amenities; (5) Food cost mastery: eating at least 2 of 3 meals at local restaurants and market stalls (฿50–100/meal) dramatically reduces monthly food spend without sacrificing Bangkok's extraordinary food quality; the best food in Bangkok is rarely at the most expensive restaurants.",
  },
];

export function BangkokATM() {
  return (
    <div className="rounded-2xl border border-emerald-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-emerald-700 mb-3">
        💸 Bangkok money essentials — ATM fees & exchange rates, PromptPay digital payments & real cost of living
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-emerald-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-[10px] font-mono text-emerald-700 text-right">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-emerald-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
