const SPOTS = [
  {
    name: "Bangkok Bicycle Infrastructure — Cycling Routes, Bike Lanes & Where It's Actually Safe",
    emoji: "🚲",
    area: "Bangkok cycling routes: Bang Kachao (Green Lung of Bangkok, south Phra Pradaeng peninsula across river from On Nut) — car-free community roads through orchards and canals, best cycling in Bangkok; Chao Phraya riverside path (limited continuous sections); Chatuchak Park (closed loop, safe for casual cycling, not extensive); Rotfai Park (Srinakarin area, eastern Bangkok, dedicated cycling track within park); Bang Sue area: partial elevated cycling track; Kanchanaburi (90km from Bangkok, excellent day-cycling); Bang Krajao ferry: Sathon to Bang Krachao crossing, ฿6–8 per crossing; bike-friendly areas: early morning Sanam Luang (5–8am, before traffic), Dusit Palace park perimeter (limited), Lumpini Park running/cycling path (short loop)",
    price: "Bang Krachao bicycle rental: ฿40–100/hour or ฿150–300/day from pier-side rental shops (several operators at the ferry landing); Bangkok bicycle purchase: Giant Thailand, Trek Thailand, Specialized Bangkok for new bikes (฿8,000–100,000+ range); Decathlon Bangkok (multiple locations, MBK area, Central Westgate) for budget-to-mid-range bikes and equipment; rental bikes for extended urban use: Bangkok has limited bike-share infrastructure vs. Chiang Mai (which has much better cycling infrastructure); folding bikes + BTS: permitted on BTS outside rush hours; Grab bicycle (if available in Bangkok area): check app",
    why: "Bangkok is not primarily a cycling city but has specific exceptional cycling contexts: (1) Bang Krachao as Bangkok's cycling paradise: the Phra Pradaeng peninsula (Bang Krachao, 'Green Lung'), separated from Bangkok by a curved section of the Chao Phraya river, is Bangkok's most exceptional cycling destination; the entire peninsula is a car-limited community with narrow lanes through orchards, community gardens, temples, and canal-side paths; cycling Bang Krachao on a weekend morning (7–11am) is the most pleasant outdoor activity accessible from central Bangkok; the ฿6–8 ferry from Klong Toei pier to the peninsula creates the car-free separation; (2) Bangkok's cycling infrastructure challenge: Bangkok's road network was designed for vehicles, not bicycles; most Bangkok roads have no designated cycling lanes; cycling in Bangkok proper (on main roads) is genuinely dangerous — narrow shoulders, fast-moving traffic, high vehicle density, and taxi/bus door zones create serious cycling hazards; (3) Community cycling movements: Bangkok has active cycling advocacy communities (BicyclePlus, Bangkok Cycling Club) that organize safe group rides, advocacy for better infrastructure, and critical mass-style rides; the group ride context provides safety-in-numbers advantages unavailable to solo cyclists; (4) Cycling for Chatuchak market: some Bangkok residents cycle to Chatuchak Weekend Market (from BTS Mo Chit/northern Bangkok neighborhoods) using quieter sois and the canal path; this is a niche but established Bangkok cycling behavior that avoids the BTS crowd; (5) Folding bicycle culture: Bangkok's cycling-commuter community has adopted folding bicycles (Brompton is the prestige choice, Tern and Dahon for mid-range) specifically because folding bikes are permitted on BTS Skytrain outside rush hours; a folding bike + BTS combination allows cycling from the station to a destination without full road cycling exposure.",
    tip: "Bangkok cycling practical guide: (1) Bang Krachao cycling timing: arrive at the Klong Toei-Sathorn ferry pier (accessible from BTS Chong Nonsi + 10-min walk to pier) before 8am on weekends to beat the weekend crowd buildup; the cycling is best 7–11am before the heat becomes oppressive; return ferries run throughout the day; (2) Bike rental quality at Bang Krachao: Bang Krachao's rental bikes are a mixed quality fleet; test brakes before riding, check tire inflation, and negotiate if the offered bike has obvious issues; the peninsula roads are smooth and flat — gear quality matters less than working brakes; (3) Bangkok cycling safety equipment: any Bangkok cycling (even in Bang Krachao) benefits from helmet (most rental shops don't provide — bring your own); hydration (water bottle or hydration pack essential in Bangkok heat); sun protection (arms and face particularly); mosquito repellent (Bang Krachao's canal environment has biting insects); (4) Public holidays and Bang Krachao: Bang Krachao is very crowded on Thai public holidays and long weekends; the area retains its car-free appeal but the cycling lanes fill with other cyclists, families, and tourists; weekday morning visits (9am–noon on non-holiday weekdays) offer the most tranquil experience; (5) Bangkok bicycle shopping: Decathlon in Bangkok (multiple locations, easiest being near Central Westgate) offers the best price/selection combination for new cyclist purchases; Giant Thailand and Trek Thailand have Bangkok retail stores for premium bikes; cycling accessories (locks, lights, helmets) are better priced at Decathlon than at independent bike shops in tourist areas.",
  },
  {
    name: "Bangkok Boat Transport — River Ferries, Canal Boats & Getting Around by Water",
    emoji: "⛵",
    area: "Bangkok water transport network: Chao Phraya Express Boat (river ferry, yellow/orange/green/blue flag boats serving 36 piers from Nonthaburi in the north to Sathorn/Central Pier in the south); Sathorn Central Pier (most important pier, adjacent to Saphan Taksin BTS); Tha Tien Pier (to Wat Arun, most tourist-used river crossing); Maharaj Pier (to Wat Pho, Grand Palace riverside access); Wang Lang Pier (Siriraj Hospital, traditional market, Thonburi residential access); Khlong Saen Saep Express Boat (canal boat, runs east-west from Pratunam Pier to Bang Kapi, 28 stops, passes through Asok/Nana area); River City Pier (to shopping complex, near Si Phraya Pier); Asiatique Pier (free shuttle from Sathorn Pier to Asiatique shopping complex, evening service)",
    price: "Chao Phraya Express Boat: tourist day pass ฿200 (unlimited hops on tourist orange flag boat); standard river ferry: ฿10–40 per trip depending on flag/distance; Khlong Saen Saep canal boat: ฿12–20 per segment, fixed flat rate sections; Wat Arun cross-river ferry (Tha Tien to Wat Arun): ฿6 per person; standard cross-river passenger ferry (many casual crossings): ฿3–5 per person; Chao Phraya tourist boat (orange flag): ฿30–50 per segment, day pass ฿200; comparison: canal boat Pratunam to Asok costs ฿12–15 vs. ฿50–150 via Grab for same route",
    why: "Bangkok's water transport is one of the city's most practical and scenic transport layers, significantly underused by visitors: (1) Khlong Saen Saep's practical value: the Khlong Saen Saep Express Boat (the long-tail style canal boat service running through Bangkok's main east-west canal) is genuinely the fastest way to travel from Bangkok's western neighborhoods (Pratunam, Victory Monument area) to eastern Sukhumvit neighborhoods without entering Bangkok's surface road traffic; the boat eliminates the Sukhumvit Road traffic entirely for that east-west corridor; travel time Pratunam to Asok: approximately 15–20 minutes by boat vs. 30–60 minutes by road; (2) River ferry scenic value: the Chao Phraya Express Boat provides Bangkok's most scenic commute — traveling along the river between landmark piers (Rattanakosin area temples visible, Thonburi riverside, Asiatique, Wat Arun opposite Tha Tien Pier) combines transport with Bangkok's premier water-level view; (3) Cross-river ferry culture: Bangkok maintains numerous small passenger ferries crossing the Chao Phraya at specific points (connecting Bangkok and Thonburi communities); these ฿3–5 per person crossings are entirely utilitarian, used by Thai commuters, and provide the most authentic Bangkok river transport experience; the Tha Tien to Wat Arun crossing is the most visitor-relevant; (4) Long-tail boat charters: private long-tail boat hire (60–90 minute canal tour, approximately ฿1,500–2,000 per boat holding 6–8 people) provides access to Bangkok's inner canal network (Bang Rak and Thonburi klongs) that scheduled boat services don't reach; the long-tail boat tours into Bangkok Noi and Bangkok Yai canals pass canal-side communities, floating temples, and riverside houses; (5) Timing and crowd patterns on river boats: Chao Phraya Express Boats are most crowded during rush hours (7–9am northbound toward work; 5–8pm southbound toward Sathorn); tourist orange flag boats are most crowded at tourist destination departure times (mornings to Grand Palace, evenings back to Sathorn); off-peak early afternoon is the most comfortable river ferry travel time.",
    tip: "Bangkok water transport practical guide: (1) Khlong Saen Saep boarding practice: the canal boat stops are very brief (10–20 seconds) at each pier; boarding requires positioning at the pier edge before the boat arrives and stepping onto the moving boat quickly (the boat barely stops); staff help passengers aboard but hesitation results in missing the boat; (2) Canal boat spray management: the Khlong Saen Saep boats travel at speed through a narrow canal; spray from the bow, other boats, and canal waves can wet sitting passengers; the cloth/tarpaulin siding can be raised to protect from spray; sitting away from the open sides during fast sections reduces spray exposure; (3) River ferry flag system: the Chao Phraya Express Boat runs multiple services identified by flag colors — orange flag boats are tourist-oriented, stop at all major piers, have English announcements; yellow, green, and blue flag boats are faster express services stopping at fewer piers; locals use the express boats; tourists use orange flag or day pass boats; (4) Night ferry experience: the Chao Phraya river at night (taking an evening ferry from Sathorn to Tha Tien area) provides Bangkok's most atmospheric evening experience — temple illumination, residential lights reflecting on water, boat lanterns; the river ferry as an evening experience (not just utilitarian transport) is worth planning for; (5) Asiatique shuttle ferry: the free tourist shuttle ferry from Sathorn Central Pier to Asiatique (every 30 minutes, 4pm–11pm) is the most convenient transport to Asiatique from BTS and operates as a value add for the shopping complex.",
  },
  {
    name: "Bangkok Motorbike Taxi — Vest Riders, Orange Vests & The City's Fastest Last-Mile Transport",
    emoji: "🏍️",
    area: "Motorbike taxi system: Bangkok's motorbike taxis operate throughout the city at registered motorcycle taxi 'queues' (stands) at the entrances of major sois, BTS stations, and busy intersections; identified by orange or colored vests; registered stands (with queue and fixed pricing list) vs. freelance riders (without official stand); BTS Skytrain station exits: most BTS station exits have official motorbike taxi stands providing last-mile service from station to final destination; major hotel areas: Sukhumvit soi entrances have established motorbike taxi stands serving apartment residents and hotel guests; Grab Bike: motorcycle taxi equivalent available via Grab app, provides metered/estimated pricing",
    price: "Motorbike taxi pricing structure: short distance (under 1km within soi): ฿10–20; medium distance (1–3km): ฿20–50; longer rides in traffic: ฿50–150; Grab Bike pricing: typically 20–50% above registered motorbike taxi stand pricing but fixed pre-journey; helmet provision: most registered stand riders carry a passenger helmet (hygiene varies); some riders carry no passenger helmet; negotiation for longer routes: standard, offer based on distance estimate; comparison: Grab motorbike from BTS Asok to Soi 11 (200m): approximately ฿30 vs. walking 5 minutes",
    why: "Motorbike taxis are Bangkok's most efficient solution to the last-mile problem and deserve understanding as a transport option: (1) The motorbike taxi's essential role: Bangkok's BTS Skytrain stations are typically located on major arteries; residential, dining, and business destinations are typically 200m–1km into adjacent sois (side streets); the motorbike taxi perfectly solves this connection — quicker than Grab cars, able to filter through soi traffic, and inexpensive for short trips; (2) Orange vest registration system: Bangkok's registered motorbike taxi riders wear distinctive orange vests with their registration number; registered riders have been background-checked and operate within the Transport Department framework; freelance riders (without official vest, operating independently near major locations) are less regulated; using registered orange vest riders from official stands provides better accountability; (3) Traffic filtering advantage: Bangkok's greatest motorbike taxi advantage is the ability to filter through stationary traffic — during Bangkok's peak traffic hours, motorbike taxis move while Grab cars sit stationary; the time advantage in congested conditions can be substantial (10–20 minutes faster than car for equivalent distance during peak); (4) Destination communication: communicating destinations to motorbike taxi riders often requires showing the address in Thai script or Google Maps; most riders know major landmarks but may not know obscure soi addresses; showing the phone screen with Google Maps destination is the most reliable communication method; (5) Risk assessment: motorbike taxi riding in Bangkok carries higher inherent risk than car travel; Bangkok has high motorcycle accident rates; the statistical risk per journey is low but not zero; wearing the provided passenger helmet (even if uncomfortable) significantly reduces head injury risk in low-speed accidents (the most common Bangkok motorcycle incidents).",
    tip: "Bangkok motorbike taxi practical guide: (1) Helmet negotiation: asking 'mee helmet mai?' (do you have a helmet?) before mounting is reasonable and worth doing; some Bangkok soi exits that are very short distance (under 300m) may be practical without helmet for low-speed short trips; judging distance and speed vs. safety tradeoff is an individual decision; (2) Grab Bike for pricing certainty: using Grab Bike (the app-based motorbike taxi) provides a fixed fare estimate before departure, eliminates negotiation, and provides GPS tracking; Grab Bike pricing is consistent vs. registered stand pricing which can vary by rider; Grab Bike is the recommended option for longer motorbike taxi trips (1km+) where fare dispute risk is higher; (3) Rush hour motorbike taxi value maximization: Bangkok motorbike taxi value peaks during surface road congestion (7–9:30am, 5–8pm); short trips that would take 20+ minutes by car take 5 minutes by motorbike; the time value makes motorbike taxi the correct transport choice for rush hour short-distance trips even at 1.5–2x the car fare; (4) Motorbike taxi from BTS to destination identification: major BTS stations have multiple exits; motorbike taxi stands are at specific exits (usually ground floor street level); asking BTS staff 'motorcycle taxi' with hand gesture or checking app-based transit guides for which exit has the stand saves searching; (5) Late night availability: Bangkok's motorbike taxi stands thin out significantly after midnight; after 1am, the supply of motorbike taxis drops sharply outside entertainment zones; Grab Bike remains available 24-hour through the app (though surge pricing applies).",
  },
];

export function BangkokBike() {
  return (
    <div className="rounded-2xl border border-lime-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-lime-700 mb-3">
        🚲 Bangkok alternative transport — cycling routes, river boats & motorbike taxi guide
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-lime-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-lime-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-lime-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
