const SPOTS = [
  {
    name: "Skydiving Near Bangkok — Pattaya & Hua Hin Drop Zones",
    emoji: "🪂",
    area: "Skydiving near Bangkok: Thai Sky Adventures (Pattaya, 2 hours from Bangkok); Skydive Thailand (Hua Hin, 2.5 hours south); no active drop zone within Bangkok proper — day trip distance required; helicopter scenic tours within Bangkok vicinity through King Power SkyWorld and airport-adjacent helicopter operators",
    price: "Tandem skydive (first-timer, 12,000–14,000 ft): ฿9,000–15,000; AFF solo skydive course (full level 1 training day): ฿15,000–25,000; Video/photo package with jump: ฿2,500–5,000; Scenic helicopter flight (Bangkok vicinity, 15 min): ฿4,000–9,000; Indoor skydiving / wind tunnel (Bangkok): ฿1,500–4,000 per session",
    why: "Thailand is one of Southeast Asia's most accessible skydiving destinations — the year-round flying weather (outside peak monsoon months), experienced instructor base trained internationally, and significantly lower cost compared to Western drop zones makes the day trip from Bangkok for a tandem skydive practical: (1) Thai Sky Adventures (Pattaya): the most established Bangkok day-trip drop zone; operates consistently with a mix of Thai and foreign instructors; Pattaya's coastal landscape provides distinctive visual backdrop at altitude; transport from Bangkok (Pattaya is 2 hours by highway) can be arranged through the drop zone; (2) Skydive Thailand (Hua Hin): southern drop zone with Gulf of Thailand coastal views; slightly further from Bangkok but established operation; (3) Weather seasonality: May–October (southwest monsoon) brings the least reliable flying weather; November–April (cool and dry season) offers the most consistent skydiving conditions; (4) Indoor wind tunnel: Bangkok has an indoor skydiving wind tunnel facility that allows body flight sensation without altitude commitment; useful for first-timers wanting to experience the sensation before committing to the full tandem jump; (5) AFF certification: completing an Accelerated Freefall (AFF) solo skydive certification course in Thailand is 40–60% less expensive than the same course in Europe or Australia; Bangkok-based skydivers doing license training in Pattaya represent significant cost savings.",
    tip: "Bangkok skydiving planning: (1) Weather checking before trip: confirming jump operations are proceeding before making the 2-hour drive to Pattaya or Hua Hin saves wasted trips; Thai Sky Adventures and Skydive Thailand both have Facebook pages and phone lines that confirm daily operations; (2) Weight limits: skydiving operations have weight limits (typically 100kg maximum for tandem jumps) and height minimums (minimum age 18 years, minimum height varies); confirming eligibility before booking prevents arrival disappointment; (3) Video package recommendation: first-time skydivers often report that the jump happens faster than expected; the video package captures what memory fails to — the recommendation from most experienced skydivers is to purchase the video; (4) Group discounts: skydiving centers in Thailand offer group pricing for 4+ jumpers; organizing a group from Bangkok makes the day trip more economical per person; (5) Tandem versus AFF: first-timers do tandem jumps (instructor attached, passenger has no solo control responsibility); AFF is the progression where students fly solo on their own parachute from the first jump; AFF requires significant ground training and is a full-day commitment.",
  },
  {
    name: "Bungee Jumping & High-Altitude Thrills in Bangkok",
    emoji: "🎪",
    area: "Bungee jumping in Thailand near Bangkok: Bungee Jump Thailand (multiple locations, Bangkok area and beyond); indoor adventure facilities (Bangkok's high ropes courses, free climbing, Urban Playground in On Nut); outdoor adventure parks (Flight of the Gibbon Chiang Mai for zip-line, Pattaya for Adventure Park); wake park cable water skiing (Rockit Wakeboard Park, Bangkok-adjacent)",
    price: "Bungee jump (single): ฿1,500–3,000; Second jump (same day): ฿1,000–2,000; High ropes course (Bangkok indoor): ฿400–800; Cable wakeboard (1 hour): ฿600–1,200; Go-kart racing (Bangkok indoor): ฿400–1,000 per session; Paintball (60 min, including gear): ฿600–1,500",
    why: "Bangkok and its vicinity offer a range of adrenaline experiences beyond the major skydiving operation: (1) Bungee jumping: Thailand's bungee jumping industry serves the adventure tourism market with fixed-platform and crane-based operations; the experience is standardized (jump, fall, bounce, lower) but the physical sensation remains genuinely significant; (2) Cable wakeboarding: cable wake parks near Bangkok provide an accessible alternative to boat-towed wake sports; the cable system (two-rope rotating cable system) pulls riders around a course without requiring a boat; suitable for beginners learning to wakeboard without expensive boat rental; (3) Indoor adventure facilities: Bangkok's urban adventure gyms (indoor climbing walls, aerial obstacle courses, trampoline parks) provide physical challenge in climate-controlled environments; particularly relevant during Bangkok's hot season when outdoor activity becomes uncomfortable; (4) Go-kart racing: Bangkok has multiple indoor and outdoor go-kart tracks; the RCA area and outer Bangkok neighborhoods have established karting facilities with rental kart fleets; racing experience requires no license; (5) Paintball: Bangkok's paintball venues (primarily in eastern and southern Bangkok suburbs) provide group tactical activity with rental equipment.",
    tip: "Bangkok thrill activity planning: (1) Rockit Wakeboard Park logistics: cable wake parks require swimwear, specific water shoes, and arrive-at-start mentality (sessions are fixed time blocks); bringing your own equipment (wakeboard, bindings) reduces rental cost if you have your own gear; (2) Go-kart racing safety: Bangkok go-kart tracks have safety standards (helmets, neck collars) comparable to Southeast Asian recreational standards; asking about track safety record and equipment age before racing is reasonable; (3) Paintball group size requirement: most Bangkok paintball venues require minimum 6–10 people for game sessions; organizing a group in advance rather than walking in as an individual is necessary; (4) Indoor climbing gym community: Bangkok's indoor climbing gym community (multiple walls exist in Phetchaburi and Lat Phrao areas) offers day passes and coaching for visitors wanting to try sport climbing without outdoor commitment; the climbing community is welcoming to beginners; (5) AirBnB experience listings: Bangkok's Airbnb Experiences platform lists adventure activity guides including local outdoor enthusiasts offering day trips to specific thrill activities; these provide both activity and local knowledge context.",
  },
  {
    name: "Bangkok's Obstacle Course & Functional Fitness Culture",
    emoji: "🏋️",
    area: "Bangkok's fitness challenge culture: CrossFit boxes throughout Bangkok (CrossFit Bangkok, EPIC Fitness, multiple affiliate boxes in Thonglor/Asoke); OCR (Obstacle Course Racing) events held at Rama IX Park and outdoor venues; F45 Training functional fitness studios; multi-sport challenge events organized through Bangkok Fitness Community groups",
    price: "CrossFit drop-in class: ฿400–800; CrossFit monthly membership: ฿3,000–7,000; OCR entry fee (Spartan Race Thailand, Warrior Dash Thailand): ฿1,500–4,000; F45 drop-in: ฿400–700; Personal training session: ฿800–2,500/hour; Running event entry (Bangkok Marathon, Bangkok Midnight Run): ฿500–2,000",
    why: "Bangkok's functional fitness and organized athletic challenge culture has grown dramatically since 2015: (1) CrossFit culture: CrossFit has strong roots in Bangkok's international expat community; affiliate boxes concentrated in Thonglor, Ekkamai, and Asoke areas serve a mix of Thai fitness enthusiasts and foreign residents; Bangkok CrossFit boxes maintain international coach certification standards; (2) OCR events in Thailand: Obstacle Course Racing events (Spartan Race Thailand, Warrior Dash Thailand, and domestic Thai OCR events) are held multiple times per year at venues accessible from Bangkok; combining mud running, rope climbing, and obstacle navigation; (3) Running event ecosystem: Bangkok and Thailand have an extensive running event calendar; the Bangkok Marathon (November), Midnight Sun Run, Color Run, and themed novelty runs create year-round race event access; the cool season (November–February) is optimal for Bangkok outdoor running events; (4) Fitness community organizations: Bangkok Fitness Community (Facebook group), Expat Fitness Bangkok, and CrossFit community connections organize informal challenge events, group workout sessions, and social runs; (5) Functional fitness for heat adaptation: Bangkok's year-round heat requires specific fitness adaptation; training Bangkok-style involves early morning 5–7am sessions before heat peaks; Bangkok's fitness community has developed heat-adapted training protocols different from temperate climate fitness conventions.",
    tip: "Bangkok functional fitness community access: (1) CrossFit drop-in standard: all Bangkok affiliate CrossFit boxes accept drop-in visitors on a per-session fee; contacting the box directly (through their website or Instagram) one day ahead confirms drop-in availability for specific class times; (2) OCR training in Bangkok: Bangkok has no dedicated OCR training facility but CrossFit boxes, parkour communities, and outdoor military-style training groups all provide relevant preparation training; the running community through Bangkok Hash House Harriers also provides functional outdoor running experience; (3) Running in Bangkok's heat: Bangkok running at ground level (not on elevated treadmill in air conditioning) requires genuine heat acclimatization; recommending to new Bangkok runners to reduce pace and distance by 20–30% during first 2 weeks of heat adaptation; (4) Bangkok Hash House Harriers: the Hash House Harriers are a global running/walking social group with an active Bangkok chapter; the 'On On' (group run) typically goes through interesting Bangkok neighborhoods with social element after; HHH is Bangkok's most established running social community; (5) Swim training Bangkok: swimming as cross-training is ideal for Bangkok's heat; multiple Bangkok condominium and gym pools are accessible for lap training; specifically organized lap swim sessions exist at international school pools for community members.",
  },
];

export function BangkokExtremeSports() {
  return (
    <div className="rounded-2xl border border-sky-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-sky-700 mb-3">
        🪂 Bangkok extreme sports — skydiving, bungee jumping & obstacle course culture
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-sky-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-sky-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
