const SPOTS = [
  {
    name: "Motorbike Taxis & Bangkok's Motorcycle Culture",
    emoji: "🏍️",
    area: "Motorbike taxis (win motorcycle taxis) throughout Bangkok — recognizable by orange-vested drivers parked at designated taxi stands (win) at BTS exits, street corners, and alley entrances; motorcycle rental shops in tourist areas (Khao San, Silom tourist zone), dedicated motorcycle rental companies on Ramkhamhaeng Road and in outer Bangkok",
    price: "Motorbike taxi (win) — short trip under 2km: ฿20–40; Motorbike taxi — longer trip 3–5km: ฿40–100; Motorbike rental (daily, 125cc automatic): ฿200–400; Motorbike rental (daily, 300cc+): ฿500–1,500; Helmet (rental with bike): typically included; Helmet purchase (quality, full face): ฿1,500–6,000",
    why: "Bangkok's motorbike culture operates at two distinct levels: (1) Motorbike taxis (win) as essential urban transport — Bangkok's motorbike taxi system is one of the world's most extensive and efficient; orange-vested motorcycle taxi drivers at designated stands throughout the city provide the fastest local transport for distances where BTS/MRT doesn't reach and traffic makes car taxis impractical; the system operates on fixed-rate pricing by distance (negotiated at the stand); (2) Motorbike rental culture — outside Bangkok proper, Thai cities (Chiang Mai, Pai, Krabi, Koh Samui) have extensive motorbike rental infrastructure; Bangkok itself has fewer tourists renting motorbikes due to traffic complexity, but rental shops exist in tourist corridor; (3) Thai motorcycle culture: Thailand is one of the world's top 10 motorcycle markets; Honda Wave, Yamaha Mio, and Honda PCX scooters dominate Bangkok's everyday motorcycle traffic; modified superbike culture (BigBike community) exists for performance motorcycle enthusiasts; (4) Big bike community: the Thai BigBike community (motorcycles above 400cc) organizes group rides, touring events, and brand communities (Harley-Davidson Thailand clubs, BMW Motorrad Thailand touring clubs); (5) Royal Enfield culture: India's Royal Enfield motorcycles have a strong Thai following for Himalayan and touring models; Bangkok dealers and the Royal Enfield Owners Club Thailand represent this specific motorcycle subculture.",
    tip: "Bangkok motorbike navigation: (1) Win motorbike taxi safety: Bangkok's motorbike taxis are officially supposed to provide helmets; insisting on a helmet before riding is legally your right and practically wise; major roads at speed without a helmet is genuinely dangerous in Bangkok traffic; (2) Pricing at win stands: win motorbike taxi fares are negotiated face-to-face; established regular routes have de facto fixed prices that local commuters know; for unfamiliar routes, stating your destination and asking 'tao rai?' (how much?) starts the negotiation; (3) Bangkok traffic and motorbike risk: Bangkok's traffic generates significantly more motorcycle fatalities than equivalent-size Western cities; the risk calculation for driving a rented motorcycle in Bangkok's central traffic is genuinely high; renting for day trips outside Bangkok (Kanchanaburi, Koh Si Chang) is a different risk level than navigating Sukhumvit; (4) IDP (International Driving Permit): legally, driving any motorcycle in Thailand requires a valid motorcycle license (Thai or international); police checkpoints (common in tourist areas) can fine unlicensed foreign motorcycle drivers; an IDP endorsed for motorcycles combined with a home-country motorcycle license is the proper legal approach; (5) BigBike events: Thailand Bike Week (Phuket, annual) and Bangkok's periodic BigBike expos (at Royal Paragon Hall) are the major gathering events for Thailand's motorcycle community.",
  },
  {
    name: "Bangkok Car Rental & Road Trip Culture",
    emoji: "🚗",
    area: "Car rental in Bangkok: major international companies (Avis, Hertz, Budget, Sixt) at Suvarnabhumi and Don Mueang airports plus downtown locations; Thai car rental companies (Thai Rent A Car, Choke Dee) at competitive rates; pick-up truck rental (popular for rural Thailand trips) at Ekkamai/Mo Chit area companies; luxury car rental (Mercedes, BMW) for special events",
    price: "Economy car (Toyota Yaris/Honda Jazz): ฿700–1,200/day; Sedan (Toyota Camry): ฿1,200–2,500/day; SUV (Toyota Fortuner, Ford Everest): ฿1,500–3,500/day; Pick-up truck (Toyota Hilux Revo): ฿1,000–2,000/day; Minivan (Toyota Commuter): ฿2,000–4,500/day; International driving permit: required (from your home country's automobile association)",
    why: "Renting a car in Bangkok unlocks weekend Thailand beyond BTS-accessible areas — the country's temple routes, national parks, and coastal destinations are most efficiently accessed with personal transport: (1) Route 1 — Ayutthaya day trip: renting a car and driving north from Bangkok (90 minutes) to Ayutthaya (UNESCO World Heritage Site) allows temple-hopping on personal schedule versus organized tour timing; (2) Kanchanaburi and the River Kwai: western Bangkok's primary day/weekend road trip destination (2 hours); accessible only by car or public bus; the Route of Death Railway history and national park access make it Bangkok's most significant historical road trip; (3) Hua Hin and Gulf coast: southern Thailand's Gulf Coast resort town (2.5–3 hours south); preferred weekend destination for Bangkok's middle class; (4) Khao Yai National Park: Thailand's most accessible national park from Bangkok (2.5 hours northeast via Highway 2); wildlife (wild elephants, gibbons, hornbills), jungle trekking, and vineyard wine country in adjacent areas make it Bangkok's primary nature road trip; (5) Pick-up truck culture: Thailand's pick-up truck culture is distinctive; modified Toyota Hilux Revo and Ford Ranger trucks are status symbols for middle-class Bangkok residents; renting a pick-up provides cultural immersion into Thai car culture beyond econobox city driving.",
    tip: "Bangkok car rental logistics: (1) Left-hand traffic: Thailand drives on the left side of the road (same as UK, Australia, Japan); transitioning from right-hand traffic requires concentrated attention for the first few hours; Bangkok-to-highway transition (where road instinct is tested) is the most challenging period; (2) Google Maps reliability: Google Maps Thailand is highly accurate for Bangkok and Thai highway navigation; offline maps download before departure is recommended for areas with poor cellular coverage; (3) Highway tollways: Bangkok's expressways (Expressway Authority of Thailand) charge tolls at ฿35–65 per gate; keeping ฿200–500 in small change in the car prevents toll booth queuing issues; Easy Pass electronic toll transponders are available from expressway offices; (4) Fuel: Thailand's petrol stations (PTT, Shell, Caltex) are widespread and open 24 hours; gasoline (benzin) prices in Thailand are government-regulated; (5) Car insurance: international rental car companies in Bangkok provide mandatory Thailand motor insurance with rental; understanding the deductible/excess for accident damage before renting (and whether credit card travel benefits cover the excess) prevents surprise costs.",
  },
  {
    name: "Bangkok Cycling Culture — Urban Bikes to Bangkrachao",
    emoji: "🚴",
    area: "Cycling in Bangkok: Bangkrachao Green Lung (cycling haven, 30 min from city center by ferry from Klong Toey Pier); Chao Phraya riverside cycling path; Lumphini Park and Benjakitti Park inner-city cycling; Bang Pa-In/Ayutthaya cycling tours (day trip); bicycle rental in Bangkrachao (฿60–150/hour at island rental shops)",
    price: "Bicycle rental in Bangkrachao (hourly): ฿60–150; Road bicycle rental (quality, Sukhumvit/Silom area): ฿300–800/day; Cycling tour (guided, with bike, full day): ฿1,500–4,500; Bicycle purchase (hybrid commuter, Bangkok shops): ฿3,500–15,000; Carbon road bike (imported): ฿30,000–200,000+; Bike maintenance (flat repair at roadside shop): ฿50–100",
    why: "Bangkok's cycling scene has two distinct modes — inner-city commuter and fitness cycling, and escape-route leisure cycling at Bangkrachao: (1) Bangkrachao — Bangkok's cycling paradise: the Bangkrachao peninsula (directly across the Chao Phraya from Klong Toey) is a giant green area free from motor vehicles; accessible by a short ferry crossing from Klong Toey pier; the entire 'green lung' is flat, shaded, and navigable on bicycle without Bangkok traffic; weekend morning cycling here (7–11am before heat peak) is the most pleasant cycling experience accessible from central Bangkok; (2) Lumphini and Benjakitti parks: Bangkok's two most central large parks have cycling paths; rental bicycles available at both; early morning cycling at these parks is a Bangkok daily commuter and fitness standard; (3) Chao Phraya riverside path: sections of the Chao Phraya riverside have been developed as pedestrian/cycling paths; the Charoenkrung creative district section is particularly pleasant; (4) Thai cycling culture: Thailand has an active recreational cycling community; group road cycling on weekend mornings (5:30–8am before traffic intensifies) on roads leading out of Bangkok is a widespread enthusiast practice; (5) Bangkok cycling tours: multiple operators run cycling tours of Bangkok's neighborhoods (typically 3–4 hours, covering Chinatown, temples, canal neighborhoods) with rental bicycle included.",
    tip: "Bangkok cycling practicalities: (1) Bangkrachao timing: arriving at Bangkrachao before 9am and leaving before noon avoids peak heat; the canal paths under tropical canopy are cooler than open Bangkok streets but still reach uncomfortable temperatures by midday; (2) Bangkrachao ferry crossing: the Klong Toey industrial pier (not a tourist pier) is where the Bangkrachao ferry departs; accessible by taxi from BTS Klong Toey; motorcycle taxis also cross on the ferry carrying passengers; (3) Road cycling routes from Bangkok: the most popular Bangkok road cycling departure routes head northeast on Highway 305 (toward Nakhon Nayok) or north toward Pathum Thani; weekend group rides organized through cycling clubs use these quieter highway sections; (4) Bicycle lock importance: bicycle theft in Bangkok exists; using a quality U-lock plus cable lock for any urban cycling; Bangkrachao rental bikes typically have basic locks that suffice for the closed island environment; (5) Heat adaptation: cycling in Bangkok requires heat adaptation; carrying 1.5–2 liters of water per hour of riding in hot season (March–May) and starting rides early morning or late afternoon prevents heat exhaustion.",
  },
];

export function BangkokMotorbike() {
  return (
    <div className="rounded-2xl border border-red-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-red-700 mb-3">
        🏍️ Bangkok transport adventures — motorbike taxis, road trips & Bangkrachao cycling
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-red-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-red-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
