const TOPICS = [
  {
    title: "Bangkok's Amulet Market — Thai Buddhist Talismans, Wat Mahathat & Collector Culture",
    emoji: "📿",
    summary: "Bangkok's amulet market is one of the world's most unusual commercial environments — a dense collector's market for sacred Buddhist talismans: (1) What Thai amulets are: Buddhist amulets (phra kruang) are consecrated sacred objects — typically medallion-sized reliefs of revered Buddhist monks, images of the Buddha, or sacred symbols — that are believed by Thai Buddhist tradition to provide protection, luck, and supernatural assistance to their wearers; the objects are typically worn on neck chains; (2) The Amulet Market at Wat Mahathat: Bangkok's main amulet market is outside and adjacent to Wat Mahathat Yuwaratrungsarit (near Sanam Luang, Maharaj Pier); hundreds of vendors spread their trays of amulets on the ground along the temple wall and in the adjacent alleys; the market operates daily (typically 8am–5pm, busiest on weekends); (3) Price range and collectors: Thai amulet collecting is a serious hobby with pricing that ranges from ฿50 (common, mass-produced) to millions of baht (historically significant amulets from highly revered monks); the most prized amulets are from specific monks (Luang Pho Thuad, Luang Phor Sothorn) who are considered especially powerful; amulets are traded like collectibles with established price guides and authentication systems; (4) Commercial TV channels: Thailand has dedicated amulet television channels (multiple channels broadcasting amulet auctions and evaluations 24 hours daily); this shows the scale of the commercial amulet market in Thai consumer culture; (5) Authentication complexity: high-value Thai amulets have sophisticated authentication processes involving surface examination, clay composition analysis, and provenance verification; the market includes both genuine antique religious objects and reproductions; experts can distinguish but novice buyers face risk at the high-price end.",
    action: "Amulet Market at Wat Mahathat (Maharaj Road, opposite Sanam Luang; nearest pier: Tha Mahathat N9); market hours: typically 7am–5pm, extended weekends; approach as observer for first visit; Tha Phra Chan area (adjacent to market) has additional amulet shops; legitimate amulets for tourists: mass-produced small amulets (฿50–500) from temple gift shops carry no authentication risk.",
  },
  {
    title: "Thai Spirit Houses — San Phra Phum, Bangkok's Invisible Architecture & Folk Religion",
    emoji: "🏯",
    summary: "Bangkok's spirit houses are one of the city's most distinctive urban elements, simultaneously everywhere and invisible to visitors who don't know what they are: (1) What spirit houses are: san phra phum (literally 'spirit of the place houses') are miniature ornate structures placed outside virtually every Thai building, business, and home in Bangkok; the spirit house provides a dwelling for the local spirit guardian (phra phum or chao thi) of the property; maintaining a properly positioned and honored spirit house is believed to ensure harmony between the property's residents and the supernatural inhabitants of the land; (2) Visual diversity: Bangkok's spirit houses range from simple ceramic structures (฿500) to elaborate multi-story architectural models (฿50,000+) often with miniature ceramic figurines of horses, elephants, servants, and celestial beings; larger businesses and hotels have multiple spirit houses, sometimes with dedicated platforms; the Erawan Shrine (Ratchaprasong intersection, Grand Hyatt area) is Bangkok's most famous and elaborately maintained spirit house destination; (3) Erawan Shrine significance: the Erawan Shrine (Thao Mahaprom, the Brahman deity Phra Brahma/Erawan) is Bangkok's most visited non-temple religious site; the shrine was built in 1956 during construction of the original Erawan Hotel (now the Grand Hyatt) after workers suffered repeated accidents that Hindu priests attributed to the spirits of the land; the shrine remains intensely active with worshippers, Thai classical dance offerings, incense, and flower garlands; (4) Spirit house maintenance culture: Thai businesses carefully maintain their spirit houses — daily incense and flower offerings, regular replacement of water and food miniatures, periodic monk blessings; spirit houses are not art objects or tourist installations; they are functioning religious infrastructure embedded in Bangkok's commercial life; (5) Spirit house sellers: Bangkok has specialized spirit house shops (San Phra Phum shops) concentrated in specific areas; major concentrations are at Lad Phrao and in Old Bangkok; purchasing a spirit house requires knowing the exact placement specifications (specific auspicious positions relative to the property, not placing in shadows of the main building) that require a specialist to determine.",
    action: "Erawan Shrine (BTS Chit Lom, corner of Ratchadamri and Ploenchit): observe offerings respectfully; Thai classical dance offerings visible throughout the day (donation box for sponsoring a dance); appropriate behavior: remove shoes before standing on shrine platform (if required), observe silently, no flash photography during active ceremonies; Bangkok spirit house tour: several Bangkok cultural tour operators include spirit house context in their walking tours.",
  },
  {
    title: "Thai Fortune Telling & Astrology — Bangkok's Divination Culture",
    emoji: "🔮",
    summary: "Bangkok has one of Asia's most active urban divination cultures, serving Thai and international clients through diverse fortune-telling traditions: (1) Fortune-telling prevalence in Bangkok: Thai astrological consultation and divination is mainstream behavior (not fringe); major Thai decisions (business investments, marriage timing, house purchases, vehicle purchases) commonly involve astrological consultation; Bangkok's fortune-tellers serve across class levels from market stall readings (฿100) to expensive consultations with revered monks or astrologers serving executives and politicians; (2) Thai astrology basis: Thai astrology (hora or daoruek system) integrates Indian (Vedic/Jyotish) astrological principles adapted over centuries to Thai Buddhist context; Thai birth charts use an 8-day week (with rahu as a hidden planet-day), 12-year zodiac cycles (same as Chinese zodiac), and lunar calendar calculations; Thai numerology, palm reading, and card reading supplement the astrological system; (3) Luk Thep dolls and belief intersection: Bangkok's Luk Thep ('child angel') doll phenomenon (sacred dolls believed to host child spirits, owning airlines seats and eating in restaurants) was a 2016 cultural moment illustrating how supernatural belief intersects with modern Thai commercial and consumer life; the phenomenon normalized by Thai celebrities became a significant Bangkok and national story; (4) Fortune-telling hotspots in Bangkok: Rachinee Road near the Grand Palace is known for fortune-telling stalls; Sanam Luang on weekends; some convenience of BTS station astrological service kiosks; major temples (Wat Mangkon Kamalawat in Chinatown, Erawan Shrine) have fortune-telling services; (5) Numerology in Bangkok life: Thai numerology (particularly for vehicle license plates and phone numbers) is a developed commercial market; Thai people pay premiums for 'lucky' license plate numbers at government auctions; mobile number resellers market phone numbers with auspicious digit combinations; understanding this numerology orientation explains certain Bangkok commercial behaviors (numbers like 9 repeated are considered very lucky in Thai culture).",
    action: "Erawan Shrine complex (BTS Chit Lom) for observing Thai divination culture in active context; Wat Mangkon Kamalawat (Chinatown) for Taoist/Buddhist divination stalls; Sanam Luang weekend market for street fortune-telling stalls; respectful approach: observe without interrupting active Thai client consultations; international visitors can engage fortune-tellers who have English capability (present at tourist-frequented spots) for their own readings.",
  },
];

export function BangkokAmuletMarket() {
  return (
    <div className="rounded-2xl border border-purple-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-purple-700 mb-3">
        📿 Bangkok's spiritual underworld — amulet markets, spirit houses & fortune-telling culture
      </div>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-purple-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-purple-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
