const SPOTS = [
  {
    name: "Bangkok Vintage & Antique Stamp & Coin Collecting",
    emoji: "📮",
    area: "Siam Square philatelic shops (near MBK Center), Chatuchak Market (Section 1 antique area), Bang Khun Phrom Market (Sunday, near National Library), Central Post Office philatelic counter, specialized collectors' shops in Old Bangkok",
    price: "Thai commemorative stamp sheet: ฿50–500; Vintage Thai stamp (pre-1950): ฿200–5,000+; Rare Thai error stamps: ฿2,000–50,000+; Thai coin collection (common): ฿100–2,000; Rare Thai historical coins: ฿1,000–100,000+; Stamp identification/valuation service: ฿200–1,000",
    why: "Thailand's philatelic and numismatic collecting history is rich — the Kingdom of Siam issued its first stamps in 1883 under King Rama V, and the subsequent hundred+ years of Thai stamp production encompasses royal portraits, Buddhist imagery, national monuments, flora and fauna, and commemorative issues that document the country's history. Thai coins span from ancient Siam's bullet coins (pod duang — small silver coins shaped like a slug, used until the 19th century) through the current royal portrait coinage of the Chakri dynasty. Bangkok's collecting community for stamps and coins centers on: (1) Chatuchak Weekend Market Section 1 (antiques): weekend vendors with mixed stamp/coin selections; (2) The Bang Khun Phrom market (Sunday mornings near Phra Athit Road): Bangkok's most active dedicated collectors' market with stamps, coins, banknotes, and militaria; (3) Siam Square stamp shops: a cluster of specialist dealers in the Siam Square/MBK area serving the philatelic community; (4) Central Post Office (Charoen Krung Road): the official Thailand Post philatelic department sells current and recent commemorative issues.",
    tip: "Bangkok philatelic collecting: (1) Bang Khun Phrom Sunday market timing: the dedicated antiques and collectibles market near Phra Athit Road/National Library operates Sunday mornings from approximately 7am to noon; arriving early (7:30–8:30am) finds the fullest vendor presence before heat peaks; (2) Thai bullet coins (pod duang): authentic ancient Siam bullet coins (pre-1868) are tangible historical artifacts available in Bangkok at prices from ฿200–5,000+ depending on quality and period; many are genuine and inexpensive given their age; (3) Thai banknote collecting: Thai paper currency collecting is a significant sub-category; early Siam banknotes from the late 19th century through WWII-era issues have strong collector demand; Chatuchak's antique section has banknote vendors; (4) Authentication: for significant purchases, Bangkok has professional numismatic and philatelic authentication services; the Thailand Philatelic Society can provide community expertise; (5) First-Day Covers: the central post office and philatelic shops sell first-day covers (envelopes franked on the issue date) for Thai commemorative stamps — a popular collecting category that documents specific historical events.",
  },
  {
    name: "Bangkok Sneaker Culture & Limited-Edition Collecting",
    emoji: "👟",
    area: "Platinum Fashion Mall (Pratunam) — Bangkok's sneaker trading hub; Siam Square One and Siam Center sneaker boutiques; Chatuchak Market independent sneaker vendors; CentralWorld and EmQuartier brand boutiques; sneaker resell communities via LINE, Facebook, and Carousell Thailand",
    price: "Nike Air Force 1 (retail): ฿3,500–5,000; Limited Jordan releases (retail): ฿5,000–12,000; Resell premium (hyped releases): 1.5–3x retail; Adidas Yeezy (resell market): ฿8,000–50,000+; New Balance 550 (retail): ฿3,500–5,500; Sneaker cleaning service: ฿500–2,000",
    why: "Bangkok has developed one of Southeast Asia's most active sneaker collecting and trading communities — powered by Thailand's young urban population's enthusiasm for streetwear culture, the city's role as a regional retail hub where international brands establish presence, and the social media-driven global sneaker community's connectivity. Bangkok sneaker culture operates on two levels: (1) Official retail — Nike, adidas, New Balance, Jordan Brand, and other sneaker brands maintain official retail presence in Bangkok's major malls; limited-edition releases draw queues at Siam Square stores similar to worldwide release events; (2) Resell culture — Bangkok has a vigorous secondary sneaker market through online platforms (LINE trading groups, Facebook Marketplace, Carousell Thailand) and physical trading spots; Platinum Fashion Mall in Pratunam serves as Bangkok's informal sneaker trading hub where resell vendors maintain stock. The Bangkok sneaker community connects with regional and global sneaker culture — Bangkok collectors have access to releases intended for the APAC market that may not be available in other regions, and conversely Bangkok serves as a sourcing point for Southeast Asian editions.",
    tip: "Bangkok sneaker culture navigation: (1) Release information: following brand official accounts and Bangkok sneaker community Instagram accounts (numerous Bangkok Streetwear pages) provides advance notice of upcoming limited releases; (2) Authenticity in resell: Bangkok's resell market includes both authentic and counterfeit product; buying from established resellers with verifiable transaction history (Carousell Thailand rating system, LINE trading groups with active community reputation) reduces counterfeit risk; (3) Chatuchak sneaker section: Chatuchak Weekend Market has independent sneaker vendors selling authentic and replica product at mixed quality; examining stitching, materials, and heel counter construction carefully before purchasing is essential; (4) Sneaker cleaning services: Bangkok's sneaker cleaning services (professional sneaker restoration through oxidation removal, stain treatment, and sole restoration) are available at Chatuchak market vendors and dedicated sneaker care shops in Sukhumvit; (5) Bangkok-exclusive colorways: some Nike and adidas releases designed for the Asian market (particularly ASEAN-specific editions) are exclusively available in Bangkok and may not appear in Western markets; following regional sneaker release calendars identifies these opportunities.",
  },
  {
    name: "Bangkok Art Toys, Vinyl Figures & Designer Collectibles",
    emoji: "🎨",
    area: "Pop culture and toy collector destinations: CentralWorld Level 4 toy and collectibles section, MBK toy floor (Level 6), specialty toy shops at Siam Paragon and Emporium, Toy Sapiens Bangkok, Chatuchak Section 7 for vintage toys, and online via Lazada and Shopee Thailand",
    price: "Funko Pop (standard): ฿500–1,200; Exclusive/grail Funko: ฿2,000–20,000+; Kaws collectible: ฿5,000–200,000+ (depending on edition); Bearbrick 400%: ฿3,000–50,000+; Hot Toys movie figures (1/6 scale): ฿8,000–30,000; Thai artist designer toys (limited edition): ฿2,000–15,000",
    why: "Bangkok's art toy and designer collectibles market has grown significantly — driven by the same pop culture enthusiasm that fuels the global Funko Pop, KAWS, Bearbrick, and designer toy market, filtered through Southeast Asia's unique creative community. Bangkok collectors participate in: (1) International brands — Bangkok has significant inventory of mainstream collectible figures (Funko Pop, Hot Toys, Dragon Models, Figma/Nendoroid) through official retail channels and specialist collectible shops; (2) Designer art toys — the KAWS/Medicom Toy/Bearbrick tradition has strong Bangkok collector presence; major department stores stock official releases while specialty shops carry exclusive editions; (3) Thai artist designer toys — Bangkok's creative community has produced several respected toy designers who create limited-edition vinyl and resin figures reflecting Thai aesthetics, Buddhist imagery, and contemporary pop culture; these represent unique Bangkok-origin collectibles; (4) Vintage and retro toys — Chatuchak Market Section 7 has vintage toy vendors including classic Japanese robots, Thai licensed toys, and early video game merchandise; (5) Pop culture merchandise — Thai-licensed merchandise from Thai drama/series and Japanese anime officially distributed in Thailand.",
    tip: "Bangkok collectibles shopping guide: (1) MBK Center toy floor: Level 6 of MBK Center (Siam area) has one of Bangkok's most diverse toy vendor concentrations; ranges from mass-market toys through specialty figure collectibles; helpful for understanding what's available before visiting specialist shops; (2) Thai artist toys discovery: Bangkok art toy market events (periodic pop-up fairs in venue spaces, sometimes announced through community Facebook groups and Instagram) showcase Thai designer toy artists; (3) Authenticity vs. high-quality bootleg: Bangkok's collectibles market has both authentic licensed product and high-quality bootleg versions of popular collectibles (particularly for KAWS, Supreme accessories, and limited figures); the pricing difference is usually obvious; (4) Pre-ordering upcoming releases: Bangkok's specialist figure shops take pre-orders for upcoming releases (particularly Nendoroid, Figma, and Hot Toys) that won't be available for several months; pre-ordering in Bangkok at Asian retail pricing before a trip home can produce savings; (5) Customs and import consideration: bringing collectibles purchased in Bangkok through customs upon return requires declaring above threshold (threshold varies by country); declaring and potentially paying duties is preferable to seizure.",
  },
];

export function BangkokCollectibles() {
  return (
    <div className="rounded-2xl border border-orange-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-orange-700 mb-3">
        🎨 Bangkok collecting culture — stamps & coins, sneaker culture & designer art toys
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-orange-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-orange-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
