const SPOTS = [
  {
    name: "Bangkok Private Aviation — Private Jet Charter to Samui, Phuket & Asia Regional Destinations",
    emoji: "✈️",
    area: "Bangkok private aviation infrastructure: Suvarnabhumi Airport (main international hub; private jet FBO facilities through Royal Orchid Hangar and Jet Aviation FBO); Don Mueang Airport (Bangkok's secondary airport; Execu-Jet FBO, Jetex; more common private aviation departure point for regional Asian charter); U-Tapao International Airport (Pattaya area, Rayong; Royal Thai Navy-managed civil airport; joint-use FBO; growing private aviation hub for eastern seaboard; 90 minutes from central Bangkok); Bangkok's FBO operators: Jet Aviation Bangkok, Execu-Jet Bangkok, Q Aviation, TAG Aviation, Muang Thong Thani FBO; regional charter companies: Bangkok Airways (operates as charter operator), Thailand private air charter operators accessible through SIAM Executive Air, Premiair, and international brokers",
    price: "Bangkok private aviation price reference: charter Bangkok to Koh Samui (280nm): light jet (Citation CJ2, 6 passengers): ฿350,000–500,000 one-way; midsize jet (Hawker 900XP, 8 passengers): ฿500,000–700,000 one-way; charter Bangkok to Phuket (450nm): light jet: ฿450,000–650,000 one-way; midsize jet: ฿650,000–900,000; charter Bangkok to Singapore (820nm): midsize jet: ฿1,200,000–1,800,000; heavy jet (Gulfstream G550, 14 passengers): ฿2,500,000–4,000,000; Suvarnabhumi VIP terminal/FBO fees: ฿5,000–15,000 per flight in/out; empty leg charter (one-way repositioning flight): 30–50% discount vs. standard charter rate; helicopter to Suvarnabhumi from central Bangkok: ฿15,000–25,000 per flight",
    why: "Bangkok is one of Southeast Asia's most active private aviation markets, driven by the combination of Thai ultra-high-net-worth individuals, regional business travel, and tourism to Thailand's island destinations: (1) Bangkok private jet usage patterns: Bangkok's private aviation serves several distinct use cases: ultra-high-net-worth Thai travel (major Thai business families traveling between Bangkok, Phuket, Ko Samui, and regional Asian destinations); regional Asian business travel (Bangkok-Singapore, Bangkok-Hong Kong, Bangkok-Kuala Lumpur lanes); international luxury tourism (guests arriving at Phuket or Ko Samui who originate from UAE, UK, USA, and fly private to avoid commercial airline routing); medical tourism (patients flying to Bangkok for treatment who prefer private aviation for comfort and efficiency); (2) Thailand private aviation market specifics: the Thai private aviation market was liberalized progressively since the 2000s; CAAT (Civil Aviation Authority of Thailand) regulations govern charter operations; on-demand charter is available through Thai operators and through international charter brokers; the absence of a cabotage restriction for foreign-registered charter aircraft on international routes makes Bangkok accessible to international aircraft registration (Cayman Islands, Isle of Man registered aircraft operate commonly in the Bangkok market); (3) U-Tapao's growing role: U-Tapao International Airport is positioned as a potential relief hub for Bangkok aviation congestion and as an Eastern Economic Corridor (EEC) aviation hub; existing private aviation FBO facilities are well-developed; luxury resort connections from U-Tapao to Koh Samet, Koh Chang, and Phuket by connecting charter create an EEC luxury corridor; (4) Private helicopter transfer to island resorts: Ko Samui's Samui Airport (operated by Bangkok Airways) accepts private aircraft; private helicopter transfers from U-Tapao Airport to Ko Samet or from Suvarnabhumi to resort locations in Hua Hin (approximately ฿20,000–35,000) create door-to-resort luxury connections; charter prices from Suvarnabhumi to Koh Samui helicopter: ฿80,000–150,000+ depending on aircraft type; (5) Empty leg markets from Bangkok: Bangkok's private aviation market generates significant empty leg availability when charter aircraft reposition; empty legs from Bangkok (departing without passengers to reposition for next paid charter) are listed on PrivateFly, JetSmarter, Victor, and similar platforms; Bangkok to Singapore empty legs are among Asia's most frequent empty leg offerings and can reduce charter cost by 40–60%.",
    tip: "Bangkok private aviation logistics: (1) Don Mueang for private departure: Don Mueang Airport (DMK) is more convenient for private aviation than Suvarnabhumi for many operators — the FBO and handling facilities are well-established and Don Mueang's traffic is lower; plan transport from central Bangkok to Don Mueang approximately 45–60 minutes by Grab; private aviation also allows later departure check-in than commercial (30 minutes prior); (2) FBO direct contact: for repeat Bangkok private aviation, establishing a relationship with a Bangkok FBO (Execu-Jet Bangkok or Jet Aviation) provides consistent handling, customs/immigration facilitation, and catering coordination; FBO relationships also provide intelligence on parking availability and fuel pricing; (3) Empty leg brokers: PrivateFly (privatefly.com), Jettly, and JetsmartFlights aggregate Bangkok empty leg availability; alert subscriptions provide notification when Bangkok empty legs become available; (4) Private aviation for island transfers: for groups of 6+ traveling Bangkok to Ko Samui or Bangkok to Phuket, private charter cost per-person can approach premium commercial first-class pricing while offering: direct point-to-point routing (commercial requires connection through Bangkok or Chiang Mai in some cases), flexible departure time, and door-to-plane service; (5) CAAT charter verification: when using unfamiliar Bangkok charter operators, verify CAAT operating certificate; reputable operators (Premiair, Q Aviation) are IATA CASS registered and hold current CAAT Air Operator Certificate; international brokers (PrivateFly, Air Charter Service) pre-qualify operators before listing.",
  },
  {
    name: "Bangkok Ultra-Luxury Hotels — Beyond 5-Star, Suite Rates & Exclusive Property Services",
    emoji: "🏨",
    area: "Bangkok's flagship luxury hotel properties: Capella Bangkok (Charoenkrung, riverside; opened 2020; part of Capella ultra-luxury brand; 101 suites only, no rooms; Chao Phraya riverfront access); Mandarin Oriental Bangkok (Oriental Avenue, Charoenkrung; operating since 1876; consistently ranked among world's greatest hotels; the Authors' Wing is the original building); Rosewood Bangkok (Ploenchit area, BTS Ploenchit; opened 2019; urban design-forward luxury, Sense spa, Carlyle and Co. bar); Four Seasons Bangkok (Charoenkrung, riverside; Chao Phraya Residences; joined Bangkok's luxury hotel cluster in 2020); Peninsula Bangkok (Silom area, BTS Saphan Taksin, riverside; Hong Kong-founded Peninsula Hotels brand; consistently high-ranking in global hotel surveys); The Sukhothai Bangkok (Sathorn, BTS Chong Nonsi; established luxury property with botanical aesthetic); Park Hyatt Bangkok (CentralWorld area, BTS Siam; opened 2017; contemporary design luxury)",
    price: "Bangkok ultra-luxury hotel pricing: Capella Bangkok suite rates: ฿40,000–250,000+ per night depending on suite category and season; Mandarin Oriental Bangkok: ฿30,000–200,000+ per night; Rosewood Bangkok: ฿20,000–150,000+ per night; Peninsula Bangkok: ฿25,000–200,000+ per night; presidential/grand suites at all properties: ฿200,000–1,000,000+ per night; long-term stay (30+ nights) negotiated rates: 20–40% below rack rate; hotel F&B minimum spend at luxury bars: ฿1,500–3,000 per person; Capella's private dining (in-suite service): typically ฿3,000–8,000+ per person; butler service: standard at all listed properties (24-hour butler per suite at Capella, Peninsula, Mandarin Oriental)",
    why: "Bangkok's luxury hotel market has experienced significant renovation and new-build activity in the 2015–2025 decade, resulting in one of Asia's most competitive ultra-luxury hotel landscapes: (1) Bangkok's luxury hotel positioning in Asia: Bangkok competes with Singapore, Hong Kong, and Tokyo for ultra-luxury hotel market in Southeast Asia; Bangkok's competitive advantages: lower land and construction costs than Singapore/Hong Kong (enabling larger suites and more generous amenity spaces); lower service staff costs (enabling higher staff-to-guest ratios); premium Bangkok hotels frequently offer 3:1 or 4:1 staff-to-guest ratios that cost-prohibitively expensive in Singapore; the Chao Phraya riverside location (unavailable in Hong Kong or Singapore's built-out waterfronts) creates distinctive Bangkok luxury positioning; (2) Capella Bangkok as the current luxury benchmark: Capella Bangkok (opened 2020) has established itself as the current reference Bangkok luxury property; 101 suites only (no entry-level rooms); all suites include private plunge pool or terrace; room sizes: minimum 82 sqm; 24-hour dedicated butler; the property's design (river-facing with Bangkok's Grand Palace and Wat Arun in the sightline) creates a specific Bangkok luxury experience; (3) Mandarin Oriental Bangkok's legacy positioning: the Mandarin Oriental Bangkok (est. 1876) carries the weight of Bangkok's colonial-era international hotel history; the Authors' Lounge (afternoon tea, ฿1,200–2,000 per person) and the collection of writers who stayed (Somerset Maugham, Noël Coward, Joseph Conrad) create a distinctive literary luxury positioning; the property has maintained contemporary competitive standards through extensive renovation; (4) Bangkok luxury hotel F&B as standalone destination: Bangkok's luxury hotel restaurants and bars attract significant non-guest business; Capella's Côte by Mauro Colagreco, Mandarin Oriental's Le Normandie (French fine dining, ฿5,000–10,000 per person), Peninsula's Thiptara (Thai cuisine, riverside), and Rosewood's Carlyle and Co. attract non-staying Bangkok diners; the luxury hotel bar circuit (Capella's Phra Nakhon Bar, Mandarin Oriental's Bamboo Bar, Peninsula's lobby lounge) is a Bangkok social institution for the city's professional class; (5) Private club and members-only access in Bangkok luxury hotels: several Bangkok luxury hotels have private club components: Rosewood's Rosewood Club lounges; Peninsula's private events facilities; the ultra-luxury property memberships and relationships create a private club ecosystem for Bangkok's high-net-worth resident community (corporate memberships, relationship rates, event access) that parallels the international luxury brand membership programs.",
    tip: "Bangkok ultra-luxury hotel strategy: (1) Club lounge access as value layer: several Bangkok luxury hotels offer club lounge access (Rosewood Club, Park Hyatt Club) at incremental upgrade cost; club lounges typically include: all-day light refreshments, breakfast, evening cocktail hour, dedicated check-in/out; for guests spending multiple days, the club lounge F&B value can exceed the upgrade cost; (2) Mandarin Oriental afternoon tea: the Mandarin Oriental's Authors' Lounge afternoon tea (from ฿1,200 per person, book in advance) is one of Bangkok's iconic luxury hospitality experiences; the setting (a restored colonial-era room with rattan furniture and ceiling fans) is architecturally distinctive; accessible to non-guests with reservation; (3) Spa day pass for ultra-luxury property access: Capella Bangkok's Auriga Spa, Peninsula Bangkok's ESPA, and Mandarin Oriental's Spa at Mandarin Oriental offer spa day packages for non-guests; spending ฿5,000–8,000 on spa access provides entry to the property's amenities including riverside pool; this is the most accessible non-guest pathway to experience these properties; (4) Capella vs. Mandarin Oriental for the single Bangkok night: Capella for first-time Bangkok luxury visitor prioritizing contemporary river views and pool + design + service quality; Mandarin Oriental for the hotel history, the Authors' Wing atmosphere, and Bangkok's original luxury hotel tradition; (5) Advance booking for high season: Bangkok luxury hotel peak occupancy is November–February; suites sell out at major properties during high season and around holiday periods (New Year, Chinese New Year, Thai New Year Songkran); 3–6 month advance booking for peak periods; direct booking with properties (rather than booking platforms) typically provides best rates, room assignment priority, and welcome amenity recognition.",
  },
  {
    name: "Bangkok VIP Hospitality & Private Member Clubs — The Invisible Elite Layer of Bangkok Social Life",
    emoji: "🥂",
    why: "Bangkok has a significant private member club and VIP hospitality ecosystem that functions parallel to the publicly visible luxury hotel and restaurant scene: (1) Private members' clubs in Bangkok: The Royal Bangkok Sports Club (RBSC, Henri Dunant Road, Pathum Wan) — established 1901; horse racing on track at property; tennis, squash, swimming, restaurant and bar; membership by application only; limited foreign membership available; the RBSC is the most prestigious social institution in Bangkok; the British Club Bangkok (Silom area) — established 1903; British Club membership accessible to British nationals and other nationalities; cricket, squash, tennis, swimming, restaurant/bar; cultural events; active expat social venue; The Royal Turf Club of Thailand (Samsen Road, Dusit) — horse racing club with social membership; The Royal Automobile Association of Thailand (established luxury motoring club); (2) Bangkok's VIP club and restaurant circuit: the private table reservation culture at Bangkok's luxury restaurants creates a tiered access system; top tier establishments maintain regular guests who book regular tables with chef relationship; examples: Gaggan Anand's new restaurant (tasting menu only, advance booking months out; VIP guests have maintained seat reservations); Jay Fai (walk-in or advance booking system that rewards relationship); Le Du (waitlist for prime seating); at the ultra-premium Bangkok dining tier, the relationship between guest and restaurant owner/chef is the primary access mechanism; (3) Bangkok's hotel club lounge circuit: the club lounges of Bangkok's luxury hotels (Capella, Rosewood, Peninsula, Four Seasons) function as de facto private dining rooms for Bangkok's business and social elite; morning breakfast at club lounges, afternoon working lunches, evening receptions — the club lounge format provides a private but hotel-hosted club function; many Bangkok business deals happen in these spaces; (4) Bangkok's elite social event circuit: the Bangkok social calendar for the ultra-high-net-worth set includes: charity gala dinners at major hotels (Red Cross fundraisers, hospital foundation galas — admission by donation, typically ฿5,000–50,000 per seat); gallery openings at River City Bangkok and private galleries; Bangkok Fashion Week events (limited access); product launches at luxury brand boutiques (Hermès, Louis Vuitton, Chanel at Emporium/EmQuartier have private client events); (5) Bangkok luxury brand boutique as social institution: Bangkok's Sukhumvit luxury corridor (Emporium, EmQuartier, The Mall Thong Lo) hosts all major international luxury brands; the Thai luxury brand market is primarily driven by Thai domestic consumers (ultra-high-net-worth Thai families, new wealth from real estate and construction); luxury brand regional events (Hermès equestrian events, Louis Vuitton Cruise shows) occasionally use Bangkok as a regional venue.",
    tip: "Bangkok VIP hospitality navigation: (1) RBSC day visit: the Royal Bangkok Sports Club's race days (horse racing schedule varies, typically weekend afternoons) are accessible to non-members for the race meeting admission (฿200–300); the racing paddock and track environment provides an authentic look at Bangkok's colonial-era social club legacy; (2) British Club visitor policy: the British Club Bangkok has reciprocal membership arrangements with some international clubs; check if your home club (particularly UK, Commonwealth, or certain US clubs) has reciprocal access before visiting Bangkok; (3) Fine dining advance booking strategy: for Bangkok's top restaurants (Gaggan Anand, Le Du, Nahm, Paste), book 3–6 weeks ahead for regular reservations and 2–3 months ahead for special occasion dining; booking directly (rather than through intermediaries) and building a relationship with the restaurant's booking system creates priority recognition over time; (4) Luxury hotel bar social observation: the lobby bars of Capella Bangkok (Phra Nakhon Bar), Mandarin Oriental (Bamboo Bar, ฿600+ minimum spend), and Peninsula Bangkok provide a window into Bangkok's upper business class social life without club membership requirement; evening hours (7–10pm) have the most active social dynamic; (5) Luxury brand invitation events: visiting Bangkok's flagship luxury boutiques (Hermès at Emporium, Chanel at EmQuartier, Louis Vuitton at Central Embassy) as a regular spending customer over multiple Bangkok visits can establish the brand relationship that results in private client event invitations; this is a slow process (12–24 months of relationship development minimum).",
  },
];

export function BangkokPrivateJet() {
  return (
    <div className="rounded-2xl border border-gray-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-gray-700 mb-3">
        ✈️ Bangkok ultra-luxury — private jet charter, beyond 5-star hotels & VIP member club circuit
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-gray-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-gray-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-gray-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
