const SPOTS = [
  {
    name: "Pattaya — Beyond the Stereotype to the Actual City",
    emoji: "🏙️",
    area: "Pattaya City: 150km southeast of Bangkok (2–2.5 hours via Motorway 7, or 3 hours by public bus from Ekamai); Chonburi Province, Gulf of Thailand; districts: North Pattaya (accommodation hub), Central Pattaya (tourist commercial core), South Pattaya (Walking Street nightlife), Jomtien Beach (south, quieter, family-oriented)",
    price: "Express bus Bangkok–Pattaya (Ekamai): ฿130–170; Bell taxi Bangkok–Pattaya shared: ฿300–500/seat; Songthaew (shared tuk tuk) within Pattaya: ฿10–20; Baht bus (Pattaya public transport): ฿10; Rental motorbike (day): ฿200–350; Mid-range hotel (3-star): ฿800–2,000/night; Beach club day pass: ฿300–800",
    why: "Pattaya's reputation as a sex tourism destination obscures its reality as a multi-dimensional city with genuine attractions beyond its nightlife infamy: (1) Genuine family resort infrastructure: South Pattaya's Walking Street is Bangkok media shorthand for Pattaya, but the majority of Pattaya's hospitality infrastructure serves Thai domestic family tourism, golf tourism, Russian beach holiday tourism, and general Asian resort tourism; (2) Sports and adventure: Pattaya is Bangkok's primary motorsport hub (Bira International Circuit for car and motorcycle racing, karting at multiple venues), watersports center (jet ski, parasailing, banana boat at Pattaya Beach; better quality at Koh Larn island), and golf cluster (35+ courses within 30km of Pattaya); (3) Koh Larn (Coral Island): the island 7km offshore from Pattaya provides cleaner beach and better snorkeling than Pattaya's main beach; ferry from Bali Hai Pier (30 min, ฿30–80 each way); despite being called Coral Island, the coral has degraded significantly but the beach sand and water quality is distinctly better than Pattaya; (4) Sanctuary of Truth: one of Thailand's most ambitious contemporary art-architecture projects; an entirely wood-carved structure inspired by 13th century Khmer and Thai temple traditions; construction began 1981 and continues; genuinely spectacular even under ongoing construction; (5) Art in Paradise: one of Southeast Asia's largest optical illusion art museums; photography-focused interactive art experience spanning multiple floors of trompe l'oeil environments.",
    tip: "Pattaya navigation for non-nightlife visitors: (1) Jomtien Beach vs. Pattaya Beach: Jomtien Beach (4km south of central Pattaya, 15 min by baht bus) is quieter, has somewhat cleaner water, and lacks the aggressive jet ski operators that crowd central Pattaya Beach; families and non-nightlife visitors benefit from basing at Jomtien; (2) Baht bus (songthaew) transport: Pattaya's shared songthaew trucks (baht buses) run fixed routes for ฿10 per person; standing in the street and waving stops them (hailing approach); agreeing on price before boarding prevents being quoted tourist prices; (3) Koh Larn timing: morning ferries to Koh Larn (first departure approximately 7:30am from Bali Hai Pier) reach the island before beach crowds; returning by 3pm avoids the afternoon ferry congestion; (4) Golf in Pattaya: booking Pattaya golf tee times through the hotel concierge or through golfasian.com/pattaya provides access to the full 35+ Pattaya course selection with transport; green fees range from ฿700 (weekday, municipal course) to ฿3,500 (premium resort course); (5) Traffic approaching Pattaya on weekends: Highway 7 from Bangkok to Pattaya is heavily congested Friday evenings and Sunday afternoons; timing travel to avoid peak hours (Friday 4–8pm, Sunday 3–7pm) saves 1–2 hours of sitting in traffic.",
  },
  {
    name: "Hua Hin — Royal Resort Town South of Bangkok",
    emoji: "👑",
    area: "Hua Hin: 200km south of Bangkok (2.5–3 hours by car via Highway 4 or toll expressway, 3.5 hours by train from Hua Lamphong); Prachuap Khiri Khan Province, Gulf coast; Thailand's oldest beach resort; Klai Kangwon Palace (current Royal Family beach residence, no public interior access); nearby: Kaeng Krachan National Park (50km), Khao Sam Roi Yot National Park (60km)",
    price: "Train Bangkok–Hua Hin (fan class): ฿100–200; Air-conditioned train: ฿350–700; Bus Bangkok–Hua Hin (Sai Tai Mai): ฿150–250; 3-star hotel (Hua Hin): ฿1,000–2,500/night; 5-star (Anantara, Sofitel, Intercontinental): ฿4,000–20,000/night; Hua Hin Night Market dinner: ฿200–600/person; Golf (Hua Hin country club): ฿1,500–3,500",
    why: "Hua Hin is Bangkok's most historically significant and internationally sophisticated beach escape — the royal family's continuing presence (the King spends significant time at Klai Kangwon Palace) creates elevated security and retail standards that distinguish Hua Hin from Pattaya's more chaotic environment: (1) Royal connection and historical atmosphere: Hua Hin has been a royal retreat since Rama VII (the Railway Hotel, now Centara Grand, hosted the royal family from 1924); the town's colonial-era architectural heritage (Hua Hin Railway Station — one of the most photographed wooden railway stations in Thailand) preserves a leisurely resort atmosphere; (2) Night market quality: Hua Hin Night Market (Dechanuchit Road) is consistently rated among Thailand's best; fresh seafood at Thai prices in a clean, organized market setting; (3) Elephant sanctuary: Elephant Village and similar operations near Hua Hin provide ethical elephant interaction alternatives to riding; (4) Khao Sam Roi Yot National Park: 60km from Hua Hin; limestone cave system (Phraya Nakhon Cave with its royal sala pavilion lit by a skylight) and wetland bird watching make this one of Thailand's most visually dramatic national parks; (5) Hua Hin active tourism: cycling (Hua Hin's flat terrain), kite surfing (Hua Hin's reliable wind), and water sports provide activity options beyond passive beach relaxation.",
    tip: "Hua Hin travel planning: (1) Train experience: the Bangkok–Hua Hin train journey (3.5 hours, coastal and rice paddy views) is one of Thailand's more scenic short train journeys; second-class air-conditioned seats (฿350–700) provide comfortable travel on the correct train; confirming train schedule at hua Lamphong or Bang Sue rather than relying on schedules is practical (trains can run late); (2) Hua Hin driving approach: many Bangkok families drive to Hua Hin (2.5–3 hours on the expressway via Phetkasem Road or Highway 4); the route is simple and well-signed; weekend return traffic from Hua Hin to Bangkok Sunday afternoon is notoriously congested; (3) Khao Sam Roi Yot cave visit: Phraya Nakhon Cave requires a 3km hillside walk (30–40 min); the skylight-illuminated pavilion inside the cave is photographed at approximately 10am when sunlight enters directly; planning visit for morning illumination maximizes the photographic experience; (4) Kite surfing conditions: Hua Hin's wind is most reliable November–February (northeast monsoon season); kite surf schools (multiple on Hua Hin Beach) offer beginner lessons for ฿1,500–3,000 for a 2-hour session; (5) Hua Hin for families: the town's safe swimming beaches (Hua Hin Beach itself is large and family appropriate), abundance of family resort infrastructure, and proximity to Bangkok make it Thailand's most practical family beach destination for Bangkok residents.",
  },
  {
    name: "Ayutthaya & Kanchanaburi — Essential Bangkok Day Trips",
    emoji: "🏯",
    area: "Ayutthaya: 80km north of Bangkok (1–1.5 hours by car or train); Ayutthaya Province; UNESCO World Heritage Site (former Siamese capital, 1351–1767); Kanchanaburi: 130km northwest of Bangkok (2–2.5 hours by car); Kanchanaburi Province; Death Railway and River Kwai War memorial; Erawan National Park waterfall",
    price: "Train Bangkok–Ayutthaya (฿20 third class, ฿30 second class); Taxi/Grab Ayutthaya round trip within ruins: ฿200–500; Tuk tuk temple tour (negotiated): ฿300–600; Bicycle rental Ayutthaya: ฿50–80; Ayutthaya UNESCO site entry (per temple): ฿50; Bus Bangkok–Kanchanaburi (Southern Bus Terminal): ฿100–150; JEATH War Museum entry: ฿40; Erawan National Park entry (foreigner): ฿300; Erawan minibus from Kanchanaburi: ฿50–80",
    why: "Ayutthaya and Kanchanaburi represent the two most important historical day trips from Bangkok: (1) Ayutthaya — Thailand's former imperial capital: Ayutthaya served as Thailand's capital for 417 years (1351–1767) before Burmese forces burned the city; the ruins left behind — hundreds of stupas, monastery complexes, and Buddha images — create one of Southeast Asia's most significant archaeological landscapes; the most haunting image: Buddha heads grown into tree roots at Wat Mahathat; (2) Kanchanaburi — Second World War memorial: the Death Railway (Thailand–Burma Railway) built by Allied POWs and Asian forced laborers under Japanese occupation during WWII is memorialized at Kanchanaburi; the Bridge on the River Kwai (the Tamarkan Bridge), JEATH War Museum, and the Commonwealth War Cemetery are among Southeast Asia's most significant WWII heritage sites; (3) Erawan Falls: within Erawan National Park (65km from Kanchanaburi), the seven-tiered emerald-green waterfall with natural limestone pools is one of Thailand's most beautiful national parks destinations; swimming in the falls is permitted (lower tiers only); (4) Death Railway scenic route: the Kanchanaburi to Nam Tok train (Friday, weekends) follows a section of the original Death Railway; the Wangpho Viaduct section clinging to limestone cliffs over the River Kwai is Thailand's most dramatic railway engineering; (5) Ayutthaya floating market: the Ayutthaya Floating Market operates daily at a historic restored riverside area; less authentic than it appears (designed for tourism) but accessible and photogenic.",
    tip: "Ayutthaya and Kanchanaburi day trip logistics: (1) Ayutthaya train simplicity: the Ayutthaya train from Bangkok's Bang Sue Grand Station is the most straightforward transport (20–30 baht, approximately hourly); the station deposits arrivals within walking/tuk-tuk distance of the historic zone; (2) Ayutthaya bicycle vs. tuk tuk: renting a bicycle at Ayutthaya (฿50/day, multiple rental shops near the station) provides maximum flexibility to stop at specific ruins; tuk tuk circuit tours run to a fixed route of major sites at fixed pricing; combining both (bicycle for independent exploration plus tuk tuk for more distant sites) is efficient; (3) Kanchanaburi weekend train: the Death Railway scenic section train runs specifically on weekends (Friday, Saturday, Sunday); the journey from Kanchanaburi to Nam Tok (2 hours) with the railway bridge section is the experiential highlight; checking the State Railway schedule for confirmed departure times before planning; (4) Erawan falls timing: Erawan National Park limits daily visitor numbers; arriving before 10am ensures entry without waiting; the lower tiers are most accessible and most crowded; upper tiers (4–7) require more hiking but have more dramatic pools; (5) Kanchanaburi WWII sites respect: the Commonwealth War Cemetery and JEATH War Museum are places of genuine historical solemnity; respectful behavior (quiet voices, no climbing on commemorative structures) is appropriate and expected.",
  },
];

export function BangkokPattayaGuide() {
  return (
    <div className="rounded-2xl border border-teal-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-teal-700 mb-3">
        🏙️ Bangkok day trips & escapes — Pattaya reality check, Hua Hin royal resort & Ayutthaya ruins
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-teal-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-teal-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
