const SPOTS = [
  {
    name: "Bangkok Helicopter Tours & Scenic Flights — Aerial Views of Bangkok & Gulf Coast Day Trips",
    emoji: "🚁",
    area: "Bangkok helicopter departure points: Samut Prakan Helipad (south Bangkok, accessible by MRT Blue Line to Srinagarindra then transfer); Don Mueang Airport (northern Bangkok, BTS + shuttle or Grab); Suvarnabhumi Airport vicinity (eastern Bangkok, BTS Gold Line + Grab); Bangkok helicopter operators: Asian Helicopter Services (charter and tours); Blue Horizon Helicopters (scenic tours); various aviation charter companies based at Don Mueang; for fixed-wing scenic flights: Cessna/small aircraft tours operated from Khlong 11 Airfield or similar general aviation strips north of Bangkok",
    price: "Bangkok aerial tour pricing: helicopter scenic flight (20–30 minutes over Bangkok): approximately ฿8,000–15,000 per person (varies significantly by operator and minimum passenger requirement); private helicopter charter (4-6 passenger): ฿30,000–80,000 per hour depending on aircraft type; Bangkok to Ko Samet helicopter (60 minutes vs. 3–4 hours ground): approximately ฿15,000–25,000 per person one-way; helicopter to Hua Hin: approximately ฿12,000–18,000 per person; seaplane exploration (floatplane service when available): check current operators as services vary; ultralight aircraft pleasure flights: ฿2,000–5,000 for 20–30 minutes at airfields outside Bangkok",
    why: "Bangkok from the air presents a completely different urban understanding — the scale, the river system, the concentric ring road system, the temple density, and the contrast between the dense urban core and the agricultural fringe become immediately apparent from altitude: (1) Bangkok's aerial geography: Bangkok from above reveals the Chao Phraya River's S-curve as the organizing spine of the original city (Rattanakosin Island and the Grand Palace visible in the river meander); the BTS elevated rail lines visible as silver threads connecting the city's commercial centers; the contrast between Sukhumvit's dense high-rise corridor and the low-rise neighborhoods just one block off the main roads; the canals (klongs) visible as thin blue lines through the urban fabric; (2) Bangkok's visual scale from altitude: Bangkok's metropolitan area covers approximately 7,761 sq km (larger than the entire island of Bali); the transition from Bangkok's urban core to the flat agricultural delta visible within 20–30km of the center creates a dramatic before-after aerial panorama; Bangkok's lack of natural height variation (the city averages 1.5m above sea level) means the aerial view at 300–500m altitude shows an extraordinarily flat urban landscape; (3) Best aerial views from skyscrapers as free alternatives: for the aerial Bangkok view without helicopter cost: Mahanakhon Tower (314m, Bangkok's tallest, King Power SkyWalk, glass floor, BTS Chong Nonsi) — ฿880 adult; Baiyoke Tower II (309m, Pratunam, currently observation deck closed for renovation — verify current status); State Tower (Lebua Hotel rooftop, Silom — open to diners, bar minimum spend ฿1,500+; famous Hangover 2 scene); Vertigo and Moon Bar (Banyan Tree Hotel, 61st floor, Sathorn); (4) Fixed-wing aircraft tourism out of Bangkok: a small number of operators offer Cessna/Piper-style scenic flights from general aviation airfields north and east of Bangkok; these provide lower-cost aerial views compared to helicopters; the view quality depends heavily on visibility; Bangkok's dry season (November–February) provides the clearest visibility for aerial photography; during monsoon season (May–October) cloud cover and haze can significantly limit aerial views; (5) Helicopter transfer vs. scenic tour: the primary Bangkok helicopter market is transfer (Bangkok city to beach resorts: Pattaya, Hua Hin, Ko Samet, Ko Chang) rather than pure sightseeing; these transfers compete on time savings (Bangkok to Pattaya: 25 minutes by helicopter vs. 1.5–2.5 hours by car); for tourists, the helicopter transfer doubles as an aerial tour of Bangkok's metropolitan area during departure.",
    tip: "Bangkok aerial experience planning: (1) Skyscraper alternative: before booking a helicopter tour, visit Mahanakhon SkyWalk (BTS Chong Nonsi) for Bangkok aerial views — at ฿880 this provides comparable visual reference for the city's urban geography without scheduling complexity; (2) Helicopter tour booking: contact Asian Helicopter Services or Blue Horizon through their websites or through luxury hotel concierges (Mandarin Oriental, Peninsula Bangkok, Capella Bangkok all have established helicopter relationships for guest transportation); (3) Optimal aerial tour timing: morning (7–9am) provides best visibility and lighting for Bangkok aerial photography — afternoon convective weather (cumulus clouds developing over the city) can create turbulence and reduce visibility; (4) Helicopter to Pattaya: if planning a Pattaya day trip from Bangkok, the helicopter option reduces round-trip transit from 3–5 hours to 50 minutes total; group bookings (4–6 passengers) make per-person costs more reasonable; contact luxury Pattaya beach clubs (Horizon Beach Club, Nobu Hotel Pattaya) which offer Bangkok helicopter package deals including beachclub day access; (5) Photography on aerial tours: request the co-pilot seat (front left) for photography; Bangkok's flat terrain means almost any altitude above 200m provides good city views; late afternoon light (4–5pm) creates long shadows that add dimension to Bangkok's otherwise flat-appearing cityscape from above.",
  },
  {
    name: "Bangkok Private Rooftop Access & Luxury Sky Dining — Height Premium Restaurant Experiences",
    emoji: "🌆",
    area: "Bangkok rooftop restaurants and sky bars (geographic coverage): Silom/Sathorn area — Vertigo & Moon Bar (Banyan Tree Hotel, 61st floor), Breeze (State Tower/Lebua, 51st floor), Sirocco (State Tower/Lebua, 63rd floor, open-air), Mezzaluna (State Tower/Lebua, 65th floor, fine dining); Sukhumvit area — Above Eleven (33rd floor, Sukhumvit Soi 11, bar and Japanese-Peruvian), Sugar Ray (rooftop bar, Ekkamai), various BTS Asok vicinity hotel rooftops; Riverside area — Riva del Fiume (Capella Bangkok), Sala Rattanakosin rooftop (near Grand Palace); Siam area — CRU Champagne Bar (CentralWorld, 17th floor, champagne focus); Chatuchak/northern Bangkok — Radio Rooftop Bar (Novotel Chatuchak area); Charoen Krung area — Warehouse 30 adjacent rooftops",
    price: "Bangkok sky restaurant pricing: rooftop bar minimum spend: typically ฿500–1,500 per person (varies by venue and day of week); Sirocco dinner (Lebua State Tower, iconic location): ฿2,500–5,000+ per person; Mezzaluna dinner (State Tower): ฿6,000–12,000 per person tasting menu; Vertigo & Moon Bar: no food minimum, drinks from ฿450–700 each, recommended ฿1,000–1,500+ budget per person; Above Eleven: cocktails ฿300–500, no minimum during most hours; Capella Bangkok riverside fine dining: ฿4,000–8,000 per person; rooftop bar cocktail prices across Bangkok: ฿350–700 for signature cocktails; hotel rooftop happy hour (many venues, 5–7pm): ฿200–350 per drink",
    why: "Bangkok's rooftop dining culture has created an entire elevated economy — both literally and figuratively — where height premium justifies significant price markup over street-level equivalents: (1) Bangkok's rooftop geography: Bangkok's flat topography (1.5m average elevation) means that even moderate building height creates dramatic panoramic views; a 50th-floor rooftop at approximately 150–180m elevation provides unobstructed 360-degree views extending 20–30km in all directions; the lack of hills means no high terrain interrupts sight lines; (2) Sirocco — Bangkok's most filmed rooftop: the State Tower's Sirocco restaurant (Charoen Krung Road, Silom area) became globally famous as the filming location for The Hangover Part II (2011); the 63rd-floor open-air circular terrace with columns has become an internationally recognized Bangkok landmark; the restaurant experience itself (Mediterranean cuisine, extensive wine list) is secondary in most guests' priorities to the location; reservations recommended, especially for peak hours (7–9pm); dress code enforced (no shorts, sandals, sleeveless shirts); (3) Vertigo vs. Sirocco vs. Mezzaluna — the height premium matrix: Vertigo (Banyan Tree, 61st floor, ฿1,000–1,500+ per person): best for casual visitors and non-dining sky-bar experience; Sirocco (State Tower, 63rd floor, ฿2,500–5,000+): for the iconic location + dinner experience; Mezzaluna (State Tower, 65th floor, ฿6,000–12,000): highest point, genuine fine dining quality for those prioritizing culinary experience with height; all three visible from each other at night; (4) Rooftop bar culture dynamics: Bangkok's rooftop scene is heavily international tourist-facing; many rooftop bars have significant service markup over comparable ground-level venues; the premium pays for: the view (genuinely spectacular from major venues), the experience narrative, and the social sharing value; Thai locals predominantly visit for special occasions rather than regular entertainment; (5) Sunset reservation timing: Bangkok's 5:30–6:30pm sunset creates a critical reservation window — the best rooftop experience is arriving 45 minutes before sunset and remaining through the blue hour; popular rooftop venues (Vertigo, Sirocco, Mezzaluna) are often fully booked for the 5–7pm window 1–2 weeks ahead during peak season (November–February); advance reservation is essential.",
    tip: "Bangkok rooftop booking strategy: (1) Advance reservation for prime venues: Sirocco, Mezzaluna, and Vertigo accept reservations — book online or by phone 1–2 weeks ahead for Friday–Sunday sunset slots during November–February; without reservation, entry may be refused when at capacity; (2) Dress code reality: all State Tower (Sirocco/Mezzaluna/Breeze/Distil) venues enforce dress code — smart casual minimum; no flip flops, no shorts for men, no sleeveless casual tops; bring a light layer for the open-air venues as Bangkok rooftops can be windier than expected; (3) Value optimization: the best price-to-experience ratio for Bangkok rooftop is happy hour (5–7pm at most venues, cocktails ฿200–350 vs. full-price ฿450–700); arrive at happy hour, enjoy the sunset, and either continue for full-price cocktails or depart; happy hour at Above Eleven (Sukhumvit Soi 11) provides excellent views and Japanese-Peruvian bar food at moderate pricing; (4) Photography at rooftop venues: most Bangkok rooftop venues allow photography; Sirocco's distinctive columns and circular terrace create the most recognizable Bangkok rooftop photography; best camera positions: facing south toward the State Tower's helical facade, or north toward the Chao Phraya River curve; (5) Alternative heights: for sunset viewing without rooftop restaurant pricing, the Mahanakhon SkyWalk (฿880) and the Golden Mount (Wat Saket, 76 steps, ฿20–50 entry) provide legitimate aerial Bangkok views; Wat Saket's Golden Mount provides a different perspective — historic temple bells, Buddhist imagery, and 360-degree view of inner Bangkok at ฿50 entry.",
  },
  {
    name: "Bangkok Hot Air Balloon & Extreme Activities — Adventure Tourism Near the Capital",
    emoji: "🎈",
    area: "Bangkok adventure activities geography: hot air balloon operations: Hua Hin (2.5 hours from Bangkok, multiple operators in the hills north of Hua Hin); Chiang Rai (30-minute flight from Bangkok, northern Thailand hot air balloon capital — dedicated sunrise balloon operations); within Bangkok metro area: skydiving (Pattaya, 90 minutes from Bangkok — Thai Sky Adventures operated from U-Tapao Airport); bungee jumping: AJ Hackett Bangkok (historical location Samitivej Hospital area — VERIFY current operation as location has changed); Jungleflight zipline: Nakhon Nayok province (100km from Bangkok, 1.5 hours, ziplines through jungle canopy); rock climbing: SCALA Climbing Gym (Bangkok, indoor competition-level facility) + Khao Yai limestone sport climbing (150km from Bangkok)",
    price: "Bangkok adventure activity pricing: hot air balloon Hua Hin: ฿5,000–8,000 per person for sunrise flight (60–90 minutes); hot air balloon Chiang Rai: ฿5,000–7,000 per person sunrise; skydiving Pattaya (tandem): ฿12,000–18,000 per person (altitude varies — 10,000ft to 14,000ft options); bungee jumping (if available): verify current provider and pricing; zipline Nakhon Nayok Jungleflight: ฿3,500–6,500 depending on course length; parasailing Pattaya beach: ฿600–1,000 per person (15 minutes); ATV Pattaya: ฿800–2,000 per hour depending on track access; wakeboarding Cable Park Pattaya: ฿500–800 per hour; indoor skydiving Bangkok (iFly-style): when available ฿1,500–2,500 for introductory session",
    why: "Bangkok itself has limited within-city extreme adventure options due to its flat, densely built-up geography — but the surrounding region within a 3-hour drive offers a surprising range of adventure activities: (1) Hot air balloon landscape — why Hua Hin and Chiang Rai: Hua Hin's balloon operations use the hills and fields north of the beach resort area for launch and landing; the balloon provides views of the Gulf of Thailand coast and the rolling hills of Prachuap Khiri Khan province; Chiang Rai's balloon culture is more developed, with dedicated sunrise operations from the rice fields and tea plantations north of the city — the Chiang Rai hot air balloon scene is the most photographed in Thailand; (2) Skydiving at Pattaya U-Tapao Airport: Thailand's primary civilian skydiving operation runs from U-Tapao International Airport (near Pattaya); Thai Sky Adventures offers tandem skydiving (experienced instructor + novice in tandem harness) with optional accelerated freefall (AFF) certification courses; U-Tapao's flat Gulf coast geography creates spectacular ocean views during freefall and canopy phase; the flight from Bangkok to Pattaya by car (90 minutes) makes U-Tapao skydiving a Bangkok day-trip activity; (3) Khao Yai adventure activities (3 hours from Bangkok): Khao Yai National Park and the surrounding Pak Chong area offer the most diverse adventure options within day-trip range of Bangkok: white water rafting on the Wang Takrai rapids (seasonal, July–November); ATV tours through jungle tracks; zipline operations; mountain biking; rock climbing on Khao Yai limestone; the Khao Yai area's elevation (400–1,000m above Bangkok's sea-level) creates cooler temperatures and jungle environments completely different from Bangkok; (4) Pattaya's adventure ecosystem: Pattaya's coastal resort infrastructure includes multiple adventure operators — parasailing from beach, jet ski (higher accident rate, use operator insurance and personal safety gear), wakeboarding Cable Park, flyboard (water jet propulsion), banana boats, and deep-water shark diving (operator-mediated, not open water); Pattaya's adventure tourism is heavily concentrated around the beach area and is price-competitive; (5) Bangkok indoor climbing and wall sports: Bangkok has a growing indoor rock climbing community with multiple climbing gyms: SCALA Bangkok (professional facility, lead and bouldering walls, competition-level routes); The Bloc (Bangkok branch of Hong Kong bouldering chain); Rock Corner Bangkok; for experienced climbers, these facilities serve as training for outdoor routes at Railay Beach (Krabi), Crazy Horse Buttress (Chiang Mai), and Pha Nok Khao (Phetchabun).",
    tip: "Bangkok adventure day trip planning: (1) Pattaya day trip for skydiving: book Thai Sky Adventures (thaiskyadventures.com) online — minimum 24–48 hours advance; transport from Bangkok to Pattaya by Grab (1.5 hours, ฿700–1,000 one-way) or bus from Ekkamai (1.5 hours, ฿100–130); pair with Pattaya beach or dining for a full day trip; (2) Hua Hin balloon booking: Hua Hin balloon operators run sunrise flights (5:30–6am departure, therefore requiring overnight stay in Hua Hin the night before or extremely early Bangkok departure); book through Hua Hin operator websites or through Bangkok-based tour operators; wind conditions cause cancellations — operators typically offer rescheduling; (3) Nakhon Nayok Jungleflight: the Nakhon Nayok zipline operation (1.5 hours from Bangkok by Grab — approximately ฿1,200–1,500 one-way) includes a jungle trekking component and can be combined with the Wang Takrai waterfall area; this makes a good self-organized Bangkok day trip; (4) Rock climbing preparation: for beginners interested in Thai limestone sport climbing, starting with 2–3 sessions at a Bangkok indoor climbing gym before traveling to Railay Beach makes the outdoor experience dramatically more enjoyable; SCALA Bangkok offers introductory sessions without prior experience; (5) Safety on Pattaya water sports: jet ski rental in Pattaya has a history of scam operations (pre-existing damage claims); if renting jet ski, video the condition thoroughly before departure; parasailing is generally lower-risk — verify the operator harness quality and safety record through recent TripAdvisor or Google Reviews before booking.",
  },
];

export function BangkokHeli() {
  return (
    <div className="rounded-2xl border border-indigo-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-indigo-700 mb-3">
        🚁 Bangkok from above — helicopter tours & aerial views, rooftop sky dining & adventure activities
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-indigo-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-indigo-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-indigo-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
