const TOPICS = [
  {
    title: "Bangkok Air Quality — PM2.5, Smog Season & What It Means for Your Visit",
    emoji: "🌫️",
    summary: "Bangkok has one of Southeast Asia's most significant urban air quality challenges, and understanding it is essential for visit planning: (1) Bangkok's air quality baseline: Bangkok's annual PM2.5 average consistently exceeds WHO guidelines (WHO safe annual mean: 5 µg/m³; Bangkok annual average: 20–35 µg/m³; peak smog days: 80–200+ µg/m³); the city is classified as having moderate to unhealthy air quality for sensitive groups for significant portions of the year; (2) Seasonal air quality pattern: Bangkok has a distinct seasonal smog cycle — dry season (January–April) is worst for air quality as agricultural burning (in northern Thailand, Myanmar, Laos) combines with stagnant low-wind conditions and Bangkok's own vehicle/industrial emissions to create severe smog events; particularly February–April, Bangkok can experience 'Haze Season' with AQI (Air Quality Index) levels above 150 (Unhealthy) and visible yellow-brown haze; (3) Rain season air quality improvement: Bangkok's rainy season (June–October) significantly improves air quality; rain washes PM2.5 from the atmosphere; the green season (when many budget travelers avoid Bangkok due to rain) actually has noticeably better air quality; (4) Bangkok's PM2.5 sources: Bangkok's air quality degradation comes from multiple sources: vehicle emissions (Bangkok's 10M+ registered vehicles, diesel trucks on expressways), industrial emissions (Map Ta Phut industrial estate in Rayong, upwind), agricultural burning (distant but significant seasonal), and local sources (street food charcoal grills, construction dust, refuse burning in outer districts); (5) Microclimate variation within Bangkok: Bangkok's air quality varies significantly by neighborhood and time of day; areas adjacent to expressways and high-traffic roads (particularly diesel truck routes) have worse air quality than BTS-adjacent areas; Lumphini Park has measurably better air than adjacent Wireless Road; Thonburi residential areas often show slightly better AQI than central Bangkok due to lower traffic density.",
    action: "Real-time Bangkok AQI monitoring: IQAir (iqair.com), AirVisual app, and AQICN (aqicn.org/city/bangkok) — all show Bangkok district-level PM2.5 data; Thai Pollution Control Department: pcd.go.th for official Thai government AQI data; protective measures: N95/KN95 masks (not paper surgical masks) provide meaningful PM2.5 filtration; hotel/condo with air purifier is beneficial during haze season; outdoor exercise timing: early morning (5–8am) typically shows lower PM2.5 than afternoon on most Bangkok days.",
  },
  {
    title: "Bangkok Flooding — Monsoon Season, Canal Overflow & Climate Resilience",
    emoji: "🌊",
    summary: "Bangkok's low-lying geography and monsoon climate create a recurring flooding challenge that has significant implications for visitors: (1) Bangkok's fundamental flooding geography: Bangkok is built on an ancient floodplain 1.5 meters above sea level, crossed by canals (khlongs) originally designed for seasonal water management; the city subsides (sinks) at 1–2cm annually due to groundwater extraction, making long-term flood management increasingly challenging; (2) Seasonal flooding pattern: Bangkok's wet season (May–October, peak July–October) brings regular street flooding in flood-prone neighborhoods; flooding from rainfall alone (pluvial flooding) occurs within hours of heavy rain events; canal overflow flooding occurs when Chao Phraya river flow combined with high tide backs up the city's drainage system; (3) The 2011 mega-flood as context: Bangkok's 2011 floods (October–December) were the country's worst in 50 years — northern Thailand flooding overwhelmed the Chao Phraya basin and inundated large parts of Bangkok for months; 7 industrial estates flooded (devastating Toyota, Honda supply chains); the 2011 event shaped Thailand's subsequent flood management investment including the Bangkok ring dyke system; (4) Tourist impact of flooding: central Bangkok tourist areas (Sukhumvit BTS corridor, Silom, Ratchaprasong) are typically protected by pumping infrastructure and are among the last to flood; outer Bangkok residential and industrial areas flood more frequently; tourists with standard itineraries rarely experience significant flood disruption except during extreme events; (5) Traffic and BTS impact: Bangkok flooding significantly impacts ground transport; flooded roads force traffic onto BTS/MRT (which becomes extremely crowded); BTS itself has not flooded its stations in routine events (stations are elevated); during city-wide flood events, airport taxi service becomes unreliable; BTS to Suvarnabhumi airport link remains operational during most flooding.",
    action: "Bangkok flood monitoring: BMA Flood Monitoring Center (Bangkok Metropolitan Administration) provides area-specific flood alerts; Bangkok BTS operational status during flooding: BTS SkyTrain app and @BTS_SkyTrain Twitter/X for station closures; Bangkok flood tracker during wet season: Thailand Meteorological Department (tmd.go.th); practical preparation for Bangkok rainy season visits: carry compact umbrella (not large umbrella, too bulky for BTS), plan for afternoon thunderstorms (daily pattern), wear waterproof footwear or bring second pair, expect BTS overcrowding during rain events.",
  },
  {
    title: "Bangkok Heat Stress — Managing Tropical Climate, Heat Exhaustion & Clothing",
    emoji: "🌡️",
    summary: "Bangkok's heat is a genuine physical challenge that requires active management, not just an inconvenience: (1) Bangkok's heat data: Bangkok's average daily maximum temperature is 33–36°C (91–97°F) year-round with higher heat index due to humidity; relative humidity ranges from 60–85%; the heat index (apparent temperature combining heat and humidity) regularly exceeds 40–44°C (104–111°F) during March–May peak heat; Bangkok does not have a 'mild' or 'cool' month in the Western sense; even the 'cool season' (November–February) averages 30–32°C maximum; (2) Heat exhaustion risk profile: Bangkok's heat is a serious health risk for: new arrivals (body takes 7–14 days to acclimatize); elderly visitors (reduced heat regulation capacity); visitors who do sustained outdoor activity (walking temple circuits, market shopping) during midday hours; people who are dehydrated (common with new visitors who don't consume enough water); (3) Heat exhaustion recognition and response: symptoms include heavy sweating, cold/pale/clammy skin, fast weak pulse, nausea, muscle cramps, weakness, dizziness, fainting; response: move to AC space immediately, hydrate with water/electrolytes, rest; Bangkok has pharmacies (Boots, Watsons) with oral rehydration salts (ORS) — electrolyte drinks; Bumrungrad or Bangkok Hospital emergency for severe cases; (4) Optimal Bangkok activity timing: Bangkok's experienced residents and visitors use a split-day pattern — active outdoor periods from 7–10am and again from 5–8pm; midday hours (11am–4pm) are spent in AC environments (malls, restaurants, hotel); temple visits, market shopping, and outdoor activities are done in early morning or late afternoon; (5) Hydration math in Bangkok: a person walking in Bangkok's heat can lose 1–2 liters of sweat per hour; the minimum hydration target is 3–4 liters of water per day for a moderately active visitor; bottled water (Singha, Nestle, Chang brand) is widely available and cheap (฿10–20 for 600ml); electrolyte sachets or sports drinks (Pocari Sweat, Gatorade) are available at 7-Eleven and pharmacies and are important for heavy sweating days.",
    action: "Bangkok sun protection: SPF 50+ sunscreen (available at Boots, Watson's, 7-Eleven), reapply every 2 hours during outdoor exposure; Pocari Sweat (Japanese electrolyte drink, widely available in Thailand) is preferred over plain water for heavy-sweating situations; pharmacy electrolyte sachets (ORSALIT, available at Boots and Guardian Pharmacy) for severe dehydration; heat exhaustion first aid: Bumrungrad ER 02-667-1000; clothing guidance: light-colored loose synthetic fabrics (moisture-wicking) outperform cotton in Bangkok heat — cotton stays wet; small portable fan (USB rechargeable) is a useful Bangkok accessory for outdoor queuing.",
  },
];

export function BangkokPollution() {
  return (
    <div className="rounded-2xl border border-gray-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-gray-700 mb-3">
        🌫️ Bangkok environment — air quality, flooding & heat management guide
      </h2>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-gray-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-gray-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
