const SPOTS = [
  {
    name: "Maternity Hospitals & Prenatal Care in Bangkok",
    emoji: "🤱",
    area: "Bangkok's top maternity hospitals: Samitivej Sukhumvit (Sukhumvit Soi 49), Bangkok Hospital Pattaya and Bangkok Hospital main (Petchburi area), Bumrungrad International (Asoke/Sukhumvit), Praram 9 Hospital, Ramathibodi Hospital (public), Paolo Hospital chains — maternity wards concentrated in Sukhumvit medical corridor",
    price: "Prenatal check-up (first trimester): ฿1,500–5,000; Ultrasound (standard): ฿800–2,500; Full prenatal blood panel: ฿3,000–8,000; Monthly OB-GYN consultation: ฿1,500–4,000; Natural delivery (hospital fee only): ฿50,000–150,000; Cesarean section delivery: ฿80,000–250,000; Private labor room (per night): ฿8,000–30,000",
    why: "Bangkok's private hospital system is among Asia's best for maternity care — combining JCI-accredited hospital standards, multilingual medical staff, and costs significantly lower than equivalent care in the US, UK, Australia, or Singapore. Why international parents choose Bangkok for maternity care: (1) Cost advantage: a complete pregnancy care package (all prenatal visits + delivery + post-natal care) at Samitivej or Bumrungrad runs ฿150,000–400,000 for natural birth — significantly less than equivalent care in most Western countries; (2) Hospital quality: Bangkok's top private hospitals have maternal-fetal medicine specialists, neonatal ICU capabilities, and maternity suites that exceed many Western hospitals in physical comfort; (3) Multilingual care: all major private Bangkok hospitals have OB-GYN specialists who are fluent in English (many trained abroad); several have Korean, Japanese, and Chinese-speaking specialist teams; (4) Integrated maternity programs: Samitivej and Bangkok Hospital offer comprehensive 'Happy Mom' style prenatal packages that bundle all check-ups, childbirth preparation classes, and delivery into a fixed-price program; (5) Residency continuity: Bangkok-based expats often benefit from prenatal care continuity as they plan their long-term Bangkok stay around the delivery timeline.",
    tip: "Bangkok maternity care planning: (1) Obstetrician selection first: choosing your OB-GYN early (first trimester ideally) and at a hospital where they have delivery privileges determines your hospital choice; switching mid-pregnancy is possible but disruptive; (2) Insurance coverage: confirming that your international health insurance covers maternity in Thailand (and specifically at your chosen hospital) is essential before the first prenatal appointment; major international insurers (Cigna, Aetna, AXA, BUPA International) typically cover Bangkok's JCI hospitals; (3) Samitivej vs. Bangkok Hospital vs. Bumrungrad: all three are excellent; Samitivej has the strongest reputation specifically for maternity among Bangkok's expat community; Bumrungrad has the most international patient infrastructure; Bangkok Hospital has multiple branches across Thailand for consistent records if you travel; (4) Thai public hospital consideration: Thai citizens often deliver at public hospitals (Ramathibodi, Siriraj, Chulalongkorn) at very low cost; these hospitals are excellent but require Thai language navigation; (5) Newborn documentation: Thai birth registration for expat parents requires specific documentation steps; planning the birth certificate and nationality documentation requirements in advance (through your home country's embassy in Bangkok) prevents stressful post-birth administrative gaps.",
  },
  {
    name: "Pregnancy Wellness & Birth Preparation in Bangkok",
    emoji: "🧘",
    area: "Prenatal yoga studios in Bangkok: multiple studios in Thonglor, Phrom Phong, Ari, and Silom offer prenatal yoga; hypnobirthing classes (Hypnobirthing Thailand); breastfeeding support (La Leche League Bangkok, hospital lactation consultants); prenatal massage (at spas with certified prenatal massage training)",
    price: "Prenatal yoga class (drop-in): ฿400–800; Prenatal yoga monthly pass: ฿3,500–8,000; Hypnobirthing course (full program): ฿8,000–20,000; Prenatal massage (60 min): ฿800–2,000; Antenatal childbirth class series (hospital): ฿5,000–15,000; Doula services (full birth support): ฿15,000–50,000",
    why: "Bangkok's wellness industry has developed strong maternity-specific programming alongside the city's general wellness culture. Key Bangkok pregnancy wellness resources: (1) Prenatal yoga: multiple Bangkok yoga studios offer classes specifically designed for pregnancy (avoiding prone positions, adjusting inversions, focusing on breathing and hip opening); some are taught by teachers who are also certified midwives or have specialized pregnancy yoga training; (2) Hypnobirthing: the hypnobirthing childbirth preparation method (using relaxation techniques to manage labor pain) has active Bangkok practitioners; international-standard hypnobirthing certification programs are available in Bangkok for those wanting training; (3) Prenatal massage: Thai massage has specific adaptation protocols for pregnancy; certified prenatal massage therapists at Bangkok spas offer safe treatments; not all Thai massage practitioners are prenatal-trained, so confirming certification is important; (4) Doula services: professional birth doulas (labor support companions) operate in Bangkok's international expat community; doulas provide continuous labor support that complements the hospital medical team; (5) La Leche League Bangkok: the international breastfeeding support organization has an active Bangkok chapter offering mother-to-mother support for breastfeeding, particularly valuable for international mothers navigating breastfeeding in a new country.",
    tip: "Bangkok pregnancy wellness navigation: (1) Prenatal yoga studio safety: confirming that the prenatal yoga teacher has specific prenatal yoga training (not just a general yoga instructor certification) ensures the modifications and contraindications are properly managed; ask about instructor credentials when booking; (2) Trimester timing: prenatal yoga programs are designed around pregnancy trimester; joining classes at the appropriate trimester stage ensures the exercises match your pregnancy stage; (3) Thai postpartum food culture: Thai traditional postpartum practice (yu fai — lying by the fire) has evolved into Bangkok's contemporary postpartum catering services; traditional postpartum food (khao tom — rice soup, galangal soups, specific herb-based dishes) can be ordered from specialized Bangkok catering services during the postpartum recovery period; (4) Expat mother community: Bangkok has active expat mother Facebook groups (eg 'Bangkok Mums', nationality-specific parenting groups) that provide practical advice on navigating maternity care, pediatric hospitals, and childcare in Bangkok; (5) Postpartum confinement services: Bangkok has specialized postpartum confinement centers (primarily serving Chinese, Korean, and Taiwanese expatriate families) that provide full postpartum care including food, massage, and newborn care services — less common than in Singapore or Hong Kong but available.",
  },
  {
    name: "Bangkok Family Life — International Schools & Child Development",
    emoji: "🏫",
    area: "International schools in Bangkok: NIST International School (Sukhumvit Soi 15), Bangkok Patana School (Sukhumvit Soi 105), Shrewsbury International School (multiple campuses), British International School Bangkok, ISB (International School Bangkok, Nichada Thani), French-international schools (LFBKK), and German International School — concentrated in Sukhumvit and outer Bangkok",
    price: "International school annual tuition (primary): ฿300,000–700,000; International school annual tuition (secondary): ฿400,000–900,000; International school application fee: ฿5,000–20,000; Private nursery/playgroup: ฿20,000–80,000/month; After-school activity programs: ฿3,000–20,000/semester; Pediatric check-up (private hospital): ฿800–3,000",
    why: "Bangkok's international school system is one of Southeast Asia's most developed — the city hosts more international schools than most Southeast Asian capitals, serving the large diplomatic, business, and educational expatriate community. Key aspects of Bangkok's international family life: (1) International curriculum variety: Bangkok international schools offer IB (International Baccalaureate), British A-level, American AP, Australian, French, German, and Japanese national curricula — most major educational frameworks are represented; (2) School reputation hierarchy: Bangkok Patana, NIST, and ISB (International School Bangkok at Nichada Thani) are Bangkok's most academically prestigious and competitive international schools; Shrewsbury and British International School are strong British curriculum alternatives; (3) Waiting lists: all Bangkok's top international schools operate waiting lists, particularly for primary-age entry; planning 1–2 years ahead for school entry at competitive schools is normal; (4) Location affecting neighborhood choice: many Bangkok expat families choose residential neighborhoods based on proximity to their chosen international school; Nichada Thani (northern Bangkok) has a large expat compound community built around ISB; (5) Pediatric specialist network: Bangkok's private hospitals have pediatric specialists with international training covering all subspecialties; Samitivej's Pediatric Hospital (on Soi 49) is Bangkok's dedicated pediatric private hospital.",
    tip: "Bangkok international family planning: (1) School application timeline: for Bangkok's top international schools, beginning the application process 12–18 months before intended entry is necessary; schools like Bangkok Patana and NIST receive more applications than available places and maintain waiting lists; (2) English-medium vs. bilingual: Bangkok's international schools range from English-only instruction to bilingual Thai-English programs; for families intending long-term Bangkok residence, bilingual programs that develop Thai literacy alongside English instruction provide long-term social integration advantages; (3) After-school activity ecosystem: Bangkok's international school communities generate a rich after-school activity ecosystem; music schools, arts programs, sports academies, and tutoring centers near international school clusters serve the international family community; (4) Childhood vaccination records: Thailand follows a vaccination schedule that differs from some countries' home vaccination schedules; Thailand's private hospitals can administer missing vaccinations from home country schedules and maintain English-language vaccination records compatible with international school requirements; (5) Bangkok family areas: Sukhumvit Soi 31–71 corridor, Ekamai-Thonglor, and Nichada Thani (outer north Bangkok) are Bangkok's primary family expat residential clusters based on international school proximity and park/community infrastructure.",
  },
];

export function BangkokPregnancy() {
  return (
    <div className="rounded-2xl border border-pink-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-pink-700 mb-3">
        🤱 Bangkok maternity & family life — prenatal care, pregnancy wellness & international schools
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-pink-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-pink-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
