const SPOTS = [
  {
    name: "Cambodian (Khmer) Cuisine in Bangkok",
    emoji: "🇰🇭",
    area: "Cambodian food in Bangkok: small community restaurants in Samut Prakan (south Bangkok, near the Cambodian worker population areas), Klong Toey port area, and occasional Cambodian dishes incorporated into Thai-Cambodian fusion at border province cuisine specialists in Bangkok's diverse food landscape",
    price: "Cambodian community restaurant set meal: ฿100–250; Nom banh chok (Khmer noodles): ฿60–150; Beef lok lak (Cambodian steak): ฿180–400; Cambodian samlor soup: ฿100–250; Fish amok (Khmer curry): ฿180–400",
    why: "Cambodian cuisine in Bangkok exists primarily within the community restaurants serving Bangkok's substantial Cambodian migrant worker population — concentrated in industrial areas south of Bangkok (Samut Prakan) and in the Klong Toey port area. Cambodia's Khmer cuisine shares some DNA with Thai cuisine (both have roots in the Khmer Empire's culinary traditions, both use fish sauce, lemongrass, galangal, and kaffir lime) but has distinct preparations: (1) Nom banh chok — Cambodia's national breakfast; thin rice noodles with a light fish-based green curry sauce topped with fresh herbs and bean sprouts; (2) Lok lak — marinated beef (or other protein) stir-fried and served with rice, lettuce, tomato, and a lime-pepper dipping sauce; one of Cambodia's most popular dishes; (3) Fish amok — delicate steamed fish curry in a banana leaf cup; Cambodia's national dish; coconut milk-based with less pungent spicing than Thai red curry; (4) Samlor Korko (stirring soup) — mixed vegetables and protein in a fermented fish paste-seasoned broth; a distinctly Cambodian flavor profile; (5) Prahok — fermented fish paste that is the foundation of Cambodian flavor; stronger and more pungent than Thai shrimp paste (kapi); used in raw preparations as well as cooked dishes.",
    tip: "Finding Cambodian food in Bangkok: (1) Community restaurant access: Cambodian restaurants in Bangkok rarely appear on TripAdvisor or Google Maps with English reviews; locating them requires walking Samut Prakan or Klong Toey's residential streets and following the sound and smell of cooking; (2) Border connection: Bangkok food enthusiasts sometimes make day trips to Sa Kaeo, Kanchanaburi, or other Thai-Cambodia border provinces for authentic Cambodian market food accessible from Thailand; (3) Cambodian New Year (Khmer New Year, April 13–15): Bangkok's Cambodian community celebrates Khmer New Year with cultural gatherings that include traditional foods; connecting with the Cambodian Embassy in Bangkok's community events calendar provides access to these events; (4) Thai-Cambodian shared ingredients: both cuisines use many identical base ingredients; comparing Thai and Cambodian preparations of dishes using the same ingredients (fish sauce, galangal, lemongrass) highlights how different cooking traditions transform shared elements; (5) Cambodian beer and drinks: Angkor Beer (Cambodia's national beer) and Tiger Beer are both available at Bangkok's Cambodian community restaurants; Cambodian coconut wine (tuk daab) and palm sugar palm wine are seasonal specialties occasionally available at community gatherings.",
  },
  {
    name: "Laotian Food & Isaan Connection in Bangkok",
    emoji: "🇱🇦",
    area: "Laotian food in Bangkok: overlaps significantly with Isaan (northeastern Thai) cuisine; Isaan restaurants throughout Bangkok serve dishes with Lao cultural roots; dedicated Laotian community restaurants in Nonthaburi and north Bangkok areas; som tum shops (papaya salad culture) with Lao variations",
    price: "Isaan/Lao set meal (rice + several dishes): ฿80–200; Tam mak houng (Lao papaya salad, fishier style): ฿60–120; Lao grilled chicken (ping gai): ฿80–200; Khao niaw (sticky rice): ฿20–40; Lao sausage (sai oua): ฿150–350; Laap (meat salad): ฿150–350",
    why: "The culinary connection between Laotian food and northeastern Thai (Isaan) food is profound — both traditions evolved within the same Lao-speaking cultural sphere that pre-dates the current national borders; many dishes classified as 'Isaan Thai food' in Bangkok are culturally Laotian in origin. Bangkok's Isaan food scene is therefore the most accessible way to experience Laotian cuisine in Thailand. Key Laotian-origin dishes available throughout Bangkok's Isaan restaurants: (1) Laap (larb) — the signature Laotian dish; finely chopped or minced meat with lime juice, fish sauce, roasted rice powder, shallots, and extensive fresh herbs; served raw (laap dip) or cooked; (2) Som tum (tam mak houng in Lao) — shredded green papaya salad; the Lao version uses fermented fish (pla ra) more prominently than the Bangkok Thai version; (3) Ping gai — Lao/Isaan grilled chicken marinated in lemongrass, coriander root, and fish sauce; (4) Khao niaw — steamed glutinous (sticky) rice, the staple of Laotian and Isaan cooking; eaten by hand, rolled into small balls and dipped into dishes; (5) Moo pla (grilled fish) — grilled freshwater fish; in Thailand/Laos, freshwater fish species (tilapia, catfish) are the culturally primary fish rather than the saltwater fish of coastal Thai cooking.",
    tip: "Bangkok Laotian food exploration: (1) Isaan restaurants as Lao food: every Bangkok Isaan restaurant serves essentially Laotian food under a Thai geographical classification; there's no need to search specifically for 'Lao restaurants'; (2) Pla ra distinction: the flavor that most distinguishes authentic Lao-influenced som tum from its modified tourist version is pla ra (fermented fish) rather than fish sauce; asking for pla ra in your som tum produces the Laotian original; (3) Laap dip caution: raw meat laap (laap dip) is an authentic Lao/Isaan specialty but carries food safety risk from raw ingredients; it is a real dish eaten by locals rather than a provocation; understanding the risk versus the cultural experience before ordering; (4) Sticky rice technique: eating khao niaw (sticky rice) by hand is the appropriate technique — taking a small amount, forming a ball with the fingers, and using it to scoop curries or dip into sauces; this hand-eating tradition distinguishes Lao/Isaan eating culture from central Thai rice culture; (5) Lao ingredients at Chatuchak: Chatuchak Weekend Market's food section has vendors selling Lao-specific ingredients (certain fermented products, distinctive Lao herb bundles) not found at general Bangkok markets.",
  },
  {
    name: "ASEAN Food Diplomacy — Southeast Asian Embassies & Cultural Food",
    emoji: "🌏",
    area: "Embassy cultural events and national day food celebrations at ASEAN embassies in Bangkok's diplomatic district (Wireless Road, Sathorn): Indonesian, Malaysian, Philippine, Vietnamese, Myanmar, Cambodian, Laotian, Brunei, and Singapore embassies all maintain Bangkok presence with periodic food cultural events",
    price: "Embassy National Day cultural events: typically free (RSVP required); Embassy-connected cultural restaurant sponsorship events: ฿500–3,000/person; ASEAN food festival (periodic): ฿300–800 entry; Cultural center food demonstrations: typically free",
    why: "Bangkok's position as host city for ASEAN diplomatic missions (all 10 ASEAN member state embassies maintain Bangkok presence) creates periodic access to authentic national food cultures through embassy cultural programming. Bangkok's ASEAN embassies regularly: (1) Host National Day receptions that include signature national dishes for diplomatic guests (and often the public through cultural programs); (2) Partner with Bangkok cultural centers (Indonesian Cultural Center, Malaysian Tourism Promotion Board, Philippine Embassy Cultural Section, etc.) on food demonstration events; (3) Organize annual food festivals that present their national cuisine to the Bangkok public; (4) Maintain relationships with Thai restaurants serving their national cuisine that they can recommend to visitors from their countries. The Indonesian Cultural Center (Sathorn area) is particularly active with Indonesian food events; the Malaysian Embassy and Tourism Malaysia Bangkok office run Malaysian food promotions; and the Philippine Embassy periodically hosts Filipino cuisine presentations.",
    tip: "Bangkok ASEAN food diplomacy access: (1) Embassy event lists: most ASEAN embassies maintain Facebook and website pages that announce public cultural events including food-related programming; following these accounts provides advance notice; (2) National day RSVPs: some embassy national day events accept public RSVPs through their cultural offices; expressing genuine interest in experiencing the national cuisine typically receives a positive response; (3) ASEAN Summit cultural programming: when Bangkok hosts ASEAN-related meetings (Thailand holds ASEAN chair periodically), the city hosts elevated cultural programming that includes public food events; (4) Cultural center language events: ASEAN cultural centers in Bangkok (Indonesian Cultural Center, Malaysian Cultural Center equivalent) often combine language learning events with food preparation demonstrations — accessing the language program provides the food dimension as well; (5) Diplomatic community awareness: Bangkok's diplomatic community sometimes creates informal recommendations for where to eat specific national cuisines — embassy staff knowing good Malaysian hawker food, Vietnamese staff recommending their community restaurants — accessing these recommendations through cultural center staff provides insider knowledge.",
  },
];

export function BangkokCambodianFood() {
  return (
    <div className="rounded-2xl border border-yellow-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-yellow-700 mb-3">
        🌏 Bangkok Southeast Asian cuisine — Cambodian, Laotian-Isaan & ASEAN food culture
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-yellow-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-yellow-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
