const SPOTS = [
  {
    name: "Bangkok Cat Cafés & Animal Cafés — Cats, Dogs, Rabbits & More",
    emoji: "🐱",
    area: "Bangkok cat cafés: Cats & Cups Café (Siam area, long-established); Cat Lover Café (multiple locations); Neko no Niwa (Ekkamai area, Japanese-influenced cat café); Purr (cat café and wine bar, Phrom Phong area); Cat colony cafés: many Bangkok cafés have adopted 'house cats' that freely roam; Dog cafés: Barkyard (various Bangkok locations, dog café concept); Rabbit cafés: Bunnies and Biscuits style concept; Capybara experiences (newer addition to Bangkok's animal café scene); Chinchilla cafés; Reptile cafés (gecko, bearded dragon experiences in certain Bangkok entertainment areas); Owl cafés: occasional pop-up events and permanent locations near Bangkok entertainment districts",
    price: "Bangkok cat café entry: typically ฿150–300 for 1–2 hours (includes drink); some cat cafés charge ฿100–150 entry + beverage minimum (฿80–150); dog café entry: ฿200–300 for 1–2 hours; animal café booking: walk-in usually possible but booking via Instagram/Line for weekend popular cafés avoids wait; food and drinks at animal cafés: typically priced at standard Bangkok café rates (฿80–180 per item); cat-themed merchandise: animal cafés often have branded merchandise at ฿100–500",
    why: "Bangkok's animal café scene is extensive and reflects Thai pet culture, urban loneliness economics, and the kawaii influence from Japanese and Korean pop culture: (1) Thai pet culture context: Thailand has a significant pet ownership culture; cats and dogs are widely kept in Bangkok condos (small dogs in particular, which building rules typically accommodate); pet cafés serve both people who genuinely love animals and urban residents who cannot keep pets in their accommodation; (2) Bangkok's stray animal challenge: Bangkok has a large stray dog and cat population (estimated hundreds of thousands city-wide); the Bangkok Metropolitan Administration and temple communities maintain stray feeding programs; some cat cafés rescue and rehabilitate stray cats as part of their model; the contrast between the curated cat café environment and Bangkok's street stray population is significant; (3) Animal welfare considerations: Bangkok's animal café quality varies; well-managed cafés have appropriate space, veterinary care, and visitor interaction limits; overcrowded cafés with excessive visitor stress on animals are a welfare concern; visitor signals of good cafés: animals can retreat to 'no-visitor' areas, animals appear healthy and not fearful, visitor numbers are limited; (4) The capybara and exotic pet trend: Bangkok has seen animal café concepts expand to more exotic animals (capybaras, meerkats, slow lorises in unethical venues — slow loris is an endangered protected species and any venue keeping them for tourist interaction is operating illegally); ethical cafés use rabbits, cats, dogs, guinea pigs; (5) Instagram and animal café social media: Bangkok's animal cafés are heavily Instagram/TikTok driven; the most photogenic cafés (well-lit, aesthetically designed with animal interaction opportunities) generate significant social media content; visitor demographics tend toward younger Thai and Japanese/Korean tourists; photography of animals in cafés is universally permitted.",
    tip: "Bangkok animal café visit guidance: (1) Timing and crowds: Bangkok animal cafés peak Saturday and Sunday afternoons (2–6pm); visiting on weekday mornings (10am–noon) provides smaller crowds and less stressed animals; animals are generally more active and interactive during less crowded periods; (2) Allergy considerations: cat cafés create significant allergen environments (cat dander, fur) — visitors with cat allergies should not visit even briefly; some cat cafés have HEPA air filtration but the concentration of cats means allergen levels are still high; (3) Cleanliness and hand hygiene: Bangkok cat cafés vary in hygiene management; wash hands before eating or touching eyes after animal contact; animal-transmitted diseases in Bangkok cat cafés are rare but possible; reputable cafés have hand sanitizer stations throughout; (4) Child-friendly cat cafés: most Bangkok cat cafés welcome older children (6+) but have age restrictions for very young children due to both child safety (cats may scratch) and cat welfare (small children may distress cats); verify age policy before visiting with young children; (5) Supporting ethical Bangkok animal organizations: visitors who want to support Bangkok's street animal welfare beyond cafe visits can donate to Soi Dog Foundation (Thailand's largest animal welfare NGO, English-language website, accepts international donations) which works on stray population management, rescue, and international adoption programs.",
  },
  {
    name: "Bangkok Pet Market & Pet Services — Chatuchak Pets & Finding Animal Care",
    emoji: "🐶",
    area: "Bangkok pet market: Chatuchak Weekend Market has a dedicated pet section (open Saturday and Sunday) selling birds, fish, reptiles, hamsters, rabbits, dogs, and cats — the largest concentrated pet market in Bangkok; JJ Mall weekday pet section (adjacent to Chatuchak); Jatujak pet market weekday: reduced but still open; Rama 9 Pet Market (outer Bangkok, extensive); aquarium supplies: Chatuchak fish section has the largest concentration of ornamental fish and aquarium supply shops in Bangkok; Bird World (Bang Khae, western Bangkok, specialized bird market); Bangkok pet veterinary: Soi Dog friendly vets throughout Bangkok; international-standard pet hospitals (AnimaCare, Bangkok Animal Hospital); expat pet services: Bangkok Pet Hotel, multiple pet boarding services; pet import/export: Thailand has specific quarantine requirements for imported pets",
    price: "Chatuchak pet market entry: free; pet pricing in Chatuchak varies enormously by species and breed; ornamental fish (tropical, freshwater): ฿20–5,000+ depending on species; hamsters, guinea pigs: ฿200–500; dogs (pedigree, popular breeds): ฿5,000–50,000+; veterinary consultation Bangkok: ฿300–800 at local vets; ฿1,000–3,000 at international-standard animal hospitals; pet boarding per night Bangkok: ฿300–800 depending on facility quality; pet passport/international health certificate: ฿2,000–5,000 (includes vet examination, paperwork)",
    why: "Bangkok's pet market and pet services ecosystem is significant both culturally and practically: (1) Chatuchak pet section's character: Chatuchak Weekend Market's animal section (operating Saturday and Sunday mornings) is one of the largest live animal markets in Southeast Asia; the section sells legal pet species as well as sometimes-questionable vendors on the periphery; the legal sections primarily sell ornamental fish (Thailand has a significant ornamental fish export industry), birds (budgerigars, cockatiels, exotic finches), hamsters, reptiles (geckos, tortoises, ball pythons), and dogs and cats; (2) Animal welfare concerns at Chatuchak: conditions for animals at Chatuchak's pet market vary significantly by vendor; the tropical heat, crowding, and noise levels create stress for many animals; purchasing animals from Chatuchak requires considering whether the animal can safely travel to the buyer's home/country (many cannot legally be exported without CITES permits or cannot tolerate the journey); observing without purchasing is appropriate for most visitor interactions; (3) Bangkok expat pet ownership: Bangkok's large expat community has created significant demand for pet services — premium veterinary care (AnimaCare, Bangkok Animal Hospital offer international-standard diagnostic and surgical facilities), pet boarding, grooming, and pet-friendly accommodation; (4) Pet import requirements for Thailand: visitors who want to bring pets to Bangkok for longer stays (or Bangkok-based expats importing pets) face strict Thai import requirements — rabies vaccination (current), import permit from the Thai Department of Livestock Development, CITES permits for certain species; quarantine at the point of entry may apply; (5) Thailand's ornamental fish export industry: Thailand is one of the world's largest exporters of ornamental (aquarium) fish; the Chatuchak fish section and nearby dedicated fish markets supply both domestic and export markets; rare and hybrid freshwater fish are a genuinely specialist Bangkok shopping opportunity for aquarium enthusiasts.",
    tip: "Bangkok pet market visitor guidance: (1) Wildlife trafficking at Chatuchak: Bangkok's markets (including Chatuchak) have historically been associated with illegal wildlife trade (CITES-protected species, exotic birds, primates); this trade has been significantly reduced by enforcement, but vigilance remains appropriate; never purchase animals that appear to be wild-caught (birds showing stress, animals with unclear origin documentation, any primate or protected species); (2) Rabies risk in Bangkok: Thailand has endemic rabies; stray dogs and cats in Bangkok are potential rabies vectors; animal bites or scratches from Bangkok strays or unknown-vaccination-status pets require immediate medical evaluation and rabies post-exposure prophylaxis (PEP) at Bangkok hospitals; Bumrungrad and Bangkok Hospital both provide rabies vaccination and PEP; (3) Expat pet relocation services: Bangkok-based pet relocation specialists (PetAir Thailand, Bangkok-based agents) manage complex international pet import/export logistics including quarantine management, health certificates, CITES permits, and flight coordination; these services are essential for pet imports from countries with complex health requirements (Australia, New Zealand, UK, Japan all have strict import requirements into Thailand); (4) Fish transport for aquarium purchases: Bangkok's ornamental fish vendors have well-developed oxygen-bag transport packaging for purchased fish; for domestic Bangkok transport, standard fish bag transport is fine; international transport of live fish requires airline cargo arrangements and species CITES documentation where applicable; (5) Volunteer at Bangkok animal shelters: Bangkok has several legitimate animal rescue organizations (Soi Dog Foundation, SCAD — Save Cats And Dogs, Bangkok Dog Shelter) that accept short-term volunteers; volunteering provides genuine interaction with Bangkok animals and directly supports animal welfare; Soi Dog Foundation's Phuket center is better organized for volunteers than Bangkok locations.",
  },
  {
    name: "Bangkok Stray Animals — Temple Dogs, Street Cats & How to Help",
    emoji: "🐕",
    area: "Bangkok stray population centers: almost every Bangkok neighborhood has a community of stray dogs and cats (referred to locally as 'soi dogs' and 'soi cats'); temple compounds throughout Bangkok (Wat Arun, Wat Pho, Wat Saket, and virtually all Bangkok temples) maintain large populations of sterilized, temple-fed dogs and cats as a form of Buddhist merit-making; local communities and restaurants feed neighborhood strays as a cultural practice; Bang Kachao (Bangkok's green lung) has significant cat populations; Buddhist monks feed strays at dawn alongside alms-giving ceremonies; Soi Dog Foundation and local rescue groups operate across Bangkok",
    price: "Supporting Bangkok stray animals: food cost at 7-Eleven or market for street feeding is ฿30–100 (suitable wet cat/dog food); Soi Dog Foundation donation (international credit card accepted, soidog.org): any amount; local Bangkok cat rescue organizations accept food and supply donations; trap-neuter-return (TNR) support through local organizations; animal first aid supplies for visible injured strays: contact local rescue groups rather than attempting personal treatment; Bangkok temple donations for stray feeding programs: donation boxes available at temple entrances",
    why: "Bangkok's stray animal population is a significant cultural and ethical landscape that visitors engage with throughout the city: (1) Buddhist cultural context of stray feeding: in Thai Buddhist culture, feeding stray animals is considered merit-making (tam bun) — an act that generates positive karma; this cultural framework makes Bangkok's stray animal situation different from purely welfare-failure narratives; Bangkok's streets are full of people voluntarily feeding neighborhood strays as a daily merit practice; the animal welfare challenge coexists with a culture of active animal caring; (2) Bangkok's TNR programs: trap-neuter-return programs (where strays are caught, sterilized, vaccinated, ear-tipped, and returned to their territory) are the internationally recommended approach for stray population management; Bangkok's major animal welfare organizations (Soi Dog Foundation, local rescue groups) operate TNR programs in Bangkok neighborhoods; the programs have reduced population growth in areas with consistent implementation; (3) Temple dog culture: Bangkok's Buddhist temple communities maintain stray dogs as temple residents — providing feeding and veterinary care (vaccination at minimum); temple dogs generally have recognizable territories, social hierarchies, and regular feeding schedules; they are typically more socialized than street-only strays; (4) Rabies vaccination programs in Bangkok strays: Bangkok's Department of Livestock Development operates rabies vaccination campaigns in Bangkok neighborhoods targeting stray populations; the campaigns have reduced but not eliminated rabies risk; visible 'ear tip' (tip of one ear removed) on a stray cat indicates it has been through a TNR program and usually includes rabies vaccination; (5) Responsible visitor interaction with Bangkok strays: visitors who want to interact with Bangkok strays should follow these principles — observe body language before approaching; do not attempt to pet or handle strays that are distressed, showing teeth, or acting defensively; carry antiseptic (available at 7-Eleven) for any scratch or bite; any bite or deep scratch from a Bangkok stray warrants immediate medical evaluation.",
    tip: "Bangkok stray animal visitor guidance: (1) Best stray dog interaction areas: Bangkok's better-managed stray populations (more socialized, vaccinated through community programs) are typically in temple compounds, university campuses (Chulalongkorn and Kasetsart universities maintain campus cat populations), and established residential neighborhoods; stray dogs near food markets and trash areas may be less socialized and less predictably behaved; (2) Supporting local rescue organizations: Bangkok has many small, community-operated animal rescue organizations run by volunteers; finding local rescue groups through Facebook groups (Bangkok Stray Dogs, Bangkok Cat Rescue, Soi Dog Support Bangkok) connects visitors to legitimate local organizations with clear donation needs; (3) Injured stray assistance: encountering an injured stray in Bangkok — Bangkok Emergency Veterinary Clinic (24-hour, for domestic animals with confirmed ownership); for strays, the most effective action is contacting local rescue networks via Line or Facebook (faster than calling) with the location and condition of the injured animal; Bangkok Animal Aid (bangkokAnimalAid.org) helps coordinate injured stray responses; (4) Cat colony caretakers: Bangkok's residential sois and neighborhoods have informal 'cat colony caretakers' — residents who regularly feed, monitor health, and coordinate care for neighborhood strays; these individuals often have deep knowledge of neighborhood animal situations and can be identified by their regular presence with animal food at predictable hours; (5) Bringing food from home: visitors who want to feed Bangkok strays should use cat or dog-appropriate food (dry kibble or canned wet food) available at 7-Eleven rather than human food; human food (particularly spicy, salty, or oily street food) is inappropriate for animal feeding; fresh water is often more valuable than food in Bangkok's heat.",
  },
];

export function BangkokPets() {
  return (
    <div className="rounded-2xl border border-yellow-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-yellow-700 mb-3">
        🐱 Bangkok animals — cat cafés, pet markets & the city's stray animal culture
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-yellow-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-yellow-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-yellow-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
