const SPOTS = [
  {
    name: "Bangkok Nail Salons — Gel Extensions, Thai Nail Art Trends & Pricing",
    emoji: "💅",
    area: "Bangkok nail salon concentration areas: Siam Square and Siam Paragon (premium nail bars); Sukhumvit Soi 11 and Thong Lo (expat-oriented nail salons); On Nut and Phra Khanong (local Thai-priced nail salons excellent quality); Chatuchak Weekend Market (nail stalls during weekend market hours); MBK Shopping Centre (multiple nail service providers on upper floors); Emquartier and Emporium (mall-based nail salons, premium pricing); neighborhood nail salons: every Bangkok soi has multiple local nail service shops — the highest concentration of low-price, high-quality options; Japanese-style nail salons (eyelash+nail combo): several concentrated in Ekkamai and Thong Lo",
    price: "Bangkok nail pricing guide: basic manicure (regular polish): ฿100–200 at local salons; gel manicure: ฿300–500 local salons; ฿600–1,200 at premium nail bars; full set acrylic/gel extensions: ฿500–1,000 local; ฿1,200–2,500 premium; nail art (per nail, intricate): ฿50–200 per nail depending on complexity; pedicure (basic): ฿150–300; pedicure with gel: ฿400–700; Japanese nail art (complex 3D, rhinestone): ฿2,000–5,000+ for full set at specialist salons; comparison to similar Western services: Bangkok nail prices are approximately 30–70% below Western equivalents for equivalent quality work",
    why: "Bangkok's nail salon culture is sophisticated and internationally competitive: (1) Thai nail artistry standards: Thai nail technicians trained in nail art have achieved internationally recognized skill levels; intricate nail art (3D acrylic designs, rhinestone patterns, hand-painted miniature designs) was pioneered significantly in East Asia (Japan, Korea) but has deep expertise in Thai nail salons; Bangkok's premium nail bars serve both Thai and international clients who specifically seek Thai nail artists for complex work; (2) Japanese-Thai nail salon fusion: Bangkok's nail market has been significantly influenced by Japanese nail culture (gyaru nail art style, gel-heavy extensions, elaborate decoration); several Bangkok nail salons have Japanese-trained or Japanese-origin technicians; the Thong Lo and Ekkamai areas (with large Japanese expat populations) have the highest concentration of Japanese-style nail salons; (3) Nail salon as social institution: Bangkok's nail salons serve a social function beyond aesthetic services; neighborhood nail salons are social gathering spaces where regular clients come for conversation and relationship alongside the service; the atmosphere in mid-range Bangkok nail salons is warm and conversational; (4) Bangkok beauty industry's nail economic role: Bangkok's nail industry employs a significant workforce; local salon operators (often family-run) provide neighborhood beauty services at prices that compete with major chains; the sector has not been as dominated by chain standardization as in some Western markets; (5) Nail product market: Bangkok's beauty supply market has extensive professional nail products; Pantip Plaza (IT mall, but also has beauty supply floors) and dedicated beauty supply shops near Pratunam carry professional gel systems (OPI, ORLY, Gelish, Korean brands) at competitive prices; visitors who do their own nails can source Thai-market brands (not available internationally) and Korean nail brands cheaply.",
    tip: "Bangkok nail salon practical guide: (1) Language and nail art communication: international nail clients should bring reference photos (Pinterest, Instagram screenshots saved offline) to Bangkok nail salons; communicating specific nail art requests through images prevents misunderstanding; most Bangkok nail technicians understand visual references even without shared language; (2) Sanitation standards: Bangkok's nail salons range widely in sanitation practice; premium nail bars sterilize tools in autoclaves; budget salons may use alcohol wipe sanitation; for medical nail conditions (fungal infection, nail injuries), seeing a dermatologist at a Bangkok hospital rather than a nail salon is appropriate; (3) Appointment vs. walk-in: Bangkok's neighborhood nail salons almost universally accept walk-in clients; premium nail bars (particularly those with Japanese-trained technicians or elaborate nail art services) benefit from advance booking via Line or Instagram messaging; (4) Nail removal in Bangkok: if arriving with gel extensions from home country, Bangkok nail salons will remove them cleanly before applying new service; removal is typically ฿100–300 as a standalone service; communicate 'take off' or 'remove' with the gesture of pointing to existing nails; (5) Tipping practice at nail salons: Bangkok nail salon tipping is appreciated but not mandatory; ฿50–100 is a common tip for a standard service; for complex nail art work (2+ hours), ฿100–200 is appropriate appreciation; at higher-end nail bars with bill-included service charges, additional tipping remains an individual choice.",
  },
  {
    name: "Bangkok Eyebrow & Eyelash Services — Threading, Microblading & Extensions",
    emoji: "👁️",
    area: "Bangkok eyebrow threading: ubiquitous in Bangkok malls (Siam Paragon, CentralWorld, Emquartier threading booths); Indian-run threading services (Pahurat area, Bang Rak Indian community — most authentic for threading); Thai-run threading studios (mall-based); Bangkok microblading: specialized brow studios in Thong Lo, Ekkamai, Asoke; Korean brow studios in Ekkamai area (Korean expat-adjacent); Eyelash extensions: Japanese-style lash salons (Thong Lo, Ekkamai, Phrom Phong — Japanese community areas); Thai lash salons (all Bangkok districts at various price points); individual vs. classic vs. volume vs. mega-volume lash styles all available; combined lash + brow services: most brow studios offer combined bookings",
    price: "Bangkok eyebrow threading: ฿80–150 (full brows, 10–15 minutes); threading stall vs. studio pricing similar; eyebrow tinting: ฿200–400 added to threading; microblading (semi-permanent eyebrow tattooing): ฿3,000–8,000 for initial session at Bangkok studios; top-up at 1–2 months: ฿1,500–3,000; Japanese-brand eyelash extensions (silk/mink): ฿800–1,500 for full set at mid-range salons; ฿2,000–4,000 at premium Japanese salons; classic vs. volume vs. mega-volume lash pricing: volume adds ฿300–600 premium; touch-up refills: ฿400–800 (within 3 weeks of initial set); comparison: lash extension pricing in Bangkok is approximately 40–60% below equivalent quality in the US/UK",
    why: "Bangkok's threading, lash, and microblading services have developed to internationally competitive standards due to the large East/Southeast Asian beauty market: (1) Threading tradition: eyebrow threading (using a twisted cotton thread to pull facial hair at the root) is an Indian/Middle Eastern beauty technique that has become Thailand's dominant brow removal method in mall environments; the technique removes hair more precisely than waxing and requires no consumable products beyond thread; Bangkok's mall-based threading stations (common at major shopping centres) provide the service with efficient turnover; (2) Microblading Thai specialization: Thailand's beauty industry has developed significant microblading expertise due to the East Asian beauty market (Chinese, Korean, Japanese tourists and residents seeking brow enhancement); Bangkok microblading studios with Korean-trained or Japan-certified technicians have reputation for natural hair-stroke results; (3) Japanese lash culture in Bangkok: Japan's eyelash extension industry is globally considered the premium standard; Bangkok's Japanese expat community (approximately 80,000+ residents across Ekkamai, Thong Lo, Phrom Phong) created demand for Japanese-standard lash services in Bangkok; today, Bangkok's Japanese-owned and Japanese-certified lash salons serve both expat Japanese and Thai clients who prefer the Japanese approach (lighter, more natural-looking extensions rather than the heavier look common in some Thai lash styles); (4) Thai brow sculpting preferences: Thai beauty standards emphasize defined, straight (non-arched) brows rather than the high-arched brow common in Western beauty; Bangkok brow studios optimized for Thai/Korean/Japanese aesthetics will default to straighter brow shapes; international visitors should specify preferred brow shape clearly (arched, straight, ombre powder, etc.) before commencing service; (5) Semi-permanent makeup permanence in Bangkok climate: Bangkok's heat and humidity affect the longevity of semi-permanent makeup (microblading, powder brows, ombre brows); pigment fades more quickly in hot/humid climates than in cold/dry climates; Bangkok studios with experience in tropical climate semi-permanent makeup adjust pigment and technique accordingly; clarifying climate-adjusted longevity expectations (typically 1–2 years in Bangkok's climate) before committing is useful.",
    tip: "Bangkok brow and lash service guide: (1) Patch test for lash extension adhesive: Bangkok lash salon adhesives (cyanoacrylate base) can cause allergic reactions in susceptible individuals; requesting a patch test (small adhesive application behind ear or on inner wrist) 24 hours before full extension set prevents rare but serious reactions; reputable Bangkok lash salons perform patch tests as standard practice; (2) Lash extension aftercare in Bangkok humidity: lash extension aftercare in Bangkok requires adapting to the humidity — oil-based cleansers break down lash adhesive faster; using oil-free cleansers for face washing, avoiding steam rooms and saunas for 48 hours post-application, and avoiding direct air conditioning airflow on lashes for 24 hours extends wear; (3) Microblading healing in Bangkok: the healing process for microblading (approximately 7–14 days of peeling and color change) is affected by Bangkok's humidity; keeping the treated area dry during healing (avoiding pool, sweat-heavy exercise, steam) is more challenging in Bangkok's heat; scheduling microblading at the beginning of a stay (not just before departure) allows healing completion in Bangkok before return travel; (4) Lash studio LINE booking: Bangkok's Japanese-run lash studios primarily use LINE messenger for appointment booking; having LINE installed and a Thai/Japanese-compatible number or LINE ID for booking is essential; most studios do not have English-language phone booking but can communicate through LINE's translation features; (5) Combined treatments booking: Bangkok beauty studios frequently offer combined packages (lash + brow + facial treatments) with package pricing 15–25% below individual service pricing; if planning multiple beauty services during a Bangkok stay, discussing package pricing at a single studio reduces total cost.",
  },
  {
    name: "Bangkok's K-Beauty & Korean Skincare Market — Shops, Clinics & Thai-Korean Skin Trends",
    emoji: "🌸",
    area: "Bangkok K-beauty shops: The Face Shop (multiple mall locations); Innisfree Thailand (Siam, Central, Emquartier); Etude House Bangkok; Korean beauty multi-brand stores at Siam Paragon basement, Emporium, The Mall; Korean cosmetics street: Siam Square area has multiple Korean beauty importers; Platinum Fashion Mall (Pratunam) has Korean beauty product traders at lower prices; Bangkok Korean beauty clinics: concentrated in Ekkamai, Thong Lo, Asoke (Korean clinic networks expanding Bangkok branch presence); Gangnam-style Bangkok clinics: Thai clinics adopting Korean techniques (mesotherapy, laser toning, carbon laser peel, 'glass skin' protocols)",
    price: "Bangkok K-beauty product pricing: Innisfree, The Face Shop, Etude retail prices: 10–20% above Korean domestic pricing due to Thailand import markup; Korean beauty products via Shopee/Lazada Thailand (grey import): often 20–40% below official retail; Korean medical skincare (Medicube, SKIN1004, Anua): available at official stores and online at varying prices; Korean skincare clinic visit Bangkok: mesotherapy (skin booster injection): ฿1,500–3,000; carbon laser facial: ฿1,200–2,500; PDRN salmon DNA skin booster (popular Korean treatment): ฿3,000–6,000; full Korean skin treatment program (multiple sessions): ฿15,000–50,000",
    why: "The Korean Wave (Hallyu) has profoundly influenced Bangkok's beauty industry, creating both product availability and service adoption: (1) Thai-Korean beauty culture integration: Thai beauty culture and K-beauty have deeply integrated; Thai women (and increasingly men) have adopted Korean 10-step skincare routines, Korean makeup techniques, and Korean aesthetic ideals (glass skin, clear skin, dewy finish) as primary beauty goals; Bangkok's cosmetic market now treats K-beauty as domestic (not foreign) beauty culture; (2) Korean beauty clinic expansion to Bangkok: Korean aesthetic medicine clinics (known for HIFU, RF microneedling, Korean mesotherapy protocols, and injectable skin boosters) have established Bangkok branches targeting both Thai domestic patients and international medical tourists; the Korean clinic brand brings reputation advantage with Thai consumers who equate Korean beauty technology with cutting-edge effectiveness; (3) Bangkok's Thai-Korean skincare innovation: Bangkok's local skincare brands have incorporated K-beauty formulation principles; Karmart (Thai brand, Cathy Doll), and multiple Thai skincare brands now position themselves within Korean-aesthetic frameworks; the boundary between 'K-beauty' and 'Thai beauty influenced by Korea' has become blurred in Bangkok's market; (4) Glass skin and Bangkok environment: the 'glass skin' aesthetic goal (clear, luminous, reflective skin with minimal visible pores) that Korean beauty promotes is particularly challenging to maintain in Bangkok's heat and humidity; Bangkok's Korean clinic clientele often seek combined treatment protocols (laser toning for even skin tone + booster injections for hydration + physical SPF for UV protection) to approximate glass skin in tropical conditions; (5) Vitamin C and whitening in Bangkok: skin whitening products (containing vitamin C, niacinamide, arbutin, kojic acid, and other melanin-inhibiting ingredients) dominate Bangkok's skincare market; whitening is deeply embedded in Thai and broader Southeast Asian beauty standards; the K-beauty market capitalizes on this existing preference by positioning Korean brightening products as the premium approach.",
    tip: "Bangkok K-beauty and skincare market guide: (1) Shopee/Lazada vs. official retail for K-beauty: Bangkok's online marketplaces (Shopee Thailand, Lazada Thailand) sell Korean beauty products at prices significantly below official retail — often grey import directly from Korean wholesalers; risk: counterfeit products (particularly for high-value items like La Mer, Sulwhasoo); safety verification: check seller ratings, request batch code, buy from verified resellers rather than lowest-price listings; (2) Korean clinic due diligence: Bangkok's Korean-branded clinics vary significantly in actual Korean staff presence, equipment quality, and treatment protocol authenticity; verifying whether doctors performing medical treatments have Thai Medical Council registration (required for medical procedures) and whether Korean staff have appropriate permits for clinical work in Thailand is important for medical procedure safety; (3) Sun protection priority in Bangkok: dermatologists in Bangkok universally identify UV protection as the single highest-impact skincare step in tropical Bangkok; SPF 50+ daily sunscreen (physical/mineral is preferred in humid Bangkok as less likely to pill under makeup) is the foundation of Bangkok skincare regardless of other treatments; (4) Hydration layering in Bangkok air conditioning: Bangkok's combined outdoor humidity and intense indoor air conditioning (which desiccates skin) requires layered hydration; Korean skincare's essence-serum-moisturizer layering approach is functionally appropriate for Bangkok's alternating humid/AC indoor-outdoor lifestyle; (5) K-beauty product selection for Bangkok climate: Bangkok's climate favors K-beauty's gel-texture and water-based formulations over heavy oil-based moisturizers; specifically: gel toners, essence-first layering, gel SPF moisturizers, and lightweight serums outperform heavier European-style cream moisturizers in Bangkok's humidity.",
  },
];

export function BangkokNailSalon() {
  return (
    <div className="rounded-2xl border border-rose-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-rose-700 mb-3">
        💅 Bangkok beauty services — nail salons, lash extensions & K-beauty skincare
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-rose-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-rose-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-rose-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
