const SPOTS = [
  {
    name: "National Science Museum Bangkok — NSM Pathumthani & Bangkok Science Learning Centers",
    emoji: "🔬",
    area: "National Science Museum (NSM): Pathumthani Province (30km north of Bangkok), accessible by taxi from Don Mueang Airport area (40 min) or from Bangkok Northern Bus Terminal (Chatuchak, Mo Chit BTS — bus/minivan to Khlong Luang, then Grab/taxi to NSM); NSM complex comprises: National Science Museum, Natural History Museum, and Information Technology Museum (three separate buildings); Address: 39/40 Moo 3, Technopolis, Khlong 5, Khlong Luang, Pathum Thani 12120; Discovery Museum (within Bangkok): Siam Discovery (Siam BTS) — consumer experience museum with interactive technology exhibits aimed at young adults; Science and Technology Center at KMITL (King Mongkut's Institute of Technology Ladkrabang): occasional public exhibitions; Planetarium (Bangkok): Chulalongkorn University has a public observatory and planetarium (Siam area adjacent); Assumption University (Huamark) also has planetarium access during school year",
    price: "NSM Pathumthani admission: adults ฿100, children ฿50 (prices may have changed — confirm at nsm.or.th); NSM complex all-three-museum combo ticket available at discount; Siam Discovery experiential floor: Siam Discovery (Siam BTS) entry is free to browse, specific interactive areas may have charges; TCDC (Thailand Creative and Design Center): annual membership ฿300 for full library access, or ฿100 day pass, Charoenkrung area (TCDC relocated to Post Building, Charoenkrung Road 1160); NSM special temporary exhibitions: additional charge (฿50–150 typically); Natural History Museum at NSM: included in NSM complex ticket",
    why: "Bangkok's science and knowledge infrastructure serves as both educational resource for Thai students and cultural insight for visitors into Thailand's scientific and technological development trajectory: (1) Thailand's science education landscape: Thailand has invested substantially in science education infrastructure during the last two decades; the NSM (National Science Museum) was established by Royal Initiative to promote science understanding; the NSM complex in Pathumthani houses three museums covering natural sciences, natural history (fossils, specimens, ecological systems), and information technology history; (2) Thailand's technology development context: Thailand has moved from primarily agricultural economy toward manufacturing and increasingly technology sectors; Bangkok is developing its Eastern Economic Corridor (EEC, special economic zone connecting Bangkok with Chonburi, Rayong) to attract high-technology industries; Thai government STEM education investment reflects this economic development goal; visiting NSM provides context for understanding Thailand's aspirations in science and technology sectors; (3) Natural History Museum at NSM: the Natural History Museum at the NSM complex houses specimens covering Thailand's extraordinary biodiversity — the country has approximately 10,000+ plant species, 1,000+ bird species, 300+ mammal species, and significant marine biodiversity; the museum contextualizes Thailand's biodiversity within paleontological history (Thailand has significant fossil sites, particularly in Khorat Plateau); (4) TCDC (Thailand Creative and Design Center): TCDC relocated to the renovated General Post Office Building (Charoenkrung Road) in 2017 — TCDC is a design library, exhibition space, and creative community hub; the building itself (1940s colonial-style government building, beautifully restored) is worth visiting; TCDC's material library (3,000+ material samples) is unique in Southeast Asia and serves Thailand's design and manufacturing industry; design exhibitions at TCDC regularly feature Thai design innovation; (5) Digital technology culture in Bangkok: Bangkok has extremely high smartphone penetration, extensive co-working infrastructure, and a growing startup scene; the government's Thailand 4.0 economic model specifically promotes AI, robotics, and digital technology sectors; Kasetsart University (Bangkok campus) and various technical universities are active in applied science research; Thailand's automotive manufacturing base (Thailand is a major vehicle production country) includes EV transition investment.",
    tip: "NSM visit planning: (1) NSM is most interesting for visitors who are either interested in natural history specimens (the Natural History Museum has extensive collections) or who are visiting with children (interactive exhibits in the Science Museum); as a tourist destination it requires specific interest in science to justify the trip distance from Bangkok; (2) Bangkok-based alternatives for science/tech curiosity: TCDC (Thailand Creative and Design Center, Charoenkrung Post Building, accessible by Grab from Saphan Taksin BTS) provides design-oriented intellectual engagement within Bangkok proper; Siam Discovery (BTS Siam) has good interactive exhibits oriented toward technology and design, particularly on its upper floors; (3) Royal Project orchid and agricultural exhibitions: the Royal Agricultural Station near Don Mueang airport occasionally holds plant and agricultural exhibitions relevant to Thailand's crop science programs — check during October–February season; (4) Science museum combined with Don Mueang Airport: NSM's proximity to Don Mueang Airport (DMK) makes it a logical stop when transiting through DMK; the airport is approximately 40 minutes from NSM; (5) Children-focused science options within Bangkok: Children's Discovery Museum (Chatuchak Park, Mo Chit MRT/BTS, children-focused interactive museum) is Bangkok's most accessible family science experience within the BTS/MRT network.",
  },
  {
    name: "Bangkok's Libraries & Academic Institutions — Intellectual Infrastructure of the City",
    emoji: "📚",
    area: "Major Bangkok libraries accessible to visitors: National Library of Thailand (Samsen Road, near Banglamphu/Khao San area, closed for renovation as of 2024 — check current status); Chulalongkorn University Library (BTS Siam/National Stadium, visitors may access common areas and campus); Thammasat University Library (Tha Phra Chan area, near Grand Palace, visitors may access common areas); TCDC Library (Thailand Creative and Design Center, Charoenkrung Post Building — membership or day pass required, ฿100); Asia Books (chain bookstore, most major Bangkok malls); Kinokuniya Bookstore (Siam Paragon B1, Emporium BTS Phrom Phong — Bangkok's best English-language bookstore selection); NAILERT Park Heritage Home library/archive (heritage home site, Wireless Road); The Reading Room (Charoenkrung, independent reading space)",
    price: "Kinokuniya Bangkok: English books at standard international price (฿400–1,500 for English-language titles, which are priced relatively high due to import costs); Asia Books: English paperbacks ฿250–800; TCDC day pass: ฿100 (grants access to library, co-working space, material samples); Bangkok used book trade: Khao San Road area has several second-hand English-language bookshops (฿50–300 per title); Bookazine at major malls for imported international magazines and books; Chulalongkorn University academic bookstore: Thai and English academic texts at university pricing; Bangkok Library (British Council): Siam Square area, English learning library, membership-based",
    why: "Bangkok's intellectual infrastructure reflects Thailand's educational ambitions and the city's role as a regional center for higher education and research: (1) Bangkok's university density: Bangkok contains Thailand's most prestigious and largest universities: Chulalongkorn University (established 1917 by Rama VI, medical, law, engineering, arts and sciences; internationally ranked in Asia regional rankings); Thammasat University (1934, strong in law and political science, historically significant as democracy movement locus); Mahidol University (health sciences emphasis, Bangkok campus and Salaya campus); King Mongkut's University of Technology (KMUTT, engineering/technology focus); Bangkok's university district centered around Siam BTS area is intellectually and culturally vibrant; (2) Thailand's education system challenges: Thailand's higher education produces approximately 400,000+ graduates annually; graduate employment quality is a persistent challenge (mismatch between university curriculum and labor market); this creates Bangkok's surplus of English-speaking, educated young adults working in service industries; (3) Bangkok's reading culture: Thai reading culture is present but compact — Thai book publishing is significant (Thai-language books at BookMoby, SE-ED book centers, B2S — common Bangkok mall bookstores); the Thai publishing industry supports active popular fiction, self-help, and business genres; Bangkok's few English-language independent bookshops (Dasa Book Café in Sukhumvit, Books Kinokuniya) serve the international community; (4) Academic journals and research infrastructure: Chulalongkorn University and Mahidol University are Thailand's primary research output institutions; the National Research Council of Thailand (NRCT) coordinates national research; Bangkok's academic infrastructure is connected to ASEAN and global academic networks through Chulalongkorn's international partnerships; (5) Informal knowledge culture in Bangkok: Bangkok's intellectual culture manifests through: TED-style talks (TEDxBangkok events), the growing café-with-books culture in Ari/Thong Lo neighborhoods, Bangkok's book club communities (English-language expat book clubs active through Facebook), and the documentary screening culture around Doc Club events.",
    tip: "Engaging Bangkok's intellectual infrastructure: (1) Chulalongkorn University campus walk: the university campus (entrance from Henri Dunant Road, BTS National Stadium adjacent) has beautiful ceremonial buildings (Chula's main administrative building is visually impressive), the King Rama V statue, Mahachakri Sirindhorn Park (within campus), and various faculty buildings accessible during academic year; the campus is Bangkok's most beautiful university environment; (2) TCDC Charoenkrung as intellectual-creative hub: the restored General Post Office building houses TCDC, River City Bangkok (antiques), several design studios, and Charoenkrung's creative scene; a day in the Charoenkrung area can combine TCDC library, River City, Asiatique riverfront, and heritage architecture; (3) Kinokuniya Siam Paragon: Bangkok's best English bookstore has extensive Southeast Asian studies, Asian history, Thai studies, and English fiction sections; the Paragon mall setting is comfortable; good for picking up serious Bangkok/Thailand reading material; (4) Used English books: Khao San Road second-hand English book trade (several small shops and street vendors on Khao San and Rambutri) provides cheap English paperbacks; the selection is typical of traveler book trades (popular fiction, travel guides); (5) Thammasat University historical significance: Thammasat University (Tha Phra Chan area, near Grand Palace) is particularly significant for understanding Thai political history — it was the site of the 1973 and 1976 popular uprisings (with tragic consequences in 1976); the university's central field is a site of memory for Thai democracy history; students and faculty continue to engage with Thai political thought in historically charged ways.",
  },
  {
    name: "Bangkok Innovation Ecosystem — Startup Scene, Innovation Districts & Thailand's Tech Future",
    emoji: "💡",
    area: "Bangkok's innovation geography: True Digital Park (Sukhumvit 101/1, BTS Udom Suk) — Bangkok's largest tech startup and innovation hub, 150,000 sqm complex, co-working, accelerators, corporates and startups; Samyan Mitrtown (Samyan MRT, near Chulalongkorn University) — mixed-use development oriented toward student and young professional tech culture; HUBBA (multiple locations: Ekkamai, Samyan) — co-working spaces popular with tech startups; RISE (acceleration program, Charoengkrung area); Dtac Accelerate, AIS The StartUp (corporate accelerator programs); SCB 10X (SCB bank's innovation arm, Ratchayothin area); Eastern Economic Corridor (EEC): 30,000+ hectare special economic zone east of Bangkok (Chonburi, Rayong provinces) — designated for high-tech manufacturing, medical hubs, digital industry; Impact (Arena) Muang Thong Thani: tech conference venue where major Thailand tech events (Thailand National Forum, RISE conference) are held",
    price: "True Digital Park: entry is free to walk through the complex; co-working day pass ฿200–500 (check current rates); HUBBA Ekkamai day pass: ฿250 (includes coffee); innovation event attendance: various Bangkok tech events are free (RISE, Techsauce, Thailand National Forum) or low-cost registration; Dragon Startup (government-backed EEC startup program): free application program; National Innovation Agency (NIA) events: check nia.or.th for current innovation-themed public events; Bangkok co-working culture: day pass ฿150–400 depending on location",
    why: "Bangkok's innovation ecosystem has developed rapidly since 2015 and represents an important emerging technology hub in Southeast Asia: (1) Thailand's startup ecosystem development: Thailand's startup ecosystem is smaller than Singapore or Indonesia but growing; notable Thai startups: SCB Abacus (fintech), Wongnai (restaurant discovery, acquired by LINE), Pomelo (fashion e-commerce), Flash Express (logistics), Gowabi (beauty booking app), ByteDance Thailand operation; Thailand's startup exits have been limited relative to larger neighbors but corporate venture interest has increased significantly; (2) Government innovation mandates — Thailand 4.0: Thailand's government economic strategy (Thailand 4.0) explicitly aims to transition from manufacturing to innovation-driven economy; specific target industries: AI, robotics, smart electronics, medical devices, digital content, biofuels; the Eastern Economic Corridor (EEC) is the primary physical implementation of this strategy — creating a special zone attracting high-tech foreign direct investment with tax incentives and streamlined regulation; (3) Corporate innovation infrastructure: Thailand's major corporations (BDMS healthcare, SCB bank, PTT energy, Charoen Pokphand group) have all created corporate venture arms and innovation programs; the Bangkok corporate ecosystem provides more startup support infrastructure than many comparable markets; government-linked corporations (PTT, Thai Beverage, etc.) are also moving toward innovation investment; (4) Bangkok's developer and tech talent pool: Thailand's computer science university programs (KMITL, KMUTT, CU engineering, Mahidol) produce approximately 15,000–20,000 computing graduates annually; the talent pool is growing but a significant portion emigrates for higher salaries in Singapore, Japan, and Western countries; Bangkok's tech salaries (฿40,000–120,000/month for experienced engineers) are lower than Singapore but cost of living allows reasonable lifestyle; (5) True Digital Park as innovation campus: True Digital Park (TDP) is the most visible physical manifestation of Bangkok's tech ambitions — a purpose-built innovation campus with co-working space, event venues, corporate innovation labs, and startup offices; the campus atmosphere is consciously modeled on Silicon Valley campus culture; visiting TDP provides a direct read on Bangkok's tech scene's scale and character.",
    tip: "Bangkok tech and innovation engagement: (1) True Digital Park visit: take BTS to Udom Suk station (exit toward Sukhumvit 101/1); the campus is a 20-minute walk or short Grab from the station; visiting during weekday daytime provides the most active startup environment; the ground-floor event space and café area are accessible without any pass; (2) Bangkok tech events: Techsauce Global Summit (annual, September, IMPACT Muang Thong Thani) is Bangkok's largest tech conference — startup pitches, corporate innovation showcases, international speakers; check techsauce.co for tickets; free satellite events run alongside the main conference; (3) RISE conference (annual, November–December) focuses on corporate innovation and digital transformation; Bangkok-based but targets corporate audience; (4) Co-working culture observation: HUBBA Ekkamai (BTS Ekkamai area) or Samyan Mitrtown (Samyan MRT) provide observation points for Bangkok's tech worker culture — the demographic (25–35, English-speaking, laptop-working in cafés) represents Thailand's emerging tech professional class; (5) EEC investment context: the Eastern Economic Corridor (EEC) is accessed easily from Bangkok by train (U-Tapao/Laem Chabang area); the EEC's industrial zone is not tourist-oriented but AMATA Corporation's innovation city in Chonburi represents the physical reality of Thailand's industrial-innovation transition; visiting as part of a day trip to the coastal Chonburi/Pattaya area is possible.",
  },
];

export function BangkokScienceMuseum() {
  return (
    <div className="rounded-2xl border border-blue-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-blue-700 mb-3">
        🔬 Bangkok knowledge infrastructure — science museums, academic libraries & startup innovation ecosystem
      </div>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-blue-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <div className="font-bold text-xs">{s.name}</div>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="shrink-0 text-[10px] font-mono text-blue-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-blue-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
