const TOPICS = [
  {
    title: "Bangkok Mosquitoes & Dengue — Dengue Risk, Prevention & What to Do if Bitten",
    emoji: "🦟",
    summary: "Bangkok has endemic dengue fever and understanding mosquito risk is essential for health-conscious visitors: (1) Bangkok's dengue reality: dengue fever is the most significant mosquito-borne illness risk for Bangkok visitors; Thailand reports 100,000–200,000 dengue cases annually (with under-reporting, actual cases are estimated significantly higher); Bangkok has dengue transmission year-round, with peaks in the rainy season (June–October) when Aedes aegypti mosquito breeding conditions are optimal; (2) Dengue vs. malaria in Bangkok: malaria risk in Bangkok city itself is minimal (urban Bangkok is not a malaria transmission zone); malaria risk exists in border areas and forested regions of Thailand (Kanchanaburi border zone, parts of Chiang Rai border area); Bangkok visitors need dengue prevention, not malaria prophylaxis; (3) Aedes aegypti characteristics: Bangkok's dengue vector (Aedes aegypti) is a daytime mosquito (biting peak 6–10am and 4–8pm) unlike the evening/nighttime-active malaria mosquito; wearing long sleeves during dawn and dusk reduces exposure; Aedes mosquitoes breed in small clean water containers (flower pot saucers, discarded bottles, air conditioner drip containers); (4) Dengue fever symptoms: dengue symptoms appear 4–7 days after bite — sudden high fever (39–40°C), severe headache (especially behind eyes), joint and muscle pain (historically called 'breakbone fever'), rash (appearing 3–5 days after fever onset), mild bleeding (gums, nose); severe dengue (dengue hemorrhagic fever) can be life-threatening; Bangkok's international hospitals (Bumrungrad, Bangkok Hospital) have dengue-experienced physicians; (5) Bangkok vs. provincial dengue risk: Bangkok's urban environment has dengue transmission but is generally lower risk than Thailand's rural and semi-rural areas; the city's pest control programs (some Bangkok districts have fumigation campaigns) and better drainage infrastructure reduce but do not eliminate risk.",
    action: "Dengue prevention in Bangkok: DEET 30–50% repellent (apply to skin, safe for adults and children 2+); picaridin (Icaridin) is an alternative with better skin feel and similar effectiveness; long-sleeve light fabrics during dusk/dawn hours; Bangkok pharmacy repellents: OFF! Lotion (widely available at 7-Eleven, Boots, Watson's), Sketolene, Thai-brand DEET products; dengue diagnosis: blood test (CBC, dengue NS1 antigen, dengue IgM/IgG) at Bangkok hospitals during fever; seek immediate care for high fever + severe headache + bone pain + rash; dengue vaccine: Dengvaxia (first dengue vaccine, requires prior dengue exposure for safety — consult doctor); Qdenga (new dengue vaccine, available without prior exposure requirement, consult travel medicine clinic before Thailand visit).",
  },
  {
    title: "Bangkok Street Food Safety — Stomach Issues, Food Poisoning & Water Safety",
    emoji: "🌮",
    summary: "Bangkok's street food is genuinely excellent and generally safer than many assume — but some specific risks require understanding: (1) Bangkok tap water: Bangkok's tap water (PAT — Metropolitan Waterworks Authority) is technically treated to potable standards by international measures; however, Bangkok residents and the vast majority of visitors use bottled water for drinking; the combination of aging pipe infrastructure in some areas, storage tank contamination risk, and cultural habit means bottled water is the universal standard; ice at restaurants: reputable restaurants use manufactured ice (tubular/hollow ice, commercially made) which is safe; ice from roadside ice machines is generally safe; crushed or block ice at market stalls has higher contamination risk; (2) Street food hygiene principles: Bangkok's street food scene operates on high volume and rapid turnover — dishes cooked and served immediately are generally safer than sitting food; the highest risk street food is: raw shellfish (oysters, raw shrimp), pre-assembled cold foods left at ambient temperature, cut fruit from vendors without refrigeration during hot midday hours, high-risk preparation (raw meat salads — larb from unknown vendors — undercooked pork); (3) Common Bangkok traveler stomach issues: the most common cause of Bangkok traveler's stomach is not pathogenic contamination but dietary adjustment — Thai food's spice, oil, and unfamiliar ingredients cause GI adjustment in most visitors during the first 2–3 days; true food poisoning (pathogenic contamination) produces faster onset, more severe symptoms; distinguishing adjustment from infection helps appropriate response; (4) The 7-Eleven food safety question: Bangkok's 7-Eleven stores (ubiquitous, 24-hour) sell prepared foods in heated cases, microwave-able meals, and shelf-stable products; heated case items maintained at proper temperature (above 60°C) are generally safe; the highest-risk 7-Eleven items are sandwiches and prepared items that have been sitting unrefrigerated; the expiry date system at 7-Eleven is generally reliable; (5) Food poisoning treatment in Bangkok: mild stomach issues — oral rehydration salts (ORS, available at all Bangkok pharmacies, 7-Eleven); clear fluids; rest; smecta (diosmectite) for diarrhea; Bangkok hospitals for severe cases (bloody diarrhea, fever above 38.5°C, vomiting unable to keep fluids down, signs of dehydration) — Bumrungrad, Bangkok Hospital, or nearest international clinic.",
    action: "Bangkok drinking water: buy large 1.5L bottles at 7-Eleven (฿8–12) or Lotus's/BigC rather than repeatedly buying small 600ml bottles; coconut water provides natural electrolytes when adjusting to Bangkok; oral rehydration salts: ORSALIT (Boots Thailand), available at all pharmacies; anti-diarrheal Bangkok: loperamide (Imodium) at Thai pharmacies without prescription for traveler's diarrhea; antibiotic for severe traveler's diarrhea: consult Bangkok pharmacist — azithromycin sometimes recommended (pharmacist consultation required); food safety app: no reliable real-time Bangkok food safety rating system exists; judgment based on cooking style (fresh/high heat) and turnover (busy stall = fresh food) is the most reliable guide.",
  },
  {
    title: "Bangkok Health Checks — Vaccinations, Travel Medicine & What to Do Before You Go",
    emoji: "💊",
    summary: "Pre-travel health preparation for Bangkok requires specific vaccine consideration and health planning: (1) Recommended vaccinations for Bangkok: the following vaccines are recommended for Bangkok visitors (checking with a travel medicine clinic for individualized advice): Hepatitis A (food and water borne, highly recommended for all Bangkok travelers); Typhoid (food and water borne, recommended for longer stays or street food emphasis); Hepatitis B (blood/sexual contact borne, recommended for extended stays); Japanese Encephalitis (mosquito-borne, recommended for rural Thailand, lower risk for Bangkok-only visits); Tetanus-Diphtheria-Pertussis (routine vaccine, update if needed); Rabies (recommended for extended stays, animal contact possibility, or remote itineraries); (2) Vaccines NOT required for Bangkok: Yellow Fever is not required for Bangkok arrival from most countries (required only from specific Yellow Fever endemic countries); malaria prophylaxis is not recommended for Bangkok city visits (rural Thailand border areas may warrant prophylaxis); (3) Bangkok's travel medicine clinics: Bangkok Hospital International Travel Clinic, Bumrungrad International Travel Clinic, and Bangkok Christian Hospital travel vaccination services provide pre-travel vaccination and medical advice for Thailand specifically; international visitors who haven't prepared can receive vaccinations in Bangkok but some vaccines require time for immunization (Hepatitis A + B series takes months for full protection); (4) Purchasing prescription medications in Bangkok: Thailand has relatively liberal pharmaceutical access — many medications requiring prescription in Western countries are available at Bangkok pharmacies without prescription at significantly lower prices; antibiotics (specific types), antiparasitics, anti-malarials, and many other medications can be purchased at Bangkok pharmacies for self-treatment; this creates both opportunity (extending supply, lower cost) and risk (medication without diagnosis); consulting a Bangkok pharmacist or doctor before self-medicating is recommended; (5) Bangkok heat and medication: Bangkok's heat affects certain medications — medications that require refrigeration (insulin, certain biologics) need cold chain management; medications affecting heat regulation (certain antihistamines, anticholinergics, psychiatric medications) can impair Bangkok heat tolerance; discussing Bangkok heat impact with prescribing physician before travel for patients on complex medication regimens is appropriate.",
    action: "CDC Thailand travel health page: cdc.gov/travel/destinations/traveler/thailand for current vaccination recommendations; WHO Thailand profile: who.int for current health advisories; Bangkok travel medicine clinic: Bumrungrad International Hospital travel clinic (appointment booking 02-667-1000); vaccine availability Bangkok: most travel vaccines available at Bumrungrad and Bangkok Hospital walk-in or appointment; Bangkok pharmacy chain for self-treatment supplies: Boots Thailand (boots.co.th, English-speaking pharmacists at many locations), Watson's Thailand; travel health insurance recommendation: World Nomads, True Traveller, or equivalent global travel insurance covering Bangkok medical costs.",
  },
];

export function BangkokMosquito() {
  return (
    <div className="rounded-2xl border border-green-200 bg-white p-4 my-4">
      <div className="text-xs font-black uppercase tracking-widest text-green-700 mb-3">
        🦟 Bangkok health essentials — dengue prevention, street food safety & travel vaccinations
      </div>
      <div className="space-y-1.5">
        {TOPICS.map((t) => (
          <details key={t.title} className="border border-green-100 rounded-xl">
            <summary className="px-3 py-2 cursor-pointer font-bold text-xs flex items-center gap-2">
              <span>{t.emoji}</span>
              <span>{t.title}</span>
            </summary>
            <div className="px-3 pb-3">
              <div className="text-[10px] text-[var(--fg)] leading-snug mb-1">{t.summary}</div>
              <div className="text-[10px] text-green-700">→ {t.action}</div>
            </div>
          </details>
        ))}
      </div>
    </div>
  );
}
