const SPOTS = [
  {
    name: "Lanna Northern Thai Cuisine in Bangkok — Khao Soi, Sai Oua & Highland Food",
    emoji: "🍜",
    area: "Northern Thai restaurant clusters in Bangkok: Ari (best concentration of northern Thai restaurants in Bangkok); Ratchada area; Ladprao; specialty: Chiang Mai native-run khao soi shops scattered across Bangkok; highland coffee and tea bars (Doi Chaang, Doi Tung, Doi Inthanon branded products) at specialty cafés in Thong Lo, Ekkamai, Ari",
    price: "Khao soi (coconut curry noodles): ฿60–150; Sai oua (northern pork sausage, 100g): ฿30–60; Nam prik ong with vegetable plate: ฿80–150; Nam jim jaew dipping sauce: included or ฿20–40; Northern Thai restaurant set meal: ฿150–350; Highland coffee (Doi Chaang): ฿80–150; Kanom jeen nam ngiao (northern noodle curry): ฿60–120",
    why: "Northern Thai (Lanna) cuisine is one of Thailand's most distinct regional food traditions, shaped by the cooler mountain climate, Burmese cultural influence, and the independent Lanna Kingdom history: (1) Khao soi (ข้าวซอย) — Bangkok's gateway to Lanna food: khao soi (coconut milk-based curry with egg noodles, served with crispy fried noodles on top) is northern Thailand's most famous dish; Bangkok has many versions ranging from authentic Chiang Mai-style (slightly bitter, less sweet) to Bangkok-adapted versions (sweeter, creamier); (2) The holy trinity of northern Thai pastes: nam prik ong (pork and tomato chili relish — vivid red, mildly spicy), nam prik num (roasted green chili paste, Lanna's defining flavor — smoky and pungent), and nam jim jaew (grilled chili and herb dipping sauce for grilled meats) define northern Thai flavor; (3) Sai oua (ไส้อั่ว): northern Thai herb pork sausage is seasoned with lemongrass, galangal, kaffir lime leaves, and northern spice blends; distinctly different from Isaan's sai krok or central Thailand's mu yo; the grilling releases aromatic herb oils; (4) Nam ngiao noodle curry: a distinctly northern Thai curry noodle soup using pork blood, pork spareribs, and tomato with a non-coconut-based broth; different from khao soi; the fermented soybean paste (tua nao) used as seasoning is unique to northern Thai cuisine; (5) Northern Thailand's coffee and tea: the Golden Triangle's highland farms (Doi Chaang, Doi Tung Royal Project, Doi Kham) produce Thai specialty coffee and Oolong tea; these products are sold at branded cafés and specialty coffee shops across Bangkok; buying Doi Tung or Doi Chaang directly supports royal project hill tribe economic development programs.",
    tip: "Finding authentic northern Thai food in Bangkok: (1) Ari neighborhood northern Thai: Bangkok's Ari neighborhood (BTS Ari) has the highest concentration of chef-owned northern Thai restaurants; the neighborhood's higher local Thai dining culture selects for quality over tourist-oriented versions; walking the streets behind the BTS station rather than the main road reveals smaller, more authentic northern Thai shops; (2) Khao soi authenticity markers: authentic northern Thai khao soi uses a mildly spiced, less-sweet coconut curry broth; condensed milk or extra sugar is sometimes added in Bangkok adaptations to sweet-optimize for central Thai palates; requesting 'mai wan' (not sweet) at northern Thai restaurants ensures the more authentic version; (3) Northern Thai sausage sourcing: the best sai oua in Bangkok is made by shops that source northern Thai pork and make their own blends; sausages sold at fresh markets (Chatuchak, Or Tor Kor) from Chiang Mai-origin vendors are more reliably authentic than pre-packaged supermarket versions; (4) Highland coffee investment: specialty highland Thai coffee (Doi Chaang shade-grown, Akha Ama community roast) commands ฿90–180 per cup but represents genuine quality and direct economic benefit to hill tribe farming communities; supporting these products over generic Bangkok café offerings has real supply chain impact; (5) Northern Thai vegetables: northern Thai cuisine uses distinctive vegetables including phak wan (sweet leaf), chaem (water mimosa), and bitter gourd preparations alongside common Thai vegetables; specialist northern Thai restaurants import seasonal northern vegetables; availability varies with harvest season.",
  },
  {
    name: "Southern Thai Food in Bangkok — Gaeng Tai Pla, Roti & Spicy Curries",
    emoji: "🌶️",
    area: "Southern Thai food in Bangkok: Chatuchak Weekend Market (multiple southern Thai vendors, some of Bangkok's best); Bang Rak district (southern Thai community along Silom back streets); specific: Baan Ying restaurant (central Bangkok), multiple vendors in Pratunam area; Phuket-style food: Ko Pha-ngan and Phuket restaurant chains in malls; Bangkok's deep south Muslim community (Bang Phlat, Thon Buri): genuine southern Thai-Malay food",
    price: "Gaeng tai pla (southern salted fish curry): ฿80–180; Roti with massaman curry: ฿40–80; Southern Thai fish paste (kapi) plate: ฿60–120; Mee sua (southern noodle): ฿50–80; Satay (traditional southern style, 10 pieces): ฿80–150; Southern Thai set meal (Bangkok restaurant): ฿180–350; Khanom jeen nam ya (southern version): ฿50–80",
    why: "Southern Thai cuisine is Thailand's most intensely flavored regional tradition — fiercely spicy, heavy on seafood, and influenced by Malay Islamic culture in ways that create dishes unlike any other Thai regional cooking: (1) Southern Thai flavor profile: gaeng (curry) dishes in the south use fresh turmeric, galangal, dried chili (significantly more than central Thai), and kapi (fermented shrimp paste) as flavor foundations; the result is denser, more pungent, and hotter than Bangkok food; the southern Thai saying 'spicy enough to make you cry' (เผ็ดจนร้องไห้) is not an exaggeration; (2) Gaeng tai pla (แกงไตปลา): fermented fish intestine curry is southern Thailand's most polarizing dish; the intense, fermented seafood flavor with significant spice heat is deeply loved by southern Thais and challenging for first-time eaters; a small portion as part of a set meal is the recommended introduction; (3) Southern Thai roti tradition: southern Thailand's Malay Muslim heritage produces the flat bread roti (โรตี) tradition; Bangkok's southern Thai roti shops (often Muslim-operated, with extended halal food offerings) serve roti with massaman curry, condensed milk, or banana filling; the technical skill of stretching and folding roti dough is a practiced craft; (4) Khanom jeen nam ya (southern style): central Thailand's khanom jeen (rice noodles with curry) has a southern version using a different curry base with coastal seafood; the southern version's deeper, more pungent flavor reflects southern seafood culture; (5) Satay's southern Thai origin: Thailand's satay (เสาะ) tradition originated in southern Thailand from Malay-Muslim peddler culture; authentic southern Thai satay uses specific spice marinades (turmeric, coriander, cumin), bamboo skewers, and a specific charcoal grilling technique; Bangkok's night market satay often approximates rather than replicates the southern original.",
    tip: "Southern Thai food access in Bangkok: (1) Chatuchak Weekend Market southern vendors: the southern Thai food vendors at Chatuchak (particularly Section 4 and the area near the Weekend Market Clock Tower) include some of Bangkok's most authentic southern Thai cooking; the market's food section is significantly less visited by tourists than the shopping sections; (2) Southern Thai spice management: southern Thai food is genuinely hot by global standards; if heat-sensitive, specifying 'mai phet' (not spicy) dramatically reduces the chili content, though the dish's character changes; trying the dish at authentic spice level even if it's challenging provides the most complete flavor understanding; (3) Kapi quality indicator: high-quality fermented shrimp paste (kapi, กะปิ) smells strongly of fermented seafood; southern Thai restaurants that use quality kapi in curries and relishes signal attention to regional authenticity; (4) Muslim southern Thai distinction: southern Thailand's significant Muslim population (particularly Pattani, Yala, Narathiwat provinces) has influenced southern Thai food to include pork-free versions of many dishes; Bangkok's southern Thai restaurants serving Muslim communities use beef or chicken where pork is traditional; the halal sign indicates Muslim-appropriate preparation; (5) Regional southern Thai sub-cuisines: southern Thai food is not uniform; Phuket's cuisine (Chinese-influenced, with roast pork, dim sum hybrids, and local spice blend) differs from the deep south's Malay-Muslim influenced cooking, which differs again from Surat Thani's seafood-forward traditions; Bangkok's best southern Thai restaurants typically specialize in one regional sub-tradition rather than aggregating all southern styles.",
  },
  {
    name: "Central Thai & Royal Cuisine — Bangkok's Culinary Heartland",
    emoji: "👑",
    area: "Central Thai fine dining: Grand Palace area (upscale traditional Thai restaurants); Riverside (Sala Rim Naam at Oriental, Harmonique, Krua Apsorn); Silom (Baan Khanitha, Blue Elephant for royal Thai cuisine); Central Thai everyday: all Bangkok neighborhoods; traditional desserts: Siam Square (Bua), Chinatown (Fa Tuan Bia Hap); royal Thai cuisine training: Blue Elephant Cooking School, Oriental Hotel Thai cooking class",
    price: "Traditional central Thai restaurant (mid-range): ฿300–700/person; Royal Thai cuisine experience (Sala Rim Naam, Blue Elephant): ฿1,200–3,000/person; Central Thai street food (per dish): ฿40–120; Thai dessert set (fine dining): ฿150–350; Ordinary dessert stall (khao niew mamuang, etc.): ฿30–80; Royal Thai cuisine cooking class: ฿2,000–5,000; Khantoke dinner (northern Thai royal table service): ฿500–1,200",
    why: "Central Thai cuisine — Bangkok's own culinary tradition — is the version most people know as 'Thai food,' yet the depth of authentic central Thai and royal Thai cooking goes far beyond what is typically exported: (1) Central Thai flavor balance: central Thai cuisine's defining characteristic is a precise balance of four flavors — sweet (palm sugar), sour (lime juice, tamarind), salty (fish sauce, shrimp paste), and spicy (fresh chili); this balance architecture is meticulously maintained in traditional cooking and often skewed in tourist-oriented versions (typically sweeter); (2) Royal Thai cuisine heritage: the Thai royal court developed a highly refined cuisine tradition emphasizing presentation (intricate vegetable and fruit carving, delicate garnishing), technique (grinding fresh curry pastes by hand, layering aromatics), and flavoring precision; Royal Thai cuisine is served at formal banquets and replicated in a small number of Bangkok fine dining restaurants; (3) Tom yam and pad thai — the global ambassadors: Bangkok's most internationally famous dishes have both authentic and tourist versions; authentic tom yam (spicy and sour lemongrass soup) uses fresh galangal, lemongrass, kaffir lime leaf, and fresh chili without cream thickening; 'tom yam' on tourist menus in Bangkok is often cream-diluted; pad thai's authentic version differs from typical tourist preparations in using tamarind-based sauce rather than ketchup substitutes; (4) Mangosteen, rambutan and tropical fruit as dessert: central Thai tradition incorporates seasonal tropical fruits as both palate cleansers and dessert; Bangkok's fruit-cutting vendor tradition (fresh pre-cut fruit in biodegradable bags) provides the most convenient tropical fruit access; (5) Kanom (Thai sweets and desserts): traditional Thai sweets use glutinous rice, coconut cream, palm sugar, pandan, banana leaf, and jasmine water as flavor foundations; the category of kanom is extremely diverse (over 100 named varieties); Bangkok's Or Tor Kor Market and specialist dessert shops carry traditional kanom not available in tourist-area restaurants.",
    tip: "Central and royal Thai cuisine exploration in Bangkok: (1) Avoiding tourist-optimized Thai food: restaurants near major tourist sites (around Grand Palace, Khao San Road, Patpong) often serve sweetened, less-spiced versions of Thai dishes to match the assumed preferences of international visitors; moving 2–3 blocks away from tourist clusters and finding restaurants with predominantly Thai clientele produces significantly more authentic food; (2) Curry paste authenticity check: the most significant quality indicator in Bangkok's traditional Thai restaurants is fresh-ground curry paste (made in-house with a mortar and pestle or fresh paste mill) vs. commercial packaged paste; asking whether curry paste is house-made ('tham sot sot' in Thai) filters for quality; (3) Thai set meal (khantoke) experience: the traditional northern Thai khantoke (lacquer tray with multiple small dishes of northern Thai food) served at historic Bangkok venues (Sala Rim Naam, Blue Elephant) provides structured exposure to multiple regional dishes in one experience; the set meal format helps navigate unfamiliar dishes; (4) Seasonal Thai fruit guide: Bangkok's fruit seasonality is intense; mangosteen (April–September), durian (May–August), rambutan (May–September), longkong (July–October), and mango (March–June for highest quality) peak at specific times; visiting Bangkok during peak season for specific favorites significantly improves fruit quality; (5) Royal Palace area restaurant quality: restaurants near the Grand Palace area that cater to tourist traffic vary enormously in quality; Krua Apsorn (Dinso Road) and a handful of local restaurants near the Democracy Monument serve genuinely high-quality central Thai food at local prices in tourist proximity.",
  },
];

export function BangkokNorthernFood() {
  return (
    <div className="rounded-2xl border border-orange-200 bg-white p-4 my-4">
      <h2 className="text-xs font-black uppercase tracking-widest text-orange-700 mb-3">
        🍜 Thailand's regional cuisines in Bangkok — northern Lanna, southern spice & central Thai royal food
      </h2>
      <div className="space-y-2">
        {SPOTS.map((s) => (
          <div key={s.name} className="border border-orange-100 rounded-xl p-3">
            <div className="flex items-start gap-2 mb-1.5">
              <span className="text-2xl shrink-0">{s.emoji}</span>
              <div className="flex-1 min-w-0">
                <h3 className="font-bold text-xs">{s.name}</h3>
                <div className="text-[10px] text-[var(--muted)]">{s.area}</div>
              </div>
              <span className="min-w-0 break-words text-right text-[10px] font-mono text-green-700">{s.price}</span>
            </div>
            <div className="text-[10px] text-[var(--fg)] mb-0.5 leading-snug">{s.why}</div>
            <div className="text-[10px] text-orange-700">💡 {s.tip}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
