// Data access for bangkoktopclinic.
//
// This used to open a MySQL pool against a Railway instance on every ISR
// regeneration. On 2026-08-06 that trial expired, the container stopped, and
// because it was the site's only datastore *and* its only copy of the data, the
// whole site degraded to cached husks within a day. It now reads a JSON file
// generated by ../../export_to_json.py and committed to git — so the data is
// versioned, the deploy is atomic, there is nothing to keep paying for, and
// there is no longer a network dependency that can take the site down.
//
// The exported function signatures and types are deliberately unchanged from
// the MySQL version so no page had to be touched. Where a query's result
// depended on a MySQL-specific ordering rule, that rule is reproduced here
// rather than quietly "improved" — see cmpNum/cmpStr.
//
// Update path: scrape into local MariaDB -> python export_to_json.py -> commit -> deploy.

import raw from "@/data/checkup_db.json";

// ── Types (unchanged from the MySQL implementation) ──────────────────────────

export type CategoryCount = { category: string; count: number };

export type PackageRow = {
  hospital_name: string;
  hospital_slug: string;
  area: string | null;
  city: string | null;
  jci: number;
  checkup_url: string | null;
  rating: string | null;
  review_count: number | null;
  package_id: number;
  package_name: string;
  category: string | null;
  price: string | null;
  currency: string;
  description: string | null;
  has_blood: number | null;
  has_xray: number | null;
  has_ultrasound: number | null;
  has_ct: number | null;
  has_mri: number | null;
  has_ecg: number | null;
  has_treadmill: number | null;
  has_cancer_marker: number | null;
  has_doctor_consult: number | null;
  has_interpreter: number | null;
  results_days: number | null;
  source_url: string | null;
};

export type OpeningHours = { day: string; hours: string }[];

export type HospitalSummary = {
  id: number;
  name: string;
  slug: string;
  area: string | null;
  city: string | null;
  jci: number;
  checkup_url: string | null;
  rating: string | null;
  review_count: number | null;
  package_count: number;
  min_price: string | null;
  /**
   * Google's own classification of the listing. Load-bearing: the HDmall
   * import files beauty salons and physiotherapy rooms under "health
   * checkup", so this is what lets the UI say what a listing actually is
   * instead of presenting a salon as a hospital.
   */
  category_name: string | null;
};

export type HospitalDetail = HospitalSummary & {
  name_th: string | null;
  lat: string | null;
  lng: string | null;
  address: string | null;
  phone: string | null;
  website: string | null;
  description: string | null;
  founded_year: number | null;
  bed_count: number | null;
  specialties: string | null;
  accreditations: string | null;
  email: string | null;
  opening_hours: OpeningHours | null;
  google_maps_url: string | null;
  packages: PackageRow[];
};

export type SnapshotRow = {
  snapshot_date: string;
  price: string | null;
};

export type ReviewRow = {
  id: number;
  author_name: string | null;
  rating: number | null;
  review_text: string | null;
  review_date: string | null;
  source: string | null;
};

export type PriceTrendRow = {
  hospital_name: string;
  hospital_slug: string;
  package_id: number;
  package_name: string;
  category: string | null;
  latest_price: number;
  prev_price: number;
  change_pct: number;
};

// ── Shapes as they come out of export_to_json.py ─────────────────────────────

type RawHospital = {
  id: number; name: string; name_th: string | null; slug: string;
  tier: string | null; area: string | null; city: string | null;
  jci: number; checkup_url: string | null; lat: string | null; lng: string | null;
  address: string | null; phone: string | null; website: string | null;
  description: string | null; founded_year: number | null; bed_count: number | null;
  specialties: string | null; accreditations: string | null; email: string | null;
  rating: string | null; review_count: number | null;
  category_name: string | null; opening_hours: OpeningHours | null;
  google_maps_url: string | null; permanently_closed: number | null;
};

type RawPackage = {
  id: number; hospital_id: number; name: string; category: string | null;
  price: string | null; currency: string | null; description: string | null;
  has_blood: number | null; has_xray: number | null; has_ultrasound: number | null;
  has_ct: number | null; has_mri: number | null; has_ecg: number | null;
  has_treadmill: number | null; has_cancer_marker: number | null;
  has_doctor_consult: number | null; has_interpreter: number | null;
  results_days: number | null; source_url: string | null;
};

type RawReview = {
  id: number; hospital_id: number; author_name: string | null;
  rating: string | number | null; review_text: string | null;
  review_date: string | null; source: string | null;
};

type RawSnapshot = { package_id: number; snapshot_date: string; price: string | null };

type Dataset = {
  generated_at: string;
  hospitals: RawHospital[];
  packages: RawPackage[];
  reviews: RawReview[];
  snapshots: RawSnapshot[];
};

const data = raw as unknown as Dataset;

// An empty dataset means the export never ran or shipped truncated. Rendering
// "0 hospitals" as a cheerful 200 is exactly the failure that hid the outage
// for a day last time, so refuse to start instead — the build fails loudly and
// nothing reaches Google.
if (!data.hospitals?.length || !data.packages?.length) {
  throw new Error(
    "web/data/checkup_db.json is empty or missing — run `python export_to_json.py` " +
    "against the local MariaDB and commit the result before building.",
  );
}

// ── MySQL ordering semantics ─────────────────────────────────────────────────
// MySQL sorts NULL *before* every non-NULL value on ASC and after it on DESC.
// JS comparators treat null as 0, which silently reorders price lists. These
// two helpers keep the rendered order byte-identical to what the SQL produced.

function cmpNum(a: number | null, b: number | null, dir: 1 | -1 = 1): number {
  if (a === null && b === null) return 0;
  if (a === null) return dir === 1 ? -1 : 1;
  if (b === null) return dir === 1 ? 1 : -1;
  return a === b ? 0 : (a < b ? -1 : 1) * dir;
}

function cmpStr(a: string | null, b: string | null, dir: 1 | -1 = 1): number {
  if (a === null && b === null) return 0;
  if (a === null) return dir === 1 ? -1 : 1;
  if (b === null) return dir === 1 ? 1 : -1;
  const c = a.localeCompare(b);
  return c === 0 ? 0 : (c < 0 ? -1 : 1) * dir;
}

const num = (v: string | number | null | undefined): number | null =>
  v === null || v === undefined || v === "" ? null : Number(v);

// ── Indexes, built once per server process ───────────────────────────────────

const hospitalsById = new Map<number, RawHospital>(data.hospitals.map((h) => [h.id, h]));
const hospitalsBySlug = new Map<string, RawHospital>(data.hospitals.map((h) => [h.slug, h]));

function toRow(p: RawPackage, h: RawHospital): PackageRow {
  return {
    hospital_name: h.name,
    hospital_slug: h.slug,
    area: h.area,
    city: h.city,
    jci: h.jci,
    checkup_url: h.checkup_url,
    rating: h.rating,
    review_count: h.review_count,
    package_id: p.id,
    package_name: p.name,
    category: p.category,
    price: p.price,
    currency: p.currency ?? "THB",
    description: p.description,
    has_blood: p.has_blood,
    has_xray: p.has_xray,
    has_ultrasound: p.has_ultrasound,
    has_ct: p.has_ct,
    has_mri: p.has_mri,
    has_ecg: p.has_ecg,
    has_treadmill: p.has_treadmill,
    has_cancer_marker: p.has_cancer_marker,
    has_doctor_consult: p.has_doctor_consult,
    has_interpreter: p.has_interpreter,
    results_days: p.results_days,
    source_url: p.source_url,
  };
}

// Every package joined to its hospital, i.e. the FROM ... JOIN every query used.
// Packages whose hospital_id dangles are dropped, matching the INNER JOIN.
const allRows: PackageRow[] = data.packages
  .map((p) => {
    const h = hospitalsById.get(p.hospital_id);
    return h ? toRow(p, h) : null;
  })
  .filter((r): r is PackageRow => r !== null);

const rowsByHospitalSlug = new Map<string, PackageRow[]>();
const rowsByCategory = new Map<string, PackageRow[]>();
for (const r of allRows) {
  const bySlug = rowsByHospitalSlug.get(r.hospital_slug);
  if (bySlug) bySlug.push(r); else rowsByHospitalSlug.set(r.hospital_slug, [r]);
  if (r.category) {
    const byCat = rowsByCategory.get(r.category);
    if (byCat) byCat.push(r); else rowsByCategory.set(r.category, [r]);
  }
}

const SORTS: Record<string, (a: PackageRow, b: PackageRow) => number> = {
  price: (a, b) => cmpNum(num(a.price), num(b.price)) || cmpStr(a.hospital_name, b.hospital_name),
  price_desc: (a, b) => cmpNum(num(a.price), num(b.price), -1) || cmpStr(a.hospital_name, b.hospital_name),
  hospital: (a, b) => cmpStr(a.hospital_name, b.hospital_name) || cmpNum(num(a.price), num(b.price)),
  results_days: (a, b) => cmpNum(a.results_days, b.results_days) || cmpNum(num(a.price), num(b.price)),
  rating: (a, b) => cmpNum(num(a.rating), num(b.rating), -1) || cmpNum(num(a.price), num(b.price)),
};

const sortRows = (rows: PackageRow[], sort: string): PackageRow[] =>
  [...rows].sort(SORTS[sort] ?? SORTS.price);

// ── Queries ──────────────────────────────────────────────────────────────────

export async function getCategories(): Promise<CategoryCount[]> {
  const counts = new Map<string, number>();
  for (const p of data.packages) {
    if (!p.category) continue;
    counts.set(p.category, (counts.get(p.category) ?? 0) + 1);
  }
  return [...counts.entries()]
    .map(([category, count]) => ({ category, count }))
    .sort((a, b) => b.count - a.count);
}

export async function getPackagesByCategory(cat: string, sort = "price"): Promise<PackageRow[]> {
  return sortRows(rowsByCategory.get(cat) ?? [], sort);
}

export async function getAllPackages(sort = "price"): Promise<PackageRow[]> {
  return sortRows(allRows, sort);
}

export async function getHospitals(): Promise<HospitalSummary[]> {
  // LEFT JOIN: hospitals with no packages still appear, with a 0 count.
  // Permanently/temporarily closed businesses are filtered out — Google says
  // they are shut, so listing them as bookable is simply wrong. The rows stay
  // in the dataset; only the listings hide them.
  return data.hospitals
    .filter((h) => !h.permanently_closed)
    .map((h) => {
      const rows = rowsByHospitalSlug.get(h.slug) ?? [];
      const prices = rows.map((r) => num(r.price)).filter((p): p is number => p !== null);
      return {
        id: h.id,
        name: h.name,
        slug: h.slug,
        area: h.area,
        city: h.city,
        jci: h.jci,
        checkup_url: h.checkup_url,
        rating: h.rating,
        review_count: h.review_count,
        package_count: rows.length,
        min_price: prices.length ? String(Math.min(...prices)) : null,
        category_name: h.category_name,
      };
    })
    .sort((a, b) => {
      const ta = hospitalsById.get(a.id)?.tier ?? null;
      const tb = hospitalsById.get(b.id)?.tier ?? null;
      return cmpStr(ta, tb, -1) || cmpStr(a.name, b.name);
    });
}

export async function getHospital(slug: string): Promise<HospitalDetail | null> {
  const h = hospitalsBySlug.get(slug);
  if (!h) return null;
  const rows = rowsByHospitalSlug.get(slug) ?? [];
  const prices = rows.map((r) => num(r.price)).filter((p): p is number => p !== null);
  return {
    id: h.id,
    name: h.name,
    slug: h.slug,
    area: h.area,
    city: h.city,
    jci: h.jci,
    checkup_url: h.checkup_url,
    rating: h.rating,
    review_count: h.review_count,
    package_count: rows.length,
    min_price: prices.length ? String(Math.min(...prices)) : null,
    category_name: h.category_name,
    opening_hours: h.opening_hours,
    google_maps_url: h.google_maps_url,
    name_th: h.name_th,
    lat: h.lat,
    lng: h.lng,
    address: h.address,
    phone: h.phone,
    website: h.website,
    description: h.description,
    founded_year: h.founded_year,
    bed_count: h.bed_count,
    specialties: h.specialties,
    accreditations: h.accreditations,
    email: h.email,
    // ORDER BY p.category, p.price ASC
    packages: [...rows].sort(
      (a, b) => cmpStr(a.category, b.category) || cmpNum(num(a.price), num(b.price)),
    ),
  };
}

export async function getPackagesByCity(city: string, sort = "price"): Promise<PackageRow[]> {
  return sortRows(allRows.filter((r) => r.city === city), sort).slice(0, 600);
}

export async function getCities(): Promise<{ city: string; count: number }[]> {
  // INNER JOIN: only cities that actually have packages.
  const counts = new Map<string, number>();
  for (const r of allRows) {
    if (!r.city) continue;
    counts.set(r.city, (counts.get(r.city) ?? 0) + 1);
  }
  return [...counts.entries()]
    .map(([city, count]) => ({ city, count }))
    .sort((a, b) => b.count - a.count);
}

export async function getPackage(type: string, hospitalSlug: string): Promise<PackageRow | null> {
  const matches = (rowsByHospitalSlug.get(hospitalSlug) ?? []).filter((r) => r.category === type);
  if (!matches.length) return null;
  // The SQL was `ORDER BY p.price ASC LIMIT 1`, and MySQL sorts NULL first —
  // so a hospital offering both a priced and an unpriced package in the same
  // category rendered "Price on request" while the sitemap listed it as
  // priced. Prefer a real price and fall back to the unpriced row.
  const priced = matches.filter((r) => num(r.price) !== null);
  const pool = priced.length ? priced : matches;
  return [...pool].sort((a, b) => cmpNum(num(a.price), num(b.price)))[0];
}

const snapshotsByPackage = new Map<number, RawSnapshot[]>();
for (const s of data.snapshots) {
  const list = snapshotsByPackage.get(s.package_id);
  if (list) list.push(s); else snapshotsByPackage.set(s.package_id, [s]);
}
for (const list of snapshotsByPackage.values()) {
  list.sort((a, b) => a.snapshot_date.localeCompare(b.snapshot_date));
}

export async function getPriceHistoryBatch(packageIds: number[]): Promise<Record<number, number[]>> {
  const result: Record<number, number[]> = {};
  for (const id of packageIds) {
    for (const s of snapshotsByPackage.get(id) ?? []) {
      const p = num(s.price);
      if (p === null) continue;
      (result[id] ??= []).push(p);
    }
  }
  return result;
}

export async function getPriceHistory(packageId: number): Promise<SnapshotRow[]> {
  return (snapshotsByPackage.get(packageId) ?? []).map((s) => ({
    snapshot_date: s.snapshot_date,
    price: s.price,
  }));
}

export async function getHospitalReviews(slug: string, limit = 5): Promise<ReviewRow[]> {
  const h = hospitalsBySlug.get(slug);
  if (!h) return [];
  return data.reviews
    .filter((r) => r.hospital_id === h.id && r.review_text && r.review_text.trim() !== "")
    .map((r) => ({
      id: r.id,
      author_name: r.author_name,
      rating: num(r.rating),
      review_text: r.review_text,
      review_date: r.review_date,
      source: r.source,
    }))
    .sort((a, b) => cmpNum(a.rating, b.rating, -1) || cmpStr(a.review_date, b.review_date, -1))
    .slice(0, limit);
}

export async function getHospitalsForCompare(slugs: string[]): Promise<HospitalDetail[]> {
  if (!slugs.length) return [];
  const results = await Promise.all(slugs.map((s) => getHospital(s)));
  return results.filter(Boolean) as HospitalDetail[];
}

export async function getAllHospitalSlugs(): Promise<string[]> {
  return data.hospitals.map((h) => h.slug);
}

export async function getCheckupCombos(): Promise<{ category: string; hospital_slug: string }[]> {
  // Priced rows only. A combo whose every package has a NULL price renders as
  // "Price on request" with an empty inclusion table — nothing a search engine
  // will index, and 6k of them were crowding the sitemap.
  const seen = new Set<string>();
  const out: { category: string; hospital_slug: string }[] = [];
  const closedSlugs = new Set(
    data.hospitals.filter((h) => h.permanently_closed).map((h) => h.slug),
  );
  for (const r of allRows) {
    const price = num(r.price);
    if (!r.category || price === null || price <= 0) continue;
    // Keeps closed businesses out of the sitemap: every sitemap section is
    // gated on this combo set.
    if (closedSlugs.has(r.hospital_slug)) continue;
    const key = `${r.category}::${r.hospital_slug}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push({ category: r.category, hospital_slug: r.hospital_slug });
  }
  return out;
}

export async function getRecentPriceChanges(limit = 20): Promise<PriceTrendRow[]> {
  // The SQL compared, for the single most recent snapshot date in the whole
  // table, each package's price against its own previous snapshot.
  let latestDate = "";
  for (const s of data.snapshots) {
    if (s.snapshot_date > latestDate) latestDate = s.snapshot_date;
  }
  if (!latestDate) return [];

  const packagesById = new Map<number, RawPackage>(data.packages.map((p) => [p.id, p]));
  const out: PriceTrendRow[] = [];

  for (const [packageId, snaps] of snapshotsByPackage) {
    const last = snaps[snaps.length - 1];
    if (!last || last.snapshot_date !== latestDate) continue;
    const prev = snaps[snaps.length - 2];
    if (!prev) continue;

    const latestPrice = num(last.price);
    const prevPrice = num(prev.price);
    if (latestPrice === null || prevPrice === null || prevPrice === 0) continue;
    if (latestPrice === prevPrice) continue;

    const pkg = packagesById.get(packageId);
    if (!pkg) continue;
    const hosp = hospitalsById.get(pkg.hospital_id);
    if (!hosp) continue;

    out.push({
      hospital_name: hosp.name,
      hospital_slug: hosp.slug,
      package_id: packageId,
      package_name: pkg.name,
      category: pkg.category,
      latest_price: latestPrice,
      prev_price: prevPrice,
      // ROUND(x, 1) in SQL.
      change_pct: Math.round(((latestPrice - prevPrice) / prevPrice) * 1000) / 10,
    });
  }

  return out
    .sort((a, b) => Math.abs(b.change_pct) - Math.abs(a.change_pct))
    .slice(0, limit);
}

export async function logClick(packageId: number, dest: string, ip: string): Promise<void> {
  // There is no longer a database to write to. The outbound URL already carries
  // utm_source/medium/campaign/content, so the destination's own analytics is
  // the system of record for these clicks; this line exists so the data is also
  // visible in Vercel's runtime logs (and any log drain) rather than vanishing.
  void ip; // deliberately not logged — it was only ever stored as an MD5 hash
  console.log(JSON.stringify({ event: "outbound_click", packageId, dest: dest.slice(0, 500) }));
}

export async function getStatsForHome(): Promise<{
  jciCount: number;
  packageCount: number;
  hospitalCount: number;
  cityCount: number;
}> {
  // Count what a visitor can actually see. `data.hospitals.length` includes
  // rows whose only listings were dropped as non-diagnostic, and
  // `data.packages.length` includes price-on-request rows — advertising those
  // in the hero counter is a number the site cannot show you.
  const priced = allRows.filter((r) => {
    const p = num(r.price);
    return p !== null && p > 0;
  });
  const hospitalsWithPrices = new Set(priced.map((r) => r.hospital_slug));
  const cities = new Set(priced.map((r) => r.city).filter((c): c is string => !!c));
  return {
    jciCount: data.hospitals.filter((h) => h.jci === 1).length,
    packageCount: priced.length,
    hospitalCount: hospitalsWithPrices.size,
    cityCount: cities.size,
  };
}

/** When export_to_json.py last ran. Surfaced on /trends and /about. */
export const DATA_GENERATED_AT = data.generated_at;
