/**
 * Hospital URLs Google still has indexed that no longer resolve.
 *
 * Search Console's 2026-08-25 export lists 211 distinct /:locale/hospital/:slug
 * URLs. Only 62 of them are still a page: the 2026-08 catalogue rebuild took
 * the site from 234 hospitals to 122 with a priced package, and every slug it
 * dropped became a hard 404 carrying real traffic — 74 clicks and 4,894
 * impressions over three months, which is a third of the site's clicks.
 *
 * The two maps below are different problems and are deliberately not merged.
 *
 * RENAMED is a true 1:1: the same business, re-slugged. `hdmall_insert.py`
 * re-created most of the HDmall catalogue with an "hdm-" prefix, so the slug
 * Google indexed lost its page while the hospital itself stayed on the site.
 * These 308 to the identical content and are pure recovery.
 *
 * MOVED_TO_GUIDE is a fallback, not an equivalence. The hospital genuinely is
 * not on the site any more, so the request goes to the city guide that covers
 * it — a page that answers "health check-up in <city>", which is what the
 * query behind these URLs almost always is. Bangkok hospitals and anything
 * without a city in the slug go to the hospital index instead, since that is
 * browsable. If one of these hospitals is ever restored, delete its line here:
 * a live page always beats a redirect.
 *
 * Generated from the Search Console export; do not hand-edit ordering.
 */

/** Old slug -> current slug of the same hospital. */
export const RENAMED_HOSPITALS: Record<string, string> = {
  "absolute-health-clinic": "hdm-absolute-health-clinic",
  "adam-wellness-clinic": "hdm-adam-wellness-clinic",
  "addlife-total-check-up-center": "hdm-addlife-total-check-up-center",
  "atgenes": "hdm-atgenes",
  "avanti-wellness": "hdm-avanti-wellness",
  "bangkok-anti-aging-center": "hdm-bangkok-anti-aging-center",
  "bangkok-cytogenetics-center": "hdm-bangkok-cytogenetics-center",
  "bangkok-medical-lab": "hdm-bangkok-medical-lab",
  "bangkok-sexual-health-center": "hdm-bangkok-sexual-health-center",
  "bangkok-sleep-center": "hdm-bangkok-sleep-center",
  "bangpakok-9-international-hospital": "bangpakok9",
  "bewellasiaco": "hdm-bewellasiaco",
  "biomed-microbiome-dna": "hdm-biomed-microbiome-dna",
  "body-adjust-wellness": "hdm-chirovedic-clinic",
  "bodylab-pilates": "hdm-bodylab-pilates",
  "botan-clinic": "hdm-botan-clinic",
  "bsr-healthcare": "hdm-bsr-healthcare",
  "btlab": "hdm-btlab",
  "checkgo-by-occicare": "hdm-checkgo-by-occicare",
  "cmc-wellness": "hdm-cmc-wellness",
  "divine-aesthetic-clinic": "hdm-divine-aesthetic-clinic",
  "dr-trin-wellness": "hdm-dr-trin-wellness",
  "drchen-surgery-hospital-international-center": "hdm-drchen-surgery-hospital-international-center",
  "drpunjai-clinic": "hdm-drpunjai-clinic",
  "geneus-dna": "hdm-geneus-dna",
  "glam-glow-wellness-centre": "hdm-glam-glow-wellness-centre",
  "harmony-life-center": "hdm-harmony-life-center",
  "health-focus-clinic": "hdm-health-focus-clinic",
  "high-life-clinic": "hdm-high-life-clinic",
  "hum-clinic": "hdm-hum-clinic",
  "id-life-clinic": "hdm-id-life-clinic",
  "infinity-clinic-by-dr-palm": "hdm-infinity-clinic-by-dr-palm",
  "innerheal-wellness": "hdm-innerheal-wellness",
  "jessica-clinic": "hdm-jessica-clinic",
  "kawintra-clinic": "hdm-kawintra-clinic",
  "life-balance-methodology": "hdm-life-balance-methodology",
  "m-clinic": "hdm-m-clinic",
  "mabella-clinic": "hdm-mabella-clinic",
  "me-center": "hdm-me-center",
  "medconsult-bangkok-medical-clinic": "hdm-medconsult-bangkok-medical-clinic",
  "medtopia-clinic": "hdm-medtopia-clinic",
  "memory-clinic": "hdm-memory-clinic",
  "menness-wellness": "hdm-menness-wellness",
  "mental-well-clinic": "hdm-mental-well-clinic",
  "mic-lab": "hdm-mic-lab",
  "mn-medical-clinic": "hdm-mn-medical-clinic",
  "mywelltality": "hdm-mywelltality",
  "patricia-clinic": "hdm-patricia-clinic",
  "pct-laboratory-services": "hdm-pct-laboratory-services",
  "prime-laboratory-bangkok": "hdm-prime-laboratory-bangkok",
  "r3-life-wellness-center": "hdm-r3-life-wellness-center",
  "raksa-physio": "hdm-raksa-physio",
  "regenelife-vital-center": "hdm-regenelife-vital-center",
  "s-mart-anti-aging-wellness-center": "hdm-s-mart-anti-aging-wellness-center",
  "semed-living-care-hospital": "hdm-semed-living-care-hospital",
  "sesh-clinic": "hdm-sesh-clinic",
  "soul-clinic": "hdm-soul-clinic",
  "spectrum-wellness": "hdm-spectrum-wellness",
  "stc-anti-aging-amp-wellness-clinic": "hdm-stc-anti-aging-wellness-clinic",
  "takara-ivf-bangkok": "hdm-takara-ivf-bangkok",
  "u-wellness-center": "hdm-u-wellness-center",
  "vanita-clinic": "hdm-vanita-clinic",
  "vital-glow-skin-amp-aesthetic": "hdm-vital-glow-skin-aesthetic",
  "w-medic": "hdm-w-medic",
  "welida-health": "hdm-welida-health",
  "yanhee-international-hospital": "yanhee-hospital",
  "yuva-wellness-center": "hdm-yuva-wellness-center",
};

/** Deleted hospital -> the live path (locale-relative) that best covers it. */
export const MOVED_TO_GUIDE: Record<string, string> = {
  "ayutthaya-hospital": "/guide/ayutthaya-health-checkup",
  "bangkok-hospital-ayutthaya": "/guide/ayutthaya-health-checkup",
  "bangkok-hospital-chon-buri": "/guide/chon-buri-health-checkup",
  "bangkok-hospital-hat-yai": "/guide/hat-yai-health-checkup",
  "bangkok-hospital-hua-hin": "/guide/hua-hin-health-checkup",
  "bangkok-hospital-khon-kaen": "/guide/khon-kaen-health-checkup",
  "bangkok-hospital-koh-chang": "/guide/koh-chang-health-checkup",
  "bangkok-hospital-korat": "/guide/korat-health-checkup",
  "bangkok-hospital-krabi": "/guide/krabi-health-checkup",
  "bangkok-hospital-lampang": "/guide/lampang-health-checkup",
  "bangkok-hospital-nakhon-si-thammarat": "/guide/nakhon-si-thammarat-health-checkup",
  "bangkok-hospital-phitsanulok": "/guide/phitsanulok-health-checkup",
  "bangkok-hospital-rayong": "/guide/rayong-health-checkup",
  "bangkok-hospital-samui": "/guide/koh-samui-health-checkup",
  "bangkok-hospital-surat-thani": "/guide/surat-thani-health-checkup",
  "bangkok-hospital-trang": "/guide/trang-health-checkup",
  "bangkok-hospital-trat-koh-chang": "/guide/koh-chang-health-checkup",
  "bangkok-nursing-home-hospital": "/hospital",
  "bangkok-pattaya-hospital": "/guide/pattaya-health-checkup",
  "banglamung-hospital-pattaya": "/guide/pattaya-health-checkup",
  "buddhachinaraj-hospital-phitsanulok": "/guide/phitsanulok-health-checkup",
  "camillian-hospital-rayong": "/guide/rayong-health-checkup",
  "chiang-rai-ram-hospital": "/guide/chiang-rai-health-checkup",
  "chon-buri-hospital": "/guide/chon-buri-health-checkup",
  "chonburi-hospital": "/guide/chon-buri-health-checkup",
  "chulalongkorn-hospital": "/hospital",
  "dibuk-hospital-phuket": "/guide/phuket-health-checkup",
  "happybirth-clinic": "/hospital",
  "hat-yai-hospital": "/guide/hat-yai-health-checkup",
  "hatyai-ramkhamhaeng-hospital": "/guide/hat-yai-health-checkup",
  "hdm-mei-house-clinic-(\u0e40\u0e21\u0e2d": "/hospital",
  "kasemrad-hospital": "/hospital",
  "kasemrad-hospital-ratchaburi": "/hospital",
  "kasemrad-international-hospital": "/hospital",
  "kasemrad-surat-thani-hospital": "/guide/surat-thani-health-checkup",
  "khelang-nakorn-lampang-hospital": "/guide/lampang-health-checkup",
  "khon-kaen-ram-hospital": "/guide/khon-kaen-health-checkup",
  "koh-chang-clinic": "/guide/koh-chang-health-checkup",
  "koh-chang-hospital": "/guide/koh-chang-health-checkup",
  "krabi-hospital": "/guide/krabi-health-checkup",
  "ladprao-hospital": "/hospital",
  "lampang-hospital": "/guide/lampang-health-checkup",
  "lampang-ruampaet-hospital": "/guide/lampang-health-checkup",
  "mae-fah-luang-university-hospital": "/guide/chiang-rai-health-checkup",
  "maharaj-nakhon-si-thammarat-hospital": "/guide/nakhon-si-thammarat-health-checkup",
  "maharat-nakhon-ratchasima-hospital": "/guide/korat-health-checkup",
  "nakhon-si-thammarat-ram-hospital": "/guide/nakhon-si-thammarat-health-checkup",
  "nakorn-lampang-hospital": "/guide/lampang-health-checkup",
  "nakornchaisri-hospital": "/guide/nakhon-pathom-health-checkup",
  "nakornping-hospital-chiang-mai": "/guide/chiang-mai-health-checkup",
  "nathon-hospital-ko-samui": "/guide/koh-samui-health-checkup",
  "nonthavej-hospital": "/hospital",
  "pagoda-hospital-samui": "/guide/koh-samui-health-checkup",
  "pakkred-infirmary-hospital": "/hospital",
  "pattaya-international-hospital": "/guide/pattaya-health-checkup",
  "phahon-yothin-hospital": "/hospital",
  "phitsanulok-ram-hospital": "/guide/phitsanulok-health-checkup",
  "phyathai-chonburi-hospital": "/guide/chon-buri-health-checkup",
  "phyathai-rayong-hospital": "/guide/rayong-health-checkup",
  "rajavithi-hospital": "/hospital",
  "ramathibodi-hospital": "/hospital",
  "ramindra-medical-center": "/hospital",
  "rutnin-hua-hin-hospital": "/guide/hua-hin-health-checkup",
  "samitivej-hospital-thonburi": "/hospital",
  "samui-international-hospital": "/guide/koh-samui-health-checkup",
  "samutprakarn-hospital": "/hospital",
  "san-paulo-hospital-hua-hin": "/guide/hua-hin-health-checkup",
  "siriraj-hospital": "/hospital",
  "songklanagarind-hospital-hat-yai": "/guide/hat-yai-health-checkup",
  "sri-udon-bhoom-hospital": "/guide/udon-thani-health-checkup",
  "srinagarind-hospital-khon-kaen": "/guide/khon-kaen-health-checkup",
  "surat-thani-hospital": "/guide/surat-thani-health-checkup",
  "synphaet-ramintra-hospital": "/hospital",
  "taksin-hospital": "/hospital",
  "taksin-hospital-surat-thani": "/guide/surat-thani-health-checkup",
  "thalang-hospital-phuket": "/guide/phuket-health-checkup",
  "the-rama-hospital-korat": "/guide/korat-health-checkup",
  "trang-hospital": "/guide/trang-health-checkup",
  "vejthani-hospital-pattaya": "/guide/pattaya-health-checkup",
  "vibhavadi-hospital-chon-buri": "/guide/chon-buri-health-checkup",
  "wattana-hospital-udon-thani": "/guide/udon-thani-health-checkup",
  "wattanavej-hospital": "/hospital",
};
