/**
 * Hospital URLs Google still has indexed that no longer resolve.
 *
 * Search Console's 2026-08-25 export lists 211 distinct /:locale/hospital/:slug
 * URLs, and only 62 of them were still a page: the 2026-08 catalogue rebuild
 * dropped every hospital without a priced package, and each dropped slug became
 * a hard 404 carrying real traffic — 74 clicks and 4,894 impressions a quarter,
 * about a third of the site's clicks.
 *
 * The two maps below are different problems and are deliberately not merged.
 *
 * RENAMED_HOSPITALS is a true 1:1: the same business, a different slug. Most
 * are the HDmall catalogue, which `hdmall_insert.py` re-created with an "hdm-"
 * prefix so the indexed slug lost its page while the hospital stayed on the
 * site. The rest come from re-scraping, where the name we searched for turned
 * out to differ from the hospital's real name — several of those searched
 * names were invented by the old city guides, and Google Maps answered with
 * the real hospital nearby. These 308 to identical content.
 *
 * MOVED_TO_GUIDE is a fallback, not an equivalence: the hospital is genuinely
 * not on the site, so the request goes to the city guide covering it, which
 * answers "health check-up in <city>" — the query behind these URLs. Bangkok
 * hospitals and slugs with no city go to the hospital index instead, since
 * that is browsable.
 *
 * Generated by apply_hospital_redirects.py. Do not hand-edit: restoring a
 * hospital has to remove its line from MOVED_TO_GUIDE, or the redirect runs in
 * middleware before routing and silently hides the page that was just added.
 */

/** Old slug -> current slug of the same hospital. */
export const RENAMED_HOSPITALS: Record<string, string> = {
  "absolute-health-clinic": "hdm-absolute-health-clinic",
  "adam-wellness-clinic": "hdm-adam-wellness-clinic",
  "addlife-total-check-up-center": "hdm-addlife-total-check-up-center",
  "atgenes": "hdm-atgenes",
  "avanti-wellness": "hdm-avanti-wellness",
  "ayutthaya-hospital": "phra-nakhon-si-ayutthaya-hospital",
  "bangkok-anti-aging-center": "hdm-bangkok-anti-aging-center",
  "bangkok-christian-hospital-nakhon-pathom": "bangkok-christian-nakhon-pathom-hospital",
  "bangkok-cytogenetics-center": "hdm-bangkok-cytogenetics-center",
  "bangkok-hospital-khon-kaen": "bangkok-hospital-khonkaen",
  "bangkok-hospital-koh-chang": "koh-chang-hospital",
  "bangkok-hospital-korat": "bangkok-hospital-ratchasima",
  "bangkok-hospital-surat": "bangkok-hospital-surat-thani",
  "bangkok-hospital-trat-koh-chang": "koh-chang-hospital",
  "bangkok-medical-lab": "hdm-bangkok-medical-lab",
  "bangkok-pattaya-hospital": "bangkok-hospital-pattaya",
  "bangkok-sanamchan-hospital": "bangkok-sanam-chan-hospital",
  "bangkok-sexual-health-center": "hdm-bangkok-sexual-health-center",
  "bangkok-sleep-center": "hdm-bangkok-sleep-center",
  "bangpakok-9-international-hospital": "bangpakok9",
  "bewellasiaco": "hdm-bewellasiaco",
  "biomed-microbiome-dna": "hdm-biomed-microbiome-dna",
  "body-adjust-wellness": "hdm-chirovedic-clinic",
  "bodylab-pilates": "hdm-bodylab-pilates",
  "botan-clinic": "hdm-botan-clinic",
  "bsr-healthcare": "hdm-bsr-healthcare",
  "btlab": "hdm-btlab",
  "buddhachinaraj-hospital-phitsanulok": "buddhachinaraj-hospital",
  "camillian-hospital-rayong": "camillian-social-center-rayong-csc-rayong",
  "checkgo-by-occicare": "hdm-checkgo-by-occicare",
  "chon-buri-hospital": "chonburi-hospital",
  "chulalongkorn-hospital": "king-chulalongkorn-memorial-hospital",
  "cmc-wellness": "hdm-cmc-wellness",
  "dibuk-hospital-phuket": "dibuk-hospital",
  "divine-aesthetic-clinic": "hdm-divine-aesthetic-clinic",
  "dr-trin-wellness": "hdm-dr-trin-wellness",
  "drchen-surgery-hospital-international-center": "hdm-drchen-surgery-hospital-international-center",
  "drpunjai-clinic": "hdm-drpunjai-clinic",
  "geneus-dna": "hdm-geneus-dna",
  "glam-glow-wellness-centre": "hdm-glam-glow-wellness-centre",
  "harmony-life-center": "hdm-harmony-life-center",
  "hat-yai-hospital": "hatyai-hospital",
  "health-focus-clinic": "hdm-health-focus-clinic",
  "high-life-clinic": "hdm-high-life-clinic",
  "hum-clinic": "hdm-hum-clinic",
  "id-life-clinic": "hdm-id-life-clinic",
  "infinity-clinic-by-dr-palm": "hdm-infinity-clinic-by-dr-palm",
  "innerheal-wellness": "hdm-innerheal-wellness",
  "jessica-clinic": "hdm-jessica-clinic",
  "kasemrad-hospital": "kasemrad-hospital-bang-khae",
  "kasemrad-hospital-ratchaburi": "kasemrad-hospital-bang-khae",
  "kasemrad-international-hospital": "kasemrad-hospital-bang-khae",
  "kawintra-clinic": "hdm-kawintra-clinic",
  "khelang-nakorn-lampang-hospital": "khelangnakorn-ram-hospital",
  "khelang-nakorn-ram-hospital": "khelangnakorn-ram-hospital",
  "koh-chang-clinic": "koh-chang-medical-clinic",
  "ladprao-hospital": "ladprao-general-hospital",
  "life-balance-methodology": "hdm-life-balance-methodology",
  "m-clinic": "hdm-m-clinic",
  "mabella-clinic": "hdm-mabella-clinic",
  "mae-fah-luang-university-hospital": "mae-fah-luang-university-medical-center-hospital",
  "me-center": "hdm-me-center",
  "medconsult-bangkok-medical-clinic": "hdm-medconsult-bangkok-medical-clinic",
  "medtopia-clinic": "hdm-medtopia-clinic",
  "memory-clinic": "hdm-memory-clinic",
  "menness-wellness": "hdm-menness-wellness",
  "mental-well-clinic": "hdm-mental-well-clinic",
  "mic-lab": "hdm-mic-lab",
  "mn-medical-clinic": "hdm-mn-medical-clinic",
  "mywelltality": "hdm-mywelltality",
  "nakhon-si-thammarat-ram-hospital": "maharaj-nakhon-si-thammarat-hospital",
  "nakornping-hospital-chiang-mai": "nakornping-hospital",
  "patricia-clinic": "hdm-patricia-clinic",
  "pct-laboratory-services": "hdm-pct-laboratory-services",
  "phahon-yothin-hospital": "phyathai-phaholyothin-hospital",
  "phitsanulok-ram-hospital": "bangkok-hospital-phitsanulok",
  "phyathai-chonburi-hospital": "phyathai-sriracha-hospital",
  "prime-laboratory-bangkok": "hdm-prime-laboratory-bangkok",
  "r3-life-wellness-center": "hdm-r3-life-wellness-center",
  "raksa-physio": "hdm-raksa-physio",
  "regenelife-vital-center": "hdm-regenelife-vital-center",
  "ruamphat-pitsanulok-hospital": "ruamphat-phitsanulok-hospital",
  "s-mart-anti-aging-wellness-center": "hdm-s-mart-anti-aging-wellness-center",
  "samitivej-hospital-thonburi": "samitivej-thonburi-hospital",
  "samutprakarn-hospital": "samut-prakan-hospital",
  "san-paulo-hospital-hua-hin": "san-paulo-hospital",
  "semed-living-care-hospital": "hdm-semed-living-care-hospital",
  "sesh-clinic": "hdm-sesh-clinic",
  "songklanagarind-hospital-hat-yai": "songklanagarind-hospital",
  "soul-clinic": "hdm-soul-clinic",
  "spectrum-wellness": "hdm-spectrum-wellness",
  "srinagarind-hospital-khon-kaen": "srinagarind-hospital",
  "stc-anti-aging-amp-wellness-clinic": "hdm-stc-anti-aging-wellness-clinic",
  "surat-thani-hospital": "suratthani-hospital",
  "takara-ivf-bangkok": "hdm-takara-ivf-bangkok",
  "taksin-hospital": "king-taksin-memorial-hospital",
  "thalang-hospital-phuket": "thalang-hospital",
  "u-wellness-center": "hdm-u-wellness-center",
  "vanita-clinic": "hdm-vanita-clinic",
  "vital-glow-skin-amp-aesthetic": "hdm-vital-glow-skin-aesthetic",
  "w-medic": "hdm-w-medic",
  "welida-health": "hdm-welida-health",
  "yanhee-international-hospital": "yanhee-hospital",
  "yuva-wellness-center": "hdm-yuva-wellness-center",
};

/** Deleted hospital -> the live path (locale-relative) that best covers it. */
export const MOVED_TO_GUIDE: Record<string, string> = {
  "bangkok-hospital-ayutthaya": "/guide/ayutthaya-health-checkup",
  "bangkok-hospital-chon-buri": "/guide/chon-buri-health-checkup",
  "bangkok-hospital-krabi": "/guide/krabi-health-checkup",
  "bangkok-hospital-lampang": "/guide/lampang-health-checkup",
  "bangkok-hospital-nakhon-si-thammarat": "/guide/nakhon-si-thammarat-health-checkup",
  "bangkok-hospital-trang": "/guide/trang-health-checkup",
  "bangkok-nursing-home-hospital": "/hospital",
  "banglamung-hospital-pattaya": "/guide/pattaya-health-checkup",
  "hatyai-ramkhamhaeng-hospital": "/guide/hat-yai-health-checkup",
  "hdm-mei-house-clinic-(\\u0e40\\u0e21\\u0e2d": "/hospital",
  "kasemrad-surat-thani-hospital": "/guide/surat-thani-health-checkup",
  "lampang-ruampaet-hospital": "/guide/lampang-health-checkup",
  "nakorn-lampang-hospital": "/guide/lampang-health-checkup",
  "nakornchaisri-hospital": "/guide/nakhon-pathom-health-checkup",
  "nathon-hospital-ko-samui": "/guide/koh-samui-health-checkup",
  "pagoda-hospital-samui": "/guide/koh-samui-health-checkup",
  "pakkred-infirmary-hospital": "/hospital",
  "phyathai-rayong-hospital": "/guide/rayong-health-checkup",
  "ramindra-medical-center": "/hospital",
  "rutnin-hua-hin-hospital": "/guide/hua-hin-health-checkup",
  "sri-udon-bhoom-hospital": "/guide/udon-thani-health-checkup",
  "taksin-hospital-surat-thani": "/guide/surat-thani-health-checkup",
  "the-rama-hospital-korat": "/guide/korat-health-checkup",
  "trang-hospital": "/guide/trang-health-checkup",
  "vejthani-hospital-pattaya": "/guide/pattaya-health-checkup",
  "vibhavadi-hospital-chon-buri": "/guide/chon-buri-health-checkup",
  "wattana-hospital-udon-thani": "/guide/udon-thani-health-checkup",
  "wattanavej-hospital": "/hospital",
};
