// Legacy district/city slug → canonical slug aliases.
// Historically lived entirely in public/_redirects, but Cloudflare Pages only
// honors the first 100 rules in that file — this project has 191, so 91 of
// them (including every /city/* alias) were silently dropped and 404ing in
// production despite looking correct in the source file. Moving the full
// tables here removes any rule-count ceiling: Functions have no such limit.
export const DISTRICT_ALIASES: Record<string, string> = {
  "ko-kha-district": "ko-kha",
  "mueang-tak-district": "mueang-tak",
  "khlong-luang-district": "khlong-luang",
  "chon-buri-district": "mueang-chon-buri",
  "bang-bo-district": "bang-bo",
  "mueang-buri-ram-district": "mueang-buri-ram",
  "bang-phli-district": "bang-phli",
  "mueang-samut-sakhon-district": "mueang-samut-sakhon",
  "bang-sao-thong-district": "bang-sao-thong",
  "phra-pradaeng-district": "phra-pradaeng",
  "amphur-muangsamutsakorn": "mueang-samut-sakhon",
  "thanyaburi-district": "thanyaburi",
  "mueang-pathum-thani-district": "mueang-pathum-thani",
  "si-racha-district": "si-racha",
  "bang-lamung-district": "bang-lamung",
  "ban-pong-district": "ban-pong",
  "phan-thong-district": "phan-thong",
  "krathum-baen-district": "krathum-baen",
  "ban-bueng-district": "ban-bueng",
  "pathumthani": "mueang-pathum-thani",
  "kanchanadit-district": "kanchanadit",
  "mueang-trat-district": "mueang-trat",
  "mae-sot-district": "mae-sot",
  "mueang-lop-buri-district": "mueang-lopburi",
  "sri-racha": "si-racha",
  "mueang-kanchanaburi-district": "mueang-kanchanaburi",
  "mueang-roi-et-district": "mueang-roi-et",
  "mueang-nakhon-pathom-district": "mueang-nakhon-pathom",
  "mueang-surat-thani-district": "mueang-surat-thani",
  "nong-yai-district": "nong-yai",
  "mueang-lamphun-district": "mueang-lamphun",
  "mueang-nakhon-si-thammarat-district": "mueang-nakhon-si-thammarat",
  "phanat-nikhom-district": "phanat-nikhom",
  "mueang-suphan-buri-district": "mueang-suphan-buri",
  "mueang-lampang-district": "mueang-lampang",
  "mueang-nong-khai-district": "mueang-nong-khai",
  "phunphin-district": "phunphin",
  "mueang-nakhon-sawan-district": "mueang-nakhon-sawan",
  "pluak-daeng-district": "pluak-daeng",
  "mueang-si-sa-ket-district": "mueang-si-sa-ket",
  "tha-muang-district": "tha-muang",
  "muang-district": "mueang-chon-buri",
  "mueang-surin-district": "mueang-surin",
  "mueang-mukdahan-district": "mueang-mukdahan",
  "huai-rat-district": "huai-rat",
  "muangchon-buri": "mueang-chon-buri",
  "mueang-phitsanulok-district": "mueang-phitsanulok",
  "bo-thong-district": "bo-thong",
  "sriracha": "si-racha",
  "phra-phutthabat-district": "phra-phutthabat",
  "sattahip-district": "sattahip",
  "khao-saming-district": "khao-saming",
  "nakhon-chai-si-district": "nakhon-chai-si",
  "phra-phrom-district": "phra-phrom",
  "kabin-buri-district": "kabin-buri",
  "อำเภอเมืองศรีราชา": "mueang-chon-buri",
  "amphur-panthong": "phan-thong",
  "hang-chat-district": "hang-chat",
  "thawat-buri-district": "thawat-buri",
  "mueang-sa-kaeo-district": "mueang-sa-kaeo",
  "banglamung": "bang-lamung",
  "pa-sang-district": "pa-sang",
  "watthana-nakhon-district": "watthana-nakhon",
  "panthong": "phan-thong",
  "ko-chan-district": "ko-chan",
  "phanthong": "phan-thong",
  "t.phanthong,-a.phanthong": "phan-thong",
  "srira": "si-racha",
  "chonburi": "mueang-chon-buri",
  "panusnikom": "phanat-nikhom",
  "muangchonburi": "mueang-chon-buri",
  "banbueng": "ban-bueng",
  "phantong": "phan-thong",
  "san-pa-tong-district": "san-pa-tong",
  "chon-buri": "mueang-chon-buri",
  "hangchat": "hang-chat",
  "uthumphon-phisai-district": "uthumphon-phisai",
  "lam-luk-ka-district": "lam-luk-ka",
  "sam-khok-district": "sam-khok",
  "lat-lum-kaeo-district": "lat-lum-kaeo",
  "bang-plee": "bang-phli",
  "phra-samut-chedi-district": "phra-samut-chedi",
  "bangsaotong": "bang-sao-thong",
  "อเมือง": "mueang-samut-sakhon",
  "krathumban": "krathum-baen",
  "pantong-district": "phan-thong",
  "nong-suea-district": "nong-suea",
  "bangsaothong": "bang-sao-thong",
  "mueng-samut-sakhon": "mueang-samut-sakhon",
  "bangplee-district": "bang-phli",
  "mueng": "mueang-samut-sakhon",
  "tungsukla-sriracha": "si-racha",
};

export const CITY_ALIASES: Record<string, string> = {
  chonburi: "chon_buri",
  srisaket: "si_sa_ket",
  suphanburi: "suphan_buri",
};
